### ISSUE TITLE
ValueError: Cannot process this value as an Image, it is of type: <class 'tuple'>

### ISSUE THREAD

**Issue by jmjuanico** [gradio-app/gradio#10042]
### Describe the bug

Tried gr.load("models/black-forest-labs/FLUX.1-schnell").launch() and sometimes it throws this error. It is not consistent as sometimes it generates the image and sometimes throws this error. I tried both in a local docker container and huggingface private space.

gradio==5.6.0
gradio_client==1.4.3

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 2028, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1834, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/site-packages/gradio/components/image.py", line 279, in postprocess
    saved = image_utils.save_image(value, self.GRADIO_CACHE, self.format)
  File "/usr/local/lib/python3.10/site-packages/gradio/image_utils.py", line 76, in save_image
    raise ValueError(
ValueError: Cannot process this value as an Image, it is of type: <class 'tuple'>

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
gr.load("models/black-forest-labs/FLUX.1-schnell").launch() 
```

### Screenshot

<img width="786" alt="image" src="https://github.com/user-attachments/assets/b59938a0-b666-4975-a1bc-599134a79617">

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 2028, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1834, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/site-packages/gradio/components/image.py", line 279, in postprocess
    saved = image_utils.save_image(value, self.GRADIO_CACHE, self.format)
  File "/usr/local/lib/python3.10/site-packages/gradio/image_utils.py", line 76, in save_image
    raise ValueError(
ValueError: Cannot process this value as an Image, it is of type: <class 'tuple'>
```

### System Info

```shell
gradio==5.6.0
gradio_client==1.4.3
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
My guess is that the underlying API is returning an error or something

**Comment by abidlabs** [comment]
Hi @jmjuanico I just tested your code snippet and I can't reproduce the error:

<img width="1123" alt="Image" src="https://github.com/user-attachments/assets/8e9740c0-f71a-4d91-beed-204aee64203e" />

Can you try with the latest version of `gradio`? Also, can you please make sure that you have access to https://huggingface.co/black-forest-labs/FLUX.1-schnell using your Hugging Face account as it is a gated model, and that you are logged in locally using the `huggingface-cli`?

**Comment by abidlabs** [comment]
Going to close for lack of follow up. We can reopen as needed
