### ISSUE TITLE
JSONDecodeError in gradio-client when an "output" contains special characters.

### ISSUE THREAD

**Issue by jeberger** [gradio-app/gradio#10133]
### Describe the bug

The Python version of `gradio_client` raises a JSONDecodeError exception when the server reply contains special characters.

The same application works fine when accessed from the browser.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import gradio_client as gc

def test():
    return "\x85"

demo = gr.Interface (fn = test, inputs = [], outputs = ["text"])
demo.launch (prevent_thread_lock = True, server_port = 7860)

client = gc.Client ("http://127.0.0.1:7860")
print (repr (client.predict (api_name = "/predict")))
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 5.1.0
gradio_client version: 1.4.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.6.2.post1
fastapi: 0.115.6
ffmpy: 0.4.0
gradio-client==1.4.0 is not installed.
httpx: 0.28.0
huggingface-hub: 0.26.3
jinja2: 3.1.4
markupsafe: 2.1.5
numpy: 2.1.3
orjson: 3.10.12
packaging: 24.2
pandas: 2.2.3
pillow: 10.4.0
pydantic: 2.10.3
pydub: 0.25.1
python-multipart: 0.0.19
pyyaml: 6.0.2
ruff: 0.8.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.15.0
typing-extensions: 4.12.2
urllib3: 2.2.3
uvicorn: 0.32.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.10.0
httpx: 0.28.0
huggingface-hub: 0.26.3
packaging: 24.2
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
I just tested this code, and just to be clear, it looks like its not really working in the UI either, right? When I click the Generate button, the textbox remains empty

**Comment by jeberger** [comment]
> I just tested this code, and just to be clear, it looks like its not really working in the UI either, right? When I click the Generate button, the textbox remains empty

That is expected, `\x85` is an unprintable control character. If you add some text before and after (e.g. `"before\x85after"`), you should see it in the text box.

**Comment by abidlabs** [comment]
Can you explain the reason for this a bit more? Why are you returning `\x85` from your function?

**Comment by jeberger** [comment]
This actually came up during fuzz testing. The `\x85` comes from user input that gets included in the output.

**Comment by BetterAndBetterII** [comment]
I also encounter this issue:

```python
if __name__ == '__main__':
    client = Client(api_url, verbose=False)

    prompt = """exihi h0 T0si s0exch (3) 
The term exch refers to the specific chemical exergy of the state points"""

    result = client.predict(query=prompt, history=[], api_name="/model_chat")
```

Exception:
```
Invalid JSON: data: {"msg":"process_generating","event_id":"fc4d441009084ab2b387ff181ad232a8","output":{"data":["",[["exihi h0 T0
Traceback (most recent call last):
  File "D:\Coding\Python\llmytt\.venv\Lib\site-packages\gradio_client\client.py", line 290, in stream_messages
    raise ValueError(f"Unexpected SSE line: '{line}'")
ValueError: Unexpected SSE line: 'si s0exch (3) \nThe term exch refers to the specific chemical exergy of the state points",""]]],"is_generating":true,"duration":0.09276962280273438,"average_duration":0.09300701183785824},"success":true}'
Traceback (most recent call last):
  File "D:\Coding\Python\llmytt\extract_text.py", line 65, in <module>
    result = client.predict(query=prompt, history=[], api_name="/model_chat")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\llmytt\.venv\Lib\site-packages\gradio_client\client.py", line 482, in predict
    ).result()
      ^^^^^^^^
  File "D:\Coding\Python\llmytt\.venv\Lib\site-packages\gradio_client\client.py", line 1519, in result
    return super().result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\llmytt\.venv\Lib\site-packages\gradio_client\client.py", line 1138, in _inner
    predictions = _predict(*data)
                  ^^^^^^^^^^^^^^^
  File "D:\Coding\Python\llmytt\.venv\Lib\site-packages\gradio_client\client.py", line 1244, in _predict
    result = self._sse_fn_v1plus(helper, event_id, self.protocol)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\llmytt\.venv\Lib\site-packages\gradio_client\client.py", line 1438, in _sse_fn_v1plus
    return utils.get_pred_from_sse_v1plus(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\llmytt\.venv\Lib\site-packages\gradio_client\utils.py", line 423, in get_pred_from_sse_v1plus
    raise exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Coding\Python\llmytt\.venv\Lib\site-packages\gradio_client\utils.py", line 539, in stream_sse_v1plus
    raise concurrent.futures.CancelledError()
concurrent.futures._base.CancelledError

```

I use a cleaner to clean my query, but not a good idea.

```python
def string_cleaner(s):
    return ''.join(b if ord(b) <= 127 else ' ' for b in s)
```
