### ISSUE TITLE
Python version is not 3.10+ in devcontainer

### ISSUE THREAD

**Issue by anirbanbasu** [gradio-app/gradio#10141]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Since the CONTRIBUTING guide (https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) says that Python version 3.10+ is highly recommended, it would be nice to have the devcontainer configured for that. Currently, it uses 3.9 on Debian 11 (see below)

https://github.com/gradio-app/gradio/blob/9a6ce6f6b089d94c06da0b8620f28967f39f8383/.devcontainer/devcontainer.json#L4

**Describe the solution you'd like**  
I expected that changing L4 of `devcontainer.json` to `"image": "mcr.microsoft.com/devcontainers/python:3.10",` would take care of the problem but it does not have any effect. After doing that, I still have `/usr/bin/python3` aliased to `/usr/bin/python3.9` and there is no 3.10.

**Additional context**  
Additional improvements, perhaps?
 - Running `apt-get update && apt-get upgrade` as part of the `postCreateCommand` as suggested by https://hub.docker.com/r/microsoft/devcontainers-python.

**Comment by abidlabs** [comment]
Thanks @anirbanbasu would you like to open a PR to fix this?

**Comment by anirbanbasu** [comment]
@abidlabs okay, I shall try.

I am very confused, though, why setting `"image": "mcr.microsoft.com/devcontainers/python:3.10",` does not download Python 3.10. Furthermore, I doubt the `postCreateCommand`s are running because neither `python` nor `pip` is available to `root` or `vscode` inside the container. Maybe, I am misunderstanding something.

**Comment by abidlabs** [comment]
I think that should do it, let me open a PR

**Comment by abidlabs** [comment]
Fixed via #10145 and #10146:

<img width="1445" alt="image" src="https://github.com/user-attachments/assets/bcc2aaef-ed96-40d7-bfeb-9769d8c2c8bb">

**Comment by anirbanbasu** [comment]
@abidlabs thanks for the PR. However, I have two persisting problems.

## First problem

My devcontainer creation failed from the gradio GitHub repository with the last few lines as follows.

```
2024-12-06 22:24:27.339Z: postCreateCommand failed with exit code 1. Skipping any further user-provided commands.

2024-12-06 22:24:27.341Z: Error: Command failed: /bin/sh -c export NODE_OPTIONS="--max-old-space-size=8192" && chmod +x scripts/install_gradio.sh scripts/install_test_requirements.sh scripts/build_frontend.sh && ./scripts/install_test_requirements.sh && ./scripts/install_gradio.sh  && ./scripts/build_frontend.sh
2024-12-06 22:24:27.341Z: {"outcome":"error","message":"Command failed: /bin/sh -c export NODE_OPTIONS=\"--max-old-space-size=8192\" && chmod +x scripts/install_gradio.sh scripts/install_test_requirements.sh scripts/build_frontend.sh && ./scripts/install_test_requirements.sh && ./scripts/install_gradio.sh  && ./scripts/build_frontend.sh","description":"The postCreateCommand in the devcontainer.json failed.","containerId":"42cf91d72c9cc0f8e7eee339066bb6b1f5d7ab98c9972a3d608fdfaddf56bfef"}
2024-12-06 22:24:27.342Z:     at b7 (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:235:130)
2024-12-06 22:24:27.342Z:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-12-06 22:24:27.342Z:     at async Am (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:4483)
2024-12-06 22:24:27.343Z:     at async Xw (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:3828)
2024-12-06 22:24:27.343Z:     at async $w (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:3032)
2024-12-06 22:24:27.344Z:     at async fa (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:2438)
2024-12-06 22:24:27.344Z:     at async mtA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:465:1534)
2024-12-06 22:24:27.344Z:     at async NH (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:465:964)
2024-12-06 22:24:27.345Z:     at async YtA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:482:3771)
2024-12-06 22:24:27.345Z:     at async eB (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:482:4886)
2024-12-06 22:24:27.351Z: devcontainer process exited with exit code 1

=================================================================================
2024-12-06 22:24:27.373Z: Finished configuring codespace.

```
See the full log attached.
[gradio-devcontainer-creation.log](https://github.com/user-attachments/files/18044416/gradio-devcontainer-creation.log)

Then, I forked the gradio repository to my own user space on GitHub and tried to create a devcontainer there, which also failed with the last few lines similar to the one above. [I show few more lines here.]

```
Building the frontend...
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your pnpm version is incompatible with "/workspaces/gradio".

Expected version: ~9.1.0
Got: 9.15.0

This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.

To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
[229502 ms] postCreateCommand failed with exit code 1. Skipping any further user-provided commands.

Error: Command failed: /bin/sh -c export NODE_OPTIONS="--max-old-space-size=8192" && chmod +x scripts/install_gradio.sh scripts/install_test_requirements.sh scripts/build_frontend.sh && ./scripts/install_test_requirements.sh && ./scripts/install_gradio.sh  && ./scripts/build_frontend.sh
{"outcome":"error","message":"Command failed: /bin/sh -c export NODE_OPTIONS=\"--max-old-space-size=8192\" && chmod +x scripts/install_gradio.sh scripts/install_test_requirements.sh scripts/build_frontend.sh && ./scripts/install_test_requirements.sh && ./scripts/install_gradio.sh  && ./scripts/build_frontend.sh","description":"The postCreateCommand in the devcontainer.json failed.","containerId":"7032618c1d8d925fd0b2c99bfa9a46193b57f1dcd591c48ea6fc2666274f2f1f"}
    at b7 (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:235:130)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Am (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:4483)
    at async Xw (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:3828)
    at async $w (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:3032)
    at async fa (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:227:2438)
    at async mtA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:465:1534)
    at async NH (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:465:964)
    at async YtA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:482:3771)
    at async eB (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:482:4886)
devcontainer process exited with exit code 1
```

Here's the full log again.
[gradio-devcontainer-userspace-creation.log](https://github.com/user-attachments/files/18044478/gradio-devcontainer-userspace-creation.log)


## Second problem

I was not clear about this but the error with the Python environment that I reported earlier was based on my attempt to create a devcontainer using Docker. That problem remains unsolved and I am perplexed as to why the Docker image specified for 3.10 is still configuring 3.9 in `/usr/bin/python3`.

## Potential solution

 - **First problem**: The devcontainer features configuration `"ghcr.io/devcontainers/features/node:1": {},` installs the latest LTS version since it is not specified (https://github.com/devcontainers/features/tree/main/src/node) while the expectation in the post create scripts is 9.1.0. Thus, either the features specification should constrain that version or the post create scripts should be modified to be able to work the the LTS version of Node.
 - **Second problem**: I have no idea! 😮

**Comment by anirbanbasu** [comment]
> **Second problem**: I have no idea!

Maybe Docker on my machine (Apple M1 Max) refuses to download the 3.10 image because the image is not made for `arm64/aarch64`. However, the image registry (https://hub.docker.com/r/microsoft/devcontainers-python) does mention these architectures.

<img width="1224" alt="Screenshot 2024-12-07 at 8 32 30" src="https://github.com/user-attachments/assets/d2201aa3-42ae-4b9a-8c06-5fb19ee14ab7">

**Comment by abidlabs** [comment]
Hi @anirbanbasu how are you creating the dev container? Is it using the GitHub codespace or something else?

**Comment by anirbanbasu** [comment]
@abidlabs I am using GitHub codespaces for this.

**Comment by anirbanbasu** [comment]
@abidlabs for the second problem, I am using Docker Desktop on macOS.

**Comment by anirbanbasu** [comment]
@abidlabs I have found a solution to the second problem but the first problem still remains. The last several lines from the devcontainer build on local Docker are as shown below. The error is very similar to the one on GitHub codespaces.

```
Building the frontend...
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your pnpm version is incompatible with "/workspaces/gradio".

Expected version: ~9.1.0
Got: 9.15.0

This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.

To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".

What's next:
    Try Docker Debug for seamless, persistent debugging tools in any container or image → docker debug e45f179b4f0d11d3acfde240c68d87d1df23b642c82bb4cc38610b6016bd73bc
    Learn more at https://docs.docker.com/go/debug-cli/
[143890 ms] postCreateCommand failed with exit code 1. Skipping any further user-provided commands.
[143891 ms] Error: Command failed: /bin/sh -c export NODE_OPTIONS="--max-old-space-size=8192" && chmod +x scripts/install_gradio.sh scripts/install_test_requirements.sh scripts/build_frontend.sh && ./scripts/install_test_requirements.sh && ./scripts/install_gradio.sh  && ./scripts/build_frontend.sh
[143891 ms]     at G7 (/Users/abasu/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/spec-node/devContainersSpecCLI.js:235:130)
[143892 ms]     at async tm (/Users/abasu/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/spec-node/devContainersSpecCLI.js:227:4483)
[143892 ms]     at async $w (/Users/abasu/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/spec-node/devContainersSpecCLI.js:227:3828)
[143892 ms]     at async em (/Users/abasu/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/spec-node/devContainersSpecCLI.js:227:3032)
[143892 ms]     at async GrA (/Users/abasu/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/spec-node/devContainersSpecCLI.js:666:2752)
[143892 ms]     at async LrA (/Users/abasu/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/spec-node/devContainersSpecCLI.js:665:8554)
[143892 ms]     at async /Users/abasu/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/spec-node/devContainersSpecCLI.js:482:1190
[143895 ms] Exit code 1
```

**Note** however, the original issue of Python version being 3.10 _has been **resolved**_. This is shown in the output below. Thank you.

```
vscode ➜ /workspaces/gradio $ python
Python 3.10.15 (main, Sep 27 2024, 21:42:47) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gradio as gr
>>> print(gr.__version__)
5.8.0
>>> quit()
```

**Comment by anirbanbasu** [comment]
@abidlabs a further note: changing the line https://github.com/gradio-app/gradio/blob/6645518a66e01ebcd2746626a4e2a14239172e76/package.json#L169

to `"pnpm": ">=9.1.0"` makes the aforementioned error go away.

Should I open a PR to fix this?

**Comment by abidlabs** [comment]
Really that's interesting. What about `"^9.1.0"`, does that work for you? Any 9.x minor release should be fine, but 10.x  may include breaking changes

**Comment by anirbanbasu** [comment]
> Really that's interesting. What about `"^9.1.0"`, does that work for you? Any 9.x minor release should be fine, but 10.x may include breaking changes

I understand @abidlabs. Yes, `"^9.1.0"` works too.

**Comment by abidlabs** [comment]
Sounds good feel free to open a PR!

**Comment by anirbanbasu** [comment]
@abidlabs done: https://github.com/gradio-app/gradio/pull/10154
