### ISSUE TITLE
gradio.exceptions.InvalidPathError: Cannot move /data/user/0/com.example.video.gardioapitest/cache/image2143670555563631404.jpg to the gradio cache dir because it was not uploaded by a user.

### ISSUE THREAD

**Issue by rufan-nativesol** [gradio-app/gradio#10231]
### Describe the bug

HI, I'm requesting to my space using HTTP request in android app, every things is working good with image url, but when I try the local file it's not working.
 here is the sample code:

`private fun fetchCardioData(image: Uri) = lifecycleScope.launch(Dispatchers.IO) {
        val file = File.createTempFile("image", ".jpg")
        contentResolver.openInputStream(image).use {
            file.outputStream().use { outputStream ->
                it?.copyTo(outputStream)
            }
        }
        val mediaType = "application/json".toMediaType()
        val body = """{
    "data": [
        {
            "path": "${file.path}",// URL works but local file is not working
            "meta": {"_type": "gradio.FileData"}
        },
        "",
        "best quality, extremely detailed",
        "longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality",
        1,
        768,
        512,
        20,
        9,
        0,
        0.1,
        0.1
    ]
}""".toRequestBody(mediaType)
        val request = Request.Builder()
            .url("https://private.space.base.url/gradio_api/call/mlsd")
            .post(body)
            .addHeader("Content-Type", "application/json")
            .addHeader("Authorization", "Bearer ....................................")
            .build()
        val response = client.newCall(request).execute()
        val responseData = response.body?.string()
        println(responseData)
        followGardioData(responseData)
    }`

when I request with the local file  this error show on the space log 

gradio.exceptions.InvalidPathError: Cannot move 

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/blocks.py", line 2011, in process_api
    inputs = await self.preprocess_data(
  File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/blocks.py", line 1694, in preprocess_data
    inputs_cached = await processing_utils.async_move_files_to_cache(
  File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/processing_utils.py", line 637, in async_move_files_to_cache
    return await client_utils.async_traverse(
  File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio_client/utils.py", line 1024, in async_traverse
    return await func(json_obj)
  File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/processing_utils.py", line 608, in _move_to_cache
    _check_allowed(payload.path, check_in_upload_folder)
  File "/home/user/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gradio/processing_utils.py", line 553, in _check_allowed
    raise InvalidPathError(msg)
gradio.exceptions.InvalidPathError: Cannot move /data/user/0/com.example.video.gardioapitest/cache/image2143670555563631404.jpg to the gradio cache dir because it was not uploaded by a user.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```kotlin
private fun fetchCardioData(image: Uri) = lifecycleScope.launch(Dispatchers.IO) {
        val file = File.createTempFile("image", ".jpg")
        contentResolver.openInputStream(image).use {
            file.outputStream().use { outputStream ->
                it?.copyTo(outputStream)
            }
        }
        val mediaType = "application/json".toMediaType()
        val body = """{
    "data": [
        {
            "path": "${file.path}",// URL works but local file is not working
            "meta": {"_type": "gradio.FileData"}
        },
        "",
        "best quality, extremely detailed",
        "longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality",
        1,
        768,
        512,
        20,
        9,
        0,
        0.1,
        0.1
    ]
}""".toRequestBody(mediaType)
        val request = Request.Builder()
            .url("https://private.space.base.url/gradio_api/call/mlsd")
            .post(body)
            .addHeader("Content-Type", "application/json")
            .addHeader("Authorization", "Bearer ....................................")
            .build()
        val response = client.newCall(request).execute()
        val responseData = response.body?.string()
        println(responseData)
        followGardioData(responseData)
    }
```

### System Info

```shell
Android Studio Ladybug | 2024.2.1 Patch 3
Build #AI-242.23339.11.2421.12700392, built on November 22, 2024
Runtime version: 21.0.3+-79915917-b509.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.0.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.intellij.marketplace (242.24335)
  dev.j-a.swift (1.2.1.368-242)
  com.karateca.jstoolbox (1.10)
  dev.polek.adbwifi (1.2.6)
  org.moe (1.5.4)
  com.jetbrains.kmm (0.8.3(242)-5)
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @rufan-nativesol can you please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by abidlabs** [comment]
Closing for lack of followup. Can open with a suitable repro.

**Comment by rufan-nativesol** [comment]
```
class MainActivity : ComponentActivity() {
    private val client = OkHttpClient.Builder()
        .connectTimeout(10, TimeUnit.SECONDS)
        .writeTimeout(10, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .build()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContent {
            GardioAPITestTheme {
                Scaffold(modifier = Modifier.fillMaxSize()) { innerPadding ->
                    Button(onClick = {
                        imagePicker.launch(PickVisualMediaRequest(ActivityResultContracts.PickVisualMedia.ImageOnly))
                    }, modifier = Modifier.padding(innerPadding)) {
                        Text("Select Image")
                    }
                }
            }
        }

    }

    private val imagePicker = registerForActivityResult(ActivityResultContracts.PickVisualMedia()) {
        it?.let {
            Log.d(TAG, "onCreate: $it")
            fetchCardioData(it)
        }
    }

    private fun fetchCardioData(image: Uri) = lifecycleScope.launch(Dispatchers.IO) {
        val file = File.createTempFile("image", ".jpg")
        contentResolver.openInputStream(image).use {
            file.outputStream().use { outputStream ->
                it?.copyTo(outputStream)
            }
        }
        val mediaType = "application/json".toMediaType()
        val body = """{
    "data": [
        {
            "path": "${file.path}",
            "meta": {"_type": "gradio.FileData"}
        },
        "",
        "best quality, extremely detailed",
        "longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality",
        1,
        768,
        512,
        20,
        9,
        0,
        0.1,
        0.1
    ]
}""".toRequestBody(mediaType)
        val request = Request.Builder()
            .url("https://davidhomebeam-controlneteasy.hf.space/gradio_api/call/mlsd")
            .post(body)
            .addHeader("Content-Type", "application/json")
            .addHeader("Authorization", "Bearer token")
            .build()
        val response = client.newCall(request).execute()
        val responseData = response.body?.string()
        println(responseData)
        followGardioData(responseData)
    }

    private fun followGardioData(responseData: String?) {
        val jsonObject = JSONObject(responseData ?: "")
        val id = jsonObject.getString("event_id")
        val request = Request.Builder()
            .get()
            .url("https://davidhomebeam-controlneteasy.hf.space/gradio_api/call/mlsd/$id")
            .addHeader("Authorization", "Bearer token")
            .addHeader("Content-Type", "text/event-stream; charset=utf-8")
            .build()
        client.newCall(request).enqueue(object : Callback {
            override fun onFailure(call: Call, e: IOException) {
                Log.e(TAG, "onFailure: ", e)
            }

            override fun onResponse(call: Call, response: Response) {
                val stream = response.body?.byteStream()
                stream?.let {
                    val streamReader = InputStreamReader(it)
                    streamReader.forEachLine { line ->
                        Log.d(TAG, "onResponse: $line")
                    }
                }
            }
        })
    }

    companion object {
        private const val TAG = "MainActivity"
    }
}
```

**Comment by rufan-nativesol** [comment]
Thank you so much for your patience, I have attached the complete code, that I'm using please check. If you need anything else, feel free to let me know.

**Comment by freddyaboulton** [comment]
Hi @rufan-nativesol ! You need to upload the local file to the server with `/upload` first. That is what the python client is doing that the bare API requests won't do for you automatically. You can also just upload the image to any remotely accessible URL as you have noted.

**Comment by slim71** [comment]
@freddyaboulton since this is the same issue I'm having, how to you upload the file when trying to use curl POST?

**Comment by freddyaboulton** [comment]
Hi @slim71 ! You can use a curl command like this:

```
curl -F "files=@<full-path-to-file>" http://<url>/gradio_api/upload
```
