### ISSUE TITLE
gr.Interface.load breaks for ruDALLE Gradio Spaces

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#1109]
### Describe the bug

The Gradio app for https://huggingface.co/spaces/multimodalart/rudalle/ works perfectly. However, when I load it with `gr.Interface.load("spaces/multimodalart/rudalle")` it breaks, giving me this error:

```
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/gradio/routes.py", line 269, in predict
    output = await run_in_threadpool(app.launchable.process_api, body, username)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/gradio/blocks.py", line 161, in process_api
    predictions = fn(*processed_input)
  File "app.py", line 16, in text2image_rudalle
    image = rudalle(text,aspect,model)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/gradio/interface.py", line 473, in __call__
    output = self.run_prediction(params, called_directly=True)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/gradio/interface.py", line 531, in run_prediction
    prediction = predict_fn(*processed_input)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/gradio/external.py", line 323, in fn
    output = result["data"]
KeyError: 'data'
```

### Reproduction

You can replicate this issue with: 
```
import gradio
rudalle = gr.Interface.load("spaces/multimodalart/rudalle")
image = rudalle("the painting of a racing car","Square","Surrealism")
```

### System Info

```shell
Gradio == 2.9.1
Linux
```

### Severity

blocker

**Comment by abidlabs** [comment]
This is now fixed! I just tested the following code and it worked:

```py
import gradio
rudalle = gr.Interface.load("spaces/multimodalart/rudalle")
image = rudalle("the painting of a racing car","Square","Surrealism")
```

Note that because of some model-internal issues, sometimes the inference step for this model fails but this is not due to anything Gradio related.
