### ISSUE TITLE
Gradio 2.9.0b9 does not work in Spaces

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1113]
### Describe the bug

If I try to use 2.9.0b9, it breaks in spaces when running any interface. 2.9.0b8 works fine.

```
/home/user/.local/lib/python3.8/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Cache at /home/user/app/gradio_cached_examples/log.csv not found. Caching now in 'gradio_cached_examples/' directory.
Traceback (most recent call last):
  File "app.py", line 6, in <module>
    iface = gr.Interface(fn=sketch_recognition, inputs="sketchpad", outputs="text").launch(cache_examples=False)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 504, in __init__
    cache_interface_examples(self)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/process_examples.py", line 45, in cache_interface_examples
    for example_id, _ in enumerate(interface.examples):
TypeError: 'NoneType' object is not iterable
```

### Reproduction

https://huggingface.co/spaces/osanseviero/broken_gradio

```py
import gradio as gr

def sketch_recognition(img):
  return "hello"

iface = gr.Interface(fn=sketch_recognition, inputs="sketchpad", outputs="text").launch()
```

### System Info

```shell
Spaces
```

### Severity

critical

**Comment by abidlabs** [comment]
Thanks @osanseviero, can confirm that this was an issue, but should be solved by upgrading to `gradio==2.9b11`
