### ISSUE TITLE
Microphone file input might not be valid wav file

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1117]
### Describe the bug

I have a script that uses `scipy.io.wavfile import read`  to read a `wav` file. Since I want users to be able to record themselves, I'm using `gr.inputs.Audio(source="microphone", type="filepath")`, but I get an error that indicates the file is not actually a valid `wav` file. 

### Reproduction

Here is an end-to-end minimal example https://colab.research.google.com/drive/1fVoqhmjk07Oq6Omj8khC_3b3LGRemEvp?usp=sharing

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 270, in predict
    session_state,
  File "/usr/local/lib/python3.7/dist-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.7/dist-packages/anyio/to_thread.py", line 29, in run_sync
    limiter=limiter)
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 271, in process_api
    predictions = block_fn.fn(*processed_input)
  File "/usr/local/lib/python3.7/dist-packages/gradio/interface.py", line 558, in <lambda>
    if len(self.output_components) == 1
  File "/usr/local/lib/python3.7/dist-packages/gradio/interface.py", line 706, in run_prediction
    prediction = predict_fn(*processed_input)
  File "<ipython-input-18-061a2456d566>", line 4, in inference
    sampling_rate, data = read(audio_path)
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/wavfile.py", line 267, in read
    file_size, is_big_endian = _read_riff_chunk(fid)
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/wavfile.py", line 168, in _read_riff_chunk
    "understood.".format(repr(str1)))
ValueError: File format b'\x1aE\xdf\xa3'... not understood.
```
```


### System Info

```shell
Gradio `2.9.0b9`, colab and spaces
```

### Severity

critical

**Comment by Frugile** [comment]
I encountered similar bug, when using [Speech Verification demo](https://huggingface.co/spaces/microsoft/unispeech-speaker-verification). It work's when using prerecorded samples, but using microphone recorded audio fails.
I downloaded the code and ran it locally, it gives an error at line `wav1, _ = apply_effects_file(path1, EFFECTS)`:
```bash
formats: can't open input file `/tmp/audiocyuip60n.wav': WAVE: RIFF header not found
Traceback (most recent call last):
...
RuntimeError: Error loading audio file: failed to open file /tmp/audiocyuip60n.wav
```
which suggests that tmp `wav` file is not valid

Whole code is available at [Huggingface Spaces -> app.py](https://huggingface.co/spaces/microsoft/unispeech-speaker-verification/blob/main/app.py)

## Minimum example:
```python
import gradio as gr
from torchaudio.sox_effects import apply_effects_file


def fn(path1):
    apply_effects_file(path1, [])
    return ""


inputs = [
    gr.inputs.Audio(
        source="microphone", type="filepath", optional=True, label="Record"
    ),
]
output = gr.outputs.HTML(label="")

interface = gr.Interface(fn=fn, inputs=inputs, outputs=output)
interface.launch()
```
Package versions: `gradio==2.9.4`, `torchaudio==0.11.0`

**Comment by Frugile** [comment]
I have checked above code with older versions of `gradio`. The newest version that works without error is `2.7.5.2`, so the `2.8.0` is first version where error ``formats: can't open input file `/tmp/audiocyuip60n.wav': WAVE: RIFF header not found`` occurs.

**Comment by mizoru** [comment]
Is there someone looking into this?

**Comment by ReneeYe** [comment]
same bug when loading the recorded audio input.
```
RuntimeError: Error loading audio file: failed to open file /tmp/audio284knjiy.wav
```
package version: ```gradio==3.0.2```.
