### ISSUE TITLE
Interpretations don't work on latest main branch 

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#1124]
### Describe the bug

I can't run the default interpretation for a simple app with a single numeric input and label output on the latest commit to main. 

### Reproduction

```python
import gradio as gr


def is_greater_than_50(num: int) -> bool:
    return num > 50


iface = gr.Interface(fn=is_greater_than_50, inputs="number",
                     outputs="label", interpretation="default")
iface.launch()
```

After hitting `Interpret`, server will throw the following exception and not render an interpretation

```
AttributeError: 'Interpretation' object has no attribute 'postprocess'
```

### Screenshot

![interpretation_bug](https://user-images.githubusercontent.com/41651716/165832607-b2b2625c-a388-44f2-b9e2-08675c308ab5.gif)

### Logs

```shell
(gradio-dev) freddy@DESKTOP-V50OCDE:~/sources/gradio-scripts$ python hello_world.py
Running on local URL:  http://127.0.0.1:7861/

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/freddy/sources/gradio/gradio/routes.py", line 247, in predict
    output = await run_in_threadpool(
  File "/home/freddy/miniconda3/envs/gradio-dev/lib/python3.9/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/freddy/miniconda3/envs/gradio-dev/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/freddy/miniconda3/envs/gradio-dev/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/freddy/miniconda3/envs/gradio-dev/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/freddy/sources/gradio/gradio/blocks.py", line 315, in process_api
    block.postprocess(predictions[i])
AttributeError: 'Interpretation' object has no attribute 'postprocess'
```
```


### System Info

```shell
On commit `6d0a6ccb83608e255e1b0ee83b2aa27d96b4c774`, on WSL
```

### Severity

critical

**Comment by Zaharah** [comment]
Hi, I am facing the same problem. The interpret button does not work for this demo https://huggingface.co/course/chapter9/6?fw=pt. 

Is there any update on this? Thanks.
