### ISSUE TITLE
Missing UI assets

### ISSUE THREAD

**Issue by hjl** [gradio-app/gradio#1221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Browser connects but displays empty white page, console output shows traceback error:

```
(torch111) hjl@HJLs-MacBook-Pro gradio % python demo/hello_world/run.py 
Running on local URL:  http://127.0.0.1:7860/

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/torch111/lib/python3.8/site-packages/starlette/responses.py", line 299, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
  File "/torch111/lib/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/torch111/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/torch111/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
FileNotFoundError: [Errno 2] No such file or directory: '/torch111/lib/python3.8/site-packages/gradio/templates/frontend/assets/index.0064653a.js'
```

### Reproduction

`python demo/hello_world/run.py`

### System Info

```shell
Gradio 2.9b26, MacOS 12.2.1 (x86), python 3.8.13, chrome 101.0.4951.54,

main @ a88c017f878a968b797e99c57ffabfee10850b1a
```

### Severity

critical

**Comment by hjl** [comment]
Looks like UI refactor has some missing paths?

**Comment by abidlabs** [comment]
Thanks @hjl! Can you try upgrading to `gradio==2.9b48` and see if you still get this error? We should have fixed all of the paths now.
