### ISSUE TITLE
[3.0b1 Issue] gr.Carousel() breaks with Blocks

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#1250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Both the front and the back-end of `gr.Carousel` don't work with Blocks. The front-end shows 1/0 outputs, while the backend throws this error even if the syntax is identical to what works `gr.Interface`:
```
Traceback (most recent call last):
  File "/home/poli/miniconda3/lib/python3.9/site-packages/gradio/routes.py", line 275, in predict
    output = await app.blocks.process_api(body, username, session_state)
  File "/home/poli/miniconda3/lib/python3.9/site-packages/gradio/blocks.py", line 365, in process_api
    block.postprocess(prediction_value)
  File "/home/poli/miniconda3/lib/python3.9/site-packages/gradio/components.py", line 3180, in postprocess
    raise ValueError("Unknown type. Please provide a list for the Carousel.")
ValueError: Unknown type. Please provide a list for the Carousel.
```

### Reproduction

```
import gradio as gr

def update(name):
    return(name,name)

demo = gr.Blocks()

with demo:
    gr.Markdown("Start typing below and then click **Run** to see the output.")
    inp = gr.Textbox(placeholder="What are your names?")
    btn = gr.Button("Run")
    out = gr.Carousel(label="Names",components=["text"])
        
    btn.click(fn=update, inputs=inp, outputs=out)

demo.launch()
```

### System Info

```shell
Gradio == 3.0b1
```

### Severity

annoyance

**Comment by apolinario** [comment]
It has been reported already on #1240
