### ISSUE TITLE
3.0.1 huggingface demo examples

### ISSUE THREAD

**Issue by Zengyf-CVer** [gradio-app/gradio#1304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@abidlabs @pngwn 

When I use gradio==3.0.1 in huggingface, I find that when using the `examples` parameter, the program has an error, When I don't use the `examples` parameter, the program is fine. **This error does not appear in local operation, but does appear in huggingface**.

My huggingface project: 
- https://huggingface.co/spaces/Zengyf-CVer/Gradio_YOLOv5_Det_v3
-  https://huggingface.co/spaces/Zengyf-CVer/Gradio_YOLOv5_Det_v3/tree/main

### Reproduction

Code:

```python
    # example image
    examples = [
        [
            "./img_example/bus.jpg",
            "cpu",
            "yolov5s",
            640,
            0.6,
            0.5,
            10,
            ["person", "bus"],
            ["label", "pdf"],],
        [
            "./img_example/giraffe.jpg",
            "cpu",
            "yolov5l",
            320,
            0.5,
            0.45,
            12,
            ["giraffe"],
            ["label", "pdf"],],
        [
            "./img_example/zidane.jpg",
            "cpu",
            "yolov5m",
            640,
            0.25,
            0.5,
            15,
            ["person", "tie"],
            ["pdf", "json"],],
        [
            "./img_example/Millenial-at-work.jpg",
            "cpu",
            "yolov5s6",
            1280,
            0.5,
            0.5,
            20,
            ["person", "chair", "cup", "laptop"],
            ["label", "pdf"],],]

    # interface
    gr.Interface(
        fn=yolo_det,
        inputs=inputs,
        outputs=outputs,
        title=title,
        description=description,
        article="",
        examples=examples,  # bug
        theme="seafoam",
        flagging_dir="run", # output directory
    ).launch(
        inbrowser=True, # Automatically open default browser
        show_tips=True, # Automatically display the latest features of gradio
    )

```

Bug:

```shell
Traceback (most recent call last):
  File "app.py", line 425, in <module>
    main(args)
  File "app.py", line 407, in main
    gr.Interface(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 423, in __init__
    cache_interface_examples(self)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/process_examples.py", line 51, in cache_interface_examples
    raise e
  File "/home/user/.local/lib/python3.8/site-packages/gradio/process_examples.py", line 48, in cache_interface_examples
    cache_logger.flag(prediction)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/flagging.py", line 130, in flag
    component.save_flagged(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/components.py", line 2240, in save_flagged
    dir, label, None if data is None else data[0]["data"], encryption_key
KeyError: 0
```

### System Info

```shell
gradio 3.0.1
ubuntu 20.04
chrome
```

### Severity

annoyance

**Comment by radames** [comment]
hi @Zengyf-CVer this is related to caching with File Component and it's also reported here #1138 
You can try your space without the File output just to double check or to make it work until we fix it. Thanks

**Comment by Zengyf-CVer** [comment]
@radames  Looking forward to your fix, thanks.
