### ISSUE TITLE
Getting error when using gradio for ML image classification

### ISSUE THREAD

**Issue by abdoul-Aziz-shara** [gradio-app/gradio#1331]
I did use gradio on image classification, It works for the past months.  And I have been trying to complete my ML senior year project by deploying it on gradio but I couldn't for the past 5 days. I desperately need this to work .   Please your help will be very much appreciated. 

**Its pneumonia detection project( Normal or pneumonia):** 

**Code:** 
```py
import gradio as gr
import numpy as np
from keras.models import load_model
from keras.preprocessing import image


# load the trained CNN model
cnn_model = keras.models.load_model("fine_tuning.keras")

def Normal_or_Pneumonia(img):
   img = img.reshape( -1, 180, 180,3 )
   prediction = cnn_model .predict(img).tolist()[0]
   CLASS_NAMES = ["NORMAL", "PNEUMONIA"]
   return {CLASS_NAMES[i]: prediction[i] for i in range(2)}

#set the user uploaded image as the input array
#match same shape as the input shape in the model

image_input = gr.inputs.Image( shape=(180, 180) ,invert_colors=False  ,   type="file"    )


#setup the interface
  iface = gr.Interface(
  fn = Normal_or_Pneumonia,
  inputs = image_input,
  outputs = gr.outputs.Label(),
)
iface.launch(share=True , debug = True)
```

Error:   
             Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 275, in predict
    output = await app.blocks.process_api(body, username, session_state)
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 274, in process_api
    predictions = await run_in_threadpool(block_fn.fn, *processed_input)
  File "/usr/local/lib/python3.7/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.7/dist-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.7/dist-packages/gradio/interface.py", line 501, in <lambda>
    if len(self.output_components) == 1
  File "/usr/local/lib/python3.7/dist-packages/gradio/interface.py", line 682, in run_prediction
    prediction = predict_fn(*processed_input)
  File "<ipython-input-74-57352bc43195>", line 11, in Normal_or_Pneumonia
    img = img.reshape( -1, 180, 180,3 )
  File "/usr/lib/python3.7/tempfile.py", line 615, in __getattr__
    a = getattr(file, name)
AttributeError: '_io.BufferedRandom' object has no attribute 'reshape'

**Comment by abidlabs** [comment]
Hi @abdoul-Aziz-shara the issue is that you are passing the input image as a file (since `type="file"`)

However, inside your function you are treating the image as an array. It should work if you instead change to `type="numpy"`

So in other words, make this line:
```py
image_input = gr.inputs.Image( shape=(180, 180) ,invert_colors=False  ,   type="file"    )
```

```py
image_input = gr.inputs.Image( shape=(180, 180) ,invert_colors=False  ,   type="numpy"    )
```

Please feel free to reopen if this does not solve the issue

**Comment by abdoul-Aziz-shara** [comment]
Hello @abidlabs , I replace it with the code you provided me but I still get this error?

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 275, in predict
    output = await app.blocks.process_api(body, username, session_state)
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 274, in process_api
    predictions = await run_in_threadpool(block_fn.fn, *processed_input)
  File "/usr/local/lib/python3.7/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.7/dist-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.7/dist-packages/gradio/interface.py", line 501, in <lambda>
    if len(self.output_components) == 1
  File "/usr/local/lib/python3.7/dist-packages/gradio/interface.py", line 682, in run_prediction
    prediction = predict_fn(*processed_input)
  File "<ipython-input-59-8bb821a6c2de>", line 12, in Normal_or_Pneumonia
    prediction = cnn_model .predict(img).tolist()[0]
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py", line 55, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnavailableError: Graph execution error:

2 root error(s) found.
  (0) UNAVAILABLE:   failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0:
:{"created":"@1652958363.112350786","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3124,"referenced_errors":[{"created":"@1652958363.112350302","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}
	 [[{{node model_3/dense_7/Sigmoid/_647}}]]
Additional GRPC error information from remote target /job:worker/replica:0/task:0/device:CPU:0:
:{"created":"@1652958363.148035506","description":"Error received from peer ipv4:10.14.95.90:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":" failed to connect to all addresses\nAdditional GRPC error information from remote target /job:localhost/replica:0/task:0:\n:{"created":"@1652958363.112350786","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3124,"referenced_errors":[{"created":"@1652958363.112350302","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}\n\t [[{{node model_3/dense_7/Sigmoid/_647}}]]","grpc_status":14}
  (1) UNAVAILABLE:  failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0:
:{"created":"@1652958363.112350786","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3124,"referenced_errors":[{"created":"@1652958363.112350302","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}
	 [[{{node model_3/dense_7/Sigmoid/_647}}]]
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1652958363.146787848","description":"Error received from peer ipv4:10.14.95.90:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"failed to connect to all addresses\nAdditional GRPC error information from remote target /job:localhost/replica:0/task:0:\n:{"created":"@1652958363.112350786","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3124,"referenced_errors":[{"created":"@1652958363.112350302","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}\n\t [[{{node model_3/dense_7/Sigmoid/_647}}]]","grpc_status":14}
	 [[model_3/resnet50/conv5_block2_3_conv/BiasAdd/ReadVariableOp/_592]]
0 successful operations.
0 derived errors ignored. [Op:__inference_predict_function_122161]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 275, in predict
    output = await app.blocks.process_api(body, username, session_state)
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 274, in process_api
    predictions = await run_in_threadpool(block_fn.fn, *processed_input)
  File "/usr/local/lib/python3.7/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.7/dist-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.7/dist-packages/gradio/interface.py", line 501, in <lambda>
    if len(self.output_components) == 1
  File "/usr/local/lib/python3.7/dist-packages/gradio/interface.py", line 682, in run_prediction
    prediction = predict_fn(*processed_input)
  File "<ipython-input-59-8bb821a6c2de>", line 12, in Normal_or_Pneumonia
    prediction = cnn_model .predict(img).tolist()[0]
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py", line 55, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnavailableError: Graph execution error:

failed to connect to all addresses
Additional GRPC error information from remote target /job:localhost/replica:0/task:0:
:{"created":"@1652958448.328754912","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3124,"referenced_errors":[{"created":"@1652958448.328753238","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}
	 [[{{node model_3/dense_7/Sigmoid/_647}}]]
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1652958448.339085913","description":"Error received from peer ipv4:10.14.95.90:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"failed to connect to all addresses\nAdditional GRPC error information from remote target /job:localhost/replica:0/task:0:\n:{"created":"@1652958448.328754912","description":"Failed to pick subchannel","file":"third_party/grpc/src/core/ext/filters/client_channel/client_channel.cc","file_line":3124,"referenced_errors":[{"created":"@1652958448.328753238","description":"failed to connect to all addresses","file":"third_party/grpc/src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}\n\t [[{{node model_3/dense_7/Sigmoid/_647}}]]","grpc_status":14}
	 [[model_3/resnet50/conv2_block2_2_bn/ReadVariableOp_1/_80]] [Op:__inference_predict_function_122161]

**Comment by abdoul-Aziz-shara** [comment]
Error from a different colab  notebook: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 275, in predict
    output = await app.blocks.process_api(body, username, session_state)
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 274, in process_api
    predictions = await run_in_threadpool(block_fn.fn, *processed_input)
  File "/usr/local/lib/python3.7/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.7/dist-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.7/dist-packages/gradio/interface.py", line 501, in <lambda>
    if len(self.output_components) == 1
  File "/usr/local/lib/python3.7/dist-packages/gradio/interface.py", line 682, in run_prediction
    prediction = predict_fn(*processed_input)
  File "<ipython-input-24-bb8dfa6c2168>", line 11, in Normal_or_Pneumonia
    prediction = model .predict(img).tolist()[0]
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py", line 55, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'TPUReplicatedInput' used by {{node input0}} with these attrs: [T=DT_INT32, index=0, is_mirrored_variable=false, N=8, is_packed=false]
Registered devices: [COMPOSITE, CPU, TPU, TPU_SYSTEM, XLA_CPU]
Registered kernels:
  <no registered kernels>

	 [[input0]] [Op:__inference_predict_function_87723]

**Comment by abidlabs** [comment]
Sorry I'm not sure what's happening here, but it looks like a TensorFlow error, not a gradio error? 

The best I can do is point you to examples of TensorFlow image classifiers that do work with Gradio. Take a look here: https://github.com/gradio-app/gradio/blob/main/demo/image_classifier/run.py

**Comment by abdoul-Aziz-shara** [comment]
Alright , thanks I will take a look at it.
