### ISSUE TITLE
Load huggingface spaces

### ISSUE THREAD

**Issue by Zengyf-CVer** [gradio-app/gradio#1335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@abidlabs @pngwn 

```python
import gradio as gr

demo = gr.Interface.load(name="spaces/Zengyf-CVer/Gradio_YOLOv5_Det_v3")

demo.launch()
```

### Reproduction

```shell
Fetching interface from: https://huggingface.co/spaces/Zengyf-CVer/Gradio_YOLOv5_Det_v3
Traceback (most recent call last):
  File "huggingface_demo.py", line 3, in <module>
    demo = gr.Interface.load(name="spaces/Zengyf-CVer/Gradio_YOLOv5_Det_v3")
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/gradio/interface.py", line 90, in load
    interface_info = load_interface(name, src, api_key, alias)
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/gradio/external.py", line 273, in load_interface
    interface_info = repos[src](name, api_key, alias)
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/gradio/external.py", line 319, in get_spaces_interface
    interface_info = interface_params_from_config(config)
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/gradio/external.py", line 281, in interface_params_from_config
    for component in config_dict["input_components"]
KeyError: 'input_components'
```

### System Info

```shell
gradio 3.0.2
ubuntu 20.04
chrome
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Thanks @Zengyf-CVer -- we are working on this issue. Let me close it since we will fix this as part of #1248
