### ISSUE TITLE
File cached examples not working

### ISSUE THREAD

**Issue by dawoodkhan82** [gradio-app/gradio#1339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

From Radames here (https://github.com/gradio-app/gradio/issues/1160). This space https://huggingface.co/spaces/radames/PIFu-Clothed-Human-Digitization. (the File Component still has a problem with the cached files)

### Reproduction

https://huggingface.co/spaces/radames/PIFu-Clothed-Human-Digitization

### System Info

```shell
Gradio version 3.0.2
```

### Severity

critical

**Comment by ags-dy** [comment]
I am also affected by this bug in gradio 3.0.5

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/process_examples.py", line 48, in cache_interface_examples
    cache_logger.flag(prediction)
  File "/usr/local/lib/python3.8/dist-packages/gradio/flagging.py", line 183, in flag
    with open(log_filepath, "a", newline="") as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'gradio_cached_examples/log.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/host_user/work/src/tests/integration_tests/src/integration_tests/tests/optimisation/optimise_collision_safety_margin.py", line 124, in <module>
    iface = gr.Interface(
  File "/usr/local/lib/python3.8/dist-packages/gradio/interface.py", line 420, in __init__
    cache_interface_examples(self)
  File "/usr/local/lib/python3.8/dist-packages/gradio/process_examples.py", line 50, in cache_interface_examples
    shutil.rmtree(CACHED_FOLDER)
  File "/usr/lib/python3.8/shutil.py", line 709, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 707, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: 'gradio_cached_examples'
```

**Comment by abidlabs** [comment]
Fixed now, thanks everyone!
