### ISSUE TITLE
Using Audio returns an error

### ISSUE THREAD

**Issue by nicolasshu** [gradio-app/gradio#137]
I have been trying to either use the microphone or upload an audio file, but it tends to output an error. I tried using the `spectrogram.py` demo. I tried uploading an audio file in `.wav` form, with a duration of 9:59, sampling frequency of 16kHz and bitrate of 256kbit/sec

```
/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/gradio/inputs.py:819: WavFileWarning: Chunk (non-data) not understood, skipping it.
  return scipy.io.wavfile.read(file_obj.name)
Test launch: spectrogram()... (8046,)
gradio_test.py:13: MatplotlibDeprecationWarning: shading='flat' when X and Y have the same dimensions as C is deprecated since 3.3.  Either specify the corners of the quadrilaterals with X and Y, or pass shading='auto', 'nearest' or 'gouraud', or set rcParams['pcolor.shading'].  This will become an error two minor releases later.
  plt.pcolormesh(times, frequencies, np.log10(spectrogram_data))
PASSED
Running locally at: http://127.0.0.1:7860/
To create a public link, set `share=True` in `launch()`.
Interface loading below...
<IPython.lib.display.IFrame object at 0x7fe400645510>
(9599616,)
[2021-03-23 12:07:27,942] ERROR in app: Exception on /api/predict/ [POST]
Traceback (most recent call last):
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2977, in _wait_cursor_for_draw_cm
    self.set_cursor(cursors.WAIT)
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 561, in set_cursor
    window.configure(cursor=cursord[cursor])
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/tkinter/__init__.py", line 1485, in configure
    return self._configure('configure', cnf, kw)
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/tkinter/__init__.py", line 1476, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
RuntimeError: main thread is not in main loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/gradio/networking.py", line 133, in predict
    prediction, durations = app.interface.process(raw_input)
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/gradio/interface.py", line 274, in process
    predictions[i]) for i, output_interface in enumerate(self.output_interfaces)]
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/gradio/interface.py", line 274, in <listcomp>
    predictions[i]) for i, output_interface in enumerate(self.output_interfaces)]
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/gradio/outputs.py", line 193, in postprocess
    out_y = processing_utils.encode_plot_to_base64(y)
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/gradio/processing_utils.py", line 33, in encode_plot_to_base64
    plt.savefig(output_bytes, format="png")
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/matplotlib/pyplot.py", line 843, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2217, in print_figure
    **kwargs)
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 406, in draw
    else nullcontext()):
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2980, in _wait_cursor_for_draw_cm
    self.set_cursor(self._lastCursor)
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 561, in set_cursor
    window.configure(cursor=cursord[cursor])
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/tkinter/__init__.py", line 1485, in configure
    return self._configure('configure', cnf, kw)
  File "/home/nickshu/anaconda3/envs/speech/lib/python3.7/tkinter/__init__.py", line 1476, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
RuntimeError: main thread is not in main loop
```

**Comment by aliabid94** [comment]
Hey Nicolasshu. I tried running spectogram.py with a large audio file and it ran fine. Looking at your error logs, it seems like the issue is somewhere with the tkinter and matplotlib, not with the audio (you can test this by trying to run an audio-only demo like reverse_audio.py).
Can you provide the versions of Gradio and matplotlib you are using?

**Comment by aliabid94** [comment]
Closed due to lack of response
