### ISSUE TITLE
The use of 'label' for Interface Outputs No Longer Works

### ISSUE THREAD

**Issue by fmegahed** [gradio-app/gradio#1399]
### Describe the bug

Hello,

I may have missed this in updated docs, but your old examples/demos for using scikit-learn type models with Gradio does not seem to work. 

**Link to your Old Titanic Example:** https://colab.research.google.com/drive/1xOU3sDHs7yZjuBosbQ8Zb2oc4BegfSFX?usp=sharing  

**Resulting App with No Output Shown:** https://15047.gradio.app/

Any suggestions?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Links are provided in the bug description

### System Info

```shell
Google Colab
```

### Severity

blocking all usage of gradio

**Comment by FarukOzderim** [comment]
I can confirm this it takes forever it to run, could it be an error about dataframe?

![image](https://user-images.githubusercontent.com/44067394/171172902-e8bb7908-78bc-4856-addd-fe44d9acb919.png)

Btw we don't have a run button in the interface, but it runs with changes in the input, is it expected @abidlabs and @aliabid94?

**Comment by FarukOzderim** [comment]
Running it locally, I got the stacktrace, it is similar to #1408 numpy not json parsable.
```

TypeError: Type is not JSON serializable: numpy.float64
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\fastapi\applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\fastapi\routing.py", line 251, in app
    response = actual_response_class(response_data, **response_args)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\responses.py", line 49, in __init__
    self.body = self.render(content)
  File "F:\SecondaryDownloads\git_repos\gradio\gradio\routes.py", line 43, in render
    return orjson.dumps(content)
TypeError: Type is not JSON serializable: numpy.float64
1
```

**Comment by aliabid94** [comment]
I thought we accepted numpy values, for now you can try to cast to an array of floats. Will fix.
