### ISSUE TITLE
 'Button' object has no attribute 'postprocess'

### ISSUE THREAD

**Issue by mizoru** [gradio-app/gradio#1404]
### Describe the bug

I'm trying to make the interface of my demo available in 2 languages, but when I return `gr.Button.update(value='...')` I get this error:
```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 281, in predict
    output = await app.blocks.process_api(body, username, session_state)
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 399, in process_api
    if prediction_value["value"] is not None
AttributeError: 'Button' object has no attribute 'postprocess'```

Other interface components update just fine.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr
from transformers import pipeline, AutoModelForCTC, Wav2Vec2Processor, Wav2Vec2ProcessorWithLM

MODELS = {
    "Tatar": {"model_id": "sammy786/wav2vec2-xlsr-tatar", "has_lm": False},
    "Chuvash": {"model_id": "sammy786/wav2vec2-xlsr-chuvash", "has_lm": False},
    "Bashkir": {"model_id": "AigizK/wav2vec2-large-xls-r-300m-bashkir-cv7_opt", "has_lm": True},
    "Erzya": {"model_id": "DrishtiSharma/wav2vec2-large-xls-r-300m-myv-v1", "has_lm": True}
    }
    
# CACHED_MODELS_BY_ID = {}
    
LANGUAGES = list(MODELS.keys())

def run(input_file, language, decoding_type):

    #logger.info(f"Running ASR {language}-{model_size}-{decoding_type} for {input_file}")

    model = MODELS.get(language, None)

    
    if decoding_type == "LM" and not model["has_lm"]:
        history.append({
            "error_message": f"LM not available for {language} language :("
        })
    else:

        # model_instance = AutoModelForCTC.from_pretrained(model["model_id"])
        model_instance = CACHED_MODELS_BY_ID.get(model["model_id"], None)
        if model_instance is None:
            model_instance = AutoModelForCTC.from_pretrained(model["model_id"])
            CACHED_MODELS_BY_ID[model["model_id"]] = model_instance

        if decoding_type == "LM":
            processor = Wav2Vec2ProcessorWithLM.from_pretrained(model["model_id"])
            asr = pipeline("automatic-speech-recognition", model=model_instance, tokenizer=processor.tokenizer, 
                           feature_extractor=processor.feature_extractor, decoder=processor.decoder)
        else:
            processor = Wav2Vec2Processor.from_pretrained(model["model_id"])
            asr = pipeline("automatic-speech-recognition", model=model_instance, tokenizer=processor.tokenizer, 
                           feature_extractor=processor.feature_extractor, decoder=None)

        transcription = asr(input_file, chunk_length_s=5, stride_length_s=1)["text"]

    return transcription

def update_interface(lang):
  if lang == 'Русский':
    languages = gr.Radio.update(label='Язык записи')
    audio =  gr.Audio.update(label='Скажите что-нибудь...')
    btn = gr.Button.update(value='Расшифровать')
    
  elif lang == 'English':
    languages = gr.Radio.update(label='Language')
    audio = gr.Audio.update(label='Say something...')
    btn = gr.Button.update(value='Transcribe')

  return languages, audio, btn

with gr.Blocks() as blocks:
  lang = gr.Radio(label="Выберите язык интерфейса / Interface language", choices=['Русский','English'])#, interactive=True)
  languages = gr.Radio(label="Language", choices=LANGUAGES)
  audio = gr.Audio(source="microphone", type="filepath", label="Скажите что-нибудь...")
  decoding = gr.Radio(label="Decoding type", choices=["greedy", "LM"])
  btn = gr.Button('Расшифровать')
  output = gr.Textbox()
  
  lang.change(fn=update_interface, inputs=[lang], outputs=[languages, audio, btn])
  btn.click(fn=run, inputs=[audio, languages, decoding], outputs=[output])

```

### System Info

```shell
gradio=3.0.6
```

### Severity

annoying

**Comment by abidlabs** [comment]
In addition, right now, button cannot be used as an output component in this way. It would be good to have a more descriptive error message or support this functionality. @aliabid94 maybe you can take this one?

**Comment by aliabid94** [comment]
Sure, I could see a user wanting to update a Button's configuration (e.g. label).  will take a look.
