### ISSUE TITLE
Cannot set non-JSON serializable value as the initial value of Variable

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#1408]
### Describe the bug

Non-JSON serializable value cannot be set as the initial value of Variable.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr
import numpy as np

with gr.Blocks() as demo:
    x = gr.Variable(value=np.arange(3))
demo.launch()
```

### System Info

```shell
gradio version 3.0.5
```

### Severity

serious, but I can work around it

**Comment by FarukOzderim** [comment]
Thx for the report @hysts, please also provide the stacktrace/logs next time.
It seems we can support python arrays but not numpy arrays. 

@aliabid94 you had made some changes with the Variable, WDYT about this issue? It seems it cannot create a TemplateResponse.
```

Traceback (most recent call last):
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\fastapi\applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\fastapi\routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "F:\SecondaryDownloads\git_repos\gradio\gradio\routes.py", line 177, in main
    return templates.TemplateResponse(
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\templating.py", line 90, in TemplateResponse
    return _TemplateResponse(
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\templating.py", line 34, in __init__
    content = template.render(context)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "F:\SecondaryDownloads\git_repos\gradio\gradio\templates\frontend\index.html", line 48, in top-level template code
    <script>window.gradio_config = {{ config | tojson }};</script>
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\jinja2\filters.py", line 1673, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\jinja2\utils.py", line 736, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
←[31mERROR←[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\fastapi\applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\fastapi\routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\fastapi\routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "F:\SecondaryDownloads\git_repos\gradio\gradio\routes.py", line 177, in main
    return templates.TemplateResponse(
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\templating.py", line 90, in TemplateResponse
    return _TemplateResponse(
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\starlette\templating.py", line 34, in __init__
    content = template.render(context)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "F:\SecondaryDownloads\git_repos\gradio\gradio\templates\frontend\index.html", line 48, in top-level template code
    <script>window.gradio_config = {{ config | tojson }};</script>
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\jinja2\filters.py", line 1673, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "F:\SecondaryDownloads\git_repos\gradio\venv\lib\site-packages\jinja2\utils.py", line 736, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable

```

**Comment by hysts** [comment]
> please also provide the stacktrace/logs next time.

Got it. Sorry about that.
Thanks for looking into this issue.

**Comment by abidlabs** [comment]
Is this related to #1399?

**Comment by FarukOzderim** [comment]
I think so:
![image](https://user-images.githubusercontent.com/44067394/174327940-aa087fc4-d3d8-493e-93b8-7a9c15df3cd3.png)
