### ISSUE TITLE
Gradio 3.0 cannot load interfaces from Gradio 2

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#1417]
### Describe the bug

Loading an interface of a Space that has <3 from a Space with Gradio 3.0 breaks

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/osanseviero/mix_match_gradio

### Logs

```shell
Fetching interface from: https://huggingface.co/spaces/mrm8488/GPT-J-6B
/home/user/.local/lib/python3.8/site-packages/gradio/deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
/home/user/.local/lib/python3.8/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Textbox, please remove them: {'default': ''}
  warnings.warn(
/home/user/.local/lib/python3.8/site-packages/gradio/interface.py:282: UserWarning: Currently, only the 'default' theme is supported.
  warnings.warn("Currently, only the 'default' theme is supported.")
Fetching interface from: https://huggingface.co/spaces/akhaliq/T0pp
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    iface2 = gr.Interface.load("spaces/akhaliq/T0pp")
  File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 90, in load
    return super().load(name=name, src=src, api_key=api_key, alias=alias, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 518, in load
    return external.load_blocks_from_repo(name, src, api_key, alias, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/external.py", line 34, in load_blocks_from_repo
    blocks: gradio.Blocks = factory_methods[src](name, api_key, alias, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/external.py", line 309, in get_spaces
    return get_spaces_blocks(model_name, config)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/external.py", line 349, in get_spaces_blocks
    return gradio.Blocks.from_config(config, fns)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 311, in from_config
    event_method(fn=fn, **dependency)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 471, in __exit__
    self.config = self.get_config_file()
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 440, in get_config_file
    "props": utils.delete_none(block.get_config())
  File "/home/user/.local/lib/python3.8/site-packages/gradio/components.py", line 3590, in get_config
    "components": [component.get_block_name() for component in self.components],
  File "/home/user/.local/lib/python3.8/site-packages/gradio/components.py", line 3590, in <listcomp>
    "components": [component.get_block_name() for component in self.components],
AttributeError: 'str' object has no attribute 'get_block_name'
```
```


### System Info

```shell
Google Chrome, Space using Gradio 3.0.9
```

### Severity

serious, but I can work around it

**Comment by FarukOzderim** [comment]
@abidlabs it seems there are errors with interface.load's legacy support. From the offline discussion:

> hmm, ok this should not happen. If the latest release cannot load a previous release then it is a bug.

**Comment by AK391** [comment]
also same error here https://huggingface.co/spaces/nagolinc/styleGanHuman_and_PIFu/discussions/1

**Comment by abidlabs** [comment]
This issue will be the end of me 😵

Can confirm the issue, working on a fix...

**Comment by satpalsr** [comment]
Hey @abidlabs, Just mentioning a similar error here.
```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 281, in predict
    output = await app.blocks.process_api(body, username, session_state)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 356, in process_api
    predictions = await run_in_threadpool(block_fn.fn, *processed_input)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/user/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 491, in <lambda>
    lambda *args: self.run_prediction(args)[0]
  File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 673, in run_prediction
    prediction = predict_fn(*processed_input)
  File "app.py", line 6, in predict
    output_image = interf(input_image)
TypeError: 'Blocks' object is not callable
```
[Reproduce with space](https://huggingface.co/spaces/satpalsr/CVSC-test)

**Comment by satpalsr** [comment]
@abidlabs I changed to 3.0.10. The issue persists. [space](https://huggingface.co/spaces/satpalsr/CVSC-test)

**Comment by freddyaboulton** [comment]
@satpalsr I think using `type='filepath'` will fix your space (at least it does for me in my space). I think the problem is this [assumption](https://github.com/gradio-app/gradio/blob/main/gradio/components.py#L1384) in the component serialization logic.

**Comment by abidlabs** [comment]
Yes, agree with @freddyaboulton's suggestion. We can probably do a better job inferring types of data in each component's `serialize()`, the same way we do it in the `postprocess()` methods.

**Comment by satpalsr** [comment]
Works. Thanks, @freddyaboulton and @abidlabs.
