### ISSUE TITLE
Reload mode throws Error about reload.app

### ISSUE THREAD

**Issue by nikky4D** [gradio-app/gradio#1493]
### Describe the bug

I would like to use the gradio app.py --reload  function. However, when called in VSCode terminal, using gradio testingGradio.py --reload, I get the following warning and error, and the page fails to load up the app: 

```
WARNING:  The --reload flag should not be used in production on Windows.
ERROR:    Error loading ASGI app. Attribute "--reload.app" not found in module "testingGradio".
```

I can load the app using python app.py.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Here is my code to reproduce:
```
import gradio as gr



def main():

    demo = gr.Blocks()


    with demo:
        gr.Markdown(
        """
        # Testing
        
        """ )
        with gr.Tabs():
            with gr.TabItem("Detection"):

                with gr.Row():
                    with gr.Column():
                        inputs_video = gr.Dropdown(choices = ['1', '2', '3'], value = '1', label = "Video Choice") ## List of videos
                        inputs_vidDisplay = gr.Video(format = "mp4", label="Input Video Choice")
                    outputs_video = gr.Video(format='mp4', label= 'Output Detection Video')
                        
                
        
            with gr.TabItem("Retrieval/Captioning"):
                with gr.Row():
                    image_input = gr.Image()
                    image_output = gr.Image()
                image_button = gr.Button("Flip")

        


    demo.launch()


    return

if __name__ == '__main__':

    main()
```

### Screenshot

![image](https://user-images.githubusercontent.com/7451106/172685331-2760c44c-291f-43fa-a820-460bf35bd6fb.png)

### Logs

```shell
WARNING:  The --reload flag should not be used in production on Windows.
ERROR:    Error loading ASGI app. Attribute "--reload.app" not found in module "detection.app".
WARNING:  StatReload detected file change in 'detection\app.py'. Reloading...
WARNING:  The --reload flag should not be used in production on Windows.
ERROR:    Error loading ASGI app. Attribute "--reload.app" not found in module "detection.app".
```

### System Info

```shell
Windows, VSCode, Gradio 3.0.13
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Hi @nikky4D it should be sufficient to put "gradio app.py", there is no need to add the "--reload" flag afterwards.

Can you try that and let us know if it works? We will work on documenting this!

**Comment by nikky4D** [comment]
I tried it but it does not work. Now, my error looks like this: 

```
Traceback (most recent call last):
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\http\client.py", line 1371, in getresponse
    response.begin()
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\http\client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\http\client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\site-packages\urllib3\connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\site-packages\urllib3\connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=7860): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nuzuegbunam\Documents\IAI_Coding\Gradio\testingGradio.py", line 228, in <module>
    main(args)
  File "C:\Users\nuzuegbunam\Documents\IAI_Coding\Gradio\testingGradio.py", line 220, in main
    demo.launch()
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\site-packages\gradio\blocks.py", line 777, in launch
    if is_colab or (_frontend and not networking.url_ok(self.local_url)):
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\site-packages\gradio\networking.py", line 187, in url_ok
    r = requests.head(url, timeout=3, verify=False)
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\site-packages\requests\api.py", line 102, in head
    return request('head', url, **kwargs)
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\nuzuegbunam\Anaconda3\envs\mdetr\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=7860): Read timed out. (read timeout=3)
```

**Comment by abidlabs** [comment]
Try changing your code as follows:

```py
import gradio as gr

demo = gr.Blocks()

with demo:
    gr.Markdown(
    """
    # Testing
    
    """ )
    with gr.Tabs():
        with gr.TabItem("Detection"):

            with gr.Row():
                with gr.Column():
                    inputs_video = gr.Dropdown(choices = ['1', '2', '3'], value = '1', label = "Video Choice") ## List of videos
                    inputs_vidDisplay = gr.Video(format = "mp4", label="Input Video Choice")
                outputs_video = gr.Video(format='mp4', label= 'Output Detection Video')
                    
            
    
        with gr.TabItem("Retrieval/Captioning"):
            with gr.Row():
                image_input = gr.Image()
                image_output = gr.Image()
            image_button = gr.Button("Flip")


if __name__ == '__main__':
    demo.launch()

```

Does this work for you?

**Comment by nikky4D** [comment]
Thanks it works.

**Comment by abidlabs** [comment]
Great!
