### ISSUE TITLE
Could not find 'data' key in response from external Space.

### ISSUE THREAD

**Issue by nagolinc** [gradio-app/gradio#1516]
### Describe the bug

When calling interface 

code:

```
def generate_model(img):

    print("about to die")
    iface = gr.Interface.load("spaces/radames/PIFu-Clothed-Human-Digitization")
    print("calling interface")
    model,file=iface.fns[0].fn(img)
    print("got result",result)
    return model,file
```

result:

```Fetching interface from: https://huggingface.co/spaces/radames/PIFu-Clothed-Human-Digitization
/home/user/.local/lib/python3.8/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Model3D, please remove them: {'clearColor': [0.0, 0.0, 0.0, 0.0]}
  warnings.warn(
calling interface
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/external.py", line 335, in fn
    output = result["data"]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 281, in predict
    output = await app.blocks.process_api(body, username, session_state)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 356, in process_api
    predictions = await run_in_threadpool(block_fn.fn, *processed_input)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/user/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "app.py", line 26, in generate_model
    model,file=iface.fns[0].fn(img)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/external.py", line 337, in fn
    raise KeyError(
KeyError: "Could not find 'data' key in response from external Space. Response received: {'error': 'list index out of range'}"```


### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/nagolinc/styleGanHuman_and_PIFu

### Screenshot

_No response_

### Logs

```shell
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 255, in run_predict
    output = await app.blocks.process_api(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 538, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 452, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "app.py", line 26, in generate_model
    model,file=iface.fns[0].fn(img)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/external.py", line 337, in fn
    raise KeyError(
KeyError: "Could not find 'data' key in response from external Space. Response received: {'error': 'list index out of range'}"
Fetching interface from: https://huggingface.co/spaces/hysts/StyleGAN-Human
about to die
Fetching interface from: https://huggingface.co/spaces/radames/PIFu-Clothed-Human-Digitization
/home/user/.local/lib/python3.8/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Model3D, please remove them: {'clearColor': [0.0, 0.0, 0.0, 0.0]}
  warnings.warn(
calling interface
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/external.py", line 335, in fn
    output = result["data"]
KeyError: 'data'
```

### System Info

```shell
sdk: gradio
sdk_version: 3.0.13
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @nagolinc this is now fixed in `main` and will be released to `pypi` shortly. The way to use it would be like this:

```py
iface = gr.Interface.load("spaces/radames/PIFu-Clothed-Human-Digitization")
model, file=iface(img)
```
