### ISSUE TITLE
Putting File component examples in Gradio Interfaces

### ISSUE THREAD

**Issue by merveenoyan** [gradio-app/gradio#1531]
### Describe the bug

You cannot enter File component examples in Interfaces. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Below is my interface:

```
import pandas_profiling as pp
from huggingface_hub.hf_api import create_repo, upload_file
import gradio as gr
import pandas as pd
import subprocess
import os
import tempfile

token = gr.Textbox(label = "Your Hugging Face Token")
username = gr.Textbox(label = "Your Hugging Face User Name")
dataset_name = gr.Textbox(label = "Dataset Name")
dataset = gr.File(label = "Dataset")
output_text = gr.Textbox(label = "Status")
example_file = gr.File(value = "./auto-mpg.csv", label = "Auto MPG Dataset")
examples = [[example_file]]

def profile_dataset(dataset, username, token, dataset_name):

    df = pd.read_csv(dataset.name)
    profile = pp.ProfileReport(df, title=f"{dataset_name} Report")
    
    repo_url = create_repo(f"{username}/{dataset_name}", repo_type = "space", token = token, space_sdk = "static", private=False)
    
    profile.to_file("./index.html")
    upload_file(path_or_fileobj ="./index.html", path_in_repo = "index.html", repo_id =f"{username}/{dataset_name}", repo_type = "space", token=token)
    
    
    
    return f"Your dataset report will be ready at {repo_url}"

gr.Interface(profile_dataset,  title = title, description = description, inputs = [dataset, username, token, dataset_name], outputs=[output_text], enable_queue = True).launch(debug=True)
```

### Logs

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/routes.py", line 177, in main
    return templates.TemplateResponse(
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/templating.py", line 98, in TemplateResponse
    return _TemplateResponse(
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/templating.py", line 37, in __init__
    content = template.render(context)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/templates/frontend/index.html", line 38, in top-level template code
    <script>window.gradio_config = {{ config | tojson }};</script>
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/jinja2/filters.py", line 1688, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/jinja2/utils.py", line 658, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/opt/anaconda3/envs/py39/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/opt/anaconda3/envs/py39/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/anaconda3/envs/py39/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/anaconda3/envs/py39/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type File is not JSON serializable
Traceback (most recent call last):
  File "/Users/mervenoyan/Desktop/dataset-profiling/dataset_profiling/app.py", line 34, in <module>
    gr.Interface(profile_dataset, examples = examples, title = title, description = description, inputs = [dataset, username, token, dataset_name], outputs=[output_text], enable_queue = True).launch(debug=True)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/blocks.py", line 779, in launch
```

### System Info

```shell
(py39) ➜  dataset_profiling git:(main) ✗ pip3 freeze | grep gradio
gradio==3.0.13
```

### Severity

annoying

**Comment by Ian-GL** [comment]
Is it expected that examples support components? I thought it was expecting only the values. When entering only the path of the file it works fine.

`examples = [["./auto-mpg.csv", "YOUR_USERNAME", "YOUR_TOKEN",  "Auto MPG Dataset"]]`

Changing it to the above makes the code work for me.

**Comment by abidlabs** [comment]
Thanks @Ian-GL, you're right, `examples` is only supposed to support values as strings. 

@merveenoyan does this solve your use case or is there is still a need to put file components?

**Comment by abidlabs** [comment]
Closing as I think we are good here! @merveenoyan feel free to reopen if there's a use case that we're missing here.
