### ISSUE TITLE
function does not work within gradio

### ISSUE THREAD

**Issue by szm0020** [gradio-app/gradio#155]
Hello,

I have written a function that involves pandas operations. At some point, I want to assign the value of the first row of a column to a new variable. When I run the function outside of gradio, there is no problem. Inside gradio, I keep getting "IndexError: index 0 is out of bounds for axis 0 with size 0".

So the function is running fine and I can print the dataframe (it not empty). What could be the reason it does not work inside gradio?

Thanks

**Comment by abidlabs** [comment]
Hi @szm0020 that seems pretty strange to me. Would you be able to share the code so that we can try to look into it ourselves?

**Comment by szm0020** [comment]
Hi @abidlabs 
The code is large but this is the part that causes the issue:

--------------------------------------------------------

f = {'Y':['min','mean']}
setdf1=fin1.groupby(['varA', "varB"], as_index = False).agg(f)
sortdf2=setdf1.sort_values(by=[('Y', 'max'), ('Y', 'min')], ascending=False, inplace=False)
sortdf2.columns = sortdf2.columns.get_level_values(0)
maxcy2=sortdf2['varB'].values[0]

---------------------------------------------------------

And this the the entire error:

[2021-04-22 09:59:08,016] ERROR in app: Exception on /api/predict/ [POST]
Traceback (most recent call last):
  File "C:\Users\szm0020\anaconda3\envs\tf\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\szm0020\anaconda3\envs\tf\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\szm0020\anaconda3\envs\tf\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\szm0020\anaconda3\envs\tf\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\szm0020\anaconda3\envs\tf\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\szm0020\anaconda3\envs\tf\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\szm0020\anaconda3\envs\tf\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\szm0020\anaconda3\envs\tf\lib\site-packages\gradio\networking.py", line 133, in predict
    prediction, durations = app.interface.process(raw_input)
  File "C:\Users\szm0020\anaconda3\envs\tf\lib\site-packages\gradio\interface.py", line 272, in process
    predictions, durations = self.run_prediction(processed_input, return_duration=True)
  File "C:\Users\szm0020\anaconda3\envs\tf\lib\site-packages\gradio\interface.py", line 246, in run_prediction
    prediction = predict_fn(*processed_input)
  File "<ipython-input-3-6314fcaabf56>", line 277, in greet
    maxcy2=sortdf2['varB'].values[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

It is weird that the 'greet' function alone (outside of gradio) works fine. I am a beginner programmer so there might be an obvious issue and solution.
Thanks again

**Comment by abidlabs** [comment]
Hi @szm0020 I will need more information. If it's possible to share a colab notebook with the full code (or some smaller code that throws the same error), that would be helpful. In the meantime, consider looking at:

- Does the value of `sortdf2['varB']` change depending on whether the function is running in/out of gradio
- What are the inputs/outputs to your function? Trying printing them to make sure they are what you expect

**Comment by szm0020** [comment]
Hi @abidlabs
Thank you for your comments, I was able to find what I had to change in my function to make it work within Gradio. Your comments/suggestions helped me a lot and now it works fine.
Thanks again
