### ISSUE TITLE
Unable to show output on Gradio

### ISSUE THREAD

**Issue by sa92leh-fs** [gradio-app/gradio#1582]
### Describe the bug

I keep getting the following error (ValueError: Attempt to convert a value (<PIL.Image.Image image mode=RGB size=640x480 at 0x7F412D85B750>) with an unsupported type (<class 'PIL.Image.Image'>) to a Tensor.)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

The model is simple

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 256, in run_predict
    fn_index, raw_input, username, session_state
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 544, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 459, in call_function
    block_fn.fn, *processed_input, limiter=self.limiter
  File "/usr/local/lib/python3.7/dist-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.7/dist-packages/gradio/interface.py", line 510, in <lambda>
    else self.run_prediction(args)
  File "/usr/local/lib/python3.7/dist-packages/gradio/interface.py", line 712, in run_prediction
    prediction = predict_fn(*processed_input)
  File "<ipython-input-39-9ba4bc0e479e>", line 5, in crowd
    results = detect_objects(input_img, detector)
  File "<ipython-input-12-caf71360a9f8>", line 20, in detect_objects
    tf.io.read_file(path), channels=3)[tf.newaxis, ...]
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/io_ops.py", line 133, in read_file
    return gen_io_ops.read_file(filename, name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 567, in read_file
    filename, name=name, ctx=_ctx)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 586, in read_file_eager_fallback
    filename = _ops.convert_to_tensor(filename, _dtypes.string)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/profiler/trace.py", line 183, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 1695, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/constant_op.py", line 343, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/constant_op.py", line 268, in constant
    allow_broadcast=True)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/constant_op.py", line 279, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/constant_op.py", line 304, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value (<PIL.Image.Image image mode=RGB size=640x480 at 0x7F412D85B750>) with an unsupported type (<class 'PIL.Image.Image'>) to a Tensor.
```

### System Info

```shell
I'm working on Google Colab
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @sa92leh-fs can you please share the code that is causing this error? Without seeing that, my guess is that the `type` of the `Image` component you are using should be `numpy` but it is instead `pil`.

**Comment by sa92leh-fs** [comment]
def reconstruct_path(image_id: int) -> str:
    """Function transforms numerical image ID
    into a relative file path filling in leading zeros
    and adding file extension and directory.
    :param image_id: Image ID
    :return: Relative path to the image
    """
    image_id = str(image_id).rjust(6, '0')
    return f'../content/frames/frames/seq_{image_id}.jpg'


def detect_objects(path: str, model) -> dict:
    """Function extracts image from a file, adds new axis
    and passes the image through object detection model.
    :param path: File path
    :param model: Object detection model
    :return: Model output dictionary
    """
    image_tensor = tf.image.decode_jpeg(
        tf.io.read_file(path), channels=3)[tf.newaxis, ...]
    return model(image_tensor)


def count_persons(path: str, model, threshold=0.) -> int:
    """Function counts the number of persons in an image
    processing "detection_classes" output of the model
    and taking into account confidence threshold.
    :param path: File path
    :param model: Object detection model
    :param threshold: Threshold for confidence scores
    :return: Number of people for one image
    """
    results = detect_objects(path, model)
    # Class ID 1 = "person"
    return (results['detection_classes'].numpy()[0] == 1)[np.where(
        results['detection_scores'].numpy()[0] > threshold)].sum()


def draw_bboxes(image_path, data: dict, threshold=0.) -> PIL.Image:
    """Function displays an image with bounding boxes
    overlaid for every detected person.
    :param image_path: File path to an image
    :param data: Output of objects detection model for this image
    :param threshold: Threshold for confidence scores
    :return: PIL.Image object
    """
    image = PIL.Image.open(image_path)
    draw = Draw(image)

    im_width, im_height = image.size

    boxes = data['detection_boxes'].numpy()[0]
    classes = data['detection_classes'].numpy()[0]
    scores = data['detection_scores'].numpy()[0]

    for i in range(int(data['num_detections'][0])):
        if classes[i] == 1 and scores[i] > threshold:
            ymin, xmin, ymax, xmax = boxes[i]
            (left, right, top, bottom) = (xmin * im_width, xmax * im_width,
                                          ymin * im_height, ymax * im_height)
            draw.line([(left, top), (left, bottom), (right, bottom), (right, top), (left, top)],
                      width=4, fill='blue')

    return image

def set_display():
    """Function sets display options for charts and pd.DataFrames.
    """
    # Plots display settings
    plt.style.use('fivethirtyeight')
    plt.rcParams['figure.figsize'] = 12, 8
    plt.rcParams.update({'font.size': 14})
    # DataFrame display settings
    pd.set_option('display.max_columns', None)
    pd.set_option('display.max_rows', None)
    pd.options.display.float_format = '{:.4f}'.format



import numpy as np
import gradio as gr
input=gr.inputs.Image(shape=(200, 200))
def crowd(input_img): 
    results = detect_objects(input_img, detector)
    count=count_persons(input_img, detector, threshold=0.25)
    final_img=draw_bboxes(input_img, results,threshold=0.25)
    print(count)
    return final_img
demo = gr.interface.Interface(fn=crowd,inputs="image",outputs=["image","text"],
      capture_session=True,
      interpretation="default",layout="horizontal",
    allow_flagging=False,
    live=False,
    show_error=True,
    enable_queue=True,
      examples=["/content/frames/frames/seq_000011.jpg"])
demo.launch(enable_queue=True,debug = 'True')

**Comment by aliabid94** [comment]
So rewrite the demo line as `demo = gr.Interface(fn=crowd,inputs=ge.Image(type="filepath"),outputs=["image","text"])`

**Comment by sa92leh-fs** [comment]
That's true, it's working now! 
Many thanks for your valuable support  
![image](https://user-images.githubusercontent.com/45196857/174355092-aed81f72-4131-48e4-b130-b532742d2ee0.png)

**Comment by abidlabs** [comment]
Great! You can consider hosting your demo for free on [Hugging Face Spaces](https://huggingface.co/spaces)
