### ISSUE TITLE
HF API with a bug of cached examples

### ISSUE THREAD

**Issue by JustinLin610** [gradio-app/gradio#1745]
### Describe the bug

Error with the HF demo, which is caused `IsADirectoryError: [Errno 21] Is a directory: 'gradio_cached_examples/'`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/OFA-Sys/OFA-Generic_Interface

### Logs

```shell
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 255, in run_predict
    output = await app.blocks.process_api(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 548, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 463, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 639, in load_example
    processed_examples += load_from_cache(self, example_id)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/process_examples.py", line 62, in load_from_cache
    component.restore_flagged(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/components.py", line 1606, in restore_flagged
    return processing_utils.encode_file_to_base64(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 56, in encode_file_to_base64
    with open(f, "rb") as file:
IsADirectoryError: [Errno 21] Is a directory: 'gradio_cached_examples/'
```
```


### System Info

```shell
3.0.24
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hmm that's strange, will look into it soon!

**Comment by JustinLin610** [comment]
@AK391 just helped me solve the problem by setting `cache_examples=False`. I think the problem should come from this place and you can check that part of the code.

**Comment by freddyaboulton** [comment]
Hi @JustinLin610, Impressive demo! I just tried it out and it's a really cool.

I think the problem is that your inference function can return either an Image or None. I can reproduce your original error with the following code snippet. It fails with the second example but not the first:

```python
import gradio as gr


def mirror(x, text):
    img = x if text == "Hello" else None
    return img, text

demo = gr.Interface(mirror, inputs=[gr.Image(type="pil"), "text"],
                    outputs=[gr.Image(type="numpy"), "text"],
                    examples=[["lion.jpg", "Hello"],
                               ["lion.jpg", "Hi"]],
                    cache_examples=True)


if __name__ == "__main__":
    demo.launch()
```

When `cache_examples=True`, gradio will save the outputs of your prediction function to a csv file. In the case of images, it writes the file path of the output image to this csv file. 

The problem is that when the image is `None`, that gets written to an empty string in the csv file.

I think there are lots of ways we can take this:
1. Better support for optional outputs
2. More informative error message
3. Error during caching examples when output type does not match expected

I'll talk to the team about which way is the best path forward but hopefully this should help you understand why the error happened and how you can avoid it in the meantime!

**Comment by freddyaboulton** [comment]
Similar to #1194
