### ISSUE TITLE
Run gradio on docker with share=False and server_name="0.0.0.0".

### ISSUE THREAD

**Issue by Mittag-tech** [gradio-app/gradio#1747]
# Overview
- I want to run gradio on docker and ```server_name="0.0.0.0"``` with ```share=False```.
- When my code run, raise ```Valueerror```.
- I don't know why this error raise and how to fix this error.
- Please tell me how to fix this error.

# Code
Dockerfile
```Dockerfile
FROM nvcr.io/nvidia/cuda:11.0.3-cudnn8-devel-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt update ; exit 0
RUN apt install wget libpsl5 publicsuffix
RUN apt-key del 7fa2af80
RUN wget -qO - https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub | apt-key add -
RUN apt-get update && apt-get install -y  \
    python3 python3-setuptools python3-pip python3-dev python3-tk
RUN ln -svf /usr/bin/python3 /usr/bin/python
RUN python -m pip install --upgrade --force pip

WORKDIR /home/src
RUN pip3 install  gradio==3.0.13
```

docker build script, ```build.sh```.
```bash
#!/bin/bash

docker build \
    -t gradio_demo:latest \
    -f Dockerfile .
```

docker run script, ```start.sh```.
```bash
#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0); pwd)
DOCKER_WORKDIR="/home/src"

xhost +local:
docker run --rm --gpus all -it -e DISPLAY=$DISPLAY \
  --volume=/tmp/.X11-unix:/tmp/.X11-unix \
  -p 7860:7860 \
  -v $SCRIPT_DIR/src/:$DOCKER_WORKDIR \
  --name=gradio_demo \
  gradio_demo:latest
```

gradio script, ```greet_usr.py```.
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import gradio

def main():
    with gradio.Blocks() as front_page:
        with gradio.Row():
            with gradio.Column():
                text_box = gradio.Textbox(label="write your name.")
                greet_button = gradio.Button(value="greet")
            with gradio.Column():
                result_box = gradio.Textbox(label="result")
        greet_button.click(fn=greet_user, inputs=text_box, outputs=result_box)
    front_page.launch(server_name="0.0.0.0")

def greet_user(input):
    return f"Hello, {input}!"

if __name__ == "__main__":
    main()

```

# Reproduction procedure
repository structure
```text
├── Dockerfile
├── build.sh
├── src
│   └── greet_usr.py
└── start.sh
```
1. ```sh build.sh```
2. ```sh start.sh```
3. ```python greet_usr.py``` on docker.

raise
```bash
Traceback (most recent call last):
  File "greet_usr.py", line 24, in <module>
    main()
  File "greet_usr.py", line 16, in main
    front_page.launch(server_name="0.0.0.0")
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 779, in launch
    raise ValueError(
ValueError: When running in Google Colab or when localhost is not accessible, a shareable link must be created. Please set share=True.
```

**Comment by abidlabs** [comment]
Thanks for the detailed issue @Mittag-tech. Can you see if this helps? https://github.com/gradio-app/gradio/issues/159

**Comment by Mittag-tech** [comment]
Thanks for your help, I was able to fix this issue.
In case it helps someone else, I write how to fix this issue.

# Background
In my network environment, I made ```~/.docker/config.json``` and wrote proxy settings.
```json
{
        "proxies": {
          "default": {
                "httpProxy": "http://hogehoge",
                "httpsProxy": "http://hogehoge"
          }
        }
  }
```
# How to fix
I wrote ```noProxy``` option on ```~/.docker/config.json```.
```json
{
        "proxies": {
          "default": {
                "httpProxy": "http://hogehoge",
                "httpsProxy": "http://hogehoge",
                "noProxy": "localhost"
          }
        }
  }
```
And, fix ```start.sh```.
```bash
#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0); pwd)
DOCKER_WORKDIR="/home/src"

xhost +local:
docker run --rm --gpus all -it -e DISPLAY=$DISPLAY \
  --env NO_PROXY="localhost" \ # add env
  --volume=/tmp/.X11-unix:/tmp/.X11-unix \
  --net host \
  -v $SCRIPT_DIR/src/:$DOCKER_WORKDIR \
  --name=gradio_demo \
  gradio_demo:latest
```

**Comment by abidlabs** [comment]
Wonderful, thanks for documenting the fix!

**Comment by FrancescoSaverioZuppichini** [comment]
I was wondering if there is a way without --network host

**Comment by abidlabs** [comment]
@FrancescoSaverioZuppichini it should be possible since you only need to expose the port Gradio is running on (`7860` by default). So if you expose `-p 7860 7860`, it should work (but haven't tested)

**Comment by FrancescoSaverioZuppichini** [comment]
> @FrancescoSaverioZuppichini it should be possible since you only need to expose the port Gradio is running on (`7860` by default). So if you expose `-p 7860 7860`, it should work (but haven't tested)

never mind, I've rebooted my mac and now it works - ahahah no idea what was going on :) thanks a lot for the reply ❤️
