### ISSUE TITLE
Fix flagging with `Gallery` component

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#1868]
### Describe the bug

Right now, the `Gallery` component does not overwrite `save_flagged()`, as pointed out by @freddyaboulton. This means that if the `Gallery` component is used an Interface and a user flags the data (or even caches examples), then the Gallery component returns a long base64 string that gets saved in the CSV file, instead of saving the images separately. Not only is this inconvenient for users, but it can lead to a `_csv.Error: field larger than field limit` error.

Internal discussion: https://huggingface.slack.com/archives/C02QZLG8GMN/p1658511653437539 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run this Interface, and then click the Flag button:

```py
import gradio as gr

gr.Interface(lambda x: [x], "image", "gallery").launch()
```

### Logs

```shell
Traceback (most recent call last):
  File "c:\users\islam\dev\gradio-repos\gradio\gradio\routes.py", line 255, in run_predict
    output = await app.blocks.process_api(
  File "c:\users\islam\dev\gradio-repos\gradio\gradio\blocks.py", line 599, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "c:\users\islam\dev\gradio-repos\gradio\gradio\blocks.py", line 514, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "c:\users\islam\appdata\local\programs\python\python39\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "c:\users\islam\appdata\local\programs\python\python39\lib\site-packages\anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "c:\users\islam\appdata\local\programs\python\python39\lib\site-packages\anyio\_backends\_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "c:\users\islam\dev\gradio-repos\gradio\gradio\interface.py", line 570, in __call__
    self.flagging_callback.flag(flag_data, flag_option=self.flag_option)
  File "c:\users\islam\dev\gradio-repos\gradio\gradio\flagging.py", line 226, in flag
    line_count = len([None for row in csv.reader(csvfile)]) - 1
  File "c:\users\islam\dev\gradio-repos\gradio\gradio\flagging.py", line 226, in <listcomp>
    line_count = len([None for row in csv.reader(csvfile)]) - 1
_csv.Error: field larger than field limit (131072)
```

### System Info

```shell
3.1.1
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Duplicate of #1867
