### ISSUE TITLE
Sketchpad demo doesn't work after clicking another tab

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#1961]
### Describe the bug

The pictionary demo on the landing page at https://gradio.app has a bug where it doesn't work if you click on a different tab and then back to it. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See https://gradio.app

### Screenshot

https://user-images.githubusercontent.com/9021060/183220089-9114b21c-8d8f-4f54-92aa-70c1c326c4ab.mov

### Logs

```shell
Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
    at saveLine (https://gradio.s3-us-west-2.amazonaws.com/3.1.1/assets/index.9d04c032.js:970:15)
    at https://gradio.s3-us-west-2.amazonaws.com/3.1.1/assets/index.9d04c032.js:790:4
    at Array.forEach (<anonymous>)
    at draw_lines (https://gradio.s3-us-west-2.amazonaws.com/3.1.1/assets/index.9d04c032.js:776:9)
    at load_save_data (https://gradio.s3-us-west-2.amazonaws.com/3.1.1/assets/index.9d04c032.js:760:4)
    at handle_canvas_resize (https://gradio.s3-us-west-2.amazonaws.com/3.1.1/assets/index.9d04c032.js:844:3)
    at ResizeObserver.<anonymous> (https://gradio.s3-us-west-2.amazonaws.com/3.1.1/assets/index.9d04c032.js:701:5)
```

### System Info

```shell
Chrome
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Happy to report that this problem is fixed in `3.4` (cc @pngwn)!

![Recording 2022-09-28 at 16 19 32](https://user-images.githubusercontent.com/1778297/192905141-8a956748-4bd3-4adf-8975-73a2bdb85981.gif)
