### ISSUE TITLE
Error with jinja2

### ISSUE THREAD

**Issue by muellerzr** [gradio-app/gradio#2039]
### Describe the bug

From what I can tell, using the latest jinja2 leads to a build error. 

My space is here: https://huggingface.co/spaces/muellerzr/bert-base-cased-tpu-accelerate-experiments

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try running the space and see the build logs. 

### Logs

```shell
--> FROM docker.io/library/python:3.8.9@sha256:49d05fff9cb3b185b15ffd92d8e6bd61c20aa916133dca2e3dbe0215270faf53
DONE 0.0s

--> RUN useradd -m -u 1000 user
CACHED

--> WORKDIR /home/user/app
CACHED

--> RUN pip install pip==22.0.2
CACHED

--> RUN apt-get update && apt-get install -y git-lfs
CACHED

--> WORKDIR /home/user
CACHED

--> RUN apt-get update && apt-get install -y         ffmpeg         libsm6         libxext6         cmake         libgl1-mesa-glx
CACHED

--> RUN pip install         streamlit==1.10.0 "protobuf<4" "click<8.1"         gradio==3.1.5
CACHED

--> RUN pip install         datasets         huggingface-hub
CACHED

--> RUN mkdir app
CACHED

--> COPY packages.txt /root/packages.txt
CACHED

--> RUN git lfs install
CACHED

--> COPY requirements.txt /home/user/app/requirements.txt
CACHED

--> RUN apt-get update && xargs -r -a /root/packages.txt apt-get install -y
CACHED

--> RUN pip install -r requirements.txt
CACHED

--> COPY --chown=user ./ /home/user/app
CACHED

--> Pushing image
DONE 1.7s

===== Application Startup =====

Traceback (most recent call last):
  File "app.py", line 6, in <module>
    import gradio as gr
  File "/home/user/.local/lib/python3.8/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/user/.local/lib/python3.8/site-packages/gradio/components.py", line 39, in <module>
    from gradio.blocks import Block
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 19, in <module>
    from gradio import (
  File "/home/user/.local/lib/python3.8/site-packages/gradio/networking.py", line 18, in <module>
    from gradio.routes import App
  File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 48, in <module>
    templates = Jinja2Templates(directory=STATIC_TEMPLATE_LIB)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/templating.py", line 53, in __init__
    self.env = self.get_env(directory)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/templating.py", line 56, in get_env
    @jinja2.contextfunction
AttributeError: module 'jinja2' has no attribute 'contextfunction'
```
```


### System Info

```shell
Huggingface Spaces
```

### Severity

annoying

**Comment by auwsom** [comment]
Hi, how is this closed.. still happening with gradio 3.4

**Comment by vietnhatthai** [comment]
I tried using jinja2 <= 3.0.3, it works well.

**Comment by sorenmc** [comment]
This is still an issue

**Comment by freddyaboulton** [comment]
My guess is that the fastapi and starlette versions are out of synch. Can you share what versions of these two packages you have installed?

**Comment by arianpasquali** [comment]
Same issue here. Versions conflict in deed. Anyone able to solve it?

**Comment by abidlabs** [comment]
Hi @arianpasquali what version of `jinja2` do you have installed? I am running `3.1.2` and everything is working fine for me. Can you try installing that version specifically and see if it resolves the problem for you?

**Comment by hwang136** [comment]
The glitch here is that FastAPI requires jinja2<=3.0.3 but gradio requires jinja2>=3.1.2. Still an issue.
