### ISSUE TITLE
Model3D preview shows grey square on spaces

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2077]
### Describe the bug

When uploading a Model3D file on spaces (from examples or manually) the preview modal doesn't show the Model3D object.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Go to the Model3D demo here:

https://huggingface.co/spaces/gradio-pr-deploys/pr-2064-all-demos

### Screenshot

![model3d_upload](https://user-images.githubusercontent.com/41651716/186450910-551f77b9-501d-466a-b903-c222cc0050a0.gif)

### Logs

```shell
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'active')
    at e.disableAttributeByIndex (index.9f8deacc.js:30:345996)
    at e.unbindAllAttributes (index.9f8deacc.js:30:371147)
    at e.wipeCaches (index.9f8deacc.js:30:354673)
    at t.dispose (index.9f8deacc.js:30:274055)
    at addNewModel (index.9f8deacc.js:611:10)
    at Upload.handle_upload (index.9f8deacc.js:588:3)
```

```
Unable to load from file//tmp/tmpd7j3mvz9/Duckgmo4snro.glb: Error status: 500  - Unable to load file//tmp/tmpd7j3mvz9/Duckgmo4snro.glb
```
```


### System Info

```shell
Spaces
```

### Severity

blocking upgrade to latest gradio version

**Comment by freddyaboulton** [comment]
The same thing happens in a more minimal space https://huggingface.co/spaces/freddyaboulton/Model3D so I think it's an issue with changing the logic for how we load files as opposed to the `all_demos` space
