### ISSUE TITLE
Support multiple instances of the `Queue` (one for each launched Blocks/Interface App)

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#2179]
### Describe the bug

Right now, if you create multiple `Interfaces` or `Blocks` in the same Python session (e.g. by re-running cells in a colab notebook), the UI errors out:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/1778297/188513430-51cb42fe-1494-446d-923a-5b59a4d8b2b0.png">

The reason for this seems to be that we share a single `Queue` object across the different FastAPI apps corresponding to each time that Blocks/Interfaces is launched. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run the following code in a Colab notebook, and then **re-run the cell**. Then, try to make a prediction

```py
import gradio as gr
import time

def test(x):
  time.sleep(5)
  return x

gr.Interface(test, "text", "text").queue().launch()
```
 

### Logs

```shell
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<Queue.process_event() done, defined at /usr/local/lib/python3.7/dist-packages/gradio/event_queue.py:241> exception=RuntimeError('Task <Task pending coro=<Queue.process_event() running at /usr/local/lib/python3.7/dist-packages/gradio/event_queue.py:267>> got Future <Future pending> attached to a different loop')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/event_queue.py", line 267, in process_event
    await event.disconnect()
  File "/usr/local/lib/python3.7/dist-packages/gradio/event_queue.py", line 298, in disconnect
    await self.websocket.close(code=code)
  File "/usr/local/lib/python3.7/dist-packages/starlette/websockets.py", line 181, in close
    {"type": "websocket.close", "code": code, "reason": reason or ""}
  File "/usr/local/lib/python3.7/dist-packages/starlette/websockets.py", line 85, in send
    await self._send(message)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 304, in asgi_send
    await self.close(code, reason)
  File "/usr/local/lib/python3.7/dist-packages/websockets/legacy/protocol.py", line 753, in close
    **loop_if_py_lt_38(self.loop),
  File "/usr/lib/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
RuntimeError: Task <Task pending coro=<Queue.process_event() running at /usr/local/lib/python3.7/dist-packages/gradio/event_queue.py:267>> got Future <Future pending> attached to a different loop
```

### System Info

```shell
Gradio 3.2
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Closed via #2193
