### ISSUE TITLE
Yielding into table throws error about enable queue

### ISSUE THREAD

**Issue by ankrgyl** [gradio-app/gradio#2210]
### Describe the bug

I'm trying to test yielding results into a table, and ran into a bug which seems unrelated: that even if you run with `enable_queue=True`, you get an error like `ValueError: Need to enable queue to use generators.`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr
import pandas

def create_rows():
    for i in range(10):
        yield pandas.DataFrame([i])

with gr.Blocks() as demo:
    a = gr.Dataframe(headers=['a'], value=[[1]]*20, max_rows=1)
    b = gr.Button()

    b.click(fn=create_rows, inputs=[], outputs=[a])

if __name__ == "__main__":
    demo.launch(enable_queue=True)
```

### Logs

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/ankur/projects/transformers/spaces/docquery/venv/lib/python3.10/site-packages/gradio/routes.py", line 263, in run_predict
    output = await app.blocks.process_api(
  File "/Users/ankur/projects/transformers/spaces/docquery/venv/lib/python3.10/site-packages/gradio/blocks.py", line 735, in process_api
    result = await self.call_function(fn_index, inputs, generator)
  File "/Users/ankur/projects/transformers/spaces/docquery/venv/lib/python3.10/site-packages/gradio/blocks.py", line 636, in call_function
    raise ValueError("Need to enable queue to use generators.")
ValueError: Need to enable queue to use generators.
```
```


### System Info

```shell
gradio==3.2.1b1
```
```


### Severity

annoying

**Comment by ankrgyl** [comment]
NOTE: I attempted this as a follow up to [this Twitter exchange](https://twitter.com/ankrgyl/status/1567389644056297474)

**Comment by abidlabs** [comment]
Hi @ankrgyl could you try with `gradio==3.2.1b2`?

I ran the following code (identical to yours, except with a `time.sleep()` so that we can observe the steps of iterator, and it works for me:

```py
import gradio as gr
import pandas

def create_rows():
    for i in range(10):
        time.sleep(0.5)
        yield pandas.DataFrame([i])

with gr.Blocks() as demo:
    a = gr.Dataframe(headers=['a'], value=[[1]]*20, max_rows=1)
    b = gr.Button()

    b.click(fn=create_rows, inputs=[], outputs=[a])

if __name__ == "__main__":
    demo.launch(enable_queue=True)
```

**Comment by freddyaboulton** [comment]
Hi @ankrgyl ! 

Should be possible if you keep track of the current state of the dataframe in each iteration and then append to it.

The following works for me:

```python
import gradio as gr
import pandas

def create_rows():
    for i in range(10):
        time.sleep(0.5)
        yield pandas.DataFrame([i])

with gr.Blocks() as demo:
    a = gr.Dataframe(headers=['a'], value=[[1]]*20, max_rows=1)
    b = gr.Button()

    b.click(fn=create_rows, inputs=[], outputs=[a])

if __name__ == "__main__":
    demo.launch(enable_queue=True)
```

![yield_df](https://user-images.githubusercontent.com/41651716/189156584-a9fb8e8c-de98-4cf1-81ca-ab4f6f00bf01.gif)

**Comment by ankrgyl** [comment]
I think that's the same code as above? I tried doing that but messed something up.

**Comment by freddyaboulton** [comment]
Lol my bad - updated the code snippet.

**Comment by ankrgyl** [comment]
This is awesome. Thank you so much!

**Comment by freddyaboulton** [comment]
No problem! @ankrgyl going to close this out
