### ISSUE TITLE
gr.update cannot update gr.dataframe headers

### ISSUE THREAD

**Issue by mustafalhamadsa** [gradio-app/gradio#2227]
### Describe the bug

Not sure if I am missing something, but apparently Dataframe headers cannot be updated with update component 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just update gr.dataframe headers with gr.update

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 269, in run_predict
    fn_index, raw_input, username, session_state, iterators
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 748, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 628, in call_function
    block_fn.fn, *processed_input, limiter=self.limiter
  File "/usr/local/lib/python3.7/dist-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "<ipython-input-5-a5d4b6c77ada>", line 180, in on_button_clicked1
    return returner(st,button=False,box=True,file1=False,t1 = title,genbutton="Update 📄",color1=color1,color2=color2,color3=color3,link=link,aimage=aimage,bottomtext=bottom,help=help,about=about,ex=ex,height=height,width=width)
  File "<ipython-input-5-a5d4b6c77ada>", line 127, in returner
    gr.Dataframe.update(headers=["Step name", "Step description", "Image (link)"],value=help),
TypeError: update() got an unexpected keyword argument 'headers'
```
```


### System Info

```shell
Google Colab
Gradio 3.3
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @mustafalhamadsa! Thank you for postong. Can you try setting the `value` to a new dataframe with the headers and data you want?
