### ISSUE TITLE
Cannot build gradio.

### ISSUE THREAD

**Issue by adamryczkowski** [gradio-app/gradio#2300]
### Describe the bug

I am using Ubuntu 20.04 64 bit and pnpm version 6.32.11. 

I am trying to build gradio from source to write a pull request. 

Here is an error I get after running the build script in the Python 3.10.7 environment. 

```
bash -x scripts/build_frontend.sh 
++ dirname scripts/build_frontend.sh
+ cd scripts/..
+ source scripts/helpers.sh
+ pnpm_required
+ program_required pnpm https://pnpm.io/7.x/installation
++ command -v pnpm
+ '[' '!' -x /home/adam/.local/share/pnpm/pnpm ']'
+ echo 'Building the frontend...'
Building the frontend...
+ cd ui
+ pnpm i --frozen-lockfile
Scope: all 29 workspace projects
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
+ pnpm build

> gradio-ui@0.0.1 build /home/adam/diffusers/gradio/ui
> pnpm --filter @gradio/app build:local --emptyOutDir


> @gradio/app@1.0.0 build:local /home/adam/diffusers/gradio/ui/packages/app
> vite build --mode production:local --emptyOutDir

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/adam/diffusers/gradio/ui/node_modules/.pnpm/vite@2.9.5/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:25:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
/home/adam/diffusers/gradio/ui/packages/app:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @gradio/app@1.0.0 build:local: `vite build --mode production:local --emptyOutDir`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
$ wget -qO- https://get.pnpm.io/install.sh | PNPM_VERSION=6.32.11 sh -
```
log out, log in, and then

```
$ python3.10 -m venv venv
$ . venv/bin/activate
$ git clone --depth 1 https://github.com/gradio-app/gradio.git
$ cd gradio/
$ bash -x scripts/build_frontend.sh 
++ dirname scripts/build_frontend.sh
+ cd scripts/..
+ source scripts/helpers.sh
+ pnpm_required
+ program_required pnpm https://pnpm.io/7.x/installation
++ command -v pnpm
+ '[' '!' -x /home/adam/.local/share/pnpm/pnpm ']'
+ echo 'Building the frontend...'
Building the frontend...
+ cd ui
+ pnpm i --frozen-lockfile
Scope: all 29 workspace projects
Lockfile is up-to-date, resolution step is skipped
Packages: +442
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are cloned from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/adam/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 442, reused 440, downloaded 0, added 442, done
node_modules/.pnpm/babylonjs@5.18.0/node_modules/babylonjs: Running postinstall script...
node_modules/.pnpm/core-js-pure@3.21.1/node_modules/core-js-pure: Running postinstall script...
node_modules/.pnpm/playwright@1.22.2/node_modules/playwright: Running install script...
node_modules/.pnpm/playwright@1.24.2/node_modules/playwright: Running install script...
node_modules/.pnpm/babylonjs@5.18.0/node_modules/babylonjs: Running postinstall script, done in 269msrocess: Running node_modules/.pnpm/core-js-pure@3.21.1/node_modules/core-js-pure: Running postinstall script, done in 283ms: Running node_modules/.pnpm/playwright@1.22.2/node_modules/playwright: Running install script, done in 418ms
node_modules/.pnpm/playwright@1.24.2/node_modules/playwright: Running install script, done in 427mseprocess: Running node_modules/.pnpm/svelte-preprocess@4.10.6_62d50a01257de5eec5be08cad9d3ed66/node_modules/svelte-preprocess: Running postinstall script, done in 4ms
node_modules/.pnpm/esbuild@0.14.31/node_modules/esbuild: Running postinstall script, done in 294ms
node_modules/.pnpm/esbuild@0.14.53/node_modules/esbuild: Running postinstall script, done in 297ms

dependencies:
+ @gradio/tootils 0.0.1 <- packages/tootils
+ @playwright/test 1.24.2
+ @sveltejs/vite-plugin-svelte 1.0.0-next.44
+ @tailwindcss/forms 0.5.0
+ @testing-library/dom 8.11.3
+ @testing-library/svelte 3.1.0
+ @testing-library/user-event 13.5.0
+ autoprefixer 10.4.4
+ babylonjs 5.18.0
+ babylonjs-loaders 5.18.0
+ happy-dom 2.49.0
+ node-html-parser 5.3.3
+ npm-run-all 4.1.5
+ playwright 1.24.2
+ plotly.js-dist-min 2.11.1
+ polka 1.0.0-next.22
+ postcss 8.4.6
+ postcss-nested 5.0.6
+ prettier 2.6.2
+ prettier-plugin-svelte 2.7.0
+ sirv 2.0.2
+ sirv-cli 2.0.2
+ svelte 3.49.0
+ svelte-check 2.8.0
+ svelte-i18n 3.3.13
+ svelte-preprocess 4.10.6
+ tailwindcss 3.1.6
+ tinyspy 0.3.0
+ typescript 4.7.4
+ vite 2.9.5
+ vitest 0.12.7

devDependencies:
+ @types/three 0.138.0
+ pnpm build

> gradio-ui@0.0.1 build /home/adam/gradio/ui
> pnpm --filter @gradio/app build:local --emptyOutDir


> @gradio/app@1.0.0 build:local /home/adam/gradio/ui/packages/app
> vite build --mode production:local --emptyOutDir

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/adam/gradio/ui/node_modules/.pnpm/vite@2.9.5/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:25:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
/home/adam/gradio/ui/packages/app:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @gradio/app@1.0.0 build:local: `vite build --mode production:local --emptyOutDir`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

### Logs

```shell
Logs included in the Reproduction paragraph
```

### System Info

```shell
Gradio version: commit `b8fc5518075b2edee406797fbc3dc33f4145d2ce` (Tue Sep 20 09:48:52 2022 -0500
)

pnpm version `6.32.11`
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Can you try with `pnpm 7`?

We've updated https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md to mention that Gradio now uses `pnpm 7`, but it may be that we've missed a reference somewhere else? Where did you see to use `pnpm 6`?

**Comment by adamryczkowski** [comment]
I initially tried pnpm 7. After getting an error I started to fill in the bug. In the bug fill form you require to make sure that the same problem has not been fixed already. Well, it was: https://github.com/gradio-app/gradio/issues/1374 , and since you never write that this solution is not valid anymore, I assumed this is the way. 

Here is the error I get when using `pnpm` version `7.12.1`:

```
bash -x scripts/build_frontend.sh 
++ dirname scripts/build_frontend.sh
+ cd scripts/..
+ source scripts/helpers.sh
+ pnpm_required
+ program_required pnpm https://pnpm.io/7.x/installation
++ command -v pnpm
+ '[' '!' -x /home/adam/.local/share/pnpm/pnpm ']'
+ echo 'Building the frontend...'
Building the frontend...
+ cd ui
+ pnpm i --frozen-lockfile
Scope: all 29 workspace projects
Recreating /home/adam/gradio/ui/node_modules
Lockfile is up to date, resolution step is skipped
Packages: +442
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are cloned from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/adam/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 442, reused 440, downloaded 0, added 442, done
node_modules/.pnpm/core-js-pure@3.21.1/node_modules/core-js-pure: Running postinstall script, done in 287ms
node_modules/.pnpm/babylonjs@5.18.0/node_modules/babylonjs: Running postinstall script, done in 275ms
node_modules/.pnpm/playwright@1.22.2/node_modules/playwright: Running install script, done in 432ms
node_modules/.pnpm/playwright@1.24.2/node_modules/playwright: Running install script, done in 439ms
node_modules/.pnpm/svelte-preprocess@4.10.2_d50790bb30dd88cc44babe7efa52bace/node_modules/svelte-preprocess: Running postinstall script, done in 6ms
node_modules/.pnpm/svelte-preprocess@4.10.6_62d50a01257de5eec5be08cad9d3ed66/node_modules/svelte-preprocess: Running postinstall script, done in 6ms
node_modules/.pnpm/esbuild@0.14.53/node_modules/esbuild: Running postinstall script, done in 304ms
node_modules/.pnpm/esbuild@0.14.31/node_modules/esbuild: Running postinstall script, done in 304ms

dependencies:
+ @gradio/tootils 0.0.1 <- packages/tootils
+ @playwright/test 1.24.2
+ @sveltejs/vite-plugin-svelte 1.0.0-next.44
+ @tailwindcss/forms 0.5.0
+ @testing-library/dom 8.11.3
+ @testing-library/svelte 3.1.0
+ @testing-library/user-event 13.5.0
+ autoprefixer 10.4.4
+ babylonjs 5.18.0
+ babylonjs-loaders 5.18.0
+ happy-dom 2.49.0
+ node-html-parser 5.3.3
+ npm-run-all 4.1.5
+ playwright 1.24.2
+ plotly.js-dist-min 2.11.1
+ polka 1.0.0-next.22
+ postcss 8.4.6
+ postcss-nested 5.0.6
+ prettier 2.6.2
+ prettier-plugin-svelte 2.7.0
+ sirv 2.0.2
+ sirv-cli 2.0.2
+ svelte 3.49.0
+ svelte-check 2.8.0
+ svelte-i18n 3.3.13
+ svelte-preprocess 4.10.6
+ tailwindcss 3.1.6
+ tinyspy 0.3.0
+ typescript 4.7.4
+ vite 2.9.5
+ vitest 0.12.7

devDependencies:
+ @types/three 0.138.0

The integrity of 2457 files was checked. This might have caused installation to take longer.
+ pnpm build

> gradio-ui@0.0.1 build /home/adam/gradio/ui
> pnpm --filter @gradio/app build:local --emptyOutDir


> @gradio/app@1.0.0 build:local /home/adam/gradio/ui/packages/app
> vite build --mode production:local --emptyOutDir "--emptyOutDir"

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/adam/gradio/ui/node_modules/.pnpm/vite@2.9.5/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:25:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
/home/adam/gradio/ui/packages/app:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @gradio/app@1.0.0 build:local: `vite build --mode production:local --emptyOutDir "--emptyOutDir"`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by pngwn** [comment]
I'll take a look at this. `pnpm 7` should be working fine but I'll investigate.

**Comment by freddyaboulton** [comment]
@adamryczkowski Are you on node version 16 ?

**Comment by adamryczkowski** [comment]
No. I use the `v10.19.0`. 

Installing node 16 solved the problem.
