### ISSUE TITLE
Audio.stream() does not work inside of gradio.Blocks()

### ISSUE THREAD

**Issue by qunash** [gradio-app/gradio#2333]
### Describe the bug

Can't pass Audio to the **callable function** in Audio.stream() inside a gradio.Blocks().

Capturing streaming audio works fine using **Interface** but not in **Blocks**.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

with gr.Blocks() as test:

    audio_mic = gr.Audio(source="microphone", type="filepath", streaming=True)

    audio_mic.stream(
            lambda value: print(value),
            inputs=audio_mic,
            outputs=[]
        )

test.launch()
```

Error occurs when pressing **Record from microphone**

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Python\Python38\site-packages\gradio\routes.py", line 273, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\xxx\AppData\Roaming\Python\Python38\site-packages\gradio\blocks.py", line 750, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\xxx\AppData\Roaming\Python\Python38\site-packages\gradio\blocks.py", line 615, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "C:\Users\xxx\AppData\Roaming\Python\Python38\site-packages\gradio\components.py", line 1810, in preprocess
    sample_rate, data = processing_utils.audio_from_file(
  File "C:\Users\xxx\AppData\Roaming\Python\Python38\site-packages\gradio\processing_utils.py", line 187, in audio_from_file
    data = np.array(audio.get_array_of_samples())
UnboundLocalError: local variable 'audio' referenced before assignment
```

### System Info

```shell
Gradio version==3.3.1
Chrome
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
@aliabid94 can you take a look at this as you look into streaming?

**Comment by freddyaboulton** [comment]
Hi @qunash Do you have ffmpeg installed?

**Comment by qunash** [comment]
@freddyaboulton yes, that was the issue, thank you!

**Comment by qslia** [comment]
how should I save it to a local .wav file?
