### ISSUE TITLE
Can't run gradio on M1

### ISSUE THREAD

**Issue by gabrielhuang** [gradio-app/gradio#2447]
### Describe the bug

I can't import gradio. Installed Python 3.9.12 using Miniconda on Mac M1.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```bash
(base) ➜  ~ python
Python 3.9.12 (main, Apr  5 2022, 01:52:34)
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gradio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/gradio/components.py", line 39, in <module>
    from gradio import media_data, processing_utils, utils
  File "/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/gradio/processing_utils.py", line 17, in <module>
    from gradio import encryptor, utils
  File "/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/gradio/encryptor.py", line 2, in <module>
    from Crypto.Cipher import AES
  File "/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/Crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/Crypto/Cipher/_mode_ecb.py", line 35, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Crypto.Cipher._raw_ecb", """
  File "/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/Crypto/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Not found '_raw_ecb.cpython-39-darwin.so', Cannot load '_raw_ecb.abi3.so': cannot load library '/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so': dlopen(/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so, 0x0002): tried: '/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_raw_ecb.abi3.so' (no such file), '/usr/lib/_raw_ecb.abi3.so' (no such file), '/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/Crypto/Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_raw_ecb.abi3.so' (no such file), '/usr/lib/_raw_ecb.abi3.so' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so', Not found '_raw_ecb.so'
```

### Logs

```shell
(base) ➜  ~ python
Python 3.9.12 (main, Apr  5 2022, 01:52:34)
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gradio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/gradio/components.py", line 39, in <module>
    from gradio import media_data, processing_utils, utils
  File "/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/gradio/processing_utils.py", line 17, in <module>
    from gradio import encryptor, utils
  File "/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/gradio/encryptor.py", line 2, in <module>
    from Crypto.Cipher import AES
  File "/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/Crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/Crypto/Cipher/_mode_ecb.py", line 35, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Crypto.Cipher._raw_ecb", """
  File "/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/Crypto/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Not found '_raw_ecb.cpython-39-darwin.so', Cannot load '_raw_ecb.abi3.so': cannot load library '/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so': dlopen(/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so, 0x0002): tried: '/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_raw_ecb.abi3.so' (no such file), '/usr/lib/_raw_ecb.abi3.so' (no such file), '/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/Crypto/Cipher/_raw_ecb.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_raw_ecb.abi3.so' (no such file), '/usr/lib/_raw_ecb.abi3.so' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Users/gabriel.huang1/miniconda3/lib/python3.9/site-packages/Crypto/Util/../Cipher/_raw_ecb.abi3.so', Not found '_raw_ecb.so'
```

### System Info

```shell
gradio==3.4.1

Darwin XXXXXXXX 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 x86_64
```

### Severity

blocking all usage of gradio

**Comment by freddyaboulton** [comment]
Hi @gabrielhuang ! Thanks for filing. Sorry about that. This is strange because I'm running a 3.9 conda env and can install gradio without a problem. Have you tried in a fresh environment?

**Comment by gabrielhuang** [comment]
Yes I have tried again. But it turns out I had issues even with running jupyter notebook. I solved/worked around the issue by uninstalling the M1 python and using the Intel version of miniconda python on a Rosetta terminal (by checking the [ ]Run in rosetta box).

**Comment by gabrielhuang** [comment]
I'm curious, are you able to make it work natively on the arm architecture?

**Comment by freddyaboulton** [comment]
Glad you found a fix! I am not using Rosetta terminal and I think I got it working on arm. This is the output of conda info for me

```
❯ conda info

     active environment : gradio-39
    active env location : /Users/freddy/miniconda3/envs/gradio-39
            shell level : 2
       user config file : /Users/freddy/.condarc
 populated config files :
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __osx=12.2.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/freddy/miniconda3  (writable)
      conda av data dir : /Users/freddy/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/freddy/miniconda3/pkgs
                          /Users/freddy/.conda/pkgs
       envs directories : /Users/freddy/miniconda3/envs
                          /Users/freddy/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.13.0 requests/2.27.1 CPython/3.9.12 Darwin/21.3.0 OSX/12.2.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by freddyaboulton** [comment]
Going to close for now since you found a workaround. Thank you @gabrielhuang ! Let us know if you have any other questions.
