### ISSUE TITLE
Raise which Space is erroring out when calling inference from a Space

### ISSUE THREAD

**Issue by merveenoyan** [gradio-app/gradio#2501]
I'm trying to put Spaces in `Series` and `Interface.load()`. At some point it errors out and inference is quite long. It would be very nice if when `debug` is set to `True` the error output could include which Space/model errors out [here](https://github.com/gradio-app/gradio/blob/9840e87e829062246808fc130dd05b4b2176ee7f/gradio/external.py#L482) for easier debugging.

Reproduction: 
```python
import gradio as gr
img_to_text = gr.Interface.load("spaces/pharma/CLIP-Interrogator")
diffusion_model = gr.Interface.load("spaces/CompVis/text2img-latent-diffusion")
gr.mix.Series(img_to_text, diffusion_model).launch(debug=True)
```
The log:

```
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/external.py", line 483, in fn
    output = result["data"]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/routes.py", line 298, in run_predict
    output = await app.blocks.process_api(
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/blocks.py", line 790, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/blocks.py", line 695, in call_function
    prediction = await block_fn.fn(*processed_input)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/mix.py", line 94, in connected_fn
    data = (await interface.call_function(0, data))["prediction"]
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/blocks.py", line 697, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/external.py", line 489, in fn
    raise KeyError(
KeyError: "Could not find 'data' key in response from external Space. Response received: {'error': 'list index out of range'}"

```
(it would be nice if I could see which Space/model is raising the `KeyError `above)
(there might be a mismatch between outputs in between but I want to make sure that that's the case)

**Comment by abidlabs** [comment]
Thanks @merveenoyan, that makes sense, we can improve the error logging here

**Comment by abidlabs** [comment]
Hey @merveenoyan I looked into this and I think the problem is actually that these Spaces are Blocks, not Interfaces. And it's not possible to use `gr.mix.Series` with `Blocks` instead of `Interface` right now (perhaps we should figure out a way to support this?) 

But for now, I've added clearer error messaging if you do try to use `Series` with `Blocks`. in #2543
