### ISSUE TITLE
Socket error when loading WAVs longer than ~20 seconds

### ISSUE THREAD

**Issue by vzakharov** [gradio-app/gradio#2630]
### Describe the bug

So I’m building this [Jukebox Web UI](https://twitter.com/vovahimself/status/1590361407245406208?s=20&t=dF6QsPQCmUPaat5VkVPccQ) thing, and the biggest problem I’m now facing is that the frontend will only reliably load wav’s that are shorter than ~20 seconds.

Here is an example, where you can see that, although the WAV is loaded the first time (by the Audio element), it fails to be so for the wavesurfer component:
![image](https://user-images.githubusercontent.com/188197/200898381-2342a1fe-1aac-4672-b8dc-c475078272bb.png)

What makes the error weird is that it’s not marked as an error in the Network tab of the console:
![image](https://user-images.githubusercontent.com/188197/200898669-e6a05d60-b122-4d43-96c4-de70c0f913e4.png)

Even more weirdly, if you open the wav in a separate tab via link, you can’t download it afterwards due to a “network error,” although the process is actually completed:
![4432b6fbb0052fed96a39e9f518db302](https://user-images.githubusercontent.com/188197/200898896-88759d44-c6ff-4756-97cf-a16d372eb633.gif)

Even MORE weirdly, if you rename that partial download to a “.wav,” it opens just fine 🤷‍♂️

*Sometimes*, the backend (Colab) will give a “Socket error” from the `paramiko` package, but sometimes it won’t. Luckily it did at the time of writing, so here you have it:
```console
Exception in thread Thread-78:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gradio/tunneling.py", line 39, in handler
    chan.send(data)
  File "/usr/local/lib/python3.7/dist-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
  File "/usr/local/lib/python3.7/dist-packages/paramiko/channel.py", line 1198, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed
```

Unfortunately I don’t have the resources right now to create an isolated case for this, but I thought maybe you would have some ideas off the top of your head?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

n/a

### Logs

```console
Exception in thread Thread-78:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gradio/tunneling.py", line 39, in handler
    chan.send(data)
  File "/usr/local/lib/python3.7/dist-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
  File "/usr/local/lib/python3.7/dist-packages/paramiko/channel.py", line 1198, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed
```

### System Info

```shell
Gradio 3.9, Chrome 106.0.5249.121, Windows 11
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Thanks for creating this issue! Would you be able to share the link to the code where you're experiencing this issue? 

Two specific questions:
* Is this with `share=True`?
* Is this with queuing enabled?

**Comment by vzakharov** [comment]
Sure @abidlabs, [here’s](https://github.com/vzakharov/jukebox-webui/blob/main/jukebox-webui.py) the code.

Unfortunately I can’t tets it with `share=False`, as my code requires some stuff to be done in the frontend which does not work from an iframe, so the app must always be opened in a new tab. I can think of a way to work around this just to test whether it will work if you think that might we what’s causing this.

Don’t know anything about queuing, can you give me an rtfm link?

**Comment by abidlabs** [comment]
Thanks @vzakharov. Btw, when you set share=False, you still do get a link that you can click on to open it up in a new tab. I think it's worth testing what happens if you set `share=False`, since in that case, you won't be using the `paramiko` library where this error seems to be happening. 

The other thing to try is to enable [queuing](https://gradio.app/setting_up_a_demo_for_maximum_performance/), which basically uses websockets instead of http requests to pass data between the backend and frontend. All you have to do is to change this line:

```py
  app.launch( share = share_gradio, debug = debug_gradio )
```

to 

```py
  app.queue().launch( share = share_gradio, debug = debug_gradio )
```

**Comment by vzakharov** [comment]
I’ll definitely give queuing a try, thanks 🤞

For new tab, I don’t get it: the link is to localhost, and I definitely
don’t have any secret started locally. Is there some even weirder magic at
play?

**Comment by abidlabs** [comment]
There is some weirder magic in fact. It says localhost, but it actually links to a special link running on colab's machine. Try clicking on it and inspect the URL :)

**Comment by vzakharov** [comment]
@abidlabs, reporting back:

1. The `share=False` trick worked, but the loading times became unbearable. A 30-second wav took 30 seconds to load, lol.

2. The `.queue()` trick didn’t. First time I tried it it just went the same way, with the same (failed) HTTP request (which is weird I guess given what you said about sockets).
 
The second time the app didn’t start at all, giving me this:

```console
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    self.scope, self.receive, self.send
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.7/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/routing.py", line 236, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.7/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.7/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.7/dist-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.7/dist-packages/gradio/routes.py", line 237, in file
    f"File cannot be fetched: {path}, perhaps because "
ValueError: File cannot be fetched: /tmp/tmphtr_e7up/tmp7wcpl0x0.wav, perhaps because it is not in any of {'/tmp/tmpwa6g_1ai', '/tmp/tmpeyb_qqcw', '/tmp/tmp38v9vzk7'}
```

I wonder if I could maybe create a separate `ngrok` server to just deliver files 🤔 Seems like an overkill, but what else can I do?..

**Comment by vzakharov** [comment]
(It’s interesting that with `share=False` it takes the _exact_ length of the wav to download it, i.e. a 10-second wav is loaded in 10 seconds, a 30-second one in 30 seconds. I wonder if it plays it at 1x speed somewhere on the server before giving it to me lol.)

**Comment by abidlabs** [comment]
@vzakharov can you please test with the new share links in Colab? You don't have to do anything differently, as long as you are using `gradio>=3.13.0`

**Comment by vzakharov** [comment]
I already rewrote it so that it splits files into chunks on the server
side, sends them separately, and merges them back on the client. So it’ll
take some tweaking to try and test it. I’ll see what I can do though!

**Comment by abidlabs** [comment]
Sounds good, thanks @vzakharov. I'll go ahead and close this issue for now as we don't have a simple repro, but please do reopen this issue if you are still experiencing this issue.
