### ISSUE TITLE
kitchen_sink is broken on spaces

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#2867]
### Describe the bug

The kitchen_sink demo is broken on the deployed spaces for PRs!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Go to any PR's deployed space, e.g. `https://huggingface.co/spaces/gradio-pr-deploys/pr-2866-all-demos` 

and click submit on the kitchen sink demo

### Logs

```shell
To create a public link, set `share=True` in `launch()`.
/home/user/.local/lib/python3.8/site-packages/altair/utils/core.py:317: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for col_name, dtype in df.dtypes.iteritems():
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1007, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 953, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/components.py", line 2082, in postprocess
    file_path = self.make_temp_copy_if_needed(y)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 364, in make_temp_copy_if_needed
    temp_file_path = self.get_temp_file_path(file_path)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 350, in get_temp_file_path
    file_hash = self.hash_file(file_path)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 319, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'demos/zip_files/files/cantina.wav'
```

### System Info

```shell
main
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment]
Closing as the reason was that there was that some of the input components did not have values. Using the examples works fine.
