### ISSUE TITLE
Issues while displaying generated images in a gallery 

### ISSUE THREAD

**Issue by sayakpaul** [gradio-app/gradio#2916]
### Describe the bug

I am trying to create a Space to demonstrate a fine-tuned Stable Diffusion model. While the inference function executes smoothly, there seems to be a problem with the rendering part. I adapted the code from here: https://huggingface.co/spaces/stabilityai/stable-diffusion. 

After the inference function executes, I run into:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/fastapi/encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
ValueError: dictionary update sequence element #0 has length 512; 2 is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/fastapi/encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 253, in app
    content = await serialize_response(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 150, in serialize_response
    return jsonable_encoder(response_content)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/encoders.py", line 131, in jsonable_encoder
    jsonable_encoder(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/encoders.py", line 131, in jsonable_encoder
    jsonable_encoder(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [ValueError('dictionary update sequence element #0 has length 512; 2 is required'), TypeError('vars() argument must have __dict__ attribute')]
```

There isn't any rendering after the execution of the inference function. Anything am I missing out on? 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Here's my Colab: https://colab.research.google.com/drive/1yAKxFutwK5u90ukw85Anf4GBnoWXdlra?usp=sharing.

Here's a [simpler version of the Colab Notebook](https://colab.research.google.com/drive/1n6nxK9vwOeaocHPyqBUzed4t_3UFvbGH?usp=sharing) (that doesn't have any customized CSS) that seems to work. 

### Logs

```shell
25/25 [==============================] - 14s 544ms/step
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/fastapi/encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
ValueError: dictionary update sequence element #0 has length 512; 2 is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/fastapi/encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.8/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 253, in app
    content = await serialize_response(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 150, in serialize_response
    return jsonable_encoder(response_content)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/encoders.py", line 131, in jsonable_encoder
    jsonable_encoder(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/encoders.py", line 131, in jsonable_encoder
    jsonable_encoder(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [ValueError('dictionary update sequence element #0 has length 512; 2 is required'), TypeError('vars() argument must have __dict__ attribute')]
Time taken: 14.297890424728394 seconds.
```

### System Info

I am using Colab.

Gradio version is 3.15.0.

### Severity

annoying

**Comment by abidlabs** [comment]
Thanks @sayakpaul will look into this

**Comment by abidlabs** [comment]
Hi @sayakpaul is there any way you can provide a simpler repro? Ideally one that doesn't require running a model. For example, if you can save the output images somewhere and just download them & show them in the Gallery component? It would make reproducing this a LOT easier

**Comment by sayakpaul** [comment]
I will try but I am running a little short on bandwidth. So, might be a while.

**Comment by abidlabs** [comment]
Hi @sayakpaul I'm going to close this for now so that we can focus on issues that we can reproduce. Feel free to open with a simpler repro. Thank you!
