### ISSUE TITLE
`gr.Interface.load()` not working with image as the output

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#2920]
### Describe the bug

Trying to load the following Space https://huggingface.co/spaces/kakaobrain/karlo
```py
karlo = gr.Interface.load("kakaobrain/karlo", src="spaces")
prompt="a mecha robot in a favela"
images_result = karlo(prompt)
```

It seems the function actually runs remotely in the requested Space, but something wrong happens when processing the output, after it returns the result - some missing temp file:

```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp336s5u4z.png'
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Full traceback: 
```
Traceback (most recent call last):
  File "/home/poli/miniconda3/envs/multimodal/lib/python3.9/site-packages/gradio/routes.py", line 325, in run_predict
    output = await app.blocks.process_api(
  File "/home/poli/miniconda3/envs/multimodal/lib/python3.9/site-packages/gradio/blocks.py", line 983, in process_api
    result = await self.call_function(
  File "/home/poli/miniconda3/envs/multimodal/lib/python3.9/site-packages/gradio/blocks.py", line 821, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/poli/miniconda3/envs/multimodal/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/poli/miniconda3/envs/multimodal/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/poli/miniconda3/envs/multimodal/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/mnt/c/Users/poli/Documents/GitHub/karlo-upscaler/app.py", line 6, in run
    results = karlo(prompt)
  File "/home/poli/miniconda3/envs/multimodal/lib/python3.9/site-packages/gradio/blocks.py", line 776, in __call__
    processed_outputs = self.deserialize_data(fn_index, outputs)
  File "/home/poli/miniconda3/envs/multimodal/lib/python3.9/site-packages/gradio/blocks.py", line 872, in deserialize_data
    deserialized = block.deserialize(outputs[o])
  File "/home/poli/miniconda3/envs/multimodal/lib/python3.9/site-packages/gradio/components.py", line 3702, in deserialize
    name = FileSerializable.deserialize(self, img_data, gallery_path)
  File "/home/poli/miniconda3/envs/multimodal/lib/python3.9/site-packages/gradio/serializing.py", line 143, in deserialize
    file_name = processing_utils.create_tmp_copy_of_file(
  File "/home/poli/miniconda3/envs/multimodal/lib/python3.9/site-packages/gradio/processing_utils.py", line 411, in create_tmp_copy_of_file
    shutil.copy2(file_path, file_obj.name)
  File "/home/poli/miniconda3/envs/multimodal/lib/python3.9/shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/poli/miniconda3/envs/multimodal/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp336s5u4z.png'
```

### Logs

```shell
None
```

### System Info

```shell
Gradio==3.15.0
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Will take a look!

**Comment by freddyaboulton** [comment]
I went back in time and the switch from base64 to temp files for the Gallery component (introduced in #2265)  seems to be causing this issue.

I think we'd need to download the images from the upstream space to fix?

**Comment by apolinario** [comment]
That makes sense @freddyaboulton. And I think downloading downstream the file make sense, given that for Spaces the temp files and the file structure should have predictable URLs. 

Another high level idea I thought of would be to check if the request is coming from 
an external request (be it API or interface load), add an additional processing step to convert the temp file back to base64 and send that as the response. But idk how complex/feasible that would be.

**Comment by abidlabs** [comment]
Looking into this

**Comment by fffiloni** [comment]
FYI @abidlabs all my space involved are running under the 3.15.0 version of gradio

**Comment by abidlabs** [comment]
Yup I have a PR ready (#3004) this should fix this retroactively. So you'll be able to load 3.15 Spaces with the latest version of Gradio
