### ISSUE TITLE
Auto-reloading throws a relative import error

### ISSUE THREAD

**Issue by jobini** [gradio-app/gradio#2963]
### Describe the bug

Auto-reloading by running `gradio app.py` throws a relative import error: `TypeError: the 'package' argument is required to perform a relative import for '.path.to.app'`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Create a Python virtual environment with the command: `python3 -m venv venv`.

2. Activate the virtual environment: `source venv/bin/activate`.

3. Install Gradio: `pip install gradio`.

4. Create a file named `app.py` with the following code:

```
import gradio as gr

with gr.Blocks() as demo:
    gr.Markdown("Test")

if __name__ == '__main__':
    demo.launch()
```

5. Run the command: `gradio app.py`

### Logs

```shell
WARNING:  StatReload detected changes in 'app.py'. Reloading...
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 121, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '.home.user1.Projects.proj.app'
```

### System Info

```shell
Gradio version: 3.16.1
Python version: 3.10.6
Operating System: Ubuntu 22.04
```

### Severity

blocking all usage of gradio

**Comment by misnaej** [comment]
Hi there, 
Maybe this can help.
I had a similar error and I looking for solution I came by this post, and then I solved it by uninstalling gradio from my venv, reinstalled a prior (gradio == 3.13.1).

**Comment by freddyaboulton** [comment]
Hi @jobini - will look into it!

**Comment by jobini** [comment]
Hi @freddyaboulton - Thanks a lot! :) Also, I can confirm @misnaej 's finding that it indeed works with earlier versions of Gradio (thanks, @misnaej ! :) ).  In fact, this issue doesn't exist upto (and including) version 3.15.0. However, there's a different error that comes up in these earlier versions, when opening `http://127.0.0.1:7860/` in the browser:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/fastapi/routing.py", line 255, in app
    content = await serialize_response(
  File "/home/user1/Projects/proj/venv/lib/python3.10/site-packages/fastapi/routing.py", line 141, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: <unprintable ValidationError object>
```

**Comment by hysts** [comment]
I came across the same error and found this issue.

@jobini FYI, you can avoid the error mentioned in https://github.com/gradio-app/gradio/issues/2963#issuecomment-1381709964 by not using `if __name__ == '__main__':`; the following code doesn't raise the error with `gradio==3.15.0`:
```python
import gradio as gr

with gr.Blocks() as demo:
    gr.Markdown("Test")

demo.launch()
```
I don't know why it works that way, but I guess this might help as a workaround until the issue is fixed.

**Comment by freddyaboulton** [comment]
Thank you for looking into it @hysts !

**Comment by jobini** [comment]
@hysts Thanks, that helps! :)

**Comment by harrywang** [comment]
I have the same issue with the latest gradio

**Comment by vlasvlasvlas** [comment]
same problem here. will test downgrade. txs!
