### ISSUE TITLE
My Gradio application is not working.

### ISSUE THREAD

**Issue by ivanislart** [gradio-app/gradio#2977]
### Describe the bug

My Gradio application is not working. What is the problem? I get an error with the parameter "examples" but I don't have that parameter in my code.

https://huggingface.co/spaces/tomaseo2022/Silueta

I have reset the application and it still doesn't work

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/tomaseo2022/Silueta

### Logs

```shell
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /home/user/.local/lib/python3.8/site-packages (22.0.2)
Collecting pip
  Downloading pip-22.3.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 111.3 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    Uninstalling pip-22.0.2:
      Successfully uninstalled pip-22.0.2
Successfully installed pip-22.3.1
Defaulting to user installation because normal site-packages is not writeable
Collecting opencv-python
  Downloading opencv_python-4.7.0.68-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (61.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.8/61.8 MB 50.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17.0 in /home/user/.local/lib/python3.8/site-packages (from opencv-python) (1.24.1)
Installing collected packages: opencv-python
Successfully installed opencv-python-4.7.0.68
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: gradio in /home/user/.local/lib/python3.8/site-packages (3.16.0)
Collecting gradio
  Downloading gradio-3.16.1-py3-none-any.whl (14.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 MB 99.8 MB/s eta 0:00:00
Requirement already satisfied: ffmpy in /home/user/.local/lib/python3.8/site-packages (from gradio) (0.3.0)
Requirement already satisfied: fastapi in /home/user/.local/lib/python3.8/site-packages (from gradio) (0.89.1)
Requirement already satisfied: typing-extensions in /home/user/.local/lib/python3.8/site-packages (from gradio) (4.4.0)
Requirement already satisfied: pydub in /home/user/.local/lib/python3.8/site-packages (from gradio) (0.25.1)
Requirement already satisfied: pydantic in /home/user/.local/lib/python3.8/site-packages (from gradio) (1.10.4)
Requirement already satisfied: pycryptodome in /home/user/.local/lib/python3.8/site-packages (from gradio) (3.16.0)
Requirement already satisfied: websockets>=10.0 in /home/user/.local/lib/python3.8/site-packages (from gradio) (10.4)
Requirement already satisfied: pyyaml in /home/user/.local/lib/python3.8/site-packages (from gradio) (6.0)
Requirement already satisfied: python-multipart in /home/user/.local/lib/python3.8/site-packages (from gradio) (0.0.5)
Requirement already satisfied: matplotlib in /home/user/.local/lib/python3.8/site-packages (from gradio) (3.6.3)
Requirement already satisfied: markupsafe in /home/user/.local/lib/python3.8/site-packages (from gradio) (2.1.1)
Requirement already satisfied: httpx in /home/user/.local/lib/python3.8/site-packages (from gradio) (0.23.3)
Requirement already satisfied: numpy in /home/user/.local/lib/python3.8/site-packages (from gradio) (1.24.1)
Requirement already satisfied: aiohttp in /home/user/.local/lib/python3.8/site-packages (from gradio) (3.8.3)
Requirement already satisfied: uvicorn in /home/user/.local/lib/python3.8/site-packages (from gradio) (0.20.0)
Requirement already satisfied: pillow in /home/user/.local/lib/python3.8/site-packages (from gradio) (9.4.0)
Requirement already satisfied: altair>=4.2.0 in /home/user/.local/lib/python3.8/site-packages (from gradio) (4.2.0)
Requirement already satisfied: jinja2 in /home/user/.local/lib/python3.8/site-packages (from gradio) (3.1.2)
Requirement already satisfied: requests in /home/user/.local/lib/python3.8/site-packages (from gradio) (2.28.2)
Requirement already satisfied: orjson in /home/user/.local/lib/python3.8/site-packages (from gradio) (3.8.5)
Requirement already satisfied: pandas in /home/user/.local/lib/python3.8/site-packages (from gradio) (1.5.2)
Requirement already satisfied: markdown-it-py[linkify,plugins] in /home/user/.local/lib/python3.8/site-packages (from gradio) (2.1.0)
Requirement already satisfied: fsspec in /home/user/.local/lib/python3.8/site-packages (from gradio) (2022.11.0)
Requirement already satisfied: jsonschema>=3.0 in /home/user/.local/lib/python3.8/site-packages (from altair>=4.2.0->gradio) (4.17.3)
Requirement already satisfied: entrypoints in /home/user/.local/lib/python3.8/site-packages (from altair>=4.2.0->gradio) (0.4)
Requirement already satisfied: toolz in /home/user/.local/lib/python3.8/site-packages (from altair>=4.2.0->gradio) (0.12.0)
Requirement already satisfied: pytz>=2020.1 in /home/user/.local/lib/python3.8/site-packages (from pandas->gradio) (2022.7)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/user/.local/lib/python3.8/site-packages (from pandas->gradio) (2.8.2)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/user/.local/lib/python3.8/site-packages (from aiohttp->gradio) (6.0.4)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /home/user/.local/lib/python3.8/site-packages (from aiohttp->gradio) (2.1.1)
Requirement already satisfied: attrs>=17.3.0 in /home/user/.local/lib/python3.8/site-packages (from aiohttp->gradio) (22.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/user/.local/lib/python3.8/site-packages (from aiohttp->gradio) (1.3.3)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/user/.local/lib/python3.8/site-packages (from aiohttp->gradio) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/user/.local/lib/python3.8/site-packages (from aiohttp->gradio) (1.8.2)
Requirement already satisfied: aiosignal>=1.1.2 in /home/user/.local/lib/python3.8/site-packages (from aiohttp->gradio) (1.3.1)
Requirement already satisfied: starlette==0.22.0 in /home/user/.local/lib/python3.8/site-packages (from fastapi->gradio) (0.22.0)
Requirement already satisfied: anyio<5,>=3.4.0 in /home/user/.local/lib/python3.8/site-packages (from starlette==0.22.0->fastapi->gradio) (3.6.2)
Requirement already satisfied: sniffio in /home/user/.local/lib/python3.8/site-packages (from httpx->gradio) (1.3.0)
Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in /home/user/.local/lib/python3.8/site-packages (from httpx->gradio) (0.16.3)
Requirement already satisfied: certifi in /home/user/.local/lib/python3.8/site-packages (from httpx->gradio) (2022.12.7)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /home/user/.local/lib/python3.8/site-packages (from httpx->gradio) (1.5.0)
Requirement already satisfied: mdurl~=0.1 in /home/user/.local/lib/python3.8/site-packages (from markdown-it-py[linkify,plugins]->gradio) (0.1.2)
Requirement already satisfied: mdit-py-plugins in /home/user/.local/lib/python3.8/site-packages (from markdown-it-py[linkify,plugins]->gradio) (0.3.3)
Requirement already satisfied: linkify-it-py~=1.0 in /home/user/.local/lib/python3.8/site-packages (from markdown-it-py[linkify,plugins]->gradio) (1.0.3)
Requirement already satisfied: packaging>=20.0 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->gradio) (23.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->gradio) (1.4.4)
Requirement already satisfied: contourpy>=1.0.1 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->gradio) (1.0.6)
Requirement already satisfied: fonttools>=4.22.0 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->gradio) (4.38.0)
Requirement already satisfied: cycler>=0.10 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->gradio) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->gradio) (3.0.9)
Requirement already satisfied: six>=1.4.0 in /home/user/.local/lib/python3.8/site-packages (from python-multipart->gradio) (1.16.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/user/.local/lib/python3.8/site-packages (from requests->gradio) (1.26.14)
Requirement already satisfied: idna<4,>=2.5 in /home/user/.local/lib/python3.8/site-packages (from requests->gradio) (3.4)
Requirement already satisfied: h11>=0.8 in /home/user/.local/lib/python3.8/site-packages (from uvicorn->gradio) (0.14.0)
Requirement already satisfied: click>=7.0 in /home/user/.local/lib/python3.8/site-packages (from uvicorn->gradio) (8.0.4)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/user/.local/lib/python3.8/site-packages (from jsonschema>=3.0->altair>=4.2.0->gradio) (1.3.10)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/user/.local/lib/python3.8/site-packages (from jsonschema>=3.0->altair>=4.2.0->gradio) (0.19.3)
Requirement already satisfied: importlib-resources>=1.4.0 in /home/user/.local/lib/python3.8/site-packages (from jsonschema>=3.0->altair>=4.2.0->gradio) (5.10.2)
Requirement already satisfied: uc-micro-py in /home/user/.local/lib/python3.8/site-packages (from linkify-it-py~=1.0->markdown-it-py[linkify,plugins]->gradio) (1.0.1)
Requirement already satisfied: zipp>=3.1.0 in /home/user/.local/lib/python3.8/site-packages (from importlib-resources>=1.4.0->jsonschema>=3.0->altair>=4.2.0->gradio) (3.11.0)
Installing collected packages: gradio
  Attempting uninstall: gradio
    Found existing installation: gradio 3.16.0
    Uninstalling gradio-3.16.0:
      Successfully uninstalled gradio-3.16.0
Successfully installed gradio-3.16.1
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pillow in /home/user/.local/lib/python3.8/site-packages (9.4.0)
/home/user/.local/lib/python3.8/site-packages/gradio/inputs.py:257: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
/home/user/.local/lib/python3.8/site-packages/gradio/deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
/home/user/.local/lib/python3.8/site-packages/gradio/inputs.py:27: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
/home/user/.local/lib/python3.8/site-packages/gradio/deprecation.py:40: UserWarning: `numeric` parameter is deprecated, and it has no effect
  warnings.warn(value)
/home/user/.local/lib/python3.8/site-packages/gradio/outputs.py:43: UserWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components
  warnings.warn(
/home/user/.local/lib/python3.8/site-packages/gradio/utils.py:805: UserWarning: Expected 2 arguments for function <function image_to_silhouette_contours at 0x7f316303a280>, received 1.
  warnings.warn(
/home/user/.local/lib/python3.8/site-packages/gradio/utils.py:809: UserWarning: Expected at least 2 arguments for function <function image_to_silhouette_contours at 0x7f316303a280>, received 1.
  warnings.warn(
Traceback (most recent call last):
  File "app.py", line 33, in <module>
    gr.Interface(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 485, in __init__
    self.render_examples()
  File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 746, in render_examples
    self.examples_handler = Examples(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/helpers.py", line 53, in create_examples
    examples_obj = Examples(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/helpers.py", line 164, in __init__
    raise ValueError(
ValueError: The parameter `examples` must either be a string directory or a list(if there is only 1 input component) or (more generally), a nested list, where each sublist represents a set of inputs.
```

### System Info

```shell
gradio-3.16.1
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @ivanislart !

I believe the issue is that you have multiple inputs but they are not in a list.

Sorry if the formatting is wrong but the following should hopefully fix that error:




gr.Interface(
  image_to_silhouette_contours,
 [ gr.inputs.Image(type="filepath", label="Input"),
  gr.inputs.Textbox(label="File Name"),]
   gr.outputs.Image(type="pil", label="Output")
   ).launch()

**Comment by freddyaboulton** [comment]
BTW, gr.inputs and gr.outputs is deprecated. You should be able to just use gr.Texbox and gr.Image

**Comment by ivanislart** [comment]
Ok, thank you very much, it seems that this partly fixed the error.

Now the interface loads but when I upload an image and try to convert it to a silhouette, I get the text "error" in the output box. 

Do you know how to fix it?

**Comment by freddyaboulton** [comment]
If you click on the “view logs” button, there may be some information there about the error

**Comment by ivanislart** [comment]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /home/user/.local/lib/python3.8/site-packages (22.0.2)
Collecting pip
  Downloading pip-22.3.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 103.1 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    Uninstalling pip-22.0.2:
      Successfully uninstalled pip-22.0.2
Successfully installed pip-22.3.1
Defaulting to user installation because normal site-packages is not writeable
Collecting opencv-python
  Downloading opencv_python-4.7.0.68-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (61.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.8/61.8 MB 54.8 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17.0 in /home/user/.local/lib/python3.8/site-packages (from opencv-python) (1.24.1)
Installing collected packages: opencv-python
Successfully installed opencv-python-4.7.0.68
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: gradio in /home/user/.local/lib/python3.8/site-packages (3.16.0)
Collecting gradio
  Downloading gradio-3.16.1-py3-none-any.whl (14.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.2/14.2 MB 117.5 MB/s eta 0:00:00
Requirement already satisfied: numpy in /home/user/.local/lib/python3.8/site-packages (from gradio) (1.24.1)
Requirement already satisfied: matplotlib in /home/user/.local/lib/python3.8/site-packages (from gradio) (3.6.3)
Requirement already satisfied: python-multipart in /home/user/.local/lib/python3.8/site-packages (from gradio) (0.0.5)
Requirement already satisfied: markdown-it-py[linkify,plugins] in /home/user/.local/lib/python3.8/site-packages (from gradio) (2.1.0)
Requirement already satisfied: typing-extensions in /home/user/.local/lib/python3.8/site-packages (from gradio) (4.4.0)
Requirement already satisfied: pydantic in /home/user/.local/lib/python3.8/site-packages (from gradio) (1.10.4)
Requirement already satisfied: uvicorn in /home/user/.local/lib/python3.8/site-packages (from gradio) (0.20.0)
Requirement already satisfied: websockets>=10.0 in /home/user/.local/lib/python3.8/site-packages (from gradio) (10.4)
Requirement already satisfied: pycryptodome in /home/user/.local/lib/python3.8/site-packages (from gradio) (3.16.0)
Requirement already satisfied: fastapi in /home/user/.local/lib/python3.8/site-packages (from gradio) (0.89.1)
Requirement already satisfied: pyyaml in /home/user/.local/lib/python3.8/site-packages (from gradio) (6.0)
Requirement already satisfied: ffmpy in /home/user/.local/lib/python3.8/site-packages (from gradio) (0.3.0)
Requirement already satisfied: pydub in /home/user/.local/lib/python3.8/site-packages (from gradio) (0.25.1)
Requirement already satisfied: pandas in /home/user/.local/lib/python3.8/site-packages (from gradio) (1.5.2)
Requirement already satisfied: requests in /home/user/.local/lib/python3.8/site-packages (from gradio) (2.28.2)
Requirement already satisfied: orjson in /home/user/.local/lib/python3.8/site-packages (from gradio) (3.8.5)
Requirement already satisfied: httpx in /home/user/.local/lib/python3.8/site-packages (from gradio) (0.23.3)
Requirement already satisfied: markupsafe in /home/user/.local/lib/python3.8/site-packages (from gradio) (2.1.1)
Requirement already satisfied: fsspec in /home/user/.local/lib/python3.8/site-packages (from gradio) (2022.11.0)
Requirement already satisfied: altair>=4.2.0 in /home/user/.local/lib/python3.8/site-packages (from gradio) (4.2.0)
Requirement already satisfied: aiohttp in /home/user/.local/lib/python3.8/site-packages (from gradio) (3.8.3)
Requirement already satisfied: pillow in /home/user/.local/lib/python3.8/site-packages (from gradio) (9.4.0)
Requirement already satisfied: jinja2 in /home/user/.local/lib/python3.8/site-packages (from gradio) (3.1.2)
Requirement already satisfied: entrypoints in /home/user/.local/lib/python3.8/site-packages (from altair>=4.2.0->gradio) (0.4)
Requirement already satisfied: jsonschema>=3.0 in /home/user/.local/lib/python3.8/site-packages (from altair>=4.2.0->gradio) (4.17.3)
Requirement already satisfied: toolz in /home/user/.local/lib/python3.8/site-packages (from altair>=4.2.0->gradio) (0.12.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/user/.local/lib/python3.8/site-packages (from pandas->gradio) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/user/.local/lib/python3.8/site-packages (from pandas->gradio) (2022.7)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/user/.local/lib/python3.8/site-packages (from aiohttp->gradio) (1.8.2)
Requirement already satisfied: aiosignal>=1.1.2 in /home/user/.local/lib/python3.8/site-packages (from aiohttp->gradio) (1.3.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/user/.local/lib/python3.8/site-packages (from aiohttp->gradio) (6.0.4)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /home/user/.local/lib/python3.8/site-packages (from aiohttp->gradio) (2.1.1)
Requirement already satisfied: frozenlist>=1.1.1 in /home/user/.local/lib/python3.8/site-packages (from aiohttp->gradio) (1.3.3)
Requirement already satisfied: attrs>=17.3.0 in /home/user/.local/lib/python3.8/site-packages (from aiohttp->gradio) (22.2.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/user/.local/lib/python3.8/site-packages (from aiohttp->gradio) (4.0.2)
Requirement already satisfied: starlette==0.22.0 in /home/user/.local/lib/python3.8/site-packages (from fastapi->gradio) (0.22.0)
Requirement already satisfied: anyio<5,>=3.4.0 in /home/user/.local/lib/python3.8/site-packages (from starlette==0.22.0->fastapi->gradio) (3.6.2)
Requirement already satisfied: sniffio in /home/user/.local/lib/python3.8/site-packages (from httpx->gradio) (1.3.0)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /home/user/.local/lib/python3.8/site-packages (from httpx->gradio) (1.5.0)
Requirement already satisfied: certifi in /home/user/.local/lib/python3.8/site-packages (from httpx->gradio) (2022.12.7)
Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in /home/user/.local/lib/python3.8/site-packages (from httpx->gradio) (0.16.3)
Requirement already satisfied: mdurl~=0.1 in /home/user/.local/lib/python3.8/site-packages (from markdown-it-py[linkify,plugins]->gradio) (0.1.2)
Requirement already satisfied: mdit-py-plugins in /home/user/.local/lib/python3.8/site-packages (from markdown-it-py[linkify,plugins]->gradio) (0.3.3)
Requirement already satisfied: linkify-it-py~=1.0 in /home/user/.local/lib/python3.8/site-packages (from markdown-it-py[linkify,plugins]->gradio) (1.0.3)
Requirement already satisfied: pyparsing>=2.2.1 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->gradio) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->gradio) (1.0.6)
Requirement already satisfied: fonttools>=4.22.0 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->gradio) (4.38.0)
Requirement already satisfied: packaging>=20.0 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->gradio) (23.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->gradio) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->gradio) (0.11.0)
Requirement already satisfied: six>=1.4.0 in /home/user/.local/lib/python3.8/site-packages (from python-multipart->gradio) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in /home/user/.local/lib/python3.8/site-packages (from requests->gradio) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/user/.local/lib/python3.8/site-packages (from requests->gradio) (1.26.14)
Requirement already satisfied: click>=7.0 in /home/user/.local/lib/python3.8/site-packages (from uvicorn->gradio) (8.0.4)
Requirement already satisfied: h11>=0.8 in /home/user/.local/lib/python3.8/site-packages (from uvicorn->gradio) (0.14.0)
Requirement already satisfied: importlib-resources>=1.4.0 in /home/user/.local/lib/python3.8/site-packages (from jsonschema>=3.0->altair>=4.2.0->gradio) (5.10.2)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/user/.local/lib/python3.8/site-packages (from jsonschema>=3.0->altair>=4.2.0->gradio) (0.19.3)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/user/.local/lib/python3.8/site-packages (from jsonschema>=3.0->altair>=4.2.0->gradio) (1.3.10)
Requirement already satisfied: uc-micro-py in /home/user/.local/lib/python3.8/site-packages (from linkify-it-py~=1.0->markdown-it-py[linkify,plugins]->gradio) (1.0.1)
Requirement already satisfied: zipp>=3.1.0 in /home/user/.local/lib/python3.8/site-packages (from importlib-resources>=1.4.0->jsonschema>=3.0->altair>=4.2.0->gradio) (3.11.0)
Installing collected packages: gradio
  Attempting uninstall: gradio
    Found existing installation: gradio 3.16.0
    Uninstalling gradio-3.16.0:
      Successfully uninstalled gradio-3.16.0
Successfully installed gradio-3.16.1
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pillow in /home/user/.local/lib/python3.8/site-packages (9.4.0)
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
An error occurred: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr for argument 'src'

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 322, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 956, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/components.py", line 1532, in postprocess
    return processing_utils.encode_url_or_file_to_base64(y)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 62, in encode_url_or_file_to_base64
    return encode_file_to_base64(str(path), encryption_key=encryption_key)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 86, in encode_file_to_base64
    with open(f, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'Error'
An error occurred: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr for argument 'src'

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 322, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 956, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/components.py", line 1532, in postprocess
    return processing_utils.encode_url_or_file_to_base64(y)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 62, in encode_url_or_file_to_base64
    return encode_file_to_base64(str(path), encryption_key=encryption_key)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 86, in encode_file_to_base64
    with open(f, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'Error'
An error occurred: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr for argument 'src'

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 322, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 956, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/components.py", line 1532, in postprocess
    return processing_utils.encode_url_or_file_to_base64(y)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 62, in encode_url_or_file_to_base64
    return encode_file_to_base64(str(path), encryption_key=encryption_key)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 86, in encode_file_to_base64
    with open(f, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'Error'
