### ISSUE TITLE
TypeError: create_repo() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by anugrahakbarp** [gradio-app/gradio#2983]
### Describe the bug

Hi, based on the [flagging.py](https://github.com/gradio-app/gradio/blob/main/gradio/flagging.py) I've found an issue regarding the create_repo() from huggingface-hub that used for HuggingFaceDatasetSaver it's not has the same argument as the original code found [here](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/hf_api#huggingface_hub.HfApi.create_repo). I found that the current argument is using **repo_id** NOT **name**. please fix ASAP, thank you :)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
HF_TOKEN = <get the token from [here](https://huggingface.co/settings/tokens)>
hf_writer = gr.HuggingFaceDatasetSaver(HF_TOKEN, "output-gpt2-indo-text-gen")

app = gr.Interface(
fn=<dummy>,
inputs=<dummy>,
outputs=<dummy>,
allow_flagging="manual",
flagging_options=["Inappropriate Word Selection", "Wordy", "Strange Word", "Others"],
flagging_callback=hf_writer,
examples=examples,
title=title,
description=description,
article=article)
```

### Screenshot

![report_for_github_issues](https://user-images.githubusercontent.com/69615570/212493252-73c0ef6b-0e31-401e-8bd9-8104026d5adb.png)

### Logs

```shell
===== Build Queued at 2023-01-14 19:01:57 / Commit SHA: a85c138 =====

--> FROM docker.io/library/python:3.8.9@sha256:49d05fff9cb3b185b15ffd92d8e6bd61c20aa916133dca2e3dbe0215270faf53
DONE 0.0s

--> RUN apt-get update && apt-get install -y 	git 	git-lfs 	ffmpeg 	libsm6 	libxext6 	cmake 	libgl1-mesa-glx 	&& rm -rf /var/lib/apt/lists/* 	&& git lfs install
CACHED

--> COPY --link packages.txt /root/packages.txt
CACHED

--> RUN pip install --no-cache-dir -r requirements.txt
CACHED

--> WORKDIR /home/user/app
CACHED

--> RUN apt-get update && xargs -r -a /root/packages.txt apt-get install -y && rm -rf /var/lib/apt/lists/*
CACHED

--> RUN useradd -m -u 1000 user
CACHED

--> COPY --link --chown=1000 requirements.txt /home/user/app/requirements.txt
CACHED

--> COPY --link --chown=1000 --from=lfs /app /home/user/app
CACHED

--> RUN pip install --no-cache-dir pip==22.0.2 && pip install --no-cache-dir         datasets         huggingface-hub     	"protobuf<4" "click<8.1"
CACHED

--> RUN pip install --no-cache-dir         streamlit==1.15.2         gradio==3.16.1
CACHED

--> COPY --link --chown=1000 --from=lfs /app /home/user/app
CACHED

--> COPY --link --chown=1000 ./ /home/user/app
DONE 0.1s

--> Pushing image
DONE 0.5s

--> Exporting cache
DONE 2.9s

===== Application Startup at 2023-01-14 19:02:09 =====


Downloading:   0%|          | 0.00/241 [00:00Downloading: 100%|██████████| 241/241 [00:00<00:00, 426kB/s]

Downloading:   0%|          | 0.00/808k [00:00Downloading: 100%|██████████| 808k/808k [00:00<00:00, 102MB/s]

Downloading:   0%|          | 0.00/1.38M [00:00Downloading: 100%|██████████| 1.38M/1.38M [00:00<00:00, 95.1MB/s]

Downloading:   0%|          | 0.00/24.0 [00:00Downloading: 100%|██████████| 24.0/24.0 [00:00<00:00, 52.6kB/s]

Downloading:   0%|          | 0.00/90.0 [00:00Downloading: 100%|██████████| 90.0/90.0 [00:00<00:00, 226kB/s]

Downloading:   0%|          | 0.00/893 [00:00Downloading: 100%|██████████| 893/893 [00:00<00:00, 1.40MB/s]

Downloading:   0%|          | 0.00/1.44G [00:00Downloading:   1%|          | 10.3M/1.44G [00:00<00:13, 103MB/s]
Downloading:   1%|▏         | 20.9M/1.44G [00:00<00:13, 105MB/s]
Downloading:   2%|▏         | 31.3M/1.44G [00:00<00:17, 80.7MB/s]
Downloading:   3%|▎         | 42.8M/1.44G [00:00<00:15, 92.2MB/s]
Downloading:   4%|▎         | 52.6M/1.44G [00:00<00:15, 92.6MB/s]
Downloading:   4%|▍         | 62.2M/1.44G [00:00<00:15, 92.2MB/s]
Downloading:   5%|▍         | 71.6M/1.44G [00:00<00:14, 92.4MB/s]
Downloading:   6%|▌         | 82.2M/1.44G [00:00<00:14, 96.5MB/s]
Downloading:   6%|▋         | 93.7M/1.44G [00:00<00:13, 102MB/s] 
Downloading:   7%|▋         | 105M/1.44G [00:01<00:14, 89.4MB/s]
Downloading:   8%|▊         | 114M/1.44G [00:01<00:15, 86.7MB/s]
Downloading:   9%|▊         | 123M/1.44G [00:01<00:14, 88.9MB/s]
Downloading:   9%|▉         | 133M/1.44G [00:01<00:14, 90.4MB/s]
Downloading:  10%|▉         | 143M/1.44G [00:01<00:13, 93.3MB/s]
Downloading:  11%|█         | 152M/1.44G [00:01<00:16, 80.5MB/s]
Downloading:  11%|█         | 161M/1.44G [00:01<00:17, 73.2MB/s]
Downloading:  12%|█▏        | 168M/1.44G [00:01<00:19, 66.3MB/s]
Downloading:  12%|█▏        | 175M/1.44G [00:02<00:20, 62.1MB/s]
Downloading:  13%|█▎        | 182M/1.44G [00:02<00:21, 59.0MB/s]
Downloading:  13%|█▎        | 188M/1.44G [00:02<00:22, 56.8MB/s]
Downloading:  13%|█▎        | 194M/1.44G [00:02<00:22, 54.8MB/s]
Downloading:  14%|█▍        | 199M/1.44G [00:02<00:23, 53.9MB/s]
Downloading:  14%|█▍        | 205M/1.44G [00:02<00:22, 54.2MB/s]
Downloading:  15%|█▍        | 211M/1.44G [00:02<00:22, 55.5MB/s]
Downloading:  15%|█▍        | 216M/1.44G [00:02<00:21, 56.3MB/s]
Downloading:  15%|█▌        | 222M/1.44G [00:03<00:22, 54.8MB/s]
Downloading:  16%|█▌        | 227M/1.44G [00:03<00:22, 54.1MB/s]
Downloading:  16%|█▌        | 233M/1.44G [00:03<00:22, 52.9MB/s]
Downloading:  16%|█▋        | 238M/1.44G [00:03<00:23, 52.1MB/s]
Downloading:  17%|█▋        | 244M/1.44G [00:03<00:22, 53.9MB/s]
Downloading:  17%|█▋        | 250M/1.44G [00:03<00:21, 55.0MB/s]
Downloading:  18%|█▊        | 255M/1.44G [00:03<00:23, 50.4MB/s]
Downloading:  18%|█▊        | 260M/1.44G [00:03<00:24, 47.9MB/s]
Downloading:  18%|█▊        | 266M/1.44G [00:03<00:23, 50.1MB/s]
Downloading:  19%|█▉        | 272M/1.44G [00:03<00:22, 51.4MB/s]
Downloading:  19%|█▉        | 277M/1.44G [00:04<00:22, 52.6MB/s]
Downloading:  20%|█▉        | 283M/1.44G [00:04<00:21, 53.6MB/s]
Downloading:  20%|█▉        | 288M/1.44G [00:04<00:21, 54.6MB/s]
Downloading:  20%|██        | 294M/1.44G [00:04<00:20, 54.9MB/s]
Downloading:  21%|██        | 300M/1.44G [00:04<00:20, 55.0MB/s]
Downloading:  21%|██        | 306M/1.44G [00:04<00:20, 56.9MB/s]
Downloading:  22%|██▏       | 312M/1.44G [00:04<00:19, 57.6MB/s]
Downloading:  22%|██▏       | 319M/1.44G [00:04<00:18, 61.9MB/s]
Downloading:  23%|██▎       | 328M/1.44G [00:04<00:15, 70.8MB/s]
Downloading:  23%|██▎       | 336M/1.44G [00:04<00:15, 73.5MB/s]
Downloading:  24%|██▍       | 343M/1.44G [00:05<00:15, 70.3MB/s]
Downloading:  24%|██▍       | 353M/1.44G [00:05<00:14, 77.9MB/s]
Downloading:  25%|██▌       | 364M/1.44G [00:05<00:12, 88.7MB/s]
Downloading:  26%|██▌       | 376M/1.44G [00:05<00:11, 96.6MB/s]
Downloading:  27%|██▋       | 388M/1.44G [00:05<00:10, 104MB/s] 
Downloading:  28%|██▊       | 400M/1.44G [00:05<00:09, 109MB/s]
Downloading:  29%|██▊       | 412M/1.44G [00:05<00:09, 112MB/s]
Downloading:  29%|██▉       | 424M/1.44G [00:05<00:09, 113MB/s]
Downloading:  30%|███       | 436M/1.44G [00:05<00:08, 115MB/s]
Downloading:  31%|███       | 447M/1.44G [00:05<00:08, 116MB/s]
Downloading:  32%|███▏      | 459M/1.44G [00:06<00:08, 117MB/s]
Downloading:  33%|███▎      | 471M/1.44G [00:06<00:08, 118MB/s]
Downloading:  33%|███▎      | 483M/1.44G [00:06<00:08, 118MB/s]
Downloading:  34%|███▍      | 495M/1.44G [00:06<00:08, 119MB/s]
Downloading:  35%|███▌      | 507M/1.44G [00:06<00:08, 115MB/s]
Downloading:  36%|███▌      | 519M/1.44G [00:06<00:07, 117MB/s]
Downloading:  37%|███▋      | 531M/1.44G [00:06<00:08, 108MB/s]
Downloading:  38%|███▊      | 543M/1.44G [00:06<00:08, 112MB/s]
Downloading:  38%|███▊      | 555M/1.44G [00:07<00:09, 91.8MB/s]
Downloading:  39%|███▉      | 565M/1.44G [00:07<00:10, 86.9MB/s]
Downloading:  40%|███▉      | 576M/1.44G [00:07<00:14, 61.4MB/s]
Downloading:  40%|████      | 584M/1.44G [00:07<00:14, 57.8MB/s]
Downloading:  41%|████      | 595M/1.44G [00:07<00:12, 69.5MB/s]
Downloading:  42%|████▏     | 604M/1.44G [00:07<00:15, 54.7MB/s]
Downloading:  43%|████▎     | 615M/1.44G [00:08<00:12, 65.2MB/s]
Downloading:  43%|████▎     | 626M/1.44G [00:08<00:10, 74.7MB/s]
Downloading:  44%|████▍     | 635M/1.44G [00:08<00:14, 55.4MB/s]
Downloading:  45%|████▍     | 645M/1.44G [00:08<00:12, 65.6MB/s]
Downloading:  45%|████▌     | 655M/1.44G [00:08<00:12, 62.7MB/s]
Downloading:  46%|████▌     | 662M/1.44G [00:08<00:12, 64.5MB/s]
Downloading:  47%|████▋     | 673M/1.44G [00:08<00:10, 74.3MB/s]
Downloading:  47%|████▋     | 681M/1.44G [00:09<00:12, 60.5MB/s]
Downloading:  48%|████▊     | 693M/1.44G [00:09<00:10, 73.2MB/s]
Downloading:  49%|████▉     | 705M/1.44G [00:09<00:08, 83.7MB/s]
Downloading:  49%|████▉     | 714M/1.44G [00:09<00:11, 64.5MB/s]
Downloading:  50%|█████     | 726M/1.44G [00:09<00:09, 76.5MB/s]
Downloading:  51%|█████     | 738M/1.44G [00:09<00:08, 86.7MB/s]
Downloading:  52%|█████▏    | 751M/1.44G [00:09<00:07, 95.4MB/s]
Downloading:  53%|█████▎    | 763M/1.44G [00:09<00:06, 102MB/s] 
Downloading:  54%|█████▎    | 775M/1.44G [00:10<00:06, 108MB/s]
Downloading:  54%|█████▍    | 786M/1.44G [00:10<00:06, 105MB/s]
Downloading:  55%|█████▌    | 798M/1.44G [00:10<00:05, 109MB/s]
Downloading:  56%|█████▌    | 810M/1.44G [00:10<00:05, 112MB/s]
Downloading:  57%|█████▋    | 822M/1.44G [00:10<00:07, 85.3MB/s]
Downloading:  58%|█████▊    | 833M/1.44G [00:10<00:06, 91.9MB/s]
Downloading:  58%|█████▊    | 845M/1.44G [00:10<00:07, 83.1MB/s]
Downloading:  59%|█████▉    | 854M/1.44G [00:11<00:10, 58.9MB/s]
Downloading:  60%|█████▉    | 864M/1.44G [00:11<00:10, 55.4MB/s]
Downloading:  61%|██████    | 875M/1.44G [00:11<00:08, 64.8MB/s]
Downloading:  61%|██████▏   | 886M/1.44G [00:11<00:07, 74.1MB/s]
Downloading:  62%|██████▏   | 895M/1.44G [00:11<00:09, 59.0MB/s]
Downloading:  63%|██████▎   | 906M/1.44G [00:11<00:07, 69.9MB/s]
Downloading:  63%|██████▎   | 915M/1.44G [00:12<00:08, 64.0MB/s]
Downloading:  64%|██████▍   | 922M/1.44G [00:12<00:08, 63.9MB/s]
Downloading:  65%|██████▍   | 934M/1.44G [00:12<00:06, 77.2MB/s]
Downloading:  65%|██████▌   | 946M/1.44G [00:12<00:05, 87.2MB/s]
Downloading:  66%|██████▋   | 958M/1.44G [00:12<00:05, 95.4MB/s]
Downloading:  67%|██████▋   | 968M/1.44G [00:12<00:06, 77.1MB/s]
Downloading:  68%|██████▊   | 977M/1.44G [00:12<00:07, 60.8MB/s]
Downloading:  68%|██████▊   | 989M/1.44G [00:12<00:06, 72.9MB/s]
Downloading:  69%|██████▉   | 998M/1.44G [00:13<00:06, 72.9MB/s]
Downloading:  70%|██████▉   | 1.01G/1.44G [00:13<00:05, 83.7MB/s]
Downloading:  71%|███████   | 1.02G/1.44G [00:13<00:05, 82.8MB/s]
Downloading:  71%|███████▏  | 1.03G/1.44G [00:13<00:04, 84.7MB/s]
Downloading:  72%|███████▏  | 1.04G/1.44G [00:13<00:04, 93.7MB/s]
Downloading:  73%|███████▎  | 1.05G/1.44G [00:13<00:05, 69.5MB/s]
Downloading:  74%|███████▎  | 1.07G/1.44G [00:13<00:04, 80.5MB/s]
Downloading:  74%|███████▍  | 1.07G/1.44G [00:14<00:04, 83.0MB/s]
Downloading:  75%|███████▌  | 1.08G/1.44G [00:14<00:04, 85.9MB/s]
Downloading:  76%|███████▌  | 1.09G/1.44G [00:14<00:03, 89.2MB/s]
Downloading:  76%|███████▋  | 1.10G/1.44G [00:14<00:04, 72.4MB/s]
Downloading:  77%|███████▋  | 1.11G/1.44G [00:14<00:04, 80.7MB/s]
Downloading:  78%|███████▊  | 1.13G/1.44G [00:14<00:03, 89.3MB/s]
Downloading:  79%|███████▊  | 1.14G/1.44G [00:14<00:04, 74.3MB/s]
Downloading:  79%|███████▉  | 1.15G/1.44G [00:14<00:03, 80.9MB/s]
Downloading:  80%|███████▉  | 1.15G/1.44G [00:15<00:04, 63.5MB/s]
Downloading:  80%|████████  | 1.16G/1.44G [00:15<00:04, 64.1MB/s]
Downloading:  81%|████████  | 1.17G/1.44G [00:15<00:03, 76.8MB/s]
Downloading:  82%|████████▏ | 1.18G/1.44G [00:15<00:03, 81.6MB/s]
Downloading:  83%|████████▎ | 1.19G/1.44G [00:15<00:04, 57.9MB/s]
Downloading:  83%|████████▎ | 1.20G/1.44G [00:15<00:03, 70.4MB/s]
Downloading:  84%|████████▍ | 1.21G/1.44G [00:15<00:03, 62.0MB/s]
Downloading:  85%|████████▍ | 1.22G/1.44G [00:16<00:03, 62.6MB/s]
Downloading:  85%|████████▌ | 1.23G/1.44G [00:16<00:04, 50.9MB/s]
Downloading:  86%|████████▌ | 1.24G/1.44G [00:16<00:03, 61.1MB/s]
Downloading:  87%|████████▋ | 1.25G/1.44G [00:16<00:02, 73.3MB/s]
Downloading:  87%|████████▋ | 1.26G/1.44G [00:16<00:03, 60.3MB/s]
Downloading:  88%|████████▊ | 1.27G/1.44G [00:16<00:02, 72.6MB/s]
Downloading:  89%|████████▉ | 1.28G/1.44G [00:17<00:02, 76.1MB/s]
Downloading:  89%|████████▉ | 1.29G/1.44G [00:17<00:02, 74.4MB/s]
Downloading:  90%|█████████ | 1.30G/1.44G [00:17<00:01, 85.8MB/s]
Downloading:  91%|█████████ | 1.31G/1.44G [00:17<00:01, 72.3MB/s]
Downloading:  92%|█████████▏| 1.32G/1.44G [00:17<00:01, 81.2MB/s]
Downloading:  92%|█████████▏| 1.34G/1.44G [00:17<00:01, 73.9MB/s]
Downloading:  93%|█████████▎| 1.34G/1.44G [00:17<00:01, 62.2MB/s]
Downloading:  94%|█████████▍| 1.35G/1.44G [00:17<00:01, 72.4MB/s]
Downloading:  94%|█████████▍| 1.36G/1.44G [00:18<00:01, 67.5MB/s]
Downloading:  95%|█████████▍| 1.37G/1.44G [00:18<00:01, 69.9MB/s]
Downloading:  96%|█████████▌| 1.38G/1.44G [00:18<00:00, 82.5MB/s]
Downloading:  96%|█████████▋| 1.39G/1.44G [00:18<00:00, 63.9MB/s]
Downloading:  97%|█████████▋| 1.40G/1.44G [00:18<00:00, 68.0MB/s]
Downloading:  98%|█████████▊| 1.41G/1.44G [00:18<00:00, 80.9MB/s]
Downloading:  98%|█████████▊| 1.42G/1.44G [00:19<00:00, 45.9MB/s]
Downloading:  99%|█████████▉| 1.43G/1.44G [00:19<00:00, 58.2MB/s]
Downloading: 100%|█████████▉| 1.44G/1.44G [00:19<00:00, 60.7MB/s]
Downloading: 100%|██████████| 1.44G/1.44G [00:19<00:00, 74.2MB/s]
Traceback (most recent call last):
  File "app.py", line 75, in 
    app = gr.Interface(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 428, in __init__
    self.flagging_callback.setup(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/flagging.py", line 329, in setup
    path_to_dataset_repo = huggingface_hub.create_repo(
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/utils/_deprecation.py", line 31, in inner_f
    return f(*args, **kwargs)
TypeError: create_repo() got an unexpected keyword argument 'name'
```

### System Info

```shell
gradio==3.16.1
huggingface-hub==0.11.1
protobuf==3.19.6
torch==1.12.1
torchaudio==0.12.1
torchvision==0.13.1
transformers==4.25.1
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Thanks @anugrahakbarp, we'll take a look!
