### ISSUE TITLE
Path.resolve break symlink and result in error

### ISSUE THREAD

**Issue by KohakuBlueleaf** [gradio-app/gradio#3024]
### Describe the bug

I use mklink to make symlink to my NAS' folder (connect with smb), and when it return the img with its path, the path become original smb path (\\\\server\\...\\..) and just broken all things

(I'm using A1111's sd-webui but this issue is more like gradio's bug)

For now, I just replace all the Path.resolve to Path.absolute and it works great now.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

use a1111's sd-webui, set output dir to an symlink to SMB folder (on windows)

and will get something like this:
```
ValueError: File cannot be fetched: /192.168.88.239/MainNas/sd-webui/main-outputs/txt2img-images/01335-2023-01-20_d7ff2a1d60_KBlueLeaf_KBlueLeaf_3273134466-512x512.png. 
All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
```

### Logs

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\apoll\Desktop\application\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 286, in file
    raise ValueError(
ValueError: File cannot be fetched: /192.168.88.239/MainNas/sd-webui/main-outputs/txt2img-images/01335-2023-01-20_d7ff2a1d60_KBlueLeaf_KBlueLeaf_3273134466-512x512.png. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
```

### System Info

```shell
python 3.10.8
Gradio 3.16.2
Windows 11
Microsoft Edge
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Thanks for raising this issue @KohakuBlueleaf. This seems to be an edge case of `pathlib.Path.resolve()`: https://discuss.python.org/t/pathlib-absolute-vs-resolve/2573/3

I'm hesitant to switch over to `pathlib.Path.absolute()` since that has its own issues: https://stackoverflow.com/questions/42513056/how-to-get-absolute-path-of-a-pathlib-path-object/44569249#44569249

Switching back to `os.path.abspath` is not ideal either, so I'm not sure where to proceed. Any suggestions are welcome!

**Comment by abidlabs** [comment]
Ok we're working on a fix: #3037

**Comment by KohakuBlueleaf** [comment]
@abidlabs I found some way to avoid this problem without change code in gradio but it would be great to not resolve the aymlink, Since this can be a potential risk for safety.
(A main reason to use symlink is to fake the actual path)

It's happy to see you work on it so fast!

**Comment by abidlabs** [comment]
Yes so the current approach in #3037 is to first detect if a path is a symlink, if so, it is not resolved, it is just made absolute. On the other hand, if a path is not a symlink, it is both resolved and made absolute.

**Comment by KohakuBlueleaf** [comment]
Yes it works and looks good.
Thank you!

**Comment by louis-she** [comment]
I'm still facing this issue with symbolic folder. I'm make the `extension` folder of stable-diffusion-web-ui a symbolic , and if it trys to fetch one of the sub file in the extension folder, same error raised. Here is the full exception:

```bash
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/featurize/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 337, in file
    raise ValueError(
ValueError: File cannot be fetched: extensions/sd-web-ui-kitchen-theme/style.css. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
```

**Comment by louis-she** [comment]
some experiments, making a symbolic folder first.

```bash
ln -s /home/featurize/work/app/stable-difussion/extensions /home/featurize/stable-diffusion-webui/extensions
```
then let's test `gradio.utils.abspath`

```python
>>> from gradio import utils
>>> from pathlib import Path
>>> 
>>> utils.abspath("extensions/sd-web-ui-kitchen-theme/javascript/index.js")
PosixPath('/home/featurize/work/app/stable-difussion/extensions/sd-web-ui-kitchen-theme/javascript/index.js')
>>> Path("extensions/sd-web-ui-kitchen-theme/style.css").absolute()
PosixPath('/home/featurize/stable-diffusion-webui/extensions/sd-web-ui-kitchen-theme/style.css')
```
