### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.cache/huggingface/hub/models--anugrahap--gpt2-indo-textgen/refs/main'

### ISSUE THREAD

**Issue by anugrahakbarp** [gradio-app/gradio#3041]
### Describe the bug
Hi, I found some weird error after upgrading to Gradio 3.16.2 for trying the Flagging **HuggingFaceDatasetSaver**. It throwback the error `"FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.cache/huggingface/hub/models--anugrahap--gpt2-indo-textgen/refs/main'"`

It happens after the Gradio 3.16.2 has been released, now my app even can't run anymore _(except to downgrade to the 3.16.1)_.

===========
I put my whole code for the app.py that you can paste on colab and spaces, please help @abidlabs 

more info for the spaces repository you can check here: 
[https://huggingface.co/spaces/anugrahap/gpt2-indo-textgen/tree/main](https://huggingface.co/spaces/anugrahap/gpt2-indo-textgen/tree/main)

Thank you in advance before :)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
#this is version two with flagging features
import gradio as gr
from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM

# initialize the environment
model_name = 'anugrahap/gpt2-indo-textgen'
HF_TOKEN = 'xxx'
hf_writer = gr.HuggingFaceDatasetSaver(HF_TOKEN, "output-gpt2-indo-textgen")

# # define the tokenization method
# tokenizer = AutoTokenizer.from_pretrained(model_name,
#                                           model_max_length=1e30,
#                                           padding_side='right',
#                                           return_tensors='pt')

# # add the EOS token as PAD token to avoid warnings
# model = AutoModelForCausalLM.from_pretrained(model_name, pad_token_id=tokenizer.eos_token_id)

generator = pipeline('text-generation', model=model_name)

# create the decoder parameter to generate the text
def single_generation(text,min_length,max_length,temperature,top_k,top_p,num_beams,repetition_penalty,do_sample):
    # create local variable for error parameter    
    error_rep=ValueError(f"ERROR: repetition penalty cannot be lower than one! Given rep penalty = {repetition_penalty}")
    error_temp=ValueError(f"ERROR: temperature cannot be zero or lower! Given temperature = {temperature}")
    error_minmax=ValueError(f"ERROR: min length must be lower than or equal to max length! Given min length = {min_length}")
    error_numbeams_type=TypeError(f"ERROR: number of beams must be an integer not {type(num_beams)}")
    error_topk_type=TypeError(f"ERROR: top k must be an integer not {type(top_k)}")
    error_minmax_type=TypeError(f"ERROR: min length and max length must be an integer not {type(min_length)} and {type(max_length)}")   
    error_empty=ValueError("ERROR: Input Text cannot be empty!")
    error_unknown=TypeError("Unknown Error.")

    if text != '':
        if type(min_length) == int and type(max_length) == int:
            if type(top_k) == int:
                if type(num_beams) == int:
                    if min_length <= max_length:
                        if temperature > 0:
                            if repetition_penalty >= 1:
                                result = generator(text,
                                                   min_length=min_length,
                                                   max_length=max_length,
                                                   temperature=temperature,
                                                   top_k=top_k,
                                                   top_p=top_p,
                                                   num_beams=num_beams,
                                                   repetition_penalty=repetition_penalty,
                                                   do_sample=do_sample,
                                                   no_repeat_ngram_size=2,
                                                   num_return_sequences=1)
                                return result[0]["generated_text"]
                            elif repetition_penalty < 1:
                                return error_rep
                        elif temperature <= 0:
                            return error_temp
                    elif min_length > max_length:
                        return error_minmax
                elif type(num_beams) != int:
                    return error_numbeams_type
            elif type(top_k) != int:
                return error_topk_type
        elif type(min_length) != int or type(max_length) != int:
            return error_minmax_type  
    elif text == '':
        return error_empty
    else:
        return error_unknown

# create the decoder parameter to generate the text
def multiple_generation(text,min_length,max_length,temperature,top_k,top_p,num_beams,repetition_penalty,do_sample):
    # create local variable for error parameter    
    error_rep=ValueError(f"ERROR: repetition penalty cannot be lower than one! Given rep penalty = {repetition_penalty}")
    error_temp=ValueError(f"ERROR: temperature cannot be zero or lower! Given temperature = {temperature}")
    error_minmax=ValueError(f"ERROR: min length must be lower than or equal to max length! Given min length = {min_length}")
    error_numbeams_type=TypeError(f"ERROR: number of beams must be an integer not {type(num_beams)}")
    error_topk_type=TypeError(f"ERROR: top k must be an integer not {type(top_k)}")
    error_minmax_type=TypeError(f"ERROR: min length and max length must be an integer not {type(min_length)} and {type(max_length)}")   
    error_empty=ValueError("ERROR: Input Text cannot be empty!")
    error_unknown=TypeError("Unknown Error.")

    if text != '':
        if type(min_length) == int and type(max_length) == int:
            if type(top_k) == int:
                if type(num_beams) == int:
                    if min_length <= max_length:
                        if temperature > 0:
                            if repetition_penalty >= 1:
                                result = generator(text,
                                                   min_length=min_length,
                                                   max_length=max_length,
                                                   temperature=temperature,
                                                   top_k=top_k,
                                                   top_p=top_p,
                                                   num_beams=num_beams,
                                                   repetition_penalty=repetition_penalty,
                                                   do_sample=do_sample,
                                                   no_repeat_ngram_size=2,
                                                   num_return_sequences=3)
                                return result[0]["generated_text"], result[1]["generated_text"], result[2]["generated_text"],
                            elif repetition_penalty < 1:
                                return error_rep,error_rep,error_rep
                        elif temperature <= 0:
                            return error_temp,error_temp,error_temp
                    elif min_length > max_length:
                        return error_minmax,error_minmax,error_minmax
                elif type(num_beams) != int:
                    return error_numbeams_type,error_numbeams_type,error_numbeams_type
            elif type(top_k) != int:
                return error_topk_type,error_topk_type,error_topk_type
        elif type(min_length) != int or type(max_length) != int:
            return  error_minmax_type,error_minmax_type,error_minmax_type
    elif text == '':
        return error_empty,error_empty,error_empty
    else:
        return error_unknown,error_unknown,error_unknown


# create the variable needed for the gradio app
forinput=[gr.Textbox(lines=5, label="Input Text"),
        gr.Slider(label="Min Length", minimum=10, maximum=50, value=10, step=5),
        gr.Slider(label="Max Length", minimum=10, maximum=100, value=30, step=10),
        gr.Number(label="Temperature Sampling", value=1.5),
        gr.Slider(label="Top K Sampling", minimum=0, maximum=100, value=30, step=5),
        gr.Slider(label="Top P Sampling", minimum=0.01, maximum=1, value=0.93),
        gr.Slider(label="Number of Beams", minimum=1, maximum=10, value=5, step=1),
        gr.Number(label="Rep Penalty", value=2.0),
        gr.Dropdown(label="Do Sample?", choices=[True,False], value=True, multiselect=False)]

output1=gr.Textbox(lines=5, max_lines=50, label="Generated Text with Greedy/Beam Search Decoding")

output2=[gr.Textbox(lines=5, max_lines=50, label="#1 Generated Text with Greedy/Beam Search Decoding"),
         gr.Textbox(lines=5, max_lines=50, label="#2 Generated Text with Greedy/Beam Search Decoding"),
         gr.Textbox(lines=5, max_lines=50, label="#3 Generated Text with Greedy/Beam Search Decoding")]

examples = [
    ["Indonesia adalah negara kepulauan", 10, 30, 1.0, 25, 0.92, 5, 2.0, True],
    ["Indonesia adalah negara kepulauan", 10, 30, 1.0, 25, 0.92, 5, 1.0, False],
    ["Skripsi merupakan tugas akhir mahasiswa", 20, 40, 1.0, 50, 0.92, 1, 2.0, True],
    ["Skripsi merupakan tugas akhir mahasiswa", 20, 40, 1.0, 50, 0.92, 1, 1.0, False],
    ["Pemandangan di pantai kuta Bali sangatlah indah.", 30, 50, 0.5, 40, 0.98, 10, 1.0, True],
    ["Pemandangan di pantai kuta Bali sangatlah indah.", 10, 30, 1.5, 30, 0.93, 5, 2.0, True]]

title = """
    <style>
    .center {
    display: block;
    margin-top: 20px;
    margin-down: 0px;
    margin-left: auto;
    margin-right: auto;
    }
    </style>
    <style>
    h1 {
    text-align: center;
    margin-top: 0px;
    }
    </style>
    <img src="https://iili.io/HayCG44.md.png"
    alt="Q-GEN Logo"
    border="0" 
    class="center"
    style="height: 100px; width: 100px;"/>
    <h1>GPT-2 Indonesian Text Generation Playground</h1>"""

description = "<p><i>This project is a part of thesis requirement of Anugrah Akbar Praramadhan</i></p>"

article = """<p style='text-align: center'>Copyright Anugrah Akbar Praramadhan 2023 <br>
    <p style='text-align: center'> Trained on Indo4B Benchmark Dataset of Indonesian language Wikipedia with a Causal Language Modeling (CLM) objective <br>
    <p style='text-align: center'><a href='https://huggingface.co/anugrahap/gpt2-indo-textgen' target='_blank'>Link to the Trained Model</a><br>
    <p style='text-align: center'><a href='https://huggingface.co/spaces/anugrahap/gpt2-indo-text-gen/tree/main' target='_blank'>Link to the Project Repository</a><br>
    <p style='text-align: center'><a href='https://huggingface.co/datasets/anugrahap/output-gpt2-indo-textgen/' target='_blank'>Link to the Autosaved Generated Output</a><br>
    <p style='text-align: center'><a href='https://d4mucfpksywv.cloudfront.net/better-language-models/language_models_are_unsupervised_multitask_learners.pdf' target='_blank'>Original Paper</a>
    """

# using gradio interfaces
app1 = gr.Interface(
    fn=single_generation,
    inputs=forinput,
    outputs=output1,
    examples=examples,
    title=title,
    description=description,
    article=article,
    allow_flagging='manual',
    flagging_options=['Well Performed', 'Inappropriate Word Selection', 'Wordy', 'Strange Word', 'Others'],
    flagging_callback=hf_writer)

app2 = gr.Interface(
    fn=multiple_generation,
    inputs=forinput,
    outputs=output2,
    examples=examples,
    title=title,
    description=description,
    article=article,
    allow_flagging='manual',
    flagging_options=['Well Performed', 'Inappropriate Word Selection', 'Wordy', 'Strange Word', 'Others'],
    flagging_callback=hf_writer)

# combining both interface
final_app = gr.TabbedInterface(interface_list=[app1, app2], tab_names=["Single Generation", "Multiple Generation"])


if __name__=='__main__':
    final_app.launch()

```

### Logs

```shell
===== Application Startup at 2023-01-22 15:32:52 =====

Traceback (most recent call last):
  File "app.py", line 9, in 
    tokenizer = AutoTokenizer.from_pretrained(model_name,
  File "/home/user/.local/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 582, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 433, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/home/user/.local/lib/python3.8/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1150, in hf_hub_download
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.cache/huggingface/hub/models--anugrahap--gpt2-indo-textgen/refs/main'
```

### System Info

```shell
gradio==3.16.2
huggingface-hub==0.11.1
protobuf==3.19.6
torch==1.12.1
torchaudio==0.12.1
torchvision==0.13.1
transformers==4.25.1
```

### Severity

blocking upgrade to latest gradio version

**Comment by freddyaboulton** [comment]
Hi @anugrahakbarp !

I think the current problem will be fixed in the next release of gradio. Sometime this week or next. 

I cloned your space and installed the latest gradio and the error now seems to be coming from `transformer`, not gradio.

```
 File "/home/user/.local/lib/python3.8/site-packages/transformers/generation/utils.py", line 1513, in generate
    raise ValueError(
ValueError: num_return_sequences has to be 1, but is 3 when doing greedy search.
```

You can see the space here: https://huggingface.co/spaces/freddyaboulton/gpt2-indo-textgen

**Comment by anugrahakbarp** [comment]
Hi @freddyaboulton 

Cool, I will take a look and try again after the next gradio update. If the problem on the Transformers I should take a look again with my code since the spaces that you're cloning is the 2nd version of my app for a testing and adding some features. The previous one is already deployed on another link of spaces.

Thank you in advance, regards

Anugrah.

**Comment by freddyaboulton** [comment]
Hi @anugrahakbarp - I [duplicated your space](https://huggingface.co/spaces/freddyaboulton/gpt2-indo-textgen
) and installed the latest gradio and now there is an error coming from transformers

```
  File "/home/user/.local/lib/python3.8/site-packages/transformers/pipelines/text_generation.py", line 202, in __call__
    return super().__call__(text_inputs, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/transformers/pipelines/base.py", line 1074, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/home/user/.local/lib/python3.8/site-packages/transformers/pipelines/base.py", line 1081, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/home/user/.local/lib/python3.8/site-packages/transformers/pipelines/base.py", line 990, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/home/user/.local/lib/python3.8/site-packages/transformers/pipelines/text_generation.py", line 244, in _forward
    generated_sequence = self.model.generate(input_ids=input_ids, attention_mask=attention_mask, **generate_kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/transformers/generation/utils.py", line 1513, in generate
    raise ValueError(
ValueError: num_return_sequences has to be 1, but is 3 when doing greedy search.
```

Going to close this as this is not a gradio issue! Thanks for filing.
