### ISSUE TITLE
Error when try create audio file and send to HTML audio component

### ISSUE THREAD

**Issue by paulocoutinhox** [gradio-app/gradio#3128]
### Describe the bug

Im trying to save an audio file, send to a folder that can be accessed by gradio server to show on `audio` html component.

```
def form_submit(state, text_to_process):
    [...]
    audio_config = speechsdk.audio.AudioOutputConfig(filename="audio.mp3")

    temp_file_manager = gr.processing_utils.TempFileManager()
    file_obj = temp_file_manager.make_temp_copy_if_needed("audio.mp3")

    state = state + [(result_text, '<audio controls src="/file='+file_obj+'"></audio>')]

    return state, state
```

It output this path:

```
<audio controls="" src="/file=/private/var/folders/_j/97qz65y57c56y7394rt316lc0000gn/T/audioe2684b618bb0f11dfa5ce7a48889b6aa11837c9e.mp3"></audio>
```

The error is:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/gradio/routes.py", line 293, in file
    raise ValueError(
ValueError: File cannot be fetched: /private/var/folders/_j/97qz65y57c56y7394rt316lc0000gn/T/audioe2684b618bb0f11dfa5ce7a48889b6aa11837c9e.mp3. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import os
import openai

import azure.cognitiveservices.speech as speechsdk
import gradio as gr


def form_submit(state, text_to_process):
    if not text_to_process:
        text_to_process = "me fale, em uma frase, algo sobre o james webb"

    # call openai api
    openai.api_key = os.getenv("OPENAI_API_KEY")

    response = openai.Completion.create(
        engine="text-davinci-002",
        prompt=text_to_process,
        temperature=0.7,
        max_tokens=100,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0,
    )

    result_text = response.choices[0].text

    if result_text:
        result_text = result_text.strip()

    # requires environment variables named "SPEECH_KEY" and "SPEECH_REGION"
    speech_config = speechsdk.SpeechConfig(
        subscription=os.environ.get("SPEECH_KEY"),
        region=os.environ.get("SPEECH_REGION"),
    )
    audio_config = speechsdk.audio.AudioOutputConfig(filename="audio.mp3")

    temp_file_manager = gr.processing_utils.TempFileManager()
    file_obj = temp_file_manager.make_temp_copy_if_needed("audio.mp3")

    # the language of the voice that speaks (https://speech.microsoft.com/portal/voicegallery)
    speech_config.speech_synthesis_voice_name = "pt-BR-FabioNeural"

    speech_synthesizer = speechsdk.SpeechSynthesizer(
        speech_config=speech_config, audio_config=audio_config
    )

    # get text from gradio
    speech_synthesis_result = speech_synthesizer.speak_text_async(result_text).get()

    if (
        speech_synthesis_result.reason
        == speechsdk.ResultReason.SynthesizingAudioCompleted
    ):
        # print("Speech synthesized for text [{}]".format(result_text))
        pass
    elif speech_synthesis_result.reason == speechsdk.ResultReason.Canceled:
        cancellation_details = speech_synthesis_result.cancellation_details
        print("Speech synthesis canceled: {}".format(cancellation_details.reason))

        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            if cancellation_details.error_details:
                print("Error details: {}".format(cancellation_details.error_details))
                print("Did you set the speech resource key and region values?")

    state = state + [(result_text, '<audio controls src="/file='+file_obj+'"></audio>')]

    return state, state


# gradio interface
if __name__ == "__main__":
    # close all
    gr.close_all()

    # main interface
    with gr.Blocks(css="#chatbot .overflow-y-auto{height:500px}") as demo:
        chatbot = gr.Chatbot(elem_id="chatbot")
        state = gr.State([])

        with gr.Row():
            with gr.Column(scale=1.0):
                txt = gr.Textbox(show_label=False, placeholder="Insira o que deseja e aperter enter").style(container=False)

        txt.submit(form_submit, [state, txt], [state, chatbot])
        txt.submit(lambda :"", None, txt)

    # launch server
    port = int(os.environ.get("PORT", 9000))
    demo.launch(server_port=port)
```

### Logs

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/paulo/Library/Python/3.9/lib/python/site-packages/gradio/routes.py", line 293, in file
    raise ValueError(
ValueError: File cannot be fetched: /private/var/folders/_j/97qz65y57c56y7394rt316lc0000gn/T/audioe2684b618bb0f11dfa5ce7a48889b6aa11837c9e.mp3. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
```
```


### System Info

```shell
Gradio: 3.17.1
MacOS: Latest
Python: 3.9
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Hi @paulocoutinhox by default, Gradio only allows serving files that are in the Gradio script's directory itself. But we have an open PR to allow serving files from additional directories: https://github.com/gradio-app/gradio/pull/3075

It sounds like this should solve the issue, right?

**Comment by paulocoutinhox** [comment]
Yes, thanks

**Comment by abidlabs** [comment]
Ok I'll go ahead and merge it into `main` shortly. Instructions to download from `main` are here: https://gradio.app/docs/main/

Or you can wait until we release to pypi (probably early this week)

**Comment by abidlabs** [comment]
Merged into `main`. Will close this issue. If you try it out and it doesn't work, feel free to reopen. Thanks @paulocoutinhox
