### ISSUE TITLE
decode_base64_to_image failing

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#317]
Spaces with the error in the logs: https://huggingface.co/spaces/Tuana/face-recognition-sklearn-demo
Error stack

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/networking.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/networking.py", line 302, in interpret
    interpretation_scores, alternative_outputs = app.interface.interpret(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 362, in interpret
    processed_input = [input_component.preprocess(raw_input[i])
  File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 362, in <listcomp>
    processed_input = [input_component.preprocess(raw_input[i])
  File "/home/user/.local/lib/python3.8/site-packages/gradio/inputs.py", line 643, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 19, in decode_base64_to_image
    content = encoding.split(';')[1]
```

**Comment by abidlabs** [comment]
Closing because it looks like everything works now :)
