### ISSUE TITLE
Bug: interpretation fails on mnist example

### ISSUE THREAD

**Issue by discdiver** [gradio-app/gradio#324]
Only modification to the example code is to use `debug=True`. 

Screenshot attached.
<img width="1137" alt="Screen Shot 2021-10-29 at 2 18 09 PM" src="https://user-images.githubusercontent.com/7703961/139483569-2a0f0eb4-f3b6-414c-b43e-2b4e3c6a27af.png">

Stack trace: 

```
[2021-10-29 14:15:09,754] ERROR in app: Exception on /api/interpret/ [POST]
Traceback (most recent call last):
  File "/Users/hale/.pyenv/versions/3.9.7/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hale/.pyenv/versions/3.9.7/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hale/.pyenv/versions/3.9.7/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/hale/.pyenv/versions/3.9.7/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hale/.pyenv/versions/3.9.7/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hale/.pyenv/versions/3.9.7/lib/python3.9/site-packages/gradio/networking.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/hale/.pyenv/versions/3.9.7/lib/python3.9/site-packages/gradio/networking.py", line 357, in interpret
    interpretation_scores, alternative_outputs = app.interface.interpret(
  File "/Users/hale/.pyenv/versions/3.9.7/lib/python3.9/site-packages/gradio/interface.py", line 374, in interpret
    processed_input = [input_component.preprocess(raw_input[i])
  File "/Users/hale/.pyenv/versions/3.9.7/lib/python3.9/site-packages/gradio/interface.py", line 374, in <listcomp>
    processed_input = [input_component.preprocess(raw_input[i])
  File "/Users/hale/.pyenv/versions/3.9.7/lib/python3.9/site-packages/gradio/inputs.py", line 727, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "/Users/hale/.pyenv/versions/3.9.7/lib/python3.9/site-packages/gradio/processing_utils.py", line 19, in decode_base64_to_image
    content = encoding.split(';')[1]
AttributeError: 'dict' object has no attribute 'split'
```

**Comment by discdiver** [comment]
python 3.9.6
tensorflow 2.6.0
flask  2.0.1 

in latest version of chrome for mac os

**Comment by abidlabs** [comment]
Thanks for pointing this out @discdiver, we've identified what the issue is and are patching it right now!

**Comment by abidlabs** [comment]
Hi @discdiver we've fixed the primary bug that was causing interpretation to fail on all of our image interfaces. We don't actually show support interpretation for the sketchpad interface, but it should work on the regular Image interface, like this:

![image](https://user-images.githubusercontent.com/1778297/140185607-eafa8695-8ba6-4506-8a53-d637c0fe8990.png)

Feel free to pull the latest version of gradio on the master branch or we will release a new version on pypi in the next day. Thanks for your feedback!

**Comment by discdiver** [comment]
Cool. Thanks!
