### ISSUE TITLE
Cached Examples don't work for File component

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#3335]
### Describe the bug

Using cached examples for `gr.File` input component or output components does not work.

1. The input files cannot be downloaded
2. Clicking `Submit` with the cached input results in an error

The cached output file can be downloaded and contains the expected output.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run the `zip_files` demo.

I tried with the duplicated `titanic.csv` files as well as different files for each input and it made no difference.

### Screenshot

![cached_examples_file_component](https://user-images.githubusercontent.com/41651716/221614577-8f5ce354-8fef-4a9c-afdb-fe55caa87895.gif)

### Logs

```shell
Traceback (most recent call last):
  File "/Users/freddy/sources/gradio/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/freddy/sources/gradio/gradio/blocks.py", line 1022, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/Users/freddy/sources/gradio/gradio/blocks.py", line 914, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/Users/freddy/sources/gradio/gradio/components.py", line 2415, in preprocess
    return [process_single_file(f) for f in x]
  File "/Users/freddy/sources/gradio/gradio/components.py", line 2415, in <listcomp>
    return [process_single_file(f) for f in x]
  File "/Users/freddy/sources/gradio/gradio/components.py", line 2377, in process_single_file
    f["name"],
KeyError: 'name'
```

### System Info

```shell
main
```

### Severity

serious, but I can work around it

**Comment by gary149** [comment]
Thanks 🥳 - I just had the issue upgraded to latest and it works!
