### ISSUE TITLE
File route can't find temporary file not placed in upload directory

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3502]
### Describe the bug

I want to reference a file uploaded into a temp folder by Gradio, however I get errors when accessing the `/file={path}` endpoint even though the URL I passed is in the temp folder. The reason is the file wasn't placed in the app's upload directory.

```
C:\Users\a\AppData\Local\Temp\tmp8nj6yq46
C:/Users/a/AppData/Local/Temp/tmpr250y62j.png
```

The first path is the app's temporary upload path, the second is the output path when uploading an image with `gr.Image` and the `type="upload"` argument

Also `blocks.temp_file_sets` and `blocks.file_directories` are empty in the file route

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Upload file with `gr.Image`, `type="upload"`, try to get URL of file into an `<img>` tag's `src` in `gr.HTML`

### Logs

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\gradio\routes.py", line 338, in file
    raise ValueError(
ValueError: File cannot be fetched: C:/Users/a/AppData/Local/Temp/tmpr250y62j.png. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
```

### System Info

```shell
3.21.0, Windows Server 2022, Chromium
```

### Severity

annoying

**Comment by space-nuko** [comment]
Seems like the reason is this code, it doesn't place the temporary file in a location that the `/file` route can access

https://github.com/gradio-app/gradio/blob/52253b8bb10688dd25d65669d7c87e29f9a980bf/gradio/components.py#L1563-L1568
