### ISSUE TITLE
Network check can time out too easily

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3517]
### Describe the bug

Apparently gradio has some kind of network check if sharing is disabled. But this check is too strict if the frontend takes too long to respond, like in the case of automatic's webui. I have to restart the program 2-3 times before it's finally let through (due to filesystem caching or whatever speedup results from restarting so many times)

So this limits the complexity that the Gradio app can have, it has to respond faster than the timeout can be triggered or it can't be opened at all. I'd prefer disabling the timeout for those apps and just waiting indefinitely instead of outright crashing

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8418

### Logs

```shell
(logs are from the linked issue)

venv "D:\ill\stable-diffusion-webui-master\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for Web UI
Launching Web UI with arguments: --medvram
No module 'xformers'. Proceeding without it.
Downloading: "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors" to D:\ill\stable-diffusion-webui-master\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors

100%|█████████████████████████████████████████████████████████████████████████████| 3.97G/3.97G [25:15<00:00, 2.81MB/s]
Calculating sha256 for D:\ill\stable-diffusion-webui-master\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors: 6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa
Loading weights [6ce0161689] from D:\ill\stable-diffusion-webui-master\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: D:\ill\stable-diffusion-webui-master\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0):
Model loaded in 851.8s (calculate hash: 57.4s, load weights from disk: 9.3s, load config: 0.1s, create model: 12.3s, apply weights to model: 514.3s, apply half(): 239.7s, apply dtype to VAE: 1.3s, load VAE: 5.0s, move model to device: 0.6s, hijack: 3.7s, load textual inversion embeddings: 7.5s, scripts callbacks: 0.5s).
Traceback (most recent call last):
  File "D:\ill\stable-diffusion-webui-master\venv\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\ill\stable-diffusion-webui-master\venv\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\LuCa\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\LuCa\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\LuCa\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\LuCa\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ill\stable-diffusion-webui-master\venv\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\ill\stable-diffusion-webui-master\venv\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\ill\stable-diffusion-webui-master\venv\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\ill\stable-diffusion-webui-master\venv\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "D:\ill\stable-diffusion-webui-master\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\ill\stable-diffusion-webui-master\venv\lib\site-packages\urllib3\connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "D:\ill\stable-diffusion-webui-master\venv\lib\site-packages\urllib3\connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=7860): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ill\stable-diffusion-webui-master\launch.py", line 361, in <module>
    start()
  File "D:\ill\stable-diffusion-webui-master\launch.py", line 356, in start
    webui.webui()
  File "D:\ill\stable-diffusion-webui-master\webui.py", line 218, in webui
    app, local_url, share_url = shared.demo.launch(
  File "D:\ill\stable-diffusion-webui-master\venv\lib\site-packages\gradio\blocks.py", line 1417, in launch
    if _frontend and (not networking.url_ok(self.local_url)) and (not self.share):
  File "D:\ill\stable-diffusion-webui-master\venv\lib\site-packages\gradio\networking.py", line 179, in url_ok
    r = requests.head(url, timeout=3, verify=False)
  File "D:\ill\stable-diffusion-webui-master\venv\lib\site-packages\requests\api.py", line 104, in head
    return request('head', url, **kwargs)
  File "D:\ill\stable-diffusion-webui-master\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\ill\stable-diffusion-webui-master\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\ill\stable-diffusion-webui-master\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\ill\stable-diffusion-webui-master\venv\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=7860): Read timed out. (read timeout=3)
```

### System Info

```shell
3.16.2, Windows, Chromium
```

### Severity

annoying

**Comment by space-nuko** [comment]
Turns out this was caused by a `gr.HTML` component with a gigantic body bloating up the app bundle to 15MB gzipped (148MB decompressed)

Might be worth warning the developer if the builder encounters such a large component?

**Comment by abidlabs** [comment]
@space-nuko would you like to open a PR for this? It's hard for me to reproduce this issue but I'd be supportive of increasing the timeout a little bit.
