### ISSUE TITLE
Event handlers should typecheck inputs/outputs

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3522]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
When I'm developing a Gradio app and pass an incorrectly typed input/output I currently get an error like this

```
Traceback (most recent call last):
  File "E:\sd\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\sd\venv\lib\site-packages\gradio\blocks.py", line 1070, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\sd\venv\lib\site-packages\gradio\blocks.py", line 1003, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "E:\sd\venv\lib\site-packages\gradio\components.py", line 553, in postprocess
    return self._round_to_precision(y, self.precision)
  File "E:\sd\venv\lib\site-packages\gradio\components.py", line 502, in _round_to_precision
    return float(num)
TypeError: float() argument must be a string or a real number, not 'dict'
```

But of course this doesn't help me find *which* event handler/parameter is incorrect. That information is held in the dependencies of the handler, wouldn't it be more useful if the types were checked before pre/postprocessing anything?

**Describe the solution you'd like**  
An error message like the following

```
Argument 5 of event handler (name: "process_images") had an incorrect type (wanted: float, got: dict).
List of passed arguments: [1, "a", True, None, {"foo": "bar"}]
```

The list of passed arguments is so I can better identify the function if it's an anonymous lambda

I don't know if python saves line numbers for compiled functions, but it would be useful to include those if so

**Additional context**  
N/A

**Comment by abidlabs** [comment]
Thanks @space-nuko agreed that this would improve the DX for complex apps significantly. It looks like PR #3519 is targeting this issue, right?

cc @aliabid94

**Comment by space-nuko** [comment]
No actually, that's for the case when the number of arguments passed into/returned from an event handler are different. The error for that case (`Number of output components does not match number of values returned from from function`) wasn't helpful in practice so I wanted to improve it

This case is for when the number of arguments matches, but they're mistyped. I don't know what's the best way to go about doing this, having a `is_input_valid(self)` method for each `Component` called before pre/postprocessing, something related to `typing`, or otherwise?
