### ISSUE TITLE
Some of the themes on Hugging Face Hub aren't compatible with 3.23.0

### ISSUE THREAD

**Issue by space-nuko** [gradio-app/gradio#3566]
### Describe the bug

I get an error when trying to load one of the themes on Hugging Face Hub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
#!/usr/bin/env python

import gradio as gr

theme = gr.themes.ThemeClass.from_hub("freddyaboulton/soft")

with gr.Blocks(theme=theme) as demo:
    gr.Textbox("foo")

demo.queue(concurrency_count=20).launch(server_port=9876)
```

### Logs

```shell
Traceback (most recent call last):
  File "c:\Users\a\build\gradio-test\main8.py", line 7, in <module>
    with gr.Blocks(theme=theme) as demo:
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\gradio\blocks.py", line 509, in __init__
    self.theme_css = theme._get_theme_css()
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\gradio\themes\base.py", line 69, in _get_theme_css
    val = re.sub(pattern, repl_func, val)
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Users\a\build\gradio-test\venv\lib\site-packages\gradio\themes\base.py", line 61, in repl_func
    raise ValueError(
ValueError: Cannot refer 'button_cancel_background_hover_dark' to '*button_cancel_background_hover' - if dark and light mode values are the same, set dark mode version to None.
```

### System Info

```shell
3.23.0, Windows, Chrome
```

### Severity

annoying

**Comment by space-nuko** [comment]
Broken themes:

```
freddyaboulton/freddy_monochrome
freddyaboulton/soft
freddyaboulton/glass
```

**Comment by freddyaboulton** [comment]
Thanks for catching that @space-nuko ! Please use `gradio/soft`, `gradio/glass`, and `gradio/monochrome`. I uploaded those to my namespace for testing and it was using an early version of the theming api that's now incompatible.

Deleted those theme spaces as well. They should be removed from the gallery in a couple of minutes!
