### ISSUE TITLE
Video upload doesn't work on google colab since it can't find tempfile's path

### ISSUE THREAD

**Issue by SoulflareRC** [gradio-app/gradio#3622]
### Describe the bug

![image](https://user-images.githubusercontent.com/107384280/227730127-eab73fa4-21d4-44c4-8aed-9f6c0ed7258f.png)
I'm trying to run my gradio interface on google colab by doing !python gradio_interface.py...However, I use gr.Video for uploading video in my program, and gr.Video returns a path to a tempfile, and I use ffmpeg to process the video according to the path. The problem is that the path of tempfile in colab looks like "/tmp/..." and it's going to be treated as a relative path while it's actually an absolute path, so google colab can never find a video uploaded as a tempfile from gr.Video...I'm not sure if this is not supported at all or they way I'm doing this is wrong. Please help me with this...

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use gr.Video in google colab and use the path returned by the value of gr.Video

### Logs

```shell
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://f3dfaf1fddb76cbd62.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
tmp/Nagi No Asukara Opening 2d62828ce83720786b4f453337623461314c3f42d.mp4
Extracting reference in video format, crop mode
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1032, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 844, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "//content/AniRef-yolov8/gradio_interface.py", line 138, in extract_ref
    res_video_path = self.refextractor.extract_chara(video_path=video_path,output_format=format,mode=mode,frame_diff_threshold=threshold,padding=padding,conf_threshold=conf_threshold,iou_threshold=iou_threshold)
  File "/content/AniRef-yolov8/extractor.py", line 143, in extract_chara
    lowf_vid = self.extractor.adjust_framerate(10)
  File "/content/AniRef-yolov8/utils/extract_frames.py", line 81, in adjust_framerate
    subprocess.run(cmd)
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg -y -i "tmp/Nagi No Asukara Opening 2d62828ce83720786b4f453337623461314c3f42d.mp4"  -filter:v fps=10  "temp/Nagi No Asukara Opening 2d62828ce83720786b4f453337623461314c3f42d.mp4" '
```

### System Info

```shell
Gradio Version:3.20.1
OS: Google Colab
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @SoulflareRC happy to look into this. Can you share a link to the Colab notebook or an example with code so that we can reproduce the issue?

**Comment by abidlabs** [comment]
Closing for lack of follow up. @SoulflareRC please feel free to reopen with more details.
