### ISSUE TITLE
Quickstart Hellow World example - PermissionError: [Errno 13] Permission denied: 'flagged'

### ISSUE THREAD

**Issue by yyahav** [gradio-app/gradio#3693]
### Describe the bug

Running the following code in Python console:
```
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
```
I get the following output:
```
>>> demo = gr.Interface(fn=greet, inputs="text", outputs="text")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/venv/lib/python3.11/site-packages/gradio/interface.py", line 418, in __init__
    self.flagging_callback.setup(
  File "/Users/user/venv/lib/python3.11/site-packages/gradio/flagging.py", line 186, in setup
    os.makedirs(flagging_dir, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: 'flagged'
```

The code works when running from a py file, but not in the console. Not sure if it should work like this out of the box but thought that an issue will raise this.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run the Hello World example code in Python console

### Logs

```shell
>>> demo = gr.Interface(fn=greet, inputs="text", outputs="text")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/venv/lib/python3.11/site-packages/gradio/interface.py", line 418, in __init__
    self.flagging_callback.setup(
  File "/Users/user/venv/lib/python3.11/site-packages/gradio/flagging.py", line 186, in setup
    os.makedirs(flagging_dir, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: 'flagged'
```

### System Info

```shell
gradio 3.23.0
Python 3.11.1
Mac M1 Pro OS Ventura 13.2.1
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @yyahav that's very strange. Is it possible that your console doesn't have permissions to create files/directories? Or that it's being run from a sensitive directory where creating directories is not allowed?

**Comment by yyahav** [comment]
Hi @abidlabs, I'm running the script directly under my user folder - /Users/<user>, Python running in venv.
How can I check if the console or venv has blocked access to the user dir?

**Comment by abidlabs** [comment]
Hi @yyahav I suppose run Python in the console, and then do:

```py
import os
os.makedirs("flagged", exist_ok=True)
```

Can you share what happens when you run that?

**Comment by yyahav** [comment]
Hi @abidlabs the folder was created properly this way, no errors ("flagged" already existed because it worked using the py script, so I tested with "flagged1" and it worked)

**Comment by abidlabs** [comment]
Interesting. I wonder if you already had the flagged folder open somewhere and so your console didn't have permissions to create that folder? I can't reproduce this issue at all

**Comment by yyahav** [comment]
Hey @abidlabs 
No, I didn't have this folder anywhere else...
Sound weird indeed that you cannot reproduce it.

How can I help you debug it?

Also, I recall `flagging.py` calls `makedirs` with `exist_ok=True` so even if it exists it should just continue without throwing an error.

**Comment by abidlabs** [comment]
Hi @yyahav can you please try running this in a reproducible environment such as Google Colab or Replit and see if you run into any issue? For example, I've tried running this in a replit and everything works fine:

![Recording 2023-04-04 at 06 43 38 (1)](https://user-images.githubusercontent.com/1778297/229812375-50ddfc16-077b-4e28-9902-aec629b9238a.gif)

I'm going to close this issue for now since we can't reproduce, but feel free to reopen once you have a repro you can share with us.

**Comment by yyahav** [comment]
@abidlabs Hi, unfortunately it's not reproducible on Colab.

Maybe a security feature on Mac OS that I'm unaware of blocks access to create folders from within a Python console?
Have you tried reproducing it on a Mac OS env?

It does seem like a minor issue, as when using a py script it works...

**Comment by abidlabs** [comment]
cc @freddyaboulton can you repro this on a Mac?

**Comment by abidlabs** [comment]
By the way, I just ran into this issue when running Gradio in a docker container. The fix was to create the `flagged` directory myself and give it permissive permissions so that I could write to it

```
mkdir -m 700 flagged
```

**Comment by shamikbose** [comment]
@abidlabs I'm running into a similar issue when trying to make a directory while running in Spaces. The directory it's trying to make is in `/usr/var/` to cache a model, but it gives this error
`  
File "/usr/local/lib/python3.10/pathlib.py", line 1175, in mkdir
self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/var'
`

The space is here: https://huggingface.co/spaces/shamikbose89/PIISA_Demo

**Comment by abidlabs** [comment]
@shamikbose I don't see any errors on your Space. Did you figure it out?

**Comment by shamikbose** [comment]
@abidlabs I made a folder within my Gradio app. Looks like the folder that the docker image was trying to create within the Space wasn’t a location that was available. I just made a /home/user/app/cache folder and that seemed to have solved it

**Comment by duerrsimon** [comment]
This error also occurs with the standard tutorial on https://www.gradio.app/guides/deploying-gradio-with-docker  
adding `RUN mkdir /usr/src/app/flagged` fixes it. It would probably be smart to add a note to add this command. Otherwise the error is a bit random.
