### ISSUE TITLE
Gradio demo using Spaces fail with webcam

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#379]
Code

```
import gradio as gr
gr.Interface.load(
  "spaces/akhaliq/AnimeGANv2", 
  inputs=[
    gr.inputs.Image(label="Input Image", source="webcam"),
    gr.inputs.Radio(['version 1 (🔺 stylization, 🔻 robustness)','version 2 (🔺 robustness,🔻 stylization)'], type="value", default='version 2 (🔺 robustness,🔻 stylization)', label='version')
  ],
  outputs=gr.outputs.Image(type="pil")
).launch()
```

Output

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/networking.py", line 195, in predict
    prediction, durations = app.interface.process(raw_input)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 373, in process
    processed_output = [output_component.postprocess(predictions[i]) if predictions[i] is not None else None
  File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 373, in <listcomp>
    processed_output = [output_component.postprocess(predictions[i]) if predictions[i] is not None else None
  File "/home/user/.local/lib/python3.8/site-packages/gradio/outputs.py", line 228, in postprocess
    out_y = processing_utils.encode_array_to_base64(y)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 70, in encode_array_to_base64
    PIL_image = Image.fromarray(_convert(image_array, np.uint8, force_copy=False))
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 439, in _convert
    image = _scale(image, 8 * itemsize_in - 1, 8 * itemsize_out)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 282, in _scale
    if n > m and a.max() < 2 ** m:
  File "/home/user/.local/lib/python3.8/site-packages/numpy/core/_methods.py", line 40, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
TypeError: cannot perform reduce with flexible type
```

**Comment by abidlabs** [comment]
Thanks so much @osanseviero for bringing this to our attention! @aliabid94 can you take this?

**Comment by aliabid94** [comment]
My guess is a permissions issue with the iframe, but will take a look!

**Comment by osanseviero** [comment]
cc @cbensimon in case it's in our side

**Comment by aliabid94** [comment]
Ah it's a problem with gradio actually, fixing now!

**Comment by aliabid94** [comment]
Ah I see the problem. When using gr.Interface.load, it automatically generates the input components and output copmonents.  Currently you can't overwrite the type= kwarg for the Output component of a loaded interface (and you most likely shouldn't) but I will fix in the behaviour in code. Meanwhile, this will work:
```
import gradio as gr

gr.Interface.load(
  "spaces/akhaliq/AnimeGANv2", 
  inputs=[
    gr.inputs.Image(label="Input Image", source="webcam"),
    gr.inputs.Radio(['version 1 (🔺 stylization, 🔻 robustness)','version 2 (🔺 robustness,🔻 stylization)'], type="value", default='version 2 (🔺 robustness,🔻 stylization)', label='version')
  ],
).launch()
```

**Comment by osanseviero** [comment]
Thanks, that works well!

**Comment by abidlabs** [comment]
Closing because this doesn't seem to need a fix
