### ISSUE TITLE
import gradio error

### ISSUE THREAD

**Issue by zhangjin4415** [gradio-app/gradio#3827]
### Describe the bug

cannot import  gradio

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

gradio==3.14.0

### Logs

```shell
Traceback (most recent call last):
  File "/media/zjin/Data/work/mfan/algo/model_fine_tune/predict.py", line 2, in <module>
    import gradio as gr
  File "/media/zjin/Data/work/mfan/algo/model_fine_tune/dev_env/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/media/zjin/Data/work/mfan/algo/model_fine_tune/dev_env/lib/python3.10/site-packages/gradio/components.py", line 34, in <module>
    from gradio import media_data, processing_utils, utils
  File "/media/zjin/Data/work/mfan/algo/model_fine_tune/dev_env/lib/python3.10/site-packages/gradio/processing_utils.py", line 22, in <module>
    from gradio import encryptor, utils
  File "/media/zjin/Data/work/mfan/algo/model_fine_tune/dev_env/lib/python3.10/site-packages/gradio/utils.py", line 414, in <module>
    class AsyncRequest:
  File "/media/zjin/Data/work/mfan/algo/model_fine_tune/dev_env/lib/python3.10/site-packages/gradio/utils.py", line 434, in AsyncRequest
    client = httpx.AsyncClient()
  File "/media/zjin/Data/work/mfan/algo/model_fine_tune/dev_env/lib/python3.10/site-packages/httpx/_client.py", line 1408, in __init__
    self._mounts: typing.Dict[URLPattern, typing.Optional[AsyncBaseTransport]] = {
  File "/media/zjin/Data/work/mfan/algo/model_fine_tune/dev_env/lib/python3.10/site-packages/httpx/_client.py", line 1409, in <dictcomp>
    URLPattern(key): None
  File "/media/zjin/Data/work/mfan/algo/model_fine_tune/dev_env/lib/python3.10/site-packages/httpx/_utils.py", line 397, in __init__
    url = URL(pattern)
  File "/media/zjin/Data/work/mfan/algo/model_fine_tune/dev_env/lib/python3.10/site-packages/httpx/_urls.py", line 113, in __init__
    self._uri_reference = urlparse(url, **kwargs)
  File "/media/zjin/Data/work/mfan/algo/model_fine_tune/dev_env/lib/python3.10/site-packages/httpx/_urlparse.py", line 246, in urlparse
    parsed_port: typing.Optional[int] = normalize_port(port, scheme)
  File "/media/zjin/Data/work/mfan/algo/model_fine_tune/dev_env/lib/python3.10/site-packages/httpx/_urlparse.py", line 341, in normalize_port
    raise InvalidURL("Invalid port")
httpx.InvalidURL: Invalid port
```

### System Info

```shell
gradio.__version__==3.14.0
```

### Severity

annoying

**Comment by zhangjin4415** [comment]
error when httpx.__version__='0.24.0'. worked after pip install httpx==0.23.3.
