### ISSUE TITLE
Way to change page's tab title and icon

### ISSUE THREAD

**Issue by charlielito** [gradio-app/gradio#385]
Although you define the `title` for the interface, the page's tab doesn't show that title but instead it shows `Gradio`. Is any way to chaging this behavior? It is also possible to change the icon showed in the tab to be different?

![unknown](https://user-images.githubusercontent.com/8033598/143098960-d1fbcfc0-098f-4183-bba3-e7cd7c6deeda.png)

**Comment by aliabid94** [comment]
Will implement and include in next release. I thought we already changed tab title to reflect the interface title but apparently not. Will also add favicon= kwarg.

**Comment by charlielito** [comment]
Thanks for the fast reply @aliabid94 . 
In the mean time do you know what's the proper what of installing gradio directly from the master branch? I tried `pip install git+https://github.com/gradio-app/gradio.git` but it doesn't work for other port different than 8000 which is very odd. If using another port I get the following traceback when opening the web page:

```
Running on local URL:  http://0.0.0.0:4569/

To create a public link, set `share=True` in `launch()`.
[2021-11-23 17:48:37,855] ERROR in app: Exception on /static/bundle.css [GET]
Traceback (most recent call last):
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/gradio/networking.py", line 142, in static_resource
    return send_file(os.path.join(STATIC_PATH_LIB, path))
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/helpers.py", line 629, in send_file
    file = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/gradio/templates/frontend/static/bundle.css'
[2021-11-23 17:48:37,856] ERROR in app: Exception on /static/css/main.ad1e2368.css [GET]
Traceback (most recent call last):
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/gradio/networking.py", line 142, in static_resource
    return send_file(os.path.join(STATIC_PATH_LIB, path))
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/helpers.py", line 629, in send_file
    file = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/gradio/templates/frontend/static/css/main.ad1e2368.css'
[2021-11-23 17:48:37,857] ERROR in app: Exception on /static/bundle.js [GET]
Traceback (most recent call last):
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/gradio/networking.py", line 142, in static_resource
    return send_file(os.path.join(STATIC_PATH_LIB, path))
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/helpers.py", line 629, in send_file
    file = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/gradio/templates/frontend/static/bundle.js'
[2021-11-23 17:48:37,867] ERROR in app: Exception on /static/bundle.css [GET]
Traceback (most recent call last):
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/gradio/networking.py", line 142, in static_resource
    return send_file(os.path.join(STATIC_PATH_LIB, path))
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/helpers.py", line 629, in send_file
    file = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/gradio/templates/frontend/static/bundle.css'
[2021-11-23 17:48:37,868] ERROR in app: Exception on /static/css/main.ad1e2368.css [GET]
Traceback (most recent call last):
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/gradio/networking.py", line 142, in static_resource
    return send_file(os.path.join(STATIC_PATH_LIB, path))
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/helpers.py", line 629, in send_file
    file = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/gradio/templates/frontend/static/css/main.ad1e2368.css'
[2021-11-23 17:48:37,868] ERROR in app: Exception on /static/bundle.js [GET]
Traceback (most recent call last):
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/gradio/networking.py", line 142, in static_resource
    return send_file(os.path.join(STATIC_PATH_LIB, path))
  File "/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/flask/helpers.py", line 629, in send_file
    file = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/charlie/miniconda3/envs/gradio/lib/python3.7/site-packages/gradio/templates/frontend/static/bundle.js'
```

**Comment by abidlabs** [comment]
Hmm I wonder if this is due to the static files not being consistent with the pypi release. @aliabid94 can you comment here?

**Comment by abidlabs** [comment]
Favicon parameter (`favicon_path`) added to `launch()` as part of the latest changes in #440

In addition, the CONTRIBUTING.md guidelines have been improved for clarity

**Comment by yesdeepakmittal** [comment]
Hi @abidlabs, 

If we add `title` in the interface, the tab title is updated with it. Can we change the tab title without adding `title` in the interface?

Thanks

**Comment by abidlabs** [comment]
Hi @yesdeepakmittal yes it should be possible by wrapping the Interface within a `gr.Blocks()` and setting the `title` on the `gr.Blocks`. Something like this:

```py
with gr.Blocks(title=title) as demo:
   gr.Interface(....)
demo.launch()
```

By the way, for general questions like this (that are not feature requests or bug reports), please ask in [GitHub Discussions](https://github.com/gradio-app/gradio/discussions) or [our Discord](http://discord.gg/feTf9x3ZSB).

**Comment by yesdeepakmittal** [comment]
It's working thank you!

Will surely join Discord. Thanks for your kind information.
