### ISSUE TITLE
AttributeError: 'tuple' object has no attribute '_id'

### ISSUE THREAD

**Issue by JunyaoHu** [gradio-app/gradio#3885]
### Describe the bug

when I use Dropdown the demo will go wrong

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

```
import gradio as gr

def predict(down):
    print(down)
    return None

with gr.Blocks(title="demo") as demo:
    down = gr.Dropdown(
        ["ran", "swam", "ate", "slept"], value=["swam", "slept"], label="Activity", info="Lorem."
    ),
    
    button = gr.Button(value="demo")

    button.click(
        fn=predict, 
        inputs=down, 
        outputs=None
    )   

demo.launch()

```

### Screenshot

![image](https://user-images.githubusercontent.com/67564714/232444911-4a490c21-0a9f-4af6-a2cd-f93833418243.png)

### Logs

```shell
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pred-vdm/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ubuntu/anaconda3/envs/pred-vdm/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/envs/pred-vdm/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/ubuntu/anaconda3/envs/pred-vdm/lib/python3.9/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/ubuntu/anaconda3/envs/pred-vdm/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/anaconda3/envs/pred-vdm/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ubuntu/anaconda3/envs/pred-vdm/lib/python3.9/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/home/ubuntu/anaconda3/envs/pred-vdm/lib/python3.9/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/ubuntu/anaconda3/envs/pred-vdm/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/ubuntu/anaconda3/envs/pred-vdm/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "----/web_ui/down.py", line 14, in <module>
    button.click(
  File "/home/ubuntu/anaconda3/envs/pred-vdm/lib/python3.9/site-packages/gradio/events.py", line 132, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
  File "/home/ubuntu/anaconda3/envs/pred-vdm/lib/python3.9/site-packages/gradio/blocks.py", line 266, in set_event_trigger
    "inputs": [block._id for block in inputs],
  File "/home/ubuntu/anaconda3/envs/pred-vdm/lib/python3.9/site-packages/gradio/blocks.py", line 266, in <listcomp>
    "inputs": [block._id for block in inputs],
AttributeError: 'tuple' object has no attribute '_id'
```
```


### System Info

```shell
gradio                    3.27.0                   pypi_0    pypi
gradio-client             0.1.3                    pypi_0    pypi
ubuntu 20.04
```

### Severity

annoying

**Comment by abidlabs** [comment]
@JunyaoHu you have an extra comma in your code this line:

```
down = gr.Dropdown(
        ["ran", "swam", "ate", "slept"], value=["swam", "slept"], label="Activity", info="Lorem."
    ),
```

You also have to set `multiselect=True` if you want to be able to select multiple options.

This code works:

```py
import gradio as gr

def predict(down):
    print(down)
    return None

with gr.Blocks(title="demo") as demo:
    down = gr.Dropdown(
        ["ran", "swam", "ate", "slept"], value=["swam", "slept"], multiselect=True, label="Activity", info="Lorem."
    )
    
    button = gr.Button(value="demo")

    button.click(
        fn=predict, 
        inputs=down, 
        outputs=None
    )   

demo.launch()
```
