### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'Thread-3'.

### ISSUE THREAD

**Issue by f-grimaldi** [gradio-app/gradio#3904]
### Describe the bug

I'm trying the visual chat-gpt script which should launch a gradio app (https://github.com/microsoft/visual-chatgpt/blob/main/visual_chatgpt.py)

Everything runs smoothly but when i arrive at
`demo.launch(server_name="0.0.0.0", server_port=7860)`

i get a RuntimeError: There is no current event loop in thread-3

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Docker container from the below image and then following instruction from https://github.com/microsoft/visual-chatgpt

```
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04

# Set certificates
RUN apt-get install ca-certificates -y
COPY ./ZscalerRootCertificate-2048-SHA256.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates

RUN apt update
RUN apt install -y --no-install-recommends python3 python3-pip
RUN ln -sf python3 /usr/bin/python
RUN ln -sf pip3 /usr/bin/pip
RUN pip install --upgrade pip
RUN pip install wheel setuptools

RUN pip install certifi
ARG CERT_PATH=/usr/local/lib/python3.8/dist-packages/certifi/cacert.pem
RUN cat /usr/local/share/ca-certificates/ZscalerRootCertificate-2048-SHA256.crt >> $CERT_PATH
ENV CERT_PATH=$CERT_PATH
ENV SSL_CERT_FILE=$CERT_PATH
ENV REQUESTS_CA_BUNDLE=$CERT_PATH
ENV NODE_OPTIONS=--use-openssl-ca
RUN update-ca-certificates

# Opencv dll
RUN apt-get update
RUN apt install ffmpeg libsm6 libxext6  -y

CMD /bin/bash
```

### Logs

```shell
root@277f3e227d67:/home/visual-chatgpt# python visual_chatgpt.py 
/opt/conda/lib/python3.8/site-packages/numba/core/types/__init__.py:108: FutureWarning: In the future `np.long` will be defined as the corresponding NumPy scalar.
  long_ = _make_signed(np.long)
Initializing VisualChatGPT, load_dict={'ImageCaptioning': 'cuda:0', 'Text2Image': 'cuda:0'}
Initializing ImageCaptioning to cuda:0
Initializing Text2Image to cuda:0
/opt/conda/lib/python3.8/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
All the Available Functions: {'ImageCaptioning': <__main__.ImageCaptioning object at 0x7f4ef87e4c70>, 'Text2Image': <__main__.Text2Image object at 0x7f4ed987af40>}
Launch demo
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/uvicorn/server.py", line 49, in run
    loop = asyncio.get_event_loop()
  File "/opt/conda/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
^C╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/visual-chatgpt/visual_chatgpt.py:1372 in <module>                                          │
│                                                                                                  │
│   1369 │   │   clear.click(lambda: [], None, chatbot)                                            │
│   1370 │   │   clear.click(lambda: [], None, state)                                              │
│   1371 │   print('Launch demo')                                                                  │
│ ❱ 1372 │   demo.launch(server_name="127.0.0.1", server_port=8888, debug=True)                    │
│   1373                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/gradio/blocks.py:1703 in launch                           │
│                                                                                                  │
│   1700 │   │   │   │   │   "Rerunning server... use `close()` to stop if you need to change `la  │
│   1701 │   │      │   )                                                                         │
│   1702 │   │   else:                                                                             │
│ ❱ 1703 │   │   │   server_name, server_port, local_url, app, server = networking.start_server(   │
│   1704 │   │   │   │   self,                                                                     │
│   1705 │   │   │   │   server_name,                                                              │
│   1706 │   │   │   │   server_port,                                                              │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/gradio/networking.py:163 in start_server                  │
│                                                                                                  │
│   160 │   │   ws_max_size=1024 * 1024 * 1024,  # Setting max websocket size to be 1 GB           │
│   161 │   )                                                                                      │
│   162 │   server = Server(config=config)                                                         │
│ ❱ 163 │   server.run_in_thread()                                                                 │
│   164 │   return server_name, port, path_to_local_server, app, server                            │
│   165                                                                                            │
│   166                                                                                            │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/gradio/networking.py:39 in run_in_thread                  │
│                                                                                                  │
│    36 │   │   self.thread = threading.Thread(target=self.run, daemon=True)                       │
│    37 │   │   self.thread.start()                                                                │
│    38 │   │   while not self.started:                                                            │
│ ❱  39 │   │   │   time.sleep(1e-3)                                                               │
│    40 │                                                                                          │
│    41 │   def close(self):                                                                       │
│    42 │   │   self.should_exit = True                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyboardInterrupt
```

### System Info

```shell
Gradio: 3.27.0
Python: 3.8.10
Ubuntu (in docker): ubuntu20.04
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @f-grimaldi !

I think this would be more appropriate to post in the visual chatgpt repo. It's not clear if it's a gradio issue or an issue in their repo.

**Comment by dxli94** [comment]
Also encountered this issue. Tried gradio==3.10, 3.20, 3.27. Not able to solve.

**Comment by dxli94** [comment]
@ahsanu123 thanks for reply. The solution makes sense but I can't get it working even with the fix.

Can @freddyaboulton maybe suggest?

**Comment by dxli94** [comment]
Meet the same issue even with the example code:

import gradio as gr
  

```python3
def greet(name, is_morning, temperature):
    salutation = "Good morning" if is_morning else "Good evening"
    greeting = f"{salutation} {name}. It is {temperature} degrees today"
    celsius = (temperature - 32) * 5 / 9
    return greeting, round(celsius, 2)

demo = gr.Interface(
    fn=greet,
    inputs=["text", "checkbox", gr.Slider(0, 100)],
    outputs=["text", "number"],
)
demo.launch()
```           
gives:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/uvicorn/server.py", line 49, in run
    loop = asyncio.get_event_loop()
  File "/opt/conda/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
```

@freddyaboulton Thanks!

**Comment by JinPingHaHa** [comment]
add
`new_loop = asyncio.new_event_loop()`
`asyncio.set_event_loop(new_loop)`
in uvicorn/server.py
before 
`loop = asyncio.get_event_loop()`
`loop.run_until_complete(self.serve(sockets=sockets))` can solve this

**Comment by BenjiKCF** [comment]
same issue
