### ISSUE TITLE
Unable to complete prediction due to error in blocks.postprocess()

### ISSUE THREAD

**Issue by 907Resident** [gradio-app/gradio#3907]
### Describe the bug

I am working on building a very similar app to the one produced on this [HF Space](https://huggingface.co/spaces/HuggingFaceH4/databricks-dolly). 

Unfortunately, after trying on two different systems (explained in "System Info"), I have been unable to produce a prediction through the app.

The app continues to crash when I attempt to generate a prediction and the error from the traceback appears to be stuck on the part where the block is attempting to process the output from the model. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Here is the information needed to reproduce the error:

```python


from transformers import pipeline
import torch
import gradio as gr
import traceback

theme = gr.themes.Glass(
    primary_hue="gray",
    secondary_hue="red",
    neutral_hue="slate",
    font=[
        gr.themes.GoogleFont("Times New Roman"), "Times", "serif"
    ]
)

def generate(query, temperature, top_p, max_new_tokens): 
    return [dolly_3b_pipe(query, temperature, top_p, max_new_tokens), dolly_7b_pipe(query, temperature, top_p, max_new_tokens)]

# establish pipeline
try:
    dolly_3b_pipe = pipeline(
        model="databricks/dolly-v2-3b",
        torch_dtype=torch.bfloat16,
        trust_remote_code=True,
        model_kwargs={'load_in_8bit': True},
        device_map="auto"
    )

except Exception as e:
    traceback.print_exc(e)
    raise e
    
# establish pipeline
try:
    dolly_7b_pipe = pipeline(
        model="databricks/dolly-v2-7b",
        torch_dtype=torch.bfloat16,
        trust_remote_code=True,
        model_kwargs={'load_in_8bit': True},
        device_map="auto"
    )

except Exception as e:
    traceback.print_exc(e)
    raise e

theme = gr.themes.Glass(
    primary_hue="gray",
    secondary_hue="red",
    neutral_hue="slate",
    font=[
        gr.themes.GoogleFont("Times New Roman"), "Times", "serif"
    ]
)
examples = [
    "What is an alpaca? How is it different from a llama?",
    "Can you explain the difference between a beaver and an otter?",
    "Write an email to congratulate new employees at Bridgestone and mention that you are excited about meeting them in person.",
    "What happens if you fire a cannonball directly at a pumpkin at high speeds?",
    "Explain the moon landing to a 6 year old in a few sentences.",
    "Why aren't birds real?"
]

def process_examples(args):
    for x in generate(args):
        pass
    return x
    
css = ".generating {visibility: hidden}"

# establish UI

with gr.Blocks(theme=theme) as app:

  with gr.Row():
    with gr.Column():
        with gr.Row():
            prompt = gr.Textbox(
                placeholder="'Instruct' Dolly here or click on one of the stock examples below",
                label="Instruction",
                elem_id="q-input"
              )
        with gr.Row():
            with gr.Column():
                with gr.Row():
                    temperature = gr.Slider(
                        label="Output diversity",
                        value=0.5,
                        minimum=0.0,
                        maximum=2.0,
                        step=0.1,
                        interactive=True,
                        info="The greater the value, the more diverse the outputs from the model(s)"
                    )
                with gr.Column():
                    with gr.Row():
                        top_p = gr.Slider(
                            label="Top-p (nucleus sampling)",
                            value=0.90,
                            minimum=0.0,
                            maximum=1,
                            step=0.05,
                            interactive=True,
                            info="The greater value, the more likely the high-probability tokens will be selected"
                        )
                with gr.Column():
                    with gr.Row():
                        max_new_tokens = gr.Slider(
                            label="Maximum new tokens",
                            value=256,
                            minimum=0,
                            maximum=2048,
                            step=10,
                            interactive=True,
                            info="The maximum number of new tokens to generate",
                        )
            with gr.Row():
                submit = gr.Button("Generate Response")

    with gr.Row():
        with gr.Column():
            with gr.Box():
                gr.Markdown(
                    """
                    **Dolly 3B | Output**
                    """
                )
                output_3b = gr.Markdown()
        with gr.Column():
            with gr.Box():
                gr.Markdown(
                    """
                    **Dolly 7B | Output**
                    """
                )
                output_7b = gr.Markdown()
    with gr.Row():
        gr.Examples(
            examples=examples,
            inputs=[prompt],
            cache_examples=False,
            fn=process_examples,
            outputs=[
                output_3b,
                output_7b
            ]
        )

    submit.click(
        generate,
        inputs=[
            prompt,
            temperature,
            top_p,
            max_new_tokens
        ],
        outputs=[
            output_3b,
            output_7b
        ]
    )
    prompt.submit(
        generate,
        inputs=[
            prompt,
            temperature,
            top_p,
            max_new_tokens
        ],
        outputs=[
            output_3b,
            output_7b
        ]
    )

app.queue(concurrency_count=16).launch(debug=True, inline=False, share=False, inbrowser=True, show_tips=True)


```

### Screenshot

These two screenshots show what the app itself presents and the traceback, respectively. 

![Screenshot 2023-04-18 at 20 21 57](https://user-images.githubusercontent.com/12258706/232953558-a1b808f7-e624-4990-a7d5-2157be458ddf.png)

![Screenshot 2023-04-18 at 20 22 46](https://user-images.githubusercontent.com/12258706/232953568-7fc55b90-a4d5-40c5-9114-5928c2777586.png)

### Logs

```shell
Ignoring args : (0.5, 0.9, 256)
Ignoring args : (0.5, 0.9, 256)
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-38bcd98e-93f5-4457-9e90-44327961e77d/lib/python3.9/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-38bcd98e-93f5-4457-9e90-44327961e77d/lib/python3.9/site-packages/gradio/blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-38bcd98e-93f5-4457-9e90-44327961e77d/lib/python3.9/site-packages/gradio/blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-38bcd98e-93f5-4457-9e90-44327961e77d/lib/python3.9/site-packages/gradio/components.py", line 5498, in postprocess
    unindented_y = inspect.cleandoc(y)
  File "/usr/lib/python3.9/inspect.py", line 632, in cleandoc
    lines = doc.expandtabs().split('\n')
AttributeError: 'list' object has no attribute 'expandtabs'
```

### System Info

```shell
# gradio version // gradio>=3.23.1b1 did not work for me at all, I could not even load the app
3.23.0

# Operating System(s)
Linux, using both g4dn.2xlarge and g4dn.4xlarge instances 

# Other important packages
accelerate>=0.12.0 
transformers[torch]==4.25.1 
bitsandbytes
```

### Severity

blocking upgrade to latest gradio version

**Comment by 907Resident** [comment]
I have also loaded a minimum working version of the code into this [Colab notebook](https://colab.research.google.com/drive/1_z3H1AuHnvbStvyzCh1bp3rj-pjfgQD-?usp=sharing). 

To use on Google Colab, the practitioner will need:
- a Google Colab Pro or higher account (not free)
- GPU runtime (Click `Runtime > Hardware accelerator > GPU`)
- a premium GPU runtime (Click `Runtime > Change Runtime Type > GPU Class > Premium`)

**Comment by freddyaboulton** [comment]
Hi @907Resident !

Can you try changing `generate` to return a tuple as opposed to a list

```python
def generate(query, temperature, top_p, max_new_tokens): 
    return dolly_3b_pipe(query, temperature, top_p, max_new_tokens), dolly_7b_pipe(query, temperature, top_p, max_new_tokens)
```

**Comment by 907Resident** [comment]
Hi @freddyaboulton, 

Thanks for getting back to me so fast.

Unfortunately, I am still getting the same error after making the suggested change from 

```python
def generate(query, temperature, top_p, max_new_tokens): 
    return [dolly_3b_pipe(query, temperature, top_p, max_new_tokens), dolly_7b_pipe(query, temperature, top_p, max_new_tokens)]
```

to 

```python

def generate(query, temperature, top_p, max_new_tokens): 
    return dolly_3b_pipe(query, temperature, top_p, max_new_tokens), dolly_7b_pipe(query, temperature, top_p, max_new_tokens)
    
```

The error that I am still getting is:

```sh

Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://1a8ef7d0281f659057.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Tip: You can show or hide the button for flagging with the `allow_flagging=` kwarg; for example: gr.Interface(..., allow_flagging=False)
Ignoring args : (0.5, 0.9, 256)
Ignoring args : (0.5, 0.9, 256)
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6f5bacfb-9abe-4697-a63a-42617cea2840/lib/python3.9/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6f5bacfb-9abe-4697-a63a-42617cea2840/lib/python3.9/site-packages/gradio/blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6f5bacfb-9abe-4697-a63a-42617cea2840/lib/python3.9/site-packages/gradio/blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-6f5bacfb-9abe-4697-a63a-42617cea2840/lib/python3.9/site-packages/gradio/components.py", line 5498, in postprocess
    unindented_y = inspect.cleandoc(y)
  File "/usr/lib/python3.9/inspect.py", line 632, in cleandoc
    lines = doc.expandtabs().split('\n')
AttributeError: 'list' object has no attribute 'expandtabs'

```

I will keep trying to ensure that everything is being returned as a tuple in case I missed something elsewhere. Let me know if you have other ideas

**Comment by freddyaboulton** [comment]
No problem! Are any of the pipelines in your demo returning a list? The error seems to be that the Markdown component is receiving a list instead of a string.

**Comment by 907Resident** [comment]
It looks like those `output` arguments need to remain as a `list` object. I will keep looking for other lists that should not be there

**Comment by 907Resident** [comment]
I actually think I may have found that the `pipeline` *does* in fact return a `list`.

<details>
<summary> This can be reproduced by:</summary>

```python

example_prompt = "How do planes fly?"

dolly_3b_pipe = pipeline(
        model="databricks/dolly-v2-3b",
        torch_dtype=torch.bfloat16,
        trust_remote_code=True,
        model_kwargs={'load_in_8bit': True},
        device_map="auto"
    )

# example prompt
output_3b = dolly_3b_pipe(
     example_prompt
)

print(type(output_3b))

```

</details>

However, when I made the change in the `generate()` function to the following:

<details>

<summary>Change in `generate()` function</summary> 

```python
def generate(query, temperature, top_p, max_new_tokens): 
    dolly_3b_pipe_out = dolly_3b_pipe(query, temperature, top_p, max_new_tokens)
    dolly_3b_pipe_out = dolly_3b_pipe_out[0]["generated_text"]

    dolly_7b_pipe_out = dolly_7b_pipe(query, temperature, top_p, max_new_tokens)
    dolly_7b_pipe_out = dolly_7b_pipe_out[0]["generated_text"]

    return dolly_3b_pipe_out, dolly_7b_pipe_out
```

</details>

This appears to have **worked**. So, I think your suggestion of looking for a list object from the `pipeline` was the right idea. 

Thanks.
