### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'Interface'

### ISSUE THREAD

**Issue by dangerous-xu** [gradio-app/gradio#3909]
### Describe the bug

AttributeError: module 'gradio' has no attribute 'Interface'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")

demo.launch()   

### Logs

```shell
gradio gradio.py    

Launching in *reload mode* on: http://127.0.0.1:7860 (Press CTRL+C to quit)

Watching: '/Users/boden_xjh/miniconda3/envs/viewer/lib/python3.7/site-packages/gradio', '/Users/boden_xjh/Projects/tool'

Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Users/boden_xjh/miniconda3/envs/viewer/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/boden_xjh/miniconda3/envs/viewer/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/boden_xjh/miniconda3/envs/viewer/lib/python3.7/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/boden_xjh/miniconda3/envs/viewer/lib/python3.7/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/boden_xjh/miniconda3/envs/viewer/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Users/boden_xjh/miniconda3/envs/viewer/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/boden_xjh/miniconda3/envs/viewer/lib/python3.7/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/Users/boden_xjh/miniconda3/envs/viewer/lib/python3.7/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/boden_xjh/miniconda3/envs/viewer/lib/python3.7/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/Users/boden_xjh/miniconda3/envs/viewer/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/boden_xjh/Projects/tool/gradio.py", line 6, in <module>
    demo = gr.Interface(fn=greet, inputs="text", outputs="text")
AttributeError: module 'gradio' has no attribute 'Interface'
```

### System Info

```shell
MacOS
python==3.7
gradio==3.27.0
```

### Severity

annoying

**Comment by xxlest** [comment]
the issue same with me
i had reinstalled but still error

**Comment by DoanNgocCuongBKEGNH** [comment]
same
