### ISSUE TITLE
using JS client throw TypeError: s.mask is not a function

### ISSUE THREAD

**Issue by zodostffaa** [gradio-app/gradio#3945]
### Describe the bug

gradio app duplicate from this : https://github.com/GaiZhenbiao/ChuanhuChatGPT

JS client :
`import { client } from "./dist/index.js";

async function run() {
	const app = await client("http://127.0.0.1:7860/", (d) => console.log(d));
	app.on("status", console.log).on("data", console.log);
    // current_model,
    // user_question,
    // chatbot,
    // use_streaming_checkbox,
    // use_websearch_checkbox,
    // index_files,
    // language_select_dropdown,
    const p = await app.predict("/predict", { data: ["gpt-3.5-turbo","hello","","true","true","false","english"] , "fn_index": 0});
	console.log(p);
}
run();
`

 JS client throw exception:
> Uncaught TypeError TypeError: s.mask is not a function
    at C.mask (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:164:38)
    at frame (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:1095:316)
    at <anonymous> (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:1269:92)
    at <anonymous> (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:379:14)
    at <anonymous> (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:437:205)
    at afterWrite (internal/streams/writable:500:5)
    at onwrite (internal/streams/writable:480:7)
    at <anonymous> (internal/streams/transform:190:7)
    at processCallback (zlib:613:8)
    at callbackTrampoline (internal/async_hooks:130:17)
    --- ZLIB ---
    at init (internal/inspector_async_hook:25:19)
    at emitInitNative (internal/async_hooks:202:43)
    at Zlib (zlib:682:18)
    at DeflateRaw (zlib:768:3)
    at value (zlib:880:14)
    at _compress (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:425:25)
    at <anonymous> (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:378:12)
    at [kRun] (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:200:23)
    at add (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:190:32)
    at compress (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:377:7)
    at dispatch (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:1257:58)
    at send (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:1212:87)
    at send (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:1826:74)
    at g.onmessage (d:\dev\gradio\client\js\dist\index.js:238:17)
    at Z (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:1491:72)
    at r (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:1440:22)
    at emit (events:513:28)
    at Ds (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:2118:11)
    at emit (events:513:28)
    at dataMessage (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:1000:14)
    at <anonymous> (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:972:22)
    at <anonymous> (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:364:14)
    at <anonymous> (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:410:215)
    at afterWrite (internal/streams/writable:500:5)
    at onwrite (internal/streams/writable:480:7)
    at <anonymous> (internal/streams/transform:190:7)
    at processCallback (zlib:613:8)
    at callbackTrampoline (internal/async_hooks:130:17)
    --- ZLIB ---
    at init (internal/inspector_async_hook:25:19)
    at emitInitNative (internal/async_hooks:202:43)
    at Zlib (zlib:682:18)
    at InflateRaw (zlib:776:3)
    at value (zlib:880:14)
    at _decompress (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:395:25)
    at <anonymous> (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:363:12)
    at [kRun] (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:200:23)
    at add (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:190:32)
    at decompress (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:362:7)
    at decompress (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:956:40)
    at getData (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:943:30)
    at startLoop (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:739:20)
    at _write (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:684:66)
    at writeOrBuffer (internal/streams/writable:392:12)
    at _write (internal/streams/writable:333:10)
    at Writable.write (internal/streams/writable:337:10)
    at ne (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:2137:21)
    at emit (events:513:28)
    at addChunk (internal/streams/readable:324:12)
    at readableAddChunk (internal/streams/readable:297:9)
    at Readable.push (internal/streams/readable:234:10)
    at onStreamRead (internal/stream_base_commons:190:23)
    at callbackTrampoline (internal/async_hooks:130:17)
    --- TCPWRAP ---
    at init (internal/inspector_async_hook:25:19)
    at emitInitNative (internal/async_hooks:202:43)
    at Socket.connect (net:1175:7)
    at connect (net:243:17)
    at Rs (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:2080:36)
    at ClientRequest (_http_client:358:45)
    at request (http:98:10)
    at ht (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:1996:18)
    at d (d:\dev\gradio\client\js\dist\wrapper-17f133d7.js:1593:524)
    at <anonymous> (d:\dev\gradio\client\js\dist\index.js:220:60)
    at x (d:\dev\gradio\client\js\dist\index.js:165:14)
    at R (d:\dev\gradio\client\js\dist\index.js:267:14)
    at run (d:\dev\gradio\client\js\test.js:15:25)
    at processTicksAndRejections (internal/process/task_queues:95:5)
    --- await ---
    at <anonymous> (d:\dev\gradio\client\js\test.js:21:1)
    at run (internal/modules/esm/module_job:194:25)
    --- await ---
    at <anonymous> (internal/modules/esm/loader:526:28)
    at processTicksAndRejections (internal/process/task_queues:95:5)
    --- Promise.then ---
    at import (internal/modules/esm/loader:526:10)
    at <anonymous> (internal/modules/run_main:58:28)
    at loadESM (internal/process/esm_loader:91:11)
    at processTicksAndRejections (internal/process/task_queues:95:5)
    --- await ---
    at runMainESM (internal/modules/run_main:55:21)
    at executeUserEntryPoint (internal/modules/run_main:78:5)
    at <anonymous> (internal/main/run_main_module:23:47)
wrapper-17f133d7.js:164

gradio app throw exception:
> 2023-04-23 17:12:53,511 [ERROR] [base_events.py:1738] Task exception was never retrieved
future: <Task finished name='s4fnattowka_0' coro=<Queue.process_events() done, defined at C:\Python39\lib\site-packages\gradio\queueing.py:343> exception=WebSocketDisconnect(1006)>
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\Python39\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\Python39\lib\site-packages\gradio\queueing.py", line 453, in get_message
    data = await asyncio.wait_for(
  File "C:\Python39\lib\asyncio\tasks.py", line 476, in wait_for
    return fut.result()
  File "C:\Python39\lib\site-packages\starlette\websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "C:\Python39\lib\site-packages\starlette\websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://github.com/GaiZhenbiao/ChuanhuChatGPT

### Logs

```shell
PS D:\dev\gradio\client\js> node .\test.js
{
  type: 'status',
  status: 'pending',
  queue: true,
  endpoint: '/predict',
  fn_index: 0
}
{
  type: 'status',
  endpoint: '/predict',
  fn_index: 0,
  queue: true,
  status: 'pending',
  size: 1,
  position: 0,
  eta: 0.018011093139648438
}
file:///D:/dev/gradio/client/js/dist/wrapper-17f133d7.js:164
      n < 48 ? et(e, t, r, i, n) : s.mask(e, t, r, i, n);
                                     ^

TypeError: s.mask is not a function
    at C.mask (file:///D:/dev/gradio/client/js/dist/wrapper-17f133d7.js:164:38)
    at $.frame (file:///D:/dev/gradio/client/js/dist/wrapper-17f133d7.js:1095:316)
    at file:///D:/dev/gradio/client/js/dist/wrapper-17f133d7.js:1269:92
    at file:///D:/dev/gradio/client/js/dist/wrapper-17f133d7.js:379:14
    at file:///D:/dev/gradio/client/js/dist/wrapper-17f133d7.js:437:205
    at afterWrite (node:internal/streams/writable:500:5)
    at onwrite (node:internal/streams/writable:480:7)
    at Zlib.cb (node:internal/streams/transform:190:7)
    at Zlib.processCallback (node:zlib:613:8)

Node.js v18.16.0
```

### System Info

```shell
gradio app:
gradio==3.25.0
```

### Severity

annoying

**Comment by zodostffaa** [comment]
Abandon the JS client and directly use websocket to solve the problem

**Comment by freddyaboulton** [comment]
Hi @zodostffaa ! Client is still under construction
