### ISSUE TITLE
After Chabot and Markdown drawing, copy object in State will cause deepcopy error

### ISSUE THREAD

**Issue by Kilig947** [gradio-app/gradio#3966]
### Describe the bug

Requirements:
Page properties: [input box], [Markdown text], [button 1], [button 2]
Events: After clicking [button 1], [button 2] appears and [button 1] is hidden

So you need to use State to store the object of [button1] [button2] and bind the click event

When there is [Markdown text], and drawn in front of [State], then it will lead to deepcopy error, the whole application crash, if [State] in front of [Markdown text], there is no problem!  Please tell me why, I've been suffering from this problem for an hour

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

class ChatBot():
    def __init__(self):
        self.demo = gr.Blocks()

    def draw_test(self):
        with self.demo:
            self.temp = gr.Markdown('')     ## Commenting this code will work properly
            self.txt = gr.Textbox(label="Input", lines=2)
            self.btn = gr.Button(value="Submit1")
            self.btn2 = gr.Button(value="Submit2", visible=False)
            self.obj = gr.State({'obj': None, 'btn': self.btn, 'btn2': self.btn2})
            # self.btn.click(set_obj, inputs=[self.obj], outputs=[self.obj, self.btn, self.btn2])
            # self.btn2.click(print_obj, inputs=[self.obj], outputs=[self.txt])
        self.demo.launch()

if __name__ == '__main__':
    ChatBot().draw_test()

### Logs

```shell
/Users/kilig/Job/Python-project/academic_gpt/venv/bin/python /Users/kilig/Job/Python-project/academic_gpt/test.py 
Traceback (most recent call last):
  File "/Users/kilig/Job/Python-project/academic_gpt/test.py", line 57, in <module>
    ChatBot().draw_test()
  File "/Users/kilig/Job/Python-project/academic_gpt/test.py", line 51, in draw_test
    self.obj = gr.State({'obj': None, 'btn': self.btn, 'btn2': self.btn2})
  File "/Users/kilig/Job/Python-project/academic_gpt/venv/lib/python3.9/site-packages/gradio/components.py", line 3242, in __init__
    IOComponent.__init__(self, value=deepcopy(value), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'module' object

Process finished with exit code 1
```

### System Info

```shell
gradio-3.25.0:
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @Kilig947 can you elaborate what you're trying to do? We usually don't see Gradio components being passed into a `gr.State`? The `gr.State` is designed to hold on to data (like scalar values or arrays)

**Comment by abidlabs** [comment]
Closing for lack of follow up
