### ISSUE TITLE
run_on_click flag of gr.Examples is not working well on the first try

### ISSUE THREAD

**Issue by MrSyee** [gradio-app/gradio#3980]
### Describe the bug

I use gr.Blocks and gr.Examples like:
```
def mirror(x):
    print(x.shape())
    return x

with gr.Blocks() as demo:
    with gr.Row():
        input_img = gr.Image(label="Input image").style(height=600)
        output_img = gr.Image(label="Output image").style(height=600)

    gr.Markdown("## Image Examples")
    gr.Examples(
        examples=[
            [os.path.join(os.path.dirname(__file__), "examples/dog.jpg")]
        ],
        inputs=[input_img],
        outputs=output_img,
        fn=mirror,
        run_on_click=True,
    )
```

In UI, I bumped into error when I clicked example.
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/17582508/234595067-eb7acc07-a207-4562-bd68-7b3b7f1ca48a.png">

But on the second click, It is working well.

I think the example doesn't save well to the variable on the first click.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
def mirror(x):
    print(x.shape())
    return x

with gr.Blocks() as demo:
    with gr.Row():
        input_img = gr.Image(label="Input image").style(height=600)
        output_img = gr.Image(label="Output image").style(height=600)

    gr.Markdown("## Image Examples")
    gr.Examples(
        examples=[
            [os.path.join(os.path.dirname(__file__), "examples/dog.jpg")]
        ],
        inputs=[input_img],
        outputs=output_img,
        fn=mirror,
        run_on_click=True,
    )
```

### Screenshot

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/17582508/234595067-eb7acc07-a207-4562-bd68-7b3b7f1ca48a.png">

### Logs

```shell
Traceback (most recent call last):
  File "/home/hpds/.conda/envs/dl_apps/lib/python3.9/site-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/hpds/.conda/envs/dl_apps/lib/python3.9/site-packages/gradio/blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "/home/hpds/.conda/envs/dl_apps/lib/python3.9/site-packages/gradio/blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/hpds/.local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/hpds/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/hpds/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/hpds/personal/dl_apps/segmentation/./app.py", line 93, in mirror
    print(x.shape())
AttributeError: 'NoneType' object has no attribute 'shape'
```

### System Info

```shell
gradio==3.27.0
gradio_client==0.1.3
```

### Severity

annoying

**Comment by drscotthawley** [comment]
I  have found the same behavior.  As long as `run_on_click` or `cache_examples` are not enabled, everything works fine, but turning either of those on causes `None` to arrive at all inputs for Blocks.   Writing about this in [this Discussions thread](https://discuss.huggingface.co/t/how-do-we-provide-audio-examples-when-using-blocks/38346/7?u=drscotthawley).

**Comment by drscotthawley** [comment]
@abidlabs Any chance we could escalate resolution of this bug?  🥺 🙏  
I'm so far invested in `gr.Blocks`, I can't switch back to `gr.Interface` just to get working Examples.

**Comment by abidlabs** [comment]
Have opened a PR here: https://github.com/gradio-app/gradio/pull/4258

**Comment by drscotthawley** [comment]
@abidlabs Awesome!  Thank you (I got sick immediately after my post last week).  I confirm that this is working now in `gradio==3.32.0`. :-)

**Comment by MrSyee** [comment]
@abidlabs Nice work! I confirm that this is working now in `gradio==3.32.0`. Thank you!
```
import os
import gradio as gr

def mirror(x):
    return x

with gr.Blocks() as demo:
    with gr.Row():
        input_img = gr.Image(label="Input image").style(height=600)
        output_img = gr.Image(label="Output image").style(height=600)

    gr.Markdown("## Image Examples")
    gr.Examples(
        examples=[
            [os.path.join(os.path.dirname(__file__), "examples/dog.jpg")]
        ],
        inputs=input_img,
        outputs=output_img,
        fn=mirror,
        run_on_click=True,
    )

demo.launch()
```
<img width="1304" alt="image" src="https://github.com/gradio-app/gradio/assets/17582508/42a8c5aa-cb54-4cd3-8345-0726ec236f9a">
