### ISSUE TITLE
chatbot_dialogpt demo not work as gif

### ISSUE THREAD

**Issue by abmybgx** [gradio-app/gradio#3985]
### Describe the bug

chatbot_dialogpt demo run.py

error like below:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "chat.py", line 16, in bot
    bot_input_ids = torch.cat([torch.LongTensor(history), new_user_input_ids], dim=-1)
ValueError: too many dimensions 'str'

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Reproduction

1. set share=True for run.py

2. python3 run.py

3. use public url access and send any message.

### Logs

```shell
no
```

### System Info

```shell
3.27.0
```

### Severity

annoying

**Comment by dawoodkhan82** [comment]
@abmybgx thansk for reporting. It seems like there's a bug in the demo code. Will take a look.
