### ISSUE TITLE
ws_max_size when starting server

### ISSUE THREAD

**Issue by themantalope** [gradio-app/gradio#4000]
### Describe the bug

First time using gradio, fairly simple setup:

```python

title = "Interactive demo: Document Layout Analysis with DiT"
description = "Demo for Microsoft's DiT, the Document Image Transformer for state-of-the-art document understanding tasks. This particular model is fine-tuned on PubLayNet, a large dataset for document layout analysis (read more at the links below). To use it, simply upload an image or use the example image below and click 'Submit'. Results will show up in a few seconds. If you want to make the output bigger, right-click on it and select 'Open image in new tab'."
article = "<p style='text-align: center'><a href='https://arxiv.org/abs/2203.02378' target='_blank'>Paper</a> | <a href='https://github.com/microsoft/unilm/tree/master/dit' target='_blank'>Github Repo</a></p> | <a href='https://huggingface.co/docs/transformers/master/en/model_doc/dit' target='_blank'>HuggingFace doc</a></p>"
examples =[['publaynet_example.jpeg']]
css = ".output-image, .input-image, .image-preview {height: 600px !important}"

def analyze_image(image):
    # image is a numpy array
    predictions = predictor(image)
    return predictions.to("cpu").numpy().tolist()

iface = gr.Interface(fn=analyze_image, 
                     inputs=gr.components.Image(type="numpy", label="document image"),
                     outputs="list",
                     title=title,
                     description=description,
                     examples=examples,
                     article=article,
                     css=css)

iface.launch(debug=True, enable_queue=True, server_port=8080)

```

However when starting:

```bash
Traceback (most recent call last):
  File "app.py", line 61, in <module>
    iface.launch(debug=True, enable_queue=True, server_port=8080)
  File "/opt/conda/lib/python3.7/site-packages/gradio/blocks.py", line 1709, in launch
    ssl_keyfile_password,
  File "/opt/conda/lib/python3.7/site-packages/gradio/networking.py", line 160, in start_server
    ws_max_size=1024 * 1024 * 1024,  # Setting max websocket size to be 1 GB
TypeError: __init__() got an unexpected keyword argument 'ws_max_size'

```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Using gradio==3.27.0

### Logs

```shell
Traceback (most recent call last):
  File "app.py", line 61, in <module>
    iface.launch(debug=True, enable_queue=True, server_port=8080)
  File "/opt/conda/lib/python3.7/site-packages/gradio/blocks.py", line 1709, in launch
    ssl_keyfile_password,
  File "/opt/conda/lib/python3.7/site-packages/gradio/networking.py", line 160, in start_server
    ws_max_size=1024 * 1024 * 1024,  # Setting max websocket size to be 1 GB
TypeError: __init__() got an unexpected keyword argument 'ws_max_size'
```

### System Info

```shell
gradio version: 3.27.0
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
It seems like you might be using an older version of `uvicorn`. Can you try upgrading to the newest version: `pip install uvicorn --upgrade`?
