### ISSUE TITLE
Plot is not displayed upon method execution

### ISSUE THREAD

**Issue by devfinwiz** [gradio-app/gradio#4022]
### Describe the bug

I am trying out a stock forecast example. I can see my method getting executed but when it comes to displaying the plot using gradio in the output tab, multiple exceptions arise. 
RuntimeError: main thread is not in main loop

[*********************100%***********************]  1 of 1 completed
This on my terminal ensures that my method to generate plot executes without error and the input from gradio is being passed to the method appropriately. The only issue is with displaying the plot which is a basic line chart. 

Exact detailed error is present in the logs. 

I am not very used to using Gradio, so I may be doing something wrong. Kindly help me with the same asap. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Here's my code snippet:

```
from distutils.command.upload import upload
import gradio as gr
from positional_signals import *

with gr.Blocks(title="Fin-Maestro Signals Generator",css="#heading{background-color:#32a8a8}") as demo:

    gr.Label(elem_id="heading",value="Fin-Maestro Signals Generator",label="Title")

    with gr.Tab("Input"):
        text_input = gr.Textbox(label="Stock Symbol",placeholder="Stock symbol example: BSE.NS or SAHYADRI.BO")
        text_button = gr.Button("Generate Signals",elem_id="generate_sigals")

    with gr.Tab("Output"), gr.Row():
        plot_output=gr.Plot(label="forecast")

    with gr.Tab("View Demo"):
        with gr.Row():
            tut_button=gr.Button("View Demo Usage")
            demo_video = gr.Image(label="Demo").style(height=350,width=500)

        gr.Label("Scan The Code For Demo Tutorial")

    #tut_button.click(signals_generator,inputs=[],outputs=[demo_video])
    text_button.click(signals_generator, inputs=text_input, outputs=plot_output)
    
demo.launch()
```

Here is my method signals_generator:

```
import sys
sys.path.append("init")
from init import *

def signals_generator(ticker):
    yf.pdr_override()
    plt.style.use('dark_background') #dark theme for plot

    #ticker = input()          #name of the stock for which signals are needed.
    num_of_signals = 10      #number of buy/sell signals to be plotted

    df = yf.download(ticker,initial,end)    #dataframe from yfinance for specific ticker

    closes = sorted(df.Close.tolist())
    low,high = closes[num_of_signals],closes[-num_of_signals]

    df['Signal'] = 0

    df.loc[df['Adj Close'] > high, 'Signal'] = -1
    df.loc[df['Adj Close'] < low, 'Signal'] = 1

    long = df.loc[df['Signal'] == 1]
    short = df.loc[df['Signal'] == -1]

    fig=plt.figure()
    plt.plot(df.index, df['Adj Close'],color='white', label='Close Price')
    plt.plot(long.index, df.loc[long.index]['Adj Close'], '^', markersize=10, color='g', label='Long/Buy')
    plt.plot(short.index, df.loc[short.index]['Adj Close'],'v', markersize=10, color='r', label='Short/Sell')
    plt.ylabel('Closing Price')
    plt.xlabel('Date')
    plt.title(ticker)
    plt.legend(loc='best')

    #plt.show()
    return fig
```

### Screenshot

![image](https://user-images.githubusercontent.com/78873223/235416090-1ce65d04-8180-4e95-b4aa-129a60dd83c5.png)

![image](https://user-images.githubusercontent.com/78873223/235416134-4b2681dc-c87f-44d1-8975-9b0bdb751125.png)

Demo Output Screenshot of the Plot: 

![image](https://user-images.githubusercontent.com/78873223/235416342-2d721403-acea-4e87-82d7-d89ea43a1a94.png)

### Logs

```shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
[*********************100%***********************]  1 of 1 completed
Traceback (most recent call last):
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\backend_bases.py", line 3044, in _wait_cursor_for_draw_cm
    self.canvas.set_cursor(tools.Cursors.WAIT)
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\backends\_backend_tk.py", line 408, in set_cursor
    self._tkcanvas.configure(cursor=cursord[cursor])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1675, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1665, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
RuntimeError: main thread is not in main loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\blocks.py", line 1302, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\blocks.py", line 1236, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\components.py", line 4859, in postprocess
    out_y = processing_utils.encode_plot_to_base64(y)
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gradio\processing_utils.py", line 58, in encode_plot_to_base64
    plt.savefig(output_bytes, format="png")
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\figure.py", line 3285, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\backend_bases.py", line 2338, in print_figure
    result = print_method(
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\backend_bases.py", line 2204, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\_api\deprecation.py", line 410, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\backends\backend_agg.py", line 517, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\backends\backend_agg.py", line 463, in _print_pil
    FigureCanvasAgg.draw(self)
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\backends\backend_agg.py", line 402, in draw
    with RendererAgg.lock, \
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\backend_bases.py", line 3047, in _wait_cursor_for_draw_cm
    self.canvas.set_cursor(self._last_cursor)
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\matplotlib\backends\_backend_tk.py", line 408, in set_cursor
    self._tkcanvas.configure(cursor=cursord[cursor])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1675, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1665, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
RuntimeError: main thread is not in main loop
```
```


### System Info

```shell
Name: gradio
Version: 3.28.1

Browser: Google Chrome
Version 112.0.5615.138 (Official Build) (64-bit)

Python 3.10.11
```

### Severity

blocking all usage of gradio

**Comment by freddyaboulton** [comment]
Setting the matplotlib backend to `Agg` should solve this issue: https://github.com/gradio-app/gradio/blob/main/demo/outbreak_forecast/run.py#L7
