### ISSUE TITLE
Issue reading uploaded file in fastapi client guide

### ISSUE THREAD

**Issue by 1lint** [gradio-app/gradio#4056]
### Describe the bug

Hi thanks for the guide at https://gradio.app/fastapi-app-with-the-gradio-client/!
I was trying it out but the line `new_video = process_video(video.filename)` was giving me an error saying the file was not found. 
I think the line should be replaced with

```
video_path = video.filename
with open(video_path, "wb+") as fp:
    fp.write(video.file.read())
new_video = process_video(video_path)
```

This is what I had at the end

```
# main.py
from gradio_client import Client
import os
from pathlib import Path

client = Client("abidlabs/music-separation")

def acapellify(audio_path):
    result = client.predict(audio_path, api_name="/predict")
    return result[0]

import subprocess

def process_video(video_path):
    old_audio = os.path.basename(video_path).split(".")[0] + ".m4a"
    subprocess.run(['ffmpeg', '-y', '-i', video_path, '-vn', '-acodec', 'copy', old_audio])
    
    new_audio = acapellify(old_audio)
    
    new_video = f"acap_{Path(video_path).name}"
    subprocess.call(['ffmpeg', '-y', '-i', video_path, '-i', new_audio, '-map', '0:v', '-map', '1:a', '-c:v', 'copy', '-c:a', 'aac', '-strict', 'experimental', f"static/{new_video}"])
    return f"static/{new_video}"

from fastapi import FastAPI, File, UploadFile, Request
from fastapi.responses import HTMLResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

app = FastAPI()
os.makedirs("static", exist_ok=True)
app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="templates")

videos = []

@app.get("/", response_class=HTMLResponse)
async def home(request: Request):
    return templates.TemplateResponse(
        "home.html", {"request": request, "videos": videos})

@app.post("/uploadvideo/")
async def upload_video(video: UploadFile = File(...)):
    video_path = f"static/{video.filename}"
    with open(video_path, "wb+") as fp:
        fp.write(video.file.read())

    new_video = process_video(video_path)
    videos.append(new_video)
    return RedirectResponse(url='/', status_code=303)
```

in `templates/home.html`
```
<!DOCTYPE html>
<html>
  <head>
    <title>Video Gallery</title>
    <style>
      body {
        font-family: sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f5f5f5;
      }
      h1 {
        text-align: center;
        margin-top: 30px;
        margin-bottom: 20px;
      }
      .gallery {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        gap: 20px;
        padding: 20px;
      }
      .video {
        border: 2px solid #ccc;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
        border-radius: 5px;
        overflow: hidden;
        width: 300px;
        margin-bottom: 20px;
      }
      .video video {
        width: 100%;
        height: 200px;
      }
      .video p {
        text-align: center;
        margin: 10px 0;
      }
      form {
        margin-top: 20px;
        text-align: center;
      }
      input[type="file"] {
        display: none;
      }
      .upload-btn {
        display: inline-block;
        background-color: #3498db;
        color: #fff;
        padding: 10px 20px;
        font-size: 16px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
      }
      .upload-btn:hover {
        background-color: #2980b9;
      }
      .file-name {
        margin-left: 10px;
      }
    </style>
  </head>
  <body>
    <h1>Video Gallery</h1>
    {% if videos %}
      <div class="gallery">
        {% for video in videos %}
          <div class="video">
            <video controls>
              <source src="/{{ video }}" type="video/mp4">
              Your browser does not support the video tag.
            </video>
            <p>{{ video }}</p>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p>No videos uploaded yet.</p>
    {% endif %}
    <form action="/uploadvideo/" method="post" enctype="multipart/form-data">
      <label for="video-upload" class="upload-btn">Choose video file</label>
      <input type="file" name="video" id="video-upload">
      <span class="file-name"></span>
      <button type="submit" class="upload-btn">Upload</button>
    </form>
    <script>
      // Display selected file name in the form
      const fileUpload = document.getElementById("video-upload");
      const fileName = document.querySelector(".file-name");

      fileUpload.addEventListener("change", (e) => {
        fileName.textContent = e.target.files[0].name;
      });
    </script>
  </body>
</html>
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://gradio.app/fastapi-app-with-the-gradio-client/

### Screenshot

<img width="949" alt="fastapi_guide" src="https://user-images.githubusercontent.com/105617163/236080330-4ebe710c-9dcb-4591-b892-008fa83d27de.png">

### Logs

```shell
INFO:     127.0.0.1:54160 - "POST /uploadvideo/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/user/acapellify/./test.py", line 43, in upload_video
    new_video = process_video(video.filename)
  File "/home/user/acapellify/./test.py", line 16, in process_video
    new_audio = acapellify(old_audio)
  File "/home/user/acapellify/./test.py", line 7, in acapellify
    result = client.predict(audio_path, api_name="/predict")
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/gradio_client/client.py", line 258, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/gradio_client/client.py", line 907, in result
    raise self.future._exception  # type: ignore
  File "/home/user/miniconda3/envs/ml/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/gradio_client/client.py", line 601, in _inner
    data = self.serialize(*data)
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/gradio_client/client.py", line 744, in serialize
    o = tuple([s.serialize(d) for s, d in zip(self.serializers, data)])
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/gradio_client/client.py", line 744, in <listcomp>
    o = tuple([s.serialize(d) for s, d in zip(self.serializers, data)])
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/gradio_client/serializing.py", line 299, in serialize
    return self._serialize_single(x, load_dir=load_dir)
  File "/home/user/miniconda3/envs/ml/lib/python3.10/site-packages/gradio_client/serializing.py", line 238, in _serialize_single
    size = Path(filename).stat().st_size
  File "/home/user/miniconda3/envs/ml/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
FileNotFoundError: [Errno 2] No such file or directory: 'QLpArkPb-YU.m4a'
```

### System Info

```shell
gradio.__version__ == 3.28.1

I run gradio on WSL2 and access the frontend with chrome on windows
```

### Severity

annoying

**Comment by 1lint** [comment]
the client is really neat, I'm going to have to make a list of gpu enabled hf spaces to use

I added an api endpoint to convert youtube urls with a gradio frontend to the client example

```
from gradio_client import Client
import yt_dlp # pip install yt-dlp

import subprocess

import os
from pathlib import Path
from fastapi import FastAPI, File, UploadFile, Request
from fastapi.responses import HTMLResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

VIDEO_DIRECTORY = "static"

client = Client("abidlabs/music-separation")

def acapellify(audio_path):
    result = client.predict(audio_path, api_name="/predict")
    return result[0]

def process_video(video_path):
    old_audio = os.path.basename(video_path).split(".")[0] + ".m4a"
    subprocess.run(['ffmpeg', '-y', '-i', video_path, '-vn', '-acodec', 'copy', old_audio])
    
    new_audio = acapellify(old_audio)
    
    new_video = f"acap_{Path(video_path).name}"
    output_path = f"{VIDEO_DIRECTORY}/{new_video}"
    subprocess.call(['ffmpeg', '-y', '-i', video_path, '-i', new_audio, '-map', '0:v', '-map', '1:a', '-c:v', 'copy', '-c:a', 'aac', '-strict', 'experimental', output_path])
    return output_path


# filename default value will return name of video on youtube
def download_yt_url(url: str, filename: str = "%(title)s", format = 'mp4'):

    output_path = f"{VIDEO_DIRECTORY}/{filename}.{format}"

    # restrict video length so one user doesn't take up all our bandwidth
    def video_filter(info):
        MAX_DURATION = 240
        duration = info.get('duration')
        if duration and duration > MAX_DURATION:
            return f'The video is too long at {duration}s, choose a video less than {MAX_DURATION}s'

    ydl_opts = {
        'match_filter': video_filter,
        'format': f'{format}/bestaudio',
        'outtmpl': output_path,
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        error_code = ydl.download([url])
        #info = ydl.extract_info(url, extra_info={"output_path": output_path})

    if error_code:
        raise Exception(f"Failed to download video, error code: {error_code}")
    
    return output_path

app = FastAPI()
os.makedirs(VIDEO_DIRECTORY, exist_ok=True)
app.mount(f"/{VIDEO_DIRECTORY}", StaticFiles(directory=VIDEO_DIRECTORY), name="static")
templates = Jinja2Templates(directory="templates")

videos = []

@app.get("/", response_class=HTMLResponse)
async def home(request: Request):
    return templates.TemplateResponse(
        "home.html", {"request": request, "videos": videos})

@app.post("/uploadvideo/")
async def upload_video(video: UploadFile = File(...)):
    video_path = f"{VIDEO_DIRECTORY}/{video.filename}"
    with open(video_path, "wb+") as fp:
        fp.write(video.file.read())

    new_video = process_video(video_path)
    videos.append(new_video)
    return RedirectResponse(url='/', status_code=303)

# ideally yt_url should be validated
def acapellify_url(yt_url):
    
    # example filename: https://www.youtube.com/watch?v=TasKo5HHWb4 -> TasKo5HHWb4
    filename = yt_url.rsplit("=", 1)[-1] 

    video_path = download_yt_url(yt_url, filename)

    return process_video(video_path)


@app.post("/process_yt_url", response_class=HTMLResponse)
async def process_yt_url(yt_url: str):
    
    new_video = acapellify_url(yt_url)
    videos.append(new_video)
    return RedirectResponse(url=f'/', status_code=303)


# gradio frontend

import gradio as gr

def greet(name):
    return "Hello " + name + "!"

with gr.Blocks() as demo:
    input_url = gr.Textbox(label="Youtube URL")
    output_video = gr.Video(label="Output Box")
    process_video_btn = gr.Button("Process URL")
    process_video_btn.click(fn=acapellify_url, inputs=[input_url], outputs=[output_video])

# gradio frontend will be at http://127.0.0.1:8000/gradio/
gr.mount_gradio_app(app, demo, "/gradio")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0")

```

**Comment by 1lint** [comment]
Hi @abidlabs! I saw the docs were all in progress and presumed this would be fixed soon. I just opened a new issue https://github.com/gradio-app/gradio/issues/4145 and didn't want to clog the page with too many issues (I see you already have 300+)

**Comment by abidlabs** [comment]
Oh that's not a problem! Docs are in progress but let me reopen so we don't miss this fix

**Comment by abidlabs** [comment]
Good issues that are clear and help us to improve the library or documentation are always welcome!
