### ISSUE TITLE
AttributeError: 'AsyncRequest' object has no attribute '_json_response_data'

### ISSUE THREAD

**Issue by LZY-the-boys** [gradio-app/gradio#4061]
### Describe the bug

I use the newest code for the fix of latex (in this [issue](https://github.com/gradio-app/gradio/issues/3943) ), however i soon run into this issue when model is generating :
```
Traceback (most recent call last):
  File "gradio/gradio/queueing.py", line 370, in process_events
    while response.json.get("is_generating", False):
  File "gradio/gradio/utils.py", line 696, in json
    return self._json_response_data
AttributeError: 'AsyncRequest' object has no attribute '_json_response_data'
```
At the mean time, the generation will stuck.
it's like the [issue](https://github.com/gradio-app/gradio/pull/2288), but it seems have not been solved yet.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

text generation using LLM, gradio.chatbot queue() 

### Logs

```shell
Traceback (most recent call last):
  File "gradio/gradio/queueing.py", line 370, in process_events
    while response.json.get("is_generating", False):
  File "gradio/gradio/utils.py", line 696, in json
    return self._json_response_data
AttributeError: 'AsyncRequest' object has no attribute '_json_response_data'
```
```


### System Info

```shell
3.28.2, win wsl, chrome
```

### Severity

annoying

**Comment by freddyaboulton** [comment]
Hi @LZY-the-boys ! Can you share the code you are running? Is it the same from #3943

**Comment by LZY-the-boys** [comment]
@freddyaboulton  here is an example code:

```
import sys
import gradio as gr
import argparse
import warnings
import time
import os
import json
def save():
    pass

def evaluate(
    inputs,
    extra,
    history,
    temperature=0.1,
    top_p=0.75,
    top_k=40,
    num_beams=4,
    max_new_tokens=128,
    min_new_tokens=1,
    repetition_penalty=2.0,
    max_memory=1024,
    do_sample=False,
    prompt_type='0',
    **kwargs,
):
    history = [] if history is None else history
    return_text = [(item['input'], item['output']) for item in history]
    show_text = ''
    for i in range(10):
        show_text += str(i) + " ▌"
        yield return_text +[(inputs, show_text)], history
    print('[EOS]', end='\n')
    output = show_text
    history.append({
        'input': inputs,
        'output': output,
    })           
    return_text += [(inputs, show_text)]
    yield return_text, history


with gr.Blocks() as demo:
    fn = evaluate
    history = gr.components.State()
    with gr.Row().style(equal_height=False):
        with gr.Column(variant="panel"):
            input_component_column = gr.Column()
            with input_component_column:
                input = gr.components.Textbox(
                    lines=2, label="Input", placeholder="请输入问题."
                )
                extra = gr.components.Textbox(
                    lines=2, label="Extra", placeholder="context or persona"
                )
                temperature = gr.components.Slider(minimum=0, maximum=1, value=1.0, label="Temperature")
                topp = gr.components.Slider(minimum=0, maximum=1, value=0.9, label="Top p")
                topk = gr.components.Slider(minimum=0, maximum=100, step=1, value=60, label="Top k")
                beam_number = gr.components.Slider(minimum=1, maximum=10, step=1, value=4, label="Beams Number")
                max_new_token = gr.components.Slider(
                    minimum=1, maximum=2000, step=1, value=256, label="Max New Tokens"
                )
                min_new_token = gr.components.Slider(
                    minimum=1, maximum=100, step=1, value=5, label="Min New Tokens"
                )
                repeat_penal = gr.components.Slider(
                    minimum=0.1, maximum=10.0, step=0.1, value=2.0, label="Repetition Penalty"
                )
                max_memory = gr.components.Slider(
                    minimum=0, maximum=2048, step=1, value=256, label="Max Memory"
                )
                do_sample = gr.components.Checkbox(label="Use sample")
                # must be str, not number !
                type_of_prompt = gr.components.Dropdown(
                    ['instruct', 'chat','chat with knowledge','chat with persona'], value='chat', label="Prompt Type", info="select the specific prompt; use after clear history"
                )
                input_components = [
                    input, extra, history, temperature, topp, topk, beam_number, max_new_token, min_new_token, repeat_penal, max_memory, do_sample, type_of_prompt
                ]
                input_components_except_states = [input,extra, temperature, topp, topk, beam_number, max_new_token, min_new_token, repeat_penal, max_memory, do_sample, type_of_prompt]
            with gr.Row():
                cancel_btn = gr.Button('Cancel')
                submit_btn = gr.Button("Submit", variant="primary")
                stop_btn = gr.Button("Stop", variant="stop", visible=False)
            with gr.Row():
                reset_btn = gr.Button("Reset Parameter")
                clear_history = gr.Button("Clear History")

        with gr.Column(variant="panel"):
            chatbot = gr.Chatbot().style(height=1024)
            output_components = [ chatbot, history ]  
            with gr.Row():
                save_btn = gr.Button("Save Chat")
        
        def wrapper(*args):
            # here to support the change between the stop and submit button
            try:
                for output in fn(*args):
                    output = [o for o in output]
                    # output for output_components, the rest for [button, button]
                    yield output + [
                        gr.Button.update(visible=False),
                        gr.Button.update(visible=True),
                    ]
            finally:
                yield [{'__type__': 'generic_update'}, {'__type__': 'generic_update'}] + [ gr.Button.update(visible=True), gr.Button.update(visible=False)]

        def cancel(history, chatbot):
            if history == []:
                return (None, None)
            return history[:-1], chatbot[:-1]

        extra_output = [submit_btn, stop_btn]

        save_btn.click(
            save, 
            input_components, 
            None, 
        )

        pred = submit_btn.click(
            wrapper, 
            input_components, 
            output_components + extra_output, 
            api_name="predict",
            scroll_to_output=True,
            preprocess=True,
            postprocess=True,
            batch=False,
            max_batch_size=4,
        )
        submit_btn.click(
            lambda: (
                submit_btn.update(visible=False),
                stop_btn.update(visible=True),
            ),
            inputs=None,
            outputs=[submit_btn, stop_btn],
            queue=False,
        )
        stop_btn.click(
            lambda: (
                submit_btn.update(visible=True),
                stop_btn.update(visible=False),
            ),
            inputs=None,
            outputs=[submit_btn, stop_btn],
            cancels=[pred],
            queue=False,
        )
        cancel_btn.click(
            cancel,
            inputs=[history, chatbot],
            outputs=[history, chatbot]
        )
        reset_btn.click(
            None, 
            [],
            (
                # input_components ; don't work for history...
                input_components_except_states
                + [input_component_column]
            ),  # type: ignore
            _js=f"""() => {json.dumps([
                getattr(component, "cleared_value", None) for component in input_components_except_states ] 
                + ([gr.Column.update(visible=True)])
                + ([])
            )}
            """,
        )
        clear_history.click(lambda: (None, None), None, [history, chatbot], queue=False)

demo.queue().launch(share=0)
```

**Comment by LZY-the-boys** [comment]
And has following errors, with will cause chatbot stuck.
![image](https://user-images.githubusercontent.com/72137647/236363670-c7227db4-d1ba-45a1-a59b-53f7b2a69015.png)

**Comment by freddyaboulton** [comment]
Hi @LZY-the-boys ! It seems like you're adding a lot of logic to change the submit button to a stop button and vice versa. We just refactored a lot of this logic so my hope is that if you borrow from the latest implementation (to be released soon) this won't happen anymore.

We might also create a new component that makes switching from submit to cancel a lot easier.

**Comment by abidlabs** [comment]
I'll go ahead and close -- @LZY-the-boys feel free to look at the latest code on `main` to see how to change the submit button to a stop button and vice versa. Please let us know if you are still running into any issues
