### ISSUE TITLE
AttributeError: 'Base' object has no attribute 'primary_xpand' on 3.28.3

### ISSUE THREAD

**Issue by reilnuud** [gradio-app/gradio#4079]
### Describe the bug

Nearly all xhr requests in theme builder result in a 500 error. Looking in the server log, you can see the error `AttributeError: 'Base' object has no attribute 'primary_xpand'` on nearly every request.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Run pip install gradio.
2. Create `builder.py` with the following code per the theming tutorial:
```python
import gradio as gr

gr.themes.builder()
```
3. Run `builder.py`.
4. Attempt to edit theme or change base theme. Nothing happens.

### Logs

```shell
Traceback (most recent call last):
  File "/Users/neilruud/.pyenv/versions/3.10.6/lib/python3.10/site-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/neilruud/.pyenv/versions/3.10.6/lib/python3.10/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/Users/neilruud/.pyenv/versions/3.10.6/lib/python3.10/site-packages/gradio/blocks.py", line 1021, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/neilruud/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/neilruud/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/neilruud/.pyenv/versions/3.10.6/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/neilruud/.pyenv/versions/3.10.6/lib/python3.10/site-packages/gradio/themes/builder.py", line 812, in render_variables
    generate_theme_code(
  File "/Users/neilruud/.pyenv/versions/3.10.6/lib/python3.10/site-packages/gradio/themes/builder.py", line 616, in generate_theme_code
    final_attr_values[final_theme_attr] = getattr(
AttributeError: 'Base' object has no attribute 'primary_xpand'
```
```


### System Info

```shell
Mac OS 13.0.1
Python 3.10.6
Gradio 3.28.3
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Can confirm the issue thanks @reilnuud! Looking into it
