### ISSUE TITLE
Prediction gets stuck in a loop and crashes the app indefinitely H11 Error ASGI

### ISSUE THREAD

**Issue by cowanAI** [gradio-app/gradio#4082]
### Describe the bug

latest version of Gradio mounted on fast API uvicorn running on docker container EC2 the app sometimes requires long recordings of 10 min predictions, I get an error from gradio saying "all connections attempt failed"

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

ui = gr.Interface(
    fn=transcribe, 
    theme='gradio/soft',
    inputs=[
        gr.Audio(source="microphone", type="filepath", label="Upload audio"),
        gr.Textbox(label="AI Clinical Worskpace:"),
        
    ],
    outputs=gr.Textbox(interactive=True,label="Alicja AI:").style(show_copy_button=True),
    #allow_flagging=('never'),
    examples=[    ["Medical_Transcriber.mp3", "Medical transcriber: Alicja, please summarize the patient visit and auto-fill the “X” form."],
    ["Medical_Writing.mp3", "Medical writing: Hey Alicja, can you help me organize my thoughts for this research paper?"],
    ["Clinical_Trials.mp3", "Clinical trials: Alicja, what is the recommended sample size for this clinical trial and can you help me analyze the results?"],
    ["Language_Translation.mp3", "Language translation: Alicja, can you help me translate what this patient is saying into English?"],
    ["Medical_Research.mp3", "Medical research: Hey Alicja, can you help me find some relevant literature for this research question?"],
    ["Patient_Education.mp3", "Patient education: Alicja, can you explain this medical condition to my patient in simple terms?"],
],
    css="footer {visibility: hidden}",
    allow_flagging=('never'),
)

ui.queue(concurrency_count=2)
app = gr.mount_gradio_app(app, ui, path=CUSTOM_PATH)

### Screenshot

I get an error from gradio saying "all connections attempt failed"

### Logs

```shell
WARNING:  Invalid HTTP request received.
INFO:     64.226.105.208:49788 - "GET /manager/html HTTP/1.1" 404 Not Found
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 91, in __call__
    await response(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 164, in __call__
    await send(
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in sender
    await send(message)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 159, in _send
    await send(message)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 513, in send
    output = self.conn.send(event)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/h11/_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/h11/_connection.py", line 537, in send_with_data_passthrough
    self._process_event(self.our_role, event)
  File "/usr/local/lib/python3.11/site-packages/h11/_connection.py", line 272, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "/usr/local/lib/python3.11/site-packages/h11/_state.py", line 293, in process_event
    self._fire_event_triggered_transitions(role, _event_type)
  File "/usr/local/lib/python3.11/site-packages/h11/_state.py", line 311, in _fire_event_triggered_transitions
    raise LocalProtocolError(
h11._util.LocalProtocolError: can't handle event type Response when role=SERVER and state=MUST_CLOSE
current working directory: /app
```

### System Info

```shell
latest version, all browsers get stucked
```

### Severity

annoying

**Comment by cowanAI** [comment]
also this mysterious behavior:


why when Im launching a docker container on a ec2 instance, I need to visit first the ec2 port before visiting the cloudfront url otherwise the requests will not come and the program will loop indefinitely?

It's difficult to say for sure without more context, but this could be related to the way that CloudFront and Docker handle routing and networking.

When you launch a Docker container on an EC2 instance, the container is typically running on a specific port. For example, you might be running a web application on port 80 inside the container. In order for traffic to reach that application, you need to expose that port on the host machine (the EC2 instance), which you can do using the -p option when you start the container.

When you then use CloudFront to serve your application, it acts as a reverse proxy, routing traffic from the internet to your EC2 instance. However, the way that CloudFront does this routing can sometimes interfere with the way that Docker is exposing ports on the host machine.

One possible explanation for the behavior you're seeing is that when you visit the EC2 instance directly, it somehow "opens up" the network connection between the container and the host machine, allowing CloudFront to properly route traffic to the container. Without visiting the EC2 instance first, the connection may not be established correctly, leading to the looping behavior you're seeing.

Another possible explanation is that there is some sort of caching or DNS issue at play. When you visit the EC2 instance directly, it could be triggering some sort of cache refresh or DNS lookup that is needed for proper routing through CloudFront.

Overall, this is a complex issue that can have a variety of causes. If you can provide more information about your setup and the specific error messages you're seeing, I may be able to provide more targeted advice.

**Comment by abidlabs** [comment]
Hi @cowanAI this is a fairly involved setup and the bug seems to be flaky from what you described. Is there any way you can provide a simpler repro for us to be able to tackle this? Thanks

**Comment by cowanAI** [comment]
Hi @abidlabs , I'm still going to troubleshoot on my end to not bother so much, just one question that I could not find in documentation and maybe you guys could add, when increase the concurrency count on gradio and mounted on fastapi, do I need to do that in parallel to the uvicorn workers as well?

Eg. concurrency count set to 10 on gradio and then when launching the uvicorn app set also 10 workers on uvicorn?

**Comment by cowanAI** [comment]
regarding the bug is a bit complex, want to make sure is not a rookie mistake on my end, here is the setup

-ec2 instances containing docker containers running gradio apps mounted on fast api uvicorn, when I reach these apps via ec2 dns they work great, but then I forward this to a load balancer, and then the load balancer to a cloudfront distribution, eveyrhting works fine, but when scaling, in order to add new ec2 instances i need to send a prediction directly first to the ec2 instance, if I replace the ec2 in the target group with a new one, and I make a prediction via the cloudfront distribution, the prediction enters into an infinite loop, but this could be due to the fast that Im not using ECS to run the docker containers, so need to troubleshoot a bit more

**Comment by cowanAI** [comment]
@abidlabs found this documentation on the uvicorn website, it says default is one but if the concurrency variable is set then it follows the variable, I'm curious if uvicorn can listen to gradio concurrency count
 

<img width="673" alt="image" src="https://github.com/gradio-app/gradio/assets/128092052/06d7deb9-2a84-4413-938f-91e113c47bc3">
