### ISSUE TITLE
KeyError: 'serialized_input'

### ISSUE THREAD

**Issue by Undertone0809** [gradio-app/gradio#4083]
### Describe the bug

- I got an error when I run the following demo.

```python

import gradio as gr


def greet(name):
    return "Hello " + name + "!"


with gr.Blocks() as demo:
    name = gr.Textbox(label="Name")
    output = gr.Textbox(label="Output Box")
    greet_btn = gr.Button("Greet")
    greet_btn.click(fn=greet, inputs=name, outputs=output)

demo.launch()

```
- This error happened when I click `Use via API` link.

![image](https://user-images.githubusercontent.com/72488598/236613831-ca1603ea-8f28-4e0e-ab2a-60f9abe6c12d.png)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python

import gradio as gr


def greet(name):
    return "Hello " + name + "!"


with gr.Blocks() as demo:
    name = gr.Textbox(label="Name")
    output = gr.Textbox(label="Output Box")
    greet_btn = gr.Button("Greet")
    greet_btn.click(fn=greet, inputs=name, outputs=output)

demo.launch()

```

### Logs

```shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\86132\AppData\Roaming\Python\Python310\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\86132\AppData\Roaming\Python\Python310\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\86132\AppData\Roaming\Python\Python310\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\gradio\routes.py", line 260, in api_info
    return gradio.blocks.get_api_info(config, serialize)  # type: ignore
  File "E:\Programming\anaconda\envs\gradio\lib\site-packages\gradio\blocks.py", line 499, in get_api_info
    info = component["api_info"]["serialized_input"]
KeyError: 'serialized_input'
```
```


### System Info

```shell
- gradio-3.28.3
```

### Severity

annoying

**Comment by Undertone0809** [comment]
I have solve this problem. Using `gradio==3.26.0`. But I still want to know why this problem occurs?

**Comment by aleimu** [comment]
+1

**Comment by abidlabs** [comment]
Can confirm the issue, looking into it!

**Comment by abidlabs** [comment]
This is now fixed on the latest version of `gradio` on `main`. You can install gradio from main by following the instructions here: https://gradio.app/docs/main

Example Colab: https://colab.research.google.com/drive/1mPVvMCwb8ne3LdO-eKXW6NSIKeSCXyAU?usp=sharing

We'll get a release out soon!

**Comment by Undertone0809** [comment]
Why I got the same problem after I clicking `Use via API` and the same code. My gradio version is `v3.28.3`

**Comment by veb-101** [comment]
I'm getting the same type of error when deploying my app on HuggingFace spaces:
```bash
  File "/home/user/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/user/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/user/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/user/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/user/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/user/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/user/.local/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/home/user/.local/lib/python3.10/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/user/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/user/.local/lib/python3.10/site-packages/gradio/routes.py", line 291, in api_info
    return gradio.blocks.get_api_info(config, serialize)  # type: ignore
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 528, in get_api_info
    serializer = serializing.COMPONENT_MAPPING[type]()
KeyError: 'dataset'
``` 
My files are available here: [UWMGI_Medical_Image_Segmentation](https://huggingface.co/spaces/veb-101/UWMGI_Medical_Image_Segmentation/tree/main)

Note: I added "gradio" in the `requirements.txt` file just to check if it solves the issue. Sadly, It didn't.

**Comment by codepharmer** [comment]
> I have solve this problem. Using `gradio==3.26.0`. But I still want to know why this problem occurs?

Thanks!
