### ISSUE TITLE
Error importing gradio 3.28.4b0

### ISSUE THREAD

**Issue by jonathanasdf** [gradio-app/gradio#4114]
### Describe the bug

See title

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
>>> import gradio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jonathanasdf/.local/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/jonathanasdf/.local/lib/python3.10/site-packages/gradio/components.py", line 34, in <module>
    from gradio.py_client import media_data
ModuleNotFoundError: No module named 'gradio.py_client'
```

### Logs

```shell
^
```

### System Info

```shell
3.28.4b0
```

### Severity

blocking all usage of gradio

**Comment by freddyaboulton** [comment]
Hi @jonathanasdf ! 

That's a pre-release. I think @abidlabs was testing something. Sorry for the confusion!
