### ISSUE TITLE
JSON dumped string not returning in output

### ISSUE THREAD

**Issue by Pranjalya** [gradio-app/gradio#4117]
### Describe the bug

When returning a nested list of Python dictionary in JSON dumped string to a Gradio Textbox component, it returns only the first character, for instance `[` for a proper list of dictionary.
I have confirmed that the text is proper by printing it in logs, where it shows quite correctly.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import json
import gradio as gr

def check(audio):
    return json.dumps([{"ret": 2, "ok":"no"}, {"ret": 1, "ok":"yes"}])

audio = gr.Audio(type="filepath")
output = gr.Textbox(label="Result")

interface = gr.Interface(check, [audio], [output])
interface.queue().launch()
```

### Screenshot

![image](https://user-images.githubusercontent.com/36627085/237005337-e81c6065-3dd2-45b0-814d-0147d3c92764.png)

### Logs

```shell
The first part is the printed log of the expected result, and followed by that is the exception.

[{"Offset": 0.1, "Duration": 4.48, "Channel": 0, "DisplayText": "You have to use Final Cut, you have to use DaVinci Resolve, so all these things are clearly possible for you.", "NBest": [{"Lexical": "You have to use Final Cut, you have to use DaVinci Resolve, so all these things are clearly possible for you.", "Display": "You have to use Final Cut, you have to use DaVinci Resolve, so all these things are clearly possible for you.", "Words": [{"Word": "You", "Offset": 0.1, "Duration": 0.4, "Confidence": 0.13548538088798523}, {"Word": "have", "Offset": 0.5, "Duration": 0.02, "Confidence": 0.6426698565483093}, {"Word": "to", "Offset": 0.52, "Duration": 0.1, "Confidence": 0.9906387329101562}, {"Word": "use", "Offset": 0.62, "Duration": 0.12, "Confidence": 0.9779289364814758}, {"Word": "Final", "Offset": 0.74, "Duration": 0.46, "Confidence": 0.8563870191574097}, {"Word": "Cut,", "Offset": 1.2, "Duration": 0.0, "Confidence": 0.7328581809997559}, {"Word": "you", "Offset": 1.2, "Duration": 0.2, "Confidence": 0.48827701807022095}, {"Word": "have", "Offset": 1.4, "Duration": 0.08, "Confidence": 0.9755832552909851}, {"Word": "to", "Offset": 1.48, "Duration": 0.02, "Confidence": 0.9937052130699158}, {"Word": "use", "Offset": 1.5, "Duration": 0.1, "Confidence": 0.9880428314208984}, {"Word": "DaVinci", "Offset": 1.6, "Duration": 0.18, "Confidence": 0.7867404222488403}, {"Word": "Resolve,", "Offset": 1.78, "Duration": 0.22, "Confidence": 0.8702954947948456}, {"Word": "so", "Offset": 2.28, "Duration": 0.24, "Confidence": 0.4128313362598419}, {"Word": "all", "Offset": 2.52, "Duration": 0.12, "Confidence": 0.7913599610328674}, {"Word": "these", "Offset": 2.64, "Duration": 0.32, "Confidence": 0.7596344947814941}, {"Word": "things", "Offset": 2.96, "Duration": 0.02, "Confidence": 0.9285494685173035}, {"Word": "are", "Offset": 2.98, "Duration": 0.28, "Confidence": 0.9882062077522278}, {"Word": "clearly", "Offset": 3.26, "Duration": 0.36, "Confidence": 0.9387730956077576}, {"Word": "possible", "Offset": 3.62, "Duration": 0.46, "Confidence": 0.985643744468689}, {"Word": "for", "Offset": 4.08, "Duration": 0.5, "Confidence": 0.9476069211959839}, {"Word": "you.", "Offset": 4.58, "Duration": 0.0, "Confidence": 0.9967785477638245}]}]}]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/user/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/user/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/user/.local/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/user/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/user/.local/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/user/.local/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/user/.local/lib/python3.8/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/user/.local/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/user/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 260, in api_info
    return gradio.blocks.get_api_info(config, serialize)  # type: ignore
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 499, in get_api_info
    info = component["api_info"]["serialized_input"]
KeyError: 'serialized_input'
```
```


### System Info

```shell
It was in Huggingface Space, the v2 15 GB CPU system.
```

### Severity

blocking all usage of gradio

**Comment by Pranjalya** [comment]
It seems to have been caused by some infrastructure issue in Huggingface Space, and seems to be not limited to Gradio, and seems to work now. Hence, closing this.
