### ISSUE TITLE
On Python 3.9, `typing.get_type_hints()` throws an error if "|" is used in the type hint

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#4216]
### Describe the bug

The following code works with Python 3.10, but not with Python 3.9, as reported by @hysts 

`app.py`

```py
#!/usr/bin/env python

import gradio as gr

from utils import fn

with gr.Blocks() as demo:
    text = gr.Text()
    text2 = gr.Text()
    text.submit(fn=fn, inputs=text, outputs=text2)

demo.queue(api_open=False).launch()
```

`utils.py`

```py
from __future__ import annotations

def fn(a: str | int) -> str:
    return f'{a}'
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See above

### Logs

```shell
Traceback (most recent call last):
  File "/home/hysts/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/hysts/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hysts/.virtualenvs/py3916/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/hysts/.virtualenvs/py3916/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/hysts/.pyenv/versions/3.9.16/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/hysts/.pyenv/versions/3.9.16/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/hysts/.virtualenvs/py3916/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/hysts/.virtualenvs/py3916/lib/python3.9/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/hysts/.virtualenvs/py3916/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/hysts/.pyenv/versions/3.9.16/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/tmp/temp2/./app.py", line 10, in <module>
    text.submit(fn=fn, inputs=text, outputs=text2)
  File "/home/hysts/.virtualenvs/py3916/lib/python3.9/site-packages/gradio/events.py", line 132, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
  File "/home/hysts/.virtualenvs/py3916/lib/python3.9/site-packages/gradio/blocks.py", line 218, in set_event_trigger
    check_function_inputs_match(fn, inputs, inputs_as_dict)
  File "/home/hysts/.virtualenvs/py3916/lib/python3.9/site-packages/gradio/utils.py", line 888, in check_function_inputs_match
    parameter_types = get_type_hints(fn)
  File "/home/hysts/.virtualenvs/py3916/lib/python3.9/site-packages/gradio/utils.py", line 862, in get_type_hints
    return typing.get_type_hints(fn)
  File "/home/hysts/.pyenv/versions/3.9.16/lib/python3.9/typing.py", line 1497, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/home/hysts/.pyenv/versions/3.9.16/lib/python3.9/typing.py", line 292, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/home/hysts/.pyenv/versions/3.9.16/lib/python3.9/typing.py", line 554, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

### System Info

```shell
latest
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Adding to 3.x milestone as this could break a lot of gradio demos running on Python 3.9

**Comment by akx** [comment]
This is the reason I disabled new-style annotations in the Ruff config.

https://github.com/gradio-app/gradio/blob/8b72e9e1272e9468646d9d5c689ec60a8cac0da8/pyproject.toml#L83

**Comment by abidlabs** [comment]
> This is the reason I disabled new-style annotations in the Ruff config.

But even annotations like this in user-defined functions cause this error in `gradio`
