### ISSUE TITLE
JSONDecodeError when importing gradio behind firewall

### ISSUE THREAD

**Issue by davidai** [gradio-app/gradio#4237]
### Describe the bug

When simplejson package is installed and trying to import gradio on a machine without an external internet connection, JSONDecodeError occurs.

I plan to submit a PR for this issue.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`import gradio`

### Logs

```shell
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/dist-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/dist-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gradio/strings.py", line 38, in get_updated_messaging
    updated_messaging = requests.get(MESSAGING_API_ENDPOINT, timeout=3).json()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
```

### System Info

```shell
gradio 3.29.0, Python 3.8.10, Ubuntu 20.04.4 LTS
```

### Severity

blocking all usage of gradio

**Comment by freddyaboulton** [comment]
Do you want to put up a PR to catch this error @davidai ?

**Comment by davidai** [comment]
I have the [changes](https://github.com/gradio-app/gradio/compare/main...davidai:gradio:fix_jsondecodeerror) ready but having difficulty following the steps in the `CONTRIBUTING.md` file. In particular, `bash scripts/build_frontend.sh` is giving the error

```
> @gradio/client@0.1.0 bundle /Users/davidai/ml/gradio/client/js
> vite build --ssr

file:///Users/davidai/ml/gradio/node_modules/.pnpm/vite@4.2.1_@types+node@17.0.14/node_modules/vite/dist/node/chunks/dep-79892de8.js:42075
                    typeof val === 'string' && /^[\p{L}_$]/u.test(val.trim())
                                               ^^^^^^^^^^^^^

SyntaxError: Invalid regular expression: /^[\p{L}_$]/: Invalid property name in character class
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)

Node.js v18.15.0
 ELIFECYCLE  Command failed with exit code 1.
/Users/davidai/ml/gradio/client/js:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @gradio/client@0.1.0 build: `pnpm bundle && pnpm generate_types`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by freddyaboulton** [comment]
Can you use node v16? Also, for this change you don't have to build the front end but happy to help debug the set up with you regardless!

**Comment by davidai** [comment]
Thank you! That worked. After running all the tests, six of them failed. Trying to figure them out now.

**Comment by davidai** [comment]
@freddyaboulton Tests pass (needed to install ffmpeg) and ready to make a PR. The instructions state the first step is `An initial review has been requested`. How do I request an initial review and to whom do I request it from?

**Comment by freddyaboulton** [comment]
Once you open the PR someone will review it!
