### ISSUE TITLE
how to use gr.Audio(source="microphone", type="filepath") in baidu-api

### ISSUE THREAD

**Issue by guoliangxie123** [gradio-app/gradio#4254]
how to solve it? ~ help,help
--------------------------------------------------------------------------------------------
To create a public link, set `share=True` in `launch()`.
C:\software\anaconda\1\envs\ml\lib\site-packages\gradio\processing_utils.py:183: UserWarning: Trying to convert audio automatically from int32 to 16-bit int format.
  warnings.warn(warning.format(data.dtype))
Traceback (most recent call last):
  File "C:\software\anaconda\1\envs\ml\lib\site-packages\gradio\routes.py", line 421, in run_predict
    event_data=event_data,
  File "C:\software\anaconda\1\envs\ml\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    fn_index, inputs, iterator, request, event_id, event_data
  File "C:\software\anaconda\1\envs\ml\lib\site-packages\gradio\blocks.py", line 1049, in call_function
    fn, *processed_input, limiter=self.limiter
  File "C:\software\anaconda\1\envs\ml\lib\site-packages\anyio\to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "C:\software\anaconda\1\envs\ml\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\software\anaconda\1\envs\ml\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:/code/python/test/tts.py", line 14, in transcribe
    "dev_pid": 1536,
  File "C:\software\anaconda\1\envs\ml\lib\site-packages\aip\speech.py", line 69, in asr
    data['speech'] = base64.b64encode(speech).decode()
  File "C:\software\anaconda\1\envs\ml\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

**Comment by abidlabs** [comment]
Hi @guoliangxie123 there is no reproduction provided here. From the description, it's not clear if it's an issue with `gradio` generally, or a specific gradio app, called `baidu-api`. I'm going to close this issue, but please feel free to reopen with a simple example that we can reproduce with step-by-step instructions.
