### ISSUE TITLE
Error with upgrade to v3.31.0

### ISSUE THREAD

**Issue by jrowen** [gradio-app/gradio#4257]
### Describe the bug

Error on opening app with v3.31.0 (worsk with v3.30.0):
```
index.js:366  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '6')
    at Object.j [as submit] (index.js:366:20)
    at pe (Blocks.svelte:298:6)
    at Blocks.svelte:285:7
j @ index.js:366
pe @ Blocks.svelte:298
(anonymous) @ Blocks.svelte:285
```
Coming from this code:
![image](https://github.com/gradio-app/gradio/assets/1530030/2557ca05-80c3-4ef5-8926-6671b96e6b89)
![image](https://github.com/gradio-app/gradio/assets/1530030/d80956a1-a091-4f57-bef7-3bd8478d9325)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See above. If this isn't sufficient, let me know.

### Logs

```shell
See above
```

### System Info

```shell
v3.31.0, Edge 112.0.1722.77
```

### Severity

blocking upgrade to latest gradio version

**Comment by abidlabs** [comment]
Thanks @jrowen, what's the code that produces this error?

**Comment by jrowen** [comment]
I'm seeing the error when the app loads.  Unfortunately, I don't have a simple example that I can share.

**Comment by abidlabs** [comment]
Ok because we've tested a variety of standard apps and they all work fine. We won't be able to make progress on this issue without a simple repro

**Comment by jrowen** [comment]
I think this may work.  I'm running as part of a fastapi using `gr.mount_gradio_app(app, test(), path=f"test")`
```
def test():

    get_window_url_params = """
        function(url_params) {
            console.log(url_params);
            const params = new URLSearchParams(window.location.search);
            url_params = Object.fromEntries(params);
            return JSON.stringify(url_params);
            }
        """

    def parse_URL_params(url_params):
        _url_params = json.loads(url_params)
        print(f'got url_params: {_url_params}')
        return(_url_params.get('token', _url_params.get('id_token')))

    with gr.Blocks(css='static/md.css') as demo:

        demo.load(
            fn=parse_URL_params,
            inputs=[],
            outputs=[],
            _js=get_window_url_params
        )

    return demo
```
The actual error with this example is
```
index.js:366  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at Object.j [as submit] (index.js:366:20)
    at pe (Blocks.svelte:298:6)
    at Blocks.svelte:285:7
```

**Comment by luav** [comment]
I have the same issue with `gradio==3.31.0 `:
```
index.js:366 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at Object.j [as submit] (index.js:366:20)
    at pe (Blocks.svelte:298:6)
    at je (Blocks.svelte:292:5)
j @ index.js:366
pe @ Blocks.svelte:298
je @ Blocks.svelte:292
await in je (async)
(anonymous) @ Blocks.svelte:373
(anonymous) @ index.mjs:1170
Fr @ index.mjs:1170
f @ Button.svelte:12
(anonymous) @ index.mjs:1170
Fr @ index.mjs:1170
v @ Button.svelte:11
Show 4 more frames
```
on clicking the input button `Submit`.
This issue occurs *when the gradio app is mounted* rather than being launched via the respective method of the interface.

A simple example:
```python
from fastapi import FastAPI
import gradio as gr
grio = gr.Interface(lambda x: "Hello, " + x + "!", "textbox", "textbox", analytics_enabled=False)
app = gr.mount_gradio_app(FastAPI(), grio, path='/')
# Note: the same issue occurs when mounting the app as:
# app = FastAPI()
# app.mount('/', gr.routes.App.create_app(grio))

# Run the app above-defined app
# either by executing it manually from the terminal via the unicorn as `uvicorn FILENAME:app --reload`,
# or by executing the following code:
from uvicorn import Config, Server
config = Config(app, port=8080)
server = Server(config=config)
await server.serve()
# or, instead of `await server.serve()`:
# import asyncio
# loop = asyncio.get_event_loop()
# loop.create_task(server.serve())
```

**Comment by abidlabs** [comment]
Thanks for the repro, we'll take a look! cc @pngwn did we make a change here?
