### ISSUE TITLE
No "exports" main defined in `@gradio/client` - nestjs and other

### ISSUE THREAD

**Issue by lisandropuzzolo** [gradio-app/gradio#4260]
### Describe the bug

I tried the gradio node client on new and existings nestjs project and all give me this error:

```
Error: No "exports" main defined in projects/nest-gradio/node_modules/@gradio/client/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:589:7)
    at resolveExports (node:internal/modules/cjs/loader:554:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:594:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1012:27)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (projects/nest-gradio/src/app.controller.ts:3:1)
```

and this is my minimal app.controller.ts:

```
import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';
import { client } from '@gradio/client';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  async getHello() {
    const app = await client('xlm-roberta-base');
    const info =app.view_api();

    return info;
  }
}

```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Create a brand new nestjs project.
```
$ npm i -g @nestjs/cli
$ nest new project-name
```

2. Install gradio node client
```
npm i @gradio/client
```

3. Edit the app.controller.ts to add some gradio client test:
```
import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';
import { client } from '@gradio/client';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  async test() {
    const app = await client('xlm-roberta-base');
    const info =app.view_api();

    return info;
  }
}

```

Run the app:
```
npm run start
```

The console (at least for me) then shows the mentioned error.

### Logs

```shell
Debugger listening on ws://127.0.0.1:42371/430d33b9-4fe3-4df9-8101-76e339641d68
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Error: No "exports" main defined in /home/me/projects/nest-gradio/node_modules/@gradio/client/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:589:7)
    at resolveExports (node:internal/modules/cjs/loader:554:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:594:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1012:27)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/me/projects/nest-gradio/src/app.controller.ts:3:1)
Waiting for the debugger to disconnect...
^CWaiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
```

### System Info

```shell
Gradio node client "version": "0.1.1"
OS: Ubuntu 22.04.2 LTS

[System Information]
OS Version     : Linux 5.19
NodeJS Version : v18.16.0
NPM Version    : 9.5.1 

[Nest CLI]
Nest CLI Version : 9.5.0 

[Nest Platform Information]
platform-express version : 9.4.1
schematics version       : 9.2.0
testing version          : 9.4.1
common version           : 9.4.1
core version             : 9.4.1
cli version              : 9.5.0
```

### Severity

blocking all usage of gradio

**Comment by abidlabs** [comment]
Thanks @lisandropuzzolo for opening the issue. cc-ing @pngwn

**Comment by Ilshidur** [comment]
Hi.
Setting `"type": "module"` in my `package.json` file did the trick for me.

**Comment by abidlabs** [comment]
Hi @lisandropuzzolo can you see if @Ilshidur's suggestion works for you?

**Comment by aednzxy** [comment]
I am also experiencing the same behaviour, node 18. Changing package.json type to module is not appropriate for my scenario.

**Comment by pngwn** [comment]
@aednzxy Can you give me more information about your usecase and  perhaps an example repo? 

The gradio js client is currently shipped as esm only so it does require the consuming package is a module, but we could revisit this if there is no workaround.

**Comment by galipmedia** [comment]
I have a big legacy project that uses commonjs, it would be a nightmare to switch every file to import syntax. I cannot find any way to incorporate gradio/client. Is it possible to hit the huggingface endpoints with just axios and a bearer token ? I have tried a bit but cannot even seem to be able to find the correct endpoint url. Tried https://huggingface.co/api/spaces/${space_id} /host /predict but both say cannot be POSTed to.

**Comment by pngwn** [comment]
@galipmedia the reason we created the client is because using Gradio apps as an API can be pretty involved, so there isn't a simple way to do it. 

I'll follow up the other comments in this thread shortly.

**Comment by kanhaiya0999** [comment]
same problem with me

**Comment by Alex-Golovin** [comment]
same issue, can't use my model on HF via Gradio API :( since @gradio/client is not working, tried different Node versions, nothing helps

**Comment by Sayene** [comment]
you may try this [work-around](https://stackoverflow.com/a/75939304) for importing @gradio/client in commonjs module (e.g. nestjs app)

**Comment by ArtemKolodko** [comment]
same issue

**Comment by jtrujillo7** [comment]
A quick and dirty workaround that works for my needs: An independent bridge ES single module that receives the arguments from the process and writes the output to stdout so it's controllable from the main app (run with child_process.spawn and read child's stdout). I had no need to pass or read files but I guess there would be no problem saving them to a common location.

**Comment by vincent-pli** [comment]
same problem with me

**Comment by arthurwolf** [comment]
« I have a big legacy project that uses commonjs, it would be a nightmare to switch every file to import syntax.  » same issue here.

**Comment by arthurwolf** [comment]
Doing 

```
export const importDynamic = new Function('modulePath', 'return import(modulePath)');

const { client } = await importDynamic('@gradio/client');
```

seemingly worked, but there has to be a cleaner solution here...

(also the call doesn't seem to work/do anything, but that's probably unrelated to the import, maybe?)

**Comment by arthurwolf** [comment]
Doing the «importDynamic» solution is described above ended up not working ( I do not remember why at this point, I think I got no errors, but also no function. I guess that might have been because something unrelated to imports was broken? ).

> A quick and dirty workaround that works for my needs: An independent bridge ES single module that receives the arguments from the process and writes the output to stdout so it's controllable from the main app (run with child_process.spawn and read child's stdout). I had no need to pass or read files but I guess there would be no problem saving them to a common location.

After seeing no progress I ended up implementing the same solution you have (write script, call script with `execSync`), except seemingly I need to pass a lot more stuff along, so the script and the caller got much more involved.

As a dev, this solution feels very nasty (*barf emoji* ... ). 

My project uses hundreds of npm modules, and this is the only one that has this issue (I think there was *one* other a while back, but I had chatgpt rewrite it and then it was fine).

**Comment by cabfile** [comment]
epic fail
```
file:///D:/BOTS/Bytebeat/node_modules/@gradio/client/dist/index.js:1241
class TextLineStream extends TransformStream {
     ^

ReferenceError: TransformStream is not defined
    at file:///D:/BOTS/Bytebeat/node_modules/@gradio/client/dist/index.js:1241:30
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async req (eval at Actions.eval (D:\BOTS\Bytebeat\bot.js:1271:12), :3:17)
```
my code:
```js
const importDynamic = new Function('modulePath', 'return import(modulePath)');
async function req() {
	const gradio = await importDynamic('@gradio/client');
	const app = await client("eswardivi/Phi-3-mini-4k-instruct");
	const result = await app.predict("/chat", [		
		"Hello!!", // string  in 'Message' Textbox component		
		0.7, // number (numeric value between 0 and 1) in 'Temperature' Slider component		
		true, // boolean  in 'Sampling' Checkbox component		
		128, // number (numeric value between 128 and 4096) in 'Max new tokens' Slider component
	]);
	console.log(result);
	dbm.storeValue(result.data, 1, "result", cache);
	dbm.callNextAction(cache);
}
req();
```

**Comment by pngwn** [comment]
What node version?

**Comment by cabfile** [comment]
> What node version?

v18.19.1

**Comment by pngwn** [comment]
Because we haven't had the chance to investigate it properly. I'm pretty sure it is a config issue that needs to be solved in the application itself but we will try to reproduce soon.

**Comment by yardenxr** [comment]
> you may try this [work-around](https://stackoverflow.com/a/75939304) for importing @gradio/client in commonjs module (e.g. nestjs app) this works for me:
> 
> ```ts
> export const importDynamic = new Function('modulePath', 'return import(modulePath)');
> 
> const { client } = await importDynamic('@gradio/client');
> ```

great workaround but we lose typing.

**Comment by CharlesSmart** [comment]
I had the same issue with a fairly fresh Vite/Reast/TS project (Node v16.15.1).
I was able to resolve it by reinstalling but not resolving unsupported dependencies with npm audit fix. Doing so broke my package.json/config. Worth double checking if you're using an older version of node like me.

**Comment by pandas9** [comment]
not sure why this is still an issue in 2024 with packages, but there is a bash version implementation for gradio api

**Comment by dkaangulhan** [comment]
> you may try this [work-around](https://stackoverflow.com/a/75939304) for importing @gradio/client in commonjs module (e.g. nestjs app) this works for me:
> 
> export const importDynamic = new Function('modulePath', 'return import(modulePath)');
> 
> const { client } = await importDynamic('@gradio/client');

This worked for me as a workaround
