### ISSUE TITLE
Doublequotes in Dropdown values break Dropdown menu.

### ISSUE THREAD

**Issue by lcrh** [gradio-app/gradio#4292]
### Describe the bug

I loaded a gradio app I wrote a month ago and noticed that the dropdown menu was non-functional. (It used to work as of mid-April).

In particular, after clicking the down arrow, the UI would become unresponsive and get stuck with the dropdown menu open and unclosable:

![image](https://github.com/gradio-app/gradio/assets/14020730/f654ea96-11ed-4b27-b0cc-298cf6bce5bd)

Looking at the javascript console, I see an error (pasted under "Logs" below).

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run from a notebook cell.
```
import gradio as gr

with gr.Blocks() as blocks:
  dropdown = gr.Dropdown(
    choices=['', '"test"'],
    value='')
blocks.launch(share=True)
```

To reproduce:
1. Click dropdown menu to reveal choices
2. Select "test"
3. Click dropdown menu again to reveal choices

This manifests slightly different than the issue I described above (the menu closes), but shows the same JavaScript error:
```
Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': 'li[data-value=""test""]' is not a valid selector.
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/14020730/f654ea96-11ed-4b27-b0cc-298cf6bce5bd)

### Logs

```shell
DropdownOptions.svelte:19 Uncaught (in promise) DOMException: Failed to execute 'querySelector' on 'Document': 'li[data-value="22da73fd-0f88-51bf-b5f6-462c0fc0782b / public / "dog""]' is not a valid selector.
    at Je.t.$$.update (https://gradio.s3-us-west-2.amazonaws.com/3.31.0/assets/index-10df479e.js:1:3366)
    at Dr (https://gradio.s3-us-west-2.amazonaws.com/3.31.0/assets/index-20f57901.js:4:1833)
    at lr (https://gradio.s3-us-west-2.amazonaws.com/3.31.0/assets/index-20f57901.js:4:1548)
Je.t.$$.update	@	DropdownOptions.svelte:19
Dr	@	index.mjs:1269
lr	@	index.mjs:1233
Promise.then (async)		
sr	@	index.mjs:1184
Wr	@	index.mjs:2066
(anonymous)	@	index.mjs:2104
ve	@	Dropdown.svelte:203
```
```


### System Info

```shell
Gradio version: 3.31.0
Host OS: Ubuntu 20.04
Browser OS: Windows
Browser: Chrome, Version 113.0.5672.93 (Official Build) (64-bit)
```

### Severity

serious, but I can work around it

**Comment by lcrh** [comment]
I'll add that replacing the double quotes by single quotes works around the issue.
