### ISSUE TITLE
Unable to read csv file

### ISSUE THREAD

**Issue by PankajJ08** [gradio-app/gradio#4299]
Hello,

I have encountered an issue when trying to process an uploaded CSV file using Gradio's File input interface. I have a Gradio interface where the input is a File type and the output is a Text type.

When I upload a CSV file to the interface and try to process it within the function linked to the interface, the CSV file appears to be empty. I tried reading the file content using standard Python file operations and even pandas' read_csv, but all approaches seem to result in an empty output. I am certain that the file I'm uploading is not empty and it can be read correctly outside of the Gradio interface.

I am currently using Python 3.10 and Gradio version 3.32.0. Any help on this issue would be greatly appreciated. Thank you.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import gradio as gr
import io

def display_csv(file):
    # Ensure the file pointer is at the start of the file.
    file.seek(0)
    # Read the file as binary
    file_content = file.read()
    # Create a StringIO object from the file content
    file_string = io.StringIO(file_content.decode('utf-8'))
    # Read the CSV data
    df = pd.read_csv(file_string, encoding='utf-8')
    # Return as formatted string
    return df.to_string()

iface = gr.Interface(fn=display_csv, inputs=gr.inputs.File(), outputs='text')
iface.launch(debug=True)

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "<ipython-input-61-ce7d0cea9a5d>", line 16, in display_csv
    df = pd.read_csv(file_string, encoding='utf-8')
  File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/c_parser_wrapper.py", line 79, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 554, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

### System Info

```shell
Gradio version: 3.32.0, Python version: 3.10, system: Google colab
```

### Severity

annoying

**Comment by akx** [comment]
Why not just ```
def display_csv(file):
    df = pd.read_csv(file, encoding='utf-8')
    return df.to_string()
```
?

**Comment by PankajJ08** [comment]
At first, I tried the same thing but I still got the same error.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "<ipython-input-3-c067bdc64904>", line 9, in display_csv
    df = pd.read_csv(file, encoding='utf-8')
  File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/c_parser_wrapper.py", line 79, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 554, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by freddyaboulton** [comment]
Hi @PankajJ08 !

Please try this:

```python
import gradio as gr
import pandas as pd

def display_csv(file):
    df = pd.read_csv(file.name, encoding='utf-8')
    # Return as formatted string
    return df.to_string()

iface = gr.Interface(fn=display_csv, inputs=gr.inputs.File(), outputs='text')
iface.launch(debug=True)
```

**Comment by PankajJ08** [comment]
It worked. Thanks, @freddyaboulton :)

**Comment by PankajJ08** [comment]
closed.
