### ISSUE TITLE
Request terminated when function runs >5 sec (queue enabled, websocket message outputs error)

### ISSUE THREAD

**Issue by mikitakandratsiuk** [gradio-app/gradio#4306]
### Describe the bug

I have a chatbot that streams data (queue enabled). When the message is submitted, and the function execution takes more than 5 seconds, two things happen:
- frontend - seems like it stops adding a bot's (response) message, a "progress" block with "..." disappears
- backend - function is executed until the first **yield** and stops

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import time
import gradio as gr

def gr_request_submit(input_message, chat_history_layout):
    return "", chat_history_layout + [[input_message, None]]

def gr_respond(chat_history_layout):
    print(f"Checkpoint 1: {time.time()}")
    time.sleep(10)

    print(f"Checkpoint 2: {time.time()}")
    chat_history_layout[-1][1] = ""

    for chunk in "Response from the bot":
        chat_history_layout[-1][1] += chunk
        print(f"Checkpoint 3: {time.time()}")
        yield chat_history_layout

    print(f"Checkpoint 4: {time.time()}")

with gr.Blocks() as app:
    gr_chat_bot = gr.Chatbot()
    gr_text_box = gr.Textbox()

    (gr_text_box
     .submit(fn=gr_request_submit, inputs=[gr_text_box, gr_chat_bot], outputs=[gr_text_box, gr_chat_bot], queue=False)
     .then(fn=gr_respond, inputs=[gr_chat_bot], outputs=[gr_chat_bot]))

app.queue(concurrency_count=10).launch()
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/33225805/3f9d5e95-1824-4c35-86c7-6ebea6899d53)

### Logs

```shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Checkpoint 1: 1684763061.7929974
Checkpoint 2: 1684763071.7940972
Checkpoint 3: 1684763071.7943397
Keyboard interruption in main thread... closing server.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022B036B37F0>
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000022B036B37F0>
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
```

### System Info

```shell
Gradio 3.28.3
OS Windows 11 Home 22H2
Browser Google Chrome Version 113.0.5672.93
```

### Severity

serious, but I can work around it

**Comment by freddyaboulton** [comment]
Hi @mikitakandratsiuk ! Thanks for filing. Will try to repro later today!

**Comment by mikitakandratsiuk** [comment]
Hi @freddyaboulton, did you have a chance to check it?

**Comment by freddyaboulton** [comment]
Sorry for the delay @mikitakandratsiuk ! I can't repro this. Does this problem happen consistently for you?

![queue_timeout_repro](https://github.com/gradio-app/gradio/assets/41651716/34b99746-a30d-403a-a549-d83370b34a47)

<img width="430" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/8444a331-ebaa-4c52-80cf-9801ee2ab124">

**Comment by mikitakandratsiuk** [comment]
Hi @freddyaboulton, thanks a lot for taking the issue.

After your message I did some additional investigation. The problem was resolved when I updated `httpx` version from `0.13.3` to `0.24.1`. I've checked the code and seems that the old version of `httpsx` had a 5 seconds timeout.

From my side the issue can be closed. Thanks!

**Comment by hundunaning** [comment]
omg, I meet the same question, but my httpx version is 0.27.2, gradio 3.37.0 by the way.
