### ISSUE TITLE
Support `pathlib.Path` as `value=` of `gr.Gallery`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#4496]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

The following code works,
```python
import pathlib

import gradio as gr

paths = sorted(pathlib.Path('images').glob('*'))
paths = [str(path) for path in paths]
with gr.Blocks() as demo:
    gallery = gr.Gallery(value=paths).style(columns=2)
demo.queue().launch()
```
but the following doesn't.
```python
import pathlib

import gradio as gr

paths = sorted(pathlib.Path('images').glob('*'))
with gr.Blocks() as demo:
    gallery = gr.Gallery(value=paths).style(columns=2)
demo.queue().launch()
```
It would be useful if we didn't have to convert `pathlib.Path` to `str` when passing to `gr.Gallery`.

BTW, the error shown when `pathlib.Path` is passed as `value` is a bit off and confusing.
```
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.virtualenvs/py31011/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/ubuntu/.virtualenvs/py31011/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/.virtualenvs/py31011/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/ubuntu/.virtualenvs/py31011/lib/python3.10/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/ubuntu/.virtualenvs/py31011/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/repos/temp/2023-06-13-gallery/app.py", line 8, in <module>
    with gr.Blocks() as demo:
  File "/home/ubuntu/.virtualenvs/py31011/lib/python3.10/site-packages/gradio/blocks.py", line 1434, in __exit__
    self.config = self.get_config_file()
  File "/home/ubuntu/.virtualenvs/py31011/lib/python3.10/site-packages/gradio/blocks.py", line 1401, in get_config_file
    props = block.get_config() if hasattr(block, "get_config") else {}
  File "/home/ubuntu/.virtualenvs/py31011/lib/python3.10/site-packages/gradio/components.py", line 4446, in get_config
    "value": self.value,
AttributeError: 'Gallery' object has no attribute 'value'
```

**Comment by abidlabs** [comment]
Sure -- we can do this. And also make sure that the other file components can accept `Path` objects

**Comment by abidlabs** [comment]
Feel free to PR this if you'd like to give it a shot!

**Comment by abidlabs** [comment]
All of our file components now support pathlib.Paths!
