### ISSUE TITLE
Error in chatbot response when authentication from OAuth provider is enabled

### ISSUE THREAD

**Issue by mikitakandratsiuk** [gradio-app/gradio#4553]
### Describe the bug

I have a chatbot that streams data (queue enabled). The application is deployed in cloud on Azure Container App. In this setup application is working fine and outputs the response as expected.

In the Azure Container Apps there is a built in feature to [enable authentication from OAuth provider](https://learn.microsoft.com/en-us/azure/container-apps/authentication#feature-architecture) (in my case I use Azure Active Directory). When I enable this feature, my chatbot stops returning the response and shows the error. On the backend side I get the exceptions (attached below).

I have validated that this authentication feature from Azure supports Web Socket connections and Server Sent Events (I have used `jmalloc/echo-server` as described in [this issue](https://github.com/microsoft/azure-container-apps/issues/549) and it works fine). This is why I suppose the root of the problem is not on the Azure side, but probably on Gradio's.

P.S.
For me this issue is severe and app doesn't meet user requirements, this is why I chose the corresponding Severity. Please, let me know it it should be changed.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

def gr_request_submit(input_message, chat_history_layout):
    return "", chat_history_layout + [[input_message, None]]

def gr_respond(chat_history_layout):
    chat_history_layout[-1][1] = ""

    for chunk in "Response from the bot":
        chat_history_layout[-1][1] += chunk
        yield chat_history_layout

with gr.Blocks() as app:
    gr_chat_bot = gr.Chatbot()
    gr_text_box = gr.Textbox()

    (gr_text_box
     .submit(fn=gr_request_submit, inputs=[gr_text_box, gr_chat_bot], outputs=[gr_text_box, gr_chat_bot], queue=False)
     .then(fn=gr_respond, inputs=[gr_chat_bot], outputs=[gr_chat_bot]))

app.queue(concurrency_count=10).launch(server_name="0.0.0.0", server_port=81)
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/33225805/d9ba9584-f004-439b-b16e-046a2b662f21)

### Logs

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 292, in app
    await dependant.call(**values)
  File "/usr/local/lib/python3.10/site-packages/gradio/routes.py", line 546, in join_queue
    session_info = await asyncio.wait_for(
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1002
```

### System Info

```shell
gradio - 3.28.3
base container image - python:3.10-slim
```

### Severity

blocking all usage of gradio

**Comment by mikitakandratsiuk** [comment]
The issue was related to Azure Container Apps and not to Gradio. Sorry for inconvenience. I close the issue.

**Comment by vikaskookna** [comment]
@mikitakandratsiuk I'm facing a similar issue with the azure web app and container registry can you please help me resolve it?

**Comment by mikitakandratsiuk** [comment]
Hi @vikaskookna,
you can find more details here https://github.com/microsoft/azure-container-apps/issues/812

As a workaround, I extended `Blocks` class and overloaded `launch` function so that the `uvicorn.config(...)` has `ws_per_message_deflate=False`.

If you find a better solution, please let me know. I was also thinking on creating an issue in Gradio to allow the `uvicorn` configuring.
