### ISSUE TITLE
Got unknown type H

### ISSUE THREAD

**Issue by hamzafarooq** [gradio-app/gradio#4561]
### Describe the bug

Getting a traceback error when trying to run basic code - the code works without the gradio app 
Running the latest 3.14.0 version of gradio

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

 a very basic app 

```
def greet(query):
    retriever = SerperSearchRetriever(GoogleSerperAPIWrapper())

    llm = ChatOpenAI(temperature=0)

    flare = FlareChain.from_llm(
        ChatOpenAI(temperature=0), 
        retriever=retriever,
        max_generation_len=200,
        min_prob=.3,
    )

    logofflare=flare.run(query)
    response=llm(query)
    return logofflare.strip(),response.strip()

demo = gr.Interface(fn=greet, title="xx", inputs="text", 
                    outputs=[gr.components.Textbox(lines=3, label="Response"),
                            gr.components.Textbox(lines=3, label="List")])

demo.launch(share=True)
```

### Logs

```shell
`Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 847, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/jupyter/serper/trispby-flare.py", line 115, in greet
    response=llm(query)
  File "/opt/conda/lib/python3.10/site-packages/langchain/chat_models/base.py", line 183, in __call__
    generation = self.generate(
  File "/opt/conda/lib/python3.10/site-packages/langchain/chat_models/base.py", line 92, in generate
    raise e
  File "/opt/conda/lib/python3.10/site-packages/langchain/chat_models/base.py", line 84, in generate
    results = [
  File "/opt/conda/lib/python3.10/site-packages/langchain/chat_models/base.py", line 85, in <listcomp>
    self._generate(m, stop=stop, run_manager=run_manager)
  File "/opt/conda/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 306, in _generate
    message_dicts, params = self._create_message_dicts(messages, stop)
  File "/opt/conda/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 334, in _create_message_dicts
    message_dicts = [_convert_message_to_dict(m) for m in messages]
  File "/opt/conda/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 334, in <listcomp>
    message_dicts = [_convert_message_to_dict(m) for m in messages]
  File "/opt/conda/lib/python3.10/site-packages/langchain/chat_models/openai.py", line 117, in _convert_message_to_dict
    raise ValueError(f"Got unknown type {message}")
ValueError: Got unknown type H`
```

### System Info

```shell
gradio-3.14.0
```

### Severity

annoying

**Comment by abidlabs** [comment]
Hi @hamzafarooq the latest version of `gradio` is `3.35.2`. Please check that version and let us know if you still experience this issue.

**Comment by abidlabs** [comment]
Closing for lack of follow up
