### ISSUE TITLE
Prediction fails with unhelpful message

### ISSUE THREAD

**Issue by osanseviero** [gradio-app/gradio#460]
**Describe the bug**
This self-contained example which was working before in HF Spaces is not working anymore, failing in the prediction.

```python
import gradio as gr

description = "BigGAN text-to-image demo."
title = "BigGAN ImageNet"

interface = gr.Interface.load(
    "huggingface/osanseviero/BigGAN-deep-128", 
    description=description,
    title = title,
    examples=[["american robin"], ["chest"], ["soap bubble"]]
)

interface.launch()
```

The provided errors are not helpful and this same code was working some time ago

```
[2022-01-15 17:35:06,539] ERROR in app: Exception on /api/predict/ [POST]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/.local/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/networking.py", line 93, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/networking.py", line 232, in predict
    prediction, durations = process_example(app.interface, example_id)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/process_examples.py", line 12, in process_example
    prediction, durations = interface.process(raw_input)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 411, in process
    predictions, durations = self.run_prediction(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/interface.py", line 384, in run_prediction
    prediction.append(self.output_components[output_component_counter].deserialize(pred))
  File "/home/user/.local/lib/python3.8/site-packages/gradio/outputs.py", line 239, in deserialize
    y = processing_utils.decode_base64_to_file(x).name
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 141, in decode_base64_to_file
    data, extension = decode_base64_to_binary(encoding)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 136, in decode_base64_to_binary
    extension = get_extension(encoding)
  File "/home/user/.local/lib/python3.8/site-packages/gradio/processing_utils.py", line 48, in get_extension
    extension = mimetypes.guess_extension(mimetypes.guess_type(
  File "/usr/local/lib/python3.8/mimetypes.py", line 326, in guess_extension
    return _db.guess_extension(type, strict)
  File "/usr/local/lib/python3.8/mimetypes.py", line 192, in guess_extension
    extensions = self.guess_all_extensions(type, strict)
  File "/usr/local/lib/python3.8/mimetypes.py", line 171, in guess_all_extensions
    type = type.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Screenshots**
USeful links:
* https://huggingface.co/spaces/osanseviero/test_gradio_2
* https://huggingface.co/spaces/osanseviero/test_gradio_2/logs/container

**Comment by abidlabs** [comment]
Fixed!
