### ISSUE TITLE
TypeError: Integer exceeds 64-bit range

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#4647]
### Describe the bug

Started since upgrading from gradio==3.34.0 to gradio==3.35.2 .

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/routes.py", line 269, in main
    return templates.TemplateResponse(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/starlette/templating.py", line 113, in TemplateResponse
    return _TemplateResponse(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/starlette/templating.py", line 39, in __init__
    content = template.render(context)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/templates/frontend/share.html", line 41, in top-level template code
    <script>window.gradio_config = {{ config | toorjson }};</script>
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/routes.py", line 84, in toorjson
    ORJSONResponse._render_str(value)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/routes.py", line 79, in _render_str
    return ORJSONResponse._render(content).decode("utf-8")
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/routes.py", line 68, in _render
    return orjson.dumps(
TypeError: Integer exceeds 64-bit range
ERROR:    Exception in ASGI application

```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Working on repro, hoping for feedback to help isolate.  Happens when using client to connect to gradio server.

### System Info

```shell
python==3.10
Ubuntu==22
gradio==3.35.2
gradio_client==0.2.7
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hmm so this doesn't happen when accessing the demo via a web browser? That stacktrace  points to loading the "/" route which the client does not access. 

Does the app have a really large value as either a default value of a component or in the examples? Looks like the error is coming from dumping the config to the index.html page

**Comment by pseudotensor** [comment]
Feel free to close if want, I so far haven't hit again.  It's obviously not fixed, but it's not common.

**Comment by abidlabs** [comment]
Ok thanks @pseudotensor we're happy to reopen if you are able to repro
