### ISSUE TITLE
TypeError when using gr.update() to update 'info' property of gr.Slider 

### ISSUE THREAD

**Issue by linoytsaban** [gradio-app/gradio#4726]
### Describe the bug

When trying to use `gr.update` to change the `info` value of a `gr.Slider` I get a `TypeError`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr

def change_slider_info():
  return gr.update(info="TEST")

with gr.Blocks() as demo:
    slider = gr.Slider( 0, 100, step=0.1, interactive=True,value=10,)
    button = gr.Button()
    button.click(fn=change_slider_info, outputs=[slider])

demo.queue()
demo.launch(debug=True)
```

### Logs

```shell
Traceback of the TypeError:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1355, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1280, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 437, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 310, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: Slider.update() got an unexpected keyword argument 'info'
```
```


### System Info

```shell
Version: 3.35.2
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Thanks for filing @linoytsaban ! Right now we don't allow updating the info but it should be possible to do so.

**Comment by pngwn** [comment]
Isnt this #4671?

Which was recently address by #4715

**Comment by abidlabs** [comment]
Yes that's right -- and I just verified that the repro from this issue now works on `main`. Closing, thanks all

**Comment by abidlabs** [comment]
@linoytsaban, you can install gradio from `main` by following the instructions here: https://gradio.app/docs/main

**Comment by linoytsaban** [comment]
Thanks!
