### ISSUE TITLE
Video fails when value is a URL.

### ISSUE THREAD

**Issue by Sreerag-ibtl** [gradio-app/gradio#4878]
### Describe the bug

I am using a Video component with the value set as a public video URL. But the pre-process function is throwing the below error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1382, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1225, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/video.py", line 207, in preprocess
    file_name = Path(self.make_temp_copy_if_needed(file_name))
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 220, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 184, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'public-url'
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio

url: str = "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"

with gradio.Blocks() as interface:
  video_in: gradio.Video = gradio.Video(value=url, autoplay=False)
  video_out: gradio.Video = gradio.Video()
  run: gradio.Button = gradio.Button()
  run.click(lambda x: x, video_in, video_out)

interface.launch(debug=True, share=True)
```

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1382, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1225, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/video.py", line 207, in preprocess
    file_name = Path(self.make_temp_copy_if_needed(file_name))
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 220, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 184, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'public-url'
```

### System Info

```shell
1. Gradio version: 3.36.1
2. Ubuntu: 22.04
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Thanks for filing @Sreerag-ibtl . We should pass through the URL in this case.

**Comment by freddyaboulton** [comment]
Hi @Sreerag-ibtl - yes gradio will download the video for your and give it to your function as a file!

**Comment by abidlabs** [comment]
We should implement it so that downloading of the URL only happens in `.preprocess()` -- `.postprocess()` should leave the video src url as is

**Comment by freddyaboulton** [comment]
I believe that's the case already (unless the video needs to be converted to a separate format)
https://github.com/gradio-app/gradio/blob/main/gradio/components/video.py#L316

**Comment by Johnserf-Seed** [comment]
hey guys. I also have a similar problem, which is that when my public video URL has parameters, it cannot function properly. 
Here is an example
```python
video_url = 'https://www.douyin.com/aweme/v1/play/?video_id=v0200fg10000ci8h233c77uc9mbr4pdg'
dy_video = gr.Video(video_url)
```
 After running, it becomes this link
```https://www.douyin.com/aweme/v1/play```

![image](https://github.com/gradio-app/gradio/assets/40727745/87a8efa8-911d-4443-b240-a2c0b82fd8ad)

![image](https://github.com/gradio-app/gradio/assets/40727745/70577e65-b1a5-44b2-af7d-afc467a108a2)

I don't know if it's because Gradio doesn't support it
