### ISSUE TITLE
Documentation page has an error with CheckBox

### ISSUE THREAD

**Issue by JElbourne** [gradio-app/gradio#4922]
### Describe the bug

Documentation page has an error with CheckBox

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Visit the webpage https://www.gradio.app/docs/chatbot
, Then go to checkbox page or another https://www.gradio.app/docs/checkbox

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/556142/ee636a42-bf8d-4fe6-9bf0-9915778b0379)

### System Info

```shell
Webpage on your site
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
There is an error in the console @aliabd 

```js
Uncaught (in promise) DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at yt (https://www.gradio.app/_app/immutable/chunks/index.a326135e.js:1:2748)
    at Object.m (https://www.gradio.app/_app/immutable/nodes/6.a488eca3.js:1:4854)
    at Object.p (https://www.gradio.app/_app/immutable/nodes/6.a488eca3.js:1:3940)
    at Object.p (https://www.gradio.app/_app/immutable/nodes/6.a488eca3.js:17:3776)
    at $t (https://www.gradio.app/_app/immutable/chunks/index.a326135e.js:1:6906)
    at rt (https://www.gradio.app/_app/immutable/chunks/index.a326135e.js:1:6559)
```

**Comment by johnson7788** [comment]
same issue, gradio-3.45.0, when use chatbox 
Uncaught (in promise) DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at T (https://gradio.s3-us-west-2.amazonaws.com/3.45.0/assets/index-a9603da9.js:2:12017)
    at Gc.i (https://gradio.s3-us-west-2.amazonaws.com/3.45.0/assets/index-a9603da9.js:2:14895)
    at Gc.p (https://gradio.s3-us-west-2.amazonaws.com/3.45.0/assets/index-a9603da9.js:2:14946)
    at Object.p (https://gradio.s3-us-west-2.amazonaws.com/3.45.0/assets/StaticMarkdown-ae9af4d2.js:339:365)
    at Object.p (https://gradio.s3-us-west-2.amazonaws.com/3.45.0/assets/StaticMarkdown-ae9af4d2.js:339:621)
    at _a (https://gradio.s3-us-west-2.amazonaws.com/3.45.0/assets/index-a9603da9.js:5:1914)
    at To (https://gradio.s3-us-west-2.amazonaws.com/3.45.0/assets/index-a9603da9.js:5:1548)

**Comment by abidlabs** [comment]
Hi @johnson7788 can you share the code that is leading to this error for you?

**Comment by alok5050** [comment]
Hello,I would like to contribute to this issue.
Is it still open?
