### ISSUE TITLE
Audio updated via _js breaks preprocess.

### ISSUE THREAD

**Issue by Sreerag-ibtl** [gradio-app/gradio#4958]
### Describe the bug

I am passing a javascript function to _js which returns an audio URL. This is expected to update the audio which is the case. But this audio component, when used as input in the button click event, it throws an error.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio

audio_url = "http://codeskulptor-demos.commondatastorage.googleapis.com/GalaxyInvaders/alien_hit.wav"

with gradio.Blocks() as blocks:
  audio = gradio.Audio(value=audio_url, type='filepath',)
  output = gradio.Audio()
  button = gradio.Button(value='Button')
  submit = gradio.Button(value='Submit')

  # First click here.
  button.click(None, None, [audio], _js="""function () {return 'http://codeskulptor-demos.commondatastorage.googleapis.com/GalaxyInvaders/alien_hit.wav'}""")

  # Then here.
  submit.click(lambda x: x, [audio], [output])

blocks.launch(debug=True)
```

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1387, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1230, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/audio.py", line 191, in preprocess
    x["name"],
TypeError: string indices must be integers
```

### System Info

```shell
1. Gradio: 3.37.0
2. Colab, Ubuntu 22.04
3. Browser: Firefox
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue, but the Gradio codebase has changed quite significantly since this issue was created. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but can reopen if needed
