### ISSUE TITLE
An error occurred while updating the DataFrame

### ISSUE THREAD

**Issue by minskiter** [gradio-app/gradio#5041]
### Describe the bug

When I try to update DataFrame with number change, fastapi has an error.
The exception below:
```sh
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/******/miniconda3/envs/resume/lib/python3.10/site-packages/fastapi/encoders.py", line 230, in jsonable_encoder
    data = dict(obj)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/******/miniconda3/envs/resume/lib/python3.10/site-packages/fastapi/encoders.py", line 235, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/******/miniconda3/envs/resume/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/******/miniconda3/envs/resume/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/******/miniconda3/envs/resume/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/home/******/miniconda3/envs/resume/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/******/miniconda3/envs/resume/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
...
    jsonable_encoder(
  File "/home/******/miniconda3/envs/resume/lib/python3.10/site-packages/fastapi/encoders.py", line 238, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [ValueError('dictionary update sequence element #0 has length 1; 2 is required'), TypeError('vars() argument must have __dict__ attribute')] 
```
Similar to #2916

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Use the following code to reproduce the problem. If you comment the line below `error here` then it works.
``` python
import gradio as gr
import pandas as pd
from typing import Any
import datasets
test = datasets.load_dataset(
    "minskiter/weibo",
    split=datasets.Split.TEST
)
int2str = test.features["labels"].feature.int2str
df = test.to_pandas()

cur = df.loc[:10]

def show(page: float)-> pd.DataFrame:
    page = int(page)
    cur = df.iloc[page*10:(page+1)*10-1]
    # error here
    return cur
    # works here
    return pd.DataFrame([[1,2,3]])

def getobj():
    return {
        "word":[],
        "start": -1,
        "end": -1,
        "entity": "O"
    }

def showIter(evt: gr.SelectData)->dict[str, Any]:
    row = cur.values.tolist()[evt.index[0]]
    text,labels = row[0],row[1]
    labels = int2str(list(map(int,labels)))
    entities = []
    obj = getobj()
    labels.append("O")
    for i,label in enumerate(labels):
        if label[0]=='B' or label[0]=="S" or label[0]=="O":
            if len(obj["word"])>0:
                obj["word"] = "".join(obj["word"])
                entities.append(obj)
                obj = getobj()
        if label[0]=="B":
            obj["start"] = i
            obj["end"] = i+1
            obj["word"].append(text[i])
            obj["entity"] = label.split("-")[-1]
        elif label[0]=="S":
            obj["start"] = i
            obj["end"] = i+1
            obj["word"] = text[i]
            obj["entity"] = label.split("-")[-1]
            entities.append(obj)
            obj = getobj()
        elif label[0]=='E' or label[0]=="I" or label[0]=="M":
            obj["word"].append(text[i])
            obj["end"] = i+1
    return {"text": "".join(text), "entities": entities}

with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column():
            output = gr.DataFrame(value=cur)
            page = gr.Number(minimum=0,maximum=270//10,label="page")
            page.change(show, page, outputs=output)
        text = gr.HighlightedText(label="preview")
        output.select(showIter,inputs=[], outputs=[text])
        
demo.launch()
```

### System Info

```shell
Gradio Environment Information:
Operating System:  Linux


gradio version:  3.39.0

gradio Dependencies:
  aiofiles: 23.1.0
  aiohttp: 3.8.5
  altair: 5.0.1
  fastapi: 0.100.1
  ffmpy: 0.3.1
  gradio-client: 0.3.0
  httpx: 0.24.1
  huggingface-hub: 0.16.4
  jinja2: 3.1.2
  markdown-it-py: 2.2.0
  markupsafe: 2.1.2
  matplotlib: 3.7.2
  mdit-py-plugins: 0.3.3
  numpy: 1.25.1
  orjson: 3.9.2
  packaging: 23.1
  pandas: 2.0.3
  pillow: 10.0.0
  pydantic: 2.1.1
  pydub: 0.25.1
  python-multipart: 0.0.6
  pyyaml: 6.0.1
  requests: 2.31.0
  semantic-version: 2.10.0
  typing-extensions: 4.6.3
  uvicorn: 0.23.1
  websockets: 11.0.3


gradio_client version:  0.3.0

gradio_client Dependencies:
  fsspec: 2023.4.0
  httpx: 0.24.1
  huggingface-hub: 0.16.4
  packaging: 23.1
  requests: 2.31.0
  typing-extensions: 4.6.3
  websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @minskiter can you provide a repro with a public dataset? When I tried running this, I got:

> FileNotFoundError: Couldn't find a dataset script at /Users/abidlabs/dev/gradio-repos/notebooks/minskiter/weibo/weibo.py or any data file in the same directory. Couldn't find 'minskiter/weibo' on the Hugging Face Hub either: FileNotFoundError: Dataset 'minskiter/weibo' doesn't exist on the Hub. If the repo is private or gated, make sure to log in with `huggingface-cli login`.

**Comment by minskiter** [comment]
Hi @abidlabs I am now making the original dataset public.
> Hi @minskiter can you provide a repro with a public dataset? When I tried running this, I got:
> 
> > FileNotFoundError: Couldn't find a dataset script at /Users/abidlabs/dev/gradio-repos/notebooks/minskiter/weibo/weibo.py or any data file in the same directory. Couldn't find 'minskiter/weibo' on the Hugging Face Hub either: FileNotFoundError: Dataset 'minskiter/weibo' doesn't exist on the Hub. If the repo is private or gated, make sure to log in with `huggingface-cli login`.

**Comment by abidlabs** [comment]
Hi @minskiter so the issue seems to be that each value in the DataFrame is *itself* an array. FastAPI doesn't seem to like encoding a dataframe of arrays, not sure exactly why. If you change the values to be a string, then it works for me (while visually, the changes are minimal):

```py
import gradio as gr
import pandas as pd
from typing import Any
import datasets
test = datasets.load_dataset(
    "minskiter/weibo",
    split=datasets.Split.TEST
)
int2str = test.features["labels"].feature.int2str
df = test.to_pandas()

for i in range(270):
    df.loc[i].text = ",".join(df.loc[i].text)
    df.loc[i].labels = ",".join([str(x) for x in df.loc[i].labels])    

cur = df.loc[:10]

def show(page: float)-> pd.DataFrame:
    page = int(page)
    cur = df.iloc[page*10:(page+1)*10-1]
    # error here
    return cur
    # works here
    return pd.DataFrame([[1,2,3]])

def getobj():
    return {
        "word":[],
        "start": -1,
        "end": -1,
        "entity": "O"
    }

def showIter(evt: gr.SelectData)->dict[str, Any]:
    row = cur.values.tolist()[evt.index[0]]
    text,labels = row[0],row[1]
    labels = int2str(list(map(int,labels)))
    entities = []
    obj = getobj()
    labels.append("O")
    for i,label in enumerate(labels):
        if label[0]=='B' or label[0]=="S" or label[0]=="O":
            if len(obj["word"])>0:
                obj["word"] = "".join(obj["word"])
                entities.append(obj)
                obj = getobj()
        if label[0]=="B":
            obj["start"] = i
            obj["end"] = i+1
            obj["word"].append(text[i])
            obj["entity"] = label.split("-")[-1]
        elif label[0]=="S":
            obj["start"] = i
            obj["end"] = i+1
            obj["word"] = text[i]
            obj["entity"] = label.split("-")[-1]
            entities.append(obj)
            obj = getobj()
        elif label[0]=='E' or label[0]=="I" or label[0]=="M":
            obj["word"].append(text[i])
            obj["end"] = i+1
    return {"text": "".join(text), "entities": entities}

with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column():
            output = gr.DataFrame(value=cur)
            page = gr.Number(minimum=0,maximum=270//10,label="page")
            page.change(show, page, outputs=output)
        text = gr.HighlightedText(label="preview")
        output.select(showIter,inputs=[], outputs=[text])
        
demo.launch()
```

**Comment by minskiter** [comment]
@abidlabs Thanks. The code below works. Both are DataFrames. What is the difference between the two, and why does the default value of DataFrame work?
```python
import gradio as gr
import gc
import pandas as pd
from typing import Any
import datasets
from tqdm import tqdm
test = datasets.load_dataset(
    "minskiter/weibo",
    split=datasets.Split.TEST,
    streaming=True
)
int2str = test.features["labels"].feature.int2str
page_size = 10
pages = []
i = 0
page = pd.DataFrame(test.take(page_size))
with tqdm(desc="load dataset") as bar:
    while len(page.index)>0:
        pages.append(page)
        i+=1
        page = pd.DataFrame(test.skip(i*page_size).take(page_size))
        bar.update(i)
    
cur = pages[0]

gr.close_all()
gc.collect()

def show(page: float)-> pd.DataFrame:
    global cur
    cur = pages[int(page)]
    return cur 

def getobj():
    return {
        "word":[],
        "start": -1,
        "end": -1,
        "entity": "O"
    }

def showIter(evt: gr.SelectData)->dict[str, Any]:
    row = cur.values.tolist()[evt.index[0]]
    text,labels = row[0],row[1]
    labels = int2str(list(map(int,labels)))
    entities = []
    obj = getobj()
    labels.append("O")
    for i,label in enumerate(labels):
        if label[0]=='B' or label[0]=="S" or label[0]=="O":
            if len(obj["word"])>0 and obj["entity"]!="O":
                obj["word"] = "".join(obj["word"])
                entities.append(obj)
            obj = getobj()
        if label[0]=="B":
            obj["start"] = i
            obj["end"] = i+1
            obj["word"].append(text[i])
            obj["entity"] = label.split("-")[-1]
        elif label[0]=="S":
            obj["start"] = i
            obj["end"] = i+1
            obj["word"] = text[i]
            obj["entity"] = label.split("-")[-1]
            entities.append(obj)
            obj = getobj()
        elif label[0]=='E' or label[0]=="I" or label[0]=="M":
            obj["word"].append(text[i])
            obj["end"] = i+1
    return {"text": "".join(text), "entities": entities}

with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column():
            output = gr.DataFrame(value=cur)
            page = gr.Number(minimum=0,maximum=len(pages)-1,label="page")
            page.change(show, page, outputs=output)
        text = gr.HighlightedText(label="preview")
        output.select(showIter,inputs=[], outputs=[text])
        
gr.close_all()
demo.launch()
```
