### ISSUE TITLE
Svelte nested API with Gradio error

### ISSUE THREAD

**Issue by natapol2547** [gradio-app/gradio#5044]
### Describe the bug

Hello everyone. I am very new to Svelte and web devloping itself. 

I am trying to make an api route in Svelte that would make a request to a gradio API that I hosted privately on Huggingface Space. I seems to have an error requesting the API specifically in Javascript.
Thank you for your time!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

1. Create a Gradio app on Huggingface and set it to private:
Gradio app.py
```py
import gradio as gr

def greet(name):
    return "Hello " + name + "!!"

iface = gr.Interface(fn=greet, inputs="text", outputs="text")
iface.launch()
```

2. Create a Svelte project
```
npm create svelte@latest my-app
cd my-app
npm install
npm run dev
```

3. Create an server route: route/api/test/+server.ts
```js
import type { RequestHandler } from './$types';
import { client } from "@gradio/client";

export const POST: RequestHandler = async () => {

    const app = await client("https://natapol-test.hf.space/", {hf_token:HF_READ_KEY});
    const result = await app.predict("/predict", [        
        "Howdy!", // string  in 'name' Textbox component
    ]);

    console.log("finished");

    return new Response();
};
```

4. Try POSTing to the local api route

Note: I have tried making the Huggingface Space public and it works perfectly.

### Logs

```shell
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 404
    at ClientRequest.<anonymous> (file:///C:/Users/Me/Desktop/test-v3/node_modules/@gradio/client/dist/wrapper-6f348d45.js:2813:7)        
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:701:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:542:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (file:///C:/Users/Me/Desktop/test-v3/node_modules/@gradio/client/dist/wrapper-6f348d45.js:2895:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.16.1
```
```


### System Info

```shell
NodeJS: 18.17.0
Svelte: 4
Gradio: Latest version on Huggingface
```

### Severity

Blocking usage of gradio

**Comment by aecorredor** [comment]
I seem to be hitting a similar issue when trying to consume the `meta/MusicGen` public space. I also tried duplicating it into my private one and passing my own auth token, but I get the same error:

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

I'm trying to hit the API where I only need to pass a text prompt.

**Comment by aecorredor** [comment]
Here's the code btw:

```ts
import { client } from "@gradio/client";


async function run() {

	const app = await client("https://facebook-musicgen--bfxcs.hf.space/");
	const result = await app.predict(2, [		
				"Howdy!", // string  in 'parameter_15' Dataset component
	]);

	console.log(result?.data);
}

run();
```

**Comment by aecorredor** [comment]
I added a try/catch and this is what I get:

```
{
  type: 'status',
  stage: 'error',
  message: "Cannot read properties of undefined (reading 'map')",
  endpoint: '/predict',
  fn_index: 3,
  queue: false,
  time: 2023-08-04T22:09:56.346Z
}
```

**Comment by aecorredor** [comment]
I did some debugging and it seems to come from `transform_output`.

**Comment by aecorredor** [comment]
It looks like the issue is inside `submit`. 

`handle_blob` seems to be gracefully handling the call to `post_data`, which seems to be returning a status `500` in the first `.then` for me. It then calls `transform_output` by passing in `output.data`, which in my case is `undefined`. 

The first thing `transform_output` does is try to map over `data`, and that's where I get the unhandled error.

**Comment by L3-N0X** [comment]
Having the same issue with `Node.js 20.6.0` and `@gradio/client@0.4.2` with [this space](https://osanseviero-mistral-super-fast.hf.space/) and the `/chat` endpoint, also with `.predict`

**Comment by j2l** [comment]
I also have the same issue (Ubuntu 22.04, node v18,  @gradio/client 0.9.0 .

Calling the same public space, the python gradio client works, but the JS client throws:
```
{
  type: 'status',
  endpoint: '/predict',
  fn_index: 0,
  time: 2023-12-13T16:13:44.572Z,
  queue: true,
  message: null,
  stage: 'error',
  code: undefined,
  success: false
}
```

**Comment by manngup** [comment]
Was this fixed? I am encountering the issues mentioned in below:

> I seem to be hitting a similar issue when trying to consume the `meta/MusicGen` public space. I also tried duplicating it into my private one and passing my own auth token, but I get the same error:
> 
> ```
> node:internal/process/promises:288
>             triggerUncaughtException(err, true /* fromPromise */);
>             ^
> 
> [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
>   code: 'ERR_UNHANDLED_REJECTION'
> }
> ```
> 
> I'm trying to hit the API where I only need to pass a text prompt.

I am also trying to make the below code work:

> Here's the code btw:
> 
> import { client } from "@gradio/client";
> 
> 
> async function run() {
> 
> 	const app = await client("https://facebook-musicgen--bfxcs.hf.space/");
> 	const result = await app.predict(2, [		
> 				"Howdy!", // string  in 'parameter_15' Dataset component
> 	]);
> 
> 	console.log(result?.data);
> }
> 
> run();

However I catch the same error described below:

> I added a try/catch and this is what I get:
> 
> ```
> {
>   type: 'status',
>   stage: 'error',
>   message: "Cannot read properties of undefined (reading 'map')",
>   endpoint: '/predict',
>   fn_index: 3,
>   queue: false,
>   time: 2023-08-04T22:09:56.346Z
> }
> ```
> 
> The docs in my space definitely show there is an `fn_index` function at `3`.

**Is it not possible to use the gradio API for the public Music Gen space?**
