### ISSUE TITLE
Gradio With Threading

### ISSUE THREAD

**Issue by Kimyobu** [gradio-app/gradio#5053]
To Fix Runtimeerror: there is no current event loop in thread
When Launch Gradio WebUI Inside Thread
```python
import gradio as gr

import threading
import subprocess
import sys
import os

subprocess.call([sys.executable, f'{os.path.dirname(__file__)}/installer.py'])

colors = gr.themes.colors
theme = gr.themes.Base(primary_hue=colors.orange,secondary_hue=colors.rose,neutral_hue=colors.slate)

darkmode = """function () {
  gradioURL = window.location.href
  if (!gradioURL.endsWith('?__theme=dark')) {
    window.location.replace(gradioURL + '?__theme=dark');
  } else window.location.replace('/')
}"""

def mode():
    return

with gr.Blocks(theme=theme) as ui:
    dark = gr.Button('Switch Theme Mode')
    with gr.Tab(label='txt2img'):
        with gr.Row():
            gr.TextArea(label='Positive Prompt',placeholder='Write Your prompt here...')
        with gr.Row():
            gr.TextArea(label='Negative Prompt',placeholder='Write Your prompt here...')
        with gr.Box(label='Empty Latent'):
            gr.Slider(minimum=1,maximum=4000,value=512,step=16,label='Width',interactive=True)
            gr.Slider(minimum=1,maximum=4000,value=512,step=16,label='Height',interactive=True)
        with gr.Row():
            gr.Button('Generate', variant='primary')


    dark.click(None,_js=darkmode)

def l():
    print('Starting Gradio WebUI')
    return ui.launch(share=True,debug=True,show_error=True,server_port=7680)

threading.Thread(target=l,daemon=True).start()
```
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\Drakn\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Drakn\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Project\ComfyUI\custom_nodes\ComfyUI-Gradio\__init__.py", line 41, in l
    return ui.launch(share=True,debug=True,show_error=True,server_port=7680)
  File "C:\Users\Drakn\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\blocks.py", line 1840, in launch
    ) = networking.start_server(
  File "C:\Users\Drakn\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\networking.py", line 131, in start_server
    app = App.create_app(blocks, app_kwargs=app_kwargs)
  File "C:\Users\Drakn\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\routes.py", line 173, in create_app
    app = App(**app_kwargs)
  File "C:\Users\Drakn\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\routes.py", line 114, in __init__
    self.lock = asyncio.Lock()
  File "C:\Users\Drakn\AppData\Local\Programs\Python\Python38\lib\asyncio\locks.py", line 164, in __init__
    self._loop = events.get_event_loop()
  File "C:\Users\Drakn\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-4'.
```

I have to Fix it by following this
```python
def __init__(self, **kwargs):
        self.tokens = {}
        self.auth = None
        self.blocks: gradio.Blocks | None = None
        self.state_holder = {}
        self.iterators = defaultdict(dict)
        self.iterators_to_reset = defaultdict(set)
        # self.lock = asyncio.Lock() <--- I Just Remove This Line and It Work With Fine
        self.queue_token = secrets.token_urlsafe(32)
        self.startup_events_triggered = False
        self.uploaded_file_dir = os.environ.get("GRADIO_TEMP_DIR") or str(
            Path(tempfile.gettempdir()) / "gradio"
        )
        # Allow user to manually set `docs_url` and `redoc_url`
        # when instantiating an App; when they're not set, disable docs and redoc.
        kwargs.setdefault("docs_url", None)
        kwargs.setdefault("redoc_url", None)
        super().__init__(**kwargs)
```

Thankyou Gradio Team, Hope To Fix This Problem

**Comment by abidlabs** [comment]
Hi @Kimyobu I can't reproduce this issue. I was able to run Gradio from within a thread locally as well as on Colab. You can see my notebook here: https://colab.research.google.com/drive/1sTffhxiPbZ-Qqoo6d3NQvQGvh0A9YZ1h?usp=sharing

**Comment by abidlabs** [comment]
Will close for now, we can reopen if you can provide us a repro. Thanks!
