### ISSUE TITLE
Comprehensive tutorial on identifying and resolving share=True issues

### ISSUE THREAD

**Issue by ysig** [gradio-app/gradio#5083]
Hi,

I use gradio (`3.39.0`) in my university server that is behind a proxy and I have been failing producing a shareable link.
Older versions of gradio like 3.9 worked out of the box on my server (they produce a shareable gradio link), while newer ones don't work at all. There is certainly a certain implementation thing that [changed in the development of gradio](https://github.com/gradio-app/gradio/issues/2918) that really has damaged or altered this function, but without it being tracked somewhere reachable along many times I've searched about this issue.

The problem is that:
a) there is no debugging message that can help identify the root cause of not creating a shareable link
b) there is no guide of how to debug this and setup the system properly so it works.

Most pull requests around this issue either remain unanswered or respond to a very beginner audience of gradio or python that forgot to set `share=True`...

So what is needed is a guide for a basic ubuntu linux system will tell you that:
a) if you set up x,y,z correctly then you will have it working
b) you can identify why it isn't working by setting an environment variable (and what the error messages mean in case they are obscure javascript error messages).

Thank you,
ysig

**Comment by abidlabs** [comment]
Hi @ysig thanks for creating this issue. I do agree that its frustrating when the share link does not get created. It seems like often times an antivirus software is blocking the share link from being created. What do you see printed to the console when the share link is not created?

**Comment by ysig** [comment]
So when `share=False` I get an error:

```
Running on local URL:  http://127.0.0.1:7861
Traceback (most recent call last):
  File "/home/isig/gaia-v2/<script-name>.py", line 42, in <module>
    demo.launch()
  File "/home/isig/miniconda3/envs/diffusers/lib/python3.10/site-packages/gradio/blocks.py", line 1913, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.
```

When `share=True` I get:
```Running on local URL:  http://127.0.0.1:7861```

Which is wrong behavior. It's probably a proxy error but my proxy is properly set up in both `http_proxy` and `https_proxy` variables. And this validates my initial message - both the error messages must be improved and concrete instructions on how to set things up correctly (e.g. there may be a GRADIO_PROXY env variable or sth). Also it's weird that this problem comes somewhere after 3.9 and multiple users seem to have reported it.

**Comment by abidlabs** [comment]
I agree its worth documenting this better -- will relabel the issue. cc @aliabd if you have bandwidth

**Comment by ysig** [comment]
@abidlabs But still can you give some context about this, so I can debug it for now? I need to share a gradio with my advisor and I have to degrade to 3.9 which kills a lot of the features and I have re-design the whole thing. Maybe the reason is simple. Can you give the basics about setting up the proxy for gradio or how to hack the code so it doesn't silence the link creation error message? Try to think according to the fact that it was working at 3.9 and then it changed. The answer for what changed should be simple.

**Comment by ysig** [comment]
@abidlabs Now I get an even more weird error.

After my localhost connection is generated I receive a:

```
*** Failed to connect to ec2.gradio.app:22: [Errno 110] Connection timed out
Aborted (core dumped)
```
and the whole app breaks (I can't even run my localhost).

**Comment by ysig** [comment]
@abidlabs Any update on this?

**Comment by abidlabs** [comment]
We haven't had a chance to put this together just yet, but you may be interested in something related: we open-sourced the Gradio share server and added a mechanism to use your own share server with Gradio: https://github.com/huggingface/frp
