### ISSUE TITLE
gradio with langchain 

### ISSUE THREAD

**Issue by phamkhactu** [gradio-app/gradio#5090]
### Describe the bug

Gradio not working with langchain

If I comment the import langchain package, it work well, otherwise I get errors:
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/nest_asyncio.py", line 27, in run
    loop = asyncio.get_event_loop()
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-5'.
/home/tupk/anaconda3/envs/nlp/lib/python3.8/threading.py:934: RuntimeWarning: coroutine 'Server.serve' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio as gr
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
from langchain.llms import HuggingFacePipeline
from langchain.document_loaders import DirectoryLoader
from langchain.document_loaders import UnstructuredWordDocumentLoader
from torch import cuda, bfloat16
import transformers
from transformers import StoppingCriteria, StoppingCriteriaList
import torch
from langchain.chains import ConversationalRetrievalChain

def welcome(name):
    return f"Welcome to Gradio, {name}!", "haahha"

inputs = gr.Textbox(label="Input")

output0 = gr.Textbox(label="ouput")
output1 = gr.Textbox(label="ouput")

    
demo = gr.Interface(fn=welcome, inputs=inputs, outputs=[output0, output1])
demo.launch()

### Logs

```shell
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/nest_asyncio.py", line 27, in run
    loop = asyncio.get_event_loop()
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-5'.
/home/tupk/anaconda3/envs/nlp/lib/python3.8/threading.py:934: RuntimeWarning: coroutine 'Server.serve' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
```


### System Info

```shell
python: 3.8
gradio: 3.39.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @phamkhactu I can't reproduce this issue. Here's my Colab notebook, which works perfectly fine: https://colab.research.google.com/drive/1j0LQrMeA0vx94dayzpAF3Sw0XVnHggTW?usp=sharing

Is there something off about my repro?

**Comment by phamkhactu** [comment]
@abidlabs Yes, I've tried on it in Jupiter not exception, however Vs-Code It comes

**Comment by moejay** [comment]
It happened to me,  I cleaned my virtualenv, the problem went away.
Probably something with how stupid pip works and handles dependencies, even if it's not pip, I would still like to blame pip
