### ISSUE TITLE
Pin `aiofiles` version?

### ISSUE THREAD

**Issue by catboxanon** [gradio-app/gradio#5153]
### Describe the bug

**Edit**: This was fixed upstream pretty fast but I still am going to propose the question here.

This is moreso a question. A recent `aiofiles` update broke compatibility with Windows systems.

https://github.com/Tinche/aiofiles/pull/162
https://github.com/Tinche/aiofiles/issues/171
https://github.com/Tinche/aiofiles/pull/172

Currently the version Gradio specifies for this is pretty lenient which allowed this to seep thru. https://github.com/gradio-app/gradio/blob/667875b2441753e74d25bd9d3c8adedd8ede11cd/requirements.txt#L1

Should this be considered to be a more strict version pin to prevent any similar issues occurring in the future?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Create a fresh Python venv and install Gradio, and run any demo from https://www.gradio.app/demos. Instead a traceback will be returned with `AttributeError: module 'os' has no attribute 'statvfs'`.

### Logs

```shell
Traceback (most recent call last):
  File "H:\Projects\Programming\_new\gradiotest\main.py", line 1, in <module>
    import gradio as gr
  File "H:\Projects\Programming\_new\gradiotest\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "H:\Projects\Programming\_new\gradiotest\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "H:\Projects\Programming\_new\gradiotest\venv\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "H:\Projects\Programming\_new\gradiotest\venv\lib\site-packages\gradio\components\base.py", line 29, in <module>
    from gradio.blocks import Block, BlockContext
  File "H:\Projects\Programming\_new\gradiotest\venv\lib\site-packages\gradio\blocks.py", line 27, in <module>
    from gradio import (
  File "H:\Projects\Programming\_new\gradiotest\venv\lib\site-packages\gradio\networking.py", line 18, in <module>
    from gradio.routes import App
  File "H:\Projects\Programming\_new\gradiotest\venv\lib\site-packages\gradio\routes.py", line 44, in <module>
    import gradio.ranged_response as ranged_response
  File "H:\Projects\Programming\_new\gradiotest\venv\lib\site-packages\gradio\ranged_response.py", line 12, in <module>
    from aiofiles.os import stat as aio_stat
  File "H:\Projects\Programming\_new\gradiotest\venv\lib\site-packages\aiofiles\os.py", line 32, in <module>
    statvfs = wrap(os.statvfs)
AttributeError: module 'os' has no attribute 'statvfs'
```

### System Info

```shell
# (can't even run this as the same crash occurs; running on Windows 11)
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Not needed, as the broken version of `aiofiles` was yanked:

<img width="786" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/bf6d9167-e19a-48a1-8eaa-2505a3f09366">

We generally avoid pinning dependencies to anything more specific than a major as that can cause issues if `gradio` is installed alongside other packages.
