### ISSUE TITLE
Outdated documentation for **Using State** in the gradio.app webpage.

### ISSUE THREAD

**Issue by saratrajput** [gradio-app/gradio#525]
**Describe the bug**
Outdated documentation for **Using State** in the gradio.app webpage.

Upon following the tutorial on the gradio [webpage](https://gradio.app/getting_started/) for "Using State", you get the error:
```
Traceback (most recent call last):
  File "/home/sp/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/app.py", line 199, in predict
    prediction, durations = await run_in_threadpool(
  File "/home/sp/anaconda3/envs/py39/lib/python3.9/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/sp/anaconda3/envs/py39/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/sp/anaconda3/envs/py39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/sp/anaconda3/envs/py39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/sp/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/interface.py", line 530, in process
    predictions, durations = self.run_prediction(
  File "/home/sp/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/interface.py", line 487, in run_prediction
    prediction = predict_fn(*processed_input)
  File "<ipython-input-2-0293d5c29cac>", line 2, in chat
    history = gr.get_state() or []
  File "/home/sp/anaconda3/envs/py39/lib/python3.9/site-packages/gradio/app.py", line 321, in get_state
    raise DeprecationWarning(
DeprecationWarning: This function is deprecated. To create stateful demos, pass 'state'as both an input and output component. Please see the getting startedguide for more information.
```

But the getting_started guide on the webpage, whereas the documentation and tutorial on the [README](https://github.com/gradio-app/gradio#using-state) are up to date. So the error message should point the user to the readme instead if that is where you can find the most up-to-date information.

**To Reproduce**
1. Go to https://gradio.app/getting_started/
2. Scroll down to **Using State**
```
history = gr.get_state() or []
...
gr.set_state()
```

**Screenshots**
![image](https://user-images.githubusercontent.com/29677848/152254035-57e85cd1-8d07-4352-aa14-2999d9bf42c3.png)

**Device information (please complete the following information):**
 - OS: [e.g. Windows or iOS]
 - Gradio version [e.g. 2.5.1]  

**Additional context**

**Comment by abidlabs** [comment]
You're right @saratrajput thanks for bringing this to our attention. Will fix asap!

**Comment by abidlabs** [comment]
Updated now! Thanks again @saratrajput :)
