### ISSUE TITLE
`gr.Dataframe` crashes when using `markdown` with latex expression

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#5257]
### Describe the bug

An error occurs when using a latex expression in `markdown` of `gr.Dataframe`.

[internal discussion](https://huggingface.slack.com/archives/C02QZLG8GMN/p1692268569340879)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://huggingface.co/spaces/hysts-debug/dataframe-latex-markdown

```python
import gradio as gr
import pandas as pd

df = pd.DataFrame([{
    'title':
    'DORSal: Diffusion for Object-centric Representations of Scenes\n  $\\textit{et al.}$'
}])

with gr.Blocks() as demo:
    gr.Dataframe(value=df, datatype='markdown')
demo.queue().launch()
```

```
Traceback (most recent call last):
  File "/home/user/app/app.py", line 12, in <module>
    gr.Dataframe(value=df, datatype='markdown')
  File "/home/user/.local/lib/python3.10/site-packages/gradio/components/dataframe.py", line 136, in __init__
    IOComponent.__init__(
  File "/home/user/.local/lib/python3.10/site-packages/gradio/components/base.py", line 182, in __init__
    else self.postprocess(initial_value)
  File "/home/user/.local/lib/python3.10/site-packages/gradio/components/dataframe.py", line 237, in postprocess
    "data": Dataframe.__process_markdown(
  File "/home/user/.local/lib/python3.10/site-packages/gradio/components/dataframe.py", line 293, in __process_markdown
    data[i][j] = cls.markdown_parser.render(data[i][j])
  File "/home/user/.local/lib/python3.10/site-packages/markdown_it/main.py", line 267, in render
    return self.renderer.render(self.parse(src, env), self.options, env)
  File "/home/user/.local/lib/python3.10/site-packages/markdown_it/renderer.py", line 87, in render
    result += self.renderInline(token.children, options, env)
  File "/home/user/.local/lib/python3.10/site-packages/markdown_it/renderer.py", line 108, in renderInline
    result += self.rules[token.type](tokens, i, options, env)
  File "/home/user/.local/lib/python3.10/site-packages/mdit_py_plugins/dollarmath/index.py", line 70, in render_math_inline
    content = _renderer(str(tokens[idx].content).strip(), {"display_mode": False})
  File "/home/user/.local/lib/python3.10/site-packages/gradio/utils.py", line 899, in tex2svg
    fig.savefig(
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/figure.py", line 3378, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2342, in print_figure
    self.figure.draw(renderer)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/figure.py", line 3175, in draw
    mimage._draw_list_compositing_images(
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/text.py", line 752, in draw
    bbox, info, descent = self._get_layout(renderer)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/text.py", line 386, in _get_layout
    w, h, d = _get_text_metrics_with_cache(
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/text.py", line 97, in _get_text_metrics_with_cache
    return _get_text_metrics_with_cache_impl(
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/text.py", line 105, in _get_text_metrics_with_cache_impl
    return renderer_ref().get_text_width_height_descent(text, fontprop, ismath)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/backends/backend_svg.py", line 1317, in get_text_width_height_descent
    return self._text2path.get_text_width_height_descent(s, prop, ismath)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/textpath.py", line 60, in get_text_width_height_descent
    self.mathtext_parser.parse(s, 72, prop)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/mathtext.py", line 226, in parse
    return self._parse_cached(s, dpi, prop)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/mathtext.py", line 247, in _parse_cached
    box = self._parser.parse(s, fontset, fontsize, dpi)
  File "/home/user/.local/lib/python3.10/site-packages/matplotlib/_mathtext.py", line 1995, in parse
    raise ValueError("\n" + ParseException.explain(err, 0)) from None
ValueError: 
\textit{et al.}
^
ParseFatalException: Unknown symbol: \textit, found '\'  (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/app/app.py", line 11, in <module>
    with gr.Blocks() as demo:
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1526, in __exit__
    self.config = self.get_config_file()
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1493, in get_config_file
    props = block.get_config() if hasattr(block, "get_config") else {}
  File "/home/user/.local/lib/python3.10/site-packages/gradio/components/dataframe.py", line 157, in get_config
    "value": self.value,
AttributeError: 'Dataframe' object has no attribute 'value'
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 3.40.1
gradio_client version: 0.4.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
aiohttp: 3.8.4
altair: 5.0.1
fastapi: 0.101.0
ffmpy: 0.3.1
gradio-client: 0.4.0
httpx: 0.24.1
huggingface-hub: 0.16.4
importlib-resources: 6.0.1
jinja2: 3.1.2
markdown-it-py: 2.2.0
markupsafe: 2.1.3
matplotlib: 3.7.2
mdit-py-plugins: 0.3.3
numpy: 1.25.1
orjson: 3.9.4
packaging: 23.1
pandas: 2.0.3
pillow: 10.0.0
pydantic: 1.10.11
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.7.1
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.24.1
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
As a nice side effect of #5268, this is now fixed! LaTeX even renders:

<img width="772" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/b7450f0d-5920-4b61-a6df-c12c0241bf7b">
