### ISSUE TITLE
KeyError: 'type'

### ISSUE THREAD

**Issue by aliuweiwei** [gradio-app/gradio#5378]
### Describe the bug

Describe the bug
I don't know why this is happening
I did not obtain system information, which is mandatory

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Traceback (most recent call last):
  File "webui.py", line 261, in <module>
    load_model_button.click(reinit_model,
  File "/home/ubuntu/anaconda3/envs/langchain/lib/python3.8/site-packages/gradio/blocks.py", line 1200, in __exit__
    self.config = self.get_config_file()
  File "/home/ubuntu/anaconda3/envs/langchain/lib/python3.8/site-packages/gradio/blocks.py", line 1176, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
  File "/home/ubuntu/anaconda3/envs/langchain/lib/python3.8/site-packages/gradio_client/serializing.py", line 43, in input_api_info
    types = api_info.get("serialized_input", [api_info["info"]["type"]] * 2)  # type: ignore
KeyError: 'type'

### System Info

```shell
log from hugging face container build:
```

### Severity

Blocking usage of gradio

**Comment by aliuweiwei** [comment]
> Okay, after I changed the version to 3.36.1, the error message no longer appears
