### ISSUE TITLE
Can't import Gradio

### ISSUE THREAD

**Issue by codeghees** [gradio-app/gradio#54]
I installed gradio.
Can't import it

Any solution?

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Moughees\AppData\Local\Continuum\anaconda3\lib\site-packages\gradio\__init__.py", line 1, in <module>
    from gradio.interface import *  # This makes it possible to import `Interface` as `gradio.Interface`.
  File "C:\Users\Moughees\AppData\Local\Continuum\anaconda3\lib\site-packages\gradio\interface.py", line 11, in <module>
    from gradio import networking, strings, utils
  File "C:\Users\Moughees\AppData\Local\Continuum\anaconda3\lib\site-packages\gradio\networking.py", line 14, in <module>
    from gradio.tunneling import create_tunnel
  File "C:\Users\Moughees\AppData\Local\Continuum\anaconda3\lib\site-packages\gradio\tunneling.py", line 12, in <module>
    import paramiko
  File "C:\Users\Moughees\AppData\Local\Continuum\anaconda3\lib\site-packages\paramiko\__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "C:\Users\Moughees\AppData\Local\Continuum\anaconda3\lib\site-packages\paramiko\transport.py", line 129, in <module>
  File "C:\Users\Moughees\AppData\Local\Continuum\anaconda3\lib\site-packages\paramiko\transport.py", line 190, in Transport
    if KexCurve25519.is_available():
  File "C:\Users\Moughees\AppData\Local\Continuum\anaconda3\lib\site-packages\paramiko\kex_curve25519.py", line 30, in is_available
    X25519PrivateKey.generate()
  File "C:\Users\Moughees\AppData\Local\Continuum\anaconda3\lib\site-packages\cryptography\hazmat\primitives\asymmetric\x25519.py", line 38, in generate
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Users\Moughees\AppData\Local\Continuum\anaconda3\lib\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Users\Moughees\AppData\Local\Continuum\anaconda3\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 74, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "C:\Users\Moughees\AppData\Local\Continuum\anaconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 15, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by dawoodkhan82** [comment]
It looks like this is a similar problem linked here (https://stackoverflow.com/questions/48003901/paramiko-importerror-dll-load-failed-the-operating-system-cannot-run-1). Can you try the solutions here and let me know if any of them worked.
