### ISSUE TITLE
Gradio Client Is Unable to Connect to Locally Served HTTPS API

### ISSUE THREAD

**Issue by pourmand1376** [gradio-app/gradio#5497]
### Describe the bug

When trying to connect to a locally served HTTPS API from a Gradio client, an SSL certification verification error occurs that prevents the client from accessing the API.

> Note that the Gradio web UI works very good in this case but Gradio API client in unusable. 

Specifically:

A simple Gradio app is created that serves an HTTPS API on localhost.
A self-signed SSL certificate is added to enable HTTPS on localhost.
The Gradio client tries to connect to this local HTTPS API, but gets an SSLCertVerificationError.
This is because the Gradio client does not trust the locally generated self-signed certificate used by the server. During the SSL handshake, certificate verification fails with the error:

"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate"

As a result, the SSL connection between the client and server cannot be established. The client is unable to send any requests to the local HTTPS API.

I do not know how I can fix this. I have tried solutions from [here](https://stackoverflow.com/questions/15445981/how-do-i-disable-the-security-certificate-check-in-python-requests) but none of them worked. 

Here is also the code I am using to connect to gradio local endpoint:

```python
from gradio_client import Client
client =  Client("https://10.2.20.20:8006/")
 result = client.predict(input_parameters,api_name="/run"
  )
 print(result)
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

- Generate a simple app which uses gradio. 
- Add Local Signed Certificate to it via [this](https://github.com/gradio-app/gradio/issues/563) or [this](https://discuss.huggingface.co/t/how-to-run-gradio-with-0-0-0-0-and-https/38003). 
- There is no way to connect to that https endpoint. 

### Logs
Loaded as API: https://10.2.20.20:8006/ ✔
```shell
SSLCertVerificationError                  Traceback (most recent call last)
File ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/urllib3/connectionpool.py:714, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    713 # Make the request on the httplib connection object.
--> 714 httplib_response = self._make_request(
    715     conn,
    716     method,
    717     url,
    718     timeout=timeout_obj,
    719     body=body,
    720     headers=headers,
    721     chunked=chunked,
    722 )
    724 # If we're going to release the connection in ``finally:``, then
    725 # the response doesn't need to know about the connection. Otherwise
    726 # it will also try to release it and we'll have a double-release
    727 # mess.

File ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/urllib3/connectionpool.py:403, in HTTPConnectionPool._make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    402 try:
--> 403     self._validate_conn(conn)
    404 except (SocketTimeout, BaseSSLError) as e:
    405     # Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.

File ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/urllib3/connectionpool.py:1053, in HTTPSConnectionPool._validate_conn(self, conn)
   1052 if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
-> 1053     conn.connect()
   1055 if not conn.is_verified:

File ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/urllib3/connection.py:419, in HTTPSConnection.connect(self)
    417     context.load_default_certs()
--> 419 self.sock = ssl_wrap_socket(
    420     sock=conn,
    421     keyfile=self.key_file,
    422     certfile=self.cert_file,
    423     key_password=self.key_password,
    424     ca_certs=self.ca_certs,
    425     ca_cert_dir=self.ca_cert_dir,
    426     ca_cert_data=self.ca_cert_data,
    427     server_hostname=server_hostname,
    428     ssl_context=context,
    429     tls_in_tls=tls_in_tls,
    430 )
    432 # If we're using all defaults and the connection
    433 # is TLSv1 or TLSv1.1 we throw a DeprecationWarning
    434 # for the host.

File ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/urllib3/util/ssl_.py:453, in ssl_wrap_socket(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir, key_password, ca_cert_data, tls_in_tls)
    452 else:
--> 453     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
    454 return ssl_sock

File ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/urllib3/util/ssl_.py:495, in _ssl_wrap_socket_impl(sock, ssl_context, tls_in_tls, server_hostname)
    494 else:
--> 495     return ssl_context.wrap_socket(sock)

File ~/.pyenv/versions/3.10.12/lib/python3.10/ssl.py:513, in SSLContext.wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    507 def wrap_socket(self, sock, server_side=False,
    508                 do_handshake_on_connect=True,
    509                 suppress_ragged_eofs=True,
    510                 server_hostname=None, session=None):
    511     # SSLSocket class handles server_hostname encoding before it calls
    512     # ctx._wrap_socket()
--> 513     return self.sslsocket_class._create(
    514         sock=sock,
    515         server_side=server_side,
    516         do_handshake_on_connect=do_handshake_on_connect,
    517         suppress_ragged_eofs=suppress_ragged_eofs,
    518         server_hostname=server_hostname,
    519         context=self,
    520         session=session
    521     )

File ~/.pyenv/versions/3.10.12/lib/python3.10/ssl.py:1071, in SSLSocket._create(cls, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, context, session)
   1070             raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
-> 1071         self.do_handshake()
   1072 except (OSError, ValueError):

File ~/.pyenv/versions/3.10.12/lib/python3.10/ssl.py:1342, in SSLSocket.do_handshake(self, block)
   1341         self.settimeout(None)
-> 1342     self._sslobj.do_handshake()
   1343 finally:

SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
File ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/adapters.py:440, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    439 if not chunked:
--> 440     resp = conn.urlopen(
    441         method=request.method,
    442         url=url,
    443         body=request.body,
    444         headers=request.headers,
    445         redirect=False,
    446         assert_same_host=False,
    447         preload_content=False,
    448         decode_content=False,
    449         retries=self.max_retries,
    450         timeout=timeout
    451     )
    453 # Send the request.
    454 else:

File ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/urllib3/connectionpool.py:798, in HTTPConnectionPool.urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    796     e = ProtocolError("Connection aborted.", e)
--> 798 retries = retries.increment(
    799     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    800 )
    801 retries.sleep()

File ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/urllib3/util/retry.py:592, in Retry.increment(self, method, url, response, error, _pool, _stacktrace)
    591 if new_retry.is_exhausted():
--> 592     raise MaxRetryError(_pool, url, error or ResponseError(cause))
    594 log.debug("Incremented Retry for (url='%s'): %r", url, new_retry)

MaxRetryError: HTTPSConnectionPool(host='10.2.20.20', port=8006): Max retries exceeded with url: /config (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
Cell In[11], line 2
      1 from gradio_client import Client
----> 2 client =  Client("https://10.2.17.14:8006/")
      3 for turn, value, speaker in diarization.itertracks(yield_label=True):
      4     clipped  = song[turn.start*1000: turn.end*1000]

File ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gradio_client/client.py:128, in Client.__init__(self, src, hf_token, max_workers, serialize, output_dir, verbose)
    126 self.upload_url = urllib.parse.urljoin(self.src, utils.UPLOAD_URL)
    127 self.reset_url = urllib.parse.urljoin(self.src, utils.RESET_URL)
--> 128 self.config = self._get_config()
    129 self.session_hash = str(uuid.uuid4())
    131 self.endpoints = [
    132     Endpoint(self, fn_index, dependency)
    133     for fn_index, dependency in enumerate(self.config["dependencies"])
    134 ]

File ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gradio_client/client.py:591, in Client._get_config(self)
    590 def _get_config(self) -> dict:
--> 591     r = requests.get(
    592         urllib.parse.urljoin(self.src, utils.CONFIG_URL), headers=self.headers
    593     )
    594     if r.ok:
    595         return r.json()

File ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/api.py:75, in get(url, params, **kwargs)
     64 def get(url, params=None, **kwargs):
     65     r"""Sends a GET request.
     66 
     67     :param url: URL for the new :class:`Request` object.
   (...)
     72     :rtype: requests.Response
     73     """
---> 75     return request('get', url, params=params, **kwargs)

File ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/api.py:61, in request(method, url, **kwargs)
     57 # By using the 'with' statement we are sure the session is closed, thus we
     58 # avoid leaving sockets open which can trigger a ResourceWarning in some
     59 # cases, and look like a memory leak in others.
     60 with sessions.Session() as session:
---> 61     return session.request(method=method, url=url, **kwargs)

File ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/sessions.py:529, in Session.request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    524 send_kwargs = {
    525     'timeout': timeout,
    526     'allow_redirects': allow_redirects,
    527 }
    528 send_kwargs.update(settings)
--> 529 resp = self.send(prep, **send_kwargs)
    531 return resp

File ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/sessions.py:645, in Session.send(self, request, **kwargs)
    642 start = preferred_clock()
    644 # Send the request
--> 645 r = adapter.send(request, **kwargs)
    647 # Total elapsed time of the request (approximately)
    648 elapsed = preferred_clock() - start

File ~/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/adapters.py:517, in HTTPAdapter.send(self, request, stream, timeout, verify, cert, proxies)
    513         raise ProxyError(e, request=request)
    515     if isinstance(e.reason, _SSLError):
    516         # This branch is for urllib3 v1.22 and later.
--> 517         raise SSLError(e, request=request)
    519     raise ConnectionError(e, request=request)
    521 except ClosedPoolError as e:

SSLError: HTTPSConnectionPool(host='10.2.20.20', port=8006): Max retries exceeded with url: /config (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1007)')))
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 3.40.1
gradio_client version: 0.5.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
aiohttp: 3.8.5
altair: 5.0.1
fastapi: 0.103.0
ffmpy: 0.3.1
gradio-client: 0.5.0
httpx: 0.24.1
huggingface-hub: 0.16.4
importlib-resources: 6.0.1
jinja2: 3.1.2
markdown-it-py: 2.2.0
markupsafe: 2.1.3
matplotlib: 3.7.2
mdit-py-plugins: 0.3.3
numpy: 1.24.4
orjson: 3.9.5
packaging: 23.1
pandas: 2.0.3
pillow: 10.0.0
pydantic: 2.3.0
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.27.0
semantic-version: 2.10.0
typing-extensions: 4.7.1
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.24.1
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.27.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by pourmand1376** [comment]
I should also mention that there is no problem when using this thing in browser. The problem only occurs in `gradio_client` and there is no way to skip this.

**Comment by 2catycm** [comment]
Same problem occurs to me too. 

```bash
>>> client = Client(f'{host}:{port}', verbose=True)
Loaded as API: http://127.0.0.1:12746/ ✔
Traceback (most recent call last):
  File "D:\python_env\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "D:\python_env\lib\site-packages\httpcore\_backends\sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
  File "D:\python_env\lib\socket.py", line 845, in create_connection
    raise err
  File "D:\python_env\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python_env\lib\site-packages\httpx\_transports\default.py", line 66, in map_httpcore_exceptions    
    yield
  File "D:\python_env\lib\site-packages\httpx\_transports\default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\python_env\lib\site-packages\httpcore\_sync\connection_pool.py", line 268, in handle_request       
    raise exc
  File "D:\python_env\lib\site-packages\httpcore\_sync\connection_pool.py", line 251, in handle_request       
    response = connection.handle_request(request)
  File "D:\python_env\lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "D:\python_env\lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "D:\python_env\lib\site-packages\httpcore\_sync\connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "D:\python_env\lib\site-packages\httpcore\_backends\sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "D:\python_env\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\python_env\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\python_env\lib\site-packages\gradio_client\client.py", line 133, in __init__
    self.config = self._get_config()
  File "D:\python_env\lib\site-packages\gradio_client\client.py", line 720, in _get_config
    r = httpx.get(
  File "D:\python_env\lib\site-packages\httpx\_api.py", line 189, in get
    return request(
  File "D:\python_env\lib\site-packages\httpx\_api.py", line 100, in request
    return client.request(
  File "D:\python_env\lib\site-packages\httpx\_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\python_env\lib\site-packages\httpx\_client.py", line 901, in send
    response = self._send_handling_auth(
  File "D:\python_env\lib\site-packages\httpx\_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "D:\python_env\lib\site-packages\httpx\_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "D:\python_env\lib\site-packages\httpx\_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "D:\python_env\lib\site-packages\httpx\_transports\default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "D:\python_env\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\python_env\lib\site-packages\httpx\_transports\default.py", line 83, in map_httpcore_exceptions    
    raise mapped_exc(message) from exc
httpx.ConnectError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
```

**Comment by 2catycm** [comment]
Should be a basic and important function
