### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'Textbox' and 'int'

### ISSUE THREAD

**Issue by Rida994** [gradio-app/gradio#5576]
### Describe the bug

Hello.. I am trying to build an interface and have some loose ends which I am unable to identify. My interface has 2 radio buttons: Custom Radio Regions and Predefined Radio regions. When user selects custom option, I want a slider to appear whose value decides the number of appending textboxes for user input. When user selects predefined radio regions, a drop down menu should appear which some options. But I'm getting errors doing that.

I want the slider and appended textboxes to disappear when user switches to 'predefined' from 'custom' and vice versa. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio as gr

max_textboxes = 10

def calculate_aci(audio_folder1, audio_folder2, region_type):
    blah = 2
    return blah
def variable_outputs(k):
    print(k)
    k = int(k)
    return [gr.Textbox.update(visible=True)]*k + [gr.Textbox.update(visible=False)]*(max_textboxes-k)

with gr.Blocks() as demo:
    # Create Gradio blocks for inputs
    with gr.Column():
        audio_folder1 = gr.inputs.Textbox(label="Define the path for first data set")
        audio_folder2 = gr.inputs.Textbox(label="Define the path for second data set")

    region_type = gr.inputs.Radio(["Custom Audio Regions", "Predefined Audio Regions"], label="Select Region Type")
    num_textboxes = gr.Slider(minimum=1, maximum=max_textboxes, value=1, step=1,
                                      label="Select the number of acoustic regions", visible=False)
    drop = gr.Dropdown(
        ["cat", "dog", "bird"], label="Animal", info="Will add more animals later!", visible=False
    )
    textboxes = []
    for i in range(max_textboxes):
        t = gr.Textbox(f"Textbox {i}", visible=False)
        textboxes.append(t)
    def toggle_slider(region_type):
        if region_type == "Custom Audio Regions":
            print('hello')
            return num_textboxes.update(visible=True), drop.update(visible=False)
        elif region_type == "Predefined Audio Regions":
            return num_textboxes.update(value=0, visible=False), drop.update(visible=True)

    with gr.Column():
        output = gr.outputs.Textbox(label='blah blah')

    num_textboxes.change(variable_outputs, num_textboxes, *textboxes)
    region_type.change(toggle_slider, region_type, [num_textboxes, drop])

    submit_btn = gr.Button("Submit")
    submit_btn.click(calculate_aci, [audio_folder1, audio_folder2, region_type],
                         output)

if __name__ == "__main__":
    demo.queue()
    demo.launch()

### Logs

```shell
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<Queue.start_processing() done, defined at /Users/xyz/test1/lib/python3.9/site-packages/gradio/queueing.py:126> exception=TypeError("unsupported operand type(s) for -: 'Textbox' and 'int'")>
Traceback (most recent call last):
  File "/Users/xyz/test1/lib/python3.9/site-packages/gradio/queueing.py", line 137, in start_processing
    events, batch = self.get_events_in_batch()
  File "/Users/xyz/test1/lib/python3.9/site-packages/gradio/queueing.py", line 120, in get_events_in_batch
    ][: batch_size - 1]
TypeError: unsupported operand type(s) for -: 'Textbox' and 'int'
```

### System Info

```shell
gradio Version: 3.41.2
```

### Severity

Blocking usage of gradio

**Comment by Rida994** [comment]
Solved by replacing 
num_textboxes.change(variable_outputs, num_textboxes, *textboxes)
with
num_textboxes.change(variable_outputs, num_textboxes, textboxes)
