### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(url)?

### ISSUE THREAD

**Issue by engperini** [gradio-app/gradio#5579]
### Describe the bug

Error when running Raspberry Pi OS 64b. I am using a virtual environment.
First, I was testing coding remote with VS Code and ssh at Raspberry Pi and everything was ok.
But now, I run direct from cli in Raspberry Pi and this occurred 

`(env) pi@raspberrypi:~/TalkAssistGPT/ChatPDF $ python3 /home/pi/TalkAssistGPT/ChatPDF/app-test.py
`
I've prepared a test to reproduce:

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

`import gradio as gr

from AppChatBot import main

title = 'TEST'

with gr.Blocks(css="""#chatbot { font-size: 14px; min-height: 1200; }""",theme=gr.themes.Soft()) as demo:
    gr.Markdown(f'<center><h3>{title}</h3></center>')
    
    btn = gr.Button(value='Submit')
    btn.style(full_width=True)
        
    btn.click(   
        main
        

    )
demo.launch()
`

### Logs

```shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/pi/env/lib/python3.9/site-packages/gradio/routes.py", line 508, in predict
    output = await route_utils.call_process_api(
  File "/home/pi/env/lib/python3.9/site-packages/gradio/route_utils.py", line 218, in call_process_api
    with utils.MatplotlibBackendMananger():
  File "/home/pi/env/lib/python3.9/site-packages/gradio/utils.py", line 817, in __enter__
    self._original_backend = matplotlib.get_backend()
  File "/home/pi/env/lib/python3.9/site-packages/matplotlib/__init__.py", line 1275, in get_backend
    return rcParams['backend']
  File "/home/pi/env/lib/python3.9/site-packages/matplotlib/__init__.py", line 760, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "/home/pi/env/lib/python3.9/site-packages/matplotlib/pyplot.py", line 327, in switch_backend
    switch_backend(candidate)
  File "/home/pi/env/lib/python3.9/site-packages/matplotlib/pyplot.py", line 342, in switch_backend
    module = importlib.import_module(cbook._backend_module_name(newbackend))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/env/lib/python3.9/site-packages/matplotlib/backends/backend_gtk4agg.py", line 4, in <module>
    from . import backend_agg, backend_gtk4
  File "/home/pi/env/lib/python3.9/site-packages/matplotlib/backends/backend_gtk4.py", line 12, in <module>
    import gi
  File "/home/pi/env/lib/python3.9/site-packages/gi/__init__.py", line 39
    		print url
    		      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(url)?
```

### System Info

```shell
(env) pi@raspberrypi:~/TalkAssistGPT/ChatPDF $ gradio environment
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 3.44.3
gradio_client version: 0.5.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.0.1
fastapi: 0.99.1
ffmpy: 0.3.1
gradio-client==0.5.0 is not installed.
httpx: 0.24.1
huggingface-hub: 0.17.1
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.24.3
orjson: 3.9.7
packaging: 23.1
pandas: 2.0.3
pillow: 9.5.0
pydantic: 1.10.12
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.5.0
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.9.0
httpx: 0.24.1
huggingface-hub: 0.17.1
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.5.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by engperini** [comment]
pip uninstall gi pip3 install pgi

worked for me.
