### ISSUE TITLE
Stuck with `HighlightedText` when using `combine_adjacent` without a `value`

### ISSUE THREAD

**Issue by volltin** [gradio-app/gradio#5584]
### Describe the bug

There is a bug in the `gr.HighlightedText` component when using the `combine_adjacent=True` parameter without providing a `value`. When these parameters are used, the application becomes stuck on "Loading...".

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Stuck on "Loading"

```python
import gradio as gr

with gr.Blocks() as demo:
    # stuck on "Loading"
    ht = gr.HighlightedText(
        combine_adjacent=True,
    )

demo.launch()
```

While other cases work well:

```python
import gradio as gr

with gr.Blocks() as demo:
    # Case 1: None, OK
    ht1 = gr.HighlightedText(
    )
    # Case 2: Empty string, OK
    ht2 = gr.HighlightedText(
        value="",
    )
    # Case 3: Empty string and combine_adjacent, OK
    ht3 = gr.HighlightedText(
        value="",
        combine_adjacent=True,
    )

demo.launch()
```

### Logs

```shell
No logs from python.

Logs from the browser console:


Uncaught (in promise) TypeError: s is not iterable
    at C (utils.ts:53:27)
    at Bl.e.$$.update (InteractiveHighlightedText.svelte:37:11)
    at kt (Component.js:132:5)
    at new Hl (InteractiveHighlightedText.svelte:37:40)
    at Fc (dom.js:1197:9)
    at Ql (Render.svelte:72:37)
    at kt (Component.js:136:34)
    at new Gt (Render.svelte:63:25)
    at Pt (Render.svelte:83:9)
    at Tt (Render.svelte:83:9)
```
```


### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 3.44.3
gradio_client version: 0.5.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.1
fastapi: 0.103.1
ffmpy: 0.3.1
gradio-client==0.5.0 is not installed.
httpx: 0.25.0
huggingface-hub: 0.17.1
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.25.2
orjson: 3.9.7
packaging: 23.1
pandas: 2.1.0
pillow: 10.0.1
pydantic: 2.3.0
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.8.0
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.9.1
httpx: 0.25.0
huggingface-hub: 0.17.1
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by volltin** [comment]
I did some investigation and found that the issue may be caused by the following code in `merge_elements` function from the file [js/highlightedtext/utils.ts](https://github.com/gradio-app/gradio/blob/52f7831751b432411e109bd41add4ab286023a8e/js/highlightedtext/utils.ts#L53). Specifically, the following code does not handle the case when `value` is `undefined`:

```javascript
export function merge_elements(
	value: HighlightValueType[],
	mergeMode: "empty" | "equal"
): HighlightValueType[] { ... }
```

As a result, the for-loop can cause the application to become stuck on loading. Handling the `undefined` case for `value` should resolve this issue.

**Comment by pngwn** [comment]
cc @hannahblair
