### ISSUE TITLE
The docs page hydration on navigation is broken

### ISSUE THREAD

**Issue by whitphx** [gradio-app/gradio#5844]
### Describe the bug

When moving around the docs pages using the sidebar menu, navigation sometimes fails as the attached video (notice from ~8s), failing to update some part of the page.

https://github.com/gradio-app/gradio/assets/3135397/e14535d1-c67b-4094-8243-1860e6ac41ae

As a result, after several clicks on the side menu links, the page would end up with the following state where each part of the page shows different content.
![CleanShot 2023-10-09 at 21 27 22@2x](https://github.com/gradio-app/gradio/assets/3135397/396c1a84-fb31-4826-9ae1-70f666ccc6e3)

When this problem occurs, errors like below appears on the dev console.
Some errors seem not related but I just dumped a bunch of them here anyway:
```
checkbox:1 Access to fetch at 'https://gradio-titanic-survival.hf.space/config' from origin 'https://www.gradio.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
start.758e0475.js:1 
 GET https://gradio-titanic-survival.hf.space/config net::ERR_FAILED 500 (Internal Server Error)
index.js:369 TypeError: Failed to fetch
    at window.fetch (start.758e0475.js:1:1536)
    at Pr (index.js:1010:26)
    at index.js:366:11
checkbox:1 Access to fetch at 'https://gradio-titanic-survival.hf.space/config' from origin 'https://www.gradio.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
start.758e0475.js:1 
 GET https://gradio-titanic-survival.hf.space/config net::ERR_FAILED 500 (Internal Server Error)
index.js:354 TypeError: Failed to fetch
    at window.fetch (start.758e0475.js:1:1536)
    at Pr (index.js:1010:26)
    at F (index.js:350:15)
    at Wt (index.js:1073:7)
index.5cabc326.js:1 Uncaught (in promise) DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Go to https://www.gradio.app/docs/ and move around the sub pages like the attached video.

### System Info

```shell
MacOS Sonoma 14.0
Google Chrome Version 117.0.5938.149 (Official Build) (arm64)
The HEAD commit was b83064da0005ca055fc15ee478cf064bf91702a4 when I tested it
```

### Severity

I can work around it

**Comment by whitphx** [comment]
Duplicated: #4922
