### ISSUE TITLE
warn against uvloop

### ISSUE THREAD

**Issue by louwjac** [gradio-app/gradio#5941]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I had problems running a gradio demo today because I was using it in an environment in which uvicorn had been installed with the ["standard"] option. That caused uvloop to be installed and resulted a fatal error when I tried to launch a gradio demo after loading a model checkpoint with orbax. In this case, the solution was to pip uninstall uvloop, but that might not be viable for the next person who runs into this. 

**Describe the solution you'd like**  
Either make gradio compatible with uvloop, or try to trap this error and provide a useful error message.

**Additional context**  

The error message was:
```
  Exception in thread Thread-12 (run):
  Traceback (most recent call last):
    File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
      self.run()
    File "/usr/lib/python3.10/threading.py", line 953, in run
      self._target(*self._args, **self._kwargs)
    File "/opt/venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
      return asyncio.run(self.serve(sockets=sockets))
    File "/opt/venv/lib/python3.10/site-packages/nest_asyncio.py", line 27, in run
      loop = asyncio.get_event_loop()
    File "/opt/venv/lib/python3.10/site-packages/nest_asyncio.py", line 41, in _get_event_loop
      loop = events.get_event_loop_policy().get_event_loop()
    File "/opt/venv/lib/python3.10/site-packages/nest_asyncio.py", line 68, in get_event_loop
      _patch_loop(loop)
    File "/opt/venv/lib/python3.10/site-packages/nest_asyncio.py", line 184, in _patch_loop
      raise ValueError('Can\'t patch loop of type %s' % type(loop))
```

You can recreate this error in colab with the notebook at the link:
[gradio_uvloop.ipynb](https://colab.research.google.com/drive/1eZ47iYeO-zaUsH6F3MIdYqG3jVbwoFn2?usp=sharing)

**Comment by freddyaboulton** [comment]
Thanks for filing! I just ran gradio 5.0 with uvloop installed and I didn't get an error. So I think this issue may be something specific about the orbax model or something else outside of gradio's control.
