### ISSUE TITLE
Lite: version conflict of anyio package when installing at the initialization

### ISSUE THREAD

**Issue by whitphx** [gradio-app/gradio#5978]
### Describe the bug

This bug is flaky, occurring randomly.

```
17:05:43.566 pyodide.asm.js:9 Loading micropip, packaging
17:05:43.583 pyodide.asm.js:9 Loaded packaging, micropip
17:05:43.925 pyodide.asm.js:9 Loading ssl, openssl, distutils, setuptools, pyparsing
17:05:44.055 pyodide.asm.js:9 Loaded pyparsing, distutils, setuptools, openssl, ssl
17:05:45.384 webworker.js:344 PythonError: Traceback (most recent call last):
  File "/lib/python3.11/site-packages/micropip/_commands/install.py", line 138, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 197, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 210, in add_requirement
    await self.add_wheel(wheel, extras=set(), specifier="")
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 357, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 197, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 201, in add_requirement
    return await self.add_requirement_inner(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 319, in add_requirement_inner
    await self.add_wheel(wheel, req.extras, specifier=str(req.specifier))
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 357, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 197, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 201, in add_requirement
    return await self.add_requirement_inner(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 283, in add_requirement_inner
    satisfied, ver = self.check_version_satisfied(req)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 228, in check_version_satisfied
    raise ValueError(
ValueError: Requested 'anyio<4.0.0,>=3.7.1', but anyio==4.0.0 is already installed

    at new_error (pyodide.asm.js:9:12519)
    at pyodide.asm.wasm:0x158827
    at pyodide.asm.wasm:0x15fcd5
    at _PyCFunctionWithKeywords_TrampolineCall (pyodide.asm.js:9:123040)
    at pyodide.asm.wasm:0x1a3091
    at pyodide.asm.wasm:0x289e4d
    at pyodide.asm.wasm:0x1e3f77
    at pyodide.asm.wasm:0x1a3579
    at pyodide.asm.wasm:0x1a383a
    at pyodide.asm.wasm:0x1a38dc
    at pyodide.asm.wasm:0x2685c5
    at pyodide.asm.wasm:0x26e3d0
    at pyodide.asm.wasm:0x1a3a04
    at pyodide.asm.wasm:0x1a3694
    at pyodide.asm.wasm:0x15f45e
    at Module.callPyObjectKwargs (pyodide.asm.js:9:81732)
    at Module.callPyObject (pyodide.asm.js:9:82066)
    at wrapper (pyodide.asm.js:9:58562)
self.onmessage @ webworker.js:344
17:05:45.385 worker-proxy.js:5 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.11/site-packages/micropip/_commands/install.py", line 138, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 197, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 210, in add_requirement
    await self.add_wheel(wheel, extras=set(), specifier="")
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 357, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 197, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 201, in add_requirement
    return await self.add_requirement_inner(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 319, in add_requirement_inner
    await self.add_wheel(wheel, req.extras, specifier=str(req.specifier))
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 357, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 197, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 201, in add_requirement
    return await self.add_requirement_inner(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 283, in add_requirement_inner
    satisfied, ver = self.check_version_satisfied(req)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 228, in check_version_satisfied
    raise ValueError(
ValueError: Requested 'anyio<4.0.0,>=3.7.1', but anyio==4.0.0 is already installed

    at new_error (pyodide.asm.js:9:12519)
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at _PyCFunctionWithKeywords_TrampolineCall (pyodide.asm.js:9:123040)
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at Module.callPyObjectKwargs (pyodide.asm.js:9:81732)
    at Module.callPyObject (pyodide.asm.js:9:82066)
    at wrapper (pyodide.asm.js:9:58562)
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Use Gradio-lite and reload the page until it occurs.

### Screenshot

![CleanShot 2023-10-18 at 17 19 43@2x](https://github.com/gradio-app/gradio/assets/3135397/9b3ac49c-4dfe-4956-bb57-19632a0400ec)

### System Info

```shell
Gradio-lite v0.4.0
```

### Severity

I can work around it

**Comment by whitphx** [comment]
It's probably because `micropip` couldn't resolve the dependency versions correctly.

`fastapi` specifies its depending `anyio` version as `>=3.4.0,<5`, while other anyio-dependents such as `gradio-client` depends on `==3.*`.
Then micropip sometimes resolves the `fastapi` dependency and installs them before resolving others and hit the conflict.

The dependency graph below is emitted by `pipdeptree` in my local env where the normal Gradio Python package is installed.
```
├── fastapi [required: Any, installed: 0.87.0]
│   ├── pydantic [required: >=1.6.2,<2.0.0,!=1.8.1,!=1.8,!=1.7.3,!=1.7.2,!=1.7.1,!=1.7, installed: 1.9.1]
│   │   └── typing-extensions [required: >=3.7.4.3, installed: 4.3.0]
│   └── starlette [required: ==0.21.0, installed: 0.21.0]
│       └── anyio [required: >=3.4.0,<5, installed: 3.6.1]  # HERE!
│           ├── idna [required: >=2.8, installed: 3.3]
│           └── sniffio [required: >=1.1, installed: 1.2.0]
...
├── gradio-client [required: ==0.6.0, installed: 0.6.0]
│   ├── fsspec [required: Any, installed: 2023.6.0]
│   ├── httpx [required: Any, installed: 0.23.0]
│   │   ├── certifi [required: Any, installed: 2022.6.15]
│   │   ├── httpcore [required: >=0.15.0,<0.16.0, installed: 0.15.0]
│   │   │   ├── anyio [required: ==3.*, installed: 3.6.1]  # HERE!
│   │   │   │   ├── idna [required: >=2.8, installed: 3.3]
│   │   │   │   └── sniffio [required: >=1.1, installed: 1.2.0]
│   │   │   ├── certifi [required: Any, installed: 2022.6.15]
│   │   │   ├── h11 [required: >=0.11,<0.13, installed: 0.12.0]
│   │   │   └── sniffio [required: ==1.*, installed: 1.2.0]
│   │   ├── rfc3986 [required: >=1.3,<2, installed: 1.5.0]
│   │   └── sniffio [required: Any, installed: 1.2.0]
```
