### ISSUE TITLE
Lite: FastAPI throws an error

### ISSUE THREAD

**Issue by whitphx** [gradio-app/gradio#5986]
### Describe the bug

Due to the new release 0.104.0: https://pypi.org/project/fastapi/0.104.0/

```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 571, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 394, in run_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 1, in <module>
  File "/lib/python3.11/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/lib/python3.11/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/lib/python3.11/site-packages/gradio/components/annotated_image.py", line 14, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "/lib/python3.11/site-packages/gradio/components/base.py", line 20, in <module>
    from fastapi import UploadFile
  File "/lib/python3.11/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/lib/python3.11/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/lib/python3.11/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/lib/python3.11/site-packages/fastapi/params.py", line 5, in <module>
    from fastapi.openapi.models import Example
  File "/lib/python3.11/site-packages/fastapi/openapi/models.py", line 4, in <module>
    from fastapi._compat import (
  File "/lib/python3.11/site-packages/fastapi/_compat.py", line 20, in <module>
    from fastapi.exceptions import RequestErrorModel
  File "/lib/python3.11/site-packages/fastapi/exceptions.py", line 6, in <module>
    from typing_extensions import Annotated, Doc  # type: ignore [attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'Doc' from 'typing_extensions' (/lib/python3.11/site-packages/typing_extensions.py)
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Run Gradio-lite

### System Info

```shell
xxx
```

### Severity

I can work around it

**Comment by whitphx** [comment]
Fixed with #5987 as a workaround.
More fundamental solution should be replace it and it will be tracked in #6010
