### ISSUE TITLE
Lite: Remove the workaround pinning the FastAPI version

### ISSUE THREAD

**Issue by whitphx** [gradio-app/gradio#6010]
I created this PR #5987 as the simplest workaround for the following error.
However, it should be replaced a better solution e.g. resolving the proper version of `typing_extensions`.

```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 571, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 394, in run_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 1, in <module>
  File "/lib/python3.11/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/lib/python3.11/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/lib/python3.11/site-packages/gradio/components/annotated_image.py", line 14, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "/lib/python3.11/site-packages/gradio/components/base.py", line 20, in <module>
    from fastapi import UploadFile
  File "/lib/python3.11/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/lib/python3.11/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/lib/python3.11/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/lib/python3.11/site-packages/fastapi/params.py", line 5, in <module>
    from fastapi.openapi.models import Example
  File "/lib/python3.11/site-packages/fastapi/openapi/models.py", line 4, in <module>
    from fastapi._compat import (
  File "/lib/python3.11/site-packages/fastapi/_compat.py", line 20, in <module>
    from fastapi.exceptions import RequestErrorModel
  File "/lib/python3.11/site-packages/fastapi/exceptions.py", line 6, in <module>
    from typing_extensions import Annotated, Doc  # type: ignore [attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'Doc' from 'typing_extensions' (/lib/python3.11/site-packages/typing_extensions.py)
```

**Comment by freddyaboulton** [comment]
@whitphx see this issue: https://github.com/pyodide/pyodide/issues/4234#issuecomment-1771735148 I think we may need to set the typing-extensions version ourselves for gradio/lite

**Comment by whitphx** [comment]
@freddyaboulton Thank you!
Actually there is already a list of manually resolved packages here for the same issue with micropip, so this would be one of them.
https://github.com/gradio-app/gradio/blob/6f15d65776926f38a9e29fbfafbacaa045f6641e/js/wasm/src/webworker/index.ts#L92-L94
