### ISSUE TITLE
Startup failed，  Network Error

### ISSUE THREAD

**Issue by yixuan1912** [gradio-app/gradio#6102]
### Describe the bug

An error occurred when running using the latest git source code and running in docker-compose mode. Can you help me？

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

**config**

[root@JUHOST-64Wkw9 gpt_academic]# cat config.py 
API_KEY = "sk-gqWauBZgMFhM*********kLM"  

USE_PROXY = False
if USE_PROXY:
    proxies = {
        #          [协议]://  [地址]  :[端口]
        "http":  "socks5h://localhost:11284",  # 再例如  "http":  "http://127.0.0.1:7890",
        "https": "socks5h://localhost:11284",  # 再例如  "https": "http://127.0.0.1:7890",
    }
else:
    proxies = None

### Logs

```shell
[root@JUHOST-64Wkw9 gpt_academic]# python3 main.py 
 [PROXY] 网络代理状态：未配置。无代理状态下很可能无法访问OpenAI家族的模型。建议：检查USE_PROXY选项是否修改。 
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
代理配置 无, 代理所在地：Japan - Google LLC
 [API_KEY] 本项目现已支持OpenAI和Azure的api-key。也支持同时填写多个api-key，如API_KEY="openai-key1,openai-key2,azure-key3" 
 [API_KEY] 您既可以在config.py中修改api-key(s)，也可以在问题输入区输入临时的api-key(s)，然后回车键提交后即可生效。 
 [API_KEY] 您的 API_KEY 是: sk-gqWauBZgMFhM*** API_KEY 导入成功 
如果浏览器没有自动打开，请复制并转到以下URL：
	「暗色主题已启用（支持动态切换主题）」: http://localhost:57531
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f08b1047070>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=57531): Max retries exceeded with url: /startup-events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f08b1047070>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/gpt_academic/main.py", line 448, in <module>
    main()
  File "/root/gpt_academic/main.py", line 427, in main
    demo.queue(concurrency_count=CONCURRENT_COUNT).launch(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1775, in launch
    requests.get(f"{self.local_url}startup-events", verify=ssl_verify)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=57531): Max retries exceeded with url: /startup-events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f08b1047070>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

### System Info

```shell
CentOS Linux release 7.9.2009 (Core)
Python-3.10.4
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @yixuan1912 sorry for the late response, can you please try with Gradio 4.0 or above? Can you also please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by abidlabs** [comment]
Closing for now, but happy to look into it again if we have a repro that persists in Gradio 4.0
