### ISSUE TITLE
A type error occurred while using the FileExplorer component

### ISSUE THREAD

**Issue by shliar** [gradio-app/gradio#6105]
### Describe the bug

**Hi I encountered the following error while using the gr.FileExplorer component of Gradio**

My program is as follows：
```
with gr.Tab("Choose File Here"):
        with gr.Row():
            file_output = gr.FileExplorer(glob="*.py",root=".",label='choose file',show_progress=True)
```
**The error output is as follows：**
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\fastapi\routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\routes.py", line 620, in component_server
    return fn(body.data)
  **File "C:\Users\uu\AppData\Local\Programs\Python\Python38\lib\site-packages\gradio\components\file_explorer.py", line 200, in ls
    files += glob_func(result, recursive=True, root_dir=self.root)  # type: ignore
TypeError: glob() got an unexpected keyword argument 'root_dir'**
```
**My Environment:**
1. Python 3.8.10
2. OS Windows 11
3. gradio 3.50.2

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr

def upload_file(file_obj):
    print(file_obj.filename)
    return file_obj.name

with gr.Blocks() as demo:
    # 设置tab选项卡
    with gr.Tab("Choose File Here"):
        with gr.Row():
            file_output = gr.FileExplorer(glob="*.py",root=".",label='choose file',show_progress=True)
        with gr.Row():
            text_output = gr.Textbox(label='path',interactive=True)
            text_button = gr.Button("OK")
        text_button.click(upload_file, inputs=[file_output],outputs=[text_output])
demo.queue(concurrency_count=1).launch()
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 3.50.2
gradio_client version: 0.6.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.103.2
ffmpy: 0.3.1
gradio-client==0.6.1 is not installed.
httpx: 0.25.0
huggingface-hub: 0.17.3
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.3
numpy: 1.24.4
orjson: 3.9.7
packaging: 23.2
pandas: 2.0.3
pillow: 10.0.1
pydantic: 2.4.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.8.0
uvicorn: 0.16.0
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.9.2
httpx: 0.25.0
huggingface-hub: 0.17.3
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
There's a bug in the file explorer. It only works on 3.10+. Will fix next week https://github.com/gradio-app/gradio/issues/5907

Closing since it's a duplicate! Thanks @shliar !

**Comment by LennardBo** [comment]
I've copied the code to a my computer and even with Python 3.10 the code above does not seem to work (see below). I have a hard time getting this new block to do anything besides looking pretty (as input to another function and its change method). Does this code actually run for you with Python 3.10?
Generally, a tutorial actually showcasing the major uses of the emthhod would be greatly appreciated, the current demo at https://www.gradio.app/docs/fileexplorer doesn't even mention the file explorer in anyway (is that a mix-up?).

```
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/site-packages/gradio/queueing.py", line 427, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/site-packages/gradio/blocks.py", line 1495, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/site-packages/gradio/blocks.py", line 1278, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/site-packages/gradio/components/file_explorer.py", line 118, in preprocess
    return [self._safe_join(file) for file in (payload)]
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/site-packages/gradio/components/file_explorer.py", line 118, in <listcomp>
    return [self._safe_join(file) for file in (payload)]
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/site-packages/gradio/components/file_explorer.py", line 206, in _safe_join
    combined_path = os.path.join(self.root, *folders)
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'
Traceback (most recent call last):
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/site-packages/gradio/queueing.py", line 427, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/site-packages/gradio/blocks.py", line 1495, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/site-packages/gradio/blocks.py", line 1278, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/site-packages/gradio/components/file_explorer.py", line 118, in preprocess
    return [self._safe_join(file) for file in (payload)]
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/site-packages/gradio/components/file_explorer.py", line 118, in <listcomp>
    return [self._safe_join(file) for file in (payload)]
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/site-packages/gradio/components/file_explorer.py", line 206, in _safe_join
    combined_path = os.path.join(self.root, *folders)
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/site-packages/gradio/queueing.py", line 472, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/home/****/conda/envs/breuer_filter/lib/python3.10/site-packages/gradio/queueing.py", line 436, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
```
