### ISSUE TITLE
Gradio image example will have a  exception in ASGI application of permission error when I upload the image

### ISSUE THREAD

**Issue by TRUEJASONFANS** [gradio-app/gradio#6242]
### Describe the bug

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\xxx\scoop\apps\python\current\Lib\shutil.py", line 825, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\tmpotno6j9x' -> 'C:\\Users\\xxx\\AppData\\Local\\Temp\\gradio\\077bafda8f82d374252967dfed899b5c3bdbb458\\DSC_0062.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\fastapi\routing.py", line 274, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\gradio\routes.py", line 706, in upload_file
    await anyio.to_thread.run_sync(
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\xxx\scoop\apps\python\current\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\scoop\apps\python\current\Lib\shutil.py", line 846, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\tmpotno6j9x'

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
jupyter_client            8.3.1
jupyter_core              5.3.1
jupyter-events            0.7.0
jupyter-lsp               2.2.0
jupyter_server            2.7.3
jupyter_server_terminals  0.4.4
jupyterlab                4.0.5
jupyterlab-pygments       0.2.2
jupyterlab_server         2.24.0
```
import numpy as np
import gradio as gr

def sepia(input_img):
    sepia_filter = np.array([
        [0.393, 0.769, 0.189], 
        [0.349, 0.686, 0.168], 
        [0.272, 0.534, 0.131]
    ])
    sepia_img = input_img.dot(sepia_filter.T)
    sepia_img /= sepia_img.max()
    return sepia_img

demo = gr.Interface(sepia, gr.Image(type="pil"), "image")
demo.launch(share=True)
```

### System Info

```shell
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.0
huggingface-hub: 0.18.0
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.1
numpy: 1.25.2
orjson: 3.9.10
packaging: 23.1
pandas: 2.1.2
pillow: 10.1.0
pydantic: 2.4.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.0
huggingface-hub: 0.18.0
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by pandazzh2020** [comment]
+1

**Comment by angelahahaa** [comment]
+1, running on Windows locally and got the same problem when uploading an image.  
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\shutil.py", line 816, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\XXX\\AppData\\Local\\Temp\\tmpd7nsyije' -> 'C:\\Users\\xxx\\AppData\\Local\\Temp\\gradio\\fa2089457f01f7e89a0b60e5415a2c1530c84292\\cat.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\fastapi\routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\gradio\routes.py", line 
706, in upload_file
    await anyio.to_thread.run_sync(
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\shutil.py", line 837, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\XXX\\AppData\\Local\\Temp\\tmpd7nsyije'
```

**Comment by angelahahaa** [comment]
> Can anyone give a working version to avoid this problem? It's such a frustrating problem when I just start using Gradio. 😩

try `gradio==3.36`

**Comment by elonzh** [comment]
> > Can anyone give a working version to avoid this problem? It's such a frustrating problem when I just start using Gradio. 😩
> 
> try `gradio==3.36`

Thanks bro, I tested `gradio==3.48.0` and it works.

**Comment by freddyaboulton** [comment]
This got fixed in gradio version 4.1.0! See #6289
