### ISSUE TITLE
[Gradio 4.0] `gr.File` is broken on windows (PermissionError)

### ISSUE THREAD

**Issue by LLukas22** [gradio-app/gradio#6246]
### Describe the bug

If i try to upload a file via a simple `gr.File` control, an `PermissionError: [WinError 32]` gets thrown. The error seams to occure while renaming the file via `os.rename`. 

A short excerpt of the exception: 
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 825, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\luk\\AppData\\Local\\Temp\\tmpc78oyzhy' -> 'C:\\Users\\luk\\AppData\\Local\\Temp\\gradio\\63e9818cb69f632e3c9f18908c5d2a15099fee83\\2023-09-21-12-00AM-160-199.xml'
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Simply create a `gr.File` control and try to uplaod a file on a windows machine.

Example-Code:
```python
import gradio as gr


with gr.Blocks() as demo:
    gr.File() 
    
demo.launch()
```

### Logs

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 825, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Users\\luk\\AppData\\Local\\Temp\\tmpq9lkwth8' -> 'C:\\Users\\luk\\AppData\\Local\\Temp\\gradio\\78ef53cc4ff4a93b90733dae25b6e5e277cb3105\\2023-09-21-12-00AM-320-359.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\routes.py", line 706, in upload_file
    await anyio.to_thread.run_sync(
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\luk\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 846, in move
    os.unlink(src)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Users\\luk\\AppData\\Local\\Temp\\tmpq9lkwth8'
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.0.2
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.1
fastapi: 0.103.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.24.1
huggingface-hub: 0.16.4
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.25.2
orjson: 3.9.6
packaging: 23.1
pandas: 1.5.3
pillow: 10.0.0
pydantic: 2.4.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.7.1
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.9.0
httpx: 0.24.1
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by Rjdrenth** [comment]
+1 
Was just about to create an issue when I saw this one.

**Comment by EricZiola** [comment]
I'm getting the same issue.
![2023-11-02 10_36_39-gradio_file_input py - General_Ledger_Coding - Visual Studio Code](https://github.com/gradio-app/gradio/assets/136095754/86fa0dfd-3132-4d31-87f8-7972670e9582)

**Comment by freddyaboulton** [comment]
This is when you upload a file right?

I think I know the line thats causing this to happen but I do not know how to fix yet. Will look into it! Thanks for filing all.

**Comment by EricZiola** [comment]
> This is when you upload a file right?
> 
> I think I know the line thats causing this to happen but I do not know how to fix yet. Will look into it! Thanks for filing all.

Thanks Freddy. Yes. I'm trying to upload a .csv file. I moved the .csv file that I'm trying to import directly to my C:\ drive (windows) so that it would not be impacted by syncing to OneDrive. From the C:\ folder I tried to import to Gradio using the Interface class (you can see in my code above) and received that error. Thanks for digging in!

**Comment by angelahahaa** [comment]
+1 same issue with `gr.Image` on Windows

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\shutil.py", line 816, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\XXX\\AppData\\Local\\Temp\\tmpd7nsyije' -> 'C:\\Users\\xxx\\AppData\\Local\\Temp\\gradio\\fa2089457f01f7e89a0b60e5415a2c1530c84292\\cat.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\fastapi\routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\gradio\routes.py", line 
706, in upload_file
    await anyio.to_thread.run_sync(
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\xxx\AppData\Local\miniconda3\envs\gr4\lib\shutil.py", line 837, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\XXX\\AppData\\Local\\Temp\\tmpd7nsyije'
```

**Comment by cwjjun** [comment]
same issue with gr.UploadButton on Windows: PermissionError: [WinError 32] The process cannot access the file because it is being used by another process
