### ISSUE TITLE
english_translator = gr.Blocks.load(name="spaces/gradio/english_translator")

### ISSUE THREAD

**Issue by AliArshadswl** [gradio-app/gradio#6248]
### Describe the bug

This line of code does not work. The first error is we should not use name, the second one is it gives following error:
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 427, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1497, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1119, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 665, in wrapper
    response = f(*args, **kwargs)
  File "<ipython-input-5-e5f268d83c97>", line 12, in generate_text
    german_text = english_translator(english_text)
  File "/usr/local/lib/python3.10/dist-packages/gradio/events.py", line 75, in __call__
    return self.fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/events.py", line 237, in wrapper
    event_trigger(
  File "/usr/local/lib/python3.10/dist-packages/gradio/events.py", line 296, in event_trigger
    raise AttributeError(
AttributeError: Cannot call load outside of a gradio.Blocks context.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 427, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1497, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1119, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 665, in wrapper
    response = f(*args, **kwargs)
  File "<ipython-input-5-e5f268d83c97>", line 12, in generate_text
    german_text = english_translator(english_text)
  File "/usr/local/lib/python3.10/dist-packages/gradio/events.py", line 75, in __call__
    return self.fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/events.py", line 237, in wrapper
    event_trigger(
  File "/usr/local/lib/python3.10/dist-packages/gradio/events.py", line 296, in event_trigger
    raise AttributeError(
AttributeError: Cannot call load outside of a gradio.Blocks context.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 472, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 436, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://886f7ea7a6651b61d3.gradio.live/
Killing tunnel 127.0.0.1:7861 <> https://0d6326549fec75b428.gradio.live/
Killing tunnel 127.0.0.1:7862 <> https://9318dbcb9132ea281b.gradio.live/

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Just paste the code in the Google Colab and try to run

### System Info

```shell
Windows, Google Colab
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @AliArshadswl . This is expected. With gradio 4.0 you should be calling `gr.load` instead of `Blocks.load`. Did you see this anywhere on our documentation?

**Comment by abidlabs** [comment]
Closing as this should be resolved.
