### ISSUE TITLE
Working Application fine in V-3.50.2 but not in V-4.0.2

### ISSUE THREAD

**Issue by AntroSafin** [gradio-app/gradio#6275]
### Describe the bug

Images are not displaying in the icons of the buttons in version V-4.0.2 but it is working fine in V-3.50.2
Also sometimes the interactivity also not getting showing event not found error.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

![image](https://github.com/gradio-app/gradio/assets/85235476/484ae852-49f8-47c4-95da-da4e15a4774a)
Provide some images and use the images in the icons of the button.

### Screenshot

![Screenshot 2023-11-03 145629](https://github.com/gradio-app/gradio/assets/85235476/681520f9-290c-4753-958b-28ec33011e7a)

### Logs

```shell
INFO:     ::1:52581 - "POST /queue/data HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gradio\routes.py", line 653, in queue_data
    blocks._queue.attach_data(body)
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gradio\queueing.py", line 132, in attach_data
    raise ValueError("Event not found", event_id)
ValueError: ('Event not found', 'c7ac91f44c394f3090f60f2509b008c4')
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.0.2
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.100.0
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.0
huggingface-hub: 0.16.4
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.25.2
orjson: 3.9.9
packaging: 23.1
pandas: 1.5.3
pillow: 10.0.0
pydantic: 2.1.1
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.7.1
uvicorn: 0.23.1
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.25.0
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by pngwn** [comment]
Do you have a reproduction?

**Comment by abidlabs** [comment]
It'd be good to have a repro @AntroSafin, although I'm pretty sure that this is the issue: https://github.com/gradio-app/gradio/issues/6281#issuecomment-1792881172 (please see the provided solution there)

**Comment by DalasNoin** [comment]
I have a very similar error but I am not using any images in my gradio, I just use a chatinterface. downgrading to 3.50 solves the issue

`  File "/home/paperspace/miniconda3/envs/lora/lib/python3.10/site-packages/starlette/routing.py", line 66, in app                                                                                  
    response = await func(request)                                                                                                                                                                 
  File "/home/paperspace/miniconda3/envs/lora/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app                                                                                   
    raw_response = await run_endpoint_function(                                                                                                                                                    
  File "/home/paperspace/miniconda3/envs/lora/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function                                                                 
    return await dependant.call(**values)                                                                                                                                                          
  File "/home/paperspace/miniconda3/envs/lora/lib/python3.10/site-packages/gradio/routes.py", line 653, in queue_data                                                                              
    blocks._queue.attach_data(body)                                                                                                                                                                
  File "/home/paperspace/miniconda3/envs/lora/lib/python3.10/site-packages/gradio/queueing.py", line 132, in attach_data                                                                           
    raise ValueError("Event not found", event_id)                                                                                                                                                  
ValueError: ('Event not found', 'a3f35cc6ea7c42219e96b5319f7942fc')`

**Comment by DalasNoin** [comment]
I have a very similar error but I am not using any images in my gradio, I just use a chatinterface. downgrading to 3.50 solves the issue

```
  File "/home/paperspace/miniconda3/envs/lora/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function                                                                 
    return await dependant.call(**values)                                                                                                                                                          
  File "/home/paperspace/miniconda3/envs/lora/lib/python3.10/site-packages/gradio/routes.py", line 653, in queue_data                                                                              
    blocks._queue.attach_data(body)                                                                                                                                                                
  File "/home/paperspace/miniconda3/envs/lora/lib/python3.10/site-packages/gradio/queueing.py", line 132, in attach_data                                                                           
    raise ValueError("Event not found", event_id)                                                                                                                                                  
ValueError: ('Event not found', 'a3f35cc6ea7c42219e96b5319f7942fc')
```

**Comment by DalasNoin** [comment]
I have tried to apply the solution with allowed_paths but did not see any change in the error. Again, I am not using any images.
```
gr.ChatInterface(
        fn=evaluate,
        additional_inputs=[
            gr.components.Slider(
                minimum=0, maximum=1, value=0.4, label="Temperature"
            ),
            gr.components.Slider(
                minimum=0, maximum=1, value=0.75, label="Top p"
            ),
            gr.components.Slider(
                minimum=0, maximum=100, step=1, value=40, label="Top k"
            ),
            gr.components.Slider(
                minimum=1, maximum=4, step=1, value=1, label="Beams"
            ),
            gr.components.Slider(
                minimum=1, maximum=2000, step=1, value=800, label="Max tokens"
            ),
            gr.components.Checkbox(label="Stream output", value=True),
        ],
       
        title="🦙",
        description="LLama-2-chat", 
        chatbot=gr.Chatbot(
            show_copy_button=True,
            show_share_button=True,)
    ).queue().launch(server_name="localhost", share=share_gradio,auth=("xxxxxx", "xxxxxx"),allowed_paths=["."])
```

**Comment by DalasNoin** [comment]
However, the old version seems to have another bug, I can't use auth in the api using the python client
```
from gradio_client import Client
client = Client("https://xxxxx.xyz/", auth=("xxxxxx", "xxxxxx"))

result = client.predict(
                       'how are you',# str in Textbox
                       0.2,# int | float (numeric value between 0 and 1) in 'Temperature' Slider component
                       0.9,# int | float (numeric value between 0 and 1) in 'Top p' Slider component
                        50,# int | float (numeric value between 0 and 100) in 'Top k' Slider component
                        1,# int | float (numeric value between 1 and 4) in 'Beams' Slider component
                        1,# int | float (numeric value between 1 and 2000) in 'Max tokens' Slider component
                        False,# bool in 'Stream output' Checkbox component
                        api_name="/chat"
)
```
Error:
```
--> 329     raise InvalidStatusCode(status_code, response_headers)
    331 check_response(response_headers, key)
    333 self.extensions = self.process_extensions(
    334     response_headers, available_extensions
    335 )

InvalidStatusCode: server rejected WebSocket connection: HTTP 403
```

**Comment by abidlabs** [comment]
@DalasNoin I ran a self-contained version of your code:

```py
gr.ChatInterface(
        fn=lambda *args: args,
        additional_inputs=[
            gr.components.Slider(
                minimum=0, maximum=1, value=0.4, label="Temperature"
            ),
            gr.components.Slider(
                minimum=0, maximum=1, value=0.75, label="Top p"
            ),
            gr.components.Slider(
                minimum=0, maximum=100, step=1, value=40, label="Top k"
            ),
            gr.components.Slider(
                minimum=1, maximum=4, step=1, value=1, label="Beams"
            ),
            gr.components.Slider(
                minimum=1, maximum=2000, step=1, value=800, label="Max tokens"
            ),
            gr.components.Checkbox(label="Stream output", value=True),
        ],
       
        title="🦙",
        description="LLama-2-chat", 
        chatbot=gr.Chatbot(
            show_copy_button=True,
            show_share_button=True,)
    ).queue().launch()
```

and don't see any issues. I think the issue you are describing is different than the 403 errors that @AntroSafin mentioned. My solution was to avoid the 403s. Please feel free to open a separate issue with a self-contained repro and clear description of the error you are facing. @AntroSafin I'll close for lack of followup, but feel free to let us know if the solution I suggested does not work.

**Comment by abdulnim** [comment]
i am having the same error while uploading audio for processing

```
demo = gr.Blocks()
with demo:
    with gr.Row():
        with gr.Column():
            # Inputs
            audio_file = gr.Audio(type="filepath")
            text_prompts = gr.Textbox(label="Initial Prompts(Optionsl)")
            
        with gr.Column():
            # Outpus
            text_transcript = gr.Textbox(label="Transcript Before cleaning")
            text_transcript_clear = gr.Textbox(label="Transcript after cleaning")
        
        # Button
    button_transcribe = gr.Button("Transcribe Audio")
    button_transcribe.click(fn=transcribe_whisperx, inputs=[audio_file, text_prompts], outputs= [text_transcript, text_transcript_clear])
    
demo.queue()
demo.launch(allowed_paths=["."], share=True)
```

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/gradio/routes.py", line 699, in upload_file
    form = await multipart_parser.parse()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/gradio/route_utils.py", line 444, in parse
    async for chunk in self.stream:
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/requests.py", line 230, in stream
    raise ClientDisconnect()
starlette.requests.ClientDisconnect

**Comment by abidlabs** [comment]
Hi @abdulnim can you try upgrading to the latest version of `gradio`?

**Comment by mangiucugna** [comment]
FWIW I just created an app in HF and I see this error as well: https://huggingface.co/spaces/mangiucugna/corporate-videocall-coach
The error happens continuously but it has no impact on the app itself.
I am using latest gradio and it doesn't happen locally.

I see some people mentioning that this might be because of security reasons but I am not try to expose any local file or anything aside from using the video and audio components.
Might it be related to the webcam with streaming enabled?

**Comment by abidlabs** [comment]
@mangiucugna would you be able to create a new issue? It seems like its a non-blocking error for you but would be good to figure out what's going on?

**Comment by mangiucugna** [comment]
Sure thing

**Comment by abdulnim** [comment]
> Hi @abdulnim can you try upgrading to the latest version of `gradio`?

the Drop Audio UI the latest version seems to be broken, the button on the bottom of the audio panel (to upload audio) doesn't work, and the drag-drop doesn't work for me either. 
I can upload small audios only by clicking on the whole panel and even then the audio doesn't show up for a very long, no progress either to show if the audio is uploading. 
a slightly bigger audio gives the same error as I showed before.

**Comment by abidlabs** [comment]
That's pretty strange @abdulnim, can you provide a repro of your Gradio app code, along with the audio files you are trying?

**Comment by abdulnim** [comment]
@abidlabs I upgraded to 4.2.0 the drag-drop is working fine for uploading the audio and I can see progress now when I upload audio.  The upload audio button is still not clickable though.

the error seems to appear as the actual demo is running on my Linux server and I am accessing it from my local Windows PC, in that case, a simple 5-min takes a very long and i get "/requests.py", line 230, in-stream raise ClientDisconnect() starlette.requests.ClientDisconnect" error.

**Comment by abidlabs** [comment]
Thanks @abdulnim would you please be able to share a [minimal code example](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to reproduce the issue?

**Comment by abdulnim** [comment]
@abidlabs 

```
import os
import gradio as gr
from pydub import AudioSegment
# os.environ["CUDA_VISIBLE_DEVICES"]="0"


#==================== Transcripbe Method is Here  ====================
def transcribe_whisperx(audio_file, prompt=None):
    
    if audio_file is None:
      print("There is no audio to transribe")
      return "The Audio is Not Loaded Yet"
    else:
      print("Audio found : "+audio_file)
  
    audio = AudioSegment.from_file(audio_file)  
    length_in_milliseconds = len(audio)
    length_in_seconds = length_in_milliseconds / 1000
    print("Audio recieved, Length in seconds:", length_in_seconds)
    return f"Audio length is seconds : {length_in_seconds}"
    

#==================== Gradio Demo ====================    
demo = gr.Blocks()
with demo:
    with gr.Row():
        with gr.Column():
            # Inputs
            audio_file = gr.Audio(type="filepath")
            text_prompts = gr.Textbox(label="Initial Prompts(Optionsl)")
            
        with gr.Column():
            # Outpus
            text_transcript = gr.Textbox(label="Transcript Before cleaning")
        
    # Button
    button_transcribe = gr.Button("Transcribe Audio")
    button_transcribe.click(fn=transcribe_whisperx, inputs=[audio_file, text_prompts], outputs= [text_transcript])
    
demo.queue()
demo.launch(allowed_paths=["."], share=True)
```
I removed loading the whisper models and made a minimal code with 4.2.0. 
This works fine on my local PC but the error appears if I run it on a Linux server with slightly bigger audio (that takes longer to process).

**Comment by abidlabs** [comment]
Thanks @abdulnim! Would you be able to create a new issue so that our team can parse it a little more easily? This issue is getting a little out of hand

**Comment by abdulnim** [comment]
@abidlabs #6393 

if you would like me provide with the audio plz let me know

**Comment by abidlabs** [comment]
Thanks @abdulnim, yes that would be great too so that we can reproduce it end2end. You can link it in the new issue

**Comment by abdulnim** [comment]
@abidlabs won't be able to make the audio public but can send it to you or the team directly.

**Comment by abidlabs** [comment]
Ok you can send it to team@gradio.app

**Comment by abdulnim** [comment]
@abidlabs sent
