### ISSUE TITLE
Batch analysis gives queue error. 

### ISSUE THREAD

**Issue by impromptuRong** [gradio-app/gradio#6293]
### Describe the bug

I have an app using queue to analyze batch of images and return the result. 
The script works on version 3.5, but gives me queue related error after I upgrade to 4.1.1. So I write a small script that takes an image and display the same image. The same script works on 3.5, and no error when I disable `batch=True`. Would you mind helping me on the problem and what I should do? 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def predict(images):
    return [images]

with gr.Blocks() as demo:
    with gr.Row(equal_height=True):
        inputs = gr.Image()
        outputs = gr.Image()
    submit_btn = gr.Button("Run")
    submit_btn.click(
        fn=predict, inputs=[inputs], outputs=[outputs], 
        api_name='predict', batch=True
    )

demo.queue().launch(share=True)
```

### Screenshot

<img width="1275" alt="Screenshot 2023-11-03 at 7 42 18 PM" src="https://github.com/gradio-app/gradio/assets/1456275/56d245a8-0dc9-40f0-b77a-163be56736ba">

### Logs

```shell
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://bdd452dbb9745be936.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Queue.start_processing() done, defined at /home/rrong/miniconda3/envs/gradio/lib/python3.12/site-packages/gradio/queueing.py:198> exception=ValueError('list.remove(x): x not in list')>
Traceback (most recent call last):
  File "/home/rrong/miniconda3/envs/gradio/lib/python3.12/site-packages/gradio/queueing.py", line 209, in start_processing
    events, batch = self.get_events_in_batch()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rrong/miniconda3/envs/gradio/lib/python3.12/site-packages/gradio/queueing.py", line 194, in get_events_in_batch
    self.event_queue.remove(event)
ValueError: list.remove(x): x not in list
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.1.1
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.1
huggingface-hub: 0.18.0
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.1
numpy: 1.26.1
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.2
pillow: 10.1.0
pydantic: 2.4.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.1
huggingface-hub: 0.18.0
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Just tested, and this is now fixed on `main`, likely thanks to https://github.com/gradio-app/gradio/pull/6814. This fix should be out in gradio==4.11 soon!
