### ISSUE TITLE
Examples not filling designated field in app loaded in Space via gr.load from other Space - gradio_client.utils.InvalidAPIEndpointError

### ISSUE THREAD

**Issue by dwipper** [gradio-app/gradio#6302]
### Describe the bug

Examples not filling designated field in app loaded in Space via gr.load from another Space (throws an error), even though Examples work fine in the orgin app.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Here's the public Space where the Examples don't load: https://huggingface.co/spaces/dwipper/NILI-Mobile-Examples (Login: admin/admin)

Here's the Space where the app is running, and Examples work: https://huggingface.co/spaces/dwipper/NILI-Mobile-Full-NoLogo 

### Screenshot

Here's a video of the problem:

https://github.com/gradio-app/gradio/assets/140648761/0ccb063a-e814-4f44-9ae3-18ccf9dff1e7

### Logs

```shell
Here's the log from the public Space after clicking on an example:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/gradio/routes.py", line 565, in predict
    output = await route_utils.call_process_api(
  File "/home/user/.local/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1484, in process_api
    result = await self.call_function(
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1106, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/user/.local/lib/python3.10/site-packages/gradio/utils.py", line 665, in wrapper
    response = f(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/gradio_client/client.py", line 865, in _inner
    raise utils.InvalidAPIEndpointError()
gradio_client.utils.InvalidAPIEndpointError
```

### System Info

```shell
No sure how to do this in a Space.
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Oh interesting. I think we set `api_name=False` for the example click event @abidlabs !

**Comment by dwipper** [comment]
@freddyaboulton Thanks. So what change should I make to the .load params?

Also, is there a way to pass the auth username from the .launch to the backend app?

**Comment by abidlabs** [comment]
Yes I was just looking into this. @dwipper if you set `api_name="load_examples"` or anything else in your `gr.Examples()`, it should work.

Meanwhile, I'm making this the default in the library to prevent this issue from reoccurring

**Comment by dwipper** [comment]
@abidlabs I made the change you suggested, and it works now. No errors.....
