### ISSUE TITLE
AsyncGenerator function yielding with component instances doesn't work

### ISSUE THREAD

**Issue by whitphx** [gradio-app/gradio#6342]
### Describe the bug

If the function passed to `fn` is an async generator function (`async def` + `yield`) yielding with component instances, an error occurs.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Run this code and click the "Generate" button.
(FYI: This code is based on the line_plot part of `demo/live_dashboard/run.py`)

```python
import math

import asyncio
import gradio as gr
import numpy as np
import pandas as pd


async def get_plot():
    period = 1
    plot_end = 2 * math.pi

    while True:
        x = np.arange(plot_end - 2 * math.pi, plot_end, 0.02)
        y = np.sin(2 * math.pi * period * x)
        update = gr.LinePlot(
            value=pd.DataFrame({"x": x, "y": y}),
            x="x",
            y="y",
            title="Plot (updates every second)",
            width=600,
            height=350,
        )
        plot_end += 2 * math.pi
        if plot_end > 1000:
            plot_end = 2 * math.pi
        yield update

        await asyncio.sleep(period)


demo = gr.Interface(fn=get_plot, inputs=None, outputs=gr.LinePlot())
demo.queue().launch()
```

### Screenshot

![CleanShot 2023-11-08 at 23 39 33@2x](https://github.com/gradio-app/gradio/assets/3135397/80b11724-5d48-4795-86bd-a48a0ace29d0)

### Logs

```shell
❯ python async_gen_plot.py
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
/path/to/workspace/.venv/lib/python3.10/site-packages/gradio/components/button.py:89: UserWarning: Using the update method is deprecated. Simply return a new object instead, e.g. `return gr.Button(...)` instead of `return gr.Button.update(...)`.
  warnings.warn(
Traceback (most recent call last):
  File "/path/to/workspace/.venv/lib/python3.10/site-packages/gradio/queueing.py", line 406, in call_prediction
    output = await route_utils.call_process_api(
  File "/path/to/workspace/.venv/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/path/to/workspace/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1563, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/path/to/workspace/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1442, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "/path/to/workspace/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 371, in postprocess_update_dict
    attr_dict["value"] = block.postprocess(update_dict["value"])
  File "/path/to/workspace/.venv/lib/python3.10/site-packages/gradio/components/line_plot.py", line 430, in postprocess
    if self.x is None or self.y is None:
AttributeError: 'LinePlot' object has no attribute 'x'
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 3.47.1
gradio_client version: 0.6.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.1.0
altair: 5.0.1
fastapi: 0.95.2
ffmpy: 0.3.0
gradio-client==0.6.0 is not installed.
httpx: 0.24.1
huggingface-hub: 0.14.1
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.2
matplotlib: 3.7.1
numpy: 1.24.3
orjson: 3.8.14
packaging: 23.1
pandas: 2.0.2
pillow: 9.5.0
pydantic: 1.10.8
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.6.2
uvicorn: 0.22.0
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.5.0
httpx: 0.24.1
huggingface-hub: 0.14.1
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.6.2
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by whitphx** [comment]
As long as I investigated as part of #6099 (https://github.com/gradio-app/gradio/pull/6099#issuecomment-1801800035), `ComponentMeta` doesn't work well inside an async generator. If I removed [this if-clause](https://github.com/gradio-app/gradio/blob/f1409f95ed39c5565bed6a601e41f94e30196a57/gradio/component_meta.py#L143C12-L146) to make it return `return fn(self, **kwargs)` in anytime, the sample code above worked.

**Comment by freddyaboulton** [comment]
Thanks for looking into it @whitphx ! Is this for all components or just plots/LinePlot?

**Comment by whitphx** [comment]
@freddyaboulton 
Not all, but some other as well.
This error occurs here by accessing `self.x` while `self.x` is not initialized due to the meta class trick written above.
https://github.com/gradio-app/gradio/blob/42f76aeeb7b7263abccc038b699fb7fae7fe2313/gradio/components/line_plot.py#L295

So, this error occurs with the components which access `self.*` attributes inside `.postprocess`.
For example, `gr.Number()` is the case as it accesses `self.precision`:
https://github.com/gradio-app/gradio/blob/42f76aeeb7b7263abccc038b699fb7fae7fe2313/gradio/components/number.py#L125

Sample code to reproduce the error is:
```python
import asyncio
import gradio as gr


async def get_text_stream():
    period = 1
    count = 0

    while True:
        yield gr.Number(f"Count: {count}")

        count += 1

        await asyncio.sleep(period)


demo = gr.Interface(fn=get_text_stream, inputs=None, outputs=["number"])
demo.queue().launch()

```
