### ISSUE TITLE
'Button' object has no attribute 'click'

### ISSUE THREAD

**Issue by AntroSafin** [gradio-app/gradio#6358]
### Describe the bug

I am using the gradio app, while using it I have the function of the components which will execute when I call the function separately it is working fine but when I call it in another button click event it showing errors

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
def process_changes():
            changed_data = gf.CDC()
            for change in changed_data:
                key, message, old_data, new_data = change
                key1 = gr.Textbox(value=key,visible=False)
                message1 = gr.Textbox(value=message,visible=False)
                new_data1 = gr.Textbox(value=new_data,visible=False)
                with gr.Row(elem_id="wrapper"):
                    key2 = gr.Markdown(key, elem_id="key")
                    message2 = gr.Markdown(message, elem_id="message")
                    difference = gr.HighlightedText(label="",
                                                    value=gf.diff_texts(old_data, new_data),
                                                    combine_adjacent=True,
                                                    color_map={"+": "#008000", "-": "#FF4433"},
                                                    elem_id="difference")
                    
                    promote_btn = gr.Button(value="Promote", icon="images/promote.png",
                                            variant="primary", size='sm', elem_id="promote_btn")

                    # Call the promotion function when the button is clicked
                    promote_btn.click(gf.promotion, [key1, new_data1, message1], [status3])

        # Add a button to trigger the changes
        sync_btn = gr.Button(value="Sync",icon="images/sync.png",variant="primary")
        sync_btn.click(process_changes)
        


### Screenshot

![image](https://github.com/gradio-app/gradio/assets/85235476/42b8b165-3add-4d61-b4cc-49182d3f29ea)


### Logs

```shell
Inside CDC
Traceback (most recent call last):
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gradio\routes.py", line 534, in predict       
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gradio\blocks.py", line 1550, in process_api  
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\anyio\to_thread.py", line 33, in run_sync     
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\004O2F744\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gradio\utils.py", line 661, in wrapper        
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Antro\Projects\DTR_Admin_UI\gradio_app.py", line 101, in process_changes
    promote_btn.click(gf.promotion, [key1, new_data1, message1], [status3])
    ^^^^^^^^^^^^^^^^^
AttributeError: 'Button' object has no attribute 'click'
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 3.50.0
gradio_client version: 0.6.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.100.0
ffmpy: 0.3.1
gradio-client==0.6.1 is not installed.
httpx: 0.25.0
huggingface-hub: 0.16.4
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.25.2
orjson: 3.9.9
packaging: 23.1
pandas: 1.5.3
pillow: 10.0.0
pydantic: 2.1.1
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.7.1
uvicorn: 0.23.1
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.25.0
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @AntroSafin ! Can you please share a minimal version of the entire app we can use to debug?

**Comment by AntroSafin** [comment]
Hi @freddyaboulton ! Here is the minimal version of the entire app I am mounting with fastapi and using gradio as ui.
```from difflib import Differ
from fastapi import FastAPI
import gradio as gr
import uvicorn

app = FastAPI()

def CDC():
    print("Inside CDC")

    # Define constant dictionaries as examples
    main_data = {
        'item1': {'data': 'value1'},
        'item2': {'data': 'value2'},
        'item3': {'data': 'value3'},
    }

    test_data = {
        'item1': {'data': 'value1'},
        'item2': {'data': 'modified_value2'},
        'item4': {'data': 'value4'},
    }

    # Initialize lists to track changes
    changes = []

    for key in main_data:
        if key in test_data:
            main_data_value = main_data[key]['data']
            test_data_value = test_data[key]['data']
            if main_data_value != test_data_value:
                changes.append((key, "update", main_data_value, test_data_value))
        else:
            changes.append((key, "delete", main_data[key]['data'], ""))

    for key in test_data:
        if key not in main_data:
            changes.append((key, "add", "", test_data[key]['data']))

    return changes

# Function to see the difference between two texts
def diff_texts(text1, text2):
    d = Differ()
    comparison_result = [
        (token[2:], token[0] if token[0] != " " else None)
        for token in d.compare(text1, text2)
    ]
    return comparison_result

# Function to promote service
def promotion():
    return "Promoted Successfully"

# UI Design
# Promote Service
with gr.Blocks() as demo:
    with gr.Tab("Promote Service") as tab2:

        #To display the status of promotion
        status3 = gr.Textbox(label="Status",lines=1)

        gr.Markdown("## Changes between Main and Test Branch")
        #Header
        with gr.Row(elem_id="wrapper"):
            gr.Markdown("### Service ID",elem_id="key")
            gr.Markdown("### Message",elem_id="message")
            gr.Markdown("### Changes",elem_id="difference")
            gr.Markdown("### Promotion Button",elem_id="promote_btn") 
               
        def process_changes():
            changed_data = CDC()
            for change in changed_data:
                key, message, old_data, new_data = change
                key1 = gr.Textbox(value=key,visible=False)
                message1 = gr.Textbox(value=message,visible=False)
                new_data1 = gr.Textbox(value=new_data,visible=False)
                with gr.Row(elem_id="wrapper"):
                    key2 = gr.Markdown(key, elem_id="key")
                    message2 = gr.Markdown(message, elem_id="message")
                    difference = gr.HighlightedText(label="",
                                                    value=diff_texts(old_data, new_data),
                                                    combine_adjacent=True,
                                                    color_map={"+": "#008000", "-": "#FF4433"},
                                                    elem_id="difference")
                    
                    promote_btn = gr.Button(value="Promote", icon="images/promote.png",
                                            variant="primary", size='sm', elem_id="promote_btn")

                    # Call the promotion function when the button is clicked
                    promote_btn.click(promotion, outputs=[status3])

        # Add a button to trigger the changes
        sync_btn = gr.Button(value="Sync",icon="images/sync.png",variant="primary")
        sync_btn.click(process_changes)

app = gr.mount_gradio_app(app, demo, path="/ui")

# Run the application
if __name__ == "__main__":
    uvicorn.run("sample_app:app", host='localhost', port=8080, reload=True)

**Comment by AntroSafin** [comment]
Hi @dawoodkhan82 Can you please solve the issue or find any alternatives please?
I have been working on this for 3 days no solution found.

**Comment by abidlabs** [comment]
Hi @AntroSafin I looked into this, but the example you have provided is not self-contained. I get `NameError: name 'Differ' is not defined` when running it

Furthermore, does the error only happen when mounting the Gradio app inside a FastAPI app, or even in the standalone Gradio app?

**Comment by AntroSafin** [comment]
Hi! @abidlabs I missed the import that's why NameError. Yeah it shows error in both standalone and mounting.
Could you rectify this error or any workaround for this secenerio?

```
from difflib import Differ
from fastapi import FastAPI
import gradio as gr
import uvicorn

app = FastAPI()

def CDC():
    print("Inside CDC")

    # Define constant dictionaries as examples
    main_data = {
        'item1': {'data': 'value1'},
        'item2': {'data': 'value2'},
        'item3': {'data': 'value3'},
    }

    test_data = {
        'item1': {'data': 'value1'},
        'item2': {'data': 'modified_value2'},
        'item4': {'data': 'value4'},
    }

    # Initialize lists to track changes
    changes = []

    for key in main_data:
        if key in test_data:
            main_data_value = main_data[key]['data']
            test_data_value = test_data[key]['data']
            if main_data_value != test_data_value:
                changes.append((key, "update", main_data_value, test_data_value))
        else:
            changes.append((key, "delete", main_data[key]['data'], ""))

    for key in test_data:
        if key not in main_data:
            changes.append((key, "add", "", test_data[key]['data']))

    return changes

# Function to see the difference between two texts
def diff_texts(text1, text2):
    d = Differ()
    comparison_result = [
        (token[2:], token[0] if token[0] != " " else None)
        for token in d.compare(text1, text2)
    ]
    return comparison_result



# Function to promote service
def promotion(key,message,data):
    return f"Promoted the {key} with the {message} Successfully.\n {data}"

# UI Design
# Promote Service
with gr.Blocks() as demo:
    with gr.Tab("Promote Service") as tab2:

        #To display the status of promotion
        status3 = gr.Textbox(label="Status",lines=1)

        gr.Markdown("## Changes between Main and Test Branch")
        #Header
        with gr.Row(elem_id="wrapper"):
            gr.Markdown("### Service ID",elem_id="key")
            gr.Markdown("### Message",elem_id="message")
            gr.Markdown("### Changes",elem_id="difference")
            gr.Markdown("### Promotion Button",elem_id="promote_btn") 
        
        def process_changes():
            changed_data = CDC()
            for change in changed_data:
                key, message, old_data, new_data = change
                key1 = gr.Textbox(value=key, visible=False)
                message1 = gr.Textbox(value=message, visible=False)
                new_data1 = gr.Textbox(value=new_data, visible=False)
                with gr.Row():
                    key2 = gr.Markdown(key, elem_id="key")
                    message2 = gr.Markdown(message, elem_id="message")
                    difference = gr.HighlightedText(label="",
                                                    value=diff_texts(old_data, new_data),
                                                    combine_adjacent=True,
                                                    color_map={"+": "#008000", "-": "#FF4433"},
                                                    elem_id="difference")
                    promote_btn = gr.Button(value="Promote", icon="images/promote.png",
                                            variant="primary", size='sm', elem_id="promote_btn")
                    promote_btn.click(promotion, inputs=[key1, new_data1, message1], outputs=[status3])

        sync = gr.Button(value="Sync", icon="images/sync.png", variant="primary", size='sm', elem_id="sync")
        sync.click(process_changes)

app = gr.mount_gradio_app(app, demo, path="/ui")

# Run the application
if __name__ == "__main__":
    uvicorn.run("sample_app:app", host='localhost', port=8080, reload=True)
```

**Comment by abidlabs** [comment]
The problem is that you're trying to call this method:

```py
        def process_changes():
            changed_data = CDC()
            for change in changed_data:
                key, message, old_data, new_data = change
                key1 = gr.Textbox(value=key, visible=False)
                message1 = gr.Textbox(value=message, visible=False)
                new_data1 = gr.Textbox(value=new_data, visible=False)
                with gr.Row():
                    key2 = gr.Markdown(key, elem_id="key")
                    message2 = gr.Markdown(message, elem_id="message")
                    difference = gr.HighlightedText(label="",
                                                    value=diff_texts(old_data, new_data),
                                                    combine_adjacent=True,
                                                    color_map={"+": "#008000", "-": "#FF4433"},
                                                    elem_id="difference")
                    promote_btn = gr.Button(value="Promote", icon="images/promote.png",
                                            variant="primary", size='sm', elem_id="promote_btn")
                    promote_btn.click(promotion, inputs=[key1, new_data1, message1], outputs=[status3])
```

dynamically every time `sync.click()` is called. Gradio doesn't support rendering components dynamically like this. The closest workaround I would suggest is to hide or make components visible based on `sync.click()`. This is discussed in various GH issues, such as here: https://github.com/gradio-app/gradio/issues/2066#issuecomment-1224515753

We are considering how to add stateful / dynamic rendering to Gradio apps here: https://github.com/gradio-app/gradio/issues/2570 if you'd like to share this example there
