### ISSUE TITLE
Button.click() raises an Exception when first click

### ISSUE THREAD

**Issue by ObsisMc** [gradio-app/gradio#6370]
### Describe the bug

My gradio version is 4.1.2 and the testing code is from the section "Hello, Blocks" of the [doc](https://www.gradio.app/guides/quickstart#hello-blocks) 

```python
import gradio as gr


def greet(name):
    return "Hello " + name + "!"


with gr.Blocks() as demo:
    name = gr.Textbox(label="Name")
    output = gr.Textbox(label="Output Box")
    greet_btn = gr.Button("Greet")
    greet_btn.click(fn=greet, inputs=name, outputs=output, api_name="greet")

demo.launch()
```

After clicking the button for the first time, an exception appears:
```text
Traceback (most recent call last):
  File "/home/zrh/Software/Environment/anaconda/envs/test/lib/python3.10/site-packages/gradio/queueing.py", line 427, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/zrh/Software/Environment/anaconda/envs/test/lib/python3.10/site-packages/gradio/route_utils.py", line 231, in call_process_api
    with utils.MatplotlibBackendMananger():
  File "/home/zrh/Software/Environment/anaconda/envs/test/lib/python3.10/site-packages/gradio/utils.py", line 847, in __exit__
    matplotlib.use(self._original_backend)
  File "/home/zrh/Software/Environment/anaconda/envs/test/lib/python3.10/site-packages/matplotlib/__init__.py", line 1249, in use
    plt.switch_backend(name)
  File "/home/zrh/Software/Environment/anaconda/envs/test/lib/python3.10/site-packages/matplotlib/pyplot.py", line 343, in switch_backend
    canvas_class = module.FigureCanvas
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'
Traceback (most recent call last):
  File "/home/zrh/Software/Environment/anaconda/envs/test/lib/python3.10/site-packages/gradio/queueing.py", line 427, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/zrh/Software/Environment/anaconda/envs/test/lib/python3.10/site-packages/gradio/route_utils.py", line 231, in call_process_api
    with utils.MatplotlibBackendMananger():
  File "/home/zrh/Software/Environment/anaconda/envs/test/lib/python3.10/site-packages/gradio/utils.py", line 847, in __exit__
    matplotlib.use(self._original_backend)
  File "/home/zrh/Software/Environment/anaconda/envs/test/lib/python3.10/site-packages/matplotlib/__init__.py", line 1249, in use
    plt.switch_backend(name)
  File "/home/zrh/Software/Environment/anaconda/envs/test/lib/python3.10/site-packages/matplotlib/pyplot.py", line 343, in switch_backend
    canvas_class = module.FigureCanvas
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zrh/Software/Environment/anaconda/envs/test/lib/python3.10/site-packages/gradio/queueing.py", line 472, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/home/zrh/Software/Environment/anaconda/envs/test/lib/python3.10/site-packages/gradio/queueing.py", line 436, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Run the code in version of 4.1.2

```python
import gradio as gr


def greet(name):
    return "Hello " + name + "!"


with gr.Blocks() as demo:
    name = gr.Textbox(label="Name")
    output = gr.Textbox(label="Output Box")
    greet_btn = gr.Button("Greet")
    greet_btn.click(fn=greet, inputs=name, outputs=output, api_name="greet")

demo.launch()
```

### System Info

```shell
gradio==4.1.2
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Interesting. It does not happen to me. What version of matplotlib do you have? I have 3.7.2.

**Comment by ObsisMc** [comment]
My matplotlib version is over 3.8 and after changing it to 3.7.2, it works. Thanks.
