### ISSUE TITLE
cannot build custom audio component

### ISSUE THREAD

**Issue by caffeinism** [gradio-app/gradio#6373]
### Describe the bug

Creating and building cc using the audio template fails.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
$ gradio cc create MyAudio --template=Audio
│ 🏗  Creating component MyAudio in directory myaudio                                                                           
│ 📠 Starting from template Audio                                                                                              
│ 🐍 Created backend code                                                                                                      
│ 🎨 Created frontend code                                                                                                     
│ 👷 Installing python... (/usr/local/bin/pip install -e myaudio[dev])                                                         
│ ✅ Python install succeeded!                                                                                                 
│ 👷 Installing javascript... (/usr/bin/npm install)                                                                           
│ ✅ NPM install succeeded!                                                                                                    
```

```
$ gradio cc build
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ 📦 Building package in myaudio                                                                                         
│ 🎨 Building frontend                                                                                                   
│ 🟥 Build failed!                                                                                                       
│ 5:06:30 AM  hmr is enabled but compilerOptions.dev is false, forcing it to true                                        
│ 5:06:30 AM  options.hot is enabled but does not work on production build, forcing it to false                          
│ 5:06:30 AM  you are building for production but compilerOptions.dev is true, forcing it to false                       
│ : Rollup failed to resolve import "wavesurfer.js/dist/plugins/record.js" from                                          
│ "/src/myaudio/frontend/recorder/AudioRecorder.svelte".                                                  
│ This is most likely unintended because it can break your application at runtime.                                       
│ If you do want to externalize this module explicitly add it to                                                         
│ `build.rollupOptions.external`                                                                                         
│ file:///usr/local/lib/python3.11/site-packages/gradio/node/dev/files/index-897f432e.js:75585                           
│                     throw new Error(`: Rollup failed to resolve import "${exporter}" from "${id}".\n` +                
│                           ^                                                                                            
│                                                                                                                        
│ Error: : Rollup failed to resolve import "wavesurfer.js/dist/plugins/record.js" from                                   
│ "/src/myaudio/frontend/recorder/AudioRecorder.svelte".                                                  
│ This is most likely unintended because it can break your application at runtime.                                       
│ If you do want to externalize this module explicitly add it to                                                         
│ `build.rollupOptions.external`                                                                                         
│     at viteWarn (file:///usr/local/lib/python3.11/site-packages/gradio/node/dev/files/index-897f432e.js:75585:27)      
│     at onRollupWarning (file:///usr/local/lib/python3.11/site-packages/gradio/node/dev/files/index-897f432e.js:75617:9)
│     at onwarn (file:///usr/local/lib/python3.11/site-packages/gradio/node/dev/files/index-897f432e.js:75345:13)        
│     at file:///usr/local/lib/python3.11/site-packages/gradio/node/dev/files/index-897f432e.js:24486:13                 
│     at Object.logger  (file:///usr/local/lib/python3.11/site-packages/gradio/node/dev/files/index-897f432e.js:26160:9) 
│     at ModuleLoader.handleInvalidResolvedId                                                                            
│ (file:///usr/local/lib/python3.11/site-packages/gradio/node/dev/files/index-897f432e.js:25072:26)                      
│     at file:///usr/local/lib/python3.11/site-packages/gradio/node/dev/files/index-897f432e.js:25032:26 {               
│   watchFiles: [                                                                                                        
│     '/src/myaudio/frontend/index.ts',                                                                   
│     '/src/myaudio/frontend/package.json',                                                               
│     '/src/myaudio/frontend/Index.svelte',                                                               
│     '/src/myaudio/frontend/static/StaticAudio.svelte',                                                  
│     '/src/myaudio/frontend/interactive/InteractiveAudio.svelte',                                        
│     '/src/myaudio/frontend/player/AudioPlayer.svelte',                                                  
│     '/src/myaudio/frontend/Example.svelte',                                                             
│     '/src/myaudio/frontend/static/StaticAudio.svelte?svelte&type=style&lang.css',                       
│     '/src/myaudio/frontend/interactive/InteractiveAudio.svelte?svelte&type=style&lang.css',             
│     '/src/myaudio/frontend/recorder/AudioRecorder.svelte',                                              
│     '/src/myaudio/frontend/streaming/StreamAudio.svelte',                                               
│     '/src/myaudio/frontend/player/AudioPlayer.svelte?svelte&type=style&lang.css',                       
│     '/src/myaudio/frontend/shared/utils.ts',                                                            
│     '/src/myaudio/frontend/shared/WaveformControls.svelte',                                             
│     '/src/myaudio/frontend/node_modules/@gradio/wasm/svelte/index.ts',                                  
│     '/src/myaudio/frontend/Example.svelte?svelte&type=style&lang.css',                                  
│     '/src/myaudio/frontend/recorder/AudioRecorder.svelte?svelte&type=style&lang.css',                  
│     '/src/myaudio/frontend/shared/WaveformRecordControls.svelte'                                        
│   ]                                                                                                                    
│ }                                                                                                                      
│                                                                                                                        
│ Node.js v20.8.1                                                                                                        
│ vite v0.0.0 building for production...                                                                                         
│ transforming...                                                                                                                
│ ✓ 11 modules transformed.                                                                                                      
│ ✓ built in 1.91s                                                                                                               
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.2.0
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 22.1.0
altair: 4.2.2
fastapi: 0.104.1
ffmpy: 0.3.0
gradio-client==0.7.0 is not installed.
httpx: 0.24.0
huggingface-hub: 0.18.0
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.2
matplotlib: 3.7.1
numpy: 1.24.2
orjson: 3.8.10
packaging: 23.1
pandas: 2.0.0
pillow: 9.5.0
pydantic: 2.4.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.28.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.21.1
websockets: 11.0.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.9.2
httpx: 0.24.0
huggingface-hub: 0.18.0
packaging: 23.1
requests: 2.28.2
typing-extensions: 4.8.0
websockets: 11.0.1



I also tested on gradio==4.0.0 and gradio==4.1.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @caffeinism for sharing this feedback. @pngwn @freddyaboulton do you have any ideas of what could be causing this error?

**Comment by freddyaboulton** [comment]
Sorry - looks like wavesurfer is not in the package.json of the component!
