### ISSUE TITLE
ERROR:    Exception in ASGI application  , ClientDisconnect() starlette.requests.ClientDisconnect on 4.2.0

### ISSUE THREAD

**Issue by abdulnim** [gradio-app/gradio#6393]
### Describe the bug

The below code works fine on my local PC but when I run the demo on my Linux server and access it via a sharable link it only works with very small audios. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import os
import gradio as gr
from pydub import AudioSegment
# os.environ["CUDA_VISIBLE_DEVICES"]="0"


#==================== Transcripbe Method is Here  ====================
def transcribe_whisperx(audio_file, prompt=None):
    
    if audio_file is None:
      print("There is no audio to transribe")
      return "The Audio is Not Loaded Yet"
    else:
      print("Audio found : "+audio_file)
  
    audio = AudioSegment.from_file(audio_file)  
    length_in_milliseconds = len(audio)
    length_in_seconds = length_in_milliseconds / 1000
    print("Audio recieved, Length in seconds:", length_in_seconds)
    return f"Audio length is seconds : {length_in_seconds}"
    

#==================== Gradio Demo ====================    
demo = gr.Blocks()
with demo:
    with gr.Row():
        with gr.Column():
            # Inputs
            audio_file = gr.Audio(type="filepath")
            text_prompts = gr.Textbox(label="Initial Prompts(Optionsl)")
            
        with gr.Column():
            # Outpus
            text_transcript = gr.Textbox(label="Transcript Before cleaning")
        
    # Button
    button_transcribe = gr.Button("Transcribe Audio")
    button_transcribe.click(fn=transcribe_whisperx, inputs=[audio_file, text_prompts], outputs= [text_transcript])
    
demo.queue()
demo.launch(allowed_paths=["."], share=True)
```

### Logs

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/gradio/routes.py", line 756, in upload_file
    form = await multipart_parser.parse()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/gradio/route_utils.py", line 492, in parse
    async for chunk in self.stream:
  File "/home/dp/miniconda3/envs/abdul-310/lib/python3.11/site-packages/starlette/requests.py", line 230, in stream
    raise ClientDisconnect()
starlette.requests.ClientDisconnect
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.2.0
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.103.2
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.0
huggingface-hub: 0.17.3
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.1
matplotlib: 3.8.0
numpy: 1.25.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.1
pillow: 10.0.1
pydantic: 2.1.1
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.7.1
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.25.0
huggingface-hub: 0.17.3
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hmm I'm not able to reproduce the issue, even with the audio file that you shared with me:

<img width="952" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/209c9138-9e11-495c-8ebd-db1508a52032">

**Comment by abidlabs** [comment]
Here's a working Colab notebook: https://colab.research.google.com/drive/1BkXnapMEZKgbHBrkSF52s2sO-J3XV-X7?usp=sharing

Can you see if this works for you?

**Comment by abdulnim** [comment]
@abidlabs As I mentioned the issue arose when I was running the gradio demo on my Linux server which I access through ssh.
the server has some security that might be restricting the use but then why did it work on small audio and not on audio greater than 20 mb.

**Comment by abidlabs** [comment]
Hi @abdulnim I'm having a hard time thinking of any reason why small audio files would work but large ones wouldn't. It might depend on internet connectivity of your server, but its a bit hard to tell since it seems specific to your server as we're not able to reproduce locally or on Colab

**Comment by abdulnim** [comment]
@abidlabs I am going to create my own FastAPI server for the time being, but if you would like to see the issue on my setup let me know.

**Comment by abdulnim** [comment]
@abidlabs to be more specific the error arises when uploading the file to gradio. the upload progress bar stops after a while and i then see the error. 

![image](https://github.com/gradio-app/gradio/assets/113373212/d872afb1-a9b3-4cfd-97eb-6cd2a46ac204)

**Comment by abdulnim** [comment]
the problem might be specific to my server security

**Comment by abidlabs** [comment]
Yes, if its specific to your server, we won't be able to do much to help unfortunately. One other possibility you could try is setting up your own share server and seeing if that allows you to create share links that work: https://github.com/huggingface/frp/

**Comment by justinzyw** [comment]
@abidlabs  I just encountered the same problem. Have you found a solution please?

**Comment by oliverkinch** [comment]
I’m encountering this issue when uploading a file exactly after 60 seconds, which suggests there might be a hardcoded timeout somewhere. However, I haven’t been able to find any reference to such a timeout in the code or any configuration option to change it.

**Comment by freddyaboulton** [comment]
Yes browsers time out requests that last more than 60 seconds
