### ISSUE TITLE
gradio_client fails most of the time with JSONDecodeError (on a Chat interface that provides results in streaming)

### ISSUE THREAD

**Issue by Jeronymous** [gradio-app/gradio#6494]
### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Describe the bug

I have an app that is using `gradio.ChatInterface` on a function that is a generator (`Iterator[str]`).
It is hosted on HuggingFace and very similar to  [Llama-2-7b-chat](https://huggingface.co/spaces/huggingface-projects/llama-2-7b-chat/blob/main/app.py#L44)

When I want to request this API with `gradio_client` using the code  given by HuggingFace to do so, I have the following failure (with my Chat, not with Llama Chat).

A difference between Llama Chat and my Chat is the version of `gradio` in the docker container:
* Llama2 is using `gradio==3.48.0`
* I am using more recent `gradio==4.4.1`

Another difference who may explains why it fail with my chat and not Llama2 is that the last token might be generated super quickly (without inference step in a neural network, just a last normalization step).

Error message:
```
Traceback (most recent call last):
  File "/home/jlouradour/.local/lib/python3.10/site-packages/gradio_client/client.py", line 305, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
  File "/home/jlouradour/.local/lib/python3.10/site-packages/gradio_client/client.py", line 1456, in result
    return super().result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jlouradour/.local/lib/python3.10/site-packages/gradio_client/client.py", line 869, in _inner
    predictions = _predict(*data)
  File "/home/jlouradour/.local/lib/python3.10/site-packages/gradio_client/client.py", line 894, in _predict
    result = utils.synchronize_async(self._sse_fn, data, hash_data, helper)
  File "/home/jlouradour/.local/lib/python3.10/site-packages/gradio_client/utils.py", line 666, in synchronize_async
    return fsspec.asyn.sync(fsspec.asyn.get_loop(), func, *args, **kwargs)  # type: ignore
  File "/home/jlouradour/.local/lib/python3.10/site-packages/fsspec/asyn.py", line 99, in sync
    raise return_result
  File "/home/jlouradour/.local/lib/python3.10/site-packages/fsspec/asyn.py", line 54, in _runner
    result[0] = await coro
  File "/home/jlouradour/.local/lib/python3.10/site-packages/gradio_client/client.py", line 1075, in _sse_fn
    return await utils.get_pred_from_sse(
  File "/home/jlouradour/.local/lib/python3.10/site-packages/gradio_client/utils.py", line 341, in get_pred_from_sse
    return task.result()
  File "/home/jlouradour/.local/lib/python3.10/site-packages/gradio_client/utils.py", line 373, in stream_sse
    resp = json.loads(line[5:])
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 3 column 1 (char 296)
```

### Reproduction

```
from gradio_client import Client

client = Client("https://openllm-france-claire-chat-0-1.hf.space/--replicas/fxl4n/")
result = client.predict(
    "Hello Olivier!",	# str  in 'Message' Textbox component
    False,
    "Hello",	# str  in 'System prompt' Textbox component
    200,	# int | float (numeric value between 1 and 2048) in 'Max new tokens' Slider component
    1.0,	# int | float (numeric value between 0.1 and 4.0) in 'Temperature' Slider component
    0.99,	# int | float (numeric value between 0.05 and 1.0) in 'Top-p (nucleus sampling)' Slider component
    10,	# int | float (numeric value between 1 and 1000) in 'Top-k' Slider component
    1,	# int | float (numeric value between 1.0 and 2.0) in 'Repetition penalty' Slider component
    api_name="/chat"
)
print(f">{result}<")
```
Then it fails (most of the time) with the error I copy-pasted above.

For exact entrypoint, see https://huggingface.co/spaces/OpenLLM-France/Claire-Chat-0.1 (click on "Use via API" at the bottom)

### Additional hints

By looking more closely at what's happening around those lines (that are causing the failure)
```
File "/home/jlouradour/.local/lib/python3.10/site-packages/gradio_client/utils.py", line 373, in stream_sse
    resp = json.loads(line[5:])
```
https://github.com/gradio-app/gradio/blob/2780d067f9f801016c0254de679b56794859abed/client/python/gradio_client/utils.py#L372-L373
I see that it happens at the end of the generation, with a `line` that contains 2 data dictionaries. Namely those very similar ones:
```
data: {"msg": "process_generating", "output": {"data": ["Bonjour Olivier, tu as l'air bien r\u00e9veill\u00e9 ce matin. Tu veux que je te pr\u00e9pare tes petits-d\u00e9j.\n", null], "is_generating": true, "duration": 0.0005967617034912109, "average_duration": 0.10917224349525474}, "success": true}

data: {"msg": "process_completed", "output": {"data": ["Bonjour Olivier, tu as l'air bien r\u00e9veill\u00e9 ce matin. Tu veux que je te pr\u00e9pare tes petits-d\u00e9j.\n", null], "is_generating": true, "duration": 0.0005967617034912109, "average_duration": 0.10917224349525474}, "success": true}

```
So json is failing to parse that. It should focus on the last line. For example with that code, that I'm using locally as a workaround:
```
json_line = line[5:]
while "data:" in json_line:
   line_json = line_json[line_json.index("data:")+5:]
resp = json.loads(line_json)
```
I can open a PR if one think that's the relevant fix.

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.4.1
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 22.1.0
altair: 4.2.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.13.3
huggingface-hub: 0.17.3
importlib-resources: 5.10.0
jinja2: 3.1.2
markupsafe: 2.1.2
matplotlib: 3.7.0
numpy: 1.23.5
orjson: 3.8.0
packaging: 23.0
pandas: 1.5.3
pillow: 9.4.0
pydantic: 2.5.1
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.28.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.21.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.1.0
httpx: 0.13.3
huggingface-hub: 0.17.3
packaging: 23.0
requests: 2.28.2
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by matrac73** [comment]
@Jeronymous I faced the same issue.

I believe it is due to a synchronisation issue : The async API call did not receive correct format information.
- Either too short string : 

> erating": true, "duration": 0.00024437904357910156, "average_duration": 0.0198629213831911}, "succ

- Either too long string : 

> data: {"msg": "process_generating", "output": {"data": [[["Mathieu Ract", "Mathieu Ract est un dipl\u00f4m\u00e9 de CentraleSup\u00e9lec et \u00e9tudie actuellement \u00e0 l'ESSEC Business School. Il a \u00e9galement un profil Facebook et est un gestionnaire de syst\u00e8mes d'information. (sources: https://fr.linkedin.com/in/mathieu-ract, https://facebook.com/mathieu.ract/, http://lgi.centrales"]]], "is_generating": true, "duration": 0.00023555755615234375, "average_duration": 0.019897434820686996}, "success": true}\n\ndata: {"msg": "process_generating", "output": {"data": [[["Mathieu Ract", "Mathieu Ract est un dipl\u00f4m\u00e9 de CentraleSup\u00e9lec et \u00e9tudie actuellement \u00e0 l'ESSEC Business School. Il a \u00e9galement un profil Facebook et est un gestionnaire de syst\u00e8mes d'information. (sources: https://fr.linkedin.com/in/mathieu-ract, https://facebook.com/mathieu.ract/, http://lgi.centrales"]]], "is_generating": true, "duration": 0.00023555755615234375, "average_duration": 0.019897434820686996}, "success": true}

To fix it, I modified the async function : stream_sse (line 358) in the file :

**/anaconda3/envs/meta-agent_env/lib/python3.9/site-packages/gradio_client/utils.py**

by forcing the API to wait to have a "correct" output and by adding a condition to pass as follow :

```
async def stream_sse(
    client: httpx.AsyncClient,
    data: dict,
    hash_data: dict,
    helper: Communicator,
    sse_url: str,
    sse_data_url: str,
    cookies: dict[str, str] | None = None,
) -> dict[str, Any]:
    try:
        ### MODIF MATHIEU ############################################################
        stream_is_valid = False
        while not stream_is_valid:
        ##############################################################################
            async with client.stream(
                "GET", sse_url, params=hash_data, cookies=cookies
            ) as response:
                async for line in response.aiter_text():
                    ### MODIF MATHIEU ############################################################
                    debut = 'data: {"msg"'
                    fin = '}'
                    debut_index = line.find(debut)
                    fin_index = line.rfind(fin)
                    if debut_index != -1 and fin_index != -1:
                        line = line[debut_index:fin_index + len(fin)]
                    else :
                        line = " "
                    if line[0] == "d" and line[-1] == "}":
                        stream_is_valid = True
                    else:
                        continue
                    ##############################################################################
                    if line.startswith("data:"):
                        resp = json.loads(line[5:])
                        with helper.lock:
                            has_progress = "progress_data" in resp
                            status_update = StatusUpdate(
                                code=Status.msg_to_status(resp["msg"]),
                                queue_size=resp.get("queue_size"),
                                rank=resp.get("rank", None),
                                success=resp.get("success"),
                                time=datetime.now(),
                                eta=resp.get("rank_eta"),
                                progress_data=ProgressUnit.from_msg(resp["progress_data"])
                                if has_progress
                                else None,
                            )
                            output = resp.get("output", {}).get("data", [])
                            if output and status_update.code != Status.FINISHED:
                                try:
                                    result = helper.prediction_processor(*output)
                                except Exception as e:
                                    result = [e]
                                helper.job.outputs.append(result)
                            helper.job.latest_status = status_update

                        if resp["msg"] == "queue_full":
                            raise QueueError("Queue is full! Please try again.")
                        elif resp["msg"] == "send_data":
                            event_id = resp["event_id"]
                            helper.event_id = event_id
                            req = await client.post(
                                sse_data_url,
                                json={"event_id": event_id, **data, **hash_data},
                                cookies=cookies,
                            )
                            req.raise_for_status()
                        elif resp["msg"] == "process_completed":
                            return resp["output"]
                    else:
                        raise ValueError(f"Unexpected message: {line}")
            raise ValueError("Did not receive process_completed message.")
    except asyncio.CancelledError:
        raise
```
