### ISSUE TITLE
[HTTPError('403 Client Error: Forbidden for url: http://localhost:7860/file=9fb99820-154e-414f-a0f7-33044a791888/139962059673072/228')]

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#6592]
### Describe the bug

With gradio>=4 I get this error when streaming with same code that works in all prior gradios 3, up to last gradio 3.50.2

Related: https://github.com/gradio-app/gradio/issues/6282

However, I'm not really using the streaming of audio.     Just the presence of audio even as None in the yield breaks streaming.  Even further, I'm not even (in first example below) getting response from that api with the audio return.  It's totally separate click and still fails in same way just because some other API has audio in return.  So it's not something one can easily work-around.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

server:

```
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.Button("Clear")

    speech_bot = gr.Audio(value=None,
                          label="Generated Bot Speech",
                          type="numpy",
                          streaming=True,
                          interactive=False,
                          show_label=True,
                          autoplay=True,
                          elem_id='bot_audio',
                          visible=True)

    def user(user_message, history):
        return "", history + [[user_message, None]]

    def bot(history):
        bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
        history[-1][1] = ""
        for character in bot_message:
            history[-1][1] += character
            time.sleep(0.05)
            yield history, None

    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        fn=bot, inputs=chatbot, outputs=[chatbot, speech_bot],
    )
    clear.click(lambda: None, None, chatbot, api_name='bot')

demo.queue()
demo.launch()

```

client:
```
import time
from gradio_client import Client

client = Client('http://localhost:7860')

args = [[['Who are you?', None]]]
job = client.submit(*tuple(args), api_name='/bot')
res1 = ''
while not job.done():
    outputs_list = job.communicator.job.outputs
    if outputs_list:
        res = job.communicator.job.outputs[-1]
        try:
            res1 = res[0][-1][-1]
        except:
            print(res, flush=True)
            raise
        print(res1)
    time.sleep(0.1)
full_outputs = job.outputs()
print('job.outputs: %s' % str(full_outputs))

```

Run the server, then run client, and get:

```
/data/conda/h2ogpt/bin/python3.10 /home/jon/h2ogpt/testchatstreamstate_client.py 
Console output is saving to: /home/jon/h2ogpt/pycharm.log
Loaded as API: http://localhost:7860/ ✔
Traceback (most recent call last):
  File "/home/jon/h2ogpt/testchatstreamstate_client.py", line 14, in <module>
    res1 = res[0][-1][-1]
TypeError: 'HTTPError' object is not subscriptable
[HTTPError('403 Client Error: Forbidden for url: http://localhost:7860/file=b75690b6-99e5-4df8-ae9f-715936f2ff49/140414092446976/4')]

```

Note that I'm not even using "bot" as the return from the bot click via API, even just the clear button without any return does this.

For the api on the bot call (more normal) one has server code:

```
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.Button("Clear")

    speech_bot = gr.Audio(value=None,
                          label="Generated Bot Speech",
                          type="numpy",
                          streaming=True,
                          interactive=False,
                          show_label=True,
                          autoplay=True,
                          elem_id='bot_audio',
                          visible=True)

    def user(user_message, history):
        return "", history + [[user_message, None]]

    def bot(history):
        bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
        history[-1][1] = ""
        for character in bot_message:
            history[-1][1] += character
            time.sleep(0.05)
            yield history, None

    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        fn=bot, inputs=chatbot, outputs=[chatbot, speech_bot], api_name='bot',
    )
    clear.click(lambda: None, None, chatbot, api_name='clear')

demo.queue()
demo.launch()
```

And that does same thing with original client code.
```
/data/conda/h2ogpt/bin/python3.10 /home/jon/h2ogpt/testchatstreamstate_client.py 
Console output is saving to: /home/jon/h2ogpt/pycharm.log
Loaded as API: http://localhost:7860/ ✔
Traceback (most recent call last):
  File "/home/jon/h2ogpt/testchatstreamstate_client.py", line 14, in <module>
    res1 = res[0][-1][-1]
TypeError: 'HTTPError' object is not subscriptable
[HTTPError('403 Client Error: Forbidden for url: http://localhost:7860/file=8a9eae00-44ed-4e65-acc9-0cce0264df6e/139786845344752/4')]
```

I just though it  might be relevant since has nothing to do with api call on audio.  Just presence of *some* api with audio return is bad enough.

### System Info

```shell
gradio==4.7.1
gradio_client==0.7.0

Unable to use gradio 4
```

### Severity

Blocking usage of gradio

**Comment by pseudotensor** [comment]
A related error I hit that worked perfectly in gradio <=3 is the below.  I don't have MRE for this.

```
"""
Traceback (most recent call last):
  File "/data/conda/h2ogpt/lib/python3.10/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/jon/h2ogpt/src/utils.py", line 963, in _traced_func
    return func(*args, **kwargs)
  File "/home/jon/h2ogpt/tests/test_client_calls.py", line 3898, in test_client1_tts
    res = client.predict(str(dict(kwargs)), api_name='/submit_nochat_api')
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/client.py", line 305, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/client.py", line 1456, in result
    return super().result(timeout=timeout)
  File "/data/conda/h2ogpt/lib/python3.10/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/data/conda/h2ogpt/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/data/conda/h2ogpt/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/client.py", line 869, in _inner
    predictions = _predict(*data)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/client.py", line 894, in _predict
    result = utils.synchronize_async(self._sse_fn, data, hash_data, helper)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/utils.py", line 664, in synchronize_async
    return fsspec.asyn.sync(fsspec.asyn.get_loop(), func, *args, **kwargs)  # type: ignore
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/client.py", line 1075, in _sse_fn
    return await utils.get_pred_from_sse(
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/utils.py", line 341, in get_pred_from_sse
    return task.result()
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/utils.py", line 377, in stream_sse
    code=Status.msg_to_status(resp["msg"]),
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/utils.py", line 128, in msg_to_status
    return {
KeyError: 'heartbeat'
"""


```

**Comment by pseudotensor** [comment]
Even non-streaming via client fails if audio is set to streaming:

server:
```
import gradio as gr
import random
import time

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.Button("Clear")

    speech_bot = gr.Audio(streaming=True)

    def user(user_message, history):
        return "", history + [[user_message, None]]

    def bot(history):
        bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
        history[-1][1] = ""
        for character in bot_message:
            history[-1][1] += character
            time.sleep(0.05)
            #yield history
            yield history, b''

    msg.submit(user, [msg, chatbot], [msg, chatbot], queue=False).then(
        fn=bot, inputs=chatbot, outputs=[chatbot, speech_bot], api_name='bot',
        #fn=bot, inputs=chatbot, outputs=chatbot, api_name='bot',
    )
    clear.click(lambda: None, None, chatbot, api_name='clear')

demo.queue()
demo.launch()

```


client:

```
import time
from gradio_client import Client

client = Client('http://localhost:7860')

args = [[['Who are you?', None]]]
res = client.predict(*tuple(args), api_name='/bot')
print(res)

```

gives:

```
/data/conda/h2ogpt/bin/python3.10 /home/jon/h2ogpt/testchat_nostream_client.py 
Console output is saving to: /home/jon/h2ogpt/pycharm.log
Loaded as API: http://localhost:7860/ ✔
Traceback (most recent call last):
  File "/home/jon/h2ogpt/testchat_nostream_client.py", line 7, in <module>
    res = client.predict(*tuple(args), api_name='/bot')
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/client.py", line 305, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/client.py", line 1456, in result
    return super().result(timeout=timeout)
  File "/data/conda/h2ogpt/lib/python3.10/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/data/conda/h2ogpt/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/data/conda/h2ogpt/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/client.py", line 870, in _inner
    predictions = self.process_predictions(*predictions)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/client.py", line 1068, in process_predictions
    predictions = self.deserialize(*predictions)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/client.py", line 1064, in deserialize
    data_: list[Any] = utils.traverse(data_, self.download_file, utils.is_file_obj)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/utils.py", line 782, in traverse
    new_obj.append(traverse(item, func, is_root))
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/utils.py", line 773, in traverse
    return func(json_obj)
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/client.py", line 826, in <lambda>
    self.download_file = lambda d: self._download_file(
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/client.py", line 1049, in _download_file
    file_name = utils.download_file(
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/gradio_client/utils.py", line 435, in download_file
    r.raise_for_status()
  File "/data/conda/h2ogpt/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://localhost:7860/file=79d0a1b6-558d-4524-9a5f-8c1b38a0dcdf/140554439314208/4

Process finished with exit code 1

```

**Comment by pseudotensor** [comment]
Even when setting serialize=False with the streaming=False for the audio component, the audio component gives back a file path, which is bad/wrong.

```
import time
from gradio_client import Client

client = Client('http://localhost:7860', serialize=True)

args = [[['Who are you?', None]]]
res = client.predict(*tuple(args), api_name='/bot')
print(res)
```

gives:
```
/data/conda/h2ogpt/bin/python3.10 /home/jon/h2ogpt/testchat_nostream_client.py 
Console output is saving to: /home/jon/h2ogpt/pycharm.log
Loaded as API: http://localhost:7860/ ✔
([['Who are you?', "I'm very hungry"]], '/tmp/gradio/da39a3ee5e6b4b0d3255bfef95601890afd80709/audio')

```

**Comment by pseudotensor** [comment]
In gradio 3 this is what serialize=False gives:

```
(/data/conda/gradio3) jon@pseudotensor:~/h2ogpt$ python testchat_nostream_client.py
Loaded as API: http://localhost:7860/ ✔
([['Who are you?', 'How are you?']], {'name': '/tmp/gradio/da39a3ee5e6b4b0d3255bfef95601890afd80709/audio', 'data': None, 'is_file': True, 'orig_name': 'audio'})
```

serialize=True gives:

```
(/data/conda/gradio3) jon@pseudotensor:~/h2ogpt$ python testchat_nostream_client.py
Loaded as API: http://localhost:7860/ ✔
Traceback (most recent call last):
  File "/home/jon/h2ogpt/testchat_nostream_client.py", line 7, in <module>
    res = client.predict(*tuple(args), api_name='/bot')
  File "/data/conda/gradio3/lib/python3.10/site-packages/gradio_client/client.py", line 292, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
  File "/data/conda/gradio3/lib/python3.10/site-packages/gradio_client/client.py", line 1131, in result
    return super().result(timeout=timeout)
  File "/data/conda/gradio3/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/data/conda/gradio3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/data/conda/gradio3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/conda/gradio3/lib/python3.10/site-packages/gradio_client/client.py", line 797, in _inner
    data = self.serialize(*data)
  File "/data/conda/gradio3/lib/python3.10/site-packages/gradio_client/client.py", line 968, in serialize
    o = tuple([s.serialize(d) for s, d in zip(self.serializers, data)])
  File "/data/conda/gradio3/lib/python3.10/site-packages/gradio_client/client.py", line 968, in <listcomp>
    o = tuple([s.serialize(d) for s, d in zip(self.serializers, data)])
  File "/data/conda/gradio3/lib/python3.10/site-packages/gradio_client/serializing.py", line 469, in serialize
    return utils.file_to_json(Path(load_dir) / x)
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'list'
```
