### ISSUE TITLE
Passing a FileExplorer without selection to a gradio.Button.click gives an error

### ISSUE THREAD

**Issue by v-chabaux** [gradio-app/gradio#6606]
### Describe the bug

I pass a FileExplorer with nothing select to a Button.click() and i have an error. So i have no way to check if its empty or not.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
def get_values(a):
  pass

output_folder = gr.FileExplorer(root="/content/drive/",glob="**/", file_count="single", value = ["/content/drive/MyDrive/"])
scrap_button.click(get_values, inputs=output_folder, outputs=None)

```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1520, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1303, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/file_explorer.py", line 116, in preprocess
    return self._safe_join(payload.root[0])
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1520, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1303, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/file_explorer.py", line 116, in preprocess
    return self._safe_join(payload.root[0])
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: [1;36m4.7[0m.[1;36m1[0m
gradio_client version: [1;36m0.7[0m.[1;36m0[0m

------------------------------------------------x
gradio dependencies in your environment:

aiofiles: [1;36m23.2[0m.[1;36m1[0m
altair: [1;36m4.2[0m.[1;36m2[0m
fastapi: [1;36m0.104[0m.[1;36m1[0m
ffmpy: [1;36m0.3[0m.[1;36m1[0m
gradio-[33mclient[0m==[1;36m0.7[0m.[1;36m0[0m is not installed.
httpx: [1;36m0.25[0m.[1;36m2[0m
huggingface-hub: [1;36m0.19[0m.[1;36m4[0m
importlib-resources: [1;36m6.1[0m.[1;36m1[0m
jinja2: [1;36m3.1[0m.[1;36m2[0m
markupsafe: [1;36m2.1[0m.[1;36m3[0m
matplotlib: [1;36m3.7[0m.[1;36m1[0m
numpy: [1;36m1.23[0m.[1;36m5[0m
orjson: [1;36m3.9[0m.[1;36m10[0m
packaging: [1;36m23.2[0m
pandas: [1;36m1.5[0m.[1;36m3[0m
pillow: [1;36m9.4[0m.[1;36m0[0m
pydantic: [1;36m2.5[0m.[1;36m2[0m
pydub: [1;36m0.25[0m.[1;36m1[0m
python-multipart: [1;36m0.0[0m.[1;36m6[0m
pyyaml: [1;36m6.0[0m.[1;36m1[0m
requests: [1;36m2.31[0m.[1;36m0[0m
semantic-version: [1;36m2.10[0m.[1;36m0[0m
[33mtomlkit[0m==[1;36m0.12[0m.[1;36m0[0m is not installed.
typer: [1;36m0.9[0m.[1;36m0[0m
typing-extensions: [1;36m4.8[0m.[1;36m0[0m
uvicorn: [1;36m0.24[0m.[1;36m0.[0mpost1
authlib; extra == [32m'oauth'[0m is not installed.
itsdangerous; extra == [32m'oauth'[0m is not installed.


gradio_client dependencies in your environment:

fsspec: [1;36m2023.6[0m.[1;36m0[0m
httpx: [1;36m0.25[0m.[1;36m2[0m
huggingface-hub: [1;36m0.19[0m.[1;36m4[0m
packaging: [1;36m23.2[0m
requests: [1;36m2.31[0m.[1;36m0[0m
typing-extensions: [1;36m4.8[0m.[1;36m0[0m
websockets: [1;36m11.0[0m.[1;36m3[0m
```

### Severity

Blocking usage of gradio

**Comment by v-chabaux** [comment]
Ok, the issue is caused by `file_count="single"`, all is working good with `file_count="multiple"`. But i need to forced a single choice.

**Comment by v-chabaux** [comment]
Quick fix on line 116 in file_explorer.py

```
if len(payload.root) == 0
    return None
else:
    return self._safe_join(payload.root[0])
```

**Comment by v-chabaux** [comment]
#6607
