### ISSUE TITLE
API image preprocessing data error

### ISSUE THREAD

**Issue by maxirozay** [gradio-app/gradio#6623]
### Describe the bug

When sending images to the API with the JS client there is an error while preprocessing data.
The UI generated by gradio work fine.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

backend
```
import gradio as gr

def test(image):
  return image

gr.Interface(
  fn=test,
  inputs=["image"],
  outputs="image",
).launch()
```
frontend
````
const app = await client('http://127.0.0.1:7860/')
app.predict('/predict', [
  image // can be a blob from canvas.toBlob(..., 'image/jpeg', 1) or a file from file input
])


### Screenshot

_No response_

### Logs

```shell
Traceback (most recent call last):
  File "/home/test/venv/lib/python3.11/site-packages/gradio/queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/venv/lib/python3.11/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1520, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1300, in preprocess_data
    inputs_cached = block.data_model(**inputs_cached)  # type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/venv/lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for FileData
path
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/test/venv/lib/python3.11/site-packages/gradio/queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/venv/lib/python3.11/site-packages/gradio/queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
```


### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.7.1
gradio_client version: 0.7.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.0 is not installed.
httpx: 0.25.2
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.3
pillow: 10.1.0
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.2
huggingface-hub: 0.19.4
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```


### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @maxirozay ! I believe the latest js client is only compatible with gradio versions 4.x. cc @pngwn to confirm.

**Comment by maxirozay** [comment]
Hi @freddyaboulton ! Yes that's what I was trying to do. I had the python version 4.7.1 with the js 0.8.2 or 0.7.0 and it didn't work. I tried again just now to confirm with the python 4.8.0 and js 0.8.2 and 0.7.1 and still I get the error `Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing`. Just to clarify this error is only when I try to upload images.

So for now I'm using gradio python 3.41 with the js client 0.6 which works fine.

**Comment by freddyaboulton** [comment]
Thanks @maxirozay !
