### ISSUE TITLE
Exception: 'File' object has no attribute 'name'

### ISSUE THREAD

**Issue by Bikatr7** [gradio-app/gradio#6681]
### Describe the bug

Exception: 'File' object has no attribute 'name'

Cannot read file contents or access name variable.

Tried searching documentation found this or old code that doesn't seem to work.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
## third-party libraries
import gradio as gr

##-------------------start-of-KudasaiGUI---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

class KudasaiGUI:

    """
    
    Kudasai is a class that contains the GUI for Kudasai.

    """

##-------------------start-of-build_gui()---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    def build_gui(self):

        """

        Builds the GUI.

        """

        with gr.Blocks() as self.gui:

            ## tab 1
            with gr.Tab("Kudasai") as self.kudasai_tab:

                ## tab 2
                with gr.Tab("Preprocessing and Translation") as self.model_tab:
                    with gr.Row():

                        ## input files
                        with gr.Column():
                            self.input_txt_file = gr.File(label='TXT file with Japanese Text', file_count='single', file_types=['.txt'], type='filepath')
                            self.input_json_file = gr.File(label='Replacements JSON file', file_count='single', file_types=['.json'], type='filepath')

                            ## mode selection 
                            with gr.Row():
                                self.mode_selection = gr.Dropdown(label='Mode', choices=['Preprocess only', 'AutoTL with OpenAI', 'AutoTL with DeepL'], value='Preprocess only', type='index', interactive=True)

                            with gr.Row():
                                self.api_key_input = gr.Textbox(label='API Key (Not needed for preprocess)', lines=1, show_label=True, interactive=True, type='password')

                            ## run and clear buttons
                            with gr.Row():
                                self.run_button = gr.Button('Run')
                                self.clear_button = gr.Button('Clear', variant='stop')

                        ## output fields
                        with gr.Column():
                            self.preprocess_output_field  = gr.Textbox(label='Preprocessed text', lines=33, show_label=True, interactive=False, show_copy_button=True)

                            with gr.Row():
                                self.save_to_file_one = gr.Button('Save As')
                            
                        with gr.Column():
                            self.translation_output_field = gr.Textbox(label='Translated Text', lines=33, show_label=True, interactive=False, show_copy_button=True)

                            with gr.Row():
                                self.save_to_file_two = gr.Button('Save As')
                ## tab 3
                with gr.Tab("Logging") as self.results_tab:
                    with gr.Row():
                        self.preprocessing_results = gr.Textbox(label='Preprocessing Results', lines=10, interactive=False)

                    with gr.Row():
                        self.debug_log = gr.Textbox(label='Debug Log', lines=10, interactive=False)

                    with gr.Row():
                        self.error_log = gr.Textbox(label='Error Log', lines=10, interactive=False)


            def run_button_click():
            
                if(self.input_txt_file is not None):

                    txt_file_path = self.input_txt_file.name ## type: ignore

                    with open(txt_file_path, "r", encoding='utf-8') as file:
                        text = file.read()

                    self.preprocess_output_field.value = text

            
            self.run_button.click(fn=run_button_click)

##-------------------start-of-launch()---------------------------------------------------------------------------------------------------------------------------------------------------------------------------                

    def launch(self):

        """

        Launches the GUI.

        """

        self.build_gui()
        self.gui.queue().launch(inbrowser=True, show_error=True)

##-------------------start-of-main()---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

if(__name__ == '__main__'):
    kudasai_gui = KudasaiGUI()
    kudasai_gui.launch()


```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/102974491/adfbc0bf-c61a-4441-af68-00180e9cd780)

### Logs

```shell
PS C:\Users\Tetra\Documents\Repositories\Kudasai> & C:/Users/Tetra/AppData/Local/Programs/Python/Python311/python.exe c:/Users/Tetra/Documents/Repositories/Kudasai/unfinished_gui.py
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1522, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\Tetra\Documents\Repositories\Kudasai\unfinished_gui.py", line 78, in run_button_click
    txt_file_path = self.input_txt_file.name ## type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'File' object has no attribute 'name'
Traceback (most recent call last):
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1522, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "c:\Users\Tetra\Documents\Repositories\Kudasai\unfinished_gui.py", line 78, in run_button_click
    txt_file_path = self.input_txt_file.name ## type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'File' object has no attribute 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tetra\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: 'File' object has no attribute 'name'
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.8.0
gradio_client version: 0.7.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.1 is not installed.
httpx: 0.25.1
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.2
matplotlib: 3.8.2
numpy: 1.24.2
orjson: 3.9.10
packaging: 23.0
pandas: 2.1.0
pillow: 9.5.0
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.1
huggingface-hub: 0.19.4
packaging: 23.0
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @Bikatr7 ! This is expected, the `gr.File` component has no `name` property. It looks like you're trying to get the current uploaded filepath but you didn't pass the file component as an input. I suggest you read the guide on creating events: https://www.gradio.app/guides/blocks-and-event-listeners#blocks-structure. The UI looks awesome though.

**Comment by Bikatr7** [comment]
Hi, I have since figured it out.

See:
https://github.com/Bikatr7/Kudasai/blob/main/unfinished_gui.py

If you're curious.

Otherwise, I appreciate the help. Have a nice day.

**Comment by freddyaboulton** [comment]
You too!

**Comment by Redias** [comment]
Hello, I have the similar question with sample code: the upload file object have no attribute 'name' so i cant get the filepath...

The code is 
```python
from zipfile import ZipFile

import gradio as gr


def zip_to_json(file_obj):
    files = []
    with ZipFile(file_obj.name) as zfile:
        for zinfo in zfile.infolist():
            files.append(
                {
                    "name": zinfo.filename,
                    "file_size": zinfo.file_size,
                    "compressed_size": zinfo.compress_size,
                }
            )
    return files


demo = gr.Interface(zip_to_json, "file", "json")

if __name__ == "__main__":
    demo.launch()
```

And the code errored while run `file_obj.name` ...

my env is 

`gradio == 4.12.0` and `gradio_client == 0.8.0` on `windows 11`

Any tips are very helpful !!
