### ISSUE TITLE
Python client: `KeyError: 'heartbeat'` after 15 seconds, even server is on local machine

### ISSUE THREAD

**Issue by garywill** [gradio-app/gradio#6682]
### Describe the bug

Write a simple Gradio server and use a simple gradio_client in Python on local machine, which just  transfer audio file simply, with a 30 seconds delay.

The client always report error after 15 seconds.

I've encountered some spaces on HF which need more than 15 seconds to do procudure. They're unusable currently because of this bug

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

server.py
```python
#!/usr/bin/python3.11

import sys, os

import gradio as gr
import time

def inference(audiofile):
    time.sleep(30)
    print('now server done. send result to client')
    return audiofile


gr.Interface(
    inference, 
    gr.Audio(type="numpy", label="Song"),
    [gr.Audio(type="filepath", label="Vocals")],
    ).launch()
```

client
```python
#!/usr/bin/python3.11

from gradio_client import Client

client = Client("http://127.0.0.1:7860")

result = client.predict('/tmp/ii.wav')
print(result)
```

### Logs

```shell
$ ./client.py
Loaded as API: http://127.0.0.1:7860/ ✔
Traceback (most recent call last):
File "/tmp/gr-audio-bug/./client.py", line 27, in <module>
result = client.predict('/tmp/ii.wav')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/username/.local/lib/python3.11/site-packages/gradio_client/client.py", line 305, in predict
return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/username/.local/lib/python3.11/site-packages/gradio_client/client.py", line 1457, in result
return super().result(timeout=timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 456, in result
return self.__get_result()
^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 401, in __get_result
raise self._exception
File "/usr/lib64/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/username/.local/lib/python3.11/site-packages/gradio_client/client.py", line 869, in _inner
predictions = _predict(*data)
^^^^^^^^^^^^^^^
File "/home/username/.local/lib/python3.11/site-packages/gradio_client/client.py", line 894, in _predict
result = utils.synchronize_async(self._sse_fn, data, hash_data, helper)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/username/.local/lib/python3.11/site-packages/gradio_client/utils.py", line 678, in synchronize_async
return fsspec.asyn.sync(fsspec.asyn.get_loop(), func, *args, **kwargs)  # type: ignore
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/fsspec/asyn.py", line 103, in sync
raise return_result
File "/usr/lib/python3.11/site-packages/fsspec/asyn.py", line 56, in _runner
result[0] = await coro
^^^^^^^^^^
File "/home/username/.local/lib/python3.11/site-packages/gradio_client/client.py", line 1075, in _sse_fn
return await utils.get_pred_from_sse(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/username/.local/lib/python3.11/site-packages/gradio_client/utils.py", line 349, in get_pred_from_sse
return task.result()
^^^^^^^^^^^^^
File "/home/username/.local/lib/python3.11/site-packages/gradio_client/utils.py", line 390, in stream_sse
code=Status.msg_to_status(resp["msg"]),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/username/.local/lib/python3.11/site-packages/gradio_client/utils.py", line 128, in msg_to_status
return {
^
KeyError: 'heartbeat'
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.8.0
gradio_client version: 0.7.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.1.0
altair: 5.1.2
fastapi: 0.104.1
ffmpy: 0.3.1
gradio-client==0.7.1 is not installed.
httpx: 0.24.1
huggingface-hub: 0.16.4
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.1
numpy: 1.25.2
orjson: 3.8.10
packaging: 23.1
pandas: 2.1.3
pillow: 10.1.0
pydantic: 2.4.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.9.2
httpx: 0.24.1
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by garywill** [comment]
I've also tested old version of Gradio. 
```
gradio version: 3.50.2
gradio_client version: 0.6.1
```
Old Gradio doesn't have such bug
