### ISSUE TITLE
file upload failed using gradio_client.Client, when there is an auth

### ISSUE THREAD

**Issue by ArslanTu** [gradio-app/gradio#6717]
### Describe the bug

Setup an gradio server with auth, uploading file through browser works fine. But it didn't work for gradio_client.
When I remove the auth setting, gradio_client works fine, too.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

`server.py`

```python
import gradio as gr

def func(file_obj) -> str:
    return file_obj.name

def auth(username: str, passwd: str) -> bool:
    return username == "tom" and passwd == "123"

def main():
    demo = gr.Interface(
        fn=func,
        inputs=[gr.File()],
        outputs=[gr.Textbox()],
    )
    demo.queue(api_open=True)
    demo.launch(
        server_port=9600,
        auth=auth,
    )

if __name__ == "__main__":
    main()
```

`test_upload.py`

```python
from gradio_client import Client
from time import sleep

client = Client("http://127.0.0.1:9600", auth=("tom", "123"))
job = client.submit(
    "./test_file.json",
    api_name="/predict",
)
while not job.done():
    sleep(1)
print(job.result())
```

### Logs

```shell
Traceback (most recent call last):
  File "/home/tom/anaconda3/envs/referqa/lib/python3.10/site-packages/gradio/queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/tom/anaconda3/envs/referqa/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/tom/anaconda3/envs/referqa/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/tom/anaconda3/envs/referqa/lib/python3.10/site-packages/gradio/blocks.py", line 1300, in preprocess_data
    inputs_cached = block.data_model(**inputs_cached)  # type: ignore
TypeError: gradio.data_classes.FileData() argument after ** must be a mapping, not str
Traceback (most recent call last):
  File "/home/tom/anaconda3/envs/referqa/lib/python3.10/site-packages/gradio/queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/tom/anaconda3/envs/referqa/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/tom/anaconda3/envs/referqa/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/tom/anaconda3/envs/referqa/lib/python3.10/site-packages/gradio/blocks.py", line 1300, in preprocess_data
    inputs_cached = block.data_model(**inputs_cached)  # type: ignore
TypeError: gradio.data_classes.FileData() argument after ** must be a mapping, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tom/anaconda3/envs/referqa/lib/python3.10/site-packages/gradio/queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/home/tom/anaconda3/envs/referqa/lib/python3.10/site-packages/gradio/queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
```
```


### System Info

```shell
gradio==4.8.0
gradio_client==0.7.1
```
```


### Severity

Blocking usage of gradio

**Comment by ArslanTu** [comment]
The error log above came from gradio, an this is the gradio_client error log:

```
Traceback (most recent call last):
  File "/home/tom/test_upload.py", line 11, in <module>
    print(job.result())
  File "/home/tom/code/gradio_client-0.7.1.1/gradio_client/client.py", line 1457, in result
    return super().result(timeout=timeout)
  File "/home/tom/anaconda3/envs/test/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/tom/anaconda3/envs/test/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/tom/anaconda3/envs/test/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tom/code/gradio_client-0.7.1.1/gradio_client/client.py", line 869, in _inner
    predictions = _predict(*data)
  File "/home/tom/code/gradio_client-0.7.1.1/gradio_client/client.py", line 896, in _predict
    raise ValueError(result["error"])
ValueError: None
```

**Comment by freddyaboulton** [comment]
Thanks for reporting @ArslanTu !

**Comment by samiragmeta** [comment]
Is there a workaround for the time being? That would really help. I am running into the same problem.

**Comment by pseudotensor** [comment]
Yes, getting same thing.  Auth via API does not work for file uploads.

**Comment by abidlabs** [comment]
Its on my roadmap (probably next couple of weeks)
