### ISSUE TITLE
Audio file only gets stored on localhost

### ISSUE THREAD

**Issue by Tejaswgupta** [gradio-app/gradio#6727]
### Describe the bug

I'm using the given barebones code to transcribe a given audio. It works perfectly fine on my local machine. I ran the same on my azure vm and it didn't work which I found out was due to `http` connection. Using self ssl signing(`ssl_keyfile='key.pem',ssl_certfile='cert.pem', ssl_verify=False,`) I am using `https` now ` but the audio returned from the component is None.

File uploads work fine.

Local logs:
```
This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
AUDIO PATH IS /private/var/folders/0j/21fzxng91r38ykg9vr3bykgc0000gn/T/gradio/33f8c1a50fa64a727773d389befa70401dd256ae/audio.wav
```

Server https logs:
```
This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Traceback (most recent call last):
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/gradio/queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/gradio/blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/gradio/blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/gradio/utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
  File "/home/azureuser/distil/audio.py", line 24, in transcribe
    print('AUDIO PATH IS '+audio)
TypeError: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/gradio/queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/gradio/blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/gradio/blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/gradio/utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
  File "/home/azureuser/distil/audio.py", line 24, in transcribe
    print('AUDIO PATH IS '+audio)
TypeError: can only concatenate str (not "NoneType") to str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/gradio/queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/home/azureuser/miniconda3/envs/whisper/lib/python3.10/site-packages/gradio/queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
def transcribe(audio: str):
    print('AUDIO PATH IS '+audio)
    if not audio.endswith('.wav'):
        output_file = 'output.wav'
        sample_rate = 16000
        ffmpeg.input(audio).output(output_file, ar=sample_rate).run()
        audio = output_file

    return pipe(audio)["text"]


demo = gr.Interface(
    transcribe,
    gr.Audio(type="filepath"),
    "text",
)
```

### System Info

```shell
VM:
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 3.46.0
gradio_client version: 0.5.3

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.1.1
fastapi: 0.100.1
ffmpy: 0.3.1
gradio-client==0.5.3 is not installed.
httpx: 0.24.1
huggingface-hub: 0.19.4
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.3
numpy: 1.24.4
orjson: 3.9.7
packaging: 23.2
pandas: 2.0.3
pillow: 10.1.0
pydantic: 1.10.13
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 5.3.1
requests: 2.31.0
semantic-version: 2.10.0
typing-extensions: 4.8.0
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.24.1
huggingface-hub: 0.19.4
packaging: 23.2
requests: 2.31.0
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @Tejaswgupta can you please check if the latest version of `gradio` (4.21) still has this issue? We made some fixes to how Gradio works behind proxies which may have solved this issue

**Comment by abidlabs** [comment]
I'm going to close this for now for lack of followup. But can reopen if indeed this remains an issue.
