### ISSUE TITLE
Gallery not catching all events

### ISSUE THREAD

**Issue by AlUlkesh** [gradio-app/gradio#6763]
### Describe the bug

When I use the right cursor key to go to the next image in a Gallery, I expect each image between the start and the end of my cursor movement to be selected, so I can do some processing on it.

This works when I hit the cursor key slowly, but when I hit it fast or keep it pressed, only some of the selections are returned to the python code.

In the example shown in the attached video I go from image 0 to image 32, and only these are returned to python:
```
1
2
6
10
16
22
27
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr
from PIL import Image, ImageDraw, ImageFont
import os
import tempfile

temp = tempfile.gettempdir()

width, height = 200, 200
pics = []

def make_images(num):
    global pics
    font_size = min(width, height) // 2
    font = ImageFont.truetype("arial", font_size)
    for i in range(0, num - 1):
        img = Image.new('RGB', (width, height), color = (255, 255, 255))
        d = ImageDraw.Draw(img)
        text = str(i)
        bbox = d.textbbox((0,0), text, font=font)
        textwidth, textheight = bbox[2] - bbox[0], bbox[3] - bbox[1]
        position = ((width-textwidth)/2,(height-textheight)/2)
        d.text(position, text, fill=(0,0,0), font=font)
        image_path = os.path.join(temp, f'gallerytest_{i:02}.jpg')
        img.save(image_path)
        pics.append(image_path)

make_images(40)

def sel(evt: gr.SelectData):
    index = evt.index
    print(index)
    return index
    
with gr.Blocks() as demo:
    with gr.Row():
        gallery_sel = gr.Textbox(label="Selected Index", interactive=False)
    with gr.Row():
        gallery = gr.Gallery(pics, show_label=False, columns=8, selected_index=0)
        gallery.select(fn=sel, inputs=[], outputs=[gallery_sel])

demo.launch(debug=True)
```

### Screenshot

https://github.com/gradio-app/gradio/assets/99896447/e794d0ea-a475-4ac7-a94e-78bbc5ab1ba0

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.8.0
gradio_client version: 0.7.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.1.0
altair: 5.0.1
fastapi: 0.105.0
ffmpy: 0.3.0
gradio-client==0.7.1 is not installed.
httpx: 0.24.1
huggingface-hub: 0.15.1
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.1
numpy: 1.24.3
orjson: 3.9.0
packaging: 23.1
pandas: 2.0.2
pillow: 9.5.0
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.31.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.22.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.5.0
httpx: 0.24.1
huggingface-hub: 0.15.1
packaging: 23.1
requests: 2.31.0
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by Franky-in** [comment]
![1702436774032](https://github.com/gradio-app/gradio/assets/22075922/d52c3e2d-655a-4aaa-b658-bfda0cc42769)
Find img is a dict, not a tuple as expected.

**Comment by abidlabs** [comment]
Hi @AlUlkesh the reason you're observing this behavior is that events in `gr.Blocks()` do not re-fire while the same event is already pending. In other words, while the `sel()` function is running, it will not run again when the `.select()` event in `Gallery` is triggered. This is usually a sensible default to avoid users triggering too many events. But in your case, it is preventing the events from being fired continuously.

Luckily, we provide a way to override this behavior, and that is to set the `trigger_mode` parameter to `"multiple"` instead of the default, which is `"once"`. 

Here's an adapted version of your code with the change:

```py
import gradio as gr
from PIL import Image, ImageDraw, ImageFont
import os
import tempfile

temp = tempfile.gettempdir()

width, height = 200, 200
pics = []

def make_images(num):
    global pics
    font_size = min(width, height) // 2
    for i in range(0, num - 1):
        img = Image.new('RGB', (width, height), color = (255, 255, 255))
        d = ImageDraw.Draw(img)
        text = str(i)
        bbox = d.textbbox((0,0), text)
        textwidth, textheight = bbox[2] - bbox[0], bbox[3] - bbox[1]
        position = ((width-textwidth)/2,(height-textheight)/2)
        d.text(position, text, fill=(0,0,0))
        image_path = os.path.join(temp, f'gallerytest_{i:02}.jpg')
        img.save(image_path)
        pics.append(image_path)

make_images(40)

def sel(evt: gr.SelectData):
    index = evt.index
    print(index)
    return index
    
with gr.Blocks() as demo:
    with gr.Row():
        gallery_sel = gr.Textbox(label="Selected Index", interactive=False)
    with gr.Row():
        gallery = gr.Gallery(pics, show_label=False, columns=8, selected_index=0)
        gallery.select(fn=sel, inputs=[], outputs=[gallery_sel], trigger_mode="multiple")

demo.launch()
```

**Comment by AlUlkesh** [comment]
Hi @abidlabs, Thanks so much for the quick reply. I just tried this out. With this change, unfortunately it seems to only catch the first 3 triggers. After right-arrowing a while more it then runs into an error:

```
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
1
2
3
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "c:\tools\python\gradio\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "c:\tools\python\gradio\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "c:\tools\python\gradio\venv\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "c:\tools\python\gradio\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\tools\python\gradio\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "c:\tools\python\gradio\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "c:\tools\python\gradio\venv\lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "c:\tools\python\gradio\venv\lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "c:\tools\python\gradio\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "c:\tools\python\gradio\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "c:\tools\python\gradio\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "c:\tools\python\gradio\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "c:\tools\python\gradio\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "c:\tools\python\gradio\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "c:\tools\python\gradio\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "c:\tools\python\gradio\venv\lib\site-packages\fastapi\routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "c:\tools\python\gradio\venv\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "c:\tools\python\gradio\venv\lib\site-packages\gradio\routes.py", line 668, in queue_data
    blocks._queue.attach_data(body)
  File "c:\tools\python\gradio\venv\lib\site-packages\gradio\queueing.py", line 161, in attach_data
    raise ValueError("Event not found", event_id)
ValueError: ('Event not found', 'a6e3865f5da7423ab3ca46ce97ab1680')

```

**Comment by abidlabs** [comment]
Hi @AlUlkesh please upgrade to gradio 4.9.0, we just pushed a fix for this bug. Thank you!

**Comment by AlUlkesh** [comment]
Hi @abidlabs, It works perfectly now! Thanks so much.
