### ISSUE TITLE
Example from official Quickstart works unreliably on AWS EC2 instance via Remote SSH

### ISSUE THREAD

**Issue by VigneshHexo** [gradio-app/gradio#6817]
### Describe the bug

I am working on replicating the results of the [Quickstart document](https://www.gradio.app/guides/quickstart). Specifically, I am working on this example 

```python
import numpy as np
import gradio as gr

def sepia(input_img):
    sepia_filter = np.array([
        [0.393, 0.769, 0.189], 
        [0.349, 0.686, 0.168], 
        [0.272, 0.534, 0.131]
    ])
    sepia_img = input_img.dot(sepia_filter.T)
    sepia_img /= sepia_img.max()
    return sepia_img

demo = gr.Interface(sepia, gr.Image(), "image")
demo.launch()

```

I am working remotely on AWS EC2 instance via Remote SSH. When I upload a very small image ~80KB as well, sometime the code works, other times it doesn't work and throws the following error

```ssh
Traceback (most recent call last):
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/tmp/ipykernel_20415/3646091551.py", line 20, in sepia_official
    sepia_img = input_img.dot(sepia_filter.T)
AttributeError: 'NoneType' object has no attribute 'dot'
Traceback (most recent call last):
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/tmp/ipykernel_20415/3646091551.py", line 20, in sepia_official
    sepia_img = input_img.dot(sepia_filter.T)
AttributeError: 'NoneType' object has no attribute 'dot'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/queueing.py", line 497, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import numpy as np
import gradio as gr

def sepia(input_img):
    sepia_filter = np.array([
        [0.393, 0.769, 0.189], 
        [0.349, 0.686, 0.168], 
        [0.272, 0.534, 0.131]
    ])
    sepia_img = input_img.dot(sepia_filter.T)
    sepia_img /= sepia_img.max()
    return sepia_img

demo = gr.Interface(sepia, gr.Image(), "image")
demo.launch()
```

I have attached the image here: ![coke_whitebg](https://github.com/gradio-app/gradio/assets/125873180/fba0728f-1ebf-441d-8f19-e34a6234deea)

### Screenshot

Traceback (most recent call last):
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/tmp/ipykernel_20415/3646091551.py", line 20, in sepia_official
    sepia_img = input_img.dot(sepia_filter.T)
AttributeError: 'NoneType' object has no attribute 'dot'
Traceback (most recent call last):
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/tmp/ipykernel_20415/3646091551.py", line 20, in sepia_official
    sepia_img = input_img.dot(sepia_filter.T)
AttributeError: 'NoneType' object has no attribute 'dot'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/queueing.py", line 497, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/opt/conda/envs/pesu/lib/python3.10/site-packages/gradio/queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.10.0
gradio_client version: 0.7.3

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.105.0
ffmpy: 0.3.1
gradio-client==0.7.3 is not installed.
httpx: 0.25.2
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.4
pillow: 10.1.0
pydantic: 2.5.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.24.0.post1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.25.2
huggingface-hub: 0.19.4
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by appleman521** [comment]
Output ./results/e3a2584b-ef1d-4780-bcb0-337f0ecb0567\appleman0326_A_Chinese_little_girl_about_8_or_9_years_old_with__3d8d7f3a-2352-42d5-8539-e0fc7b57cad0##audio_enhanced.mp4 same as Input #0 - exiting
FFmpeg cannot edit existing files in-place.
Error opening output file ./results/e3a2584b-ef1d-4780-bcb0-337f0ecb0567\appleman0326_A_Chinese_little_girl_about_8_or_9_years_old_with__3d8d7f3a-2352-42d5-8539-e0fc7b57cad0##audio_enhanced.mp4.
Error opening output files: Invalid argument
Traceback (most recent call last):
  File "E:\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\SadTalker\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1542, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1427, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "E:\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 226, in postprocess
    processed_files = (self._format_video(y), None)
  File "E:\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 295, in _format_video
    ff.run()
  File "E:\SadTalker\venv\lib\site-packages\ffmpy.py", line 113, in run
    raise FFRuntimeError(self.cmd, self.process.returncode, out[0], out[1])
ffmpy.FFRuntimeError: `ffmpeg -y -i ./results/e3a2584b-ef1d-4780-bcb0-337f0ecb0567\appleman0326_A_Chinese_little_girl_about_8_or_9_years_old_with__3d8d7f3a-2352-42d5-8539-e0fc7b57cad0##audio_enhanced.mp4 ./results/e3a2584b-ef1d-4780-bcb0-337f0ecb0567\appleman0326_A_Chinese_little_girl_about_8_or_9_years_old_with__3d8d7f3a-2352-42d5-8539-e0fc7b57cad0##audio_enhanced.mp4` exited with status 4294967274

STDOUT:


STDERR:

Traceback (most recent call last):
  File "E:\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\SadTalker\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1542, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\SadTalker\venv\lib\site-packages\gradio\blocks.py", line 1427, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "E:\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 226, in postprocess
    processed_files = (self._format_video(y), None)
  File "E:\SadTalker\venv\lib\site-packages\gradio\components\video.py", line 295, in _format_video
    ff.run()
  File "E:\SadTalker\venv\lib\site-packages\ffmpy.py", line 113, in run
    raise FFRuntimeError(self.cmd, self.process.returncode, out[0], out[1])
ffmpy.FFRuntimeError: `ffmpeg -y -i ./results/e3a2584b-ef1d-4780-bcb0-337f0ecb0567\appleman0326_A_Chinese_little_girl_about_8_or_9_years_old_with__3d8d7f3a-2352-42d5-8539-e0fc7b57cad0##audio_enhanced.mp4 ./results/e3a2584b-ef1d-4780-bcb0-337f0ecb0567\appleman0326_A_Chinese_little_girl_about_8_or_9_years_old_with__3d8d7f3a-2352-42d5-8539-e0fc7b57cad0##audio_enhanced.mp4` exited with status 4294967274

STDOUT:


STDERR:


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 497, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "E:\SadTalker\venv\lib\site-packages\gradio\queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None


After installing SadTalker, an error occurs when producing the first video. What is the reason? How to exclude? Thanks！

**Comment by abidlabs** [comment]
Hi @matthew-stewart-satalia can you please check if the latest version of `gradio` (4.21) still has this issue? We made some fixes to how Gradio works behind proxies which may have solved this issue

**Comment by VigneshHexo** [comment]
Hi @abidlabs,
Thank you very much for your message. We have finished this project and moved on to the next one. I'll raise an issue if this recurs while I use Gradio next time. Thank you very much.

**Comment by abidlabs** [comment]
Ok thanks! I’ll close for now
