### ISSUE TITLE
"ValueError: None" when attempting prediction with gradio_client

### ISSUE THREAD

**Issue by butterflyhigh** [gradio-app/gradio#6832]
### Describe the bug

When attempting prediction on a Huggingface space, I get the following output:

```
True ## (from me checking that the file exists)
Loaded as API: https://resembleai-resemble-enhance.hf.space/--replicas/jpfzk/ ✔
Traceback (most recent call last):
  File "C:\Users\EShad\Documents\defoko_denoiser\main.py", line 9, in <module>
    res = client.predict(DEFOKO_DIR + "_chi_che_cho_chu_chi_chi.wav", "Midpoint", 64, 0.5, api_name="/predict")
  File "C:\Users\EShad\Documents\defoko_denoiser\venv\lib\site-packages\gradio_client\client.py", line 392, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
  File "C:\Users\EShad\Documents\defoko_denoiser\venv\lib\site-packages\gradio_client\client.py", line 1565, in result
    return super().result(timeout=timeout)
  File "C:\Python310\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\EShad\Documents\defoko_denoiser\venv\lib\site-packages\gradio_client\client.py", line 959, in _inner
    predictions = _predict(*data)
  File "C:\Users\EShad\Documents\defoko_denoiser\venv\lib\site-packages\gradio_client\client.py", line 999, in _predict
    raise ValueError(result["error"])
ValueError: None
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
from gradio_client import Client
import os

DIR = "dir that exists"

print(os.path.exists(DIR + "file.wav")) ## is returning true

client = Client("https://resembleai-resemble-enhance.hf.space/--replicas/jpfzk/")
res = client.predict(DIR + "file.wav", "Midpoint", 64, 0.5, api_name="/predict")
print(res)
```

### System Info

```shell
Windows 10
Python 3.10.5
gradio_client 0.7.3

When I attempt to run `gradio enviroment`, it says `FileNotFoundError: [Errno 2] No such file or directory: 'enviroment'`. I'm not sure if this is related.
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @butterflyhigh ! You're missing a fifth argument to the `predict` call, the boolean

<img width="1095" alt="image" src="https://github.com/gradio-app/gradio/assets/41651716/cfdb7a5a-e7fa-4d58-b33a-4d2c3f07739d">
