### ISSUE TITLE
File upload with file_count='directory' creates error

### ISSUE THREAD

**Issue by joshwilson-dev** [gradio-app/gradio#6873]
### Describe the bug

gr.File(file_count="directory") causes the error: "ModelMetaclass object argument after ** must be a mapping, not list".

I can fix it by changing line 82 in gradio>components>file.py to:

if self.file_count == "multiple" or self.file_count == "directory":

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def main(dir):
    return [d.name for d in dir]

demo = gr.Interface(
    fn = main,
    inputs = gr.File(file_count="directory"),
    outputs = gr.Textbox(label="File paths"))

demo.queue().launch()
```

### Logs

```shell
Traceback (most recent call last):
  File "env\lib\site-packages\gradio\queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "env\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "env\lib\site-packages\gradio\blocks.py", line 1559, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "env\lib\site-packages\gradio\blocks.py", line 1335, in preprocess_data
    inputs_cached = block.data_model(**inputs_cached)  # type: ignore
TypeError: ModelMetaclass object argument after ** must be a mapping, not list
```

### System Info

```shell
Gradio 4.12.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @joshwilson-dev for catching this! That seems to be the fix indeed. Would you be able to open a PR with this fix?

**Comment by joshwilson-dev** [comment]
Yep, I'll do it now.
