### ISSUE TITLE
Hot reload not working on python 12

### ISSUE THREAD

**Issue by SalamanderXing** [gradio-app/gradio#6878]
### Describe the bug

I ran my demo gradio app and when i make changes to my files i got an error.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import time
import gradio as gr


def slow_echo(message, history):
    for i in range(len(message)):
        time.sleep(0.05)
        yield "You typed: " + message[: i + 1]

css = ""
with gr.Blocks(css=css) as main_block:
    gr.ChatInterface(
        slow_echo,
        theme=gr.themes.Soft(),
        clear_btn=None,
        retry_btn=None,
        undo_btn=None,
        examples=["hey"],
    ).queue()

main_block.launch()
```
Run

 `gradio test.py` 

I first run it and it displays well, but then i make a change and get an error and have to exit and restart gradio.

### Logs

```shell
Warning: Cannot statically find a gradio demo called demo. Reload
work may fail.
Watching: 
'/home/bluesk/venv/lib/python3.12/site-packages/gradio', 
'/home/bluesk/Documents/aikosmo', 
'/home/bluesk/Documents/aikosmo'

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Changes detected in: /home/bluesk/Documents/aikosmo/test.py
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1052, in _bootstr
ap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bluesk/venv/lib/python3.12/site-packages/gradio/uti
ls.py", line 217, in watchfn
    demo = getattr(module, reloader.demo_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'test' has no attribute 'demo'
```
```


### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.12.0
gradio_client version: 0.8.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.100.1
ffmpy: 0.3.1
gradio-client==0.8.0 is not installed.
httpx: 0.25.1
huggingface-hub: 0.19.4
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.26.0
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.1
pillow: 10.0.1
pydantic: 2.4.2
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.23.2
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.25.1
huggingface-hub: 0.19.4
packaging: 23.2
typing-extensions: 4.8.0
websockets: 11.0.3

Python version 3.12.0
```

### Severity

I can work around it

**Comment by Lilneo786** [comment]
Use a File watcher

`pip install watchdog`


 create a separate script that uses watchdog to monitor the changes and restart the Gradio app when needed. Here's an example script

```
import time
import gradio as gr
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

def slow_echo(message, history):
    for i in range(len(message)):
        time.sleep(0.05)
        yield "You typed: " + message[: i + 1]

css = ""
with gr.Blocks(css=css) as main_block:
    gr.ChatInterface(
        slow_echo,
        theme=gr.themes.Soft(),
        clear_btn=None,
        retry_btn=None,
        undo_btn=None,
        examples=["hey"],
    ).queue()

main_block.launch()

# Watch for changes in your Python file
class MyHandler(FileSystemEventHandler):
    def on_modified(self, event):
        if event.src_path == '/path/to/your/test.py':
            main_block.stop()
            main_block.launch()

observer = Observer()
observer.schedule(MyHandler(), path='/path/to/your')
observer.start()

try:
    while True:
        time.sleep(5)
except KeyboardInterrupt:
    observer.stop()
observer.join()
```

Replace /path/to/your/test.py with the actual path to your Python file.

Define Demo Name

```
gr.ChatInterface(
    slow_echo,
    theme=gr.themes.Soft(),
    clear_btn=None,
    retry_btn=None,
    undo_btn=None,
    examples=["hey"],
).queue().launch(demo_name="demo")

```

Update Gradio

`pip install --upgrade gradio`
