### ISSUE TITLE
SystemError when using gradio with starlette>=0.30.0 on Python3.8

### ISSUE THREAD

**Issue by narugo1992** [gradio-app/gradio#6904]
### Describe the bug

SystemError (or some other error) will occured when the following condition is satisfied
* Python3.8 (when I use Python3.10, the error disappeared)
* `gradio==4.12.0`
* `starlette>=0.30.0` (when i downgrade starlette version to `0.29.0`, the error disappeared)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

The simplest reproduction (app.py)

```python
import gradio as gr


if __name__ == '__main__':
    with gr.Blocks() as demo:
        gr_markdown = gr.Markdown(value='nothing')

    demo.launch()

```

the dependencies (requirements.txt)

```
gradio==4.12.0
```

install the newest version with 

```shell
pip install -U -r requirements.txt
```

and just run

```shell
python app.py
```

### Logs

when `starlette==0.32.0.post1`

```
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    import gradio as gr
  File "/home/narugo/wtf-projects/k/venv/lib/python3.8/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/home/narugo/wtf-projects/k/venv/lib/python3.8/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/home/narugo/wtf-projects/k/venv/lib/python3.8/site-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "/home/narugo/wtf-projects/k/venv/lib/python3.8/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/narugo/wtf-projects/k/venv/lib/python3.8/site-packages/gradio/components/annotated_image.py", line 12, in <module>
    from gradio.components.base import Component
  File "/home/narugo/wtf-projects/k/venv/lib/python3.8/site-packages/gradio/components/base.py", line 21, in <module>
    from gradio.blocks import Block, BlockContext
  File "/home/narugo/wtf-projects/k/venv/lib/python3.8/site-packages/gradio/blocks.py", line 29, in <module>
    from gradio import (
  File "/home/narugo/wtf-projects/k/venv/lib/python3.8/site-packages/gradio/networking.py", line 20, in <module>
    from gradio.routes import App
  File "/home/narugo/wtf-projects/k/venv/lib/python3.8/site-packages/gradio/routes.py", line 112, in <module>
    templates = Jinja2Templates(directory=STATIC_TEMPLATE_LIB)
  File "/home/narugo/wtf-projects/k/venv/lib/python3.8/site-packages/starlette/templating.py", line 110, in __init__
    self._setup_env_defaults(self.env)
  File "/home/narugo/wtf-projects/k/venv/lib/python3.8/site-packages/starlette/templating.py", line 126, in _setup_env_defaults
    context: typing.Dict[str, typing.Any],
SystemError: no locals when loading 'str'
```

### System Info

```shell
Cannot run gradio environment, it raise the same error as the log.

This issue can be stably reproduced on my local Ubuntu20.04 environment, and the python:3.8.1 docker image on huggingface space.
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Apparently, this was a bug in Python itself: https://www.reddit.com/r/Python/comments/eobtwm/systemerror_no_locals_when_loading_str/, that should be fixed in the latest version of python 3.8
