### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u2018' in position 7: ordinal not in range(128)

### ISSUE THREAD

**Issue by BrightArgo** [gradio-app/gradio#6955]
### Describe the bug

I believe NGINX is passing a non-compatible header to Python and it is receiving the non-compatible header from Gradio. See the logs below.  Locally on my Mac both with the local and public URL, my chatbot works fine.  Please note: I do *NOT* have NGINX in between serving as a reverse proxy on my local.  However, I receive the error below when I run the application in OCI, over HTTP or HTTPS.  To be clear, I have mapped localhost to both the server IP as well as my domain over HTTP and HTTPS and still receive the error below.  

Here is the NGINX conf:

server {
    server_name <my IP>;  # Change this to your domain name

    location / {  # Change this if you'd like to server your Gradio app on a different path
        proxy_pass http://127.0.0.1:7861/; # Change this if your Gradio app will be running on a different port
        proxy_buffering off;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}

I assume that the httpx library is receiving non-ascii char in a header and cannot process it.  I could be wrong.  However, I checked header values by downloading a har file from the browser and ran a script to check that all headers were UTF-8 encoded.  They were all UTF-8.

Happy to provide more details as necessary.  

Thanks!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```
logger.info("Setting up Gradio interface...")
iface = gr.Interface(
    fn=query_model,
    inputs=gr.Textbox(label="Ask a question about ....."),
    outputs=gr.Textbox(),
    title="",
    description="Ask questions about .....",
)

logger.info("Launching Gradio interface...")
iface.launch(share=False)

### Logs

```shell
Traceback (most recent call last):
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/gradio/queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/sentence_window_retrieval_w_iface_logging.py", line 110, in query_model
    window_response = query_engine.query(full_prompt)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/llama_index/core/base_query_engine.py", line 30, in query
    return self._query(str_or_query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/llama_index/query_engine/retriever_query_engine.py", line 171, in _query
    response = self._response_synthesizer.synthesize(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/llama_index/response_synthesizers/base.py", line 146, in synthesize
    response_str = self.get_response(
                   ^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/llama_index/response_synthesizers/compact_and_refine.py", line 38, in get_response
    return super().get_response(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/llama_index/response_synthesizers/refine.py", line 146, in get_response
    response = self._give_response_single(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/llama_index/response_synthesizers/refine.py", line 202, in _give_response_single
    program(
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/llama_index/response_synthesizers/refine.py", line 64, in __call__
    answer = self._llm.predict(
             ^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/llama_index/llms/llm.py", line 220, in predict
    chat_response = self.chat(messages)
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/llama_index/llms/base.py", line 97, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/llama_index/llms/openai.py", line 234, in chat
    return chat_fn(messages, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/llama_index/llms/openai.py", line 289, in _chat
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/openai/_utils/_utils.py", line 272, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/openai/resources/chat/completions.py", line 645, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 1088, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 853, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 873, in _request
    request = self._build_request(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 447, in _build_request
    headers = self._build_headers(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/openai/_base_client.py", line 408, in _build_headers
    headers = httpx.Headers(headers_dict)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/httpx/_models.py", line 70, in __init__
    self._list = [
                 ^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/httpx/_models.py", line 74, in <listcomp>
    normalize_header_value(v, encoding),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/opc/*****/venv/lib64/python3.11/site-packages/httpx/_utils.py", line 53, in normalize_header_value
    return value.encode(encoding or "ascii")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\u2018' in position 7: ordinal not in range(12
```

### System Info

```shell
Oracle Linux 8 VM
nginx/1.14.1
Gradio 4.12
Python 3.11
```

### Severity

Blocking usage of gradio

**Comment by BrightArgo** [comment]
BTW...this bug report https://github.com/encode/httpx/issues/894 seemed similar.  That said, gradio seems to depend on httpx so unsure how to pivot to requests to see if it would solve the issue.

**Comment by BrightArgo** [comment]
I implemented a front utilizing streamlit and observed the same behavior.  Closing out as I am certain now that this is not related to gradio.
