### ISSUE TITLE
Gradio Timeout error when uploading Big files

### ISSUE THREAD

**Issue by pourmand1376** [gradio-app/gradio#6962]
### Describe the bug

Hi, I've seen this bug appear when I upload large files (over 200Mbs) to gradio and when the operation takes some time. 

> Note that this does not happen when the file is small or network connection is well.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

Possible Related Issues:
- #3517 
- #5143 
- [websockets.exceptions.ConnectionClosedError: code = 1011 (unexpected error), no reason](https://stackoverflow.com/questions/67810506/websockets-exceptions-connectionclosederror-code-1011-unexpected-error-no)

### Reproduction

```python
import gradio as gr
import time


def predict(input_audio_file):
    time.sleep(100)
    return "Operation Finished", None


with gr.Blocks() as demo:
    with gr.Group():
        input_audio_file = gr.Audio(
            label="Input speech",
            type="filepath",
            source="upload",
            visible=True,
        )
        submit = gr.Button("Submit")
        text_output = gr.Textbox(
            label="Text",
            value="",
            interactive=False,
        )
        file_output = gr.File(label="output")

        submit.click(
            fn=predict,
            inputs=[input_audio_file],
            outputs=[text_output, file_output],
            api_name="predict",
        )


demo.queue().launch()

```
Then I use it via gradio_client:
```
from gradio_client import Client
client = Client("http://localhost:7860/")
result = client.predict('/home/amir/Downloads/a.mp3', api_name='/predict')
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/32064808/b1ab8140-9e06-4bc1-be5d-85eaef3558c2)

### Logs

```shell
Traceback (most recent call last):
  File "/home/amir/miniconda3/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 959, in transfer_data
    message = await self.read_message()
  File "/home/amir/miniconda3/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1029, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/amir/miniconda3/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1104, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/amir/miniconda3/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1161, in read_frame
    frame = await Frame.read(
  File "/home/amir/miniconda3/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
  File "/home/amir/miniconda3/lib/python3.10/asyncio/streams.py", line 707, in readexactly
    await self._wait_for_data('readexactly')
  File "/home/amir/miniconda3/lib/python3.10/asyncio/streams.py", line 501, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amir/miniconda3/lib/python3.10/site-packages/gradio_client/client.py", line 291, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
  File "/home/amir/miniconda3/lib/python3.10/site-packages/gradio_client/client.py", line 1120, in result
    return super().result(timeout=timeout)
  File "/home/amir/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/amir/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/amir/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/amir/miniconda3/lib/python3.10/site-packages/gradio_client/client.py", line 793, in _inner
    predictions = _predict(*data)
  File "/home/amir/miniconda3/lib/python3.10/site-packages/gradio_client/client.py", line 822, in _predict
    result = utils.synchronize_async(self._ws_fn, data, hash_data, helper)
  File "/home/amir/miniconda3/lib/python3.10/site-packages/gradio_client/utils.py", line 527, in synchronize_async
    return fsspec.asyn.sync(fsspec.asyn.get_loop(), func, *args, **kwargs)  # type: ignore
  File "/home/amir/miniconda3/lib/python3.10/site-packages/fsspec/asyn.py", line 106, in sync
    raise return_result
  File "/home/amir/miniconda3/lib/python3.10/site-packages/fsspec/asyn.py", line 61, in _runner
    result[0] = await coro
  File "/home/amir/miniconda3/lib/python3.10/site-packages/gradio_client/client.py", line 1050, in _ws_fn
    return await utils.get_pred_from_ws(websocket, data, hash_data, helper)
  File "/home/amir/miniconda3/lib/python3.10/site-packages/gradio_client/utils.py", line 273, in get_pred_from_ws
    msg = task.result()
  File "/home/amir/miniconda3/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/home/amir/miniconda3/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received or sent
```
```


### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 3.43.2
gradio_client version: 0.5.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.0.1
fastapi: 0.103.1
ffmpy: 0.3.1
gradio-client==0.5.0 is not installed.
httpx: 0.24.1
huggingface-hub: 0.16.4
importlib-resources: 6.0.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.2
numpy: 1.25.0
orjson: 3.9.7
packaging: 23.1
pandas: 2.0.3
pillow: 10.0.0
pydantic: 1.10.9
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0
requests: 2.26.0
semantic-version: 2.10.0
typing-extensions: 4.7.1
uvicorn: 0.23.2
websockets: 11.0.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.24.1
huggingface-hub: 0.16.4
packaging: 23.1
requests: 2.26.0
typing-extensions: 4.7.1
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @pourmand1376 could you try checking a more recent version of Gradio? We've significantly changed how uploaded files are handled in Gradio 4.x so I'd recommend checking on `gradio==4.13.0`

**Comment by pourmand1376** [comment]
Thank you for your answer. 

The problem solves when upgrading to the newer version.
