### ISSUE TITLE
Error Hugging Face Spaces

### ISSUE THREAD

**Issue by FLOPS-FLOPS** [gradio-app/gradio#6964]
### Describe the bug

It keeps returning an error when I try to test a model called `cognitivecomputations/dolphin-2.5-mixtral-8x7b`
 in Hugging face spaces created by Gradio.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### Logs

```shell
===== Application Startup at 2024-01-08 08:51:59 =====

Fetching model from: https://huggingface.co/cognitivecomputations/dolphin-2.5-mixtral-8x7b
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/ssl.py", line 1292, in recv
    return self.read(buflen)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/ssl.py", line 1165, in read
    return self._sslobj.read(len)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 111, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 212, in _receive_event
    data = self._network_stream.read(
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/gradio/queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/gradio/external.py", line 436, in query_huggingface_api
    response = httpx.request("POST", api_url, headers=headers, data=data)  # type: ignore
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpx/_api.py", line 104, in request
    return client.request(
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpx/_client.py", line 828, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpx/_transports/default.py", line 230, in handle_request
    with map_httpcore_exceptions():
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/.pyenv/versions/3.10.13/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out
```

### System Info

```shell
gradio[oauth]==4.12.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @FLOPS-FLOPS this model is too large to be loaded through the Hugging Face Inference API, which `gr.load()` implicitly uses, so `gr.load("cognitivecomputations/dolphin-2.5-mixtral-8x7b")` will not work.

You will need to use Inference Endpoints for this. Take a look here: https://ui.endpoints.huggingface.co/abidlabs/new?repository=cognitivecomputations%2Fdolphin-2.5-mixtral-8x7b
