### ISSUE TITLE
Lite: <gradio-file> tag produces ModuleNotFoundError

### ISSUE THREAD

**Issue by fcole** [gradio-app/gradio#7044]
### Describe the bug

I'm trying to use the <gradio-file> tags to load multiple python modules, as described here: https://www.gradio.app/guides/gradio-lite#multiple-files

However even the example in the documentation appears to produce a ModuleNotFoundError: 

Traceback (most recent call last): File "<exec>", line 103, in _run_script File "<exec>", line 149, in _run_code File "app.py", line 3, in <module> from utils import add ModuleNotFoundError: No module named 'utils'

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

my index.html is this, which I copied from the example here: https://www.gradio.app/guides/gradio-lite#multiple-files

```html
<html>
<head>
<script type="module" crossorigin src="https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.css" />
</head>
<body>
<gradio-lite>

<gradio-file name="app.py" entrypoint>
import gradio as gr
from utils import add

demo = gr.Interface(fn=add, inputs=["number", "number"], outputs="number")

demo.launch()
</gradio-file>

<gradio-file name="utils.py" >
def add(a, b):
	return a + b
</gradio-file>

</gradio-lite>
</body>
</html>
```

### Logs

```shell
Traceback (most recent call last): File "<exec>", line 103, in _run_script File "<exec>", line 149, in _run_code File "app.py", line 3, in <module> from utils import add ModuleNotFoundError: No module named 'utils'

k@https://cdn.jsdelivr.net/pyodide/v0.24.0/full/pyodide.asm.js:9:104349
new_error@https://cdn.jsdelivr.net/pyodide/v0.24.0/full/pyodide.asm.js:9:12538
<?>.wasm-function[295]@[wasm code]
<?>.wasm-function[452]@[wasm code]
452@[native code]
<?>.wasm-function[1057]@[wasm code]
<?>.wasm-function[3387]@[wasm code]
<?>.wasm-function[2037]@[wasm code]
<?>.wasm-function[2158]@[wasm code]
<?>.wasm-function[1064]@[wasm code]
<?>.wasm-function[8153]@[wasm code]
<?>.wasm-function[3774]@[wasm code]
<?>.wasm-function[3197]@[wasm code]
<?>.wasm-function[1067]@[wasm code]
<?>.wasm-function[1068]@[wasm code]
<?>.wasm-function[3200]@[wasm code]
<?>.wasm-function[3201]@[wasm code]
<?>.wasm-function[1070]@[wasm code]
<?>.wasm-function[2158]@[wasm code]
<?>.wasm-function[1065]@[wasm code]
<?>.wasm-function[440]@[wasm code]
@https://cdn.jsdelivr.net/pyodide/v0.24.0/full/pyodide.asm.js:9:81747
wrapper@https://cdn.jsdelivr.net/pyodide/v0.24.0/full/pyodide.asm.js:9:58574
```

### System Info

```shell
Latest gradio-lite from CDN loaded in <script> tag
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
@whitphx could you take a look at this?

**Comment by fcole** [comment]
Thanks for the fix! When should we expect this to be in the released gradio-lite from npm? (is the release schedule documented somewhere?)
