### ISSUE TITLE
Can't generate local url when set share=False in interface.launch() method (not google colab environment)

### ISSUE THREAD

**Issue by fulwang** [gradio-app/gradio#7100]
### Describe the bug

Hello, 

I want to create only a local url using gradio and set the share=False in interface.launch() method doesn't work in my case, does anyone encounter this before and have any ideas?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
    
demo.launch(share=False)

```

### Screenshot

<img width="1297" alt="Screenshot 2024-01-22 at 11 20 22" src="https://github.com/gradio-app/gradio/assets/31059578/a4fa84c3-286d-4a48-92a6-69f5c4017120">

### Logs

```shell
Running on local URL:  http://127.0.0.1:7860
Traceback (most recent call last):
  File "/Users/fulwang/vscode/python/chatbot1_py311/demo.py", line 8, in <module>
    demo.launch(share=False)
  File "/Users/fulwang/anaconda3/envs/chatbot1_py311/lib/python3.11/site-packages/gradio/blocks.py", line 1990, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.
```

### System Info

```shell
(chatbot1_py311) fulwang@fulwang-mbp chatbot1_py311 % gradio environment
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.14.0
gradio_client version: 0.8.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.109.0
ffmpy: 0.3.1
gradio-client==0.8.0 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.2
importlib-resources: 6.1.1
jinja2: 3.1.3
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.3
orjson: 3.9.12
packaging: 23.2
pandas: 2.1.4
pillow: 10.2.0
pydantic: 2.5.3
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.26.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.26.0
huggingface-hub: 0.20.2
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3


(chatbot1_py311) fulwang@fulwang-mbp chatbot1_py311 %
```

### Severity

Blocking usage of gradio

**Comment by fulwang** [comment]
I'm using MacOS Sonoma 14.2.1 and ping to localhost and loopback address works

**Comment by abidlabs** [comment]
Hi @fulwang, are you running this code in any unusual environment, e.g. a jupyter notebook that is hosted on a remote server?

**Comment by fulwang** [comment]
Not on web or remote server, i ran the code using MacOS terminal ( virtual python env created using anaconda)

**Comment by abidlabs** [comment]
Could you try installing `gradio` with `pip` and seeing if that makes any difference?

**Comment by abidlabs** [comment]
Closing for now, happy to reopen with more details that could allow us to report
