### ISSUE TITLE
HuggingFaceDatasetSaver error with deserialization

### ISSUE THREAD

**Issue by kevinconka** [gradio-app/gradio#7114]
### Describe the bug

When running the example of `HuggingFaceDatasetSaver` and flagging a sample, an error is thrown:
```python
Error while flagging: '{"path":<local_dataset_path>/inp/0e70bc57e195427b613a/18095390.jpg","url":"http:/127.0.0.1:7860/file=/private/var/folders/4y/pnmysh0j3mx29k4xfh88xkgw0000gn/T/gradio/ace3f0c3a4f1aa9aa82666d02a32ac1d136f32b1/18095390.jpg","size":69843,"orig_name":"18095390.jpg","mime_type":""}' is not in the subpath of '<local_dataset_path>' OR one path is relative and the other is absolute.
```

The error seems to be coming from the `component.flag` since it returns a string version of a dict, and the further logic assumes `deserialized` is a path.
https://github.com/gradio-app/gradio/blob/217bfe39ca6a0de885824f16be4a707e7f032d57/gradio/flagging.py#L421-L441

I have found a workaround which works for my specific case, but I doubt this is a good solution. Maybe you have some better proposals.
<img width="553" alt="image" src="https://github.com/gradio-app/gradio/assets/35779409/28ec66ee-867d-4f60-91ce-96eff192b3de">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
from huggingface_hub import get_token

hf_writer = gr.HuggingFaceDatasetSaver(get_token(), "username/dataset")
def image_classifier(inp):
    return {'cat': 0.3, 'dog': 0.7}
demo = gr.Interface(fn=image_classifier, inputs="image", outputs="label",
                    allow_flagging="manual", flagging_callback=hf_writer)
demo.launch()
```

Uploading an image and clicking on `Flag` are enough to trigger the error

### Screenshot

<img width="987" alt="image" src="https://github.com/gradio-app/gradio/assets/35779409/5ab9e108-9b3e-4a93-96d3-6dfe5f0f1059">

### Logs

```shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "<env_dir>/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "<env_dir>/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "<env_dir>/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "<env_dir>/lib/python3.10/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "<env_dir>/lib/python3.10/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "<env_dir>/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "<env_dir>/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "<env_dir>/lib/python3.10/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/Users/kevinserrano/HF/detection-RGB/app.py", line 94, in <lambda>
    lambda *args: hf_writer.flag(args),
  File "<env_dir>/lib/python3.10/site-packages/gradio/flagging.py", line 303, in flag
    return self._flag_in_dir(
  File "<env_dir>/lib/python3.10/site-packages/gradio/flagging.py", line 322, in _flag_in_dir
    features, row = self._deserialize_components(
  File "<env_dir>/lib/python3.10/site-packages/gradio/flagging.py", line 441, in _deserialize_components
    Path(deserialized).relative_to(self.dataset_dir)
  File "<env_dir>/lib/python3.10/pathlib.py", line 818, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '{"path":"<ommited_path>/input/a26425aa786bec36687e/pexels-photo-913111.jpegautocompresscstinysrgbw1260h750dpr2","url":"http:/127.0.0.1:7860/file=/private/var/folders/4y/pnmysh0j3mx29k4xfh88xkgw0000gn/T/gradio/1e06e071282abb5097e1f73678ccb07e5e99d87f/pexels-photo-913111.jpegautocompresscstinysrgbw1260h750dpr2","size":null,"orig_name":null,"mime_type":null}' is not in the subpath of '<ommited_path>' OR one path is relative and the other is absolute.
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.14.0
gradio_client version: 0.8.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 22.1.0
altair: 5.0.1
fastapi: 0.103.0
ffmpy: 0.3.0
gradio-client==0.8.0 is not installed.
httpx: 0.23.0
huggingface-hub: 0.20.2
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.0
numpy: 1.26.3
orjson: 3.9.10
packaging: 23.1
pandas: 2.1.4
pillow: 10.0.1
pydantic: 2.0.3
pydub: 0.25.1
python-multipart: 0.0.6
pyyaml: 6.0.1
semantic-version: 2.8.5
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.7.1
uvicorn: 0.20.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.23.0
huggingface-hub: 0.20.2
packaging: 23.1
typing-extensions: 4.7.1
websockets: 10.4
```

### Severity

I can work around it

**Comment by toshas** [comment]
My dirty fix:
```
     deserialized = component.flag(sample, save_dir)

+    # Base component .flag method returns JSON; extract path from it when it is FileData
+    if component.data_model:
+        data = component.data_model.from_json(json.loads(deserialized))
+        if component.data_model == gr.data_classes.FileData:
+            deserialized = data.path
+
     # Add deserialized object to row

```

**Comment by abidlabs** [comment]
The HFDatasetSaver has been deprecated in Gradio 5, so closing this issue as it is no longer applicable.
