### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Sriharsha\\Documents\\tsai\\S12\\grad_imgs'

### ISSUE THREAD

**Issue by ksharsha72** [gradio-app/gradio#7121]
### Describe the bug

Hai i have been trying to use gr.Examples to populate some images as example, when user click the image it need to get loaded in to the input component gr.Gallery

i have given exmpales as path to my .jpeg file

```
examples = ["./example_0.jpeg"]  # single input image
examples  = "./S12/grad_imgs"  #directory holding inputs

```

and inputs =gallery , where `gallery=gr.Gallery()`

```
def mirror(x): 
           return x
```

```
examples= gr.Examples(examples=examples,inputs=gallery,fn=mirror)

```

when i run `demo.launch()` i am getting the error as follows

```
Traceback (most recent call last):
  File "c:\Users\Sriharsha\Documents\tsai\S12\inference.py", line 200, in <module>
    gr.Examples(
  File "C:\Users\Sriharsha\AppData\Roaming\Python\Python311\site-packages\gradio\helpers.py", line 58, in create_examples
    examples_obj = Examples(
                   ^^^^^^^^^
  File "C:\Users\Sriharsha\AppData\Roaming\Python\Python311\site-packages\gradio\helpers.py", line 220, in __init__
    prediction_value = processing_utils.move_files_to_cache(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sriharsha\AppData\Roaming\Python\Python311\site-packages\gradio\processing_utils.py", line 268, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sriharsha\AppData\Roaming\Python\Python311\site-packages\gradio_client\utils.py", line 928, in traverse
    new_obj.append(traverse(item, func, is_root))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sriharsha\AppData\Roaming\Python\Python311\site-packages\gradio_client\utils.py", line 923, in traverse
    new_obj[key] = traverse(value, func, is_root)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sriharsha\AppData\Roaming\Python\Python311\site-packages\gradio_client\utils.py", line 919, in traverse
    return func(json_obj)
           ^^^^^^^^^^^^^^
  File "C:\Users\Sriharsha\AppData\Roaming\Python\Python311\site-packages\gradio\processing_utils.py", line 260, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sriharsha\AppData\Roaming\Python\Python311\site-packages\gradio\processing_utils.py", line 236, in move_resource_to_block_cache    
    return block.move_resource_to_block_cache(url_or_file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sriharsha\AppData\Roaming\Python\Python311\site-packages\gradio\blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sriharsha\AppData\Roaming\Python\Python311\site-packages\gradio\processing_utils.py", line 172, in save_file_to_cache
    temp_dir = hash_file(file_path)
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sriharsha\AppData\Roaming\Python\Python311\site-packages\gradio\processing_utils.py", line 104, in hash_file
    with open(file_path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Sriharsha\\Documents\\tsai\\S12\\grad_imgs'
```

could some one help me with this , 
```
for both single input and directory i am getting permission denied error

```

i tried giving directoy path also but still getting the same error

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
gradio.__version__ = '4.12.0'
python.__version__ = '3.11.4'
windows 11 os
```

**Comment by abidlabs** [comment]
Hi @ksharsha72 can you please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by ksharsha72** [comment]
Yeah sure here is the code that i have tried to reproduce it , please take any of your jpeg files

```
examples= [
    "./example_0.jpeg",
    "./example_1.jpeg",
    "./example_2.jpeg",
    "./example_3.jpeg",
    "./example_4.jpeg",
    "./example_5.jpeg",
    "./example_6.jpeg",
    "./example_7.jpeg",
    "./example_8.jpeg",
]


def mirror(x):
    return x


import gradio as gr

with gr.Blocks() as demo:
    with gr.Row():
        file = gr.Gallery()
        out = gr.Gallery()
        gr.Examples(examples=examples,inputs=out,outputs=out,fn=mirror)


demo.launch()

```


and i got the same error of permission denied

```
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
Cell In[6], line 7
      5 file = gr.Gallery()
      6 out = gr.Gallery()
----> 7 gr.Examples(examples=examples,inputs=out,outputs=out,fn=mirror)

File ~\AppData\Roaming\Python\Python311\site-packages\gradio\helpers.py:58, in create_examples(examples, inputs, outputs, fn, cache_examples, examples_per_page, _api_mode, label, elem_id, run_on_click, preprocess, postprocess, api_name, batch)
     41 def create_examples(
     42     examples: list[Any] | list[list[Any]] | str,
     43     inputs: Component | list[Component],
   (...)
     55     batch: bool = False,
     56 ):
     57     """Top-level synchronous function that creates Examples. Provided for backwards compatibility, i.e. so that gr.Examples(...) can be used to create the Examples component."""
---> 58     examples_obj = Examples(
     59         examples=examples,
     60         inputs=inputs,
     61         outputs=outputs,
     62         fn=fn,
     63         cache_examples=cache_examples,
     64         examples_per_page=examples_per_page,
     65         _api_mode=_api_mode,
     66         label=label,
     67         elem_id=elem_id,
     68         run_on_click=run_on_click,
     69         preprocess=preprocess,
     70         postprocess=postprocess,
     71         api_name=api_name,
     72         batch=batch,
     73         _initiated_directly=False,
     74     )
     75     examples_obj.create()
     76     return examples_obj

File ~\AppData\Roaming\Python\Python311\site-packages\gradio\helpers.py:218, in Examples.__init__(self, examples, inputs, outputs, fn, cache_examples, examples_per_page, _api_mode, label, elem_id, run_on_click, preprocess, postprocess, api_name, batch, _initiated_directly)
    216     if isinstance(prediction_value, (GradioRootModel, GradioModel)):
    217         prediction_value = prediction_value.model_dump()
--> 218     prediction_value = processing_utils.move_files_to_cache(
    219         prediction_value, component, postprocess=True
    220     )
    221     sub.append(prediction_value)
    222 self.processed_examples.append(sub)

File ~\AppData\Roaming\Python\Python311\site-packages\gradio\processing_utils.py:265, in move_files_to_cache(data, block, postprocess)
    262 if isinstance(data, (GradioRootModel, GradioModel)):
    263     data = data.model_dump()
--> 265 return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)

File ~\AppData\Roaming\Python\Python311\site-packages\gradio_client\utils.py:928, in traverse(json_obj, func, is_root)
    926     new_obj = []
    927     for item in json_obj:
--> 928         new_obj.append(traverse(item, func, is_root))
    929     return new_obj
    930 else:

File ~\AppData\Roaming\Python\Python311\site-packages\gradio_client\utils.py:923, in traverse(json_obj, func, is_root)
    921     new_obj = {}
    922     for key, value in json_obj.items():
--> 923         new_obj[key] = traverse(value, func, is_root)
    924     return new_obj
    925 elif isinstance(json_obj, (list, tuple)):

File ~\AppData\Roaming\Python\Python311\site-packages\gradio_client\utils.py:919, in traverse(json_obj, func, is_root)
    917 def traverse(json_obj: Any, func: Callable, is_root: Callable) -> Any:
    918     if is_root(json_obj):
--> 919         return func(json_obj)
    920     elif isinstance(json_obj, dict):
    921         new_obj = {}

File ~\AppData\Roaming\Python\Python311\site-packages\gradio\processing_utils.py:257, in move_files_to_cache.<locals>._move_to_cache(d)
    255     temp_file_path = payload.url
    256 else:
--> 257     temp_file_path = move_resource_to_block_cache(payload.path, block)
    258 assert temp_file_path is not None
    259 payload.path = temp_file_path

File ~\AppData\Roaming\Python\Python311\site-packages\gradio\processing_utils.py:234, in move_resource_to_block_cache(url_or_file_path, block)
    228 def move_resource_to_block_cache(
    229     url_or_file_path: str | Path | None, block: Component
    230 ) -> str | None:
    231     """This method has been replaced by Block.move_resource_to_block_cache(), but is
    232     left here for backwards compatibility for any custom components created in Gradio 4.2.0 or earlier.
    233     """
--> 234     return block.move_resource_to_block_cache(url_or_file_path)

File ~\AppData\Roaming\Python\Python311\site-packages\gradio\blocks.py:258, in Block.move_resource_to_block_cache(self, url_or_file_path)
    256 url_or_file_path = str(utils.abspath(url_or_file_path))
    257 if not utils.is_in_or_equal(url_or_file_path, self.GRADIO_CACHE):
--> 258     temp_file_path = processing_utils.save_file_to_cache(
    259         url_or_file_path, cache_dir=self.GRADIO_CACHE
    260     )
    261 else:
    262     temp_file_path = url_or_file_path

File ~\AppData\Roaming\Python\Python311\site-packages\gradio\processing_utils.py:170, in save_file_to_cache(file_path, cache_dir)
    167 def save_file_to_cache(file_path: str | Path, cache_dir: str) -> str:
    168     """Returns a temporary file path for a copy of the given file path if it does
    169     not already exist. Otherwise returns the path to the existing temp file."""
--> 170     temp_dir = hash_file(file_path)
    171     temp_dir = Path(cache_dir) / temp_dir
    172     temp_dir.mkdir(exist_ok=True, parents=True)

File ~\AppData\Roaming\Python\Python311\site-packages\gradio\processing_utils.py:102, in hash_file(file_path, chunk_num_blocks)
    100 def hash_file(file_path: str | Path, chunk_num_blocks: int = 128) -> str:
    101     sha1 = hashlib.sha1()
--> 102     with open(file_path, "rb") as f:
    103         for chunk in iter(lambda: f.read(chunk_num_blocks * sha1.block_size), b""):
    104             sha1.update(chunk)

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Sriharsha\\Documents\\Gradio_Tutorial\\notebooks'

```

**Comment by abidlabs** [comment]
Ah okay so a few things going on here. 

1) `Gallery` is not technically meant to be used as an input component, so it doesn't really support examples.
 
2) If you want, you can provide examples, but they'll show up like this:

<img width="717" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/a87dfa42-24f1-4ba5-96f6-b66d872fc006">

3) In order to do that, you need to provide `examples` as a nested nested list, i.e. there should be three lists. Here's your code adapted that works for me:

```py
examples= [[[
    "./cheetah.jpg",
]]]


def mirror(x):
    return x


import gradio as gr

with gr.Blocks() as demo:
    with gr.Row():
        file = gr.Gallery()
        out = gr.Gallery()
        gr.Examples(examples=examples,inputs=file,outputs=out,fn=mirror)


demo.launch()

```
