### ISSUE TITLE
multiple versions of python, cmd  has taken gradio from the first encountered version rather than one in  top of the environment variables and default

### ISSUE THREAD

**Issue by ksharsha72** [gradio-app/gradio#7153]
### Describe the bug

Hello i have a python 3.10  installed at  `C:\Python310` and other version python 3.11.4 at `C:\Program Files\Python311`

by default the python3.11 is on the top of the environment variables path and when i type python version i am getting it as 3.11.4

```
python --version

python 3.11.4

``` 
in vs code also i selected python 3.11.4 interpreter

when i run gradio for fatser development it is taking the gradio command from python3.10, 
```gradio app.py```

so i uninstalled gradio from 3.10 then `cmd` says there is no command gradio, but as per the environment variables path , it should take `gradio command` from python 3.11.4 but it is not been taken , and i have gradio installed in both the versions

```
where python 

C:\Program Files\Python311\python.exe
C:\Python310\python.exe
C:\Users\Sriharsha\AppData\Local\Microsoft\WindowsApps\python.exe

```
and the above is the output of where python, could some one help me how to resolve this and what is happening

there has been problem with gradio also from Python 3.10 version, which is later in the environment variable path ,  i am getting KeyError  __main__, 

```
  File "C:\Python310\lib\site-packages\gradio\utils.py", line 207, in watchfn
    module = importlib.import_module(reloader.watch_module_name)
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Sriharsha\Documents\tsai\S12\inference.py", line 30, in <module>
    model = LitResnet.load_from_checkpoint(model_path)
  File "C:\Python310\lib\site-packages\lightning\pytorch\utilities\model_helpers.py", line 91, in __get__
    is_scripting = any(os.path.join("torch", "jit") in frameinfo.filename for frameinfo in inspect.stack())
  File "C:\Python310\lib\inspect.py", line 1678, in stack
    return getouterframes(sys._getframe(1), context)
  File "C:\Python310\lib\inspect.py", line 1655, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "C:\Python310\lib\inspect.py", line 1625, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "C:\Python310\lib\inspect.py", line 829, in getsourcefile
    module = getmodule(object, filename)
  File "C:\Python310\lib\inspect.py", line 882, in getmodule
    main = sys.modules['__main__']
KeyError: '__main__'

```

could some one give solutios for both, the error above and the python version for which gradio command being used

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
python 3.11.4 and 3.10.7
windows 11
gradio 4.15.0
```

**Comment by freddyaboulton** [comment]
Hi @ksharsha72 !

Can you try installing and running gradio from a virtual environment like [venv](https://docs.python.org/3/library/venv.html) (built in) or [conda](https://docs.conda.io/projects/conda/en/stable/user-guide/getting-started.html).

Installing packages into the system python version is not a good idea because of the issue you've found with conflicting versions.

**Comment by ksharsha72** [comment]
sorry for delay yes i have created the venv , now i can see gradio is been taken from 3.11 venv but the KeyERROR __main__ is still there

```
Traceback (most recent call last):
  File "C:\Users\Sriharsha\Documents\tsai\venv\Lib\site-packages\gradio\utils.py", line 208, in watchfn
    module = importlib.import_module(reloader.watch_module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Sriharsha\Documents\tsai\S12\inference.py", line 30, in <module>
    model = LitResnet.load_from_checkpoint(model_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sriharsha\Documents\tsai\venv\Lib\site-packages\lightning\pytorch\utilities\model_helpers.py", line 91, in __get__
    is_scripting = any(os.path.join("torch", "jit") in frameinfo.filename for frameinfo in inspect.stack())
                                                                                           ^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\inspect.py", line 1755, in stack
    return getouterframes(sys._getframe(1), context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\inspect.py", line 1730, in getouterframes
    traceback_info = getframeinfo(frame, context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\inspect.py", line 1688, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\inspect.py", line 952, in getsourcefile
    module = getmodule(object, filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\inspect.py", line 1005, in getmodule
    main = sys.modules['__main__']
           ~~~~~~~~~~~^^^^^^^^^^^^
KeyError: '__main__'
Running on public URL: https://a2ba030f5ed917663c.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
```

**Comment by abidlabs** [comment]
Do you have a code block like this to run your Gradio app @ksharsha72?

```py

if __name__ == "__main__":
    demo.launch()

```

**Comment by abidlabs** [comment]
Closing for lack of followup, but happy to reopen with more details.

**Comment by ksharsha72** [comment]
Sorry i dont have a code like inside if__name__ == "__main__"
