### ISSUE TITLE
Unable to include Logout button offline

### ISSUE THREAD

**Issue by Solomin0** [gradio-app/gradio#7163]
### Describe the bug

I used to be able to use the workaround here by modifying the routes file [#5163](https://github.com/gradio-app/gradio/issues/5163) but now the gradio application refuses to launch at all. I need to be able to host everything including my authorization locally what are my options here. 
This is gradio 4.15.0
                             

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

This is just the chatbot demo with a logout button
```                                                                    
import gradio as gr
import random
import time

def fake_login(username, password):
    return True

with gr.Blocks() as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.ClearButton([msg, chatbot])

    def respond(message, chat_history):
        bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
        chat_history.append((message, bot_message))
        time.sleep(2)
        return "", chat_history
    gr.LogoutButton()
    msg.submit(respond, [msg, chatbot], [msg, chatbot])

if __name__ == "__main__":
    demo.launch(server_name = "0.0.0.0",server_port = 80, auth = fake_login, inbrowser=True, auth_message="For account management contact 
```                    

### Logs

```shell
@76f6a19bdcda:/workspace# python3 a.py
/usr/local/lib/python3.10/dist-packages/gradio/oauth.py:116: UserWarning: Gradio does not support OAuth features outside of a Space environment. To help you debug your app locally, the login and logout buttons are mocked with your profile. To make it work, your machine must be logged in to Huggingface.
  warnings.warn(
Traceback (most recent call last):
  File "/workspace/a.py", line 8, in <module>
    with gr.Blocks() as demo:
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1673, in __exit__
    self.app = routes.App.create_app(self)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 308, in create_app
    attach_oauth(app)
  File "/usr/local/lib/python3.10/dist-packages/gradio/oauth.py", line 36, in attach_oauth
    _add_mocked_oauth_routes(app)
  File "/usr/local/lib/python3.10/dist-packages/gradio/oauth.py", line 121, in _add_mocked_oauth_routes
    mocked_oauth_info = _get_mocked_oauth_info()
  File "/usr/local/lib/python3.10/dist-packages/gradio/oauth.py", line 228, in _get_mocked_oauth_info
    raise ValueError(
ValueError: Your machine must be logged in to HF to debug a Gradio app locally. Please run `huggingface-cli login` or set `HF_TOKEN` as environment variable with one of your access token. You can generate a new token in your settings page (https://huggingface.co/settings/tokens).
root@76f6a19bdcda:/workspace#
```

### System Info

```shell
version 4.15.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @Solomin0 the `gr.LogoutButton` is intended to to be used with HuggingFace-specific auth. If you want your own logout functionality, please use something like: `gr.Button(link="/logout")`

I believe this should work, but if not, please let me know and we can look some more into this.

**Comment by Solomin0** [comment]
this works but i still needed to manually add the path in the routes.py file. 
```@app.get("/logout")
        def logout():
            response = RedirectResponse(url="/", status_code=status.HTTP_302_FOUND)
            response.delete_cookie(key=f"access-token-{app.cookie_id}")
            response.delete_cookie(key=f"access-token-unsecure-{app.cookie_id}")
            return response```

is there any plan to just add the change into default gradio?

**Comment by abidlabs** [comment]
Yes I think we should probably add it, pls follow https://github.com/gradio-app/gradio/issues/5163
