### ISSUE TITLE
"No Event Data" on gradio=3.16.2

### ISSUE THREAD

**Issue by FengRuii** [gradio-app/gradio#7168]
### Describe the bug

While running stable diffusion controlnet depth2image by [@lllyasviel](https://github.com/lllyasviel/ControlNet/tree/main), I encountered the following error after hitting the "run" button on the gradio interface: 

```
Task exception was never retrieved
future: <Task finished name='0e389f9nnpz9_0' coro=<Queue.process_events() done, defined at C:\Users\fengr\miniconda3\envs\control\lib\site-packages\gradio\queueing.py:324> exception=AssertionError('No event data')>
Traceback (most recent call last):
  File "C:\Users\fengr\miniconda3\envs\control\lib\site-packages\gradio\queueing.py", line 338, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\fengr\miniconda3\envs\control\lib\site-packages\gradio\queueing.py", line 298, in call_prediction
    assert data is not None, "No event data"
```

The output window would be stuck with the timer which never stops going, and no output images were generated. 

I suspect that this might be a version issue, therefore I followed the huggingface topic: [link](https://discuss.huggingface.co/t/duplicated-gradio-app-receives-task-exception-was-never-retrieved/46237/3).  However it did not help in this case, and also generated more errors after changing the dependencies.  Would like to test out the controlnet features with gradio as is documented in the ControlNet repository and understand the root-cause of this issue. 

Thank you in advance

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
from share import *
import config

import cv2
import einops
import gradio as gr
import numpy as np
import torch
import random

from pytorch_lightning import seed_everything
from annotator.util import resize_image, HWC3
from annotator.midas import MidasDetector
from cldm.model import create_model, load_state_dict
from cldm.ddim_hacked import DDIMSampler

```

### Logs

```shell
Task exception was never retrieved
future: <Task finished name='ynw66cfz1_0' coro=<Queue.process_events() done, defined at C:\Users\miniconda3\envs\control\lib\site-packages\gradio\queueing.py:324> exception=AssertionError('No event data')>
Traceback (most recent call last):
  File "C:\Users\miniconda3\envs\control\lib\site-packages\gradio\queueing.py", line 338, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\miniconda3\envs\control\lib\site-packages\gradio\queueing.py", line 298, in call_prediction
    assert data is not None, "No event data"
AssertionError: No event data
```

### System Info

```shell
absl-py                   2.1.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
aiohttp                   3.9.1                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
albumentations            1.3.0                    pypi_0    pypi
altair                    5.2.0                    pypi_0    pypi
annotated-types           0.6.0                    pypi_0    pypi
antlr4-python3-runtime    4.8                      pypi_0    pypi
anyio                     4.2.0                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
backports-zoneinfo        0.2.1                    pypi_0    pypi
basicsr                   1.4.2                    pypi_0    pypi
blas                      1.0                         mkl
blinker                   1.7.0                    pypi_0    pypi
braceexpand               0.1.7                    pypi_0    pypi
brotli-python             1.0.9            py38hd77b12b_7
ca-certificates           2023.12.12           haa95532_0
cachetools                5.3.2                    pypi_0    pypi
certifi                   2023.11.17       py38haa95532_0
cffi                      1.16.0           py38h2bbff1b_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cryptography              41.0.3           py38h3438e0d_0
cudatoolkit               11.3.1               h59b6b97_2
cycler                    0.12.1                   pypi_0    pypi
einops                    0.3.0                    pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
fastapi                   0.109.0                  pypi_0    pypi
ffmpy                     0.3.1                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
fonttools                 4.47.2                   pypi_0    pypi
freetype                  2.12.1               ha860e81_0
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2023.12.2                pypi_0    pypi
ftfy                      6.1.3                    pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
giflib                    5.2.1                h8cc25b3_3
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.41                   pypi_0    pypi
google-auth               2.27.0                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
gradio                    3.16.2                   pypi_0    pypi
grpcio                    1.60.0                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.2                    pypi_0    pypi
httpx                     0.26.0                   pypi_0    pypi
huggingface-hub           0.20.3                   pypi_0    pypi
idna                      3.4              py38haa95532_0
imageio                   2.9.0                    pypi_0    pypi
imageio-ffmpeg            0.4.2                    pypi_0    pypi
importlib-metadata        7.0.1                    pypi_0    pypi
importlib-resources       6.1.1                    pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
invisible-watermark       0.2.0                    pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
jpeg                      9e                   h2bbff1b_1
jsonschema                4.21.1                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
kornia                    0.6.0                    pypi_0    pypi
lazy-loader               0.3                      pypi_0    pypi
lerc                      3.0                  hd77b12b_0
libdeflate                1.17                 h2bbff1b_1
libpng                    1.6.39               h8cc25b3_0
libtiff                   4.5.1                hd77b12b_0
libuv                     1.44.2               h2bbff1b_0
libwebp                   1.3.2                hbc33d0d_0
libwebp-base              1.3.2                h2bbff1b_0
linkify-it-py             2.0.2                    pypi_0    pypi
lmdb                      1.4.1                    pypi_0    pypi
lz4-c                     1.9.4                h2bbff1b_0
markdown                  3.5.2                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.4                    pypi_0    pypi
matplotlib                3.7.4                    pypi_0    pypi
mdit-py-plugins           0.4.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py38h2bbff1b_0
mkl_fft                   1.3.1            py38h277e83a_0
mkl_random                1.2.2            py38hf11a4ad_0
multidict                 6.0.4                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
numpy                     1.23.1           py38h7a0a035_0
numpy-base                1.23.1           py38hca35cd5_0
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.1.1                    pypi_0    pypi
open-clip-torch           2.0.2                    pypi_0    pypi
opencv-contrib-python     4.3.0.36                 pypi_0    pypi
opencv-python             4.9.0.80                 pypi_0    pypi
opencv-python-headless    4.9.0.80                 pypi_0    pypi
openjpeg                  2.4.0                h4fc8c34_0
openssl                   1.1.1w               h2bbff1b_0
orjson                    3.9.12                   pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
pillow                    10.0.1           py38h045eedc_0
pip                       20.3.3           py38haa95532_0
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
prettytable               3.6.0                    pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
pyarrow                   15.0.0                   pypi_0    pypi
pyasn1                    0.5.1                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pycryptodome              3.20.0                   pypi_0    pypi
pydantic                  2.5.3                    pypi_0    pypi
pydantic-core             2.14.6                   pypi_0    pypi
pydeck                    0.8.1b0                  pypi_0    pypi
pydeprecate               0.3.1                    pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pympler                   1.0.1                    pypi_0    pypi
pyopenssl                 23.2.0           py38haa95532_0
pyparsing                 3.1.1                    pypi_0    pypi
pysocks                   1.7.1            py38haa95532_0
python                    3.8.5                h5fd99cc_1
python-dateutil           2.8.2                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
pytorch                   1.12.1          py3.8_cuda11.3_cudnn8_0    pytorch
pytorch-lightning         1.5.0                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3.post1             pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
qudida                    0.0.4                    pypi_0    pypi
referencing               0.32.1                   pypi_0    pypi
regex                     2023.12.25               pypi_0    pypi
requests                  2.31.0           py38haa95532_0
requests-oauthlib         1.3.1                    pypi_0    pypi
rich                      13.7.0                   pypi_0    pypi
rpds-py                   0.17.1                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
safetensors               0.2.7                    pypi_0    pypi
scikit-image              0.20.0                   pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.9.1                    pypi_0    pypi
semver                    3.0.2                    pypi_0    pypi
setuptools                68.2.2           py38haa95532_0
six                       1.16.0             pyhd3eb1b0_1
smmap                     5.0.1                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
starlette                 0.35.1                   pypi_0    pypi
streamlit                 1.12.1                   pypi_0    pypi
streamlit-drawable-canvas 0.8.0                    pypi_0    pypi
tb-nightly                2.14.0a20230808          pypi_0    pypi
tensorboard               2.14.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
test-tube                 0.7.5                    pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tifffile                  2023.7.10                pypi_0    pypi
timm                      0.6.12                   pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
tokenizers                0.12.1                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
torchmetrics              0.6.0                    pypi_0    pypi
torchvision               0.13.1               py38_cu113    pytorch
tornado                   6.4                      pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
transformers              4.19.2                   pypi_0    pypi
typing_extensions         4.9.0            py38haa95532_1
tzdata                    2023.4                   pypi_0    pypi
tzlocal                   5.2                      pypi_0    pypi
uc-micro-py               1.0.2                    pypi_0    pypi
urllib3                   1.26.18          py38haa95532_0
uvicorn                   0.27.0                   pypi_0    pypi
validators                0.22.0                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  3.0.0                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webdataset                0.2.5                    pypi_0    pypi
websockets                12.0                     pypi_0    pypi
werkzeug                  3.0.1                    pypi_0    pypi
wheel                     0.41.2           py38haa95532_0
win_inet_pton             1.1.0            py38haa95532_0
xz                        5.4.5                h8cc25b3_0
yapf                      0.32.0                   pypi_0    pypi
yarl                      1.9.4                    pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.5                hd43e919_0
```

### Severity

Blocking usage of gradio

**Comment by FengRuii** [comment]
Hi, thanks for the input.  I upgraded Gradio to 4.16 however I am now getting a different error: 

```
Traceback (most recent call last):
  File "gradio_depth2image.py", line 76, in <module>
    input_image = gr.Image(source='upload', type="numpy")
  File "C:\Users\miniconda3\envs\control\lib\site-packages\gradio\component_meta.py", line 157, in wrapper
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'source'
```

**Comment by abidlabs** [comment]
Hi @FengRuii, `source` has been renamed to `sources` in Gradio 4.0.

Please see here for a list of breaking changes: https://github.com/gradio-app/gradio/issues/6339

Will close for now as the original error should hopefully have been solved, but we can reopen if needed.
