### ISSUE TITLE
server easily overloaded by client config/info setup, massive regression compared to gradio 3

### ISSUE THREAD

**Issue by pseudotensor** [gradio-app/gradio#7169]
### Describe the bug

Excessive CPU usage by gradio 4 for simple client connect ruins the server (no other activity can be handled).  No issue at all for gradio 3.

Easy to spam any gradio server just with api access and lead to denial of service, so is a security issue too.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import time
import concurrent.futures


def server():
    import gradio as gr

    with gr.Blocks() as demo:
        def respond(message, chat_history):
            return "", chat_history

        for i in range(200):
            chatbot = gr.Chatbot()
            msg = gr.Textbox()
            msg.submit(respond, [msg, chatbot], [msg, chatbot])

    demo.launch(show_api=True, prevent_thread_lock=True)


def do_client1(i):
    from gradio_client import Client
    t0 = time.time()
    client = Client('http://localhost:7860')
    print('duration: %s %s' % (i, time.time() - t0))


if __name__ == "__main__":
    server()

    futs = []
    with concurrent.futures.ProcessPoolExecutor() as executor:
        for i in range(0, 64):
            futs.append(executor.submit(do_client1, i))
    for fut in futs:
        print(fut.result())
```
Note local pool is not required, one could use separate pytest -n 64 or separate individual calls and see same thing, just trying to keep the test all in one place.

Run with gradio 3.50.2 and one sees something like 0.6s per call:

However, run with gradio==4.16.0 and it takes about 30s per call, seemingly because the single core for the server is overwhelmed.

Now please note that this repro is just trying to show the issue.  I don't actually have 200 chatbots, but I probably have in h2oGPT about 200 elements overall and hit this issue.

I can't use gradio 4 due to this issue.

### Logs

Also note that nominally one will hit:
```

Traceback (most recent call last):
  File "/home/jon/h2ogpt/issue_slow_setup.py", line 35, in <module>
    print(fut.result())
  File "/data/conda/h2ogpt/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/data/conda/h2ogpt/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
httpx.ReadTimeout: timed out
```

which is also an issue.  I had to manually edit the client.py code so that `httpx.get()` has timeout=60 passed, else hit the long delay.

IMO, the user should be able to control any such timeouts, else it's very confusing when random packages timeout and gradio just reports this and we have no idea why and no ability to control.

When I ping the server, it's busy with alot of json processing, like:
```
Thread 0x00007ff488aff640 (most recent call first):
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 2221 in _make_json_hashable
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 2223 in <genexpr>
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 2223 in _make_json_hashable
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 2221 in <genexpr>
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 2221 in _make_json_hashable
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 2221 in <genexpr>
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 2221 in _make_json_hashable
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 2221 in <genexpr>
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 2221 in _make_json_hashable
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 2216 in <dictcomp>
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 2216 in _deduplicate_schemas
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 175 in from_prioritized_choices
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 2110 in _build_definitions_remapping
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 430 in generate
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 2158 in model_json_schema
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/main.py", line 385 in model_json_schema
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/components/base.py", line 268 in api_info
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/blocks.py", line 2312 in get_api_info
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/routes.py", line 359 in api_info
  File "/home/jon/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851 in run
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/threading.py", line 973 in _bootstrap
```
or:
```
Thread 0x00007ff4a97fe640 (most recent call first):
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 507 in handler_func
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36 in __call__
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2012 in json_schema_update_func
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 544 in new_handler_func
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36 in __call__
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 552 in generate_inner
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 1226 in _named_required_fields_schema
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 1415 in model_fields_schema
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 509 in handler_func
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36 in __call__
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 552 in generate_inner
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 1323 in model_schema
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 509 in handler_func
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36 in __call__
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 212 in modify_model_json_schema
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 526 in new_handler_func
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36 in __call__
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/main.py", line 603 in __get_pydantic_json_schema__
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 526 in new_handler_func
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36 in __call__
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 552 in generate_inner
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 1735 in definitions_schema
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 509 in handler_func
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 36 in __call__
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 552 in generate_inner
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 413 in generate
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/json_schema.py", line 2158 in model_json_schema
  File "/home/jon/.local/lib/python3.10/site-packages/pydantic/main.py", line 385 in model_json_schema
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/components/base.py", line 268 in api_info
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/blocks.py", line 2342 in get_api_info
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/routes.py", line 359 in api_info
  File "/home/jon/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851 in run
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/threading.py", line 973 in _bootstrap

```

many threads doing that, using 100% of 1 core to handle all those threads.  Clearly in gradio 4 something excessive is going on and abusing the CPU, which thrashes the threading and makes it impossible to complete any tasks.

### System Info

```shell
gradio==3.50.2 vs. gradio==4.16.0

Blocking all potential to upgrade to gradio 4, since any traffic to gradio server stalls the server severely.
```

### Severity

Blocking usage of gradio

**Comment by pseudotensor** [comment]
@freddyaboulton Still much slower than gradio 3 by factor of 5x.

```
import time
import concurrent.futures


def server():
    import gradio as gr

    with gr.Blocks() as demo:
        def respond(message, chat_history):
            return "", chat_history

        for i in range(200):
            chatbot = gr.Chatbot()
            msg = gr.Textbox()
            msg.submit(respond, [msg, chatbot], [msg, chatbot])

    demo.launch(show_api=True, prevent_thread_lock=True)


def do_client1(i):
    from gradio_client import Client
    t0 = time.time()
    client = Client('http://localhost:7860')
    print('duration: %s %s' % (i, time.time() - t0))


if __name__ == "__main__":
    server()

    futs = []
    with concurrent.futures.ProcessPoolExecutor() as executor:
        for i in range(0, 64):
            futs.append(executor.submit(do_client1, i))
    for fut in futs:
        print(fut.result())
```

gives:
```
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔Loaded as API: http://localhost:7860/ ✔

duration: 1 1.3192787170410156
Loaded as API: http://localhost:7860/ ✔
duration: 3 1.3861596584320068
Loaded as API: http://localhost:7860/ ✔
duration: 0 1.5812201499938965
Loaded as API: http://localhost:7860/ ✔
duration: 11 1.658273458480835
Loaded as API: http://localhost:7860/ ✔
duration: 4 1.7150487899780273
Loaded as API: http://localhost:7860/ ✔
duration: 6 1.902554988861084
Loaded as API: http://localhost:7860/ ✔
duration: 7 1.9710841178894043
Loaded as API: http://localhost:7860/ ✔
duration: 2 2.0403997898101807
Loaded as API: http://localhost:7860/ ✔
duration: 12 2.1314146518707275
Loaded as API: http://localhost:7860/ ✔
duration: 9 2.212402820587158
Loaded as API: http://localhost:7860/ ✔
duration: 5 2.280294418334961
Loaded as API: http://localhost:7860/ ✔
duration: 15 2.3474130630493164
Loaded as API: http://localhost:7860/ ✔
duration: 10 2.5686707496643066
Loaded as API: http://localhost:7860/ ✔
duration: 8 2.6532583236694336
Loaded as API: http://localhost:7860/ ✔
duration: 13 2.7424912452697754
Loaded as API: http://localhost:7860/ ✔
duration: 14 2.7786831855773926
Loaded as API: http://localhost:7860/ ✔
duration: 16 2.8060505390167236
Loaded as API: http://localhost:7860/ ✔
duration: 17 2.851980686187744
Loaded as API: http://localhost:7860/ ✔
duration: 19 2.6817708015441895
Loaded as API: http://localhost:7860/ ✔
duration: 18 2.8340537548065186
Loaded as API: http://localhost:7860/ ✔
duration: 20 2.841890573501587
Loaded as API: http://localhost:7860/ ✔
duration: 21 2.8056037425994873
Loaded as API: http://localhost:7860/ ✔
duration: 22 2.814274787902832
Loaded as API: http://localhost:7860/ ✔
duration: 23 2.8129594326019287
Loaded as API: http://localhost:7860/ ✔
duration: 25 2.7592408657073975
Loaded as API: http://localhost:7860/ ✔
duration: 29 2.465376138687134
Loaded as API: http://localhost:7860/ ✔
duration: 24 3.050553321838379
Loaded as API: http://localhost:7860/ ✔
duration: 26 3.0029919147491455
Loaded as API: http://localhost:7860/ ✔
duration: 27 3.0265345573425293
Loaded as API: http://localhost:7860/ ✔
duration: 28 2.8320796489715576
Loaded as API: http://localhost:7860/ ✔
duration: 30 2.858151912689209
Loaded as API: http://localhost:7860/ ✔
duration: 31 2.8491430282592773
Loaded as API: http://localhost:7860/ ✔
duration: 32 2.5477635860443115
Loaded as API: http://localhost:7860/ ✔
duration: 34 2.683720111846924
Loaded as API: http://localhost:7860/ ✔
duration: 33 2.876636505126953
Loaded as API: http://localhost:7860/ ✔
duration: 36 2.6252429485321045
Loaded as API: http://localhost:7860/ ✔
duration: 35 2.8493921756744385
Loaded as API: http://localhost:7860/ ✔
duration: 37 2.6727657318115234
Loaded as API: http://localhost:7860/ ✔
duration: 38 2.7684290409088135
Loaded as API: http://localhost:7860/ ✔
duration: 39 2.7702994346618652
Loaded as API: http://localhost:7860/ ✔
duration: 42 2.5517125129699707
Loaded as API: http://localhost:7860/ ✔
duration: 41 2.686220407485962
Loaded as API: http://localhost:7860/ ✔
duration: 40 2.92683482170105
Loaded as API: http://localhost:7860/ ✔
duration: 43 2.6855688095092773
Loaded as API: http://localhost:7860/ ✔
duration: 44 2.6775248050689697
Loaded as API: http://localhost:7860/ ✔
duration: 45 2.8270394802093506
Loaded as API: http://localhost:7860/ ✔
duration: 46 2.7916958332061768
Loaded as API: http://localhost:7860/ ✔
duration: 47 2.9029626846313477
Loaded as API: http://localhost:7860/ ✔
duration: 48 2.807755947113037
duration: 50 2.7048895359039307
duration: 51 2.7057607173919678
duration: 52 2.731238603591919
duration: 49 3.037794828414917
duration: 53 2.769714117050171
duration: 54 2.6628222465515137
duration: 55 2.7716708183288574
duration: 56 2.755613088607788
duration: 59 2.6149742603302
duration: 58 2.757035493850708
duration: 60 2.705479145050049
duration: 61 2.6512837409973145
duration: 57 3.1461868286132812
duration: 62 2.709378242492676
duration: 63 2.6261589527130127
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
```

on build off head of main for gradio.

However, if I revert to gradio==3.50.2 (and related client) exact same script gives:

```
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loaded as API: http://localhost:7860/ ✔Loaded as API: http://localhost:7860/ ✔

Loaded as API: http://localhost:7860/ ✔Loaded as API: http://localhost:7860/ ✔

Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔Loaded as API: http://localhost:7860/ ✔

Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔
Loaded as API: http://localhost:7860/ ✔Loaded as API: http://localhost:7860/ ✔

duration: 3 0.08678269386291504
Loaded as API: http://localhost:7860/ ✔
duration: 1 0.12864255905151367
Loaded as API: http://localhost:7860/ ✔
duration: 4 0.18710064888000488
Loaded as API: http://localhost:7860/ ✔
duration: 6 0.2301161289215088
Loaded as API: http://localhost:7860/ ✔
duration: 2 0.26844096183776855
Loaded as API: http://localhost:7860/ ✔
duration: 0 0.3366553783416748
Loaded as API: http://localhost:7860/ ✔
duration: 5 0.41399216651916504
Loaded as API: http://localhost:7860/ ✔
duration: 8 0.442887544631958
Loaded as API: http://localhost:7860/ ✔
duration: 9 0.49597930908203125
Loaded as API: http://localhost:7860/ ✔
duration: 7 0.5131330490112305
Loaded as API: http://localhost:7860/ ✔
duration: 10 0.5708472728729248
Loaded as API: http://localhost:7860/ ✔
duration: 11 0.6323947906494141
Loaded as API: http://localhost:7860/ ✔
duration: 14 0.6725714206695557
Loaded as API: http://localhost:7860/ ✔
duration: 12 0.6954843997955322
Loaded as API: http://localhost:7860/ ✔
duration: 15 0.7379050254821777
Loaded as API: http://localhost:7860/ ✔
duration: 13 0.8171801567077637
Loaded as API: http://localhost:7860/ ✔
duration: 16 0.7890558242797852
Loaded as API: http://localhost:7860/ ✔
duration: 17 0.7741677761077881
Loaded as API: http://localhost:7860/ ✔
duration: 18 0.7658417224884033
Loaded as API: http://localhost:7860/ ✔
duration: 19 0.7922635078430176
Loaded as API: http://localhost:7860/ ✔
duration: 20 0.8044064044952393
Loaded as API: http://localhost:7860/ ✔
duration: 21 0.8384149074554443
Loaded as API: http://localhost:7860/ ✔
duration: 22 0.8233702182769775
Loaded as API: http://localhost:7860/ ✔
duration: 23 0.8097338676452637
Loaded as API: http://localhost:7860/ ✔
duration: 24 0.7974309921264648
Loaded as API: http://localhost:7860/ ✔
duration: 25 0.8207898139953613
Loaded as API: http://localhost:7860/ ✔
duration: 26 0.7990880012512207
Loaded as API: http://localhost:7860/ ✔
duration: 27 0.8041729927062988
Loaded as API: http://localhost:7860/ ✔
duration: 28 0.7869372367858887
Loaded as API: http://localhost:7860/ ✔
duration: 29 0.8267819881439209
Loaded as API: http://localhost:7860/ ✔
duration: 30 0.8017456531524658
Loaded as API: http://localhost:7860/ ✔
duration: 31 0.7629446983337402
Loaded as API: http://localhost:7860/ ✔
duration: 33 0.7259135246276855
Loaded as API: http://localhost:7860/ ✔
duration: 32 0.7923059463500977
Loaded as API: http://localhost:7860/ ✔
duration: 34 0.7567098140716553
Loaded as API: http://localhost:7860/ ✔
duration: 35 0.7279303073883057
Loaded as API: http://localhost:7860/ ✔
duration: 37 0.6168227195739746
Loaded as API: http://localhost:7860/ ✔
duration: 36 0.7795579433441162
Loaded as API: http://localhost:7860/ ✔
duration: 38 0.642136812210083
Loaded as API: http://localhost:7860/ ✔
duration: 39 0.654090404510498
Loaded as API: http://localhost:7860/ ✔
duration: 40 0.6602482795715332
Loaded as API: http://localhost:7860/ ✔
duration: 41 0.681286096572876
Loaded as API: http://localhost:7860/ ✔
duration: 42 0.6869003772735596
Loaded as API: http://localhost:7860/ ✔
duration: 43 0.6654376983642578
Loaded as API: http://localhost:7860/ ✔
duration: 44 0.6780803203582764
Loaded as API: http://localhost:7860/ ✔
duration: 45 0.6603858470916748
Loaded as API: http://localhost:7860/ ✔
duration: 46 0.6789207458496094
Loaded as API: http://localhost:7860/ ✔
duration: 47 0.6780996322631836
Loaded as API: http://localhost:7860/ ✔
duration: 48 0.6710684299468994
duration: 49 0.6716887950897217
duration: 50 0.671778678894043
duration: 51 0.667771577835083
duration: 52 0.6661367416381836
duration: 53 0.6686456203460693
duration: 54 0.6555113792419434
duration: 56 0.6208791732788086
duration: 55 0.731945276260376
duration: 58 0.6189899444580078
duration: 57 0.7234225273132324
duration: 59 0.6720647811889648
duration: 60 0.6730806827545166
duration: 61 0.6654307842254639
duration: 62 0.6870317459106445
duration: 63 0.6661834716796875
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
```

**Comment by pseudotensor** [comment]
I'd recommend re-opening and considering what else makes this slow.

**Comment by freddyaboulton** [comment]
@pseudotensor just making sure you installed the client locally from source as well when building gradio? If you just install gradio from source, the client will be installed from PyPi which does not have the fix from my PR.
