### ISSUE TITLE
[Blocks] `State` throws a js error 

### ISSUE THREAD

**Issue by aliabd** [gradio-app/gradio#730]
### Describe the bug

Using `State` with `Chatbot` throws an error.

### Reproduction

```python 
import gradio as gr


def chat(message, history):
    history = history or []
    history.append((message, message))
    return history, history


block = gr.Blocks()


with block:
    chatbot = gr.outputs.Chatbot()
    message = gr.inputs.Textbox()
    submit = gr.Button("SEND")
    submit.click(chat, inputs=[message, gr.inputs.State()], outputs=[chatbot, gr.outputs.State()])


block.launch()
```

Throws this console error:

```
index.800943b3.js:14 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'component')
    at Array.uu (index.800943b3.js:14:7188)
    at kn (index.800943b3.js:14:9671)
    at du (index.800943b3.js:14:10040)
    at Qs (vendor.ba9f2ee9.js:1:6986)
    at new nt (index.800943b3.js:14:11214)
    at hu (index.800943b3.js:14:11379)
    at Qs (vendor.ba9f2ee9.js:1:6986)
    at new bu (index.800943b3.js:14:12689)
    at window.launchGradio (index.800943b3.js:14:15525)
    at index.800943b3.js:14:15863
uu @ index.800943b3.js:14
kn @ index.800943b3.js:14
du @ index.800943b3.js:14
Qs @ vendor.ba9f2ee9.js:1
nt @ index.800943b3.js:14
hu @ index.800943b3.js:14
Qs @ vendor.ba9f2ee9.js:1
bu @ index.800943b3.js:14
window.launchGradio @ index.800943b3.js:14
(anonymous) @ index.800943b3.js:14
Promise.then (async)
(anonymous) @ index.800943b3.js:14
```
Nothing is rendered on the page. 

Replacing the block launch with 
```python
gr.Interface(chat, [message, gr.inputs.State()], [chatbot, gr.outputs.State()]).launch()
```
works as expected

### System Info

```shell
gradio v2.8.0b20
```

### Severity

blocker

**Comment by abidlabs** [comment]
Different error, but still an issue. 

Try running `demo/chatbot/run.py` to reproduce

**Comment by abidlabs** [comment]
Closed via #977

**Comment by satpalsr** [comment]
Hey @abidlabs , There is still an issue. [Reproduce with colab](https://colab.research.google.com/drive/1WZQe7kFNArF065Do34Ds4O5Ez4G8QzQC?usp=sharing) or check out this [space](satpalsr/chat-test). The space just keeps loading.

**Comment by FarukOzderim** [comment]
@aliabid94 could you take a look?

**Comment by abidlabs** [comment]
I've been looking into this issue and can take it!

**Comment by abidlabs** [comment]
Thanks @aliabd for creating the issue, this should be fixed now in the following way:

```py
import gradio as gr


def chat(message, history):
    history = history or []
    history.append((message, message))
    return history, history


block = gr.Blocks()


with block:
    chatbot = gr.Chatbot()
    message = gr.Textbox()
    state = gr.State()
    submit = gr.Button("SEND")
    submit.click(chat, inputs=[message, state], outputs=[chatbot, state])


block.launch()
```
