### ISSUE TITLE
Gradio can't handle images in HEIC format

### ISSUE THREAD

**Issue by smikhai1** [gradio-app/gradio#7482]
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
I've implemented a simple demo to demonstrate the problem. The demo consists of two image components: for input and output images respectively. The output image is just a copy of the input one for simplicity.

```python
from PIL import Image
import gradio as gr


def identity_fn(img: Image) -> Image:
    return img


def main():
    with gr.Blocks() as demo:
        with gr.Row():
            with gr.Column():
                input_img = gr.Image(label='Input image', sources=['upload', 'clipboard'],
                                     elem_id='input_image', type='pil')
                run_btn = gr.Button(value='Run')

            with gr.Column():
                output_img = gr.Image(label='Output image', interactive=False,
                                      elem_id='output_image', type='pil')

        run_btn.click(fn=identity_fn, inputs=[input_img],
                      outputs=[output_img])

    demo.launch(server_name="0.0.0.0", server_port=7606)


if __name__ == '__main__':
    main()
``` 

When I upload image in HEIC format taken on my iPhone camera, I got the following error:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 233, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1604, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1335, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/image.py", line 167, in preprocess
    im = PIL.Image.open(file_path)
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '/tmp/gradio/cc9ca9309c159697f76994c7fa712cf42bc0f7bb/IMG_1022.HEIC'
```

<img width="1255" alt="error_example" src="https://github.com/gradio-app/gradio/assets/43113925/5e6105f3-14bf-45e5-9725-23145fd644fd">

So from the traceback and the source code, I found out that the problem arises when we load the image with `PIL.Image.open`

**Describe the solution you'd like**  
The simplest solution is to use PIL's plugin, which adds HEIC support. You can find details in [this](https://stackoverflow.com/a/69988418) StackOverflow answer

**Additional context**  
Environment I used for the fronted:
- Browser: Safari
- OS: MacOS Sonoma 14.2.1 
- Browser: Safari

And for the backend:
- OS: Ubuntu 22.04.3
- python=3.10.12
- gradio==4.19.1

**Comment by abidlabs** [comment]
Hi @smikhai1 thanks for creating the PR. I'll respond there!

**Comment by abidlabs** [comment]
Please see the comments in the PR
