### ISSUE TITLE
[Model3D] reset button doesn't work

### ISSUE THREAD

**Issue by whitphx** [gradio-app/gradio#7484]
### Describe the bug

When clicking the reset button, the following error occurs.
```
Model3D.svelte:40 Uncaught TypeError: canvas3d.reset_camera_position is not a function
    at handle_undo (Model3D.svelte:40:12)
    at HTMLButtonElement.click_handler (Model3D.svelte:78:57)
    at svelte.js:2009:40
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.bubble (svelte.js:2009:21)
    at HTMLButtonElement.click_handler (IconButton.svelte:14:58)
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def identity(x):
    return x

demo = gr.Interface(
    identity,
    gr.Model3D(),
    gr.Model3D(),
)

if __name__ == "__main__":
    demo.launch()
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.19.1
gradio_client version: 0.10.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.1.0
altair: 5.0.1
fastapi: 0.104.1
ffmpy: 0.3.0
gradio-client==0.10.0 is not installed.
httpx: 0.24.1
huggingface-hub: 0.20.1
importlib-resources: 6.1.0
jinja2: 3.1.2
markupsafe: 2.1.2
matplotlib: 3.7.1
numpy: 1.24.3
orjson: 3.8.14
packaging: 23.1
pandas: 2.0.2
pillow: 9.5.0
pydantic: 2.5.0
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0
ruff: 0.2.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.8.0
uvicorn: 0.22.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.5.0
httpx: 0.24.1
huggingface-hub: 0.20.1
packaging: 23.1
typing-extensions: 4.8.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by whitphx** [comment]
This bug was introduced in #7406?
