### ISSUE TITLE
TypeError: Option() missing 1 required positional argument: 'default'

### ISSUE THREAD

**Issue by ahbon123** [gradio-app/gradio#7512]
### Describe the bug

I installed the gradio library using pip install gradio, but a TypeError occurred when importing the package: Option() missing 1 required positional argument: 'default'.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import gradio as gr
Traceback (most recent call last):
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3548, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-43eca54f7d45>", line 1, in <module>
    import gradio as gr
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/gradio/__init__.py", line 10, in <module>
    from gradio.cli import deploy
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/gradio/cli/__init__.py", line 1, in <module>
    from .cli import cli, deploy
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/gradio/cli/cli.py", line 4, in <module>
    from gradio_client.cli import deploy_discord  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/gradio_client/cli/__init__.py", line 1, in <module>
    from gradio_client.cli import deploy_discord
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/gradio_client/cli/deploy_discord.py", line 12, in <module>
    Option(
TypeError: Option() missing 1 required positional argument: 'default'
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/15428667/516a0795-bfa6-49e4-a79e-73a141de20f6)

### System Info

```shell
Mac OS, Pycharm
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @ahbon123 it looks like you might be using an older version of `typer`. Can you report which version of `typer` you have installed and try `pip install --upgrade typer`?

**Comment by ahbon123** [comment]
Thanks for your help. I run `pip install --upgrade typer` but the issue still exists.

```
(base) mac@localhost ~ % pip install --upgrade typer
Requirement already satisfied: typer in ./anaconda3/lib/python3.11/site-packages (0.9.0)
Requirement already satisfied: click<9.0.0,>=7.1.1 in ./anaconda3/lib/python3.11/site-packages (from typer) (8.1.7)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./anaconda3/lib/python3.11/site-packages (from typer) (4.8.0)
(base) mac@localhost ~ % python
Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gradio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/gradio/__init__.py", line 10, in <module>
    from gradio.cli import deploy
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/gradio/cli/__init__.py", line 1, in <module>
    from .cli import cli, deploy
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/gradio/cli/cli.py", line 4, in <module>
    from gradio_client.cli import deploy_discord  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/gradio_client/cli/__init__.py", line 1, in <module>
    from gradio_client.cli import deploy_discord
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/gradio_client/cli/deploy_discord.py", line 12, in <module>
    Option(
TypeError: Option() missing 1 required positional argument: 'default'
```

**Comment by abidlabs** [comment]
Hmm that's very strange, there's definitely something up with the installation of `typer`, because as you can see, in `typer==0.9.0`, `default` is not a required argument:

<img width="629" alt="image" src="https://github.com/gradio-app/gradio/assets/1778297/48a3ca75-3af5-4a1f-bfde-7c30560fd33a">

A similar issue is here: https://github.com/tiangolo/typer/discussions/656 so I'm quite sure this is an issue with `typer` and not related to `gradio`

**Comment by ahbon123** [comment]
> Hmm that's very strange, there's definitely something up with the installation of `typer`, because as you can see, in `typer==0.9.0`, `default` is not a required argument:
> 
> <img alt="image" width="629" src="https://private-user-images.githubusercontent.com/1778297/307204254-48a3ca75-3af5-4a1f-bfde-7c30560fd33a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTkzNTUsIm5iZiI6MTcwODY1OTA1NSwicGF0aCI6Ii8xNzc4Mjk3LzMwNzIwNDI1NC00OGEzY2E3NS0zYWY1LTRhMWYtYmZkZS03YzMwNTYwZmQzM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjNUMDMzMDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE3NjBkMDJlMGRmODg0ZGMwZDYzMjBmZWY5NmU5ZmM0ZDYxYWQxZDkyZjE2YmNjODk5MTFlY2UyMzQ5YWI3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._DArxFgzizLZu5kLOQDoFs8FF2Rlo9Ou_-vWLubpmSk">
> A similar issue is here: [tiangolo/typer#656](https://github.com/tiangolo/typer/discussions/656) so I'm quite sure this is an issue with `typer` and not related to `gradio`

You are right. I uninstalled `typer` and then used `pip install "typer[all]"` (from [typer](https://github.com/tiangolo/typer)) to install the package. `gradio` package can be imported correctly.

**Comment by abidlabs** [comment]
Ok great! Closing
