### ISSUE TITLE
client.predict ValueError: None

### ISSUE THREAD

**Issue by keeper-jie** [gradio-app/gradio#7573]
### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

## gradio server python code: 
```python
import gradio as gr
import os

def video_identity(video):
    return video

demo = gr.Interface(video_identity, 
                    gr.Video(), 
                    "playable_video", 
                    examples=[
                        os.path.join(os.path.dirname(__file__), 
                                     "res/fall_detect/N/aaaaa20240221_083819.mp4")])

if __name__ == "__main__":
    demo.launch(server_name='10.10.30.30', server_port=8889)
```

## gradio client code:
```python
from gradio_client import Client

client = Client("http://10.10.30.30:8889") 
# view gradio interface
api=client.view_api(return_format="dict")
print(api)

# ValueError: None
# result = client.predict('/home/liujie/gradio/demo/res/fall_detect/N/aaaaa20240221_083819.mp4', api_name="/predict")
# print(result)

# ValueError: None
job = client.submit('/home/liujie/gradio/demo/res/fall_detect/N/aaaaa20240221_083819.mp4',api_name="/predict") 
data=job.result(timeout=600)
print(data)
```

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/33612777/532c299b-2e1e-4720-8ebe-0b8682a3df2b)

### Logs

```shell
## client.predict error

Traceback (most recent call last):
  File "/home/liujie/miniconda3/envs/demo/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/liujie/miniconda3/envs/demo/lib/python3.10/site-packages/gradio/route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/liujie/miniconda3/envs/demo/lib/python3.10/site-packages/gradio/blocks.py", line 1618, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/liujie/miniconda3/envs/demo/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/liujie/miniconda3/envs/demo/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/home/liujie/miniconda3/envs/demo/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/liujie/miniconda3/envs/demo/lib/python3.10/site-packages/gradio/blocks.py", line 1336, in preprocess_data
    inputs_cached = block.data_model(**inputs_cached)  # type: ignore
  File "/home/liujie/miniconda3/envs/demo/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for VideoData
video
  Field required [type=missing, input_value={'path': '/tmp/gradio/dcb...one, 'is_stream': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
```

## client.submit error
```
Traceback (most recent call last):
  File "/home/liujie/miniconda3/envs/demo/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/liujie/miniconda3/envs/demo/lib/python3.10/site-packages/gradio/route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/liujie/miniconda3/envs/demo/lib/python3.10/site-packages/gradio/blocks.py", line 1618, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/liujie/miniconda3/envs/demo/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/liujie/miniconda3/envs/demo/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/home/liujie/miniconda3/envs/demo/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/liujie/miniconda3/envs/demo/lib/python3.10/site-packages/gradio/blocks.py", line 1336, in preprocess_data
    inputs_cached = block.data_model(**inputs_cached)  # type: ignore
  File "/home/liujie/miniconda3/envs/demo/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for VideoData
video
  Field required [type=missing, input_value={'path': '/tmp/gradio/dcb...one, 'is_stream': False}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
```

### System Info

```shell
# pip list output:

Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.19.2
gradio_client version: 0.10.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.108.0
ffmpy: 0.3.1
gradio-client==0.10.1 is not installed.
httpx: 0.26.0
huggingface-hub: 0.20.2
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.8.2
numpy: 1.26.3
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.4
pillow: 10.2.0
pydantic: 2.5.3
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.2.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.9.0
uvicorn: 0.25.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.12.2
httpx: 0.26.0
huggingface-hub: 0.20.2
packaging: 23.2
typing-extensions: 4.9.0
websockets: 11.0.3
```

## client.view_api output:
```
Loaded as API: http://10.10.30.30:8889/ ✔
Client.predict() Usage Info
---------------------------
Named API endpoints: 1

 - predict(video, api_name="/predict") -> output
    Parameters:
     - [Video] video: Dict(video: filepath, subtitles: filepath | None) 
    Returns:
     - [Video] output: Dict(video: filepath, subtitles: filepath | None) 

{'named_endpoints': {'/predict': {'parameters': [{'label': 'video', 'type': {'$defs': {'FileData': {'properties': {'path': {'title': 'Path', 'type': 'string'}, 'url': {'anyOf': [{'type': 'string'}, {'type': 'null'}], 'default': None, 'title': 'Url'}, 'size': {'anyOf': [{'type': 'integer'}, {'type': 'null'}], 'default': None, 'title': 'Size'}, 'orig_name': {'anyOf': [{'type': 'string'}, {'type': 'null'}], 'default': None, 'title': 'Orig Name'}, 'mime_type': {'anyOf': [{'type': 'string'}, {'type': 'null'}], 'default': None, 'title': 'Mime Type'}, 'is_stream': {'default': False, 'title': 'Is Stream', 'type': 'boolean'}}, 'required': ['path'], 'title': 'FileData', 'type': 'object'}}, 'properties': {'video': {'$ref': '#/$defs/FileData'}, 'subtitles': {'anyOf': [{'$ref': '#/$defs/FileData'}, {'type': 'null'}], 'default': None}}, 'required': ['video'], 'title': 'VideoData', 'type': 'object'}, 'python_type': {'type': 'Dict(video: filepath, subtitles: filepath | None)', 'description': ''}, 'component': 'Video', 'example_input': {'video': 'https://github.com/gradio-app/gradio/raw/main/demo/video_component/files/world.mp4', 'subtitles': None}}], 'returns': [{'label': 'output', 'type': {'$defs': {'FileData': {'properties': {'path': {'title': 'Path', 'type': 'string'}, 'url': {'anyOf': [{'type': 'string'}, {'type': 'null'}], 'default': None, 'title': 'Url'}, 'size': {'anyOf': [{'type': 'integer'}, {'type': 'null'}], 'default': None, 'title': 'Size'}, 'orig_name': {'anyOf': [{'type': 'string'}, {'type': 'null'}], 'default': None, 'title': 'Orig Name'}, 'mime_type': {'anyOf': [{'type': 'string'}, {'type': 'null'}], 'default': None, 'title': 'Mime Type'}, 'is_stream': {'default': False, 'title': 'Is Stream', 'type': 'boolean'}}, 'required': ['path'], 'title': 'FileData', 'type': 'object'}}, 'properties': {'video': {'$ref': '#/$defs/FileData'}, 'subtitles': {'anyOf': [{'$ref': '#/$defs/FileData'}, {'type': 'null'}], 'default': None}}, 'required': ['video'], 'title': 'VideoData', 'type': 'object'}, 'python_type': {'type': 'Dict(video: filepath, subtitles: filepath | None)', 'description': ''}, 'component': 'Video'}]}}, 'unnamed_endpoints': {}}
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @keeper-jie for `Video` inputs, you need to supply the data in this format: `Dict(video: filepath, subtitles: filepath | None)`, so this works:

Server code (no changes needed here):

```py
import gradio as gr
import os

def video_identity(video):
    return video

demo = gr.Interface(video_identity, 
                    gr.Video(), 
                    "playable_video", 
)

if __name__ == "__main__":
    _, url, _ = demo.launch()
```

Client code:

```
from gradio_client import Client

client = Client(url) 

api=client.view_api(return_format="dict")
job = client.submit({'video': 'test.mp4'}, api_name="/predict") 
data=job.result(timeout=600)
print(data)
```

**Comment by RectalWorm** [comment]
![Gradio Client not working with any multimodal models](https://github.com/gradio-app/gradio/assets/129939078/1cc6ca14-09e8-4654-a881-b55600ad740e)
