### ISSUE TITLE
Has anyone encountered a situation where the program can run normally independently, only occupying 2GB of GPU memory, but when running through Gradio, it reports the error torch.cuda.OutOfMemoryError?

### ISSUE THREAD

**Issue by liuxuan111** [gradio-app/gradio#7622]
details:
Traceback (most recent call last):
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/gradio/queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "app.py", line 27, in get_video
    test(img_path,model_name,positive_prompt)
  File "/home/liuxuan/Desktop/photomaker/test.py", line 231, in test
    output = makevideo(fps=100)
  File "/home/liuxuan/Desktop/photomaker/inference_img.py", line 96, in makevideo
    mid = model.inference(img_list[j], img_list[j + 1])
  File "/home/liuxuan/Desktop/photomaker/train_log/RIFE_HDv3.py", line 58, in inference
    flow, mask, merged = self.flownet(imgs, scale_list)
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/liuxuan/Desktop/photomaker/train_log/IFNet_HDv3.py", line 101, in forward
    f0, m0 = block[i](torch.cat((warped_img0[:, :3], warped_img1[:, :3], mask), 1), flow, scale=ada_scale[i])
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/liuxuan/Desktop/photomaker/train_log/IFNet_HDv3.py", line 61, in forward
    feat = self.convblock0(feat) + feat
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 1364, in forward
    return F.prelu(input, self.weight)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 24.00 MiB. GPU 0 has a total capacity of 10.75 GiB of which 23.50 MiB is free. Including non-PyTorch memory, this process has 10.73 GiB memory in use. Of the allocated memory 9.52 GiB is allocated by PyTorch, and 197.87 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
AgingDataLoader
Traceback (most recent call last):
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/gradio/queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "app.py", line 27, in get_video
    test(img_path,model_name,positive_prompt)
  File "/home/liuxuan/Desktop/photomaker/test.py", line 225, in test
    generate_face(model_name, img_path)
  File "/home/liuxuan/Desktop/photomaker/LATS/face_age.py", line 31, in generate_face
    data_loader = CreateDataLoader(opt)
  File "/home/liuxuan/Desktop/photomaker/LATS/data/data_loader.py", line 38, in CreateDataLoader
    data_loader.initialize(opt)
  File "/home/liuxuan/Desktop/photomaker/LATS/data/data_loader.py", line 13, in initialize
    self.dataset = CreateDataset(opt)
  File "/home/liuxuan/Desktop/photomaker/LATS/data/data_loader.py", line 31, in CreateDataset
    dataset.initialize(opt)
  File "/home/liuxuan/Desktop/photomaker/LATS/data/multiclass_unaligned_dataset.py", line 100, in initialize
    self.preprocessor = preprocessInTheWildImage(out_size=opt.fineSize)
  File "/home/liuxuan/Desktop/photomaker/LATS/util/preprocess_itw_im.py", line 51, in __init__
    self.deeplab_model = getattr(deeplab, 'resnet101')(
  File "/home/liuxuan/Desktop/photomaker/LATS/util/deeplab.py", line 235, in resnet101
    pretrained_dict = torch.load('models/R-101-GN-WS.pth.tar')
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/serialization.py", line 1268, in _legacy_load
    result = unpickler.load()
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/serialization.py", line 1205, in persistent_load
    wrap_storage=restore_location(obj, location),
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/serialization.py", line 391, in default_restore_location
    result = fn(storage, location)
  File "/home/liuxuan/.conda/envs/FA/lib/python3.8/site-packages/torch/serialization.py", line 269, in _cuda_deserialize
    return torch.UntypedStorage(obj.nbytes(), device=torch.device(location))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB. GPU 0 has a total capacity of 10.75 GiB of which 3.50 MiB is free. Including non-PyTorch memory, this process has 10.75 GiB memory in use. Of the allocated memory 9.56 GiB is allocated by PyTorch, and 169.00 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by abidlabs** [comment]
Hi @liuxuan111 can you please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by abidlabs** [comment]
Closing for now, for lack of repro. Happy to reopen if we have a way to reproduce the issue consistently.
