### ISSUE TITLE
Why i cannot call predict of a hugging space function?

### ISSUE THREAD

**Issue by Akin1995** [gradio-app/gradio#7634]
### Describe the bug

I want to call a model from hugging face [https://huggingface.co/spaces/hysts/ControlNet-v1-1](url) in my code.
The problem is i get a serialize error and do not know why? The return type is wrtten in the documentation!

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```

import fastapi
from gradio_client import Client
from pydantic import Field, BaseModel

router = fastapi.APIRouter(tags=["Controlnet Router"])
client = Client("https://hysts-controlnet-v1-1.hf.space/")


class ControlnetOptions(BaseModel):
    path: str = Field(...,
                      description="str (Filepath on your computer (or URL) of image) in 'parameter_8' Image component")
    prompt: str = Field(..., description="The prompt of the image")
    additional: str = Field(..., description="Additional prompt")
    seed: float = Field(..., description="(Numeric value between 1 and 1) in 'Number of images' Slider component")


def generate_image(path: str, prompt: str, additional: str,
                   seed: float, ):
    result = client.predict(
        path,
        prompt,  # str  in 'Prompt' Textbox component
        additional,  # str  in 'Additional prompt' Textbox component
        "longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, "
        "worst quality, low quality",  # str  in 'Negative prompt' Textbox component
        1,  # int | float (numeric value between 1 and 1) in 'Number of images' Slider component
        768,  # int | float (numeric value between 256 and 768) in 'Image resolution' Slider component
        20,  # int | float (numeric value between 1 and 100) in 'Number of steps' Slider component
        9,  # int | float (numeric value between 0.1 and 30.0) in 'Guidance scale' Slider component
        seed,  # int | float (numeric value between 0 and 2147483647) in 'Seed' Slider component
        100,  # int | float (numeric value between 1 and 255) in 'Canny low threshold' Slider component
        200,  # int | float (numeric value between 1 and 255) in 'Canny high threshold' Slider component
        api_name="/canny"
    )

    return result
```
```

import gradio as gr
from src.tools.controlnet import generate_image

css = """img {object-fit: fill !important};footer {visibility: hidden};"""
with gr.Blocks(css=css, theme=gr.themes.Default(text_size=gr.themes.sizes.text_lg,
                                                font=gr.themes.GoogleFont("Monospace"))) as gradio_interface:
    image_path = search_file_in_given_directory(os.getcwd(), "Ella-Logo-transparent.png")
    gr.Image(value=image_path, width=150, height=150, interactive=False,
             show_label=False, show_download_button=False, show_share_button=False, container=False)
    analytics_enabled = False
    gr.Markdown("MLToolkit demo, use any of the available tools!")

    suggested_output_styles = ["emotional", "narrative", "neutral", "philosophical", "sensational",
                               "suspenseful", "polite"]

    with gr.Tab(Tools.CONTROLNET): #Just the name
        input_image = gr.Image()
        input_controlnet_text = gr.Textbox(lines=10, label="Input")
        additional_controlnet_input = gr.Textbox(lines=10, label="Additional input")
        seed = gr.Number(label="Random seed")
        button_control = gr.Button("Convert picture")
        output_image = gr.Gallery(label="Output", interactive=True)

    button_control.click(generate_image, inputs=[input_image, input_controlnet_text, additional_controlnet_input, seed], outputs=output_image)
```

### Screenshot

![Bildschirmfoto vom 2024-03-07 10-56-33](https://github.com/gradio-app/gradio/assets/33101550/403e8846-c6b8-4983-9480-57c5169ece22)

### Logs

```shell
Traceback (most recent call last):
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/site-packages/gradio/route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/site-packages/gradio/blocks.py", line 1627, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/site-packages/gradio/blocks.py", line 1173, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/site-packages/gradio/utils.py", line 690, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/akin/Schreibtisch/mltoolkit/src/tools/controlnet.py", line 19, in generate_image
    result = client.predict(
             ^^^^^^^^^^^^^^^
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/site-packages/gradio_client/client.py", line 404, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/site-packages/gradio_client/client.py", line 1612, in result
    return super().result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/site-packages/gradio_client/client.py", line 1279, in _inner
    data = self.serialize(*data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/site-packages/gradio_client/client.py", line 1447, in serialize
    o = tuple([s.serialize(d) for s, d in zip(self.serializers, data)])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/site-packages/gradio_client/client.py", line 1447, in <listcomp>
    o = tuple([s.serialize(d) for s, d in zip(self.serializers, data)])
               ^^^^^^^^^^^^^^
  File "/home/akin/miniconda3/envs/ml_toolkit/lib/python3.11/site-packages/gradio_client/serializing.py", line 183, in serialize
    if not x:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### System Info

```shell
anthropic==0.9.*
deepl==1.16.*
elevenlabs==0.2.*
google-cloud-aiplatform==1.39.*
langdetect==1.0.*
openai==1.7.*
termcolor==2.4.*
tiktoken==0.5.*

# webapp
fastapi==0.110.*
pydantic==2.5.*
pydantic-settings==2.1.*
uvicorn[standard]==0.25.*
gradio==4.19.*

# database
pymongo[srv]==4.6.*
motor==3.3.*
beanie==1.24.*

# GCP
google-cloud-core==2.4.*
google-cloud-logging==3.9.*
google-cloud-pubsub==2.19.*

# test requirements
coverage==7.4.*
pytest==7.4.*
pytest-asyncio==0.23.*
httpx==0.26.*
mongomock-motor==0.0.*

# Authentication
# python-jose[cryptography]

toml==0.10.*
```

### Severity

I can work around it

**Comment by Akin1995** [comment]
Solved issue by gr.Image(type="filepath")
