### ISSUE TITLE
Gradio barfs when imported under Python 3.8

### ISSUE THREAD

**Issue by brorson** [gradio-app/gradio#7652]
### Describe the bug

Gradio barfs under Python 3.8 with the below spew.  Dependency hell -- why do I need unicode support just to run gradio?

gradio waldo_app.py 
Traceback (most recent call last):
  File "/home/sdb/.local/bin/gradio", line 5, in <module>
    from gradio.cli import cli
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/components/annotated_image.py", line 14, in <module>
    from gradio.components.base import Component
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/components/base.py", line 20, in <module>
    from gradio.blocks import Block, BlockContext
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/blocks.py", line 29, in <module>
    from gradio import (
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/networking.py", line 20, in <module>
    from gradio.routes import App
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/routes.py", line 48, in <module>
    from fastapi.templating import Jinja2Templates
  File "/home/sdb/.local/lib/python3.8/site-packages/fastapi/templating.py", line 1, in <module>
    from starlette.templating import Jinja2Templates as Jinja2Templates  # noqa
  File "/home/sdb/.local/lib/python3.8/site-packages/starlette/templating.py", line 14, in <module>
    import jinja2
  File "/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.8/dist-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/sdb/.local/lib/python3.8/site-packages/markupsafe/__init__.py)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Here's an ipython session:

ipython
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import gradio as gr                                                                                                  
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-43eca54f7d45> in <module>
----> 1 import gradio as gr

~/.local/lib/python3.8/site-packages/gradio/__init__.py in <module>
      1 import json
      2 
----> 3 import gradio._simple_templates
      4 import gradio.image_utils
      5 import gradio.processing_utils

~/.local/lib/python3.8/site-packages/gradio/_simple_templates/__init__.py in <module>
----> 1 from .simpledropdown import SimpleDropdown
      2 from .simpleimage import SimpleImage
      3 from .simpletextbox import SimpleTextbox
      4 
      5 __all__ = ["SimpleDropdown", "SimpleTextbox", "SimpleImage"]

~/.local/lib/python3.8/site-packages/gradio/_simple_templates/simpledropdown.py in <module>
      4 from typing import Any, Callable
      5 
----> 6 from gradio.components.base import FormComponent
      7 from gradio.events import Events
      8 

~/.local/lib/python3.8/site-packages/gradio/components/__init__.py in <module>
----> 1 from gradio.components.annotated_image import AnnotatedImage
      2 from gradio.components.audio import Audio
      3 from gradio.components.bar_plot import BarPlot
      4 from gradio.components.base import (
      5     Component,

~/.local/lib/python3.8/site-packages/gradio/components/annotated_image.py in <module>
     12 
     13 from gradio import processing_utils, utils
---> 14 from gradio.components.base import Component
     15 from gradio.data_classes import FileData, GradioModel
     16 from gradio.events import Events

~/.local/lib/python3.8/site-packages/gradio/components/base.py in <module>
     18 
     19 from gradio import utils
---> 20 from gradio.blocks import Block, BlockContext
     21 from gradio.component_meta import ComponentMeta
     22 from gradio.data_classes import GradioDataModel

~/.local/lib/python3.8/site-packages/gradio/blocks.py in <module>
     27 from gradio_client.documentation import document
     28 
---> 29 from gradio import (
     30     analytics,
     31     components,

~/.local/lib/python3.8/site-packages/gradio/networking.py in <module>
     18 
     19 from gradio.exceptions import ServerFailedToStartError
---> 20 from gradio.routes import App
     21 from gradio.tunneling import Tunnel
     22 from gradio.utils import SourceFileReloader, watchfn

~/.local/lib/python3.8/site-packages/gradio/routes.py in <module>
     46 )
     47 from fastapi.security import OAuth2PasswordRequestForm
---> 48 from fastapi.templating import Jinja2Templates
     49 from gradio_client import utils as client_utils
     50 from gradio_client.documentation import document

~/.local/lib/python3.8/site-packages/fastapi/templating.py in <module>
----> 1 from starlette.templating import Jinja2Templates as Jinja2Templates  # noqa

~/.local/lib/python3.8/site-packages/starlette/templating.py in <module>
     12 
     13 try:
---> 14     import jinja2
     15 
     16     # @contextfunction was renamed to @pass_context in Jinja 3.0, and was removed in 3.1

/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py in <module>
     10 from .bccache import FileSystemBytecodeCache
     11 from .bccache import MemcachedBytecodeCache
---> 12 from .environment import Environment
     13 from .environment import Template
     14 from .exceptions import TemplateAssertionError

/usr/local/lib/python3.8/dist-packages/jinja2/environment.py in <module>
     23 from .compiler import CodeGenerator
     24 from .compiler import generate
---> 25 from .defaults import BLOCK_END_STRING
     26 from .defaults import BLOCK_START_STRING
     27 from .defaults import COMMENT_END_STRING

/usr/local/lib/python3.8/dist-packages/jinja2/defaults.py in <module>
      1 # -*- coding: utf-8 -*-
      2 from ._compat import range_type
----> 3 from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
      4 from .tests import TESTS as DEFAULT_TESTS  # noqa: F401
      5 from .utils import Cycler

/usr/local/lib/python3.8/dist-packages/jinja2/filters.py in <module>
     11 from markupsafe import escape
     12 from markupsafe import Markup
---> 13 from markupsafe import soft_unicode
     14 
     15 from ._compat import abc

ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/sdb/.local/lib/python3.8/site-packages/markupsafe/__init__.py)

In [2]:                                                                                                                      

### System Info

```shell
gradio environment
Traceback (most recent call last):
  File "/home/sdb/.local/bin/gradio", line 5, in <module>
    from gradio.cli import cli
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/components/annotated_image.py", line 14, in <module>
    from gradio.components.base import Component
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/components/base.py", line 20, in <module>
    from gradio.blocks import Block, BlockContext
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/blocks.py", line 29, in <module>
    from gradio import (
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/networking.py", line 20, in <module>
    from gradio.routes import App
  File "/home/sdb/.local/lib/python3.8/site-packages/gradio/routes.py", line 48, in <module>
    from fastapi.templating import Jinja2Templates
  File "/home/sdb/.local/lib/python3.8/site-packages/fastapi/templating.py", line 1, in <module>
    from starlette.templating import Jinja2Templates as Jinja2Templates  # noqa
  File "/home/sdb/.local/lib/python3.8/site-packages/starlette/templating.py", line 14, in <module>
    import jinja2
  File "/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.8/dist-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/sdb/.local/lib/python3.8/site-packages/markupsafe/__init__.py)
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
What version of gradio is this? And how did you install it? I recommend trying in a fresh environment. We test gradio in python 3.8 so I think some incorrect dependency version got pulled in.

**Comment by abidlabs** [comment]
Yes agree, you could also try the solutions mentioned here: https://stackoverflow.com/questions/72191560/importerror-cannot-import-name-soft-unicode-from-markupsafe

**Comment by abidlabs** [comment]
Going to close this for now, but we can reopen if indeed its an issue in Gradio.
