### ISSUE TITLE
Video-LLaVA demo api not working with Gradio-Client

### ISSUE THREAD

**Issue by Kamakshi8104** [gradio-app/gradio#7722]
### Describe the bug

Im trying to use the python api for the Video-LLaVA model demo on hugging face spaces but I get an error:
Traceback (most recent call last):
  File "/Users/kamakshiramamurthy/Desktop/GSoC/outline/app.py", line 7, in <module>
    result = client.predict(
             ^^^^^^^^^^^^^^^
  File "/Users/kamakshiramamurthy/miniconda3/envs/out_test/lib/python3.12/site-packages/gradio_client/client.py", line 409, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamakshiramamurthy/miniconda3/envs/out_test/lib/python3.12/site-packages/gradio_client/client.py", line 1246, in result
    return super().result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamakshiramamurthy/miniconda3/envs/out_test/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/kamakshiramamurthy/miniconda3/envs/out_test/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/kamakshiramamurthy/miniconda3/envs/out_test/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamakshiramamurthy/miniconda3/envs/out_test/lib/python3.12/site-packages/gradio_client/compatibility.py", line 66, in _inner
    predictions = self.process_predictions(*predictions)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamakshiramamurthy/miniconda3/envs/out_test/lib/python3.12/site-packages/gradio_client/compatibility.py", line 255, in process_predictions
    predictions = self.deserialize(*predictions)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamakshiramamurthy/miniconda3/envs/out_test/lib/python3.12/site-packages/gradio_client/compatibility.py", line 242, in deserialize
    s.deserialize(
  File "/Users/kamakshiramamurthy/miniconda3/envs/out_test/lib/python3.12/site-packages/gradio_client/serializing.py", line 207, in deserialize
    file = utils.decode_base64_to_file(x, dir=save_dir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamakshiramamurthy/miniconda3/envs/out_test/lib/python3.12/site-packages/gradio_client/utils.py", line 799, in decode_base64_to_file
    data, extension = decode_base64_to_binary(encoding)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamakshiramamurthy/miniconda3/envs/out_test/lib/python3.12/site-packages/gradio_client/utils.py", line 764, in decode_base64_to_binary
    extension = get_extension(encoding)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamakshiramamurthy/miniconda3/envs/out_test/lib/python3.12/site-packages/gradio_client/utils.py", line 710, in get_extension
    encoding = encoding.replace("audio/wav", "audio/x-wav")
AttributeError: 'dict' object has no attribute 'replace'

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
from gradio_client import Client

client = Client("https://languagebind-video-llava.hf.space/")
result = client.predict(
				"https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png",	# str (filepath or URL to image) in 'Input Image' Image component
				"https://github.com/gradio-app/gradio/raw/main/test/test_files/video_sample.mp4",	# str (filepath or URL to file) in 'Input Video' Video component
				"Howdy!",	# str in 'parameter_0' Textbox component
				fn_index=3
)
print(result)


```

### System Info

```shell
I am running the code on hugging face spaces
```

### Severity

Blocking usage of gradio

**Comment by Kamakshi8104** [comment]
I added serialize=False but  now I'm getting error:
File "/Users/kamakshiramamurthy/miniconda3/envs/out_test/lib/python3.12/site-packages/gradio_client/compatibility.py", line 95, in _predict
    raise ValueError(result["error"])
ValueError: None

**Comment by Kamakshi8104** [comment]
@abidlabs how can I solve this?

**Comment by Kamakshi8104** [comment]
@abidlabs Is there any way I can contribute to resolve this issue myself?

**Comment by abidlabs** [comment]
Hi @Kamakshi8104 this Space is running a very old version of Gradio (3.37) which we no longer support so I'll go ahead and close this issue. I would suggest duplicating the Space and then upgrading the version of Gradio if possible. Its likely that this is an old bug that is now fixed in recent versions of Gradio (particularly in 4.x)
