### ISSUE TITLE
Autoreload not working when demo is wrapped by `if __name__ == '__main__'`

### ISSUE THREAD

**Issue by kexul** [gradio-app/gradio#7740]
### Describe the bug

I'm using `gradio main.py` to debug my application, it automatically detect the file change and reload the functions, which is super helpful!
But when the `demo` function is under `if __name__ == '__main__` it raised an error:
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/gymuser/miniforge3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/gymuser/miniforge3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gymuser/miniforge3/lib/python3.10/site-packages/gradio/utils.py", line 220, in watchfn
    demo = getattr(module, reloader.demo_name)
AttributeError: module 'main' has no attribute 'demo'
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def test_fn(x):
    pass

if __name__ == '__main__':
    demo = gr.Interface(test_fn, inputs='text', outputs='text')
    demo.launch()
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.21.0
gradio_client version: 0.12.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.108.0
ffmpy: 0.3.2
gradio-client==0.12.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.21.4
importlib-resources: 6.1.3
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.3
numpy: 1.26.4
orjson: 3.9.15
packaging: 23.2
pandas: 2.2.1
pillow: 9.5.0
pydantic: 2.6.3
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.10.0
uvicorn: 0.28.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.27.0
huggingface-hub: 0.21.4
packaging: 23.2
typing-extensions: 4.10.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
HI @kexul ! Thanks for filing the issue. Yes that is expected behavior. Gradio uses python's built-in functions to reload your module so that means we won't re-run code underneath the `if __name__ == '__main__':` branch. So please move `demo` outside that codeblock.
