### ISSUE TITLE
[WORKAROUND] IIS ReverseProxy fails on Gradio v4.17 thru v4.21 (client 0.12.0)

### ISSUE THREAD

**Issue by jeremykei** [gradio-app/gradio#7749]
### Describe the bug

I believe this is more of a configuration setting albeit in base code. Trying to figure if the workaround affects anything else beyond cursory eyeballing.

Use Case: IIS ReverseProxy fails for https://fqdn --> http://localhost
Workaround: Traced and narrowed down to prioritize_base setting - toggle in favor of base_url works.
Question: Checking if this affects anything else?

WORKAROUND:
client/js/dist/index.js: 1369
- config.root = resolve_root(endpoint, config.root, false);
+ config.root = resolve_root(endpoint, config.root, true);

Minimal setup with or without fastapi generates the same result. 

Regressed v4.16.0 works fine. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

from fastapi import FastAPI
import gradio as gr
SERVER_PORT = 7683
SERVER_NAME = '127.0.0.1'
app = FastAPI()
demo = gr.Interface( lambda x: x, "text", "text" )
demo.ssl_verify = False
queue = demo.queue()
app = gr.mount_gradio_app( app, demo, path="/" )

if __name__ == '__main__':
    import uvicorn
    uvicorn.run(app, host=SERVER_NAME, port=SERVER_PORT )

### Screenshot

![inspector](https://github.com/gradio-app/gradio/assets/6842589/7e785159-4b81-4124-8a49-759eb00cdac5)
![index js](https://github.com/gradio-app/gradio/assets/6842589/1891e0f1-1af1-4c5a-a602-38a01ae4bf0c)
![prioritize_base_false](https://github.com/gradio-app/gradio/assets/6842589/6023c318-0a4a-4d68-96ed-2be8341b4438)
![workaround](https://github.com/gradio-app/gradio/assets/6842589/b46a1c90-b5b1-49ef-a142-783d550cce70)
![console](https://github.com/gradio-app/gradio/assets/6842589/661f5c96-95bf-44d4-a51a-ce6a8aaf40ea)

### Logs

```shell
(.venv) C:\share\genai\gradio\subpath>py uvicorn.gradio.00002.py
INFO:     Started server process [15404]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:7683 (Press CTRL+C to quit)
INFO:     [::1]:59839:0 - "GET / HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/index-10ead756.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/index-138adf03.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/svelte/svelte.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/index-10ead756.js.map HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-7fdff9d2.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-b2fdba73.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-7fdff9d2.js.map HTTP/1.1" 200 OK
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
INFO:     [::1]:59839:0 - "GET /assets/Blocks-2b5ac0cf.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Button-bd009e9a.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Blocks-e8e682ce.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Blocks-e8e682ce.js.map HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Button-bd009e9a.js.map HTTP/1.1" 200 OK
WARNING:  Invalid HTTP request received.
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
INFO:     [::1]:59839:0 - "GET /assets/Index-7cbc3ec9.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-24a33ce1.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-b1b07f9e.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Textbox-4b7f8a69.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/BlockTitle-16231197.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Info-47f6c44f.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Check-f7edb5d9.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Copy-a69620a8.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-0d7ad3de.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Example-e0df15d4.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-37392b60.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-b1b07f9e.js.map HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/BlockTitle-16231197.js.map HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Textbox-4b7f8a69.js.map HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Info-47f6c44f.js.map HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-37392b60.js.map HTTP/1.1" 200 OK
WARNING:  Invalid HTTP request received.
INFO:     [::1]:59839:0 - "GET / HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/index-10ead756.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/index-138adf03.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/svelte/svelte.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-7fdff9d2.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-b2fdba73.css HTTP/1.1" 200 OK
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
INFO:     [::1]:59839:0 - "GET /assets/Button-2a9911a9.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Blocks-e8e682ce.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Button-bd009e9a.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Blocks-2b5ac0cf.css HTTP/1.1" 200 OK
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
INFO:     [::1]:59839:0 - "GET /assets/Index-7cbc3ec9.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-815f98ca.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-24a33ce1.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-2abed479.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-b1b07f9e.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Textbox-4b7f8a69.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/BlockTitle-16231197.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Info-47f6c44f.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Check-f7edb5d9.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Example-e0df15d4.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Textbox-4c6022f4.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Copy-a69620a8.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Example-e8628e88.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-7ab72019.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-0d7ad3de.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/api-logo-5346f193.svg HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-37392b60.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/logo-3707f936.svg HTTP/1.1" 200 OK
WARNING:  Invalid HTTP request received.
INFO:     [::1]:59839:0 - "GET /client/js/dist/index.js HTTP/1.1" 404 Not Found
INFO:     [::1]:59839:0 - "GET / HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/index-10ead756.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/index-138adf03.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/svelte/svelte.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-b2fdba73.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-7fdff9d2.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /favicon.ico HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /info HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /theme.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Blocks-e8e682ce.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Button-bd009e9a.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Button-2a9911a9.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Blocks-2b5ac0cf.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-7cbc3ec9.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-2abed479.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-815f98ca.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-24a33ce1.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Textbox-4c6022f4.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Example-e8628e88.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-b1b07f9e.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-7ab72019.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Textbox-4b7f8a69.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/BlockTitle-16231197.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Info-47f6c44f.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Check-f7edb5d9.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Copy-a69620a8.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Example-e0df15d4.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-0d7ad3de.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-37392b60.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/api-logo-5346f193.svg HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/logo-3707f936.svg HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET / HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-7fdff9d2.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /info HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /theme.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET / HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-7fdff9d2.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET / HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /info HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-7fdff9d2.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /info HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET / HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /theme.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-7fdff9d2.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET / HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /info HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-7fdff9d2.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET / HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /info HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /assets/Index-7fdff9d2.js HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /info HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /theme.css HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "POST /queue/join HTTP/1.1" 200 OK
INFO:     [::1]:59839:0 - "GET /queue/data?session_hash=v8bf6df4t4b HTTP/1.1" 200 OK
```

### System Info

```shell
Windows 11/Server / Ubuntu 22.X

gradio                       4.21.0
gradio_client                0.12.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @jeremykei thanks for creating this issue. We have indeed made some changes to how the root_path works. I don't quite understand the reverse proxy set up you are describing. Can you please walk me through the setup? Because the repro you've provided works for me behind nginx proxy for example

**Comment by jeremykei** [comment]
Absolutely - appreciate the quick revert too. You're rite, Ngnix RP works, hence the issue's specificity on IIS RP. I can confirm v4.16.0 works too for IIS RP, as do a few versions prior. Pinned a few candidates for tracing and utils.ts got flagged on a deep-dive.

Here's a quick screengrab on IIS Reverse Proxy settings out of box (aka "mod" rewrite IIS):

![image](https://github.com/gradio-app/gradio/assets/6842589/49da12dc-614a-4e28-a736-60f4880daa13)

The IIS rewrite module can be installed with:
https://www.iis.net/downloads/microsoft/url-rewrite

IIS version on server 2019 is 10.0 Express Developers Edition:
![image](https://github.com/gradio-app/gradio/assets/6842589/d3bd8430-ac24-4dcc-be0d-4bf1672265fc)

![image](https://github.com/gradio-app/gradio/assets/6842589/b6a52cb1-60d8-444e-8723-d5950180a426)

Hope this helps and do let me know if there's anything I've missed that might help.

**Comment by rwb-truelime** [comment]
> Use Case: IIS ReverseProxy fails for https://fqdn --> http://localhost

The first screenshot shows https requests to https://localhost:7683. Your config in the example provided does not implement SSL keys and fully supports https requests for the proxied Gradio instance. Isn't this a cause or a part of the problem?

**Comment by jeremykei** [comment]
Thanks for the feedback. 

The RP setup we've illustrated works as @abidlabs indicated on Ngnix officially, very well if I might add. It also works flawlessly on IIS up to 4.16.0 and breaks 4.17+. For background, all of our backhaul services on dev, uat and prd are proxied for security and load balancing reasons.

We're trying to understand if the base_url toggle (hardwired to a falsy) has other implications post 4.16+ when we flip it. The codebase is substantial.

Hope this helps to disambiguate the scenario - appreciate any light thrown on this.

**Comment by jeremykei** [comment]
> > Use Case: IIS ReverseProxy fails for https://fqdn --> http://localhost
> 
> The first screenshot shows https requests to https://localhost:7683. Your config in the example provided does not implement SSL keys and fully supports https requests for the proxied Gradio instance. Isn't this a cause or a part of the problem?

Just managed to get back to my machine for some screen grabs with apol for the earlier brief.

Under the network inspector we expect preflight + actual calls going to https://fqdn:4445. Instead it's using the root_path and appending it to the https:// requesting protocol is what @abidlabs was mentioning (root_path changes). In 4.16 and prior you'll see the working requests going thru base_url instead of root_path. Hence the (error) screenshot for illustration to wit.

![image](https://github.com/gradio-app/gradio/assets/6842589/30644102-9144-4ba4-90b1-9c6f2f7523d4)

If we set the prioritize_base flag to true (show as false below) it uses the base_url which will work in our scenario. Since this is a false literal, the shoutout here to figure if anything else may be affected (uploads, et al).

![image](https://github.com/gradio-app/gradio/assets/6842589/5c153bcb-931a-45da-a223-c260999411ef)

So once the flag is flipped /info for instance will work.

**Comment by abidlabs** [comment]
Going to close this for now as I believe this is an issue with how IIS is set up.
