### ISSUE TITLE
Error while uploading file with certain name

### ISSUE THREAD

**Issue by deepanshuc** [gradio-app/gradio#7755]
### Describe the bug

I am trying to upload this video file to gradio but it throws error.
Apparently gradio throws error on every file with this name no matter what file type(jpg, txt etc).

**Filename:** 
> _Like A Royal Bengal Tiger...__ Mamata Banerjee Responds To JP Nadda.mp4

I checked the tmp upload folder and the file is present in there.
I don't think its a corrupt file because it works if I change the name.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import os


def video_identity(video):
    return video


demo = gr.Interface(video_identity, 
                    gr.Video(), 
                    "playable_video")

if __name__ == "__main__":
    demo.launch()

```

### Screenshot

<img width="1840" alt="Screenshot 2024-03-20 at 6 02 28 PM" src="https://github.com/gradio-app/gradio/assets/35916748/cbdfee99-bdec-4037-ad64-aee2afba9438">

### Logs

```shell
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/vscode/.local/lib/python3.10/site-packages/gradio/route_utils.py", line 253, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/vscode/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1686, in process_api
    inputs = await anyio.to_thread.run_sync(
  File "/home/vscode/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/vscode/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/home/vscode/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/vscode/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1391, in preprocess_data
    inputs_cached = processing_utils.move_files_to_cache(
  File "/home/vscode/.local/lib/python3.10/site-packages/gradio/processing_utils.py", line 303, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "/home/vscode/.local/lib/python3.10/site-packages/gradio_client/utils.py", line 1010, in traverse
    new_obj[key] = traverse(value, func, is_root)
  File "/home/vscode/.local/lib/python3.10/site-packages/gradio_client/utils.py", line 1006, in traverse
    return func(json_obj)
  File "/home/vscode/.local/lib/python3.10/site-packages/gradio/processing_utils.py", line 276, in _move_to_cache
    raise ValueError(
ValueError: File /tmp/gradio/810814ce14bb2e4b0bdf094f0e08d99426b460cf/_Like A Royal Bengal Tiger...__ Mamata Banerjee Responds To JP Nadda.mp4 is not in the upload folder and cannot be accessed.
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.21.0
gradio_client version: 0.12.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.2.0
fastapi: 0.110.0
ffmpy: 0.3.2
gradio-client==0.12.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.21.4
importlib-resources: 6.3.0
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.3
numpy: 1.26.4
orjson: 3.9.15
packaging: 24.0
pandas: 2.2.1
pillow: 10.2.0
pydantic: 2.6.4
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.3.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.9.0
typing-extensions: 4.10.0
uvicorn: 0.28.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.27.0
huggingface-hub: 0.21.4
packaging: 24.0
typing-extensions: 4.10.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by shubhamofbce** [comment]
Developer notes: We are returning false if the file path has `..`. We should return false only if the path except filename has `..`.
https://github.com/gradio-app/gradio/blob/4da44c458940bf7797572806f1ff25aaefbcac4d/gradio/utils.py#L956-L958

**Comment by shubhamofbce** [comment]
Just wanted to add one more thing, when i fixed it from backend on my local, Even our player is not able to load a file with thisn name.
I am getting this error in the browser console. I will look into it as well.
`Uncaught (in promise) DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable.
    play_pause Player.svelte:61`
