### ISSUE TITLE
Minified version of Gradio Lite is broken

### ISSUE THREAD

**Issue by quangIle** [gradio-app/gradio#7776]
### Describe the bug

Although the tutorial does not use the minified, jsDelivr's install section uses minified version.
<img width="859" alt="image" src="https://github.com/gradio-app/gradio/assets/33140936/7f76c16c-3cc8-480c-9da8-f6a12e35d4ae">

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```html
<html>

<head>
  <script type="module" crossorigin src="https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.min.css" />
</head>

<body>
  <gradio-lite>
    import gradio as gr

    def greet(name):
      return "Hello, " + name + "!"

    gr.Interface(greet, "textbox", "textbox").launch()
  </gradio-lite>
</body>

</html>
```

### Logs

```shell
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$$')
    at init$1 (Component.js:130:44)
    at new Blocks (Blocks.svelte:447:31)
    at Array.create_if_block_1$2 (lite.min.js:7:184561)
    at Object.p (lite.min.js:7:186726)
    at update_slot_base (utils.js:203:8)
    at Object.p (lite.min.js:7:127367)
    at update (scheduler.js:119:30)
    at flush$1 (scheduler.js:79:5)
```

### System Info

```shell
Chrome browser
```

### Severity

I can work around it

**Comment by whitphx** [comment]
`lite.js` is minified after #7852 and jsDeliver skips minification now.
```
$ wget https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.js
$ wget https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.min.js
$ diff lite.js lite.min.js
0a1,6
> /**
>  * Skipped minification because the original files appears to be already minified.
>  * Original file: /npm/@gradio/lite@4.26.0/dist/lite.js
>  *
>  * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
>  */
```

However, this problem still exists 🤔 Keep investigation...

**Comment by abidlabs** [comment]
Is this still an issue?

**Comment by whitphx** [comment]
Yes it is.
btw v5 is not released to npm/jsDeliver yet?

**Comment by freddyaboulton** [comment]
Lite is no longer maintained but someone can fork it and contribute a fix for this.

Last release of lite: https://github.com/gradio-app/gradio-lite
