### ISSUE TITLE
TypeError: Image.init() got an unexpected keyword argument 'tool'

### ISSUE THREAD

**Issue by Checkmate** [gradio-app/gradio#7799]
### Describe the bug

Traceback (most recent call last):
File "C:\workspace\dreamgaussian\gradio_app.py", line 68, in
image_block = gr.Image(type='pil', image_mode='RGBA', height=290, label='Input image', tool=None)
File "C:\Users\Administrator.conda\envs\dreamgaussian\lib\site-packages\gradio\component_meta.py", line 159, in wrapper
return fn(self, **kwargs)
TypeError: Image.init() got an unexpected keyword argument 'tool'

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

python gradio_app.py

### Logs

```shell
Traceback (most recent call last):
File "C:\workspace\dreamgaussian\gradio_app.py", line 68, in
image_block = gr.Image(type='pil', image_mode='RGBA', height=290, label='Input image', tool=None)
File "C:\Users\Administrator.conda\envs\dreamgaussian\lib\site-packages\gradio\component_meta.py", line 159, in wrapper
return fn(self, **kwargs)
TypeError: Image.init() got an unexpected keyword argument 'tool'
```

### System Info

```shell
win11 x64
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @Checkmate you may be using Gradio 3.x syntax. As of 4.0, the `Image` component no longer takes `tool` as a parameter. You may be interested in the ImageEditor component instead: https://www.gradio.app/main/docs/imageeditor
