### ISSUE TITLE
TypeError: Expected a gr.Textbox or gr.MultimodalTextbox component, but got <class 'gradio.components.textbox.Textbox'>

### ISSUE THREAD

**Issue by Jacoo520** [gradio-app/gradio#7806]
### Describe the bug

> demo：

```
import gradio as gr

def echo(message, history):
    return message

demo = gr.ChatInterface(fn=echo, 
                        chatbot=gr.Chatbot(label='AI_chat'),
                        textbox= gr.Textbox(placeholder = "Please enter your question:",container=False),
                        examples=["hello", "hola", "merhaba"], title="Echo Bot")
demo.launch()
```
Error：
```
Traceback (most recent call last):
  File "d:/PY/111py.py", line 6, in <module>
    demo = gr.ChatInterface(fn=echo,
  File "D:\anaconda3\envs\llama_alpaca\lib\site-packages\gradio\chat_interface.py", line 212, in __init__
    raise TypeError(
TypeError: Expected a gr.Textbox or gr.MultimodalTextbox component, but got <class 'gradio.components.textbox.Textbox'>
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import gradio as gr

def echo(message, history):
    return message

demo = gr.ChatInterface(fn=echo, 
                        chatbot=gr.Chatbot(label='AI_chat'),
                        textbox= gr.Textbox(placeholder = "Please enter your question:",container=False),
                        examples=["hello", "hola", "merhaba"], title="Echo Bot")
demo.launch()
```

### System Info

```shell
Name: gradio
Version: 4.22.0
Summary: Python library for easily interacting with trained machine learning models
Home-page:
Author:
Author-email: Abubakar Abid <gradio-team@huggingface.co>, Ali Abid <gradio-team@huggingface.co>, Ali Abdalla <gradio-team@huggingface.co>, Dawood Khan <gradio-team@huggingface.co>, Ahsen Khaliq <gradio-team@huggingface.co>, Pete Allen <gradio-team@huggingface.co>, Ömer Faruk Özdemir <gradio-team@huggingface.co>, Freddy A Boulton <gradio-team@huggingface.co>, Hannah Blair <gradio-team@huggingface.co>
License:
Location: d:\anaconda3\envs\llama_alpaca\lib\site-packages
Requires: aiofiles, altair, fastapi, ffmpy, gradio-client, httpx, huggingface-hub, importlib-resources, jinja2, markupsafe, matplotlib, numpy, orjson, packaging, pandas, pillow, pydantic, pydub, python-multipart, pyyaml, ruff, semantic-version, tomlkit, typer, typing-extensions, uvicorn
Required-by:
```

### Severity

I can work around it

**Comment by 11301858** [comment]
I had the same problem. To the best of my knowledge, #7783 fixes this but it's not on the stable version yet.

**Comment by AkagawaTsurunaki** [comment]
I solved this problem by using an old version `gradio==4.21.0`.
You could use the command to reinstall the gradio.
```shell
pip install gradio==4.21
```

**Comment by Jacoo520** [comment]
> 我使用旧版本解决了这个问题。您可以使用该命令重新安装 gradio。`gradio==4.21.0`
> 
> ```shell
> pip install gradio==4.21
> ```

我现在使用的是4.22.0版本，主要是MultimodalTextbox这个组件的使用问题。

**Comment by freddyaboulton** [comment]
Hi @Jacoo520 - this got fixed here - we should get a release out soon . https://github.com/gradio-app/gradio/pull/7783
