### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 2074: illegal multibyte sequence

### ISSUE THREAD

**Issue by hyraymond1** [gradio-app/gradio#7856]
### Describe the bug

(1 )gradio version as follows:
gradio                                   4.23.0
gradio_client                            0.14.0

(2)python version    
Python 3.11.6

(3)gradio codings as follows:
import gradio as gr

def greet(name, intensity):
    return "Hello, " + name + "!" * int(intensity)

demo = gr.Interface(
    fn=greet,
    inputs=["text", "slider"],
    outputs=["text"],
)

demo.launch()

(4)detail errors as follows:
[Running] python -u "c:\Users\RayX1\OneDrive\uibe\code2004\gradioEx\firstdemo.py"
Traceback (most recent call last):
  File "c:\Users\RayX1\OneDrive\uibe\code2004\gradioEx\firstdemo.py", line 1, in <module>
    import gradio as gr
  File "C:\Users\RayX1\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "C:\Users\RayX1\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "C:\Users\RayX1\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "C:\Users\RayX1\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\components\__init__.py", line 40, in <module>
    from gradio.components.multimodal_textbox import MultimodalTextbox
  File "C:\Users\RayX1\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\components\multimodal_textbox.py", line 34, in <module>
    class MultimodalTextbox(FormComponent):
  File "C:\Users\RayX1\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\component_meta.py", line 198, in __new__
    create_or_modify_pyi(component_class, name, events)
  File "C:\Users\RayX1\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi
    source_code = source_file.read_text()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RayX1\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 2074: illegal multibyte sequence

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

import gradio as gr

def greet(name, intensity):
    return "Hello, " + name + "!" * int(intensity)

demo = gr.Interface(
    fn=greet,
    inputs=["text", "slider"],
    outputs=["text"],
)

demo.launch()

### Screenshot

![image](https://github.com/gradio-app/gradio/assets/150356389/a9e785e3-ffc7-41ce-aad0-e07fe2b17012)

### System Info

```shell
(1 )gradio version as follows:
gradio                                   4.23.0
gradio_client                            0.14.0

(2)python version    
Python 3.11.6
```

### Severity

I can work around it

**Comment by pngwn** [comment]
I think this is the same issue as https://github.com/gradio-app/gradio/issues/7812

**Comment by freddyaboulton** [comment]
Yes agreed , will close!
