### ISSUE TITLE
Unclear gr.File() documentation - `TypeError: gradio.data_classes.FileData() argument after ** must be a mapping, not list`

### ISSUE THREAD

**Issue by mberco-quandl** [gradio-app/gradio#8037]
### Describe the bug

Using a gr.File() object as an input to any function triggers this error: `TypeError: gradio.data_classes.FileData() argument after ** must be a mapping, not list`. Is it possible to clarify how to interact with File() objects? Related to this [issue](https://github.com/gradio-app/gradio/pull/7299#issuecomment-2058111359): , as the core of the problem is trying to reduce storage leakage from users not manually erasing files uploaded to temp storage.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
with gr.Blocks(title="Title") as interface:
    with gr.Tab("Inputs"):

        csv_upload = gr.File(
            file_count=1,
            file_types=["csv"],
            label="Upload CSV file here:",
            type="filepath",
        )

        csv_as_json = gr.Text(
            label="JSON representation of uploaded csv after deletion",
            info="to be hidden once implemented",
        )

        button = gr.Button(value="Read CSV into memory and delete")

        @button.click(
            inputs=[csv_upload],
            outputs=[csv_as_json],
        )
        def convert_csv_to_json_then_delete(csv_upload):
            return "Test"
```

### Logs

```shell
2024-04-16 09:37:17 frontend-1  | Traceback (most recent call last):
2024-04-16 09:37:17 frontend-1  |   File "/usr/local/lib/python3.11/site-packages/gradio/queueing.py", line 527, in process_events
2024-04-16 09:37:17 frontend-1  |     response = await route_utils.call_process_api(
2024-04-16 09:37:17 frontend-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-16 09:37:17 frontend-1  |   File "/usr/local/lib/python3.11/site-packages/gradio/route_utils.py", line 261, in call_process_api
2024-04-16 09:37:17 frontend-1  |     output = await app.get_blocks().process_api(
2024-04-16 09:37:17 frontend-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-16 09:37:17 frontend-1  |   File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1782, in process_api
2024-04-16 09:37:17 frontend-1  |     inputs = await self.preprocess_data(
2024-04-16 09:37:17 frontend-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-16 09:37:17 frontend-1  |   File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1501, in preprocess_data
2024-04-16 09:37:17 frontend-1  |     inputs_cached = block.data_model(**inputs_cached)  # type: ignore
2024-04-16 09:37:17 frontend-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-16 09:37:17 frontend-1  | TypeError: gradio.data_classes.FileData() argument after ** must be a mapping, not list
```

### System Info

```shell
Every time I build the container I am pulling the latest Gradio version from pip. Using a local dev environment container setup.
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Hi @mberco-quandl , you need to set `file_count` equal to `single` or `multiple`, not and integer. Once I made that change, your demo worked fine!
