### ISSUE TITLE
Failure of Hot Reloading with Code Containing Multibyte Characters

### ISSUE THREAD

**Issue by zolgear** [gradio-app/gradio#8070]
### Describe the bug

**Summary:**

The changes made to the file `gradio/utils.py` are causing issues with hot reloading for applications using code containing multibyte characters.

**Details:**

Pull Request #7684 adds the open function to gradio/utils.py without specifying the file encoding, which impacts hot reload functionality when using code that contains multibyte characters.

gradio/utils.py
```python
NO_RELOAD = True


def _remove_no_reload_codeblocks(file_path: str):
    """Parse the file, remove the gr.no_reload code blocks, and write the file back to disk.
    Parameters:
        file_path (str): The path to the file to remove the no_reload code blocks from.
    """

    with open(file_path) as file:
        code = file.read()
```

**Related Links:**

- Related past issues: [#6063](https://github.com/gradio-app/gradio/issues/6063), [#6364](https://github.com/gradio-app/gradio/issues/6364)
- Related past Bug Fix: [#6622](https://github.com/gradio-app/gradio/pull/6622)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
# File Save with UTF-8 encoding
import gradio as gr

with gr.Blocks() as demo:
    markdown = gr.Markdown('こんにちわ.')

demo.launch()
```

### Logs

```shell
(.env) PS D:\gradio-issue-hotreload> gradio .\demo.py
Watching: 'D:\gradio-issue-hotreload' 'D:\gradio-issue-hotreload'

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Changes detected in: D:\gradio-issue-hotreload\demo.py
Reloading demo failed with the following exception:
Traceback (most recent call last):
  File "D:\gradio-issue-hotreload\.env\Lib\site-packages\gradio\utils.py", line 266, in watchfn
    changed_in_copy = _remove_no_reload_codeblocks(str(changed))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\gradio-issue-hotreload\.env\Lib\site-packages\gradio\utils.py", line 173, in _remove_no_reload_codeblocks
    code = file.read()
           ^^^^^^^^^^^
UnicodeDecodeError: 'cp932' codec can't decode byte 0x8f in position 125: illegal multibyte sequence
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.27.0
gradio_client version: 0.15.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.3.0
fastapi: 0.110.2
ffmpy: 0.3.2
gradio-client==0.15.1 is not installed.
httpx: 0.27.0
huggingface-hub: 0.22.2
importlib-resources: 6.4.0
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.4
numpy: 1.26.4
orjson: 3.10.1
packaging: 24.0
pandas: 2.2.2
pillow: 10.3.0
pydantic: 2.7.0
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.4.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.11.0
urllib3: 2.2.1
uvicorn: 0.29.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.3.1
httpx: 0.27.0
huggingface-hub: 0.22.2
packaging: 24.0
typing-extensions: 4.11.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Thanks @zolgear  for reporting! Would you be down to open a PR for this?
