### ISSUE TITLE
TypeError: gradio.data_classes.FileData() argument after ** must be a mapping, not list

### ISSUE THREAD

**Issue by stunlocked1** [gradio-app/gradio#8088]
### Describe the bug

I am trying to use gr.Files to get a folder, but it doesn't work. I need to get all files in a folder. The other issue was about file, this one is about folder.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def test(folderobj):
    print(folderobj.name)

with gr.Blocks() as interface:
    folderobj = gr.Files(file_count="directory", type="filepath") # type:ignore
    folderobj.change(test, folderobj)

if __name__ == "__main__":
   interface.launch()

```

### Logs

```shell
Traceback (most recent call last):
  File "d:\miniconda3\envs\pytorch311\Lib\site-packages\gradio\queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\miniconda3\envs\pytorch311\Lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\miniconda3\envs\pytorch311\Lib\site-packages\gradio\blocks.py", line 1531, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\miniconda3\envs\pytorch311\Lib\site-packages\gradio\blocks.py", line 1307, in preprocess_data
    inputs_cached = block.data_model(**inputs_cached)  # type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: gradio.data_classes.FileData() argument after ** must be a mapping, not list
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.27.0
gradio_client version: 0.15.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 22.1.0
altair: 5.2.0
fastapi: 0.103.2
ffmpy: 0.3.0
gradio-client==0.15.1 is not installed.
httpx: 0.24.1
huggingface-hub: 0.19.4
importlib-resources: 6.1.1
jinja2: 3.1.2
markupsafe: 2.1.1
matplotlib: 3.8.0
numpy: 1.25.2
orjson: 3.9.10
packaging: 23.2
pandas: 2.1.1
pillow: 10.2.0
pydantic: 2.1.1
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.4.1
semantic-version: 2.8.5
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.10.0
urllib3: 2.2.1
uvicorn: 0.24.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.10.0
httpx: 0.24.1
huggingface-hub: 0.19.4
packaging: 23.2
typing-extensions: 4.10.0
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @stunlocked1 when `file_count="directory"`, the Python function receives a list of files, so you need to handle a list in your functions. This works for me:

```py
import gradio as gr

def test(folderobj):
    print([f.name for f in folderobj])

with gr.Blocks() as interface:
    folderobj = gr.Files(file_count="directory", type="filepath") # type:ignore
    folderobj.change(test, folderobj)

if __name__ == "__main__":
   interface.launch()

```
