### ISSUE TITLE
streaming problems with `Chatbot`

### ISSUE THREAD

**Issue by not-lain** [gradio-app/gradio#8116]
### Describe the bug

i don't know if it's a problem in the first place but I have a function that sometimes yields and other times returns text.
thinking about updating how the transformers pipeline works soon using the same logic. and it seems I'm encountering a problem with cases where I'm yielding.
I tried it outside gradio and it seems to be working fine.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

# logic states we need to separate the yield into another function
# to avoid always yielding (it's a python problem)
def f(flag):
    def gen(n):
        out =""
        for i in range(n):
            out+=f"{i}\n"
            yield out
    n = 10
    # when user says the word stream
    if flag=="stream":
        return gen()
    else:
        out = ""
        for i in range(n) : 
          out+=f"{i}\n"
        return out


def talk(prompt,history=[]):
  return f(prompt)

demo = gr.ChatInterface(fn=talk, 
          chatbot=gr.Chatbot(),
          examples=[["stream",[]],["do not stream",[]]], 
          title="Text Streaming")
demo.launch(debug=True)
```
I can provide more examples if you want

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1788, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1338, in call_function
    prediction = await fn(*processed_input)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 726, in async_wrapper
    response = await f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/gradio/chat_interface.py", line 514, in _submit_fn
    response = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "<ipython-input-26-210f1399586a>", line 23, in talk
    return f(prompt)
  File "<ipython-input-26-210f1399586a>", line 14, in f
    return gen()
TypeError: f.<locals>.gen() missing 1 required positional argument: 'n'
Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7861 <> https://cf88433e01e5de7bd0.gradio.live
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.27.0
gradio_client version: 0.15.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 4.2.2
fastapi: 0.110.2
ffmpy: 0.3.2
gradio-client==0.15.1 is not installed.
httpx: 0.27.0
huggingface-hub: 0.20.3
importlib-resources: 6.4.0
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.7.1
numpy: 1.25.2
orjson: 3.10.1
packaging: 24.0
pandas: 2.0.3
pillow: 9.4.0
pydantic: 2.7.0
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.4.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.11.0
urllib3: 2.0.7
uvicorn: 0.29.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.27.0
huggingface-hub: 0.20.3
packaging: 24.0
typing-extensions: 4.11.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @not-lain ! I think you need to pass in `n` to the `gen` function? In general though, a function that yields sometimes and returns other times should work. gradio will just treat it like an iterator in both cases.

**Comment by not-lain** [comment]
@freddyaboulton 
i tried this 
```python
import gradio as gr

# logic states we need to separate the yield into another function
# to avoid always yielding (it's a python problem)
def f(flag):
    def gen(n):
        out =""
        for i in range(n):
            out+=f"{i}\n"
            yield out
    # when user says the word stream
    if flag=="stream":
        return gen(10)
    else:
        out = ""
        for i in range(10) : 
          out+=f"{i}\n"
        return out


def talk(prompt,history=[]):
  return f(prompt)

demo = gr.ChatInterface(fn=talk, 
          chatbot=gr.Chatbot(),
          examples=[["stream",[]],["do not stream",[]]], 
          title="Text Streaming")
demo.launch(debug=True)
```

**Comment by freddyaboulton** [comment]
I was wrong about being able to mix `return` and `yield` without a problem. I think you need to yield at least once before returning. But refactoring to always be an iterator achieves the desired result. Need `yield from` otherwise you wouldn't be yielding from the iterator, you'd be returning the iterator itself.

```python
import gradio as gr

# logic states we need to separate the yield into another function
# to avoid always yielding (it's a python problem)
def f(flag):
    def gen(n):
        out =""
        for i in range(n):
            out+=f"{i}\n"
            yield out
    # when user says the word stream
    if flag=="stream":
        yield from gen(10)
    else:
        out = ""
        for i in range(10) : 
          out+=f"{i}\n"
        yield out


def talk(prompt, history=[]):
    yield from f(prompt)

demo = gr.ChatInterface(fn=talk, 
          chatbot=gr.Chatbot(),
          examples=[["stream",[]],["do not stream",[]]], 
          title="Text Streaming")
demo.launch(debug=True)
```

**Comment by not-lain** [comment]
@freddyaboulton 
this fixed it for me thank youuuu
