### ISSUE TITLE
Add diffusers pipeline type: image-to-image

### ISSUE THREAD

**Issue by darkball1** [gradio-app/gradio#8167]
I was deploying a virtual try on model and I got the error.

Fetching model from: https://huggingface.co/yisol/IDM-VTON
Traceback (most recent call last):
  File "/home/user/app/app.py", line 3, in <module>
    gr.load("models/yisol/IDM-VTON").launch()
  File "/usr/local/lib/python3.10/site-packages/gradio/external.py", line 60, in load
    return load_blocks_from_repo(
  File "/usr/local/lib/python3.10/site-packages/gradio/external.py", line 99, in load_blocks_from_repo
    blocks: gradio.Blocks = factory_methods[src](name, hf_token, alias, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gradio/external.py", line 352, in from_model
    raise ValueError(f"Unsupported pipeline type: {p}")
ValueError: Unsupported pipeline type: image-to-image

Please add the image to image pipeline

**Comment by freddyaboulton** [comment]
Would you be interested in opening a PR for this @darkball1 ?
