### ISSUE TITLE
Lite started to fail booting up with an installation error of a dependency

### ISSUE THREAD

**Issue by whitphx** [gradio-app/gradio#8202]
### Describe the bug

```
Traceback (most recent call last): File "/lib/python3.11/site-packages/micropip/_commands/install.py", line 146, in install raise ValueError( ValueError: Can't find a pure Python 3 wheel for: 'ujson!=4.0.2,!=4.1.0,!=4.2.0,!=4.3.0,!=5.0.0,!=5.1.0,>=4.0.1', 'httptools>=0.5.0; extra == "standard"', 'uvloop!=0.15.0,!=0.15.1,>=0.14.0; (sys_platform != "win32" and (sys_platform != "cygwin" and platform_python_implementation != "PyPy")) and extra == "standard"', 'watchfiles>=0.13; extra == "standard"' See: https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package

PythonError: Traceback (most recent call last):
  File "/lib/python3.11/site-packages/micropip/_commands/install.py", line 146, in install
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for: 'ujson!=4.0.2,!=4.1.0,!=4.2.0,!=4.3.0,!=5.0.0,!=5.1.0,>=4.0.1', 'httptools>=0.5.0; extra == "standard"', 'uvloop!=0.15.0,!=0.15.1,>=0.14.0; (sys_platform != "win32" and (sys_platform != "cygwin" and platform_python_implementation != "PyPy")) and extra == "standard"', 'watchfiles>=0.13; extra == "standard"'
See: https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package


    at new_error (https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.js:9:10014)
    at https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.wasm:wasm-function[300]:0x158e62
    at https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.wasm:wasm-function[454]:0x15ff9e
    at _PyEM_TrampolineCall_JS (https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.js:9:120223)
    at https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.wasm:wasm-function[1083]:0x1a3494
    at https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.wasm:wasm-function[3413]:0x28a2bd
    at https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.wasm:wasm-function[2063]:0x1e431e
    at https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.wasm:wasm-function[1090]:0x1a397d
    at https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.wasm:wasm-function[1093]:0x1a3c3e
    at https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.wasm:wasm-function[1094]:0x1a3ce0
    at https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.wasm:wasm-function[3226]:0x2689a4
    at https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.wasm:wasm-function[3227]:0x26e800
    at https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.wasm:wasm-function[1096]:0x1a3e08
    at https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.wasm:wasm-function[1091]:0x1a3a98
    at https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.wasm:wasm-function[442]:0x15f76b
    at Module.callPyObjectKwargs (https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.js:9:64297)
    at Module.callPyObject (https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.js:9:65365)
    at wrapper (https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide.asm.js:9:32855)
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Launch a Lite app.

### System Info

```shell
Looks like any ver. of Lite has this problem.
```

### Severity

Blocking usage of gradio

**Comment by whitphx** [comment]
A new ver. of `fastapi` may be the cause that added `ujson` as its dep.
