### ISSUE TITLE
API Recorder not working for HuggingFace space

### ISSUE THREAD

**Issue by freddyaboulton** [gradio-app/gradio#8246]
### Describe the bug

Tried using the API recorder on [StoryDiffusion](https://huggingface.co/spaces/YupengZhou/StoryDiffusion) and I got the following error when closing the recorder.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parameters')
    at RecordingSnippet.svelte:20:49
    at Array.map (<anonymous>)
    at Array.c (RecordingSnippet.svelte:19:5)
    at gl (RecordingSnippet.svelte:55:2)
    at Array.E_ (RecordingSnippet.svelte:51:7)
    at Array.C_ (RecordingSnippet.svelte:61:47)
    at create_slot (svelte.js:165:23)
    at ue (index.js:132:1)
    at _e (Block.svelte:35:11)
    at init (svelte.js:3250:34)
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

See above^

### System Info

```shell
-
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Will look into it!

**Comment by freddyaboulton** [comment]
Gonna close in favor of #8259
