### ISSUE TITLE
Broken IPv6 in Docker Container

### ISSUE THREAD

**Issue by bival-pierre-grimme** [gradio-app/gradio#8437]
### Describe the bug

Trying to set a dualstack network configuration via environment variables in docker compose

    environment:
      - GRADIO_SERVER_PORT=7861
      - GRADIO_SERVER_NAME="[::]"
 
 fails with: 

OSError: Cannot find empty port in range: 7861-7960. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`

not a suitable workaround:

```python
import gradio as gr
import logging

logging.basicConfig(level=logging.DEBUG)

def greet(name, intensity):
    return "Hello, " + name + "!" * int(intensity)

demo = gr.Interface(
    fn=greet,
    inputs=["text", "slider"],
    outputs=["text"],
)

if __name__ == "__main__":
    demo.launch(debug=True, server_name="[::]")

```

because the docker container is not reachable from [::]:7861 from the host system. I verified it with a fastapi sample and the fastapi works dualstack no problem (access via [::1]:8080 in the browser).

Another interesting obversation is, the when GRADIO_SERVER_NAME=0.0.0.0 is set as a container environment variable, i am able to access it via http://[::1]:7860/ from my host system's browser ( keep an eye on my port mapping configuration in the docker compose)

My suggestion is to seperate IPv4 from IPv6. When you choose 0.0.0.0 it will only listen to IPv4 and if you choose :: it will listen to IPv4+IPv6.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import logging

logging.basicConfig(level=logging.DEBUG)

def greet(name, intensity):
    return "Hello, " + name + "!" * int(intensity)

demo = gr.Interface(
    fn=greet,
    inputs=["text", "slider"],
    outputs=["text"],
)

if __name__ == "__main__":
    demo.launch(debug=True)
```

```yaml
docker compose:

    ports:
      - "7860:7861"
    environment:
      - GRADIO_SERVER_PORT=7861
      - GRADIO_SERVER_NAME=0.0.0.0
    #  - GRADIO_SERVER_NAME='::'
    #  - GRADIO_SERVER_NAME="::"
    #  - GRADIO_SERVER_NAME="[::]"
```

```dockerfile
FROM python:3.10-slim

WORKDIR /app

RUN pip install gradio --no-cache

COPY . .

CMD ["python", "test.py"]
```

### Logs

```shell
2024-06-03 12:36:34 DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
2024-06-03 12:36:34 DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
2024-06-03 12:36:34 DEBUG:asyncio:Using selector: EpollSelector
2024-06-03 12:36:34 DEBUG:httpx:load_verify_locations cafile='/usr/local/lib/python3.10/site-packages/certifi/cacert.pem'
2024-06-03 12:36:34 DEBUG:httpx:load_verify_locations cafile='/usr/local/lib/python3.10/site-packages/certifi/cacert.pem'
2024-06-03 12:36:34 DEBUG:httpcore.connection:connect_tcp.started host='api.gradio.app' port=443 local_address=None timeout=3 socket_options=None
2024-06-03 12:36:34 DEBUG:httpcore.connection:connect_tcp.started host='checkip.amazonaws.com' port=443 local_address=None timeout=3 socket_options=None
2024-06-03 12:36:34 Traceback (most recent call last):
2024-06-03 12:36:34   File "/app/./frontend/test.py", line 16, in <module>
2024-06-03 12:36:34     demo.launch(debug=True)
2024-06-03 12:36:34   File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 2321, in launch
2024-06-03 12:36:34     ) = http_server.start_server(
2024-06-03 12:36:34   File "/usr/local/lib/python3.10/site-packages/gradio/http_server.py", line 154, in start_server
2024-06-03 12:36:34     raise OSError(
2024-06-03 12:36:34 OSError: Cannot find empty port in range: 7861-7960. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.
2024-06-03 12:36:34 DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f03bbf69810>
2024-06-03 12:36:34 DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x7f03c08f3140> server_hostname='checkip.amazonaws.com' timeout=3
2024-06-03 12:36:34 DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f03bbf2ac80>
2024-06-03 12:36:34 DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x7f03c08f3340> server_hostname='api.gradio.app' timeout=3
2024-06-03 12:36:34 DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f03bbf697e0>
2024-06-03 12:36:34 DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
2024-06-03 12:36:34 DEBUG:httpcore.http11:send_request_headers.complete
2024-06-03 12:36:34 DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
2024-06-03 12:36:34 DEBUG:httpcore.http11:send_request_body.complete
2024-06-03 12:36:34 DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
2024-06-03 12:36:34 DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'', [(b'Date', b'Mon, 03 Jun 2024 10:36:35 GMT'), (b'Content-Type', b'text/plain;charset=UTF-8'), (b'Content-Length', b'12'), (b'Connection', b'keep-alive'), (b'Server', b'nginx'), (b'Vary', b'Origin'), (b'Vary', b'Access-Control-Request-Method'), (b'Vary', b'Access-Control-Request-Headers')])
2024-06-03 12:36:34 INFO:httpx:HTTP Request: GET https://checkip.amazonaws.com/ "HTTP/1.1 200 "
2024-06-03 12:36:34 DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
2024-06-03 12:36:34 DEBUG:httpcore.http11:receive_response_body.complete
2024-06-03 12:36:34 DEBUG:httpcore.http11:response_closed.started
2024-06-03 12:36:34 DEBUG:httpcore.http11:response_closed.complete
2024-06-03 12:36:34 DEBUG:httpcore.connection:close.started
2024-06-03 12:36:34 DEBUG:httpcore.connection:close.complete
2024-06-03 12:36:34 DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): huggingface.co:443
2024-06-03 12:36:35 DEBUG:urllib3.connectionpool:https://huggingface.co:443 "HEAD /api/telemetry/gradio/initiated HTTP/1.1" 200 0
2024-06-03 12:36:35 DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f03bbf2ac50>
2024-06-03 12:36:35 DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
2024-06-03 12:36:35 DEBUG:httpcore.http11:send_request_headers.complete
2024-06-03 12:36:35 DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
2024-06-03 12:36:35 DEBUG:httpcore.http11:send_request_body.complete
2024-06-03 12:36:35 DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
2024-06-03 12:36:35 DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Date', b'Mon, 03 Jun 2024 10:36:36 GMT'), (b'Content-Type', b'application/json'), (b'Content-Length', b'21'), (b'Connection', b'keep-alive'), (b'Server', b'nginx/1.18.0'), (b'Access-Control-Allow-Origin', b'*')])
2024-06-03 12:36:35 INFO:httpx:HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
2024-06-03 12:36:35 DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
2024-06-03 12:36:35 DEBUG:httpcore.http11:receive_response_body.complete
2024-06-03 12:36:35 DEBUG:httpcore.http11:response_closed.started
2024-06-03 12:36:35 DEBUG:httpcore.http11:response_closed.complete
2024-06-03 12:36:35 DEBUG:httpcore.connection:close.started
2024-06-03 12:36:35 DEBUG:httpcore.connection:close.complete
```

### System Info

```shell
docker v4.30.0
--------------
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.32.2
gradio_client version: 0.17.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.3.0
fastapi: 0.111.0
ffmpy: 0.3.2
gradio-client==0.17.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.23.2
importlib-resources: 6.4.0
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.9.0
numpy: 1.26.4
orjson: 3.10.3
packaging: 24.0
pandas: 2.2.2
pillow: 10.3.0
pydantic: 2.7.2
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.4.7
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.12.1
urllib3: 2.2.1
uvicorn: 0.30.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.5.0
httpx: 0.27.0
huggingface-hub: 0.23.2
packaging: 24.0
typing-extensions: 4.12.1
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by aymeric-roucher** [comment]
sdk_version: 4.37.2

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue yet, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by masterflitzer** [comment]
i could reproduce it today like shown below, i used docker engine v27 on linux (debian 12) to make sure there is proper ipv6 support, i also tried different (very high) port numbers to make sure it's not due to a port being in use

i would suggest listening on dual stack (both ipv6 & ipv4) no matter if `::` or `0.0.0.0` is provided and if either ipv6 or ipv4 are not available, fallback to single stack (ipv6-only or ipv4-only) respectively

`src/app.py`
```python
import gradio as gr

def greet(name):
    return f"Hello {name}!"

def main():
    gr.Interface(fn=greet, inputs="text", outputs="text").launch()

if __name__ == "__main__":
    main()

```

`compose.yaml`
```yaml
networks:
  default:
    enable_ipv6: true

services:
  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "7860:7860"
    environment:
      GRADIO_SERVER_PORT: "7860"
      # does work (ipv4)
      GRADIO_SERVER_NAME: "0.0.0.0"
      # doesn't work (ipv6)
      #GRADIO_SERVER_NAME: "::"
      # doesn't work (ipv6)
      #GRADIO_SERVER_NAME: "[::]"

```

`dockerfile`
```dockerfile
FROM python:3.10-slim

WORKDIR /opt/app

RUN apt-get update && \
    apt-get install -y --no-install-recommends dumb-init && \
    apt-get clean

COPY requirements.txt .
RUN pip install -r requirements.txt && \
    rm requirements.txt

COPY src .

ENTRYPOINT ["dumb-init", "--"]
CMD ["python", "app.py"]

```

`requirements.txt`
```txt
gradio

```

output of `sudo docker compose up --build`
```bash
Attaching to app-1
app-1  | Traceback (most recent call last):
app-1  |   File "/opt/app/app.py", line 13, in <module>
app-1  |     main()
app-1  |   File "/opt/app/app.py", line 9, in main
app-1  |     gr.Interface(fn=greet, inputs="text", outputs="text").launch()
app-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 2481, in launch
app-1  |     ) = http_server.start_server(
app-1  |   File "/usr/local/lib/python3.10/site-packages/gradio/http_server.py", line 154, in start_server
app-1  |     raise OSError(
app-1  | OSError: Cannot find empty port in range: 7860-7959. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.
app-1 exited with code 1

```

additionally: when gradio starts with `0.0.0.0` (as `::` crashes), ipv6 connections fail, with the nginx container for example they succeed, in both cases the container correctly gets an ipv6 & ipv4 gateway & ip address assigned which can be inspected by running  
`sudo docker inspect "$(sudo docker ps -qf name=app)" | jq`

query **nginx** container with curl on ipv6 & ipv4: `curl -I 'http://[::1]:8080'; curl -I 'http://127.0.0.1:8080'`
```bash
HTTP/1.1 200 OK
HTTP/1.1 200 OK
```

query **app** container with curl on ipv6 & ipv4: `curl -I 'http://[::1]:8080'; curl -I 'http://127.0.0.1:8080'`
```bash
curl: (56) Recv failure: Connection reset by peer
HTTP/1.1 200 OK
```

**Comment by abidlabs** [comment]
Could either of you check ot see if https://github.com/gradio-app/gradio/pulls fixes the issue?

**Comment by abidlabs** [comment]
Going to close for lack of follow up
