### ISSUE TITLE
gr.FileExplorer - Malfunction after Permission Error ( WinError 5 )

### ISSUE THREAD

**Issue by thmoeller** [gradio-app/gradio#8475]
### Describe the bug

In my app i need to select multiple files. So, i was starting to go with the gr.FileExplorer module. I am on a Windows machine. This worked well until my selection included a folder that i do not have the correct permissions for. In general the app continuous to work, but an error shows in the terminal and the module fails to work properly ( folders are not expandable anymore and change events are not firing anymore). Try to find some kind of workaround, but failed to do so.

The module itself does not give me the opportunity to handle this error in any way.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import os

def handle_files(files):
    # This function will process the list of files
    file_info = [d for d in files]
    return file_info

with gr.Blocks() as demo:
    gr.Markdown('## Select folder or files to read into index')
    with gr.Row():
            files = gr.FileExplorer(
                glob="*",
                # value=["themes/utils"],
                root_dir="/Users/" + os.getlogin(),
                interactive=True,
                ignore_glob="**/__init__.py",
            )
            output=gr.Textbox(label="Selected files & folders:")
    
    files.change(handle_files, files, output)

if __name__ == "__main__":
    demo.launch()

```

### Logs

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\uvicorn\protocols\http\httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\gradio\route_utils.py", line 713, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\gradio\route_utils.py", line 729, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\gradio\routes.py", line 1042, in component_server
    return fn(body.data)
           ^^^^^^^^^^^^^
  File "C:\Users\XXXXXX\AppData\Roaming\Python\Python312\site-packages\gradio\components\file_explorer.py", line 175, in ls
    subdir_items = sorted(os.listdir(full_subdir_path))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access denied: 'c:\\Users\\XXXXXX\\Eigene Dateien'
```

### System Info

```shell
gradio 4.31.5
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi, apologies for the late follow up. We haven't had a chance to look into this issue yet, but the Gradio codebase has changed quite significantly since this issue was created, particularly with the release of Gradio 5. Could you let us know if this is still an issue in the latest version of Gradio (`pip install --upgrade gradio`)? Thanks!

**Comment by abidlabs** [comment]
Closing the issue for now, but happy to reopen if the issue continues to persist in the latest version of Gradio

**Comment by ExcellentAmericanEagle** [comment]
@abidlabs 
Can confirm it continues to persist in gradio 5.44.1.

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.FileExplorer(root_dir="C:\\")

demo.launch()
```

If I try to expand a directory which I don't have permission to, a `PermissionError` exception is thrown and the application freezes

<img width="1510" height="535" alt="Image" src="https://github.com/user-attachments/assets/54d8d642-558f-4166-919f-24a65091df3a" />

<details>
  <summary>
     Obtained Error
  </summary>

```txt
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__ 
    await super().__call__(scope, receive, send)
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\gradio\brotli_middleware.py", line 74, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\gradio\route_utils.py", line 883, in __call__    
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\gradio\route_utils.py", line 899, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\starlette\routing.py", line 714, in __call__     
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle       
    await self.app(scope, receive, send)
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
editor-gradio\.venv\Lib\site-packages\gradio\routes.py", line 1595, in component_server
    return fn(*processed_input)
  File "C:\Users\user\projects\gradio-sandbox\.venv\Lib\site-packages\gradio\components\file_explorer.py", line 183, in ls
    subdir_items = sorted(os.listdir(full_subdir_path))
                          ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: 'C:\\Users/SomeRandomUser'
```
</details>
<details>
  <summary>
     Gradio Environment Information
  </summary>

```txt
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 5.44.1
gradio_client version: 1.12.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 24.1.0
anyio: 4.9.0
audioop-lts: 0.2.1
brotli: 1.1.0
fastapi: 0.115.12
ffmpy: 0.5.0
gradio-client: 1.12.1
groovy: 0.1.2
httpx: 0.28.1
huggingface-hub: 0.34.4
jinja2: 3.1.6
markupsafe: 3.0.2
numpy: 2.2.5
orjson: 3.10.18
packaging: 25.0
pandas: 2.2.3
pillow: 11.2.1
pydantic: 2.11.4
pydub: 0.25.1
python-multipart: 0.0.20
pyyaml: 6.0.2
ruff: 0.11.8
safehttpx: 0.1.6
semantic-version: 2.10.0
starlette: 0.46.2
tomlkit: 0.13.2
typer: 0.15.3
typing-extensions: 4.14.1
urllib3: 2.4.0
uvicorn: 0.34.2
mcp is not installed.
pydantic: 2.11.4
authlib is not installed.
itsdangerous is not installed.


gradio_client dependencies in your environment:

fsspec: 2025.3.2
httpx: 0.28.1
huggingface-hub: 0.34.4
packaging: 25.0
typing-extensions: 4.14.1
websockets: 15.0.1


(.venv)
```
</details>


https://github.com/user-attachments/assets/21293c1b-2579-40d7-a28b-ab703806273b

**Comment by abidlabs** [comment]
Will take a look, thanks @ExcellentAmericanEagle for confirming
