### ISSUE TITLE
ImportError: cannot import name 'CommitOperationAdd' from 'huggingface_hub'

### ISSUE THREAD

**Issue by JWJUN233233** [gradio-app/gradio#8479]
### Describe the bug

It is strange.
if I just install torch with command `pip install torch`, then everything goes well
but if i use command `conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia` and import gradio,
there is errors

```
  File "test.py", line 2, in <module>
    import gradio
  File "C:\ProgramData\anaconda3\envs\ChatTTS\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "C:\ProgramData\anaconda3\envs\ChatTTS\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "C:\ProgramData\anaconda3\envs\ChatTTS\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "C:\ProgramData\anaconda3\envs\ChatTTS\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\ProgramData\anaconda3\envs\ChatTTS\lib\site-packages\gradio\components\annotated_image.py", line 7, in <module>
    import gradio_client.utils as client_utils
  File "C:\ProgramData\anaconda3\envs\ChatTTS\lib\site-packages\gradio_client\__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "C:\ProgramData\anaconda3\envs\ChatTTS\lib\site-packages\gradio_client\client.py", line 29, in <module>
    from huggingface_hub import CommitOperationAdd, SpaceHardware, SpaceStage
ImportError: cannot import name 'CommitOperationAdd' from 'huggingface_hub' (C:\ProgramData\anaconda3\envs\ChatTTS\lib\site-packages\huggingface_hub\__init__.py)
```
There must be something wrong with gradio.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

//Install torch with cuda first
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia

then
```python
import gradio
```

### System Info

```shell
there are errors after running gradio environment.

(ChatTTS) PS C:\users\13063\source\repos\AI\ChatTTS> gradio environment
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\ChatTTS\Scripts\gradio-script.py", line 5, in <module>
    from gradio.cli import cli
  File "C:\ProgramData\anaconda3\envs\ChatTTS\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "C:\ProgramData\anaconda3\envs\ChatTTS\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "C:\ProgramData\anaconda3\envs\ChatTTS\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "C:\ProgramData\anaconda3\envs\ChatTTS\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\ProgramData\anaconda3\envs\ChatTTS\lib\site-packages\gradio\components\annotated_image.py", line 7, in <module>
    import gradio_client.utils as client_utils
  File "C:\ProgramData\anaconda3\envs\ChatTTS\lib\site-packages\gradio_client\__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "C:\ProgramData\anaconda3\envs\ChatTTS\lib\site-packages\gradio_client\client.py", line 29, in <module>
    from huggingface_hub import CommitOperationAdd, SpaceHardware, SpaceStage
ImportError: cannot import name 'CommitOperationAdd' from 'huggingface_hub' (C:\ProgramData\anaconda3\envs\ChatTTS\lib\site-packages\huggingface_hub\__init__.py)

my os is Windows11
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Can you try manually upgrading your huggingface hub issue? Maybe conda installed an older version. The `CommitOperationAdd` was added quite a while ago to the hub library. 

I will close since I don't think this is a gradio issue.

**Comment by hr1z0** [comment]
exact same problem here, did you find any solution?

**Comment by JWJUN233233** [comment]
> exact same problem here, did you find any solution?

pip install -U gradio
