### ISSUE TITLE
Image component raises ValueError when it is updated with a callable value

### ISSUE THREAD

**Issue by edgarGracia** [gradio-app/gradio#8575]
### Describe the bug

When I pass a function to a ``gradio.Image`` (e.g. ``gr.Image(get_random_img)``), it gets called and the returned image is displayed.

However, when the same component is returned by a function to update an Image component, it raises ``ValueError: Cannot process this value as an Image, it is of type: <class 'function'>``

I was planning to create an image that updates continuously (with the ``every`` parameter) once a button is clicked. Should I update the Image value in a different way?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import numpy as np


def get_random_img():
    return (np.random.random((512,512,3)) * 255).astype("uint8")


def set_gr_image():
    return gr.Image(get_random_img, width=512, height=512)


with gr.Blocks() as demo:
    gr_image = gr.Image(get_random_img, width=512, height=512)  # works well
    button = gr.Button()
    button.click(set_gr_image, outputs=gr_image)  # raises ValueError


demo.launch()

```

### Logs

```shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\gradio\blocks.py", line 1938, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\gradio\blocks.py", line 1749, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\gradio\blocks.py", line 615, in postprocess_update_dict
    update_dict["value"] = block.postprocess(value)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\gradio\components\image.py", line 208, in postprocess
    saved = image_utils.save_image(value, self.GRADIO_CACHE, self.format)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\gradio\image_utils.py", line 72, in save_image
    raise ValueError(
ValueError: Cannot process this value as an Image, it is of type: <class 'function'>
```

### System Info

```shell
python: 3.10
gradio: 4.36.1
```

### Severity

I can work around it

**Comment by edgarGracia** [comment]
Hi @abidlabs, thanks for you quick response, this solves my issue!
