### ISSUE TITLE
Error while loading private space

### ISSUE THREAD

**Issue by phanav** [gradio-app/gradio#8596]
### Describe the bug

The following error appears when I tried to load a private huggingface space.
The access token has read permission and seems correct.

I tried to look around in huggingface forum and gradio github, but still have no clue.
I found an existing issue here.
https://github.com/gradio-app/gradio/issues/759

Traceback (most recent call last):
  File "/home/user/app/app.py", line 6, in <module>
    demo = gr.load("phanav/coeurun_back", hf_token=os.getenv("HUGGINGFACE_ACCESS_TOKEN"), src="spaces")
  File "/usr/local/lib/python3.10/site-packages/gradio/external.py", line 60, in load
    return load_blocks_from_repo(
  File "/usr/local/lib/python3.10/site-packages/gradio/external.py", line 99, in load_blocks_from_repo
    blocks: gradio.Blocks = factory_methods[src](name, hf_token, alias, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gradio/external.py", line 423, in from_spaces
    raise ValueError(f"Could not load the Space: {space_name}") from ae
ValueError: Could not load the Space: phanav/coeurun_back
Fetching Space from: https://huggingface.co/spaces/phanav/coeurun_back
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/external.py", line 421, in from_spaces
    config = json.loads(result.group(1))  # type: ignore
AttributeError: 'NoneType' object has no attribute 'group'

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```
import os
import gradio as gr

# read_key = os.environ.get('HF_TOKEN', None)

demo = gr.load("phanav/coeurun_back", hf_token=os.getenv("HUGGINGFACE_ACCESS_TOKEN"), src="spaces")
demo.launch()
```

### System Info

```shell
huggingface gradio sdk

sdk: gradio
sdk_version: 4.36.1
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Can you try the suggestions here please @phanav ? https://github.com/gradio-app/gradio/issues/8564#issuecomment-2179312300

**Comment by abidlabs** [comment]
Going to close for now but we can reopen if we get more information
