### ISSUE TITLE
Gradio doesn't work in an ipython console

### ISSUE THREAD

**Issue by jeberger** [gradio-app/gradio#8701]
### Describe the bug

I tried running the "Quickstart" example in an `ipython` console (_not a Jupyter notebook_, just a plain text console). When I run `demo.launch()`, I can access the demo page from my web browser on http://localhost:7860/ but when I click the submit button, I get an error.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Type this interactively in a plain `ipython` console:

```python
import gradio as gr

def greet (name, intensity):
    return f"{intensity} times hello, {name}!"

gr.Interface (fn = greet, inputs = [ "text", "slider" ], outputs = [ "text" ], analytics_enabled = False).launch()
```

Note that typing the same code in a `test.py` file and running `python test.py` works.

### Logs

```shell
Traceback (most recent call last):
  File ".venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 399,
in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File ".venv\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File ".venv\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File ".venv\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File ".venv\Lib\site-packages\gradio\route_utils.py", line 720, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File ".venv\Lib\site-packages\gradio\route_utils.py", line 736, in simple_response
    await self.app(scope, receive, send)
  File ".venv\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File ".venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File ".venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File ".venv\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File ".venv\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File ".venv\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File ".venv\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File ".venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File ".venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File ".venv\Lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\gradio\routes.py", line 781, in queue_join
    return await queue_join_helper(body, request, username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\gradio\routes.py", line 799, in queue_join_helper
    success, event_id = await blocks._queue.push(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\gradio\queueing.py", line 223, in push
    async with self.pending_message_lock:
TypeError: 'NoneType' object does not support the asynchronous context manager protocol
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 4.37.2
gradio_client version: 1.0.2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.3.0
fastapi: 0.111.0
ffmpy: 0.3.2
gradio-client==1.0.2 is not installed.
httpx: 0.27.0
huggingface-hub: 0.23.4
importlib-resources: 6.4.0
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.9.1
numpy: 2.0.0
orjson: 3.10.6
packaging: 24.1
pandas: 2.2.2
pillow: 10.4.0
pydantic: 2.8.2
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.5.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.30.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.6.1
httpx: 0.27.0
huggingface-hub: 0.23.4
packaging: 24.1
typing-extensions: 4.12.2
websockets: 11.0.3

`pip list` output:


Package                   Version
------------------------- -----------
aiofiles                  23.2.1
altair                    5.3.0
annotated-types           0.7.0
anyio                     4.4.0
asttokens                 2.4.1
attrs                     23.2.0
certifi                   2024.7.4
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
contourpy                 1.2.1
cycler                    0.12.1
decorator                 5.1.1
dnspython                 2.6.1
email_validator           2.2.0
executing                 2.0.1
fastapi                   0.111.0
fastapi-cli               0.0.4
ffmpy                     0.3.2
filelock                  3.15.4
fonttools                 4.53.0
fsspec                    2024.6.1
gradio                    4.37.2
gradio_client             1.0.2
h11                       0.14.0
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.0
huggingface-hub           0.23.4
idna                      3.7
importlib_resources       6.4.0
ipython                   8.26.0
jedi                      0.19.1
Jinja2                    3.1.4
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.1
matplotlib-inline         0.1.7
mdurl                     0.1.2
numpy                     2.0.0
orjson                    3.10.6
packaging                 24.1
pandas                    2.2.2
parso                     0.8.4
pillow                    10.4.0
pip                       24.1.1
prompt_toolkit            3.0.47
pure-eval                 0.2.2
pydantic                  2.8.2
pydantic_core             2.20.1
pydub                     0.25.1
Pygments                  2.18.0
pyparsing                 3.1.2
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-multipart          0.0.9
pytz                      2024.1
PyYAML                    6.0.1
referencing               0.35.1
requests                  2.32.3
rich                      13.7.1
rpds-py                   0.18.1
ruff                      0.5.0
semantic-version          2.10.0
setuptools                65.5.0
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.1
stack-data                0.6.3
starlette                 0.37.2
tomlkit                   0.12.0
toolz                     0.12.1
tqdm                      4.66.4
traitlets                 5.14.3
typer                     0.12.3
typing_extensions         4.12.2
tzdata                    2024.1
ujson                     5.10.0
urllib3                   2.2.2
uvicorn                   0.30.1
watchfiles                0.22.0
wcwidth                   0.2.13
websockets                11.0.3
```
```


### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @jeberger does this solution help resolve this issue as well? https://github.com/gradio-app/gradio/issues/6793

**Comment by abidlabs** [comment]
Closing for lack of follow up, we can reopen if needed

**Comment by jeberger** [comment]
> Closing for lack of follow up, we can reopen if needed

Well, excuse me for not answering work-related questions on the week-end.

That being said, the change from #6785 does fix the problem.
