### ISSUE TITLE
Gradio version upgrade to 4.37.2, image upload error

### ISSUE THREAD

**Issue by yaosheng216** [gradio-app/gradio#8707]
### Describe the bug

Gradio version upgrade to 4.37.2, image upload function cannot load local images，error information is: Connection errored out. Failed to fetch.In the browser console print error log, server not print log error.

Browser console error information:
TypeError: Cannot set properties of undefined (setting 'abort_controller')
    at stream (index.js:2250:10)
    at UploadProgress.svelte:41:18
    at run (svelte.js:41:9)
    at Array.map (<anonymous>)
    at svelte.js:3182:48
    at flush (svelte.js:2141:5)
stream @ index.js:2250
(anonymous) @ UploadProgress.svelte:41
run @ svelte.js:41
(anonymous) @ svelte.js:3182
flush @ svelte.js:2141
Promise.then (async)
schedule_update @ svelte.js:2062
make_dirty @ svelte.js:3216
(anonymous) @ svelte.js:3274
pe @ Upload.svelte:84
await in pe (async)
I @ Upload.svelte:114
await in I (async)
be @ Upload.svelte:121
index.js:2243 
        
POST http://120.27.158.12:2026/upload?upload_id=502h86iwqvx net::ERR_CONNECTION_RESET

Please help me to review this issue
Thanks.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```
with gr.Column(variant='panel', scale=1, min_width=0):
     self.upload_image = gr.Image(
            abel=self.component_names.upload_image,
            sources=['upload'],
            type='pil')

### System Info

```shell
Python version: 3.9
Gradio version: 4.37.2
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @yaosheng216 what version did you upgrade from? I can't reproduce this issue locally so I wonder if it has something to do with how you are deploying Gradio.

Could you reproduce this issue in a reproducible environment such as https://colab.google/ or the [Gradio Playground](https://www.gradio.app/playground)?

**Comment by yaosheng216** [comment]
Hello @abidlabs,my gradio version is from 3.50.1 upgrade to 4.37.2,the problem cannot be reproducible in Gradio Playground  environment.
Thanks of your reply.

**Comment by abidlabs** [comment]
Thanks @yaosheng216 we'll need more information about how you are deploying the Gradio app because we cannot reproduce this on our end. For example, are you deploying behind a reverse proxy like nginx?

**Comment by yaosheng216** [comment]
Hello @abidlabs, services are deployed on cloud servers, not use proxy, this is a development enviroment.

**Comment by yaosheng216** [comment]
Hello @abidlabs, current problem is service deployed on locally, upload image function is success, but service deployed on cloud servers, upload image is error. What causes this.
