### ISSUE TITLE
"IsADirectoryError: [Errno 21] Is a directory" when using gr.File

### ISSUE THREAD

**Issue by joaocarazzato** [gradio-app/gradio#8721]
### Describe the bug

Happens everytime I try to use gr.file as a input/output, after the file gets processed, It doesn't show up as a file or something like that in the chatbot, the file processing goes well, only the output that doesn't work and doesn't work as a binary type too.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import os
import gradio as gr
from langchain.prompts import ChatPromptTemplate
from langchain_community.llms import Ollama
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain.chains import ConversationalRetrievalChain, LLMChain
from langchain.chains.question_answering import load_qa_chain
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from langchain.memory import ConversationBufferMemory

def model_prompting(file_sent):
    if not os.path.isfile(file_sent):
        return "O caminho fornecido não é um arquivo."

    edital_loader = PyPDFLoader(file_sent)
    edital_docs = edital_loader.load()

    # Vetorize docs
    embeddings = HuggingFaceEmbeddings(model_name="BAAI/bge-small-en-v1.5", encode_kwargs={"normalize_embeddings": True})
    edital_vectorstore = FAISS.from_texts([page.page_content for page in edital_docs], embeddings)

    # Conversation buffer memory
    memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)

    # Start model
    model = Ollama(model="phi3:medium")

    # Create prompt template
    template = """
    My template for model understanding.

    """

    # Prompt Object
    prompt = ChatPromptTemplate.from_template(template)

    # Question Prompt Template
    question_prompt = PromptTemplate(
        input_variables=["context", "question"],
        template=""
    )

    # LLM Chain
    question_generator = LLMChain(
        llm=model,
        prompt=question_prompt
    )

    # Q&A Chain
    qa_chain = load_qa_chain(model, chain_type="stuff")

    # Create Conversational Retrieval Chain
    rag_chain = ConversationalRetrievalChain(
        retriever=edital_vectorstore.as_retriever(),
        combine_docs_chain=qa_chain,
        question_generator=question_generator,
        memory=memory,
    )

    # Consult
    prompt_value = prompt.format_prompt(context="", pdf_text="")

    # Initial talk with model to get answer with RAG
    response = rag_chain({"question": prompt_value.to_string()})

    # Model response
    print("\nResposta do Modelo:\n")
    print(response["answer"])
    return response["answer"]

def generate_response(prompt, chat_history):
    response = model_prompting(prompt)
    chat_history.append(("File", response))
    return "", chat_history

with gr.Blocks() as demo:
    title = "LLM Chatbot"
    chatbot = gr.Chatbot()

    file_input = gr.File(label="Select file", type="filepath")
    submit_button = gr.Button("Send file", variant="primary")

    clear = gr.ClearButton([file_input, chatbot], value="Clear chat")

    submit_button.click(generate_response, [file_input, chatbot], [file_input, chatbot])

if __name__ == "__main__":
    demo.launch()

```

### Logs

```shell
Traceback (most recent call last):
  File "/home/joao/.local/lib/python3.10/site-packages/gradio/queueing.py", line 541, in process_events
    response = await route_utils.call_process_api(
  File "/home/joao/.local/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/joao/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1938, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "/home/joao/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1763, in postprocess_data
    outputs_cached = await processing_utils.async_move_files_to_cache(
  File "/home/joao/.local/lib/python3.10/site-packages/gradio/processing_utils.py", line 485, in async_move_files_to_cache
    return await client_utils.async_traverse(
  File "/home/joao/.local/lib/python3.10/site-packages/gradio_client/utils.py", line 999, in async_traverse
    return await func(json_obj)
  File "/home/joao/.local/lib/python3.10/site-packages/gradio/processing_utils.py", line 460, in _move_to_cache
    temp_file_path = await block.async_move_resource_to_block_cache(
  File "/home/joao/.local/lib/python3.10/site-packages/gradio/blocks.py", line 294, in async_move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "/home/joao/.local/lib/python3.10/site-packages/gradio/processing_utils.py", line 250, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "/home/joao/.local/lib/python3.10/site-packages/gradio/processing_utils.py", line 182, in hash_file
    with open(file_path, "rb") as f:
IsADirectoryError: [Errno 21] Is a directory: '/home/joao/Documents/GitHub/KPIs_detect/src'
```

### System Info

```shell
gradio (4.37.2)
importlib-resources (6.1.1)
httpx (0.27.0)
pandas (2.1.3)
uvicorn (0.24.0.post1)
typing-extensions (4.8.0)
matplotlib (3.5.1)
pydub (0.25.1)
typer (0.12.3)
python-multipart (0.0.9)
pyyaml (6.0.1)
ruff (0.5.1)
ffmpy (0.3.1)
numpy (1.25.0)
huggingface-hub (0.23.4)
aiofiles (23.2.1)
packaging (24.0)
gradio-client (1.0.2)
altair (5.1.2)
pydantic (2.8.2)
orjson (3.10.5)
jinja2 (3.1.2)
pillow (9.0.1)
semantic-version (2.10.0)
tomlkit (0.12.0)
fastapi (0.104.1)
urllib3 (2.2.2)
markupsafe (2.1.5)
fsspec (2023.10.0)
websockets (11.0.3)
jsonschema (4.20.0)
toolz (0.12.0)
idna (3.7)
certifi (2024.6.2)
anyio (3.7.1)
httpcore (1.0.2)
sniffio (1.3.0)
h11 (0.14.0)
tqdm (4.66.1)
filelock (3.13.1)
requests (2.31.0)
pytz (2022.1)
tzdata (2023.3)
python-dateutil (2.8.2)
annotated-types (0.6.0)
pydantic-core (2.20.1)
shellingham (1.5.4)
rich (13.7.0)
click (8.1.7)
starlette (0.27.0)
exceptiongroup (1.1.3)
referencing (0.31.0)
attrs (23.1.0)
jsonschema-specifications (2023.11.1)
rpds-py (0.13.1)
six(1.16.0)
markdown-it-py (3.0.0)
pygments (2.17.1)
charset-normalizer (3.3.2)
mdurl (0.1.2)
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
HI @joaocarazzato ! You can't return "" for a file component. It looks like you're trying to clear the value of the file_input component. Can you please try returning None instead?

**Comment by joaocarazzato** [comment]
> HI @joaocarazzato ! You can't return "" for a file component. It looks like you're trying to clear the value of the file_input component. Can you please try returning None instead?

Hi @freddyaboulton! Thanks for the reply! This seems to work, thanks! There's a explanation for why returning None works in this case? 

Besides that, theres any way to get a better exhibition of the file besides a simple text? Thanks!

**Comment by freddyaboulton** [comment]
In general, `None` works to clear out any component into it's empty state. For textboxes, empty strings also work but that's not true in general.

You can display PDF files with this custom PDF component: https://github.com/freddyaboulton/gradio-pdf

For other file types, consider using a different gradio component, e.g. gr.Image for images but there is no general "better file viewer" because it depends on the file type.
