### ISSUE TITLE
Sharing to community is broken on Hugging Face

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#8729]
### Describe the bug

It seems the “Share to Community” button has broken across all Spaces (except old ones) — both native share button and hardcoded-style share buttons

Not working:
https://huggingface.co/spaces/InstantX/InstantID
https://huggingface.co/spaces/gokaygokay/Kolors
https://huggingface.co/spaces/AP123/IllusionDiffusion (here you can also test the hard-coded share to community)
https://huggingface.co/spaces/TencentARC/PhotoMaker

Working (older gradio):
https://huggingface.co/spaces/stabilityai/stable-diffusion

### Native  
The native share button shows a gr.Error toast and some different errors in the console such as 
```
ShareButton.svelte:32 TypeError: dataurl.split is not a function
    at dataURLtoBlob (utils.ts:76:20)
    at uploadToHuggingFace (utils.ts:42:10)
    at func (ImagePreview.svelte:56:16)
    at HTMLButtonElement.click_handler (ShareButton.svelte:27:28)
    at svelte.js:2009:40
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.bubble (svelte.js:2009:21)
    at HTMLButtonElement.click_handler (IconButton.svelte:14:58)
```
and
```
TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
    at utils.ts:9:13
    at Array.map (<anonymous>)
    at Fe (utils.ts:9:9)
    at HTMLButtonElement._ (ShareButton.svelte:27:28)
    at svelte.js:2042:40
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.bubble (svelte.js:2042:21)
    at HTMLButtonElement.P (IconButton.svelte:15:23)
```

### Share to community button 
The hard-coded one (try it here by clicking in the sahre button) shows this Hub error https://huggingface.co/spaces/AP123/IllusionDiffusion  
```
<img src="{"error":"Only GIF, JPEG, JPG, MOV, MP3, MP4, MPGA, PNG, QT, WAV, WEBM, WEBP files are supported"}" />
```
It was working on older gradio versions.

I've tested and the https://huggingface.co/uploads endpoint and it is working flawlessly, including with webp uploads, so I ruled out it being a HF Hub issue. Probably a Gradio issue but I couldn’t isolate the cause, I think it could be how it gets meta-tags from webp files or maybe some routing on how to grab the image file to upload to the Hub that got changed?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Does not apply

### System Info

```shell
all
```

### Severity

I can work around it

**Comment by pngwn** [comment]
This might have been broken since 4.0 release. Need to check.

**Comment by abidlabs** [comment]
cc @aliabid94 as well
