### ISSUE TITLE
Gradio-lite v4.38.1 fails to import PydanticV2

### ISSUE THREAD

**Issue by yongsukyee** [gradio-app/gradio#8776]
### Describe the bug

In Gradio-lite v4.38.1, it uses [pyodide v0.26.1](https://github.com/gradio-app/gradio/blob/main/js/wasm/src/webworker/index.ts#L26) which appears to support [pydantic v2.7.0](https://pyodide.org/en/stable/usage/packages-in-pyodide.html). However while importing modules from pydantic, version 1.10.17 is used instead. This issue might be resolved by [removing these lines](https://github.com/gradio-app/gradio/blob/main/js/wasm/src/webworker/index.ts#L91-L92).

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```html
<html>
<head>
<script type="module" crossorigin src="https://cdn.jsdelivr.net/npm/@gradio/lite@4.38.1/dist/lite.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.css" />
</head>
<body>
<gradio-lite>
<gradio-file name="app.py" entrypoint>
#import micropip
#await micropip.install('pydantic==2.7.0') # will raise ValueError: Requested 'pydantic==2.7.0', but pydantic==1.10.17 is already installed

from pydantic import BaseModel, Field, field_validator, model_validator, ValidationError

def get_text(text=None):
	return text

demo = gr.Interface(get_text, "textbox", "textbox")
demo.launch()
</gradio-file>
</gradio-lite>
</body>
</html>
```

### Logs

```shell
Traceback (most recent call last): File "<exec>", line 103, in _run_script File "<exec>", line 149, in _run_code File "app.py", line 4, in <module> from pydantic import BaseModel, ConfigDict, create_model, Field, field_validator, model_validator, ValidationError, ValidationInfo ImportError: cannot import name 'field_validator' from 'pydantic' (/lib/python3.12/site-packages/pydantic/__init__.py). Did you mean: 'root_validator'?

PythonError: Traceback (most recent call last):
  File "<exec>", line 103, in _run_script
  File "<exec>", line 149, in _run_code
  File "app.py", line 4, in <module>
    from pydantic import BaseModel, ConfigDict, create_model, Field, field_validator, model_validator, ValidationError, ValidationInfo
ImportError: cannot import name 'field_validator' from 'pydantic' (/lib/python3.12/site-packages/pydantic/__init__.py). Did you mean: 'root_validator'?

    at new_error (https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.js:10:9965)
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[302]:0x16dbfd
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[489]:0x177431
    at _PyEM_TrampolineCall_JS (https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.js:10:125894)
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[1134]:0x1c2eaf
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[3602]:0x2c7c0f
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[2167]:0x20a884
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[1142]:0x1c359c
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[1145]:0x1c38ab
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[1146]:0x1c3929
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[3408]:0x29e95d
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[3409]:0x2a4f54
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[1148]:0x1c3a69
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[1143]:0x1c36d2
    at https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.wasm:wasm-function[476]:0x176a95
    at callPyObjectKwargs (https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.js:10:64068)
    at Module.callPyObjectMaybePromising (https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.js:10:65316)
    at wrapper (https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.js:10:27006)
    at Cn.e.port1.onmessage (https://cdn.jsdelivr.net/pyodide/v0.26.1/full/pyodide.asm.js:10:102154)
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.37.2
gradio_client version: 1.0.2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.3.0
fastapi: 0.110.2
ffmpy: 0.3.2
gradio-client==1.0.2 is not installed.
httpx: 0.27.0
huggingface-hub: 0.22.2
importlib-resources: 6.4.0
jinja2: 3.1.3
markupsafe: 2.1.5
matplotlib: 3.8.4
numpy: 1.26.4
orjson: 3.10.1
packaging: 23.2
pandas: 2.2.2
pillow: 10.3.0
pydantic: 2.7.0
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.4.0
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.11.0
urllib3: 2.2.1
uvicorn: 0.29.0
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.27.0
huggingface-hub: 0.22.2
packaging: 23.2
typing-extensions: 4.11.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by whitphx** [comment]
Thanks!
I didn't notice Pydantic v2 became available on the latest Pyodide.
Will fix it.
