### ISSUE TITLE
ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by WanMMao** [gradio-app/gradio#8778]
### Describe the bug

Name: gradio
Version: 4.33.0

Name: gradio_client
Version: 0.17.0

system : windows 11

error info :

Python 3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gradio as gr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin\.conda\envs\chatglm\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "C:\Users\admin\.conda\envs\chatglm\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "C:\Users\admin\.conda\envs\chatglm\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "C:\Users\admin\.conda\envs\chatglm\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\Users\admin\.conda\envs\chatglm\lib\site-packages\gradio\components\annotated_image.py", line 7, in <module>
    import gradio_client.utils as client_utils
  File "C:\Users\admin\.conda\envs\chatglm\lib\site-packages\gradio_client\__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "C:\Users\admin\.conda\envs\chatglm\lib\site-packages\gradio_client\client.py", line 27, in <module>
    import httpx
ValueError: source code string cannot contain null bytes

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

```

### System Info

```shell
Name: gradio
Version: 4.33.0


Name: gradio_client
Version: 0.17.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
@WanMMao it sounds like the issue might be with the way your Python interpreter is loading the Gradio files. Can you try any of the solutions here: https://stackoverflow.com/questions/31233777/python-source-code-string-cannot-contain-null-bytes

**Comment by WanMMao** [comment]
> @WanMMao听起来问题可能出在你的 Python 解释器加载 Gradio 文件的方式上。你可以尝试这里的任何解决方案吗：https://stackoverflow.com/questions/31233777/python-source-code-string-cannot-contain-null-bytes

Using the python environment created by Conda, activating the environment in powershell, powershell reported an error when he executed Impot Gladio gr. It's not clear to me what's wrong with my python interpreter . Thank you!

**Comment by WanMMao** [comment]
There is no error in conda base python version is 3.12.4. In the environment created by conda, this error occurs in python version 3.10.14.

**Comment by WanMMao** [comment]
Sorry, it was indeed an issue with my Conda environment. I recreated the environment and no errors occurred. Thank you
