### ISSUE TITLE
Can't hide clear button with `clear_button=None`

### ISSUE THREAD

**Issue by heaversm** [gradio-app/gradio#8808]
### Describe the bug

You are supposed to be able to hide the clear button with 'None' according to the docs. This throws an error:

```
Traceback (most recent call last):
  File "/Users/mheavers/Documents/Mozilla/Prompt de Resistance/pdr-hf-imagegen/pdr-image-gen/app.py", line 47, in <module>
    iface = gr.Interface(
            ^^^^^^^^^^^^^
  File "/Users/mheavers/Documents/Mozilla/Prompt de Resistance/pdr-hf-imagegen/pdr-image-gen/venv/lib/python3.12/site-packages/gradio/interface.py", line 357, in __init__
    raise ValueError(
ValueError: The clear_btn parameter must be a gr.Button or string, not <class 'list'>
```

using code:

```
iface = gr.Interface(
    fn=display_images,
    inputs=None,
    allow_flagging="never",
    clear_btn=None,
    outputs=gr.Gallery(
        label="Mozweek Images",show_label=True,
        columns=[3],
        rows=[1],
        object_fit="contain",
        height="auto",
        allow_preview=False
    ),
```

in gradio 4.29.0

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
# see above
```

### Screenshot

<img width="724" alt="image" src="https://github.com/user-attachments/assets/2bf64227-9afc-4a29-9186-915cd5d36fe7">

### Logs

```shell
Traceback (most recent call last):
  File "/Users/mheavers/Documents/Mozilla/Prompt de Resistance/pdr-hf-imagegen/pdr-image-gen/app.py", line 47, in <module>
    iface = gr.Interface(
            ^^^^^^^^^^^^^
  File "/Users/mheavers/Documents/Mozilla/Prompt de Resistance/pdr-hf-imagegen/pdr-image-gen/venv/lib/python3.12/site-packages/gradio/interface.py", line 357, in __init__
    raise ValueError(
ValueError: The clear_btn parameter must be a gr.Button or string, not <class 'list'>
```

### System Info

```shell
Mac OS X, gr 4.29.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @heaversm this was introduced in a later version of gradio. Can you please upgrade to the latest version (4.38.1). This minimal example works for me:

```py
import gradio as gr

iface = gr.Interface(
    fn=lambda :["cheetah.jpg"],
    inputs=None,
    allow_flagging="never",
    clear_btn=None,
    outputs=gr.Gallery(
        label="Mozweek Images",show_label=True,
        columns=[3],
        rows=[1],
        object_fit="contain",
        height="auto",
        allow_preview=False
    )
)
    
iface.launch()
```
