### ISSUE TITLE
Gradio Lite Websocket Timeout with OpenAI API

### ISSUE THREAD

**Issue by pbronez** [gradio-app/gradio#8840]
### Describe the bug

I have a simple Gradio app backed by OpenAI's API. It works just fine run locally. When I run it with Gradio-Lite, the chat interface loads but submitting a message produces a terminal Error.

Specifically, I get three of these in a row:

`pyodide.asm.js:10 WebSocket connection to 'ws://api.openai.com:443/' failed: WebSocket is closed before the connection is established.`

and then it dies with:

`pyodide.asm.js:10 openai.APITimeoutError: Request timed out.`

I tried using the Queue() feature and the OpenAI async client. Neither of those solved the problem. I tried setting `stream=False` on the `client.chat.completions.create` call, but then regular Gradio app fails with `AttributeError: 'tuple' object has no attribute 'choices'` and gradio-lite continues to fail with the time out. 

I reproduced the behavior in Chrome 126.0.6478.183 and Safari 17.5 (19618.2.12.11.6).

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```html
<!DOCTYPE html>
<html>
	<head>
		<script type="module" crossorigin src="https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.js"></script>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@gradio/lite/dist/lite.css" />
	</head>
	<body>
		<gradio-lite>
            <gradio-requirements>
                openai
            </gradio-requirements>
            <gradio-file name="app.py" entrypoint>
```
```python
from openai import OpenAI
import gradio as gr

api_key = "<API_KEY>"
client = OpenAI(api_key=api_key)

def predict(message, history):
    history_openai_format = []
    for human, assistant in history:
        history_openai_format.append({"role": "user", "content": human })
        history_openai_format.append({"role": "assistant", "content":assistant})
    history_openai_format.append({"role": "user", "content": message})
  
    response = client.chat.completions.create(
model='gpt-3.5-turbo',
    messages= history_openai_format,
    temperature=1.0,
    stream=True)

    partial_message = ""
    for chunk in response:
        if chunk.choices[0].delta.content is not None:
              partial_message = partial_message + chunk.choices[0].delta.content
              yield partial_message

gr.ChatInterface(predict).launch()
```
```html
        </gradio-file>
		</gradio-lite>
	</body>
</html>
```

### Screenshot

<img width="1197" alt="Screenshot 2024-07-18 at 10 26 37 PM" src="https://github.com/user-attachments/assets/15d9eb22-0d60-4051-9230-62e95bdf9fdc">

### Logs

```shell
pyodide.asm.js:10 Loading micropip, packaging
pyodide.asm.js:10 Loaded micropip, packaging
pyodide.asm.js:10 Loading openssl, pyparsing, setuptools, ssl
pyodide.asm.js:10 Loaded openssl, pyparsing, setuptools, ssl
pyodide.asm.js:10 Loading idna, typing-extensions
pyodide.asm.js:10 Loaded idna, typing-extensions
pyodide.asm.js:10 packaging already loaded from default channel
pyodide.asm.js:10 pyparsing already loaded from default channel
pyodide.asm.js:10 typing-extensions already loaded from default channel
pyodide.asm.js:10 idna already loaded from default channel
pyodide.asm.js:10 Loading Jinja2, MarkupSafe, Pillow, altair, attrs, certifi, charset-normalizer, cycler, fonttools, fsspec, jsonschema, jsonschema_specifications, kiwisolver, matplotlib, matplotlib-pyodide, numpy, orjson, pandas, pyrsistent, python-dateutil, pytz, pyyaml, referencing, requests, rpds-py, six, toolz, tqdm, urllib3
pyodide.asm.js:10 Loaded Jinja2, MarkupSafe, Pillow, altair, attrs, certifi, charset-normalizer, cycler, fonttools, fsspec, jsonschema, jsonschema_specifications, kiwisolver, matplotlib, matplotlib-pyodide, numpy, orjson, pandas, pyrsistent, python-dateutil, pytz, pyyaml, referencing, requests, rpds-py, six, toolz, tqdm, urllib3
pyodide.asm.js:10 /lib/python3.12/site-packages/huggingface_hub/utils/_fixes.py:21: UserWarning: only soft file lock is available
pyodide.asm.js:10   from filelock import BaseFileLock, FileLock, Timeout
pyodide.asm.js:10 WebSocket connection to 'ws://api.openai.com:443/' failed: WebSocket is closed before the connection is established.
pyodide.asm.js:10 WebSocket connection to 'ws://api.openai.com:443/' failed: WebSocket is closed before the connection is established.
pyodide.asm.js:10 WebSocket connection to 'ws://api.openai.com:443/' failed: WebSocket is closed before the connection is established.
pyodide.asm.js:10 Traceback (most recent call last):
pyodide.asm.js:10   File "/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
pyodide.asm.js:10     yield
pyodide.asm.js:10   File "/lib/python3.12/site-packages/httpx/_transports/default.py", line 233, in handle_request
pyodide.asm.js:10     resp = self._pool.handle_request(req)
pyodide.asm.js:10            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
pyodide.asm.js:10     raise exc from None
pyodide.asm.js:10   File "/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
pyodide.asm.js:10     response = connection.handle_request(
pyodide.asm.js:10                ^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
pyodide.asm.js:10     raise exc
pyodide.asm.js:10   File "/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
pyodide.asm.js:10     stream = self._connect(request)
pyodide.asm.js:10              ^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 122, in _connect
pyodide.asm.js:10     stream = self._network_backend.connect_tcp(**kwargs)
pyodide.asm.js:10              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
pyodide.asm.js:10     with map_exceptions(exc_map):
pyodide.asm.js:10   File "/lib/python312.zip/contextlib.py", line 158, in __exit__
pyodide.asm.js:10     self.gen.throw(value)
pyodide.asm.js:10   File "/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
pyodide.asm.js:10     raise to_exc(exc) from exc
pyodide.asm.js:10 httpcore.ConnectTimeout: timed out
pyodide.asm.js:10 
pyodide.asm.js:10 The above exception was the direct cause of the following exception:
pyodide.asm.js:10 
pyodide.asm.js:10 Traceback (most recent call last):
pyodide.asm.js:10   File "/lib/python3.12/site-packages/openai/_base_client.py", line 978, in _request
pyodide.asm.js:10     response = self._client.send(
pyodide.asm.js:10                ^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/httpx/_client.py", line 914, in send
pyodide.asm.js:10     response = self._send_handling_auth(
pyodide.asm.js:10                ^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/httpx/_client.py", line 942, in _send_handling_auth
pyodide.asm.js:10     response = self._send_handling_redirects(
pyodide.asm.js:10                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
pyodide.asm.js:10     response = self._send_single_request(request)
pyodide.asm.js:10                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/httpx/_client.py", line 1015, in _send_single_request
pyodide.asm.js:10     response = transport.handle_request(request)
pyodide.asm.js:10                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/httpx/_transports/default.py", line 232, in handle_request
pyodide.asm.js:10     with map_httpcore_exceptions():
pyodide.asm.js:10   File "/lib/python312.zip/contextlib.py", line 158, in __exit__
pyodide.asm.js:10     self.gen.throw(value)
pyodide.asm.js:10   File "/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
pyodide.asm.js:10     raise mapped_exc(message) from exc
pyodide.asm.js:10 httpx.ConnectTimeout: timed out
pyodide.asm.js:10 
pyodide.asm.js:10 The above exception was the direct cause of the following exception:
pyodide.asm.js:10 
pyodide.asm.js:10 Traceback (most recent call last):
pyodide.asm.js:10   File "/lib/python3.12/site-packages/gradio/queueing.py", line 536, in process_events
pyodide.asm.js:10     response = await route_utils.call_process_api(
pyodide.asm.js:10                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/gradio/route_utils.py", line 276, in call_process_api
pyodide.asm.js:10     output = await app.get_blocks().process_api(
pyodide.asm.js:10              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/gradio/blocks.py", line 1897, in process_api
pyodide.asm.js:10     result = await self.call_function(
pyodide.asm.js:10              ^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/gradio/blocks.py", line 1495, in call_function
pyodide.asm.js:10     prediction = await utils.async_iteration(iterator)
pyodide.asm.js:10                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/gradio/utils.py", line 661, in async_iteration
pyodide.asm.js:10     return await iterator.__anext__()
pyodide.asm.js:10            ^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/gradio/utils.py", line 766, in asyncgen_wrapper
pyodide.asm.js:10     response = await iterator.__anext__()
pyodide.asm.js:10                ^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/gradio/chat_interface.py", line 649, in _stream_fn
pyodide.asm.js:10     first_response = await async_iteration(generator)
pyodide.asm.js:10                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/gradio/utils.py", line 661, in async_iteration
pyodide.asm.js:10     return await iterator.__anext__()
pyodide.asm.js:10            ^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/gradio/utils.py", line 654, in __anext__
pyodide.asm.js:10     return await anyio.to_thread.run_sync(
pyodide.asm.js:10            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "<exec>", line 3, in mocked_anyio_to_thread_run_sync
pyodide.asm.js:10   File "/lib/python3.12/site-packages/gradio/utils.py", line 637, in run_sync_iterator_async
pyodide.asm.js:10     return next(iterator)
pyodide.asm.js:10            ^^^^^^^^^^^^^^
pyodide.asm.js:10   File "app.py", line 14, in predict
pyodide.asm.js:10     response = client.chat.completions.create(model='gpt-3.5-turbo',
pyodide.asm.js:10                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/openai/_utils/_utils.py", line 277, in wrapper
pyodide.asm.js:10     return func(*args, **kwargs)
pyodide.asm.js:10            ^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 643, in create
pyodide.asm.js:10     return self._post(
pyodide.asm.js:10            ^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/openai/_base_client.py", line 1266, in post
pyodide.asm.js:10     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
pyodide.asm.js:10                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/openai/_base_client.py", line 942, in request
pyodide.asm.js:10     return self._request(
pyodide.asm.js:10            ^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/openai/_base_client.py", line 987, in _request
pyodide.asm.js:10     return self._retry_request(
pyodide.asm.js:10            ^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/openai/_base_client.py", line 1079, in _retry_request
pyodide.asm.js:10     return self._request(
pyodide.asm.js:10            ^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/openai/_base_client.py", line 987, in _request
pyodide.asm.js:10     return self._retry_request(
pyodide.asm.js:10            ^^^^^^^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/openai/_base_client.py", line 1079, in _retry_request
pyodide.asm.js:10     return self._request(
pyodide.asm.js:10            ^^^^^^^^^^^^^^
pyodide.asm.js:10   File "/lib/python3.12/site-packages/openai/_base_client.py", line 997, in _request
pyodide.asm.js:10     raise APITimeoutError(request=request) from err
pyodide.asm.js:10 openai.APITimeoutError: Request timed out.
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.38.1
gradio_client version: 1.1.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.3.0
fastapi: 0.111.1
ffmpy: 0.3.0
gradio-client==1.1.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.23.4
importlib-resources: 6.4.0
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.9.1
numpy: 1.26.4
orjson: 3.10.6
packaging: 24.1
pandas: 2.2.2
pillow: 10.4.0
pydantic: 2.8.2
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.5.2
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.30.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.

gradio_client dependencies in your environment:

fsspec: 2024.6.1
httpx: 0.27.0
huggingface-hub: 0.23.4
packaging: 24.1
typing-extensions: 4.12.2
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Lite is no longer maintained but someone can fork it and contribute a fix for this.

Last release of lite: https://github.com/gradio-app/gradio-lite
