### ISSUE TITLE
Get error on adding gr.Request to queue and ZeroGpu

### ISSUE THREAD

**Issue by f1delius** [gradio-app/gradio#8844]
### Describe the bug

Adding request parameters to function cause the pickle error or thread Lock

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import numpy as np
import random
from diffusers import AuraFlowPipeline
import torch
import spaces
import requests

device = "cuda" if torch.cuda.is_available() else "cpu"

#torch.set_float32_matmul_precision("high")

#torch._inductor.config.conv_1x1_as_mm = True
#torch._inductor.config.coordinate_descent_tuning = True
#torch._inductor.config.epilogue_fusion = False
#torch._inductor.config.coordinate_descent_check_all_directions = True

pipe = AuraFlowPipeline.from_pretrained(
	"fal/AuraFlow",
    torch_dtype=torch.float16
).to("cuda")

#pipe.transformer.to(memory_format=torch.channels_last)
#pipe.transformer = torch.compile(pipe.transformer, mode="reduce-overhead", fullgraph=True)
#pipe.transformer.to(memory_format=torch.channels_last)
#pipe.vae.to(memory_format=torch.channels_last)

#pipe.transformer = torch.compile(pipe.transformer, mode="max-autotune", fullgraph=True)
#pipe.vae.decode = torch.compile(pipe.vae.decode, mode="max-autotune", fullgraph=True)

MAX_SEED = np.iinfo(np.int32).max
MAX_IMAGE_SIZE = 1024

def test_func():
    return [prompt, negative_prompt, seed, randomize_seed, width, height, guidance_scale,
                                num_inference_steps, result, seed]

@spaces.GPU
def infer(request: gr.Request ,prompt, negative_prompt="", seed=42, randomize_seed=False, width=1024, height=1024, guidance_scale=5.0, num_inference_steps=28 ,progress=gr.Progress(track_tqdm=True)):

    if randomize_seed:
        seed = random.randint(0, MAX_SEED)
        
    generator = torch.Generator().manual_seed(seed)
    
    
    image = pipe(
        prompt = prompt, 
        negative_prompt = negative_prompt,
        width=width,
        height=height,
        guidance_scale = guidance_scale, 
        num_inference_steps = num_inference_steps, 
        generator = generator
    ).images[0] 
    
    return image, seed

examples = [
    "A photo of a lavender cat",
    "Astronaut in a jungle, cold color palette, muted colors, detailed, 8k",
    "An astronaut riding a green horse",
    "A delicious ceviche cheesecake slice",
]

css="""
#col-container {
    margin: 0 auto;
    max-width: 520px;
}
"""

if torch.cuda.is_available():
    power_device = "GPU"
else:
    power_device = "CPU"

with gr.Blocks(css=css) as demo:
    
    with gr.Column(elem_id="col-container"):
        gr.Markdown(f"""
        # AuraFlow 0.1
        Demo of the [AuraFlow 0.1](https://huggingface.co/fal/AuraFlow) 6.8B parameters open source diffusion transformer model
        [[blog](https://blog.fal.ai/auraflow/)] [[model](https://huggingface.co/fal/AuraFlow)] [[fal](https://fal.ai/models/fal-ai/aura-flow)]
        """)
        
        with gr.Row():
            
            prompt = gr.Text(
                label="Prompt",
                show_label=False,
                max_lines=1,
                placeholder="Enter your prompt",
                container=False,
            )
            
            run_button = gr.Button("Run", scale=0)
        
        result = gr.Image(label="Result", show_label=False)

        with gr.Accordion("Advanced Settings", open=False):
            
            negative_prompt = gr.Text(
                label="Negative prompt",
                max_lines=1,
                placeholder="Enter a negative prompt",
            )
            
            seed = gr.Slider(
                label="Seed",
                minimum=0,
                maximum=MAX_SEED,
                step=1,
                value=0,
            )
            
            randomize_seed = gr.Checkbox(label="Randomize seed", value=True)
            
            with gr.Row():
                
                width = gr.Slider(
                    label="Width",
                    minimum=256,
                    maximum=MAX_IMAGE_SIZE,
                    step=32,
                    value=1024,
                )
                
                height = gr.Slider(
                    label="Height",
                    minimum=256,
                    maximum=MAX_IMAGE_SIZE,
                    step=32,
                    value=1024,
                )
            
            with gr.Row():
                
                guidance_scale = gr.Slider(
                    label="Guidance scale",
                    minimum=0.0,
                    maximum=10.0,
                    step=0.1,
                    value=5.0,
                )
                
                num_inference_steps = gr.Slider(
                    label="Number of inference steps",
                    minimum=1,
                    maximum=50,
                    step=1,
                    value=28,
                )
        
        gr.Examples(
            examples = examples,
            fn = infer,
            inputs = [prompt],
            outputs = [result, seed],
            cache_examples="lazy"
        )

    gr.on(
        triggers=[run_button.click, prompt.submit, negative_prompt.submit],
        fn = infer,
        inputs = [prompt, negative_prompt, seed, randomize_seed, width, height, guidance_scale, num_inference_steps],
        outputs = [result, seed]
    )
    
    demo.load(fn=test_func, outputs=[prompt, negative_prompt, seed, randomize_seed, width, height, guidance_scale,
                                num_inference_steps, result, seed]
    )

demo.queue().launch()
```

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/spaces/utils.py", line 42, in put
    super().put(obj)
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 371, in put
    obj = _ForkingPickler.dumps(obj)
  File "/usr/local/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'Examples.create.<locals>.load_example'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1338, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/spaces/zero/wrappers.py", line 162, in gradio_handler
    worker.arg_queue.put(((args, kwargs), GradioPartialContext.get()))
  File "/usr/local/lib/python3.10/site-packages/spaces/utils.py", line 50, in put
    raise PicklingError(message)
_pickle.PicklingError: Can't pickle local object 'Examples.create.<locals>.load_example'

```

### System Info

```shell
gradio==4.29.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @f1delius can you try upgrading your Gradio version to `4.38.1`? You can do that by upgrading the `sdk_version` in the README.md file. If that doesn't work, can you check if this code works on a regular GPU?

**Comment by f1delius** [comment]
I was trying to run this on huggingface but looks like gradio is locked at 4.26.0 over there,i had 4.29.0 in requirements but it later uninstalls it.

As for pc,I tried to run but its complicated to get it running with cuda and xformers installed and working properly.
As of now,i have decided to skip zerogpu, Thanks for looking into the issue though.

**Comment by f1delius** [comment]
Sorry,I didnt read the Readme part and only realized it later,
I updated the sdk_version to 4.38.1 and still get the same error.

**Comment by seshubonam** [comment]
> Sorry,I didnt read the Readme part and only realized it later, I updated the sdk_version to 4.38.1 and still get the same error. Also,it works with regular gpu,tested it with A10G large

+1

**Comment by abidlabs** [comment]
After some [internal discussion](https://huggingface.slack.com/archives/C05GV830X3K/p1721745499711839?thread_ts=1721678872.147339&cid=C05GV830X3K), it seems the issue is that the `gr.Request` object is not serializable. Suggestion from @cbensimon:

> If this is a reasonable-enough constraint, I think that we should add tests in Gradio codebase to make sure that all the dependency-injected objects are picklable (this is one constraint of ZeroGPU because the function has to run in a subprocess)

**Comment by seshubonam** [comment]
thanks for the feedback. regardless gradio FTW. and great initiative with ZeroGPU.

**Comment by lidar-guy** [comment]
I am having the same issues.  any suggestions welcome!! amazing platform!

**Comment by f1delius** [comment]
We use query_params , it is used to share gradio demos with output and input data entered by user.
using .load and passing a unique id to a function through url query parameters, it loads the data from external db.
The same process is done to save  input and output components data to db.


```
def test_func(request: gr.Request):
    data = request.query_params
    if "msg_id" in data:
        msg_id = data["msg_id"]
        response = requests.get(f"{API_URL}/check_data/{msg_id}")
        if response.status_code == 200:
            api_data = response.json().get("data")
            return [value for value in api_data.values()]
    return prompt, height, width, steps, number_of_images, random_seed, seed, gallery, seed_used
```

**Comment by abidlabs** [comment]
@lidar-guy @seshubonam do you need anything else?

**Comment by seshubonam** [comment]
query_params... yes that would be great. currently thats limiting us for using these demos as embedded applications 

and optionally if ip address and request headers could also be useful for some applications. 
otherwise, we can anyway work around this using the query_params to identify user.

**Comment by seshubonam** [comment]
im assuming this is planned soon query_params 🙈

**Comment by abidlabs** [comment]
Yes, should have a fix next week

**Comment by abidlabs** [comment]
Have a PR here: https://github.com/gradio-app/gradio/pull/9148. To confirm the fix, please try installing Gradio from this PR (you'll need to set the `sdk_version` to 4.41 in Spaces and include the wheel to that PR (mentioned in the PR body) in your `requirements.txt`

**Comment by seshubonam** [comment]
amazing. thanks for the your great support 💯
