### ISSUE TITLE
[`blocks-dev`] Some components throw JS error

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#887]
### Describe the bug

When using the following components, they throw a javascript error so nothing shows up:
* `HighlightedText` 
* `Carousel`

### Reproduction

Run the following demos for each of the above components, respectively:

`demo/diff_texts/run.py`
`demo/disease_report/run.py`

It might also be worth testing the kitchen sink demo to make sure there aren't other components that have the same problem.

### Logs

```shell
index.84342a61.js:3 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at R (index.84342a61.js:3:3273)
    at Yr (vendor.906e418a.js:1:6936)
    at new U (index.84342a61.js:3:3624)
    at V (index.84342a61.js:3:3716)
    at Yr (vendor.906e418a.js:1:7136)
    at new X (index.84342a61.js:3:4447)
    at Bl (index.9cf03fca.js:8:5868)
    at Yr (vendor.906e418a.js:1:7136)
    at new st (index.9cf03fca.js:8:7419)
    at tt (index.9cf03fca.js:8:4729)
```

### System Info

```shell
blocks-dev
```

### Severity

blocker

**Comment by abidlabs** [comment]
Closed via #901
