### ISSUE TITLE
Upgrade Gradio but have problem on upgrade the old codes utilizing the old version of Gradio

### ISSUE THREAD

**Issue by lindawang0122ds** [gradio-app/gradio#8874]
### Describe the bug

Based on your suggestion in [#8866](https://github.com/gradio-app/gradio/issues/8866), I upgraded Gradio to the latest version: 4.39.0. However, while I'm upgrading the code app.py from Track-Anything Model to adapt the latest version of Gradio, I'm not quite sure how to adjust some of them. The specific line of code that shows the TypeError are below, in which both of them (Row and Video) mention got an unexpected keyword argument respectively 

            with gr.Row(scale=0.4): 
                video_input = gr.Video(autosize=True)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks() as iface:
    """
        state for 
    """
    click_state = gr.State([[],[]])
    interactive_state = gr.State({
        "inference_times": 0,
        "negative_click_times" : 0,
        "positive_click_times": 0,
        "mask_save": args.mask_save,
        "multi_mask": {
            "mask_names": [],
            "masks": []
        },
        "track_end_number": None,
        "resize_ratio": 1
    }
    )

    video_state = gr.State(
        {
        "user_name": "",
        "video_name": "",
        "origin_images": None,
        "painted_images": None,
        "masks": None,
        "inpaint_masks": None,
        "logits": None,
        "select_frame_number": 0,
        "fps": 30
        }
    )
    gr.Markdown(title)
    gr.Markdown(description)
    with gr.Row():

        # for user video input
        with gr.Column():
            with gr.Row(scale=0.4): 
                video_input = gr.Video(autosize=True)
                with gr.Column():
                    video_info = gr.Textbox(label="Video Info")
                    resize_info = gr.Textbox(value="If you want to use the inpaint function, it is best to git clone the repo and use a machine with more VRAM locally. \
                                            Alternatively, you can use the resize ratio slider to scale down the original image to around 360P resolution for faster processing.", label="Tips for running this demo.")
                    resize_ratio_slider = gr.Slider(minimum=0.02, maximum=1, step=0.02, value=1, label="Resize ratio", visible=True)

```

### Logs

```shell
Initializing BaseSegmenter to cuda:0
Hyperparameters read from the model weights: C^k=64, C^v=512, C^h=64
Single object mode: False
load pretrained SPyNet...
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmediting/restorers/basicvsr/spynet_20210409-c6c1bd09.pth
Traceback (most recent call last):
  File "/home/suw469/Track-Anything/app.py", line 434, in <module>
    with gr.Row(scale=0.4):
  File "/home/suw469/.local/lib/python3.10/site-packages/gradio/component_meta.py", line 163, in wrapper
    return fn(self, **kwargs)
TypeError: Row.__init__() got an unexpected keyword argument 'scale'




Initializing BaseSegmenter to cuda:0
Hyperparameters read from the model weights: C^k=64, C^v=512, C^h=64
Single object mode: False
load pretrained SPyNet...
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmediting/restorers/basicvsr/spynet_20210409-c6c1bd09.pth
Traceback (most recent call last):
  File "/home/suw469/Track-Anything/app.py", line 436, in <module>
    video_input = gr.Video(autosize=True)
  File "/home/suw469/.local/lib/python3.10/site-packages/gradio/component_meta.py", line 163, in wrapper
    return fn(self, **kwargs)
TypeError: Video.__init__() got an unexpected keyword argument 'autosize'
```

### System Info

```shell
[suw469@compute-g-17-146 Track-Anything]$ pip show gradio
Name: gradio
Version: 4.39.0
Summary: Python library for easily interacting with trained machine learning models
Home-page: 
Author: 
Author-email: Abubakar Abid <gradio-team@huggingface.co>, Ali Abid <gradio-team@huggingface.co>, Ali Abdalla <gradio-team@huggingface.co>, Dawood Khan <gradio-team@huggingface.co>, Ahsen Khaliq <gradio-team@huggingface.co>, Pete Allen <gradio-team@huggingface.co>, Ömer Faruk Özdemir <gradio-team@huggingface.co>, Freddy A Boulton <gradio-team@huggingface.co>, Hannah Blair <gradio-team@huggingface.co>
License: 
Location: /home/suw469/.local/lib/python3.10/site-packages
Requires: aiofiles, anyio, fastapi, ffmpy, gradio-client, httpx, huggingface-hub, importlib-resources, jinja2, markupsafe, matplotlib, numpy, orjson, packaging, pandas, pillow, pydantic, pydub, python-multipart, pyyaml, ruff, semantic-version, tomlkit, typer, typing-extensions, urllib3, uvicorn
Required-by:
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @lindawang0122ds please see the list of breaking changes in 4.0: https://github.com/gradio-app/gradio/issues/6339

In this case, I believe you should be able to just remove these two parameters and the app should render all right, but there might be more significant changes you need to make in order to use 4.0 as described in the issue above^
