### ISSUE TITLE
[`blocks-dev`] Clear button does not work in sketchpad

### ISSUE THREAD

**Issue by abidlabs** [gradio-app/gradio#888]
### Describe the bug

The clear button does not do anything in the sketchpad component

### Reproduction

`demo\digit_classifier\run.py`

### Screenshot

![image](https://user-images.githubusercontent.com/1778297/160425934-ea010721-7b02-4db3-b32a-79f3d579fc5a.png)

### Logs

```shell
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'label')
    at O (index.b60e4c0e.js:2:413)
    at Yr (vendor.906e418a.js:1:7136)
    at new Q (index.b60e4c0e.js:2:1183)
    at H (index.b60e4c0e.js:2:1249)
    at Object.p (index.b60e4c0e.js:2:1668)
    at Dt (vendor.906e418a.js:1:4796)
    at st (vendor.906e418a.js:1:4470)
```

### System Info

```shell
blocks-dev
```

### Severity

critical

**Comment by dawoodkhan82** [comment]
Doesn't seem to be a bug anymore
