### ISSUE TITLE
Invalid URL Error

### ISSUE THREAD

**Issue by Nullsire** [gradio-app/gradio#8902]
### Describe the bug

I have seen somebody report similiar issues, but I didn't find a nice way to solve the problem. 
Currently I comment out line 161 and 162 in _urlparse.py to avoid it.

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

```python
def greet(name, intensity):
    return "Hello, " + name + "!" * int(intensity)

demo = gr.Interface(
    fn=greet,
    inputs=["text", "slider"],
    outputs=["text"],
)

demo.launch()
```

### Screenshot

Traceback (most recent call last):
  File "/home/disk2/zgy/MiniGPT/self_regression/sample_gradio.py", line 1, in <module>
    import gradio as gr
  File "/home/user/HKD/miniconda3/envs/ML_test/lib/python3.12/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/home/user/HKD/miniconda3/envs/ML_test/lib/python3.12/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/home/user/HKD/miniconda3/envs/ML_test/lib/python3.12/site-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import Component, FormComponent
  File "/home/user/HKD/miniconda3/envs/ML_test/lib/python3.12/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/user/HKD/miniconda3/envs/ML_test/lib/python3.12/site-packages/gradio/components/annotated_image.py", line 13, in <module>
    from gradio import processing_utils, utils
  File "/home/user/HKD/miniconda3/envs/ML_test/lib/python3.12/site-packages/gradio/processing_utils.py", line 99, in <module>
    sync_client = httpx.Client(transport=sync_transport)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/HKD/miniconda3/envs/ML_test/lib/python3.12/site-packages/httpx/_client.py", line 696, in __init__
    URLPattern(key): None
    ^^^^^^^^^^^^^^^
  File "/home/user/HKD/miniconda3/envs/ML_test/lib/python3.12/site-packages/httpx/_utils.py", line 370, in __init__
    url = URL(pattern)
          ^^^^^^^^^^^^
  File "/home/user/HKD/miniconda3/envs/ML_test/lib/python3.12/site-packages/httpx/_urls.py", line 115, in __init__
    self._uri_reference = urlparse(url, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/HKD/miniconda3/envs/ML_test/lib/python3.12/site-packages/httpx/_urlparse.py", line 162, in urlparse
    raise InvalidURL("Invalid non-printable ASCII character in URL")
httpx.InvalidURL: Invalid non-printable ASCII character in URL

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.39.0
gradio_client version: 1.1.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.4.0
fastapi: 0.111.1
ffmpy: 0.3.2
gradio-client==1.1.1 is not installed.
httpx: 0.27.0
huggingface-hub: 0.24.0
importlib-resources: 6.4.0
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.9.1
numpy: 1.26.4
orjson: 3.10.6
packaging: 24.1
pandas: 2.2.2
pillow: 10.4.0
pydantic: 2.8.2
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.5.4
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.30.3
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.5.0
httpx: 0.27.0
huggingface-hub: 0.24.0
packaging: 24.1
typing-extensions: 4.12.2
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
I can't repro this problem even with that version of httpx installed. Will close for now
