### ISSUE TITLE
[Regression] `cache_examples="lazy"` broken on `4.39.0`

### ISSUE THREAD

**Issue by apolinario** [gradio-app/gradio#8925]
### Describe the bug

Lazy caching examples isn't working on `4.39.0`

When the any example is clicked for the first time, it does run the function correctly and displays the output. However, if clicked again it errors:
```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 663, in async_iteration
    return await iterator.__anext__()
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 656, in __anext__
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 639, in run_sync_iterator_async
    return next(iterator)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 801, in gen_wrapper
    response = next(iterator)
  File "/usr/local/lib/python3.10/site-packages/gradio/helpers.py", line 437, in sync_lazy_cache
    cached_index = self._get_cached_index_if_cached(example_index)
  File "/usr/local/lib/python3.10/site-packages/gradio/helpers.py", line 360, in _get_cached_index_if_cached
    cached_indices = [int(line.strip()) for line in f]
  File "/usr/local/lib/python3.10/site-packages/gradio/helpers.py", line 360, in <listcomp>
    cached_indices = [int(line.strip()) for line in f]
ValueError: invalid literal for int() with base 10: "(0, ['building.jpeg'])"
```

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Repro Space: https://huggingface.co/spaces/multimodalart/cache_lazy_test

Repro Code: 
```python
import gradio as gr

def magic(image):
    return image

EXAMPLES = ["building.jpeg", "bird.webp"]

with gr.Blocks() as demo:
    image = gr.Image()
    output = gr.Image()
    btn = gr.Button("Do magic")
    btn.click(fn=magic, inputs=image, outputs=output)

    examples = gr.Examples(
            examples = EXAMPLES,
            fn = magic,
            inputs=[image],
            outputs=[output],
            cache_examples="lazy",
    )

if __name__ == "__main__":
    demo.launch()
```

### System Info

```shell
gradio==4.39.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
I'll take a look!
