### ISSUE TITLE
`cache_examples=True` doesn't work for `gr.ChatInterface` when `multimodal=True`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#8971]
### Describe the bug

`ValueError` occurs when using `cache_examples=True` in multimodal chatbot.

(I originally reported this as a part of #8963, but looks like it's a separate issue, so I'm opening this one.)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

repro: https://huggingface.co/spaces/hysts-debug/multimodal-chat-cache-examples

```python
import gradio as gr


def run(message, history):
    return message["text"]


examples = [
    {
        "text": "hey",
        "files": ["cats.jpg"],
    },
]

demo = gr.ChatInterface(
    fn=run,
    multimodal=True,
    examples=examples,
    cache_examples=True,
)
demo.queue().launch()
```

### Logs

```shell
===== Application Startup at 2024-08-02 06:44:18 =====

Caching examples at: '/home/user/app/gradio_cached_examples/14'
Caching example 1/1
Traceback (most recent call last):
  File "/home/user/app/app.py", line 15, in <module>
    demo = gr.ChatInterface(
  File "/usr/local/lib/python3.10/site-packages/gradio/chat_interface.py", line 325, in __init__
    self.examples_handler._start_caching()
  File "/usr/local/lib/python3.10/site-packages/gradio/helpers.py", line 391, in _start_caching
    client_utils.synchronize_async(self.cache)
  File "/usr/local/lib/python3.10/site-packages/gradio_client/utils.py", line 855, in synchronize_async
    return fsspec.asyn.sync(fsspec.asyn.get_loop(), func, *args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/usr/local/lib/python3.10/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/usr/local/lib/python3.10/site-packages/gradio/helpers.py", line 517, in cache
    prediction = await Context.root_block.process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1933, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1756, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/site-packages/gradio/components/chatbot.py", line 491, in postprocess
    return self._postprocess_messages_tuples(cast(TupleFormat, value))
  File "/usr/local/lib/python3.10/site-packages/gradio/components/chatbot.py", line 425, in _postprocess_messages_tuples
    self._postprocess_content(message_pair[0]),
  File "/usr/local/lib/python3.10/site-packages/gradio/components/chatbot.py", line 418, in _postprocess_content
    raise ValueError(f"Invalid message for Chatbot component: {chat_message}")
ValueError: Invalid message for Chatbot component: {'text': 'hey', 'files': ['/tmp/gradio/5ac01cc65ae664ba34fbf70c592d9ec922953353/cats.jpg']}
Caching examples at: '/home/user/app/gradio_cached_examples/14'
Caching example 1/1
```

### System Info

```shell
gradio==4.40.0
```

### Severity

I can work around it

**Comment by hysts** [comment]
(Looks like I accidentally pasted the old code with a bug in the `run` function. I fixed the code above so it can run when `cache_examples=False`. There's nothing to change about the error log when `cache_examples=True`, though.)

**Comment by abidlabs** [comment]
Closed via https://github.com/gradio-app/gradio/pull/8966, thanks @dawoodkhan82!
