### ISSUE TITLE
error 404: Session not found when configured with two upstream servers in nginx configuration 

### ISSUE THREAD

**Issue by jasnei** [gradio-app/gradio#9070]
### Describe the bug

I tried to configured with two upstream servers in nginx configuration, it seems that the configuration of nginx is working. But I keep getting 404 error (Session not found). However, one upstream server was down, then the other server is working perfectly.
I also write a testing code with FastAPI framework and with same nginx configuration, both upstream servers work.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Here is simple gradio script for reproduction. 

```python
import argparse
import logging

import gradio as gr

logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

argparser = argparse.ArgumentParser()
argparser.add_argument("--port", type=int, default=7861,
                       help="Port to run the server on")
args = argparser.parse_args()


def text_length(text):
    logging.info(f"Request received: {text}")
    return len(text)


# Create a Gradio interface
iface = gr.Interface(
    fn=text_length,
    inputs="text",
    outputs="number",
    title="Text Length Calculator",
    description="Enter some text to get its length."
)

# Launch the interface
iface.launch(server_port=args.port, debug=True)
```

I start two processes by following command
```bash
python gradio_simple.py --port 7861
python gradio_simple.py --port 7863
```

here is FastAPI scrip
```python
import argparse
import os

import uvicorn
from fastapi import FastAPI

argparser = argparse.ArgumentParser()
argparser.add_argument("--port", type=int, default=7861,
                       help="Port to run the server on")
args = argparser.parse_args()

app = FastAPI()


@app.get("/")
def read_root():
    print('Hello')
    return {"Hello": "World"}


@app.get("/items/{item_id}")
def read_item(item_id: int, q: str = None):
    return {"item_id": item_id, "q": q}


if __name__ == "__main__":
    # Get the port from an environment variable or default to 8000
    port = int(args.port)
    uvicorn.run(app, host="127.0.0.1", port=port)
```

here is the config of nginx
`nginx.conf`
```bash
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;

    upstream backend {
        server 127.0.0.1:7863 max_fails=3 fail_timeout=10s;
        server 127.0.0.1:7861 max_fails=3 fail_timeout=10s;
        keepalive 32;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
            # proxy_set_header Host $host; # i changed proxy_set_header Host $http_host; still not work
            # proxy_set_header X-Real-IP $remote_addr;
            # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # proxy_set_header X-Forwarded-Proto $scheme;

            proxy_buffering off;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Increase timeout settings
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;

        }
    }

}
```

### Screenshot

here is the screenshot for the error
![image](https://github.com/user-attachments/assets/7b166e7f-1bf0-478f-9623-24906b2deb37)

### Logs

```shell
here is gradio debug logs 

To create a public link, set `share=True` in `launch()`.
2024-08-09 11:31:53,267 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2024-08-09 11:31:53,267 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2024-08-09 11:31:53,305 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f63a175e350>
2024-08-09 11:31:53,306 - httpcore.connection - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x7f63a1700b40> server_hostname='api.gradio.app' timeout=3
2024-08-09 11:31:53,655 - httpcore.connection - DEBUG - start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7f63a175e320>
2024-08-09 11:31:53,655 - httpcore.http11 - DEBUG - send_request_headers.started request=<Request [b'GET']>
2024-08-09 11:31:53,655 - httpcore.http11 - DEBUG - send_request_headers.complete
2024-08-09 11:31:53,655 - httpcore.http11 - DEBUG - send_request_body.started request=<Request [b'GET']>
2024-08-09 11:31:53,655 - httpcore.http11 - DEBUG - send_request_body.complete
2024-08-09 11:31:53,655 - httpcore.http11 - DEBUG - receive_response_headers.started request=<Request [b'GET']>
2024-08-09 11:31:53,836 - httpcore.http11 - DEBUG - receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Date', b'Fri, 09 Aug 2024 03:31:54 GMT'), (b'Content-Type', b'application/json'), (b'Content-Length', b'21'), (b'Connection', b'keep-alive'), (b'Server', b'nginx/1.18.0'), (b'Access-Control-Allow-Origin', b'*')])
2024-08-09 11:31:53,836 - httpx - INFO - HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
2024-08-09 11:31:53,836 - httpcore.http11 - DEBUG - receive_response_body.started request=<Request [b'GET']>
2024-08-09 11:31:53,836 - httpcore.http11 - DEBUG - receive_response_body.complete
2024-08-09 11:31:53,836 - httpcore.http11 - DEBUG - response_closed.started
2024-08-09 11:31:53,836 - httpcore.http11 - DEBUG - response_closed.complete
2024-08-09 11:31:53,836 - httpcore.connection - DEBUG - close.started
2024-08-09 11:31:53,837 - httpcore.connection - DEBUG - close.complete
2024-08-09 11:32:19,592 - matplotlib - DEBUG - matplotlib data path: /home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/matplotlib/mpl-data
2024-08-09 11:32:19,595 - matplotlib - DEBUG - CONFIGDIR=/home/jasnei/.config/matplotlib
2024-08-09 11:32:19,596 - matplotlib - DEBUG - interactive is False
2024-08-09 11:32:19,596 - matplotlib - DEBUG - platform is linux
2024-08-09 11:32:19,625 - matplotlib - DEBUG - CACHEDIR=/home/jasnei/.cache/matplotlib
2024-08-09 11:32:19,625 - matplotlib.font_manager - DEBUG - Using fontManager instance from /home/jasnei/.cache/matplotlib/fontlist-v390.json
2024-08-09 11:32:19,748 - matplotlib.pyplot - DEBUG - Loaded backend tkagg version 8.6.
2024-08-09 11:32:19,748 - matplotlib.pyplot - DEBUG - Loaded backend agg version v2.2.
2024-08-09 11:32:19,748 - root - INFO - Request received: 123456
2024-08-09 11:32:19,749 - matplotlib.pyplot - DEBUG - Loaded backend tkagg version 8.6.
```

second logs
```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/responses.py", line 265, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap
    await func()
  File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/responses.py", line 238, in listen_for_disconnect
    message = await receive()
  File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 553, in receive
    await self.message_event.wait()
  File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f4a99c51210

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
  |     return await self.app(scope, receive, send)
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/gradio/route_utils.py", line 714, in __call__
  |     await self.app(scope, receive, send)
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
  |     await route.handle(scope, receive, send)
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/responses.py", line 258, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap
    |     await func()
    |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/gradio/routes.py", line 954, in sse_stream
    |     raise e
    |   File "/home/jasnei/miniconda3/envs/hf/lib/python3.10/site-packages/gradio/routes.py", line 889, in sse_stream
    |     raise HTTPException(
    | fastapi.exceptions.HTTPException: 404: Session not found.
    +------------------------------------
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.37.1
gradio_client version: 1.0.2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
altair: 5.3.0
fastapi: 0.111.1
ffmpy: 0.4.0
gradio-client==1.0.2 is not installed.
httpx: 0.27.0
huggingface-hub: 0.23.3
importlib-resources: 6.4.0
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.9.1
numpy: 1.26.4
orjson: 3.10.6
packaging: 24.1
pandas: 2.2.2
pillow: 10.3.0
pydantic: 2.8.2
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.5.5
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.12.2
urllib3: 2.2.1
uvicorn: 0.30.4
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.2.0
httpx: 0.27.0
huggingface-hub: 0.23.3
packaging: 24.1
typing-extensions: 4.12.2
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @jasnei you will need to enable sticky sessions i.e. a ensure that a client's requests are consistently routed to the same backend server

can you try updating the `upstream backend` block to this:

```
upstream backend {
    ip_hash;
    server 127.0.0.1:7863;
    server 127.0.0.1:7861;
    keepalive 32;
}
```

**Comment by jasnei** [comment]
Hi @abidlabs 

Thanks for your advice, I had tried to update the `upstream backend`  as you suggested.

I would get 404 error anymore. However, there is only one server could get all the request, instead of two.

**Comment by abidlabs** [comment]
Hi @jasnei yes that's expected. What's happening is that all requests from the same IP address are going to the same server. There are different ways to do sticky sessions that you can see here: https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/

**Comment by jasnei** [comment]
Hi @abidlabs. Thanks for your help. However, that's not what I want. I would like load balancing for both or more servers. I am new to nginx, and I will keep looking how to configure for load balancing. you may close this issue.
