### ISSUE TITLE
Got Unexpected datatype

### ISSUE THREAD

**Issue by avcode-exe** [gradio-app/gradio#9107]
### Describe the bug

I got datatype of `message` to be `<class 'gradio.components.multimodal_textbox.MultimodalData'>` instead of `<class 'dict'>`, hence `messages["text"]` breaks.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import time
import gradio as gr

class response_test:
    def __init__(self):
        self.text = "test"

def chatbot_nightly(message, history):
    print(type(message))  # Got <class 'gradio.components.multimodal_textbox.MultimodalData'>
    print(message)  # Return text='hi' files=[]
    message_text = message["text"]  # Breaks here
    message_files = message["files"]
    
    response_nightly = response_test()

    # Suspect the culprit is the for loop below
    for i in range(len(response_nightly.text)):
        time.sleep(0.05)
        yield response_nightly.text[:i + 1]

gr.ChatInterface(
    chatbot_nightly,
    title='name',
    multimodal=True
).queue().launch(debug=True, show_error=True, share=True)
```

### Screenshot

![image](https://github.com/user-attachments/assets/c832e1ee-d6e8-48f0-be1d-354c9c27bcb8)

### Logs

```shell
To create a public link, set `share=True` in `launch()`.
<class 'gradio.components.multimodal_textbox.MultimodalData'>
text='hi' files=[]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 288, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1931, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1528, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 671, in async_iteration
    return await iterator.__anext__()
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 776, in asyncgen_wrapper
    response = await iterator.__anext__()
  File "/usr/local/lib/python3.10/site-packages/gradio/chat_interface.py", line 651, in _stream_fn
    first_response = await async_iteration(generator)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 671, in async_iteration
    return await iterator.__anext__()
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 664, in __anext__
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 647, in run_sync_iterator_async
    return next(iterator)
  File "/home/user/app/app.py", line 464, in chatbot_nightly
    message_text = message["text"]
TypeError: 'MultimodalData' object is not subscriptable
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.41.0
gradio_client version: 1.3.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.4.0
fastapi: 0.112.0
ffmpy: 0.4.0
gradio-client==1.3.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.24.5
importlib-resources: 6.4.0
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.9.2
numpy: 2.0.1
orjson: 3.10.7
packaging: 24.1
pandas: 2.2.2
pillow: 10.4.0
pydantic: 2.8.2
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.2
ruff: 0.5.7
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.3
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.30.5
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.6.1
httpx: 0.27.0
huggingface-hub: 0.24.5
packaging: 24.1
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
I know what the issue is @avcode-exe
