### ISSUE TITLE
TypeError: Object of type JsonData is not JSON serializable When Using gr.JSON in HTTP API

### ISSUE THREAD

**Issue by xribene** [gradio-app/gradio#9184]
### Describe the bug

Building a Gradio app with gr.Blocks and using `gr.JSON` to display data. UI works fine, but when trying to access the data through the HTTP API (curl), I get a TypeError that `JsonData` can't be serialized by `json.dumps`.

A hack to temporarily fix the problem is by replacing
```python
return f"event: {event}\ndata: {json.dumps(data)}\n\n"
```
with
```python
if data[0].__class__.__name__ == "JsonData":
    data = data[0].root
return f"event: {event}\ndata: {json.dumps(data)}\n\n"
```
in 
[https://github.com/gradio-app/gradio/blob/main/gradio/routes.py#L908](https://github.com/gradio-app/gradio/blob/main/gradio/routes.py#L908)

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Here is a toy example to reproduce the issue.
```python
import gradio as gr

def get_sample_data():
    sample_data = {
        "name": "xribene",
    }
    return sample_data

with gr.Blocks() as demo:
    json_output = gr.JSON(label="User Information")
    show_data_button = gr.Button("Show Data")
    show_data_button.click(
        fn=get_sample_data,
        inputs=[],
        outputs=json_output
    )
    
demo.queue()
demo.launch(share=True, show_error=True)
```

After that, run 
```bash
curl -X POST http://127.0.0.1:7860/call/get_sample_data -s -H "Content-Type: application/json" -d '{
  "data": [
]}' \
  | awk -F'"' '{ print $4}'  \
  | read EVENT_ID; curl -N http://127.0.0.1:7860/call/get_sample_data/$EVENT_ID
```

### Logs

```shell
+-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/xribene/miniconda3/envs/gradioapp/lib/python3.12/site-packages/starlette/responses.py", line 261, in wrap
    |     await func()
    |   File "/Users/xribene/miniconda3/envs/gradioapp/lib/python3.12/site-packages/starlette/responses.py", line 250, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/Users/xribene/Projects/gradio/gradio/routes.py", line 957, in sse_stream
    |     raise e
    |   File "/Users/xribene/Projects/gradio/gradio/routes.py", line 921, in sse_stream
    |     response = process_msg(message)
    |                ^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/xribene/Projects/gradio/gradio/routes.py", line 859, in process_msg
    |     return f"event: {event}\ndata: {json.dumps(data)}\n\n"
    |                                     ^^^^^^^^^^^^^^^^
    |   File "/Users/xribene/miniconda3/envs/gradioapp/lib/python3.12/json/__init__.py", line 231, in dumps
    |     return _default_encoder.encode(obj)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/xribene/miniconda3/envs/gradioapp/lib/python3.12/json/encoder.py", line 200, in encode
    |     chunks = self.iterencode(o, _one_shot=True)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/xribene/miniconda3/envs/gradioapp/lib/python3.12/json/encoder.py", line 258, in iterencode
    |     return _iterencode(o, 0)
    |            ^^^^^^^^^^^^^^^^^
    |   File "/Users/xribene/miniconda3/envs/gradioapp/lib/python3.12/json/encoder.py", line 180, in default
    |     raise TypeError(f'Object of type {o.__class__.__name__} '
    | TypeError: Object of type JsonData is not JSON serializable
    +------------------------------------
```

### System Info

```shell
- Gradio: 4.42.0
- Python: 3.12
- OS: MacOS M1
```

### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Thanks for reporting @xribene
