### ISSUE TITLE
SessionMiddleware error when launching gradios

### ISSUE THREAD

**Issue by nicolas-dufour** [gradio-app/gradio#9240]
### Describe the bug

When i'm launching demos that used to work 2 days ago i currently get the following error:
```
Traceback (most recent call last):
  File "/home/dufour/miniconda3/envs/diffusion/lib/python3.10/site-packages/gradio/queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/dufour/miniconda3/envs/diffusion/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/dufour/miniconda3/envs/diffusion/lib/python3.10/site-packages/gradio/blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "/home/dufour/miniconda3/envs/diffusion/lib/python3.10/site-packages/gradio/blocks.py", line 1137, in call_function
    processed_input, progress_index, _ = special_args(
  File "/home/dufour/miniconda3/envs/diffusion/lib/python3.10/site-packages/gradio/helpers.py", line 772, in special_args
    getattr(request, "session", {})
  File "/home/dufour/miniconda3/envs/diffusion/lib/python3.10/site-packages/gradio/route_utils.py", line 125, in __getattr__
    return self.dict_to_obj(getattr(self.request, name))
  File "/home/dufour/miniconda3/envs/diffusion/lib/python3.10/site-packages/starlette/requests.py", line 148, in session
    "session" in self.scope
AssertionError: SessionMiddleware must be installed to access request.session
```

The demo launchs but as soon i interact with it i get the same error.
The weird part is that everything worked and i didn't update anything
This is an issue both using share=True or not

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Launch a demo

### System Info

```shell
gradio==4.42
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @nicolas-dufour that's strange, can you try reinstalling Gradio and its requirements? I wonder if some dependency of Gradio, such as `fastapi` got updated

**Comment by abidlabs** [comment]
Closing for lack of repro

**Comment by unclemusclez** [comment]
```bash
Traceback (most recent call last):
  File "/home/musclez/.local/lib/python3.11/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musclez/.local/lib/python3.11/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musclez/.local/lib/python3.11/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musclez/.local/lib/python3.11/site-packages/gradio/blocks.py", line 1506, in call_function
    processed_input, progress_index, _ = special_args(
                                         ^^^^^^^^^^^^^
  File "/home/musclez/.local/lib/python3.11/site-packages/gradio/helpers.py", line 922, in special_args
    getattr(request, "session", {})
  File "/home/musclez/.local/lib/python3.11/site-packages/gradio/route_utils.py", line 176, in __getattr__
    return self.dict_to_obj(getattr(self.request, name))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musclez/.local/lib/python3.11/site-packages/starlette/requests.py", line 154, in session
    assert "session" in self.scope, "SessionMiddleware must be installed to access request.session"
           ^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: SessionMiddleware must be installed to access request.session

also getting this when trying to build a gradio app locally.
