### ISSUE TITLE
pydantic.errors.PydanticSchemaGenerationError in Gradio 4.42.0

### ISSUE THREAD

**Issue by Kugelblitz25** [gradio-app/gradio#9275]
### Describe the bug

I'm getting pydantic.errors.PydanticSchemaGenerationError even on the quick-start code from the [website](https://www.gradio.app/guides/quickstart). 
I am using:
- `Python 3.10.12`
- `Gradio 4.42.0`

Error Log:
```sh
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/type_adapter.py", line 279, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/type_adapter.py", line 121, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/gradio/route_utils.py", line 766, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/gradio/route_utils.py", line 782, in simple_response
    await self.app(scope, receive, send)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 639, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 810, in request_body_to_args
    fields_to_extract = get_model_fields(first_field.type_)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/fastapi/_compat.py", line 283, in get_model_fields
    return [
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/fastapi/_compat.py", line 284, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/fastapi/_compat.py", line 109, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/type_adapter.py", line 266, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/type_adapter.py", line 144, in wrapped
    return func(self, *args, **kwargs)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/type_adapter.py", line 286, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/type_adapter.py", line 104, in _get_schema
    schema = gen.generate_schema(type_)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2025, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2104, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2186, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2182, in <lambda>
    lambda source, handler: handler(source)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2085, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "/home/vihans16/.cache/pypoetry/virtualenvs/nlp-WiEU4Jtf-py3.10/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
``` 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def greet(name, intensity):
    return "Hello, " + name + "!" * int(intensity)

demo = gr.Interface(
    fn=greet,
    inputs=["text", "slider"],
    outputs=["text"],
)

demo.launch()
```

### Screenshot

![image](https://github.com/user-attachments/assets/eca35f10-b5c7-421f-8cb5-8aa7240785a9)

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.42.0
gradio_client version: 1.3.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.4.0
fastapi: 0.113.0
ffmpy: 0.4.0
gradio-client==1.3.0 is not installed.
httpx: 0.27.2
huggingface-hub: 0.24.6
importlib-resources: 6.4.4
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.9.2
numpy: 1.26.4
orjson: 3.10.7
packaging: 24.1
pandas: 2.2.2
pillow: 10.4.0
pydantic: 2.9.0
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.2
ruff: 0.6.4
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.5
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.30.6
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.9.0
httpx: 0.27.2
huggingface-hub: 0.24.6
packaging: 24.1
typing-extensions: 4.12.2
websockets: 11.0.3
```

### Severity

Blocking usage of gradio

**Comment by BenCaunt** [comment]
I am having the same issue

**Comment by FurkanGozukara** [comment]
this pydantic  broken my just gradio having app just gradio

so annoying

all gradio apps are broken

i think fastapi broken it

```
2024-09-06 00:12:20,515 - INFO - HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
Running on local URL:  http://127.0.0.1:7860
2024-09-06 00:12:20,542 - INFO - HTTP Request: GET http://127.0.0.1:7860/startup-events "HTTP/1.1 200 OK"
2024-09-06 00:12:20,552 - INFO - HTTP Request: HEAD http://127.0.0.1:7860/ "HTTP/1.1 200 OK"

To create a public link, set `share=True` in `launch()`.
2024-09-06 00:12:20,673 - INFO - HTTP Request: GET https://checkip.amazonaws.com/ "HTTP/1.1 200 "
2024-09-06 00:12:21,337 - INFO - HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\type_adapter.py", line 209, in __init__
    core_schema = _getattr_no_parents(type, '__pydantic_core_schema__')
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\type_adapter.py", line 98, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\gradio\route_utils.py", line 766, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\gradio\route_utils.py", line 782, in simple_response
    await self.app(scope, receive, send)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\fastapi\routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\fastapi\dependencies\utils.py", line 639, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\fastapi\dependencies\utils.py", line 810, in request_body_to_args
    fields_to_extract = get_model_fields(first_field.type_)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\fastapi\_compat.py", line 283, in get_model_fields
    return [
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\fastapi\_compat.py", line 284, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\fastapi\_compat.py", line 109, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\type_adapter.py", line 211, in __init__
    core_schema = _get_schema(type, config_wrapper, parent_depth=_parent_depth + 1)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\type_adapter.py", line 81, in _get_schema
    schema = gen.generate_schema(type_)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 490, in generate_schema
    schema = self._generate_schema(obj)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 721, in _generate_schema
    schema = self._generate_schema_inner(obj)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 727, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1697, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1765, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1847, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1843, in <lambda>
    lambda source, handler: handler(source)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1746, in inner_handler
    schema = self._generate_schema(obj)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 721, in _generate_schema
    schema = self._generate_schema_inner(obj)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 747, in _generate_schema_inner
    return self.match_type(obj)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 830, in match_type
    return self._match_generic_type(obj, origin)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 854, in _match_generic_type
    return self._union_schema(obj)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 1141, in _union_schema
    choices.append(self.generate_schema(arg))
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 490, in generate_schema
    schema = self._generate_schema(obj)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 721, in _generate_schema
    schema = self._generate_schema_inner(obj)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 747, in _generate_schema_inner
    return self.match_type(obj)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 834, in match_type
    return self._unknown_type_schema(obj)
  File "R:\Image_Caption_Editor_v6\venv\lib\site-packages\pydantic\_internal\_generate_schema.py", line 393, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.6/u/schema-for-unknown-type
```

**Comment by FurkanGozukara** [comment]
ye fast api broken it 0.111.0 fixes

**Comment by FurkanGozukara** [comment]
https://github.com/fastapi/fastapi/issues/12133

**Comment by glebarez** [comment]
just pin the versions in requirements.txt already ...

**Comment by dwipper** [comment]
Just burned a whole day trying to figure out why my app wouldn't load......grrr

**Comment by dwipper** [comment]
Yes, pinning fastapi==0.112.2 in my requirements.txt for my docker build worked!

**Comment by weipienlee** [comment]
seems to start all the back to 4.0.0 (did random test between that and current version), also not working for me. Seems unlikely that it has been there unnoticed for so many versions, hopefully it's only me and few that have this.

**Comment by abidlabs** [comment]
Thanks everyone for pointing out the issue. PR in the works (and we'll do a release shortly afterwards so that latest version of `gradio` will work for you): https://github.com/gradio-app/gradio/pull/9277

**Comment by FurkanGozukara** [comment]
> Thanks everyone for pointing out the issue. PR in the works (and we'll do a release shortly afterwards so that latest version of `gradio` will work for you): #9277

Latest version gradio is horrible solution. Because latest version would break so many older apps. I think fastapi has to fix the problem

**Comment by abidlabs** [comment]
Yes `fastapi` needs to fix/yank their release, but we have no control over that. For now, please pin an older version of `fastapi` in your older apps or upgrade to the latest version of gradio (once we release it) if possible

**Comment by allanchan339** [comment]
Omg this issue save my day

**Comment by LocNgoXuan23** [comment]
> Yes, pinning fastapi==0.112.2 in requirements.txt for my docker build worked!🥳
tks, for your anwer, it worked for me

**Comment by chiffa** [comment]
confirming here - please ping once the release integrating the fastapi pin is pushed.
