### ISSUE TITLE
CSV sanitization corrupts cached Plotly examples

### ISSUE THREAD

**Issue by sarlinpe** [gradio-app/gradio#9287]
### Describe the bug

When outputting a Plotly plot with negative values, loading the cached example throws an error when deserializing the dict. I traced this down to `gradio.utils.sanitize_value_for_csv`, which prepends the serialized dict with `'`, thereby corrupting it. Adding `gr.utils.sanitize_value_for_csv = lambda v: v` fixes the problem, showing that it comes from the sanitization.

cc @abidlabs who wrote it in https://github.com/gradio-app/gradio/pull/2017

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
import plotly.graph_objects as go

# gr.utils.sanitize_value_for_csv = lambda v: v  # dirty fix

def run(num):
    x = list(range(-5, num))
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=x, y=x))
    return fig

app = gr.Interface(
    fn=run,
    inputs=[
        gr.Radio(
            [10, 20],
            value=10,
            label="Num",
        ),
    ],
    outputs=[
        gr.Plot(label="Plot"),
    ],
    examples=[[10]],
    cache_examples=True,
)

app.launch(share=False)
```

### Logs

```shell
Traceback (most recent call last):
  File ".../python3.10/site-packages/gradio/routes.py", line 789, in predict
    output = await route_utils.call_process_api(
  File ".../python3.10/site-packages/gradio/route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File ".../python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File ".../python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File ".../python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File ".../python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File ".../python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File ".../python3.10/site-packages/gradio/utils.py", line 829, in wrapper
    response = f(*args, **kwargs)
  File ".../python3.10/site-packages/gradio/helpers.py", line 542, in load_example
    ) + self.load_from_cache(example_id)
  File ".../python3.10/site-packages/gradio/helpers.py", line 582, in load_from_cache
    output.append(component.read_from_flag(value_to_use))
  File ".../python3.10/site-packages/gradio/components/base.py", line 356, in read_from_flag
    raise e
  File ".../python3.10/site-packages/gradio/components/base.py", line 352, in read_from_flag
    data = json.loads(payload)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 4.43.0
gradio_client version: 1.3.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 3.7.1
fastapi: 0.112.2
ffmpy: 0.4.0
gradio-client==1.3.0 is not installed.
httpx: 0.24.1
huggingface-hub: 0.24.6
importlib-resources: 6.4.4
jinja2: 3.1.2
markupsafe: 2.1.3
matplotlib: 3.7.2
numpy: 1.25.2
orjson: 3.10.7
packaging: 23.1
pandas: 2.2.2
pillow: 10.0.0
pydantic: 2.7.0
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.1
ruff: 0.6.3
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.5
typing-extensions: 4.11.0
urllib3: 2.0.4
uvicorn: 0.30.6
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2023.6.0
httpx: 0.24.1
huggingface-hub: 0.24.6
packaging: 23.1
typing-extensions: 4.11.0
websockets: 11.0.3
```

### Severity

I can work around it

**Comment by theevildoof** [comment]
Can I work on solving this?

**Comment by Nitish-Kshatriya-P** [comment]
Hey @sarlinpe, if you don't mind I'll get this issue solved within the next 48 hours?

**Comment by ujjwaltwri** [comment]
Hi, I’d like to work on this as a first-time contributor.
I’ll start by reproducing the issue and then propose a fix in sanitize_value_for_csv.
