### ISSUE TITLE
httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

### ISSUE THREAD

**Issue by XinlingWang0628** [gradio-app/gradio#9294]
### Describe the bug

I'm working on a project that uses Gradio as the frontend framework, and I start the application using the launch() function. The project works perfectly when run locally on my computer, but it encounters errors when I try to run it in a Docker image. The docker image created a month ago worked, but not anymore.  Docker link: https://hub.docker.com/repository/docker/xinlingwang/chatbot/general 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

FROM python:3.11-slim
ENV PYTHONUNBUFFERED True
RUN apt-get update && apt-get install -y libpq-dev build-essential
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir gradio
RUN pip install --upgrade certifi
RUN pip install httpcore
RUN pip install httpx
COPY . .
EXPOSE 7860
ENV GRADIO_SERVER_NAME="0.0.0.0"
CMD ["python", "demo/cbioportal_chatbot.py"]

### Logs

```shell
APIConnectionError('Connection error.')Traceback (most recent call last):


  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield


  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 167, in handle_request
    raise UnsupportedProtocol(


httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.



The above exception was the direct cause of the following exception:



Traceback (most recent call last):


  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 962, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():


  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)


  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc


httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.



During handling of the above exception, another exception occurred:



Traceback (most recent call last):


  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield


  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 167, in handle_request
    raise UnsupportedProtocol(


httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.



The above exception was the direct cause of the following exception:



Traceback (most recent call last):


  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 962, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():


  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)


  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc


httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.



During handling of the above exception, another exception occurred:



Traceback (most recent call last):


  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield


  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 167, in handle_request
    raise UnsupportedProtocol(


httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.



The above exception was the direct cause of the following exception:



Traceback (most recent call last):


  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 962, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():


  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)


  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc


httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.



The above exception was the direct cause of the following exception:



Traceback (most recent call last):


  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2505, in invoke
    input = step.invoke(input, config, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3152, in invoke
    output = {key: future.result() for key, future in zip(steps, futures)}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 3152, in <dictcomp>
    output = {key: future.result() for key, future in zip(steps, futures)}
                   ^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception


  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2507, in invoke
    input = step.invoke(input, config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 248, in invoke
    self.generate_prompt(


  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 677, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 534, in generate
    raise e


  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 524, in generate
    self._generate_with_cache(


  File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 749, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 549, in _generate
    response = self.client.create(messages=message_dicts, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 643, in create
    return self._post(
           ^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1250, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 931, in request
    return self._request(
           ^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 986, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1063, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 986, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1063, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^


  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 996, in _request
    raise APIConnectionError(request=request) from err


openai.APIConnectionError: Connection error.
```

### System Info

```shell
langchain-chroma = "==0.1.2"
langchain = "==0.2.6"
langchain-community = "==0.2.6"
langchain-core = "==0.2.10"
langchain-openai = "*"
langchain-text-splitters = "==0.2.2"
gradio = "==4.43.0"
gradio-client = "==1.3.0"
openai = "==1.35.7"
openapi-pydantic = "==0.4.1"
openapi-schema-pydantic = "==1.2.4"
sentence-transformers = "==3.0.1"
python-dotenv = "==1.0.1"
lark = "*"
pymupdf = "*"
beautifulsoup4 = "*"
lxml = "*"
jq = "*"
chromadb = "==0.5.3"
python-dateutil = "*"
pandas = "*"
rank-bm25 = "*"
grandalf = "*"
bravado = "*"
matplotlib-inline = "*"
plotext = "*"
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @XinlingWang0628 from the stack trace, it looks like the issue is related to langchain/openai clients. If you think that this is related to `gradio`, can you please provide a minimal code example that we can use to reproduce the issue above? See: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by abidlabs** [comment]
Can you reproduce the issue with an example that does not include `langchain`? Perhaps by putting a mock response function instead?

**Comment by XinlingWang0628** [comment]
Hi @abidlabs , I figured it out. I had double quote in my api key. Thanks for your help.
