### ISSUE TITLE
AttributeError: 'AsyncRequest' object has no attribute '_json_response_data'

### ISSUE THREAD

**Issue by crazymsn** [gradio-app/gradio#9440]
### Describe the bug

2024-09-23 03:49:48 ERROR Task exception was never retrieved
future: <Task finished name='mq6zww37tt_16' coro=<Queue.process_events() done, defined at /usr/local/lib/python3.11/site-packages/gradio/queueing.py:343> exception=AttributeError("'AsyncRequest' object has no attribute '_json_response_data'")>
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/gradio/queueing.py", line 370, in process_events
while response.json.get("is_generating", False):
^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 538, in json
return self._json_response_data
^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AsyncRequest' object has no attribute '_json_response_data'

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

async def process_events(self, events: list[Event], batch: bool) -> None:
    awake_events: list[Event] = []
    try:
        for event in events:
            client_awake = await self.gather_event_data(event)
            if client_awake:
                client_awake = await self.send_message(
                    event, {"msg": "process_starts"}
                )
            if client_awake:
                awake_events.append(event)
        if not awake_events:
            return
        begin_time = time.time()
        response = await self.call_prediction(awake_events, batch)
        if response.has_exception:
            for event in awake_events:
                await self.send_message(
                    event,
                    {
                        "msg": "process_completed",
                        "output": {"error": str(response.exception)},
                        "success": False,
                    },
                )
        elif response.json.get("is_generating", False):
            old_response = response
            while response.json.get("is_generating", False):

### System Info

```shell
the latest gradio
```

### Severity

I can work around it

**Comment by freddyaboulton** [comment]
Hi @crazymsn can you share the gradio code that triggers this exception?

**Comment by abidlabs** [comment]
Will go ahead and close this for now. Happy to reopen if we have a repro.
