### ISSUE TITLE
Argument of type 'NonType' is not iterable

### ISSUE THREAD

**Issue by hackedpassword** [gradio-app/gradio#9461]
### Describe the bug

The following crash is being extremely difficult. I have a gradio interface script, it worked weeks ago, no longer does. Couldn't tell you what changed. Thus far, attempted:
- removing py 3.12, using 3.10
- reinstalled, now: numpy==1.25.0, diffusers, torch=2.1.2, gradio, gradio_client
- chatgpt troubleshooting, gpt believes it's a code problem, unfortunately I script not code :p
- ..which included a stripped down bare functionality basic gradio script, same behavior
- existing issues touch on this, but appears threads withered from awaiting further info

Hopefully all relevant info is here to solve this issue, else tell me what helps you.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Dies at `image =`
```
        # Generate the image
        with torch.no_grad():
            torch.manual_seed(seed)
            image = pipe(prompt=prompt, num_inference_steps=num_inference_steps, guidance_scale=guidance_scale).images[0]
            image.save(image_path)
            generated_image_paths.append(image_path)
```

### Logs

```shell
0%|                                                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Python310\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Python310\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Python310\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "C:\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "C:\Python310\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "D:\Dev\AI dev\image_gen.py", line 69, in generate_images
    image = pipe(prompt=prompt, num_inference_steps=num_inference_steps, guidance_scale=guidance_scale).images[0]
  File "C:\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Python310\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 1000, in __call__
    noise_pred = self.unet(
  File "C:\Python310\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Python310\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Python310\lib\site-packages\diffusers\models\unets\unet_2d_condition.py", line 1152, in forward
    aug_emb = self.get_aug_embed(
  File "C:\Python310\lib\site-packages\diffusers\models\unets\unet_2d_condition.py", line 969, in get_aug_embed
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable
```
```


### System Info

```shell
AMD CPU, Nvidia (old, no functional cuda)

>pip list
Package             Version
------------------- -----------
accelerate          0.34.2
aiofiles            23.2.1
annotated-types     0.7.0
anyio               4.6.0
certifi             2024.8.30
charset-normalizer  3.3.2
click               8.1.7
colorama            0.4.6
contourpy           1.3.0
cycler              0.12.1
diffusers           0.30.3
exceptiongroup      1.2.2
fastapi             0.115.0
ffmpy               0.4.0
filelock            3.16.1
fonttools           4.54.1
fsspec              2024.9.0
gradio              4.44.0
gradio_client       1.3.0
h11                 0.14.0
httpcore            1.0.5
httpx               0.27.2
huggingface-hub     0.25.1
idna                3.10
importlib_metadata  8.5.0
importlib_resources 6.4.5
Jinja2              3.1.4
kiwisolver          1.4.7
markdown-it-py      3.0.0
MarkupSafe          2.1.5
matplotlib          3.9.2
mdurl               0.1.2
mpmath              1.3.0
networkx            3.3
numpy               1.25.0
orjson              3.10.7
packaging           24.1
pandas              2.2.3
pillow              10.4.0
pip                 22.2.1
psutil              6.0.0
pydantic            2.9.2
pydantic_core       2.23.4
pydub               0.25.1
Pygments            2.18.0
pyparsing           3.1.4
python-dateutil     2.9.0.post0
python-multipart    0.0.10
pytz                2024.2
PyYAML              6.0.2
regex               2024.9.11
requests            2.32.3
rich                13.8.1
ruff                0.6.8
safetensors         0.4.5
semantic-version    2.10.0
setuptools          63.2.0
shellingham         1.5.4
six                 1.16.0
sniffio             1.3.1
starlette           0.38.6
sympy               1.13.3
tokenizers          0.20.0
tomlkit             0.12.0
torch               2.1.2
tqdm                4.66.5
transformers        4.45.1
typer               0.12.5
typing_extensions   4.12.2
tzdata              2024.2
urllib3             2.2.3
uvicorn             0.30.6
websockets          12.0
zipp                3.20.2
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @hackedpassword, thanks for creating the issue, but this seems unrelated to Gradio? From the stacktrace, doesn't it seem like an issue in diffusers?

```
  File "C:\Python310\lib\site-packages\diffusers\models\unets\unet_2d_condition.py", line 969, in get_aug_embed
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by hackedpassword** [comment]
I guess. I re-installed diffusers before, made no difference. Maybe I'll have to regress the version. Dunno. Might post an issue towards diffusers if this persists. Thank for looking!

**Comment by abidlabs** [comment]
No problem!
