### ISSUE TITLE
Broken `gr.Image` and `gr.Video` in gradio lite

### ISSUE THREAD

**Issue by e8035669** [gradio-app/gradio#9475]
### Describe the bug

I am trying gradio in playground. https://www.gradio.app/playground
I found `Sepia Filter` and `Video Identity` examples are not working.

But I can run these example on my local machine.

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

Try `Sepia Filter` and `Video Identity` example in gradio playground.

```python
import numpy as np
import gradio as gr

def sepia(input_img):
    sepia_filter = np.array([
        [0.393, 0.769, 0.189],
        [0.349, 0.686, 0.168],
        [0.272, 0.534, 0.131]
    ])
    sepia_img = input_img.dot(sepia_filter.T)
    sepia_img /= sepia_img.max()
    return sepia_img

demo = gr.Interface(sepia, gr.Image(), "image")
if __name__ == "__main__":
    demo.launch()

```

### Screenshot

![螢幕截圖_20240930_203607](https://github.com/user-attachments/assets/da76c0c6-0201-41d0-b27f-333fd1fa8fe4)

### Logs

```shell
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "<exec>", line 33, in _call_asgi_app_from_js
  File "/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/gradio/routes.py", line 1331, in upload_file
    form = await multipart_parser.parse()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/gradio/route_utils.py", line 651, in parse
    parser.write(chunk)
  File "/lib/python3.12/site-packages/multipart/multipart.py", line 1029, in write
    l = self._internal_write(data, data_len)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/multipart/multipart.py", line 1293, in _internal_write
    i0 = data.find(boundary, i, data_length)
         ^^^^^^^^^
AttributeError: 'memoryview' object has no attribute 'find'

    at new_error (pyodide.asm.js:10:9965)
    at pyodide.asm.wasm:0x16dbfd
    at pyodide.asm.wasm:0x177431
    at _PyEM_TrampolineCall_JS (pyodide.asm.js:10:125894)
    at pyodide.asm.wasm:0x1c2eaf
    at pyodide.asm.wasm:0x2c7c0f
    at pyodide.asm.wasm:0x20a884
    at pyodide.asm.wasm:0x1c359c
    at pyodide.asm.wasm:0x1c38ab
    at pyodide.asm.wasm:0x1c3929
    at pyodide.asm.wasm:0x29e95d
    at pyodide.asm.wasm:0x2a4f54
    at pyodide.asm.wasm:0x1c3a69
    at pyodide.asm.wasm:0x1c36d2
    at pyodide.asm.wasm:0x176a95
    at callPyObjectKwargs (pyodide.asm.js:10:64068)
    at Module.callPyObjectMaybePromising (pyodide.asm.js:10:65316)
    at wrapper (pyodide.asm.js:10:27006)
    at Cn.e.port1.onmessage (pyodide.asm.js:10:102154)
```

### System Info

```shell
I am using gradio playground.
Google Chrome: 129.0.6668.58
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
Hi @e8035669, this has been fixed in the v5 version of Lite, which should be out next week. In the meantime, you can take a look [here](https://5-0-dev.gradio-website.pages.dev/playground?demo=Hello_World&code=aW1wb3J0IG51bXB5IGFzIG5wCmltcG9ydCBncmFkaW8gYXMgZ3IKCmRlZiBzZXBpYShpbnB1dF9pbWcpOgogICAgc2VwaWFfZmlsdGVyID0gbnAuYXJyYXkoWwogICAgICAgIFswLjM5MywgMC43NjksIDAuMTg5XSwKICAgICAgICBbMC4zNDksIDAuNjg2LCAwLjE2OF0sCiAgICAgICAgWzAuMjcyLCAwLjUzNCwgMC4xMzFdCiAgICBdKQogICAgc2VwaWFfaW1nID0gaW5wdXRfaW1nLmRvdChzZXBpYV9maWx0ZXIuVCkKICAgIHNlcGlhX2ltZyAvPSBzZXBpYV9pbWcubWF4KCkKICAgIHJldHVybiBzZXBpYV9pbWcKCmRlbW8gPSBnci5JbnRlcmZhY2Uoc2VwaWEsIGdyLkltYWdlKCksICJpbWFnZSIpCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICBkZW1vLmxhdW5jaCgpCg==)

**Comment by abidlabs** [comment]
Btw Cloudflare is triggering a phishing alert, but its a false alert

**Comment by e8035669** [comment]
Thanks, it's great
