### ISSUE TITLE
Centralized state management won't work

### ISSUE THREAD

**Issue by Cynwell** [gradio-app/gradio#9502]
### Describe the bug

I'm testing the concept of centralized state management on Gradio. My idea is to have a dictionary storing the states. When needed, `gr.State` objects will be referenced to fill in the `inputs=[...]` and `outputs=[...]` in function calls to subscribe and update states correspondingly.

Here's the original version that worked fine:
```python
import gradio as gr

def identity(x, state):
    state += 1
    return x, state, state

with gr.Blocks() as demo:
    slider = gr.Slider(0, 100, step=0.1)
    state = gr.State(value=0)
    with gr.Row():
        number = gr.Number(label="On release")
        number2 = gr.Number(label="Number of events fired")
    slider.release(identity, inputs=[slider, state], outputs=[number, state, number2], api_name="predict")

if __name__ == "__main__":
    print("here")
    demo.launch()
    print(demo.server_port)
```

Here's the modified version that uses centralized state management with `dict`, which doesn't work:
```python
import gradio as gr

def identity(x, state):
    state += 1
    return x, state, state

state_dict = {
  "state": gr.State(value=0)
}

with gr.Blocks() as demo:
    slider = gr.Slider(0, 100, step=0.1)
    state = state_dict["state"]
    with gr.Row():
        number = gr.Number(label="On release")
        number2 = gr.Number(label="Number of events fired")
    slider.release(identity, inputs=[slider, state], outputs=[number, state, number2], api_name="predict")

if __name__ == "__main__":
    print("here")
    demo.launch()
    print(demo.server_port)
```

The motivation is that I'd like to modularize components, while components could share states via a centralized state manager. Imagine a case where there are two components and has 3 variables each, to share states among the two components, using a centralized state management approach can reduce the dependencies between two components rather than finding ways to pass states among components. This problem become an critical issue as the number of components increase, the number of connections among components increases exponentially. A centralized state management would be an effective approach to solve the scalability issue.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

def identity(x, state):
    state += 1
    return x, state, state

state_dict = {
  "state": gr.State(value=0)
}

with gr.Blocks() as demo:
    slider = gr.Slider(0, 100, step=0.1)
    state = state_dict["state"]
    with gr.Row():
        number = gr.Number(label="On release")
        number2 = gr.Number(label="Number of events fired")
    slider.release(identity, inputs=[slider, state], outputs=[number, state, number2], api_name="predict")

if __name__ == "__main__":
    print("here")
    demo.launch()
    print(demo.server_port)
```

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\env\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\env\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\env\Lib\site-packages\gradio\blocks.py", line 1931, in process_api
    inputs = await self.preprocess_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\env\Lib\site-packages\gradio\blocks.py", line 1648, in preprocess_data
    processed_input.append(state[block._id])
                           ~~~~~^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\env\Lib\site-packages\gradio\state_holder.py", line 82, in __getitem__
    block = self.blocks_config.blocks[key]
            ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 0
```

### System Info

```shell
gradio==4.44.0
```

### Severity

Blocking usage of gradio

**Comment by abidlabs** [comment]
Hi @Cynwell the issue is that all components, including `gr.State` that are used in a `gr.Blocks` app must be defined inside of that `gr.Blocks` app. For example, this works:

```py
import gradio as gr

def identity(x, state):
    state += 1
    return x, state, state

with gr.Blocks() as demo:
    state_dict = {
      "state": gr.State(value=0)
    }
    
    slider = gr.Slider(0, 100, step=0.1)
    state = state_dict["state"]
    with gr.Row():
        number = gr.Number(label="On release")
        number2 = gr.Number(label="Number of events fired")
    slider.release(identity, inputs=[slider, state], outputs=[number, state, number2], api_name="predict")

if __name__ == "__main__":
    demo.launch()
```

I'll go ahead and close this, but let us know if this doesn't work for you for any reason
