### ISSUE TITLE
ImportError: cannot import name 'GetCoreSchemaHandler' from 'pydantic'

### ISSUE THREAD

**Issue by PabloVD** [gradio-app/gradio#9870]
### Describe the bug

Cannot import gradio, I get the error:
`ImportError: cannot import name 'GetCoreSchemaHandler' from 'pydantic'`

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
```

### Logs

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import Component, FormComponent
  File "/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/gradio/components/annotated_image.py", line 13, in <module>
    from gradio import processing_utils, utils
  File "/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/gradio/processing_utils.py", line 22, in <module>
    from gradio import utils, wasm_utils
  File "/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/gradio/utils.py", line 58, in <module>
    from gradio.data_classes import (
  File "/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/gradio/data_classes.py", line 26, in <module>
    from pydantic import (
ImportError: cannot import name 'GetCoreSchemaHandler' from 'pydantic' (/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/pydantic/__init__.cpython-38-x86_64-linux-gnu.so)
```
```


### System Info

```shell
gradio==4.44.1
gradio_client==1.3.0
pydantic==1.9.0
pydantic_core==2.0.1

When running `gradio environment` I get the same:

Traceback (most recent call last):
  File "/home/tda/miniconda3/envs/rag/bin/gradio", line 5, in <module>
    from gradio.cli import cli
  File "/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import Component, FormComponent
  File "/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/gradio/components/annotated_image.py", line 13, in <module>
    from gradio import processing_utils, utils
  File "/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/gradio/processing_utils.py", line 22, in <module>
    from gradio import utils, wasm_utils
  File "/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/gradio/utils.py", line 58, in <module>
    from gradio.data_classes import (
  File "/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/gradio/data_classes.py", line 26, in <module>
    from pydantic import (
ImportError: cannot import name 'GetCoreSchemaHandler' from 'pydantic' (/home/tda/miniconda3/envs/rag/lib/python3.8/site-packages/pydantic/__init__.cpython-38-x86_64-linux-gnu.so)
```
```


### Severity

Blocking usage of gradio

**Comment by freddyaboulton** [comment]
Can you please reinstall pydantic? Any of the recent 2.x versions should work. I just tried with 2.9.2

**Comment by PabloVD** [comment]
It worked, thanks!

**Comment by usman61** [comment]
I am also getting the same error **cannot import name 'GetCoreSchemaHandler' from 'pydantic'** 
while using presidio-anlyzer for anonymization in my databricks python notebooks.
surprisingly it works on my local machine but getting the conflict issues in databricks environment.
