### ISSUE TITLE
Parameter passing of button.click()

### ISSUE THREAD

**Issue by Semper4u** [gradio-app/gradio#9876]
### Describe the bug

When using `button.click(fn=..., inputs=[],...)`, if the input parameter is a button component, the type of the component will change after being passed to the fn target function.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr  
  
def setup_feedback_buttons(like_btn: gr.Button, dislike_btn: gr.Button):  
    print(f"Before setting visible: like_btn.visible = {like_btn.visible}, dislike_btn.visible = {dislike_btn.visible}")  
    like_btn.visible = True  
    dislike_btn.visible = True    
  
with gr.Blocks() as demo:  
  
    like_btn = gr.Button("Like", visible=False)  
    dislike_btn = gr.Button("Dislike", visible=False)  
    submit_btn = gr.Button("Submit")  
  
    submit_btn.click(fn=setup_feedback_buttons, inputs=[like_btn, dislike_btn], outputs=None)   
  
demo.launch(debug=True)

```

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "<ipython-input-4-ce9f8f625052>", line 4, in setup_feedback_buttons
    print(f"Before setting visible: like_btn.visible = {like_btn.visible}, dislike_btn.visible = {dislike_btn.visible}")
AttributeError: 'str' object has no attribute 'visible'
```

### System Info

```shell
Package            Version
------------------ -----------
aiofiles           23.2.1
annotated-types    0.7.0
anyio              4.6.2.post1
Brotli             1.1.0
certifi            2024.8.30
cffi               1.17.1
charset-normalizer 3.4.0
click              8.1.7
colorama           0.4.6
contourpy          1.3.0
cycler             0.12.1
dnspython          2.7.0
email_validator    2.2.0
exceptiongroup     1.2.2
fastapi            0.115.4
fastapi-cli        0.0.5
ffmpy              0.3.0
filelock           3.16.1
fonttools          4.54.1
fsspec             2024.10.0
gradio             5.1.0
gradio_client      1.4.0
h11                0.14.0
h2                 4.1.0
hpack              4.0.0
httpcore           1.0.6
httptools          0.6.1
httpx              0.27.2
huggingface_hub    0.26.2
hyperframe         6.0.1
idna               3.10
Jinja2             3.1.4
kiwisolver         1.4.7
markdown-it-py     3.0.0
MarkupSafe         2.1.5
matplotlib         3.9.2
mdurl              0.1.2
numpy              2.1.2
orjson             3.10.10
packaging          24.1
pandas             2.2.3
pillow             10.2.0
pip                24.3.1
pycparser          2.22
pydantic           2.0.3
pydantic_core      2.3.0
pydub              0.25.1
Pygments           2.18.0
pyparsing          3.2.0
PySocks            1.7.1
python-dateutil    2.9.0
python-dotenv      1.0.1
python-multipart   0.0.16
pytz               2024.1
PyYAML             6.0.2
requests           2.32.3
rich               13.9.3
ruff               0.7.1
semantic-version   2.10.0
setuptools         75.1.0
shellingham        1.5.4
six                1.16.0
sniffio            1.3.1
starlette          0.41.2
tomlkit            0.12.0
tqdm               4.66.6
typer              0.12.5
typer-slim         0.12.5
typing_extensions  4.12.2
tzdata             2024.2
unicodedata2       15.1.0
urllib3            2.2.3
uvicorn            0.32.0
uvloop             0.21.0
watchfiles         0.24.0
websockets         12.0
wheel              0.44.0
zstandard          0.23.0


I tried using multiple different versions of python(3.10,3.11,3.12,3.13) and gradio(4.44,4.44.1,5.4) on Ubuntu 18.04 and Ubuntu 22.04, and all got the same error
```

### Severity

I can work around it

**Comment by CISC** [comment]
You've misunderstood how `inputs` work, you never get the original component, but rather some value of it, in the case of buttons you will get the [label](https://www.gradio.app/docs/gradio/button#behavior).

To change the properties of a component you have to set them as `outputs` and return a new component with the properties you wish to change set, see [here](https://www.gradio.app/guides/blocks-and-event-listeners#updating-component-configurations).

**Comment by freddyaboulton** [comment]
Thank you @CISC ! @Semper4u, @CISC 's suggestion is the proper way to update components!

**Comment by Semper4u** [comment]
Thanks a lot, I get it.
