### ISSUE TITLE
Lazy cache doesn't work in `gr.ChatInterface`

### ISSUE THREAD

**Issue by hysts** [gradio-app/gradio#9981]
### Describe the bug

When setting `cache_examples=True, cache_mode="lazy"` in `gr.ChatInterface`, clicking an example leads to an error.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

repro space: https://huggingface.co/spaces/hysts-debug/gradio-ChatInterface-lazy-cache

```python
import gradio as gr


def fn(message, history):
    return message


gr.ChatInterface(
    fn=fn,
    cache_examples=True,
    cache_mode="lazy",
    examples=[["hey"], ["hello"]],
    type="messages",
).launch()
```

### Logs

```shell
===== Application Startup at 2024-11-18 09:00:28 =====

Will cache examples in '/home/user/app/.gradio/cached_examples/9' directory at first use. 


* Running on local URL:  http://0.0.0.0:7860, with SSR ⚡

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 2015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/site-packages/gradio/blocks.py", line 1562, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/gradio/utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/gradio/chat_interface.py", line 689, in example_clicked
    return self.examples_handler.load_from_cache(x.index)[0].root
  File "/usr/local/lib/python3.10/site-packages/gradio/helpers.py", line 577, in load_from_cache
    with open(self.cached_file, encoding="utf-8") as cache:
FileNotFoundError: [Errno 2] No such file or directory: '.gradio/cached_examples/9/log.csv'
```

### System Info

```shell
gradio==5.6.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
https://github.com/gradio-app/gradio/pull/9990 will fix the eager caching bug, but not lazy caching since its not easily supported right now. But at least the error will go away (but no caching will occur)
